### ISSUE TITLE
Error while installing requirements.txt

### ISSUE THREAD

**Issue by atulyakhatri** [elebumm/RedditVideoMakerBot#1]
There is an error while installing the requirements.txt file using command `pip install -r requirements.txt`.
It is showing something like this 
```
Processing d:\appleinternal\buildroot\library\caches\com.apple.xbs\sources\pytho
n3\python3-110\six-1.15.0-py2.py3-none-any.whl
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or d
irectory: '\\AppleInternal\\BuildRoot\\Library\\Caches\\com.apple.xbs\\Sources\\
python3\\python3-110\\six-1.15.0-py2.py3-none-any.whl'
```

I am currently on Windows and using python 3.8.
Hope you fix it

**Comment by elebumm** [comment]
Try pulling the latest version. I made a fix!

The version of `six` was directing it to a local version on my computer rather than grabbing it from the `pip` repository. Should work now!

**Comment by 8xu** [comment]
Here you go, @elebumm !
![image](https://user-images.githubusercontent.com/45739184/171285923-d15a43f6-ae11-4578-ac75-84e96661af13.png)

**Comment by plgonzalezrx8** [comment]
I'm getting similar errors as well.

**Comment by plgonzalezrx8** [comment]
Tried on my Linux machine as well, and I get similar results, for some reason packages are not installing properly and I can't figure out what the problem might be. Posting a screenshot below.

**Comment by plgonzalezrx8** [comment]
![Screenshot 2022-05-31 195601](https://user-images.githubusercontent.com/19900049/171307088-00333da5-f5fe-471f-9a84-28e6a29af50b.png)
![Screenshot 2022-05-31 195534](https://user-images.githubusercontent.com/19900049/171307090-1e2f3f1d-b1ee-40db-9324-d1d47a7fea06.png)

**Comment by plgonzalezrx8** [comment]
And this is on my windows computer.

![Screenshot 2022-05-31 195743](https://user-images.githubusercontent.com/19900049/171307239-ba7f77cb-5f46-44ab-9dda-655bd4f135ae.png)
![Screenshot 2022-05-31 195729](https://user-images.githubusercontent.com/19900049/171307241-6bf14d44-6c27-4777-ae7e-326ac078339f.png)

**Comment by Bango88** [comment]
On my linux machine after changing the requirement to `typed-ast==1.5.4` it installs successfully.

**Comment by 8xu** [comment]
I will try making a PR when I fix it. ✨

**Comment by atulyakhatri** [comment]
I think it's fixed, so I am closing it @elebumm  :+1:
