### ISSUE TITLE
Crashing while Creating the final video

### ISSUE THREAD

**Issue by Proton45** [elebumm/RedditVideoMakerBot#10]
While creating the final video it crashed and I'm not sure what happened. Everything else has worked so far, except for this. Does anyone know a solution or atleast what went wrong and why? 

┌─────────────────────────────────────────────────────────────────────────────┐
│ Creating the final video 🎥                                                 
└─────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "C:\RedditVideoMakerBot\main.py", line 22, in <module>
    final_video = make_final_video(number_of_comments)
  File "C:\RedditVideoMakerBot\video_creation\final_video.py", line 22, in make_final_video
    VideoFileClip("assets/mp4/clip.mp4")
  File "C:\Users\Anwender\anaconda3\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "C:\Users\Anwender\anaconda3\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 37, in __init__
    self.fps = infos['video_fps']
KeyError: 'video_fps'

**Comment by elebumm** [comment]
Are you able to see if the `clip.mp4` is there? I am wondering if it failed to generate.

**Comment by Proton45** [comment]
> 



> Are you able to see if the `clip.mp4` is there? I am wondering if it failed to generate.

What exactly do you mean? Where should I look for it? Because to me, it looks like it breaks while trying to create the final video. Everything else runs just fine, except for this.

**Comment by Proton45** [comment]
> Are you able to see if the `clip.mp4` is there? I am wondering if it failed to generate.

hmm it seems to have solved itself after reinstalling.. 

but I have another question/problem. Cromium always tries to use an incognito tab to get to the reddit website. This results in the white mode (which I don't want, dark mode is easier on the eyes) and reddit continues to ask for cookies, which results in the cookie window being placed over the comments in the screenshots. Do you have an idea on how to get chromium to not use an incognito tab
![comment_2](https://user-images.githubusercontent.com/106629851/171451935-4560c070-d54d-4370-9ba5-2af4ba577e17.png)
?

**Comment by elebumm** [comment]
Awesome! Glad to see :) Are you able to create a new issue for this?
