### ISSUE TITLE
Cromium incognito tab and normal tab  

### ISSUE THREAD

**Issue by Proton45** [elebumm/RedditVideoMakerBot#100]
Cromium is the headless browser that is used to get the screenshots of the reddit thread. Cromium always tries to use an incognito tab to get to the reddit website. This results in the white mode (which I don't want; dark mode is easier on the eyes) and reddit continues to ask for cookies, which results in the cookie window being placed over the comments in the screenshots. Does anyone have an idea on how to get chromium to not use an incognito tab and instead use a normal tab? Maybe we could even implement this into the project?
![comment_2](https://user-images.githubusercontent.com/106629851/171476711-9b9d608f-f027-43a5-8974-510521fa278d.png)

**Comment by lothaen20** [comment]
You can solve the cookies issue by referring to #39

**Comment by Proton45** [comment]
> You can solve the cookies issue by referring to #39

Thanks. I already solved this issue yesterday using #39. I just forgot to close this issue. Thanks again
