### ISSUE TITLE
 every time i run bot it gives same error raise IOError(("MoviePy error: failed to read the first frame of "

### ISSUE THREAD

**Issue by electro199** [elebumm/RedditVideoMakerBot#1002]
when  I run the bot it  give error  i thing  some thing is wrong with the background maker may be it is creating corupted file 
`Moviepy - Running:
>>> "+ " ".join(cmd)
Moviepy - Command successful
Background video chopped successfully!
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Creating the final video 🎥                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "J:\New folder\RedditVideoMakerBot-master\main.py", line 65, in <module>
    run_many(config["settings"]["times_to_run"])
  File "J:\New folder\RedditVideoMakerBot-master\main.py", line 56, in run_many
    main()
  File "J:\New folder\RedditVideoMakerBot-master\main.py", line 48, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "J:\New folder\RedditVideoMakerBot-master\video_creation\final_video.py", line 68, in make_final_video
    VideoFileClip("assets/temp/background.mp4")
  File "C:\Users\AA DIGITAL\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "C:\Users\AA DIGITAL\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 73, in __init__
    self.lastread = self.read_frame()
  File "C:\Users\AA DIGITAL\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 133, in read_frame
    raise IOError(("MoviePy error: failed to read the first frame of "
OSError: MoviePy error: failed to read the first frame of video file assets/temp/background.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.

(venv) J:\New folder\RedditVideoMakerBot-master>`
![15 07 2022_18 38 45_REC](https://user-images.githubusercontent.com/109358640/179235492-3cb83492-0ff9-4e1f-b466-15c30ace1609.png)
also the  background.mp4 is only 3 sec long  and it is not opening
![15 07 2022_18 40 08_REC](https://user-images.githubusercontent.com/109358640/179235480-20c35920-b625-41cf-a02a-bf63f7c14c1c.png)

**To Reproduce**

the bot is freshly downloaded no modification

**Comment by KPGNED** [comment]
delete the Config.toml file... then you need to re-select everything but hopefully it works

**Comment by DaniRuzsa** [comment]
Same error here and did delete config and no change

**Comment by DaniRuzsa** [comment]
fixed idk what was the problem but deleted all the files and downloaded again and now works

**Comment by electro199** [comment]
I have redownloaded the clone and it is running well now 
but i thing the problem is in some post or may be some glitch
