### ISSUE TITLE
No text to send to TTS API

### ISSUE THREAD

**Issue by ZainGamer7876** [elebumm/RedditVideoMakerBot#1005]
Error just says this after running main.py:
PS C:\Users\zaina\RedditVideoMakerBot> python main.py
Using United Kingdom server backend.

██████╗ ███████╗██████╗ ██████╗ ██╗████████╗    ██╗   ██╗██╗██████╗ ███████╗ ██████╗     ███╗   ███╗ █████╗ ██╗  ██╗███████╗██████╗
██╔══██╗██╔════╝██╔══██╗██╔══██╗██║╚══██╔══╝    ██║   ██║██║██╔══██╗██╔════╝██╔═══██╗    ████╗ ████║██╔══██╗██║ ██╔╝██╔════╝██╔══██╗
██████╔╝█████╗  ██║  ██║██║  ██║██║   ██║       ██║   ██║██║██║  ██║█████╗  ██║   ██║    ██╔████╔██║███████║█████╔╝ █████╗  ██████╔╝
██╔══██╗██╔══╝  ██║  ██║██║  ██║██║   ██║       ╚██╗ ██╔╝██║██║  ██║██╔══╝  ██║   ██║    ██║╚██╔╝██║██╔══██║██╔═██╗ ██╔══╝  ██╔══██╗
██║  ██║███████╗██████╔╝██████╔╝██║   ██║        ╚████╔╝ ██║██████╔╝███████╗╚██████╔╝    ██║ ╚═╝ ██║██║  ██║██║  ██╗███████╗██║  ██║
╚═╝  ╚═╝╚══════╝╚═════╝ ╚═════╝ ╚═╝   ╚═╝         ╚═══╝  ╚═╝╚═════╝ ╚══════╝ ╚═════╝     ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

  Thanks for using this tool! Feel free to contribute to this project on GitHub! If you have any questions, feel free
     to reach out to me on Twitter or submit a GitHub issue. You can find solutions to many common problems in the
                                                     Documentation

╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ You are using v2.3 of the bot                                                                                        │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯###############################
#                             #
# Checking TOML configuration #
#                             #
###############################
If you see any prompts, that means that you have unset/incorrectly set variables, please input the correct values.
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ on the 1st iteration of 1                                                                                            │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Logging into Reddit.
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ Getting subreddit threads...                                                                                         │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Using subreddit: r/minecraft from TOML config
This post was pinned by moderators. Skipping...
This post was pinned by moderators. Skipping...
Video will be: why can't i spawn the wither? i'm on hard difficulty. 👍
Thread has 6577 upvotes
Thread has a upvote ratio of 97.0%
Thread has 288 comments
Received subreddit threads Successfully.
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ Saving Text to MP3 files...                                                                                          │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Translating Text...
Saving... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   Translating Text...
Saving... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   Translating Text...
Saving... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Traceback (most recent call last):
  File "C:\Users\zaina\RedditVideoMakerBot\main.py", line 65, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\zaina\RedditVideoMakerBot\main.py", line 56, in run_many
    main()
  File "C:\Users\zaina\RedditVideoMakerBot\main.py", line 42, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\zaina\RedditVideoMakerBot\video_creation\voices.py", line 48, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\zaina\RedditVideoMakerBot\TTS\engine_wrapper.py", line 73, in run
    self.split_post(comment["comment_body"], idx)  # Split the comment
  File "C:\Users\zaina\RedditVideoMakerBot\TTS\engine_wrapper.py", line 95, in split_post
    self.call_tts(f"{idx}-{idy - offset}.part", text_cut)
  File "C:\Users\zaina\RedditVideoMakerBot\TTS\engine_wrapper.py", line 113, in call_tts
    self.tts_module.run(text=process_text(text), filepath=f"{self.path}/{filename}.mp3")
  File "C:\Users\zaina\RedditVideoMakerBot\TTS\GTTS.py", line 20, in run
    tts.save(filepath)
  File "C:\Users\zaina\AppData\Local\Programs\Python\Python310\lib\site-packages\gtts\tts.py", line 329, in save
    self.write_to_fp(f)
  File "C:\Users\zaina\AppData\Local\Programs\Python\Python310\lib\site-packages\gtts\tts.py", line 310, in write_to_fp
    for idx, decoded in enumerate(self.stream()):
  File "C:\Users\zaina\AppData\Local\Programs\Python\Python310\lib\site-packages\gtts\tts.py", line 260, in stream
    prepared_requests = self._prepare_requests()
  File "C:\Users\zaina\AppData\Local\Programs\Python\Python310\lib\site-packages\gtts\tts.py", line 209, in _prepare_requests
    assert text_parts, "No text to send to TTS API"
AssertionError: No text to send to TTS API

**Comment by micziz** [comment]
The reddit api cloud not get the text in comments/title

**Comment by JasonLovesDoggo** [comment]
Related to #1006 they will be fixed at the same time
