### ISSUE TITLE
Feature Request: Allow us to use more than one instance at a time

### ISSUE THREAD

**Issue by ibby55** [elebumm/RedditVideoMakerBot#1007]
title is self explanatory. currently, bot can only make 1 video at a time, and u have to type in the command again to start creating a new video.

**Comment by micziz** [comment]
If you would like to do it, you cloud add a while loop to do videos infinitely. If you are talking about multithreading, moviepy does not support it. I might make a pull request.

**Comment by Anvilator-web** [comment]
But you could try using multiple terminal windows.
However, performance may plummet.

**Comment by JasonLovesDoggo** [comment]
Sulution: get some popcorn and set times_to_run to however many you want
