### ISSUE TITLE
At the end crashes 

### ISSUE THREAD

**Issue by Guffy31** [elebumm/RedditVideoMakerBot#1008]
When is doing a specific thred at the it crashes, for it does it whit "Without saying the name, what's your favorite video game?" thats the one that makes it crash at the end.
![Captura de pantalla 2022-07-15 235345](https://user-images.githubusercontent.com/109401612/179338407-57f042f6-e381-4d1a-a1ce-36290cfdab3a.png)

**Comment by LiamGallagher737** [comment]
I'm also getting the same error and only on that reddit thread #1006

**Comment by micziz** [comment]
A response is in #1006

**Comment by JasonLovesDoggo** [comment]
Duplicate of #1006
