### ISSUE TITLE
Invalid_grant error processing request

### ISSUE THREAD

**Issue by MoiEtMoiPuisMoi** [elebumm/RedditVideoMakerBot#101]
![Screenshot_2](https://user-images.githubusercontent.com/56231137/171476817-72f35703-476b-4dad-8b94-0210a7013f91.png)

I got a "invalid_grant error processing request" when i start my script
I created my app at a script and fille REDDIT_USERNAME and REDDIT_PASSWORD with my account password and username.

**Comment by lesterrar** [comment]
check the API keys

**Comment by MoiEtMoiPuisMoi** [comment]
API keys are done

**Comment by MoiEtMoiPuisMoi** [comment]
I have the impression that the error comes from the REDDIT_USERNAME and REDDIT_PASSWORD because when I modify the client_id it gives me a 401 error
