### ISSUE TITLE
IDEA: Add space inbetween lines if line break

### ISSUE THREAD

**Issue by RocketNinja15** [elebumm/RedditVideoMakerBot#1010]
**Is your feature request related to a problem? Please describe.**

When ever there is a line break, the TTS ignores it and makes the words combined together.

 EX:

"Hey How are you?"

"Im doing well thank, you!"

"Great" 
Sounds like
Hey How are you?Im doing well thank you!Great!

**Describe the solution you'd like**
Add a space or more extended break when sending to TTS

**Comment by JasonLovesDoggo** [comment]
Can you provide an example of text that you would want it to sound like?

**Comment by RocketNinja15** [comment]
> Can you provide an example of text that you would want it to sound like?

Yea! Lemme send some errors in the videos I think you'll hear it:

https://user-images.githubusercontent.com/50027436/179897938-b39d2172-6e27-4c51-a25c-7ec4158be8f9.mp4


https://user-images.githubusercontent.com/50027436/179897943-182e55ef-9369-4050-8e60-ca2b6d327c94.mp4


https://user-images.githubusercontent.com/50027436/179897952-e2a028ae-c824-4235-b053-2af1eb508f68.mp4

<img width="391" alt="Screen Shot 2022-07-19 at 9 34 54 PM" src="https://user-images.githubusercontent.com/50027436/179897957-f4ff7397-7cb5-4f39-a67f-b2443df271ae.png">

**Comment by Drugsosos** [comment]
There is new text_split function in my PR.
Try using it for now
https://github.com/Drugsosos/RedditVideoMakerBot/tree/move-to-async-webdriver

**Comment by RocketNinja15** [comment]
> There is new text_split function in my PR. Try using it for now https://github.com/Drugsosos/RedditVideoMakerBot/tree/move-to-async-webdriver

sounds good, i will try as soon as i can!

**Comment by Drugsosos** [comment]
@RocketNinja15 
Sorry, I was mistaken. It's not fixed there. I'll open PR with the fix later.

You still can try that branch tho, there are lots of interesting improvements 😉

**Comment by OpenSourceSimon** [comment]
Fixed
