### ISSUE TITLE
ADD: A stop command

### ISSUE THREAD

**Issue by mikkoxs** [elebumm/RedditVideoMakerBot#1011]
I think it would be a great idea to add a command to stop the program instead of using Cntrl+C or closing the application as this may course the temp files to not get deleted correctly etc.

**Comment by CordlessCoder** [comment]
> I think it would be a great idea to add a command to stop the program instead of using Cntrl+C or closing the application as this may course the temp files to not get deleted correctly etc.
Ctrl+C is already the stop command and no, it can't cause that.
https://github.com/elebumm/RedditVideoMakerBot/blob/2cfd20b566445dfc682726e57583d1a2492bd614/main.py#L77

**Comment by JasonLovesDoggo** [comment]
exactly what cordless coder linked and
Besides temp files also get deleted on start
