### ISSUE TITLE
Is there a way for the bot to read only top sorted comment section.

### ISSUE THREAD

**Issue by manmohanhunjan** [elebumm/RedditVideoMakerBot#1013]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered** (optional)

**Additional context** (optional)

**Comment by JasonLovesDoggo** [comment]
Yes. You would Just change the code to sorting from hot to top

**Comment by micziz** [comment]
Yes, probably yes

**Comment by rastogiujj12** [comment]
find where it says `threads = subreddit.hot(limit=25)` change it to `threads = subreddit.top()`
