### ISSUE TITLE
First Screenshot is Grayed 

### ISSUE THREAD

**Issue by msharique8** [elebumm/RedditVideoMakerBot#1016]
For every video I generate the first screenshot is grayed like the one attached. Did anyone face a similar issue.
![title](https://user-images.githubusercontent.com/35597242/179364311-5d37c46d-967b-4faa-bd2b-2ffc38a3d1c3.png)

**Comment by JasonLovesDoggo** [comment]
Try using @Drugsosos 's version is that uses a different web driver
https://github.com/Drugsosos/RedditVideoMakerBot/tree/move-to-async-webdriver

I don't believe anybody else has had this issue though

**Comment by msharique8** [comment]
Takin the title screenshot at the end instead of the beginning solved the issue. Also I'm using firefiox as headless browser because the chromium one just keeps crashing for me.
