### ISSUE TITLE
A feature to do stories like r/storytime

### ISSUE THREAD

**Issue by MinoaBaccus** [elebumm/RedditVideoMakerBot#1017]
I want to make Reddit videos that are Story's and not questions and I can't do this because I can't turn off the comment limit and the TTS doesn't read the body of a post, I don't know what story mode even dose I turn it on nothing changes.

**Comment by MinoaBaccus** [comment]
I don't know if I'm an idiot or if this is not a feature.

**Comment by JasonLovesDoggo** [comment]
It's called storymode and it's in development
