### ISSUE TITLE
Add more than one subreddit

### ISSUE THREAD

**Issue by MinoaBaccus** [elebumm/RedditVideoMakerBot#1020]
Make it so you can add more than 1 Subreddit at a time, and it will ever go in a random order or in a pattern.

**Comment by JasonLovesDoggo** [comment]
You can... Just split the subreddits with a plus

**Comment by MinoaBaccus** [comment]
Like this?
subreddit = "Horror_stories+nosleep+tifu+offmychest+TrueOffMyChest"

**Comment by JasonLovesDoggo** [comment]
> Like this?
> subreddit = "Horror_stories+nosleep+tifu+offmychest+TrueOffMyChest"

Exactly

**Comment by MinoaBaccus** [comment]
It dosent work

**Comment by lamasterso** [comment]
more than one subreddit does not work, The bot suggests an example and even if you copy-paste that example onto the setup it still asks that it is wrong, are you sure it is right? it says, then if you choose yes I am sure, it does not work.

tested this with any variations possible, so it is a clear bug in the script and, not a typo error.
