### ISSUE TITLE
An option to select the second 60s chunk of a reddit post

### ISSUE THREAD

**Issue by thefinaloneg** [elebumm/RedditVideoMakerBot#1021]
Many times when a TTS bot or person reads out a reddit post, it/they will read out the top x posts. However, this almost always makes it so if more than one person selects the same post, the person watching the content will have heard the exact same thing before. My proposal is to allow users to select an option that calculates how many seconds each post takes, and ignore the first 60s of posts, then draw from the second 60s in order to get organic content from the same post. 

I'm here just to get feedback towards this idea, as I'm considering creating a PR for this.

**Comment by rastogiujj12** [comment]
it doesn't take the first, it takes the hot comments and hot comments changes over time.

**Comment by JasonLovesDoggo** [comment]
Exactly what @rastogiujj12 said Plus this wouldn't be viable for smaller posts
