### ISSUE TITLE
When running the program it doesn't find text to translate

### ISSUE THREAD

**Issue by MCholden** [elebumm/RedditVideoMakerBot#1022]
\RedditVideoMakerBot\TTS\streamlabs_polly.py", line 46, in run
    voice_data = requests.get(response.json()["speak_url"])
KeyError: 'speak_url'

Crashes the program, but only applies to this post. Everything was working fine before.

**Comment by JasonLovesDoggo** [comment]
Update the bot

**Comment by MCholden** [comment]
> Update the bot

I'm new to github, how would I go about that?

**Comment by JasonLovesDoggo** [comment]
Download the latest release
