### ISSUE TITLE
Sometimes the bot crashes because the file name is to long.

### ISSUE THREAD

**Issue by DrakonWarrior** [elebumm/RedditVideoMakerBot#1024]
![Screenshot from 2022-07-17 17-41-07](https://user-images.githubusercontent.com/75917187/179425836-77e7f2c9-4055-4243-b3bf-b8b7ad66e943.png)
That is the error I keep getting, to replicate it just run the bot enough times on a subreddit that usually has long post titles and you will get it. I believe a simple fix would to add some sort of character limit to the titles. I tried messing around a bit, but I am fairly new to python, and although the code works by itself, I cannot figure out how to make it work in final_video.py, which is where I believe the fix should be implemented. The code I was trying to implement was
`lenf = 32 - len(str(filename))
 fname = filename
 for i in range(lenf):
       fname = data.rstrip(fname[-1])`
but I could not figure out how to add it without getting errors.

**Comment by JasonLovesDoggo** [comment]
Pretty sure this has been fixed in the develop branch and see #1025
