### ISSUE TITLE
Reddit post title length is too long.

### ISSUE THREAD

**Issue by FritteX14** [elebumm/RedditVideoMakerBot#1025]
**Describe the bug**
When the post title length is too long the file wont save on Windows because of Window's file length limit.

**To Reproduce**
Run the script for this post: https://www.reddit.com/r/AskReddit/comments/w1hi2c/youre_gifted_24_straight_hours_where_you_and_your/

**System:**
- Python Version: Python 3.10.5
- OS: Windows 11
- App version / Branch: v2.3

**Additional context**
I found a quick fix for everyone who needs the solution fast. It is not good code, but it gets the job done.
What I did is just check if the length of the title is > 50 characters and if it is it divides the length of the string by the length of the title. It isn't "clean" or anything, but it makes the file's name 1 character and it saves. When I wake up tomorrow maybe ill actually fix the issue and post it.
How to fix it:
In video_creation/final_video.py find the section where it says "title = re.sub..." (just ctrl + F it)
Then just replace it with this:
```    
if len(reddit_obj["thread_title"]) > 50:
    h = reddit_obj["thread_title"]
    title = re.sub(r"[^\w\s-]", "", h[:len(h)//len(h)])
else:
    title = re.sub(r"[^\w\s-]", "", reddit_obj["thread_title"])
```
Sorry for any mistakes, it's late, English is not my primary language and it's my first time posting anything on GitHub ;/
I just wanted to post this because I haven't found a solution and someone might need it quickly. :P

**Comment by JasonLovesDoggo** [comment]
Pretty sure this has been fixed in developed

**Comment by NeoV55** [comment]
```
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Creating the final video 🎥                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
[04:55:17]  Video Will Be: 53 Seconds Long                                                            final_video.py:83
Moviepy - Building video assets/temp/temp.mp4.
MoviePy - Writing audio in tempTEMP_MPY_wvf_snd.mp4
MoviePy - Done.
Moviepy - Writing video assets/temp/temp.mp4

Moviepy - Done !
Moviepy - video ready assets/temp/temp.mp4
Moviepy - Running:
>>> "+ " ".join(cmd)
Moviepy - Command returned an error
Traceback (most recent call last):
  File "C:\Users\User\RedditVideoMakerBot\main.py", line 65, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\User\RedditVideoMakerBot\main.py", line 56, in run_many
    main()
  File "C:\Users\User\RedditVideoMakerBot\main.py", line 48, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "C:\Users\User\RedditVideoMakerBot\video_creation\final_video.py", line 144, in make_final_video
    ffmpeg_extract_subclip(
  File "C:\Users\User\anaconda3\lib\site-packages\moviepy\video\io\ffmpeg_tools.py", line 64, in ffmpeg_extract_subclip
    subprocess_call(cmd)
  File "C:\Users\User\anaconda3\lib\site-packages\moviepy\tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
OSError: ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'assets/temp/temp.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:54.13, start: 0.000000, bitrate: 2413 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1080x1920, 2216 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 195 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
results/todayilearned/TIL upon request Martin Luther King Jr gave his copy of the I have a dream speech he had just delivered to the then security guard George Raveling Raveling has been offered as much as 3 million for the original copy but he has refused all offers.mp4: No such file or directory

```
hi guys , still facing the same issue ... tried almost every workaround/fix from here but with no success ... any help is very much appreciated, thank you guys.

System:

Python Version: Python 3.10.4
OS: Windows 10
App version / Branch: v2.3

**Comment by FritteX14** [comment]
> ```
> ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
> │ Creating the final video 🎥                                                                                         │
> └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
> [04:55:17]  Video Will Be: 53 Seconds Long                                                            final_video.py:83
> Moviepy - Building video assets/temp/temp.mp4.
> MoviePy - Writing audio in tempTEMP_MPY_wvf_snd.mp4
> MoviePy - Done.
> Moviepy - Writing video assets/temp/temp.mp4
> 
> Moviepy - Done !
> Moviepy - video ready assets/temp/temp.mp4
> Moviepy - Running:
> >>> "+ " ".join(cmd)
> Moviepy - Command returned an error
> Traceback (most recent call last):
>   File "C:\Users\User\RedditVideoMakerBot\main.py", line 65, in <module>
>     run_many(config["settings"]["times_to_run"])
>   File "C:\Users\User\RedditVideoMakerBot\main.py", line 56, in run_many
>     main()
>   File "C:\Users\User\RedditVideoMakerBot\main.py", line 48, in main
>     make_final_video(number_of_comments, length, reddit_object, bg_config)
>   File "C:\Users\User\RedditVideoMakerBot\video_creation\final_video.py", line 144, in make_final_video
>     ffmpeg_extract_subclip(
>   File "C:\Users\User\anaconda3\lib\site-packages\moviepy\video\io\ffmpeg_tools.py", line 64, in ffmpeg_extract_subclip
>     subprocess_call(cmd)
>   File "C:\Users\User\anaconda3\lib\site-packages\moviepy\tools.py", line 54, in subprocess_call
>     raise IOError(err.decode('utf8'))
> OSError: ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
>   built with gcc 9.2.1 (GCC) 20200122
>   configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
>   libavutil      56. 31.100 / 56. 31.100
>   libavcodec     58. 54.100 / 58. 54.100
>   libavformat    58. 29.100 / 58. 29.100
>   libavdevice    58.  8.100 / 58.  8.100
>   libavfilter     7. 57.100 /  7. 57.100
>   libswscale      5.  5.100 /  5.  5.100
>   libswresample   3.  5.100 /  3.  5.100
>   libpostproc    55.  5.100 / 55.  5.100
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'assets/temp/temp.mp4':
>   Metadata:
>     major_brand     : isom
>     minor_version   : 512
>     compatible_brands: isomiso2avc1mp41
>     encoder         : Lavf58.29.100
>   Duration: 00:00:54.13, start: 0.000000, bitrate: 2413 kb/s
>     Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1080x1920, 2216 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
>     Metadata:
>       handler_name    : VideoHandler
>     Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 195 kb/s (default)
>     Metadata:
>       handler_name    : SoundHandler
> results/todayilearned/TIL upon request Martin Luther King Jr gave his copy of the I have a dream speech he had just delivered to the then security guard George Raveling Raveling has been offered as much as 3 million for the original copy but he has refused all offers.mp4: No such file or directory
> ```
> 
> hi guys , still facing the same issue ... tried almost every workaround/fix from here but with no success ... any help is very much appreciated, thank you guys.
> 
> System:
> 
> Python Version: Python 3.10.4 OS: Windows 10 App version / Branch: v2.3


Could you post the full terminal, from the very start to the end? 

From the logs that you attached currently, I think that in config.toml, in the setting "times_to_run" you've set a value of more than 1. Try setting it to 1, and let me know if that fixed it!
