### ISSUE TITLE
FFMPEG OSError

### ISSUE THREAD

**Issue by App1ePi** [elebumm/RedditVideoMakerBot#1027]
I don't exactly know what is causing it as it working fine yesterday but upon the video creation the ffmpeg_extract_sublcip class ( final_video.py ln141) is throwing an exception error. In my terminal I get these 3 messages when it gets to the class

```
Moviepy - Running:
>>>` "+ " ".join(cmd)
Moviepy - Command returned an error
```

 This means that the bot keeps picking the same exact askReddit post every time I run it.

 It seems to have broken after  I changed a setting in the config.toml on how many times I wanted to run it, but even after changing it back to 1 it did not fix the issue

**Comment by ProjectSlxsh** [comment]
I have had this issue before and is solved in #176 read the entire error includes editing a line of code.
