### ISSUE TITLE
error after saving text to mp3 files

### ISSUE THREAD

**Issue by SyumSenpai** [elebumm/RedditVideoMakerBot#1033]
well idk if it this a bug but for sure this is issue what i have XD
RedditVideoMakerBot-2.3
![Výstřižek](https://user-images.githubusercontent.com/32436087/179600259-6ad61651-da9a-4f7e-88c8-7f89a29a1d94.PNG)

**Comment by JasonLovesDoggo** [comment]
Try using the develop branch

**Comment by micziz** [comment]
The error is caused by it not receiving the text to actually speak. As @JasonLovesDoggo said, use the develop branch. More info in the [docs](https://luka-hietala.gitbook.io/documentation-for-the-reddit-bot/)
