### ISSUE TITLE
AssertionError: No text to send to TTS API

### ISSUE THREAD

**Issue by imdelette** [elebumm/RedditVideoMakerBot#1036]
**Describe the bug**
No text to send to TTS API

**To Reproduce**
Run the applucation with Google Translate TTS choice

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/52404270/179691218-75a8d6d6-0ae9-4f50-9918-d070cf479247.png)

**System (please complete the following information):**

- Python Version: Python 3.10
- OS: Arch Linux
- App version / Branch: develop

**Comment by JasonLovesDoggo** [comment]
#1033

**Comment by JasonLovesDoggo** [comment]
#1029 fixes
