### ISSUE TITLE
Does anyone manage to get view on TikTok recently using this script ?

### ISSUE THREAD

**Issue by Larvouu** [elebumm/RedditVideoMakerBot#1037]
Hello, I tried to post those scripted videos on TikTok with several accounts, but none of them are seen by anyone. It looks like TikTok censor this kind of videos, but idk exactly why. 

Does someone has experienced a similar behavior, or does someone recently managed to get views with this script ? 

Thanks. 👀

**Comment by MCholden** [comment]
I am currently doing well using the script on YouTube Shorts, but I have no experience with TikTok

**Comment by PatatjeMC** [comment]
This is not a bug with the script this is just how TikTok works. A lot of videos get 0 views and then sometimes there are a few that do well but the chance is pretty small. But sending them with multiple accounts will not help and will more likely get you flagged as a bot probably.

**Comment by JasonLovesDoggo** [comment]
Not a bug and I know of at least one person who has gone more than a million views with one of these videos
