### ISSUE TITLE
Crashes And Dont Creat Video

### ISSUE THREAD

**Issue by ItzSqd12** [elebumm/RedditVideoMakerBot#1038]
**Describe the bug**
So I Tried Using Reddit Bot Maker And The 2 Time I Tried It Just Crashed

**To Reproduce**
???
**Expected behavior**
So What I Expected Is A Crystal Audio Good Reddit Video And The First Time It Worked And I Thought It Was Gonna Last Forver

**Screenshots**
No

**System (please complete the following information):**

- Python Version: Latest Version
- OS: Windows 10 - App version 2.1 / Branch [e.g. latest, V2.0, master, develop ]

**Additional context**
No There Is Not

**Comment by CordlessCoder** [comment]
"Guys I expected thing to work and it didnt, this is a huge bug fix now!"
Actually go into detail on what's the problem if you want help
