### ISSUE TITLE
ModuleNotFoundError: No module named 'toml'

### ISSUE THREAD

**Issue by tturkey25** [elebumm/RedditVideoMakerBot#1044]
It might be that I am very new to this, but I keep getting this every time I run python main.py, i can't seem to find a file named tool as well so im not really sure what to do from here

**Comment by tturkey25** [comment]
> 

yeah I get that, that file wasn't in my download so where would I find and where would I put in so that it can be located

**Comment by T9es** [comment]
... what?
![image](https://user-images.githubusercontent.com/107748212/179851013-c9dcdd25-a478-4b3c-901e-7f8b293ebcc1.png)
This is the file you are missing. Put it into the main folder, where you can find CODE OF CONDUST and so on.

As to "that file wasn't in my download", highly doubt. The file literally comes with the download, unless an AV deleted it for weird file format.

**Comment by tturkey25** [comment]
> 
I've added that file and gotten the same result
<img width="1364" alt="Screen Shot 2022-07-19 at 5 37 42 PM" src="https://user-images.githubusercontent.com/78127004/179853080-c6cca62b-7200-4fb9-87d4-a0d5da4e1d46.png">

**Comment by JasonLovesDoggo** [comment]
It's not related to the files The problem is that you don't have the module installed
Run python -m pip install -r requirements.txt

**Comment by T9es** [comment]
Lol, you'd assume people would follow the install guide, and yet, here we are. I had the error when I did not have the config up and running.
