### ISSUE TITLE
how to make video of a specific reddit thread???

### ISSUE THREAD

**Issue by rakesh0972** [elebumm/RedditVideoMakerBot#1047]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**

- Python Version: [e.g. Python 3.6]
- OS: [e.g. Windows 11]
- App version / Branch [e.g. latest, V2.0, master, develop ]

**Additional context**

**Comment by JasonLovesDoggo** [comment]
Exactly
