### ISSUE TITLE
Navigation failed because page crashed

### ISSUE THREAD

**Issue by superidol5** [elebumm/RedditVideoMakerBot#1048]
**Describe the bug**
ran the file as normal (first time) and everything went smooth until it needed to screenshot

**To Reproduce**
used this command: `bash <(curl -sL https://raw.githubusercontent.com/elebumm/RedditVideoMakerBot/master/install.sh)`

**Expected behavior**
to produce a video
**Screenshots**
![image](https://user-images.githubusercontent.com/106981553/179917535-c70162d2-2c53-410a-97e9-dedefbec0027.png)

**System (please complete the following information):**

- Python Version: python3.8 
- fresh install of ubuntu (wsl) updated and upgraded everything'
- App version: latest

**Comment by Drugsosos** [comment]
Maybe the cause is `timeout=0`
@superidol5 Try using new async webdriver for now
https://github.com/Drugsosos/RedditVideoMakerBot/tree/move-to-async-webdriver

**Comment by CultOfHeisenberg** [comment]
Did you mess around with the config file and changed the number of times to run? If so, change it back to default.
