### ISSUE TITLE
Encountered error when trying to to load .config.template.toml: Weirdness with leading zeroes or underscores in your number.

### ISSUE THREAD

**Issue by AdiyanAbdurRahman** [elebumm/RedditVideoMakerBot#1050]
When I put my client ID it shows the message

client_id = ---0---

the dash lines are the letters and that's the position of the zero. For some reason, it always shows this message only for this position even when I remove the 0. 

Error message: Encountered error when trying to to load .config.template.toml: Weirdness with leading zeroes or underscores in your number. (line 2 column 1 char 15)

![Screenshot (29)](https://user-images.githubusercontent.com/78403903/180038302-aefb03c0-28cc-4685-adf8-d96815c3823e.png)

- Python Version: 3.9.13
- OS: Windows 10
- App version v2.3

**Comment by CordlessCoder** [comment]
You shouldn't EVER touch .config.template.toml
Redownload that file and launch main.py
