### ISSUE TITLE
Selectively skipping reddit posts

### ISSUE THREAD

**Issue by ghost** [elebumm/RedditVideoMakerBot#1053]
When a post is selected that may be NSFW but not tagged and i don't want to use it, there is no way for me to skip making the post into a video. I can ctl+c the main.py but every time i rerun the file it chooses the same post. 

It would be nice to have the option to skip. This could be implemented in the "Please choose one of the following TTS providers: " section, with a Skip option.

**Comment by rastogiujj12** [comment]
you can add the post id manually on /video_creation/data/videos.json or just let it create the video and delete it when done.
