### ISSUE TITLE
Has anyone made a follow up on - "Added TTS reading the text of the post if present"

### ISSUE THREAD

**Issue by MrSneak190** [elebumm/RedditVideoMakerBot#1056]
**Is your feature request related to a problem? Please describe.**
No problem - just a feature implementation

**Describe the solution you'd like**
Lookingg for a follow up on a previous post from around June in regards to the bot creating videos (and reading text of the post) for subs such as AITA (amitheasshole).

**Comment by MrSneak190** [comment]
Following up to my own post - saw that there's a feature called story mode in another post however I don't see that implemented on my end, is this currently in the works or out?

**Comment by bobcat4848** [comment]
It is currently in the works @MrSneak190

**Comment by MrSneak190** [comment]
Thanks for letting me know @bobcat4848

**Comment by MrSneak190** [comment]
@JasonLovesDoggo are you guys still working on this as a potential feature? i noticed you closed this as "not planned" so had to ask.

**Comment by JasonLovesDoggo** [comment]
> @JasonLovesDoggo are you guys still working on this as a potential feature? i noticed you closed this as "not planned" so had to ask.

@bobcat4848 already told you.

**Comment by MrSneak190** [comment]
Got it, just wanted to be sure, thanks @JasonLovesDoggo :)
