### ISSUE TITLE
New version only takes punctuation from comments

### ISSUE THREAD

**Issue by 16aces** [elebumm/RedditVideoMakerBot#1062]
**Describe the bug**
On the final video it reads the title fine, but all then for all the comments, it only reads the punctuations. 

The old version of this program works fine for me it's only the newest version that does this. Went back to the old version and it works fine

**To Reproduce**
download and run the program, set up the TOML file, end with a video of the title being read than flashing fifty different comments with the words "dot" and "question mark" spoken overtop.

**Expected behavior**
read the text.

System 

- Python Version: 3.10.5
- OS:  Windows 
- App version:  latest

**Comment by Sometoms** [comment]
Have you found a fix?

**Comment by 16aces** [comment]
no I've just been using an older version as it seems more stable.
