### ISSUE TITLE
Encountered error when trying to to load .config.template.toml: Found tokens after a closed string. Invalid TOML. (line 2 column 1 char 15)

### ISSUE THREAD

**Issue by SmuglerMike** [elebumm/RedditVideoMakerBot#1067]
**Describe the bug**
When i run main.py through Visual Studios i get this error "Encountered error when trying to to load .config.template.toml: Found tokens after a closed string. Invalid TOML. (line 2 column 1 char 15)"

Can someone help me out?

**Comment by JasonLovesDoggo** [comment]
> **Describe the bug**
> When i run main.py through Visual Studios i get this error "Encountered error when trying to to load .config.template.toml: Found tokens after a closed string. Invalid TOML. (line 2 column 1 char 15)"
> 
> Can someone help me out?

Did you edit the file at all?

**Comment by SmuglerMike** [comment]
Ya I filled in everything in the file, what do you think the issue could be?

**Comment by SmuglerMike** [comment]
Nevermind i was being stupid, fixed it

**Comment by htjsjisoi** [comment]
what was the solution? I ran into the same problem and I'm too stupid to solve it.

**Comment by JasonLovesDoggo** [comment]
> what was the solution? I ran into the same problem and I'm too stupid to solve it.

Don't edit that file....
