### ISSUE TITLE
Cant Create The Last Video

### ISSUE THREAD

**Issue by ItzSqd12** [elebumm/RedditVideoMakerBot#1068]
**Describe the bug**
So I Wanted To Make A Reddit Channel When I Run Main.py

**To Reproduce**
Idrk

**Expected behavior**
So I Opened Main.py I Was Excited But And I Thought It Would Work But It Didnt

**Screenshots**
Sorry the error closes the program too fast

**System (please complete the following information):**

- Python Version: 3.10.5
- OS: Windows 10
- App version 2.1

**Additional context**
There is a thing i want to say is it doesnt happen to all computers just some

**Comment by RollingChonCho** [comment]
https://github.com/elebumm/RedditVideoMakerBot/issues/1023

It was talked about here but is sounds like python may not be installed. You'll need to run it properly according to the previous thread.

**Comment by JasonLovesDoggo** [comment]
And you actually have to follow the docs on how to run it

Create a new issue after following the proper dogs

**Comment by JasonLovesDoggo** [comment]
And you actually have to follow the docs on how to run it

Create a new issue after following the proper docs

**Comment by ItzSqd12** [comment]
heres the recording
https://www.youtube.com/watch?v=Qb81OIqI7CY
