### ISSUE TITLE
Encountered error when trying to to load .config.template.toml: [Errno 2] No such file or directory: '.config.template.toml'

### ISSUE THREAD

**Issue by loudderz** [elebumm/RedditVideoMakerBot#1069]
Encountered error when trying to to load .config.template.toml: [Errno 2] No such file or
directory: '.config.template.toml'
can someone help?

**Comment by RollingChonCho** [comment]
My issue was that I had the master folder within a master folder so check your directory first. Secondly (a temp fix) is to just manually create one, copy and paste the old one into the new one and it should work.

**Comment by CultOfHeisenberg** [comment]
@loudderz 

Send the full error message, format it properly, and tell me your operating system.

**Comment by Drugsosos** [comment]
@loudderz 
try to launch the bot from it's folder

**Comment by Sometoms** [comment]
How do i open it on Ubuntu when i have the folder in Home?

**Comment by Drugsosos** [comment]
> How do i open it on Ubuntu when i have the folder in Home?

@Sometoms 
wdym?
```bash
cd ~/<your_folder>
python3 main.py
```

**Comment by Sometoms** [comment]
oh ok thanks
