### ISSUE TITLE
Bug on opening main.py

### ISSUE THREAD

**Issue by lmc87lmc** [elebumm/RedditVideoMakerBot#1073]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior: i just open main.py and get errors 

**Expected behavior**

**Screenshots**

**System (please complete the following information):**

- Python Version: [e.g. Python 3.10]
- OS: macos 12.2.1 (21D62)]
- App version / Branch [e.g. latest, V2.0, master, develop ]

**Additional context**
Last login: Mon Jul 25 21:23:11 on ttys001
lachlancrawford@Lachlans-MacBook-Air ~ % python main.py
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'main.py': [Errno 2] No such file or directory
lachlancrawford@Lachlans-MacBook-Air ~ % /Users/lachlancrawford/RedditVideoMakerBot/RedditVideoMakerBot/main.py
  File "/Users/lachlancrawford/RedditVideoMakerBot/RedditVideoMakerBot/main.py", line 24
SyntaxError: Non-ASCII character '\xe2' in file /Users/lachlancrawford/RedditVideoMakerBot/RedditVideoMakerBot/main.py on line 25, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
lachlancrawford@Lachlans-MacBook-Air ~ % 
lachlancrawford@Lachlans-MacBook-Air ~ % python3 /Users/lachlancrawford/RedditVideoMakerBot/RedditVideoMakerBot/main.py
Traceback (most recent call last):
  File "/Users/lachlancrawford/RedditVideoMakerBot/RedditVideoMakerBot/main.py", line 10, in <module>
    from video_creation.background import (
  File "/Users/lachlancrawford/RedditVideoMakerBot/RedditVideoMakerBot/video_creation/background.py", line 7, in <module>
    from moviepy.editor import VideoFileClip
  File "/opt/homebrew/lib/python3.9/site-packages/moviepy/editor.py", line 36, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/opt/homebrew/lib/python3.9/site-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.audio.io.AudioFileClip import AudioFileClip
  File "/opt/homebrew/lib/python3.9/site-packages/moviepy/audio/io/AudioFileClip.py", line 3, in <module>
    from moviepy.audio.AudioClip import AudioClip
  File "/opt/homebrew/lib/python3.9/site-packages/moviepy/audio/AudioClip.py", line 7, in <module>
    from moviepy.audio.io.ffmpeg_audiowriter import ffmpeg_audiowrite
  File "/opt/homebrew/lib/python3.9/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 7, in <module>
    from moviepy.config import get_setting
  File "/opt/homebrew/lib/python3.9/site-packages/moviepy/config.py", line 36, in <module>
    FFMPEG_BINARY = get_exe()
  File "/opt/homebrew/lib/python3.9/site-packages/imageio/plugins/ffmpeg.py", line 159, in get_exe
    return imageio_ffmpeg.get_ffmpeg_exe()
  File "/opt/homebrew/lib/python3.9/site-packages/imageio_ffmpeg/_utils.py", line 49, in get_ffmpeg_exe
    raise RuntimeError(
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.
lachlancrawford@Lachlans-MacBook-Air ~ %

**Comment by Drugsosos** [comment]
@lmc87lmc  It's not a bug

Try to install *ffmpeg* 
```bash
brew install ffmpeg
```
*If you don't have brew installed*
```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

**Comment by lmc87lmc** [comment]
thanks, just installed it jut now it fails
lachlancrawford@Lachlans-MacBook-Air ~ % python3 /Users/lachlancrawford/Downloads/RedditVideoMakerBot-master/main.py 
Using Australia server backend.

██████╗ ███████╗██████╗ ██████╗ ██╗████████╗    ██╗   ██╗██╗██████╗ ███████╗ ██████╗     ███╗   ███╗ █████╗ ██╗  ██╗███████╗██████╗
██╔══██╗██╔════╝██╔══██╗██╔══██╗██║╚══██╔══╝    ██║   ██║██║██╔══██╗██╔════╝██╔═══██╗    ████╗ ████║██╔══██╗██║ ██╔╝██╔════╝██╔══██╗
██████╔╝█████╗  ██║  ██║██║  ██║██║   ██║       ██║   ██║██║██║  ██║█████╗  ██║   ██║    ██╔████╔██║███████║█████╔╝ █████╗  ██████╔╝
██╔══██╗██╔══╝  ██║  ██║██║  ██║██║   ██║       ╚██╗ ██╔╝██║██║  ██║██╔══╝  ██║   ██║    ██║╚██╔╝██║██╔══██║██╔═██╗ ██╔══╝  ██╔══██╗
██║  ██║███████╗██████╔╝██████╔╝██║   ██║        ╚████╔╝ ██║██████╔╝███████╗╚██████╔╝    ██║ ╚═╝ ██║██║  ██║██║  ██╗███████╗██║  ██║
╚═╝  ╚═╝╚══════╝╚═════╝ ╚═════╝ ╚═╝   ╚═╝         ╚═══╝  ╚═╝╚═════╝ ╚══════╝ ╚═════╝     ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

                                                                                                                         
                                                                                                                         
   Thanks for using this tool! Feel free to contribute to this project on GitHub! If you have any questions, feel free   
      to reach out to me on Twitter or submit a GitHub issue. You can find solutions to many common problems in the      
                                                      Documentation                                                      
                                                                                                                         
                                                                                                                         
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ You are using v2.3 of the bot                                                                                         │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Encountered error when trying to to load .config.template.toml: [Errno 2] No such file or directory: 
'.config.template.toml'
lachlancrawford@Lachlans-MacBook-Air ~ %

**Comment by Drugsosos** [comment]
@lmc87lmc 
Don't run it like this

Run the bot like this
```bash
cd ~/Downloads/RedditVideoMakerBot-master
python3 main.py
```

It's trying to find `utils/.config.template.toml` in the root of your filesystem. So it's not a surprise it's not there🐸

**Comment by Drugsosos** [comment]
https://github.com/elebumm/RedditVideoMakerBot/issues/1069
