### ISSUE TITLE
Story Mode Enhancement 

### ISSUE THREAD

**Issue by JamesJackson123** [elebumm/RedditVideoMakerBot#1075]
For the story mode feature it would be fantastic if instead of reading from a wall of text it segments the text into mini-screen shots. This is a popular method of reddit story creators on TikTok.

**Comment by JasonLovesDoggo** [comment]
Continue.... I need examples

**Comment by JamesJackson123** [comment]
https://www.tiktok.com/@redditstories56/video/7121440850734959918 here's an example. For text that's quite long, segmenting it increases engagement. Could be an optional config setting for storymode/regular

**Comment by Drugsosos** [comment]
@JasonLovesDoggo 
I'm thinking about `fx.all.scroll`, maybe it'll even look cooler

**Comment by JasonLovesDoggo** [comment]
> @JasonLovesDoggo 
> I'm thinking about `fx.all.scroll`, maybe it'll even look cooler than splitting one big screenshot into smaller ones

That could be experimented with

**Comment by PauloMendes81** [comment]
This probably is a dumb question but I've seen you guys talk about this story mode and I'm not understanding... Is this feature available or it's an upcoming feature?

**Comment by electro199** [comment]
> This probably is a dumb question but I've seen you guys talk about this story mode and I'm not understanding... Is this feature available or it's an upcoming feature?

it's an upcoming feature?
