### ISSUE TITLE
Warning: Can get a channel terminated!

### ISSUE THREAD

**Issue by artificialbutter** [elebumm/RedditVideoMakerBot#1077]
I've found that using this tool without any modification to the finished videos, uploading daily that YouTube can suspend your channel for video spam.
![image](https://user-images.githubusercontent.com/59352535/181149177-34c85beb-2472-4484-a459-00748530897e.png)
Adding music, or adding something else of value would probably negate this, but I'm making this issue to warn against doing what I did.
![image](https://user-images.githubusercontent.com/59352535/181149413-d3092154-14d5-4945-bf91-2b310b74a9f7.png)
I still think this can be a good tool though, and TikTok probably wouldn't care.

**Comment by JasonLovesDoggo** [comment]
"that computers post"

**Comment by artificialbutter** [comment]
The magic youtube algorithms obviously didn't see the difference between me scheduling them, and a computer. I'm just warning against what I did.

**Comment by C5fifteen** [comment]
So you had a bot upload them or you did it manually?

**Comment by artificialbutter** [comment]
I uploaded 7 videos manually over about 3 hours, and scheduled them to go public every day of the week.

**Comment by theharshitkumar** [comment]
The reason they give you is totally different. maybe you can ask them for a review?

**Comment by jamesrpoirier** [comment]
This still happens. Unsure what triggers it. Could be # of videos uploaded over time. I have asked for a review of my channel as it is quite frustrating seeing lower quality content make its way into my shorts feed when mine get removed.
