### ISSUE TITLE
JSONDecodeError: requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Dimah4x** [elebumm/RedditVideoMakerBot#1079]
**Describe the bug**
making a long video saves while converting text to MP3

**To Reproduce**
Steps to reproduce the behavior: set video length to 10 minutes

**Expected behavior**
A clear and concise description of what you expected to happen. to make a 10 minute video

**Screenshots**
![image](https://user-images.githubusercontent.com/37594125/181288265-025d204b-dc09-4f0f-866d-5792d2745cdf.png)

**System (please complete the following information):**

- Python Version: [e.g. Python 3.6] python 3.10.5
- OS: [e.g. Windows 11] windows 10
- App version / Branch [e.g. latest, V2.0, master, develop ] 2.1

**Additional context**

**Comment by JasonLovesDoggo** [comment]
Fixed

**Comment by codergamer7** [comment]
How did u fix it?
