### ISSUE TITLE
Playwright

### ISSUE THREAD

**Issue by thebug8** [elebumm/RedditVideoMakerBot#108]
I currently have playwright test for VSCode downloaded but when I run the python3 main.py code in powershell it tells me to install playwright.

**Comment by alxb421** [comment]
Do `pip3 install playwright` and then `python3 -m playwright install`. It works for me(I had the same problem)

**Comment by Goodgamer78** [comment]
Greenlet is not needed. python3 -m playwright install worked for me.

**Comment by FreebieII** [comment]
Hi @thebug8 

I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
