### ISSUE TITLE
lots of errors 

### ISSUE THREAD

**Issue by Greg-Creator** [elebumm/RedditVideoMakerBot#1080]
After installing the background video for the first time, the program stops and gives a lot of errors
<img width="1440" alt="Bildschirmfoto 2022-07-27 um 18 50 05" src="https://user-images.githubusercontent.com/58531829/181306937-d02194cb-628d-4623-bd6a-873948956734.png">
. 

It says a lot of things, and in the end there is an error. I'm not that good with python, so I don't understand a lot :(

**Comment by JasonLovesDoggo** [comment]
Go to the directory you have Python installed in and click install.certificates.com command
