### ISSUE TITLE
gui and CORS

### ISSUE THREAD

**Issue by zaourzag** [elebumm/RedditVideoMakerBot#1083]
**Describe the bug**
gui failing to load due to CORS
**To Reproduce**
open index.html in chrome. open inspect and see console
**Expected behavior**

the file opens and all is good
**Screenshots**

[1](https://zws.im/%F3%A0%81%A4%F3%A0%81%AF%E2%80%8D%F3%A0%81%BA%F3%A0%81%B6%F3%A0%81%AC%F3%A0%81%B2)
**System (please complete the following information):**

- Python Version: [e.g. Python 3.6]
- OS: windows 10 pro
- App version / Branch: latest on Master

**Comment by JasonLovesDoggo** [comment]
Fixed

**Comment by zaourzag** [comment]
What turned out to be the issue?

**Comment by JasonLovesDoggo** [comment]
> What turned out to be the issue?

CORS
