### ISSUE TITLE
Ability to make longer video times

### ISSUE THREAD

**Issue by C5fifteen** [elebumm/RedditVideoMakerBot#1087]
Add the ability to make longer videos, maybe from options of 3mins, 5mins, 10mins.

**Comment by AntiCtrl** [comment]
i agree. Would be nice.

**Comment by Dimah4x** [comment]
the problem with this is that the TTS has max characters it can read before giving a json error,
the way to implement it would be dividing the video to chunks and appending them all in the end to avoid the TTS limit

**Comment by bobshepard87** [comment]
I would like this as well.

**Comment by hm0809** [comment]
So would I
