### ISSUE TITLE
Traceback bug

### ISSUE THREAD

**Issue by hellowtf0111** [elebumm/RedditVideoMakerBot#1088]
**Describe the bug**

**To Reproduce**

**Expected behavior**┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ You are using v2.3 of the bot                                                                                       │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
###############################
#                             #
# Checking TOML configuration #
#                             #
###############################
If you see any prompts, that means that you have unset/incorrectly set variables, please input the correct values.
Example: streamlabspolly
Non-optional choice=
The default value is ""
Do you want to use it?(y/n)
y
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ on the 1st iteration of 1                                                                                           │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Logging into Reddit.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Getting subreddit threads...                                                                                        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Using subreddit: r/Romania from TOML config
This post was pinned by moderators. Skipping...
This post was pinned by moderators. Skipping...
Video will be: Un maramureșean a sunat la 112 pentru a anunța că o femeie s-a urcat beată la volan / Era de fapt
logodnica lui și tocmai îl anunțase că s-au despărțit / Tipa avea 1,22 mg/l alcool pur în aerul expirat 👍
Thread has 605 upvotes
Thread has a upvote ratio of 97.0%
Thread has 93 comments
Received subreddit threads Successfully.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Please choose one of the following TTS providers:                                                                   │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌─────────────────┐ ┌──────────┐ ┌─────────────────┐ ┌────────┐
│ GoogleTranslate │ │ AWSPolly │ │ StreamlabsPolly │ │ TikTok │
└─────────────────┘ └──────────┘ └─────────────────┘ └────────┘

TikTok
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Saving Text to MP3 files...                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Translating Text...
Saving... ----------------------------------------   Translating Text...
Saving... ----------------------------------------   Translating Text...
Saving... ----------------------------------------   Translating Text...
Saving... ---------------------------------------- 0.5 it/s  Translating Text...
Saving... ---------------------------------------- 0.5 it/s  Translating Text...
Saving... ---------------------------------------- 0.5 it/s  Translating Text...
Saving... ---------------------------------------- 0.5 it/s  Translating Text...
Saving... ---------------------------------------- 0.5 it/s  Translating Text...
Saving... ---------------------------------------- 0.5 it/s  Translating Text...
Saving... ---------------------------------------- 0.5 it/s  Translating Text...
Saving... ---------------------------------------- 0.5 it/s  Translating Text...
Saving... ---------------------------------------- 0.5 it/s  Translating Text...
Saving... ---------------------------------------- 0.5 it/s  Translating Text...
Saving... ---------------------------------------- 0.5 it/s  Translating Text...
Saving... ---------------------------------------- 0.5 it/s  Translating Text...
Saving... ---------------------------------------- 0.5 it/s  Translating Text...
Saving... ---------------------------------------- 0.5 it/s  Translating Text...
Saving... ---------------------------------------- 0.4 it/s  Translating Text...
Saving... ---------------------------------------- 0.4 it/s  Translating Text...
Saving... ---------------------------------------- 0.4 it/s  Translating Text...
Saving... ---------------------------------------- 0.4 it/s  Translating Text...
Saving... ---------------------------------------- 0.4 it/s  Translating Text...
Saving... ---------------------------------------- 0.4 it/s  Translating Text...
Saving... ---------------------------------------- 0.4 it/s  Translating Text...
Saving... ---------------------------------------- 0.4 it/s  Translating Text...
Saving... ---------------------------------------- 0.4 it/s  Translating Text...
Saving... ---------------------------------------- 0.4 it/s
Saved Text to MP3 files successfully.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Downloading screenshots of reddit posts...                                                                          │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Launching Headless Browser...
Translating post...
Traceback (most recent call last):
  File "C:\Users\pc1\Desktop\redditTotTiktok\RedditVideoMakerBot\main.py", line 65, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\pc1\Desktop\redditTotTiktok\RedditVideoMakerBot\main.py", line 56, in run_many
    main()
  File "C:\Users\pc1\Desktop\redditTotTiktok\RedditVideoMakerBot\main.py", line 44, in main
    download_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "C:\Users\pc1\Desktop\redditTotTiktok\RedditVideoMakerBot\video_creation\screenshot_downloader.py", line 65, in download_screenshots_of_reddit_posts
    page.evaluate(
  File "C:\Users\pc1\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 6786, in evaluate
    self._sync(
  File "C:\Users\pc1\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 89, in _sync
    return task.result()
  File "C:\Users\pc1\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_page.py", line 412, in evaluate
    return await self._main_frame.evaluate(expression, arg)
  File "C:\Users\pc1\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 262, in evaluate
    await self._channel.send(
  File "C:\Users\pc1\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\pc1\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 370, in _
    return await result
  File "C:\Users\pc1\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: TypeError: Cannot set properties of null (setting 'textContent')
    at eval (eval at evaluate (:178:30), <anonymous>:1:114)
    at UtilityScript.evaluate (<anonymous>:185:19)
    at UtilityScript.<anonymous> (<anonymous>:1:44)

**Comment by hellowtf0111** [comment]
My config , i try to get a ROMANIAN post,i want a Romanian TTS i tried TTS : Google,tiktok,streamlabs AWS but : and You need to install the AWS CLI and configure your profile,i don't undestun what it's the problem.

[settings]
allow_nsfw = false
theme = "dark"
times_to_run = 1
opacity = 0.9
storymode = false

[settings.background]
background_choice = "minecraft"

[settings.tts]
choice = ""
aws_polly_voice = ""
streamlabs_polly_voice = ""
tiktok_voice = "br_001"


[reddit.thread]
random = false
subreddit = "Romania"
post_id = ""
max_comment_length = 500
post_lang = "ro"
min_comments = 15

**Comment by rOP123r** [comment]
same problem for me

**Comment by arifengineer** [comment]
i am facing this same issue

**Comment by Neo19867** [comment]
so as me
