### ISSUE TITLE
AssertionError: No text to send to TTS API

### ISSUE THREAD

**Issue by knambrose** [elebumm/RedditVideoMakerBot#1089]
When trying to run the bot, I get error "No text to send to TTS API". Not sure what I'm doing wrong.

**Comment by rOP123r** [comment]
ME TOO

**Comment by Defconn4** [comment]
I ran into the same issue as well, turns out it was an issue with the thread itself, likely a deleted comment or something similar. Just run `python main.py` again.

**Comment by swoker** [comment]
this was already fixed in the latest develop version, check this PR to apply the changes directly in your master code if neccessary: https://github.com/elebumm/RedditVideoMakerBot/pull/1029/files
