### ISSUE TITLE
Error on start.

### ISSUE THREAD

**Issue by Matthaeus07** [elebumm/RedditVideoMakerBot#1090]
**Describe the bug**

When I am execution "main.py" I am getting this error:

![image](https://user-images.githubusercontent.com/87285710/181653189-4389d265-ad26-4caf-9550-6d86f7fdcc64.png)

Interestingly this file exists:

![image](https://user-images.githubusercontent.com/87285710/181653467-858ec9dd-359d-4537-8ef4-0d08f21391df.png)

**System**

- Python Version: 3.10
- OS: Windows 10
- App version / Branch: v2.3

**Comment by BlackCat3568** [comment]
I'am with the same problem.

**Comment by Supreme-hub** [comment]
Hey, i fixed this for me by running the script by double clicking on it, for some reason it does not work by using open with

**Comment by Matthaeus07** [comment]
> Hey, i fixed this for me by running the script by double clicking on it, for some reason it does not work by using open with 

Yes, this fixes it for me too.
