### ISSUE TITLE
TTS reading emoji code

### ISSUE THREAD

**Issue by vandersdg** [elebumm/RedditVideoMakerBot#1094]
**Describe the bug**
Whenever a comment has an emoji like a chad face or a man smiling, the TTS reads it like " Oh this is based and redpilled (emoji two hundred and seventy five)"

**To Reproduce**
Just find a comment with emojis and do the test.

**Expected behavior**
Ignore the emoji

**Comment by JasonLovesDoggo** [comment]
> **Describe the bug**
> Whenever a comment has an emoji like a chad face or a man smiling, the TTS reads it like " Oh this is based and redpilled (emoji two hundred and seventy five)"
> 
> **To Reproduce**
> Just find a comment with emojis and do the test.
> 
> **Expected behavior**
> Ignore the emoji
> 

Noted
