### ISSUE TITLE
Not being uploaded as shorts even though its below 60s

### ISSUE THREAD

**Issue by Waffle-s** [elebumm/RedditVideoMakerBot#1095]
idk if this is a yt bug or a bug from the side of the script, whenever I try to upload it, it never gets uploaded as a short. (I used my alt to check whether it's a short or not)

**Comment by Waffle-s** [comment]
edit: found out that while edtitng the script, I accidentally deleted some parts of it making the video 1920x1080.

**Comment by theharshitkumar** [comment]
So the issue is solved?  Then this should be closed
