### ISSUE TITLE
Trash the video if longer than 60 seconds

### ISSUE THREAD

**Issue by C5fifteen** [elebumm/RedditVideoMakerBot#1098]
Trash it because anything over 60 seconds doesn't count as a short, and I'm pretty sure the bot was made to make videos that are shorts.

**Comment by JasonLovesDoggo** [comment]
> Trash it because anything over 60 seconds doesn't count as a short, and I'm pretty sure the bot was made to make videos that are shorts.

That is the primary purpose But it'd be kind of stupid to trash them after all of the processing that went into it

**Comment by C5fifteen** [comment]
Sometimes it creates videos longer than 60 secs like 1:05 or 1:10
