### ISSUE TITLE
Ignore videos on reddit

### ISSUE THREAD

**Issue by vandersdg** [elebumm/RedditVideoMakerBot#1099]
Whenever a post is a video, the bot is unable to play it resulting in a screenshot of "cannot load video" message. To resolve, I suggest the bot simply ignore if it identifies a video and go to the next post.

**Comment by StopmotionSimonYT** [comment]
Do you have an example URL of the post? Then I can see if it is possible to make this feature.

**Comment by liamb13** [comment]
@OpenSourceSimon [Random Video Post](https://www.reddit.com/user/alrirra/comments/gf5x66/minecraft_but_if_you_die_you_get_banned_for_24h/)

**Comment by OpenSourceSimon** [comment]
> @OpenSourceSimon [Random Video Post](https://www.reddit.com/user/alrirra/comments/gf5x66/minecraft_but_if_you_die_you_get_banned_for_24h/)

Wow that's a late response but thanks! I'll try to resolve the issue
