### ISSUE TITLE
Add Backround Music

### ISSUE THREAD

**Issue by mrpekr** [elebumm/RedditVideoMakerBot#11]
It is a good idea to add option to put some Copyright Free music into the video.

**Comment by Devilbager** [comment]
Maybe you could download a bunch of royalty free music, randomly take one of them, and put it as background music. I'm pretty sure the [moviepy](https://pypi.org/project/moviepy/) library is able to add audio to videos.

**Comment by JasonLovesDoggo** [comment]
honestly, I don't think it's a great idea.

**Comment by TechStudent11** [comment]
Awesome idea that needs to be added

**Comment by JasonLovesDoggo** [comment]
For anybody who does want to implement this
It can be done with
`moviepy.ffmpeg_tools.ffmpeg_merge_video_audio ('after.mp4, 'audio.wav, 'new.mp4')`

**Comment by JasonLovesDoggo** [comment]
testing implementation now.

**Comment by JasonLovesDoggo** [comment]
sorry... i really can't do this

**Comment by yungfresh1** [comment]
where do i need the put "moviepy.ffmpeg_tools.ffmpeg_merge_video_audio ('after.mp4, 'audio.wav, 'new.mp4')"?

**Comment by yeetus1992** [comment]
Is it implemented yet?

**Comment by mrpekr** [comment]
> Is it implemented yet?

Yes it was implemented in https://github.com/elebumm/RedditVideoMakerBot/commit/e44718ffdb634c174b77b349fb55a15c9b5ab3d7 so its been added for some time

**Comment by yeetus1992** [comment]
So I have to add the file under assets>backgrounds; but also background_audio = true in config or how does that work?
