### ISSUE TITLE
2fa not working properly

### ISSUE THREAD

**Issue by theglitchedgrenade** [elebumm/RedditVideoMakerBot#1100]
when I try to run main.py it asks for 2fa and when I did set up 2fa it still didn't work when I try to disable the 2fa in config.toml main.py 
crashes (and I did disable 2fa for Reddit)  and I wouldn't think it's anything to do with my system because it has a 5600x 32GB ddr4 ram and an RTX 3060ti. im running the latest version of win11 and python so i don't know what's happening so hopefully there's a solution

**Comment by JasonLovesDoggo** [comment]
> when I try to run main.py it asks for 2fa and when I did set up 2fa it still didn't work when I try to disable the 2fa in config.toml main.py 
> crashes (and I did disable 2fa for Reddit)  and I wouldn't think it's anything to do with my system because it has a 5600x 32GB ddr4 ram and an RTX 3060ti. im running the latest version of win11 and python so i don't know what's happening so hopefully there's a solution
> 

You probably input some invalid characters
