### ISSUE TITLE
Screenshots show up at the top of the screen in the final video.

### ISSUE THREAD

**Issue by notluismora** [elebumm/RedditVideoMakerBot#1101]
How do I make it so the screenshots are in the middle of the screen instead of at the top?
![image](https://user-images.githubusercontent.com/110213031/182003648-f467a7f5-442a-4ad2-a313-6211b4382978.png)
Example

**Comment by RiveN000** [comment]
All background videos (Minecraft, Rocket League, etc.) have different predefined positions of screenshots on the screen to avoid covering gameplay. If you want to modify them, go to `video_creation > background.py` and find a long dictionary of background videos. Under the author (e.g., Orbital Gameplay, Achy Gaming), there's a line responsible for the screenshots' position (`lambda...`). Just change it to `"center"`.

**Example with Rocket League:**

```python
"rocket-league": (  # Rocket League
    "https://www.youtube.com/watch?v=2X9QGY__0II",
    "rocket_league.mp4",
    "Orbital Gameplay",
    "center",
```
