### ISSUE TITLE
Downloading the backgrounds videos, SSL: CERTIFICATE_VERIFY_FAILED?

### ISSUE THREAD

**Issue by sosojustdo** [elebumm/RedditVideoMakerBot#1103]
**Screenshots**
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/3364336/182020626-a51f663e-ad27-4465-a31b-2cb638ef111d.png">

**System (please complete the following information):**
- Python Version: 3.10.5
- Openssl：1.1.1q  5 Jul 2022
- OS: CentOS Linux release 7.9.2009 (Core)
- App version: develop and master

**Additional context**
Prompt SSL error every time download Youtube background video mp4 file,  please help me?

**Note：** When I installed python3.10.5, pip3 install package also prompted an ssl error. Later, I found information on the Internet and found that a high version of openssl was needed. Later, I downloaded 1.1.1 and installed it. After setting up /etc/profile and soft connection /usr /bin/openssl, after recompiling and installing python3.10.5, the pip3 install ssl error is solved,

**Comment by sosojustdo** [comment]
@JasonLovesDoggo Hi， My operating system is centos, not macOs, and there is no install.certificates.command file in the Python installation directory

**Comment by JasonLovesDoggo** [comment]
> @JasonLovesDoggo Hi， My operating system is centos, not macOs, and there is no install.certificates.command file in the Python installation directory

Google how to generate new certificates for centOS

**Comment by mattsegura** [comment]
https://www.youtube.com/watch?v=dEBN1M609zk

**Comment by mattsegura** [comment]
After install certifi you can run this command,

"/Applications/Python\ 3.9/Install\ Certificates.command"

change the python version to the one you're using, so maybe 3.10
