### ISSUE TITLE
My reddit account got suspended while running the code

### ISSUE THREAD

**Issue by TheM1sty** [elebumm/RedditVideoMakerBot#1106]
**Describe the bug**
My reddit account got suspended while running the code

**Screenshots**
![image](https://user-images.githubusercontent.com/71806432/182026611-fe38c880-da5a-4784-9e35-3afc2487d2f0.png)

**System (please complete the following information):**

- Python Version: [e.g. Python 3.6]
- OS: Win 10
- latest, V2.0, master

**Comment by Anvilator-web** [comment]
Uhh that never happened... is this the first time you ran the bot?

**Comment by omxpro** [comment]
It doesn't happen. I ran the bot on GitHub actions multiple times. This has never happened to me.

**Comment by TheM1sty** [comment]
Idk but It doesn't work for me at all. for example "Import "utils.console" could not be resolved"  How long does it normally take for one video? 

> Uhh that never happened... is this the first time you ran the bot?

**Comment by JasonLovesDoggo** [comment]
> Idk but It doesn't work for me at all. for example "Import "utils.console" could not be resolved"  How long does it normally take for one video? 
> 
> > Uhh that never happened... is this the first time you ran the bot?
> 
> 

Update your python version and make sure it's added to path
