### ISSUE TITLE
Encountered error when trying to to load .config.template.toml: Found tokens after a closed string. Invalid TOML. (line 2 column 1 char 15)

### ISSUE THREAD

**Issue by htjsjisoi** [elebumm/RedditVideoMakerBot#1109]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**

- Python Version: [e.g. Python 3.6]
- OS: [e.g. Windows 11]
- App version / Branch [e.g. latest, V2.0, master, develop ]

**Additional context**

**Comment by htjsjisoi** [comment]
I'm not sure If I'm just being stupid but this error code always shows up.

**Comment by JasonLovesDoggo** [comment]
Don't edit that file
