### ISSUE TITLE
Different voices

### ISSUE THREAD

**Issue by ChefBars** [elebumm/RedditVideoMakerBot#1111]
What are the names of some different voices (so other than Matthew) that I can use to differentiate the videos a little bit?

**Comment by Tintinero1** [comment]
This is for streamlabspolly: valid voices https://lazypy.ro/tts/
For TikTok check comments in code file: RedditVideoMakerBot/TTS/TikTok.py

**Comment by Coding-Fella** [comment]
"Brian","Emma","Russell","Joey","Matthew","Joanna","Kimberly","Amy","Geraint","Nicole","Justin","Ivy","Kendra","Salli" and "Raveena". I'm using version 2.1 so this migth not work for you. If you go to the files of the code(
RedditVideoMakerBot) and open "TTS". You can then open the one called "POLLY.py" with Notepad and you'll see all the names.
