### ISSUE TITLE
Why doesn't my final generated video screenshot + voice and video length match?

### ISSUE THREAD

**Issue by sosojustdo** [elebumm/RedditVideoMakerBot#1115]
**Describe the bug**
Why doesn't my final generated video screenshot + voice and video length match?

**To Reproduce**

**Screenshots**
<img width="803" alt="image" src="https://user-images.githubusercontent.com/3364336/182541910-4f7d2bee-26f3-4c3d-a687-102bc5949ed6.png">

**System (please complete the following information):**
- Python Version:3.10.5
- OS: Centos7
- App version / Branch: develop

**Additional context**
Downloading screenshots... Just 13% and return Successfully.

**Comment by sosojustdo** [comment]
Note: Branch -master can't reproduce, I am still in the process of continuous testing and verification, I hope that the develop branch will not be merged with master, which will lead to the introduction of bugs @jcreek @SpaYco

**Comment by theharshitkumar** [comment]
I agree i am also having this issue. Almost extra 5-10 sec is there in everyvideo. I am using Windows and python 3.10.5

**Comment by JasonLovesDoggo** [comment]
> Note: Branch -master can't reproduce, I am still in the process of continuous testing and verification, I hope that the develop branch will not be merged with master, which will lead to the introduction of bugs. @JasonLovesDoggo @ CallumIO

I feel it was caused by this commit https://github.com/elebumm/RedditVideoMakerBot/commit/b0fa6616248ac9df93b533c3e50f127f328ec29b

Unfortunately I can't do anything right now as I am away from my PC if you want you could make a PR reverting that

**Comment by Trichtern** [comment]
Also happens to me
