### ISSUE TITLE
winError 10054 on mp4 download?

### ISSUE THREAD

**Issue by yiffsec** [elebumm/RedditVideoMakerBot#1118]
**Describe the bug**
I keep getting the same error and I've tried using my laptop too with no results. I have a 500mb line hardwired to my desktop.
I've tried using python3 in place of python main.py.  Pls be kind r noob

**To Reproduce**
python main.py

![1error](https://user-images.githubusercontent.com/85042479/182698721-5f78d160-c81e-41ce-ab0f-d04b98fd1b56.png)

![12error](https://user-images.githubusercontent.com/85042479/182698758-9deb2c04-8d34-4fb7-b9ea-ece689ed33dd.png)

- Python Version: [e.g. Python 3.9
- OS:  Windows 11
- App version / Branch [e.g. latest,

**Comment by JasonLovesDoggo** [comment]
https://stackoverflow.com/questions/8814802/python-errno-10054-an-existing-connection-was-forcibly-closed-by-the-remote-h
