### ISSUE TITLE
Final video 

### ISSUE THREAD

**Issue by charlierollo** [elebumm/RedditVideoMakerBot#1122]
Where does the final video go? For me when the process is done it goes back to the blank command line and I can’t find a completed video file.

The Reddit post taken also seems to be the same every time.

**Comment by jam41803** [comment]
It should go into a folder called "Results"

**Comment by charlierollo** [comment]
In the desktop or where? I don’t have this

**Comment by Zitrone-0987** [comment]
> In the desktop or where? I don’t have this

I dont see it either
