### ISSUE TITLE
2.4: No module named pyttsx3

### ISSUE THREAD

**Issue by CJthisis** [elebumm/RedditVideoMakerBot#1130]
I just got the latest version and did everything the readme asked to install everything, then tried to set the bot up for the first time, and this was the error i received:
(I am running python version 3.10.5)

![grafik](https://user-images.githubusercontent.com/99442347/183579995-07cadb71-a92f-47dc-a4ad-e68cccd6d84b.png)

**Comment by PM24PM24** [comment]
For me the following command solved the issue "pip3 install pyttsx"

**Comment by Lukabera** [comment]
> For me the following command solved the issue "pip3 install pyttsx"

it didn't solve for me :(

**Comment by Nahuhacks** [comment]
I had the same issue and i fixed it running this command
pip install pyttsx3

**Comment by CJthisis** [comment]
> I had the same issue and i fixed it running this command
> 
> pip install pyttsx3

Thanks, this fixed it for me too!

**Comment by CJthisis** [comment]
This issue is now irrelevent, since v2.4.1 fixed this issue with pyttsx3 being in requirements.txt
