### ISSUE TITLE
print_step(f"You are using v{__VERSION__} of the bot")

### ISSUE THREAD

**Issue by Lukabera** [elebumm/RedditVideoMakerBot#1131]
after i enter: python2 main.py
this error shows up:
print_step(f"You are using v{__VERSION__} of the bot")

![image](https://user-images.githubusercontent.com/88141418/183618322-db9b15a4-994e-4bdf-a13f-ca3f258ae751.png)

**Comment by joshgreenwood2003** [comment]
use python3 instead of python2
