### ISSUE TITLE
2.4.1: cannot import name 'print:_substep' from 'utils'

### ISSUE THREAD

**Issue by CJthisis** [elebumm/RedditVideoMakerBot#1139]
**Describe the bug**
The bot doesn't start after installing the requirements, playwright and playwright deps

- Python Version: Python 3.10.5
- OS: Windows 10
- App version / Branch v2.4.1, master branch

![grafik](https://user-images.githubusercontent.com/99442347/183764267-a59bc2a2-16ae-4590-a84d-bb1c88508b2d.png)

**Comment by callumio** [comment]
Update please
