### ISSUE TITLE
How do I use it once I've installed it?

### ISSUE THREAD

**Issue by kadencrafter78** [elebumm/RedditVideoMakerBot#114]
I've installed all the code, but whenever I click on main.py, Python only opens for like a second before it closes. Why does it do this? And how do I make the videos with this code?

**Comment by Ragingerz** [comment]
You have to go to cmd and write "python main.py"

**Comment by kadencrafter78** [comment]
It keeps saying that that file is not found

**Comment by FreebieII** [comment]
> It keeps saying that that file is not found

Hi @kadencrafter78, please double check that you are in the correct filepath when running `python3 main.py`


I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
