### ISSUE TITLE
Can I get help setting this thing up

### ISSUE THREAD

**Issue by itsW3RN3R** [elebumm/RedditVideoMakerBot#1146]
i've read the Documentation but unfortunately didn't help am stupid i get REDDIT App IDs and stuff but where should i put them on the Docum says to put it in configuring.md but i see no configuring.md all i have is config.template.toml in the utils and i have no idea how to set it up

**Comment by IbrahimKarsamov** [comment]
I think it will create the file if you execute main.py

**Comment by itsW3RN3R** [comment]
The reason i was getting the match e.response.status_code invalid syntax i had only python3.9 but when i try running the bot using py -3.10 main.py i get no module named prawcore even doe i have it downloaded and tried to reinstall it but nothing happens still

**Comment by JasonLovesDoggo** [comment]
Download develop branch and retry

**Comment by itsW3RN3R** [comment]
> Download develop branch and retry

ngl i actually give up itried older version 2.1 working even tho there's lil bit of bugs but its fine 
sorry for bothering :D
