### ISSUE TITLE
in the post only the headline is read

### ISSUE THREAD

**Issue by JeremyX9** [elebumm/RedditVideoMakerBot#1147]
There should be a setting that only the post or the post content can be read. he reads only the headline and then goes to the comments

But should it be about scary stories that someone tells directly should be read aloud of course

Do you need an example or do you understand what I mean.

Otherwise this thing is a super cool tool. Of course it could be improved, but which tool isn't?

**Comment by minicrapsy** [comment]
Post a example please

**Comment by jam41803** [comment]
I think they're talking about subreddits based on stories like r/ProRevenge and r/NuclearRevenge

**Comment by swoker** [comment]
have you tried to set `storymode=true` in `config.toml`? That should be exactly hat you're looking for

**Comment by CiaranMcKeown21** [comment]
Did anyone find a solution to this?
