### ISSUE TITLE
Question: How do i add a watermark to the video?

### ISSUE THREAD

**Issue by CJthisis** [elebumm/RedditVideoMakerBot#1148]
I tried to read the code itself to learn this, but I am not particularly good at that.

How do I add the watermark?

**Comment by BluePlattypus** [comment]
```
from pyffmpeg import FFmpeg

ff = FFmpeg()
ff.options("-i input.mp4 -i watermark.png -filter_complex overlay=1500:10 output.mp4")
```

**Comment by JasonLovesDoggo** [comment]
There already is one. Why do you want to add another

**Comment by CJthisis** [comment]
> There already is one. Why do you want to add another 

I mean there is no guide to do a watermark and no setting in toml.config that suggests how to add one. 

Where do I have to put an image so that is is recognized as a watermark, and where do I change the position?

**Comment by JasonLovesDoggo** [comment]
> > There already is one. Why do you want to add another 
> 
> I mean there is no guide to do a watermark and no setting in toml.config that suggests how to add one. 
> 
> Where do I have to put an image so that is is recognized as a watermark, and where do I change the position?

Again you have not answered my question Why would you want to The whole purpose of the watermark is to prevent copyright strikes for the background video creators and not designed for you to change
