### ISSUE TITLE
Issue when running main.py

### ISSUE THREAD

**Issue by Subbwae** [elebumm/RedditVideoMakerBot#115]
![image](https://user-images.githubusercontent.com/46504443/171504296-ca640e91-9edf-4e2a-876f-62cf800f9fc1.png)

After installing everything and running it it gets to here and stops. Don't know why,

**Comment by andrewweir410** [comment]
Yeah I have the same problem.

**Comment by Hen105** [comment]
Same is there a fix?

**Comment by Hen105** [comment]
but mine just crashes before i can take a screenshot

**Comment by Subbwae** [comment]
Turning off 2 factor authentication fixed that issue, but another arose
