### ISSUE TITLE
Temp Files Not Removed After Video Completed

### ISSUE THREAD

**Issue by coopermarino** [elebumm/RedditVideoMakerBot#1152]
**Describe the bug**
After a video is produced the temp file containing the video files still persists 

**To Reproduce**

Run bot with current version (2.4.2)

**Expected behavior**
Expected behavior, temp file to be removed after video is saved to /results/{subreddit}

**System:**

- Python Version: 3.10.6
- OS: Win 10
- App version / Branch: Latest (2.4.2)

**Comment by JasonLovesDoggo** [comment]
It clears if it's needed this does not break a single thing
