### ISSUE TITLE
Ability to make shorter videos

### ISSUE THREAD

**Issue by KaranKapur123** [elebumm/RedditVideoMakerBot#1155]
Is there any way to set the maximum length of the video?

**Comment by KaranKapur123** [comment]
By this i mean reducing it, not increasing the length .

**Comment by JasonLovesDoggo** [comment]
Yep engine wrapper.py

**Comment by Leon7810** [comment]
`DEFAULT_MAX_LENGTH: int = 50  # video length variable`

@JasonLovesDoggo, int 50 means 50 seconds or?

**Comment by JasonLovesDoggo** [comment]
> `DEFAULT_MAX_LENGTH: int = 50  # video length variable`
> 
> @JasonLovesDoggo, int 50 means 50 seconds or?

MHM
