### ISSUE TITLE
Select background video from file

### ISSUE THREAD

**Issue by ic3dm4ng0** [elebumm/RedditVideoMakerBot#1159]
**Is your feature request related to a problem? Please describe.**
YouTube (which is where it gets the parkour from) is blocked on my WiFi by my parents.

**Describe the solution you'd like**
Because of this, I think it would be very helpful if you could add an option to select background footage from a file, allowing for more variation in videos (maybe putting something like a waterfall that gets looped over and over?)

**Describe alternatives you've considered** (optional)
I have tried modifying the code, but I'm stupid and can't figure out which file and line to change.

**Comment by jam41803** [comment]
Use a vpn

**Comment by ic3dm4ng0** [comment]
> Use a vpn

The reason I want to choose background footage from a file is not just because of the block. It is to allow more variation in videos and more customization in the program. It is also very easy for my parents to find out if I am using a vpn, which they have blocked so I cannot use it anyway.

**Comment by AcidClown** [comment]
bro just use any mp4 file but change the name to "bbswitzer-parkour.mp4" and put it in the backgrounds folder
Then choose the Minecraft option in your settings

**Comment by Leon7810** [comment]
However it would be handy to make it optionable

**Comment by fin-github** [comment]
> However it would be handy to make it optionable

It is inside of the GUI version of RedditVideoMakerBot. But I can make it custom. Idk! If you want to have a variety of backgrounds just tell me and ill add custom backgrounds!

**Comment by fin-github** [comment]
> > However it would be handy to make it optionable
> 
> It is inside of the GUI version of RedditVideoMakerBot. But I can make it custom. Idk! If you want to have a variety of backgrounds just tell me and ill add custom backgrounds!

Sorry! I said misinformation. Its already in it while I was making this possible. Check the lastest version!

**Comment by woahhjack** [comment]
Possible to include battlebit footage?
