### ISSUE TITLE
requirements.txt no such file directory error, playwright is not pre installed and even if i pip install it it still throws error.

### ISSUE THREAD

**Issue by Overpaint** [elebumm/RedditVideoMakerBot#1161]
error when i try to install requirements.txt:
![image](https://user-images.githubusercontent.com/111278577/184617938-25fb5655-054a-4add-8027-e8fbf9859757.png)

error that happens when i run command: python -m playwright install and python -m playwright install-deps:
![image](https://user-images.githubusercontent.com/111278577/184617363-6cb8fbd6-d582-40ac-8e76-eaed30f362b3.png)

Screenshots:
trying to pip install playwright:
![image](https://user-images.githubusercontent.com/111278577/184616480-424b84f1-2f33-464c-9c16-f3ee38e61c38.png)
![image](https://user-images.githubusercontent.com/111278577/184616575-edc2267c-91ef-4390-a531-5f926e2a306d.png)
![image](https://user-images.githubusercontent.com/111278577/184616777-c231e897-b5c3-49ce-b087-14b67e385661.png)

System:
- Python Version: 3.10.2
- OS: Windows 10

Additional context:
im using venv while using this, and i haven't and don't want to try doing it without virtual environment. tried downgrading pip and trying to install all of them(did not work). i think i did every possible solutions i saw on google and still nothing.

**Comment by mattsegura** [comment]
did you try pip3 install? you're telling it to install via python2...

**Comment by Overpaint** [comment]
> Yeah i tried

**Comment by MarcosNovelli** [comment]
Have you tried installing wheel before trying to install playwright? Since it says it'll use "setup.py install" since "wheel" is not installed. Also I tried installing playwright with anaconda and it worked perfectly, have you tried using it?
