### ISSUE TITLE
python requirement/match statement

### ISSUE THREAD

**Issue by funkyrice** [elebumm/RedditVideoMakerBot#1162]
The documentation states python 3.9.0+ as a requirement, but subreddit.py uses a match statement on line 44 which is not supported by python 3.9. so either the match statement needs to be changed to if else, or the required python version should be 3.10

**Comment by StopmotionSimonYT** [comment]
Correct, but it is already fixed. The use of the match statement is removed in the develop branch. So it will be pushed to the main branch by the new update.

**Comment by funkyrice** [comment]
That makes more sense. Thanks

**Comment by Freddy1547** [comment]
Hi. Sorry to ask, but just to clarify: would the problem be fixed, if I only have Python 3.10 installed on my system?

**Comment by StopmotionSimonYT** [comment]
> Hi. Sorry to ask, but just to clarify: would the problem be fixed, if I only have Python 3.10 installed on my system?

Yes!
