### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Abdulai123** [elebumm/RedditVideoMakerBot#1163]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "/home/abdulai/bot/RedditVideoMakerBot-master/reddit/subreddit.py", line 44
    match e.response.status_code:
          ^
SyntaxError: invalid syntax

**System (please complete the following information):**

- Python Version: [e.g. Python 3.6]
- OS: [e.g. Windows 11]
- App version / Branch [e.g. latest, V2.0, master, develop ]

**Additional context**

**Comment by funkyrice** [comment]
This is because match is not supported by python 3.9. The error is fixed in the develop branch and will soon be committed to master. You can wait for it to be committed or just use the develop branch

**Comment by StopmotionSimonYT** [comment]
> This is because match is not supported by python 3.9. The error is fixed in the develop branch and will soon be committed to master. You can wait for it to be committed or just use the develop branch

Thank you for your explanation! You can also update to python 3.10

**Comment by Freddy1547** [comment]
> This is because match is not supported by python 3.9. The error is fixed in the develop branch and will soon be committed to master. You can wait for it to be committed or just use the develop branch

How to use the develop branch?

**Comment by StopmotionSimonYT** [comment]
Press the button 'master' like from the image.
`![Show-a-list-of-branches..png](https://user-images.githubusercontent.com/65854503/185229406-2246e339-e7e5-4f1f-93bc-79416e401939.png)`
Then press the develop branch and download as an zip.
