### ISSUE TITLE
post title with link tries to fetch thumbnail image

### ISSUE THREAD

**Issue by lamasterso** [elebumm/RedditVideoMakerBot#1166]
**Describe the bug**
when a post has a link, in the post title "not in comments", the bot takes a screenshot of an empty thumbnail image.

it would be great, to either remove the link from the title or fetch the thumbnail image rather than displaying an empty image box beside the text.

**Comment by StopmotionSimonYT** [comment]
Hi, thanks for reporting the bug! Could you give an example post so we can fix it? 
Thanks in advance.
