### ISSUE TITLE
Add Compatibility for New Trend

### ISSUE THREAD

**Issue by devium335** [elebumm/RedditVideoMakerBot#1168]
**Is your feature request related to a problem? Please describe.**

There is a new trend where the bot reads out just the post from r/AmIThe***Hole

**Describe the solution you'd like**

A option in the setup gui to configure it like that

**Describe alternatives you've considered** (optional)

**Additional context** (optional)

**Comment by StopmotionSimonYT** [comment]
You can edit the subreddit in the config.toml!

**Comment by techpluscraft** [comment]
Yes but it only shows the title and it shows comments

**Comment by devium335** [comment]
> You can edit the subreddit in the config.toml!

The problem is the new style includes the title and description but not the comments

**Comment by StopmotionSimonYT** [comment]
We are working on a story mode (so it reads the description of the post)

**Comment by devium335** [comment]
> We are working on a story mode (so it reads the description of the post)

Awesome! Is there a way to turn of comment reading?

**Comment by StopmotionSimonYT** [comment]
I think so

**Comment by StopmotionSimonYT** [comment]
> > I think so
> 
> Do you have to manually or is it an option?

It is a function of the story mode but we are still working on it

**Comment by devium335** [comment]
> It is a function of the story mode but we are still working on it

Ok, how close is it to being finished?

**Comment by StopmotionSimonYT** [comment]
> > It is a function of the story mode but we are still working on it
> 
> Ok, how close is it to being finished?

I don't know

**Comment by devium335** [comment]
> > > It is a function of the story mode but we are still working on it
> > 
> > 
> > Ok, how close is it to being finished?
> 
> I don't know

Is there a PR or fork with it?

**Comment by JasonLovesDoggo** [comment]
> > > > It is a function of the story mode but we are still working on it
> > > 
> > > 
> > > Ok, how close is it to being finished?
> > 
> > I don't know
> 
> Is there a PR or fork with it?

Not yet but you're welcome to make one

**Comment by CJthisis** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> 
> 
> There is a new trend where the bot reads out just the post from r/AmIThe***Hole
> 
> 
> 
> **Describe the solution you'd like**
> 
> A clear and concise description of what you want to happen.
> 
> 
> 
> A option in the setup gui to configure it like that
> 
> 
> 
> **Describe alternatives you've considered** (optional)
> 
> A clear and concise description of any alternative solutions or features you've considered.
> 
> 
> 
> **Additional context** (optional)
> 
> Add any other context or screenshots about the feature request here.
> 
> 

Set the Subreddit you want in config.toml and for AITA turn on storymode. That way only the post gets read.

**Comment by StopmotionSimonYT** [comment]
> Set the Subreddit you want in config.toml and for AITA turn on storymode. That way only the post gets read.

You're right. But it's not 100% working. The text is not fully displayed with large posts. That's because the screenshots aren't split up yet.

**Comment by JasonLovesDoggo** [comment]
> > Set the Subreddit you want in config.toml and for AITA turn on storymode. That way only the post gets read.
> 
> You're right. But it's not 100% working. The text is not fully displayed with large posts. That's because the screenshots aren't split up yet.
> 
> 

👍

**Comment by devium335** [comment]
> > Set the Subreddit you want in config.toml and for AITA turn on storymode. That way only the post gets read.
> 
> You're right. But it's not 100% working. The text is not fully displayed with large posts. That's because the screenshots aren't split up yet.
> 
> 

What file is the story mode in

**Comment by StopmotionSimonYT** [comment]
> > > Set the Subreddit you want in config.toml and for AITA turn on story mode. That way only the post gets read.
> > 
> > 
> > You're right. But it's not 100% working. The text is not fully displayed with large posts. That's because the screenshots aren't split up yet.
> 
> What file is the story mode in

You can set it to True in the config.toml. As mentioned before, it is not 100% working yet.

**Comment by devium335** [comment]
Can you guys add it to to-do and project board?
