### ISSUE TITLE
Change video name instead of overwriting the existing video?

### ISSUE THREAD

**Issue by Goodgamer78** [elebumm/RedditVideoMakerBot#117]
Hey, I've made a script to auto run the process. It can make a bunch of videos and is fully automatic. I'd like to have it be fully automatic although the existing video gets overwritten. Is there any way to have the video name change itself after completing so it won't overwrite it?

**Comment by JasonLovesDoggo** [comment]
sure. 
in [final_video.py L57](https://github.com/elebumm/RedditVideoMakerBot/blob/master/video_creation/final_video.py#L57) thats where the file name is picked  just replace final_video with {os.getenv("POST_ID")} 
and in [askreddit.py](https://github.com/elebumm/RedditVideoMakerBot/blob/master/reddit/askreddit.py) just add os.environ["POST_ID"] = str(submission) after L26

**Comment by JasonLovesDoggo** [comment]
then the file name would be the Reddit post's ID
(you can also replace submission with submission.title if you want the posts title instead of the id)

**Comment by JasonLovesDoggo** [comment]
or even easier but lame imo 
replace 
```
 final.write_videofile(
        "assets/final_video.mp4", fps=30, audio_codec="aac", audio_bitrate="192k"
    )
```
with 
```
 final.write_videofile(
        f"assets/{len(os.listdir('./assets'))}.mp4", fps=30, audio_codec="aac", audio_bitrate="192k"
    )
``` and the file names will be like 1.mp4, 2.mp4......

**Comment by FluffyUnicorn111** [comment]
I tried with the reddit post name but I get the below error:

`Traceback (most recent call last):
  File "C:\r\main.py", line 22, in <module>
    final_video = make_final_video(number_of_comments)
  File "C:\r\video_creation\final_video.py", line 57, in make_final_video
    f"assets/{len(os.listdir('./assets'))}.mp4", fps=30, audio_codec="aac", audio_bitrate="192k"
NameError: name 'os' is not defined`

**Comment by JasonLovesDoggo** [comment]
You have to import OS

**Comment by realdav2** [comment]
what do you mean by import os ? sorry im kinda new haha

**Comment by JasonLovesDoggo** [comment]
At the top of the file type
Import os

**Comment by realdav2** [comment]
oh perfect thank you seems to work although I am stugeling to get find an outrun solution like every 10 min or when its complete any idea on that ? Thanks in advance

**Comment by JasonLovesDoggo** [comment]
please clarify

**Comment by realdav2** [comment]
I mean if you might have an idea how to implement an end of autorun so every time it completes a video it directly starts a new one

**Comment by realdav2** [comment]
I mean if you might have an idea how to implement an end of autorun so every time it completes a video it directly starts a new one

**Comment by JasonLovesDoggo** [comment]
you could add os.system('python main.py') at the bottom of the main.py file in the if main block

**Comment by realdav2** [comment]
oh shit thx ill try it out later

**Comment by realdav2** [comment]
oh shit thx ill try it out later

**Comment by WordedOne** [comment]
> oh perfect thank you seems to work although I am stugeling to get find an outrun solution like every 10 min or when its complete any idea on that ? Thanks in advance
Where exactly did you put the Import OS command Im also very new to this

**Comment by mlvps** [comment]
I get this error message:
`Traceback (most recent call last):                                                                                                                                                                                     File "C:\Users\User\Desktop\RedditVideoMakerBot-master\main.py", line 7, in <module>                                                                                                                                   from video_creation.final_video import make_final_video                                                                                                                                                            File "C:\Users\User\Desktop\RedditVideoMakerBot-master\video_creation\final_video.py", line 58                                                                                                                         "results/{os.getenv("POST_ID")}.mp4", fps=30, audio_codec="aac", audio_bitrate="192k"                                                                                                                                                     ^                                                                                                                                                                                           SyntaxError: invalid syntax`
any ideas how to fix it?

**Comment by FreebieII** [comment]
Hi @Goodgamer78,


I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
