### ISSUE TITLE
Adding trackmania to the games list

### ISSUE THREAD

**Issue by Skinny957** [elebumm/RedditVideoMakerBot#1173]
**Is your feature request related to a problem? Please describe.*no its not related to a problem*

**Describe the solution you'd like**
i would like the game trackmania to be added to the list of background games
**Describe alternatives you've considered** (optional)

**Additional context** (optional)
preferably the new trackmania 2020 game

**Comment by StopmotionSimonYT** [comment]
You can add custom backgrounds! It's in the CONSTANTS.py file

**Comment by AcidClown** [comment]
bro just use any mp4 file but change the name to "bbswitzer-parkour.mp4" and put it in the backgrounds folder
Then choose the Minecraft option in your settings

**Comment by StopmotionSimonYT** [comment]
> bro just use any mp4 file but change the name to "bbswitzer-parkour.mp4" and put it in the backgrounds folder
> Then choose the Minecraft option in your settings
> 

That is also possible. But it is better to add it in the CONSTANTS.py. Because then the owner gets a little credit for the background. BTW: when the new release comes, it is much easier to add a custom background. Then you can simply edit it in the GUI.
