### ISSUE TITLE
Can't even run first command... "pip install -r requirements.txt" - SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Casquet12** [elebumm/RedditVideoMakerBot#1175]
Hi!

(I'm new using python and all this)

As you can see in the photo I can't even run the first command, always the same error, I saw some videos but nothing helps me there... I'm using the python 3.10 update.

![Error](https://user-images.githubusercontent.com/111464746/185244961-bac7c2bd-ed65-4301-b4ac-cbaf26fbd177.png)

The reposory had been clone, extract and all was done... I don't know what to do...

Hope someone can help me! =(

**Comment by AcidClown** [comment]
You need to go into the directory of which you extracted the bot to. Your welcome to dm on discord @JoshVear#9550

**Comment by hammamikhairi** [comment]
### Problem
You're executing `pip install -r requirements.txt` as if it was python code. That's because you've opened the python interpreter in cmd (probably by running `python3` prior to that).

### Solution
To solve this problem, you can either :
- Return to normal cmd by typing `exit()` in the interpreter (what you should do in your current position)
- Reopen cmd in the project directory and (before doing anything else) run `pip install -r requirements.txt`

**Comment by Casquet12** [comment]
> ### Problem
> You're executing `pip install -r requirements.txt` as if it was python code. That's because you've opened the python interpreter in cmd (probably by running `python3` prior to that).
> 
> ### Solution
> To solve this problem, you can either :
> 
> * Return to normal cmd by typing `exit()` in the interpreter (what you should do in your current position)
> * Reopen cmd in the project directory and (before doing anything else) run `pip install -r requirements.txt`

I think I'm stupid or something i miss =( 
When I use the cmd in the directory brings me another error: 

![3](https://user-images.githubusercontent.com/111464746/185408619-18c291e9-9397-4646-9325-3ae00306d91d.png)

It's saying it doesn't recognize the internal/external command, program or files executables.

It's probably so easy to do but I can't get it ;(

**Comment by hammamikhairi** [comment]
Don't worry, we've all been there. You have to install `pip` in order to use, it doesn't come with python by default.
open cmd and run `py -m ensurepip --upgrade`.

(also, mark my previous reply as the answer so that this issue closes)

**Comment by Casquet12** [comment]
> Don't worry, we've all been there. You have to install `pip` in order to use, it doesn't come with python by default. open cmd and run :
> 
> ```shell
> py -m ensurepip --upgrade
> ```
> 
> (also, mark my previous reply as the answer so that this issue closes)

The fact is that is already installed and I still have the problem =(

![image](https://user-images.githubusercontent.com/111464746/185457305-bd513e76-44bd-4d35-9fde-981ecf124a86.png)

**Comment by hammamikhairi** [comment]
here's my discord `Asuma#5625`, add me and we'll figure it out
