### ISSUE TITLE
16:9 resolution setting

### ISSUE THREAD

**Issue by Omgaa** [elebumm/RedditVideoMakerBot#1176]
I believe that we should be able to make a horizontal based video instead of just a short form video just because it would help people trying to make money once they are a little bigger from shorts and already have a fanbase.

I believe that we could make this happen by adding a setting in config.toml that is something like Full Length and it would make a video of a few different posts based on your configuration in config.toml.

I also think that we should have the option to disable the watermark since it is a considerable slowdown in the performance since 2.3 and a lot of background videos just require a link/credit from the creator in every description of the video.

**Comment by CJthisis** [comment]
OMG I would LOVE THIS! I have tried various methods to do this by myself, but with no luck.

**Comment by StopmotionSimonYT** [comment]
Thanks for the idea! I am working on a 16:9 function. But I think we don't disable the watermark. Because it is fair to give the creators credits for their videos. We're looking at why the watermark causes the performance slowdown.

**Comment by Omgaa** [comment]
> Thanks for the idea! I am working on a 16:9 function. But I think we don't disable the watermark. Because it is fair to give the creators credits for their videos. We're looking at why the watermark causes the performance slowdown.

Alright thank you for the reply and if you could make it an easily accessible feature be sure to tell me where to find it

**Comment by CJthisis** [comment]
> Thanks for the idea! I am working on a 16:9 function. But I think we don't disable the watermark. Because it is fair to give the creators credits for their videos. We're looking at why the watermark causes the performance slowdown.

Do you have a repo or fork with this implemented? Because I would love to maybe test the code and review it and stuff.

**Comment by StopmotionSimonYT** [comment]
> > Thanks for the idea! I am working on a 16:9 function. But I think we don't disable the watermark. Because it is fair to give the creators credits for their videos. We're looking at why the watermark causes the performance slowdown.
> 
> Do you have a repo or fork with this implemented? Because I would love to maybe test the code and review it and stuff.

I am working on it and when I am done you can test it. I also make a pull request for it so others can use it too!

**Comment by Furiousness** [comment]
Hey!

Any updates on this project?

**Comment by CJthisis** [comment]
@OpenSourceSimon Is this feature ever going to be implemented?

**Comment by OpenSourceSimon** [comment]
> @OpenSourceSimon Is this feature ever going to be implemented?

I think the feature is in the New-Webdriver branch, but that needs to be tested first. If that doesn't have bugs, this (and many other features) are gonna get merged.

**Comment by MarkelAdanez** [comment]
Is this already implemented?

**Comment by OpenSourceSimon** [comment]
> Is this already implemented?

Yes, in the develop branch. Feel free to test!
