### ISSUE TITLE
Text to speech only reads main title and not sub title of the post

### ISSUE THREAD

**Issue by LowOp** [elebumm/RedditVideoMakerBot#1178]
Have This Issue With Text To Speech That It Doesn't Read The Sub Titles Of the Reddit Posts
Any Fix Of This Problem As It Is Quite Annoying 
Attached the image 

![vlcsnap-2022-08-18-21h48m07s403](https://user-images.githubusercontent.com/111524277/185446607-7690fa06-2189-4690-844f-51e55cc952d2.png)

Thanks

**Comment by StopmotionSimonYT** [comment]
Hi, that is not a feature yet. We are working on a story mode. So it reads the post description.

**Comment by amjadaslan** [comment]
Hi, this issue has been closed, was it implemented? as i have story mode enabled yet the result video only shows the description but doesn't read it.

**Comment by JasonLovesDoggo** [comment]
> Hi, this issue has been closed, was it implemented? as i have story mode enabled yet the result video only shows the description but doesn't read it.

Do you know How many duplicates there are..
