### ISSUE TITLE
The ID of your Reddit app of SCRIPT type

### ISSUE THREAD

**Issue by Nielzaclord** [elebumm/RedditVideoMakerBot#1179]
When I run the code, it displays this :

The ID of your Reddit app of SCRIPT type
Example: fFAGRNJru1FTz70BzhT3Zg
Non-optional client_id=

Where I can find-it ?

**Comment by jam41803** [comment]
https://www.reddit.com/prefs/apps

Go to this and make a personal script. You can put a random url as the link.
Once you've finished, click on it to find your client id(under the name) and the secret
