### ISSUE TITLE
Why is it asking me for my reddit account password?

### ISSUE THREAD

**Issue by Vepsie** [elebumm/RedditVideoMakerBot#1183]
![image](https://user-images.githubusercontent.com/108100601/185672423-b466062a-da67-4a50-89a5-e79eabd77704.png)

**Comment by rohitkrishna094** [comment]
were you able to figure this out? Is it for playwright? Seems risky that this is asking for password and I see no mention of it on Readme.

**Comment by MasKhan20** [comment]
What if you log in through google?
I'll have to make a new account for this.
