### ISSUE TITLE
Setting in the Config File to set a new result folder

### ISSUE THREAD

**Issue by holzhaker1** [elebumm/RedditVideoMakerBot#1185]
**Describe the solution you'd like**
Setting in the Config File to set a new result folder

Its pretty annoying for automation purposes because the folder changes sometimes. also clicking through all those folders is annoying when you have to do it a lot

**Comment by JasonLovesDoggo** [comment]
.... WHAT?  🤣

**Comment by JasonLovesDoggo** [comment]
> > .... WHAT? 🤣
> 
> in the config.toml:
> 
> Folder for results: "the/folder/I/want/my/results/at/"

What's the problem with the current system though........

**Comment by JasonLovesDoggo** [comment]
Like for automation assuming you are using Python


Have you never heard of os.listdir() or glob.glob?

**Comment by holzhaker1** [comment]
I am using os.listdir() but if i am changing the subreddits, the bot creates a new folder where it dumps the results, thats my main problem.

**Comment by JasonLovesDoggo** [comment]
> I am using os.listdir() but if i am changing the subreddits, the bot creates a new folder where it dumps the results, thats my main problem.

Yes cuz it's designed to do that That's not a problem....

The only problem here is the fact that you're being lazy with either

1. Coding your automation thing So that it reads config.toml and sees what subreddit is being used

Or 

2. You can't bother to change a single variable when you change the subreddit

**Comment by holzhaker1** [comment]
I know thats its designed to do that, but the design itself is bs. It just doesnt help 99% of people. Theres probably 1% who want their videos split by subreddit. Its just a shitty design aspect which isnt as userfriendly as having an option to dump all the videos into one folder, nothing to do with being lazy when stuff is being overcomplicated
