### ISSUE TITLE
Problem occuring when I try to make a video

### ISSUE THREAD

**Issue by ElectricIceBird** [elebumm/RedditVideoMakerBot#1186]
Traceback (most recent call last):
  File "C:\Users\WHO\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 972, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\WHO\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\WHO\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\WHO\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 70, in <module>
    main()
  File "main.py", line 48, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\WHO\Desktop\Stuff\RedditVideoMakerBot-master\video_creation\voices.py", line 59, in save_text_to_mp3
    random_speaker=False,
  File "C:\Users\WHO\Desktop\Stuff\RedditVideoMakerBot-master\TTS\POLLY.py", line 61, in tts
    if response.json()["error"] == "Text length is too long!":
  File "C:\Users\WHO\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 976, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
**System (please complete the following information):**

- Python Version: [e.g. Python 3.6]
- OS: [e.g. Windows 11]
- App version / Branch [e.g. latest, V2.0, master, develop ]

**Additional context**
This is what I have been getting

**Comment by StopmotionSimonYT** [comment]
The comment text is too long. You can adjust it in the config.toml.

**Comment by ElectricIceBird** [comment]
How much should I increase it?

**Comment by StopmotionSimonYT** [comment]
What is the value you have now? Btw you need to decrease it.

**Comment by ElectricIceBird** [comment]
500

**Comment by StopmotionSimonYT** [comment]
Then you can try 250

**Comment by ElectricIceBird** [comment]
also what is this storymode thing?

**Comment by ElectricIceBird** [comment]
giving me same error

**Comment by StopmotionSimonYT** [comment]
> also what is this storymode thing?
> 
> 

Do you have that on? Because that is not yet implemented. It is that the program only reads the title and description.

**Comment by ElectricIceBird** [comment]
Oh ok

**Comment by ElectricIceBird** [comment]
I just turned it on to check it out

**Comment by StopmotionSimonYT** [comment]
And does it work now?

**Comment by ElectricIceBird** [comment]
nope gave me a error

**Comment by StopmotionSimonYT** [comment]
> nope gave me a error
> 

The same?

**Comment by ElectricIceBird** [comment]
Wait Oh it my fault need to restart the cmd

**Comment by StopmotionSimonYT** [comment]
> Yes the same one

Weird, maybe use an other TTS

**Comment by ElectricIceBird** [comment]
TTS?

**Comment by ElectricIceBird** [comment]
How can I do that?

**Comment by StopmotionSimonYT** [comment]
TTS is the software that speaks the text (Text to speech). You can change it in the config.toml by voice_choice

**Comment by ElectricIceBird** [comment]
Wait I am Config.py not config.toml where is that?

**Comment by StopmotionSimonYT** [comment]
> Wait I am Config.py not config.toml where is that?

In the main folder where the main.py also is

**Comment by ElectricIceBird** [comment]
![explorer_nMWXdXzwhO](https://user-images.githubusercontent.com/67385565/185734627-0632cd17-3717-408c-a6f8-afc3790e45bc.jpg)

**Comment by ElectricIceBird** [comment]
nothing here

**Comment by StopmotionSimonYT** [comment]
What version are you using? Because you have a .env file for the settings and the new versions have a config.toml

**Comment by ElectricIceBird** [comment]
maybe that is why I am having problems let me download the new version

**Comment by ElectricIceBird** [comment]
File "main.py", line 9, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "C:\Users\WHO\Desktop\bob\RedditVideoMakerBot-2.4.2\RedditVideoMakerBot-2.4.2\reddit\subreddit.py", line 44
    match e.response.status_code: why is this happening

**Comment by StopmotionSimonYT** [comment]
>   File "main.py", line 9, in <module>
>     from reddit.subreddit import get_subreddit_threads
>   File "C:\Users\WHO\Desktop\bob\RedditVideoMakerBot-2.4.2\RedditVideoMakerBot-2.4.2\reddit\subreddit.py", line 44
>     match e.response.status_code: why is this happening

That is because you don't have python 3.10. you need to upgrade or switch to the develop branch where it is fixed

**Comment by ElectricIceBird** [comment]
I install and got this error Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "C:\Users\WHO\Desktop\bob\RedditVideoMakerBot-2.4.2\RedditVideoMakerBot-2.4.2\reddit\subreddit.py", line 44
    match e.response.status_code:
          ^
SyntaxError: invalid syntax

**Comment by StopmotionSimonYT** [comment]
> I install and got this error Traceback (most recent call last):
>   File "main.py", line 9, in <module>
>     from reddit.subreddit import get_subreddit_threads
>   File "C:\Users\WHO\Desktop\bob\RedditVideoMakerBot-2.4.2\RedditVideoMakerBot-2.4.2\reddit\subreddit.py", line 44
>     match e.response.status_code:
>           ^
> SyntaxError: invalid syntax

Then you are not using python 3.10

**Comment by ElectricIceBird** [comment]
I just installed it

**Comment by StopmotionSimonYT** [comment]
The command to start the script is `python3 main.py` instead of `python main.py`. Maybe you did that wrong

**Comment by ElectricIceBird** [comment]
Now it is saying I do not have it install even though I have it installed

**Comment by StopmotionSimonYT** [comment]
> Now it is saying I do not have it install even though I have it installed

For me it was fixed by installing it with the Microsoft store.

**Comment by ElectricIceBird** [comment]
prawcore not found

**Comment by StopmotionSimonYT** [comment]
> prawcore not found
> 

Did you install the dependencies with `pip3 install -r requirements.txt`

**Comment by ElectricIceBird** [comment]
Done it still giving me error

**Comment by StopmotionSimonYT** [comment]
> Done it still giving me error
> 

Is it with the same post or does the error come every time

**Comment by ElectricIceBird** [comment]
no I am getting prawcore error

**Comment by StopmotionSimonYT** [comment]
> no I am getting prawcore error

Sorry, have you tried the command `pip3 install prawcore`

**Comment by ElectricIceBird** [comment]
Requirement already satisfied: requests<3.0,>=2.6.0 in c:\users\who\appdata\local\programs\python\python310\lib\site-packages (from prawcore) (2.28.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\who\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0,>=2.6.0->prawcore) (2022.6.15)
Requirement already satisfied: idna<4,>=2.5 in c:\users\who\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0,>=2.6.0->prawcore) (3.3)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\who\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0,>=2.6.0->prawcore) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\who\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0,>=2.6.0->prawcore) (1.26.11)

**Comment by StopmotionSimonYT** [comment]
> Requirement already satisfied: requests<3.0,>=2.6.0 in c:\users\who\appdata\local\programs\python\python310\lib\site-packages (from prawcore) (2.28.1)
> Requirement already satisfied: certifi>=2017.4.17 in c:\users\who\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0,>=2.6.0->prawcore) (2022.6.15)
> Requirement already satisfied: idna<4,>=2.5 in c:\users\who\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0,>=2.6.0->prawcore) (3.3)
> Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\who\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0,>=2.6.0->prawcore) (2.1.1)
> Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\who\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0,>=2.6.0->prawcore) (1.26.11)
> 

That's weird, but if that doesn't work then I don't know how to help you. I am sorry.

**Comment by ElectricIceBird** [comment]
Ok I am using the old version since atleast I know it works how can I make it skip a thread?

**Comment by StopmotionSimonYT** [comment]
> Ok I am using the old version since atleast I know it works how can I make it skip a thread?
> 

I don't know which version but if it has a video_creation/data/videos.json then you can add the id in that.

**Comment by SanmayAvhad** [comment]
I encountered the same error. I upgraded my python version to 3.10, then installed requirements and also pip -m playwright install and pip -m playwright install-deps. Now it works

**Comment by ProffessorPolo** [comment]
if you want to use the program with python3.9 or lower change this code
```
match e.response.status_code:
          case 401:
                   print("Invalid credentials - please check them in config.toml")
```
to this code
```
if (e.response.status_code == 401):
         print("Invalid credentials - please check them in config.toml")
```

you can find it in reddit/subreddit.py
