### ISSUE TITLE
Not able to perform SSL handshake[SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by anshumanthakur** [elebumm/RedditVideoMakerBot#1187]
**Describe the bug**
I have given all the basic credentials and my config.toml file is also set but I am not able to fetch the subreddit posts due to SSL certification error

**To Reproduce**
Run python main.py

**Expected behavior**
A video being created.

**Screenshots**
![image](https://user-images.githubusercontent.com/22526030/185748660-6d7a3e53-7af6-4b3c-820d-fce45b17b55a.png)

**System (please complete the following information):**

- Python Version: [e.g. Python 3.9.6]
- OS: [e.g. Windows 10]
- App version / Branch [e.g. latest, V2.0, master, develop ]

**Comment by StopmotionSimonYT** [comment]
I found this article on internet and I think it will fix the problem
https://kinsta.com/knowledgebase/ssl-handshake-failed/
