### ISSUE TITLE
When i run main.py it says No module named 'prawcore'

### ISSUE THREAD

**Issue by FREEFNACCOUNT** [elebumm/RedditVideoMakerBot#1189]
When i run main.py (python main.py) i get an error 
Traceback (most recent call last):
  File "C:\Users\kentfn\Desktop\RedditVideoMakerBot-master\main.py", line 7, in <module>
    from prawcore import ResponseException
ModuleNotFoundError: No module named 'prawcore'
can someone solve this issue

**Comment by MarcosNovelli** [comment]
Have you already installed all the requirements before trying to run the code??

**Comment by woutklee0202** [comment]
I had the same problem, just reinstall python.

**Comment by Zitrone-0987** [comment]
Pip install prawcore

Keep spamming pip install for all problems

**Comment by CJthisis** [comment]
@FREEFNACCOUNT 

Can you close this as completed?

**Comment by xav123q** [comment]
I have this problem and I haven't been able to fix it

**Comment by OpenSourceSimon** [comment]
Pip install praw
