### ISSUE TITLE
Lots of Issues with pip3 install -r requirements.txt

### ISSUE THREAD

**Issue by herohunterttv** [elebumm/RedditVideoMakerBot#119]
When going to install, the computer will install most of the project but then try to install files that it cannot find, resulting in errors. I'm new and don't know how to fix this haha pls help
![Screenshot 2022-06-01 172442](https://user-images.githubusercontent.com/106681711/171512017-02a52d49-894d-40b8-b1f0-97f01d38f414.png)
![Screenshot 2022-06-01 172354](https://user-images.githubusercontent.com/106681711/171512028-a1ee5860-04a2-4f87-b9d4-12ebe59e67a8.png)
.

**Comment by Vexirale** [comment]
thought it was just me but im just getting this
![image](https://user-images.githubusercontent.com/73032255/171512243-faccccd6-673d-4815-a627-e6143cbe710d.png)

**Comment by zaintechsavvy** [comment]
Getting the same issue here.

**Comment by lesterrar** [comment]
try browsing the closed issues and also try referring to this #60

**Comment by zaintechsavvy** [comment]
Thanks so much! It has worked for me!

**Comment by FreebieII** [comment]
Hi @herohunterttv.

You can install a new version of the code as it's been fixed, or refer to #60  (not recommended, rather get new code!)

I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
