### ISSUE TITLE
Is there a way to select only comments with a minimum number of characters?

### ISSUE THREAD

**Issue by DumbravaRobert** [elebumm/RedditVideoMakerBot#1190]
**Is your feature request related to a problem? Please describe.**
I would like to select only comments that are a at list 50 characters long. So Instead of one word comments, the bot will search for longer comments.
Example of comments that I dont want to use:
- Alien
- Yes
- Jhon
- oh no
- just do it

**Comment by JasonLovesDoggo** [comment]
Pretty simple check for you to implement yourself Just go to subreddit.py and add a check before adding the comment to the stack
