### ISSUE TITLE
[Bug]: Can not start bot

### ISSUE THREAD

**Issue by PerkaZmaj** [elebumm/RedditVideoMakerBot#1195]
### Describe the bug

When i first time setup bot, everything was fine, it creates 2 videos, I go to sleep and next morning I face this error, try to reinstall, try to use Microsoft store version etc
https://prnt.sc/vzTuh4dej03j

### Reproduction Steps

Install

### Expected behavior

Start creating videos

### Screenshots

https://prnt.sc/vzTuh4dej03j

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by StopmotionSimonYT** [comment]
Hi,
I don't know why the error comes. The problem may be because the TTS isn't accessible. But I do know how to solve it. I think the problem is solved when you use an other TTS. Can you let me know if it works?

**Comment by PerkaZmaj** [comment]
I select Google Translate, it works now but it's terrible..

**Comment by PerkaZmaj** [comment]
> Hi, I don't know why the error comes. The problem may be because the TTS isn't accessible. But I do know how to solve it. I think the problem is solved when you use an other TTS. Can you let me know if it works
it works now but it's terrible..
Thanks for help
Btw, how i can know how each TTS sounds? Can i find that somewhere so i can choose voice which i like?

**Comment by StopmotionSimonYT** [comment]
> 
> it works now but it's terrible..
> Thanks for help
> Btw, how i can know how each TTS sounds? Can i find that somewhere so i can choose voice which i like?

Hi, no problem I'm happy to help! More people have this issue so I will investigate it further. You can hear the sounds in the documentation under examples.
