### ISSUE TITLE
[Bug]: Error after Saving text to MP3 files...

### ISSUE THREAD

**Issue by Zalluxia** [elebumm/RedditVideoMakerBot#1198]
### Describe the bug

When running the main.py it stops after saving text to MP3 files...
It gives the following error codes.

Traceback (most recent call last):
  File "C:\Users\PC\Documents\RedditVideoMakerBot-2.4.2\main.py", line 83, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\PC\Documents\RedditVideoMakerBot-2.4.2\main.py", line 62, in run_many
    main()
  File "C:\Users\PC\Documents\RedditVideoMakerBot-2.4.2\main.py", line 48, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\PC\Documents\RedditVideoMakerBot-2.4.2\video_creation\voices.py", line 50, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\PC\Documents\RedditVideoMakerBot-2.4.2\TTS\engine_wrapper.py", line 61, in run
    self.call_tts("title", process_text(self.reddit_object["thread_title"]))
  File "C:\Users\PC\Documents\RedditVideoMakerBot-2.4.2\TTS\engine_wrapper.py", line 117, in call_tts
    self.tts_module.run(text, filepath=f"{self.path}/{filename}.mp3")
  File "C:\Users\PC\Documents\RedditVideoMakerBot-2.4.2\TTS\TikTok.py", line 94, in run
    vstr = [r.json()["data"]["v_str"]][0]
KeyError: 'data'

### Reproduction Steps

Run on windows 11
Python 3.10
Subreddit: AskReddit

config.TOML settings:

[settings]
allow_nsfw = true
theme = "dark"
times_to_run = 1
opacity = 0.9
transition = 0.2
storymode = false

[settings.background]
background_choice = "minecraft"

[settings.tts]
voice_choice = "tiktok"
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_006"
python_voice = "1"
py_voice_num = "2"

[reddit.creds]
client_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
client_secret = "xxxxxxxxxxxxxxxxxx"
username = "xxxxxxxxxxxxxx"
password = "xxxxxxxxxxx"
2fa = false

[reddit.thread]
random = false
subreddit = "AskReddit"
post_id = ""
max_comment_length = 500
post_lang = ""
min_comments = 20

### Expected behavior

Running and saving the video?

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by PerkaZmaj** [comment]
I think this is the same error like I have
When CMD gives you option  Google Translate | TikTok etc, do not use TikTok,  it seems to be broken
I hope it helps you

**Comment by joshcaarve** [comment]
I'm seeing this error too. I switched from `tiktok` to `googletranslate` and it has resolved my problem.

**Comment by StopmotionSimonYT** [comment]
The TikTok TTS has a bug and we are working on it.

**Comment by ObviousNiNi** [comment]
I have this same problem but it's just when I change the post_lang to "es". Even changed the tiktok voice to es, but still got the same bug.
