### ISSUE TITLE
error: legacy-install-failure

### ISSUE THREAD

**Issue by OfficialLexthor** [elebumm/RedditVideoMakerBot#12]
Hi,

I get this error when i try to call "-m pip install -r requirements.txt"

LOG: 

Collecting appdirs==1.4.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting black==20.8b1
  Using cached black-20.8b1-py3-none-any.whl
Collecting certifi==2021.10.8
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting charset-normalizer==2.0.12
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting click==7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting commonmark==0.9.1
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Collecting decorator==4.4.2
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting flake8==3.8.3
  Using cached flake8-3.8.3-py2.py3-none-any.whl (72 kB)
Collecting greenlet==1.1.2
  Using cached greenlet-1.1.2-cp310-cp310-macosx_10_14_x86_64.whl (92 kB)
Collecting gTTS==2.2.4
  Using cached gTTS-2.2.4-py3-none-any.whl (26 kB)
Collecting idna==3.3
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting imageio==2.19.2
  Using cached imageio-2.19.2-py3-none-any.whl (3.4 MB)
Collecting imageio-ffmpeg==0.4.7
  Using cached imageio_ffmpeg-0.4.7-py3-none-macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (22.5 MB)
Collecting mccabe==0.6.1
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting moviepy==1.0.3
  Using cached moviepy-1.0.3.tar.gz (388 kB)
  Preparing metadata (setup.py) ... done
Collecting mutagen==1.45.1
  Using cached mutagen-1.45.1-py3-none-any.whl (218 kB)
Collecting mypy-extensions==0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting numpy==1.22.3
  Using cached numpy-1.22.3-cp310-cp310-macosx_10_14_x86_64.whl (17.6 MB)
Collecting pathspec==0.8.0
  Using cached pathspec-0.8.0-py2.py3-none-any.whl (28 kB)
Collecting Pillow==9.1.1
  Using cached Pillow-9.1.1-cp310-cp310-macosx_10_10_x86_64.whl (3.1 MB)
Collecting playwright==1.22.0
  Using cached playwright-1.22.0-py3-none-macosx_11_0_universal2.whl (29.9 MB)
Collecting praw==7.6.0
  Using cached praw-7.6.0-py3-none-any.whl (188 kB)
Collecting prawcore==2.3.0
  Using cached prawcore-2.3.0-py3-none-any.whl (16 kB)
Collecting proglog==0.1.10
  Using cached proglog-0.1.10-py3-none-any.whl (6.1 kB)
Collecting pycodestyle==2.6.0
  Using cached pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
Collecting pyee==8.1.0
  Using cached pyee-8.1.0-py2.py3-none-any.whl (12 kB)
Collecting pyflakes==2.2.0
  Using cached pyflakes-2.2.0-py2.py3-none-any.whl (66 kB)
Collecting Pygments==2.12.0
  Using cached Pygments-2.12.0-py3-none-any.whl (1.1 MB)
Collecting python-dotenv==0.20.0
  Using cached python_dotenv-0.20.0-py3-none-any.whl (17 kB)
Collecting pytube==12.1.0
  Using cached pytube-12.1.0-py3-none-any.whl (56 kB)
Collecting regex==2020.10.15
  Using cached regex-2020.10.15.tar.gz (690 kB)
  Preparing metadata (setup.py) ... done
Collecting requests==2.27.1
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting rich==12.4.4
  Using cached rich-12.4.4-py3-none-any.whl (232 kB)
Collecting six==1.16.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting toml==0.10.1
  Using cached toml-0.10.1-py2.py3-none-any.whl (19 kB)
Collecting tqdm==4.64.0
  Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
Collecting typed-ast==1.4.1
  Using cached typed_ast-1.4.1.tar.gz (208 kB)
  Preparing metadata (setup.py) ... done
Collecting typing_extensions==4.2.0
  Using cached typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Collecting update-checker==0.18.0
  Using cached update_checker-0.18.0-py3-none-any.whl (7.0 kB)
Collecting urllib3==1.26.9
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting websocket-client==1.3.2
  Using cached websocket_client-1.3.2-py3-none-any.whl (54 kB)
Collecting websockets==10.1
  Using cached websockets-10.1-cp310-cp310-macosx_10_9_x86_64.whl (96 kB)
Using legacy 'setup.py install' for moviepy, since package 'wheel' is not installed.
Using legacy 'setup.py install' for regex, since package 'wheel' is not installed.
Using legacy 'setup.py install' for typed-ast, since package 'wheel' is not installed.
Installing collected packages: typed-ast, toml, regex, pyee, mypy-extensions, mccabe, commonmark, certifi, appdirs, websockets, websocket-client, urllib3, typing_extensions, tqdm, six, pytube, python-dotenv, Pygments, pyflakes, pycodestyle, Pillow, pathspec, numpy, mutagen, imageio-ffmpeg, idna, greenlet, decorator, click, charset-normalizer, rich, requests, proglog, playwright, imageio, flake8, black, update-checker, prawcore, moviepy, gTTS, praw
  Running setup.py install for typed-ast ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for typed-ast did not run successfully.
  │ exit code: 1
  ╰─> [84 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-3.10
      creating build/lib.macosx-10.9-universal2-3.10/typed_ast
      copying typed_ast/conversions.py -> build/lib.macosx-10.9-universal2-3.10/typed_ast
      copying typed_ast/__init__.py -> build/lib.macosx-10.9-universal2-3.10/typed_ast
      copying typed_ast/ast3.py -> build/lib.macosx-10.9-universal2-3.10/typed_ast
      copying typed_ast/ast27.py -> build/lib.macosx-10.9-universal2-3.10/typed_ast
      package init file 'ast3/tests/__init__.py' not found (or not a regular file)
      creating build/lib.macosx-10.9-universal2-3.10/typed_ast/tests
      copying ast3/tests/test_basics.py -> build/lib.macosx-10.9-universal2-3.10/typed_ast/tests
      running build_ext
      building '_ast27' extension
      creating build/temp.macosx-10.9-universal2-3.10
      creating build/temp.macosx-10.9-universal2-3.10/ast27
      creating build/temp.macosx-10.9-universal2-3.10/ast27/Custom
      creating build/temp.macosx-10.9-universal2-3.10/ast27/Parser
      creating build/temp.macosx-10.9-universal2-3.10/ast27/Python
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c ast27/Custom/typed_ast.c -o build/temp.macosx-10.9-universal2-3.10/ast27/Custom/typed_ast.o
      In file included from ast27/Custom/typed_ast.c:2:
      In file included from ast27/Include/Python-ast.h:3:
      ast27/Include/asdl.h:37:41: error: unknown type name 'PyArena'
      asdl_seq *asdl_seq_new(Py_ssize_t size, PyArena *arena);
                                              ^
      ast27/Include/asdl.h:38:49: error: unknown type name 'PyArena'
      asdl_int_seq *asdl_int_seq_new(Py_ssize_t size, PyArena *arena);
                                                      ^
      In file included from ast27/Custom/typed_ast.c:2:
      ast27/Include/Python-ast.h:398:63: error: unknown type name 'PyArena'
      mod_ty _Ta27_Module(asdl_seq * body, asdl_seq * type_ignores, PyArena *arena);
                                                                    ^
      ast27/Include/Python-ast.h:400:43: error: unknown type name 'PyArena'
      mod_ty _Ta27_Interactive(asdl_seq * body, PyArena *arena);
                                                ^
      ast27/Include/Python-ast.h:402:39: error: unknown type name 'PyArena'
      mod_ty _Ta27_Expression(expr_ty body, PyArena *arena);
                                            ^
      ast27/Include/Python-ast.h:404:65: error: unknown type name 'PyArena'
      mod_ty _Ta27_FunctionType(asdl_seq * argtypes, expr_ty returns, PyArena *arena);
                                                                      ^
      ast27/Include/Python-ast.h:406:37: error: unknown type name 'PyArena'
      mod_ty _Ta27_Suite(asdl_seq * body, PyArena *arena);
                                          ^
      ast27/Include/Python-ast.h:409:92: error: unknown type name 'PyArena'
                                decorator_list, string type_comment, int lineno, int col_offset, PyArena
                                                                                                 ^
      ast27/Include/Python-ast.h:413:68: error: unknown type name 'PyArena'
                             decorator_list, int lineno, int col_offset, PyArena *arena);
                                                                         ^
      ast27/Include/Python-ast.h:415:65: error: unknown type name 'PyArena'
      stmt_ty _Ta27_Return(expr_ty value, int lineno, int col_offset, PyArena *arena);
                                                                      ^
      ast27/Include/Python-ast.h:417:70: error: unknown type name 'PyArena'
      stmt_ty _Ta27_Delete(asdl_seq * targets, int lineno, int col_offset, PyArena *arena);
                                                                           ^
      ast27/Include/Python-ast.h:420:34: error: unknown type name 'PyArena'
                           col_offset, PyArena *arena);
                                       ^
      ast27/Include/Python-ast.h:423:25: error: unknown type name 'PyArena'
                              PyArena *arena);
                              ^
      ast27/Include/Python-ast.h:425:91: error: unknown type name 'PyArena'
      stmt_ty _Ta27_Print(expr_ty dest, asdl_seq * values, bool nl, int lineno, int col_offset, PyArena
                                                                                                ^
      ast27/Include/Python-ast.h:429:61: error: unknown type name 'PyArena'
                        type_comment, int lineno, int col_offset, PyArena *arena);
                                                                  ^
      ast27/Include/Python-ast.h:432:21: error: unknown type name 'PyArena'
                          PyArena *arena);
                          ^
      ast27/Include/Python-ast.h:435:18: error: unknown type name 'PyArena'
                       PyArena *arena);
                       ^
      ast27/Include/Python-ast.h:438:62: error: unknown type name 'PyArena'
                         type_comment, int lineno, int col_offset, PyArena *arena);
                                                                   ^
      ast27/Include/Python-ast.h:440:92: error: unknown type name 'PyArena'
      stmt_ty _Ta27_Raise(expr_ty type, expr_ty inst, expr_ty tback, int lineno, int col_offset, PyArena
                                                                                                 ^
      fatal error: too many errors emitted, stopping now [-ferror-limit=]
      20 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> typed-ast

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by basedgodant** [comment]
same
