### ISSUE TITLE
IndentationError: unindent does not match any outer indentation level

### ISSUE THREAD

**Issue by mrawesomey** [elebumm/RedditVideoMakerBot#1200]
### Describe the bug

I have filld out cong.toml and it still doesnt work pls help

### Reproduction Steps

I fileed out config.tml and typed in python3.10 main.py

### Expected behavior

make bot work

### Screenshots

![image](https://user-images.githubusercontent.com/106691142/186021357-c738ba7b-1cc6-42b9-a0f2-c5fc53438bb5.png)

### System Information

Operating System : 10
Python version : 3.10
App version / Branch [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by StopmotionSimonYT** [comment]
Hi,
Thanks for using the bot! The error above says that the credentials are not valid. Can you check that again?

**Comment by JasonLovesDoggo** [comment]
This is an error on your part It means you filled out the file wrong

**Comment by mrawesomey** [comment]
I filled it out correctly it still happens 
![image](https://user-images.githubusercontent.com/106691142/187037268-cdf2bb4d-2db0-4409-b8e1-a52465628e5c.png)

**Comment by StopmotionSimonYT** [comment]
> I filled it out correctly it still happens 
> ![image](https://user-images.githubusercontent.com/106691142/187037268-cdf2bb4d-2db0-4409-b8e1-a52465628e5c.png)
> 

You edited the wrong file. The template config should not be edited by the user.

**Comment by mrawesomey** [comment]
Oh what should i edit ?

**Comment by StopmotionSimonYT** [comment]
> Oh what should i edit ?

Revert all the changes, or download the bot again. Then just run the main.py and fill in the questions

**Comment by mrawesomey** [comment]
so now even tho I installed translators it says this:
![image](https://user-images.githubusercontent.com/106691142/187041025-87cdf338-47fd-4554-9566-4bdc36385eed.png)
![image](https://user-images.githubusercontent.com/106691142/187041037-8a32011c-aa08-451c-b148-9e52730b8268.png)

**Comment by mrawesomey** [comment]
How do I use more than 1 background?
Because I want to use rocket leauge and minecraft and csgo surfing

**Comment by StopmotionSimonYT** [comment]
> so now even tho I installed translators it says this:
> ![image](https://user-images.githubusercontent.com/106691142/187041025-87cdf338-47fd-4554-9566-4bdc36385eed.png)
> ![image](https://user-images.githubusercontent.com/106691142/187041037-8a32011c-aa08-451c-b148-9e52730b8268.png)
> 

You're using 2 different python versions. Please use the pip3 command to install the dependencies and run it with the python3 command. You can add more backgrounds in the CONSTANTS.py. If you need further assistance, use the Discord server!

**Comment by JasonLovesDoggo** [comment]
> > so now even tho I installed translators it says this:
> > ![image](https://user-images.githubusercontent.com/106691142/187041025-87cdf338-47fd-4554-9566-4bdc36385eed.png)
> > ![image](https://user-images.githubusercontent.com/106691142/187041037-8a32011c-aa08-451c-b148-9e52730b8268.png)
> > 
> 
> You're using 2 different python versions. Please use the pip3 command to install the dependencies and run it with the python3 command. You can add more backgrounds in the CONSTANTS.py. If you need further assistance, use the Discord server!

Never use python3 or pip3..
