### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Marshall-mk** [elebumm/RedditVideoMakerBot#1202]
### Describe the bug

The codes written in reddit/subreddit.py requires python3.10+. Therefore, the right requirement for this project should be Python3.10+

### Reproduction Steps

python main.py
Traceback (most recent call last):
  File "C:\Users\HI\Desktop\.dev\python\Deep learning\Scripts\RedditVideoMakerBot\main.py", line 9, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "C:\Users\HI\Desktop\.dev\python\Deep learning\Scripts\RedditVideoMakerBot\reddit\subreddit.py", line 44
    match e.response.status_code:
          ^
SyntaxError: invalid syntax

### Expected behavior

It should run smoothly

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by ProffessorPolo** [comment]
change this code
```
match e.response.status_code:
          case 401:
                   print("Invalid credentials - please check them in config.toml")
```
to this code
```
if (e.response.status_code == 401):
         print("Invalid credentials - please check them in config.toml")
```

**Comment by ProffessorPolo** [comment]
you can find that in the reddit/subreddit.py line 44

**Comment by Marshall-mk** [comment]
That solves the issue. Thank you.
