### ISSUE TITLE
what do i do about this

### ISSUE THREAD

**Issue by synaek** [elebumm/RedditVideoMakerBot#1208]
C:\RedditVideoMakerBot>python3 main.py
Traceback (most recent call last):
  File "C:\RedditVideoMakerBot\main.py", line 9, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "C:\RedditVideoMakerBot\reddit\subreddit.py", line 44
    match e.response.status_code:
          ^
SyntaxError: invalid syntax

**Comment by DevFlock** [comment]
Install latest version of python. The `match`  statement only works in 3.10 and over.

**Comment by mainali123** [comment]
I am getting the same error even when I have **Python 3.9.13**......... Is there any wrong with a code ?? @DevFlock

**Comment by DevFlock** [comment]
There is nothing wrong with the code, the match statement is a new feature that was introduced in Python 3.10. In order to use this you will have to upgrade to 3.10 or higher. Personally I have tested it with python 3.10.4 and it works perfectly.

**Comment by CJthisis** [comment]
@

**Comment by CJthisis** [comment]
@synaek 

Can you close this as completed?
