### ISSUE TITLE
[Bug]:  TikTok TTS API broken?

### ISSUE THREAD

**Issue by Auax** [elebumm/RedditVideoMakerBot#1212]
### Describe the bug

I think the TikTok API is no longer working. This is the response it returns `{[...], 'message': "Couldn't load speech. Try again.", [...]}`.

### Reproduction Steps

Run the program using the TikTok tts service.

### Expected behavior

Should save the audio files.

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.10]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by DerVini** [comment]
I am getting the same error, but it works with all the other tts providers. So my best guess for now is, that the TikTok TTS API might be down or in maintenance or something. I will just try again in a few hours.

**Comment by turulix** [comment]
Same Issue here (Has been for the last 4 days). Trying to send a manual request to the URL  just returns a 404. Not sure if i'm doing something wrong or if they changed something
