### ISSUE TITLE
[Bug]:  vstr = [r.json()["data"]["v_str"]][0] KeyError: 'data'

### ISSUE THREAD

**Issue by Shashwat-pd** [elebumm/RedditVideoMakerBot#1218]
### Describe the bug

{"extra":{"log_id":"20220828132151C892A5606AED020C70B9"},"message":"Couldn't load speech. Try again.","status_code":1,"status_msg":"Couldn't load speech. Try again."}

This is the response from r.text

This is my config.toml

[settings]
allow_nsfw = true
theme = "dark"
times_to_run = 1
opacity = 0.8
transition = 0.2
storymode = true

[settings.background]
background_choice = "gta"

[settings.tts]
voice_choice = "tiktok"
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_006"
python_voice = "1"
py_voice_num = "2"

[reddit.creds]
client_id = "  "
client_secret = "  "
username = "  "
password = "  "
2fa = false

[reddit.thread]
random = false
subreddit = "Nepal"
post_id = "wznlo9"
max_comment_length = 500
post_lang = ""
min_comments = 20

### Reproduction Steps

Run main.py
Answered prompts as given in the description. (Can check contents of config I have put above)

### Expected behavior

A Video in the local storage

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.10]
App version / Branch [e.g. 2.4.1, V2., master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by B3nnjoe** [comment]
Also happened to me

**Comment by StopmotionSimonYT** [comment]
Hi,
Thanks for using the bot! Unfortunately, the TikTok TTS currently doesn't work. We are working on it!

**Comment by B3nnjoe** [comment]
> Hi, Thanks for using the bot! Unfortunately, the TikTok TTS currently doesn't work. We are working on it!
Hi,
could you send your config (minus the sensetive part) so i can try it out?

**Comment by StopmotionSimonYT** [comment]
> > Hi, Thanks for using the bot! Unfortunately, the TikTok TTS currently doesn't work. We are working on it!
>
> Hi,
> could you send your config (minus the sensetive part) so i can try it out?

Hi,
I am not using the bot. I just contribute to the project. You can join our Discord community to talk about the bot!

**Comment by MPagliari** [comment]
I think TikTok has changed something as I cant get other things to work on the TikTok API call. I will have to look into this further

**Comment by harvey298** [comment]
they've moved the end point and locked it down, it was solved/figured out [here](https://github.com/Weilbyte/tiktok-tts/issues/10)

**Comment by Archemike** [comment]
so tts lib fixed this, is this updated in this repo?

**Comment by OpenSourceSimon** [comment]
> so tts lib fixed this, is this updated in this repo? 

There is a pull request for it
