### ISSUE TITLE
[Bug]: Traceback (most recent call last):

### ISSUE THREAD

**Issue by mallik30** [elebumm/RedditVideoMakerBot#1219]
### Describe the bug
seeing the below error after running python3 main.py "Traceback (most recent call last):"

**Full error:**
│ You are using v2.3 of the bot                                                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
###############################
#                             #
# Checking TOML configuration #
#                             #
###############################
If you see any prompts, that means that you have unset/incorrectly set variables, please input the correct values.
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ on the 1st iteration of 10                                                                                                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Logging into Reddit.
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Getting subreddit threads...                                                                                                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Using subreddit: r/AskReddit from TOML config
Video will be: What is common knowledge that you found out way too late? 👍
Thread has 20593 upvotes
Thread has a upvote ratio of 95.0%
Thread has 10111 comments
Received subreddit threads Successfully.
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Saving Text to MP3 files...                                                                                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "/Users/arjunp/bot/RedditVideoMakerBot-master/main.py", line 65, in <module>
    run_many(config["settings"]["times_to_run"])
  File "/Users/arjunp/bot/RedditVideoMakerBot-master/main.py", line 56, in run_many
    main()
  File "/Users/arjunp/bot/RedditVideoMakerBot-master/main.py", line 42, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "/Users/arjunp/bot/RedditVideoMakerBot-master/video_creation/voices.py", line 48, in save_text_to_mp3
    return text_to_mp3.run()
  File "/Users/arjunp/bot/RedditVideoMakerBot-master/TTS/engine_wrapper.py", line 58, in run
    self.call_tts("title", self.reddit_object["thread_title"])
  File "/Users/arjunp/bot/RedditVideoMakerBot-master/TTS/engine_wrapper.py", line 113, in call_tts
    self.tts_module.run(text=process_text(text), filepath=f"{self.path}/{filename}.mp3")
  File "/Users/arjunp/bot/RedditVideoMakerBot-master/TTS/TikTok.py", line 94, in run
    vstr = [r.json()["data"]["v_str"]][0]
KeyError: 'data'

### Reproduction Steps

python3 main.py

### Expected behavior

run

### System Information

Operating System : [e.g. Mac]
Python version : [e.g. Python 3.6]
App version / Branch [e.g. latest, V2.3, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by mallik30** [comment]
tried deleting config file, still fails with same error

**Comment by StopmotionSimonYT** [comment]
Hi,
Thanks for using the bot! Unfortunately, the TikTok TTS currently doesn't work. We are working on it!

**Comment by Gal1le0Oo** [comment]
the EXACT thing happened to me
which tts can i use then?

**Comment by OpenSourceSimon** [comment]
> the EXACT thing happened to me
> which tts can i use then?

Streamlabspolly, Google Translate or AWS Polly
