### ISSUE TITLE
No module named 'dotenv'

### ISSUE THREAD

**Issue by thorhelson** [elebumm/RedditVideoMakerBot#122]
after installing every thing it gives me this 
![image](https://user-images.githubusercontent.com/104784435/171520374-22d0e2b3-4b17-4b3e-9a53-7c239582becf.png)
so i try to install dotenv i get this 
![image](https://user-images.githubusercontent.com/104784435/171520698-cdd31d21-d3e0-4f4f-a17b-20dfc7880e4c.png)

**Comment by JasonLovesDoggo** [comment]
pip install python-dotenv
