### ISSUE TITLE
[Bug]:  Traceback (most recent call last)...........  invalid continuation byte

### ISSUE THREAD

**Issue by X023301** [elebumm/RedditVideoMakerBot#1222]
### Describe the bug

Hello guys,

so my problem is that if I start the program for the first time and enter my credentials, everything is fine. After I started it for the second time, it is not working anymore and gives me this error message.

`Traceback (most recent call last):
  File "C:\Users\Mouad\Downloads\RedditVideoMakerBot-2.4.2\main.py", line 79, in <module>
    config = settings.check_toml("utils/.config.template.toml", "config.toml")
  File "C:\Users\Mouad\Downloads\RedditVideoMakerBot-2.4.2\utils\settings.py", line 120, in check_toml
    config = toml.load(config_file)
  File "C:\Users\Mouad\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\toml\decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 270: invalid continuation byte`

### Reproduction Steps

-Start program for the first time with python3 main.py (everything works)
-Video is done
-enter the command python3 main.py again
-error occurs

### Expected behavior

Normally the program should just start and give me the video as output

### Screenshots

![image](https://user-images.githubusercontent.com/59014437/187279667-d524b3dd-c3c5-45d8-b414-15df27ded0a8.png)

### System Information

Operating System : Windows 10
Python version : Python 3.10.6
App version / Branch -> Version 2.4.1

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by JasonLovesDoggo** [comment]
Duplicate

**Comment by X023301** [comment]
Can you tell me please where to find the solution? I would appreciate it!
