### ISSUE TITLE
[Bug]: Syntax Error: Invalid Syntax

### ISSUE THREAD

**Issue by TEPTIS** [elebumm/RedditVideoMakerBot#1224]
### Describe the bug

Just resolved it by installing all modules by hands

### Reproduction Steps

‎ ‎ 

### Expected behavior

‎ 

### System Information

Operating System : AntiX-Linux 64 bits
Python version : 3.9.2, 3.10.0
Branch : latest, V2.0, master, develop

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by aamirdhanani** [comment]
I've been having the same issue.

I did get it to get past this point once but it quickly became a game of "pip install" install everything.

I have installed the latest Python 3.9 version (3.9.11) and still no luck.

<img width="680" alt="Screen Shot 2022-08-30 at 4 08 33 PM" src="https://user-images.githubusercontent.com/59127865/187533272-22a33a95-d7d9-45fd-bc49-764a3caaa011.png">

**Comment by SomeRandomGuy009** [comment]
> I've been having the same issue.
> 
> I did get it to get past this point once but it quickly became a game of "pip install" install everything.
> 
> I have installed the latest Python 3.9 version (3.9.11) and still no luck.
> 
> <img alt="Screen Shot 2022-08-30 at 4 08 33 PM" width="680" src="https://user-images.githubusercontent.com/59127865/187533272-22a33a95-d7d9-45fd-bc49-764a3caaa011.png">
> 
> Looks like you had a solution? Do you mind letting me know which modules you reinstalled I feel like I've tried everything. Thanks

same problem

**Comment by SomeRandomGuy009** [comment]
This did fix after installing python 3.10.0

**Comment by aamirdhanani** [comment]
Going to share my experience just in case someone needs it.

It looks like to get it to work you need to install Python 3.10 and make sure all the Modules are up to date.

Oddly enough I was having trouble installing "translators" from the requirements list as "lmxl" was not installed on my system(Mac). 

To get that to install I had to run "xcode-select --install". After that ran, I installed "lxml" and then "translators" to get everything to work.

If that doesn't work I would try to go through the requirements list and see what isn't installing correctly. More likely then not there's something that is stopping the program from running.
