### ISSUE TITLE
[Bug]: Installation failed

### ISSUE THREAD

**Issue by C5fifteen** [elebumm/RedditVideoMakerBot#1226]
### Describe the bug

Not able to install the bot. It displays: 

warning: python-3.10.5-2 is up to date -- skipping
warning: tk-8.6.12-1 is up to date -- skipping
warning: git-2.37.2-1 is up to date -- skipping
 there is nothing to do
usage: python -m ensurepip [-h] [--version] [-v] [-U] [--user] [--root ROOT]
                           [--altinstall] [--default-pip]
python -m ensurepip: error: unrecognized arguments: unzip
Installation failed

### Reproduction Steps

Run bash <(curl -sL https://raw.githubusercontent.com/elebumm/RedditVideoMakerBot/master/install.sh)

### Expected behavior

I expected the bot to normally install.

### System Information

Operating System : Manjaro Linux
Python version : Python 3.10.5
App version / Branch: Latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by C5fifteen** [comment]
uh

**Comment by 0x0000000FF1CE** [comment]
Is pip upto date?
