### ISSUE TITLE
[Feature]: A tutorial video

### ISSUE THREAD

**Issue by Nikicha316** [elebumm/RedditVideoMakerBot#1229]
### Summary

Make a tutorial video like this one

### Is your feature request related to a problem?

A lot of people don't know how to install your program

### Describe the solution you'd like

Make a tutorial video like this one:https://www.youtube.com/watch?v=T0ztYcPnMsY&t

**Comment by X023301** [comment]
They literally created a whole documentation around this on https://reddit-video-maker-bot.netlify.app/docs/intro .
I was new into this stuff and I already got it, so everybody can.

If this helped you, then please change the label to fixed or close this bug.
