### ISSUE TITLE
[Bug]: Why dosent everything from the folder temp get deleted when the video is done being made

### ISSUE THREAD

**Issue by mrawesomey** [elebumm/RedditVideoMakerBot#1230]
### Describe the bug

All the the temp files from all the last videos i made werent deleted

### Reproduction Steps

nothing

### Expected behavior

temp folder to be clean

### Screenshots

![image](https://user-images.githubusercontent.com/106691142/187965423-d14434bd-c3d1-43e1-9264-c1c6fe303e85.png)
![image](https://user-images.githubusercontent.com/106691142/187965983-b69cfa7d-991c-4fbe-b68b-7e79f1cb8842.png)

### System Information

Operating System : win 10
Python version : py 3.10
App version / Branch 2.41.1

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by JasonLovesDoggo** [comment]
Duplicate

**Comment by mrawesomey** [comment]
Wheres the original ?

**Comment by simix** [comment]
i have this issue too
