### ISSUE TITLE
[Bug]: The Bot Does Not work on NSFW subreddits

### ISSUE THREAD

**Issue by goodzombz** [elebumm/RedditVideoMakerBot#1231]
### Describe the bug

when you start the program it all goes fine until the screenshot process then it freezes and after like 30 secs it says that it lost connection

### Reproduction Steps

I changes the subreddit to r/AskRedditAfterDark and I allowed nsfw 

### Expected behavior

It should just do what its supposed to

### System Information

windows 11

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by StopmotionSimonYT** [comment]
More details:
The user is not logged in on the Playwright browser. So to fix it, maybe add a login header? The NSFW post needs an account to verify that the user is 18+. The post URL: https://www.reddit.com/r/AskRedditAfterDark/comments/x40xz2/anybody_else_masturbate_when_they_cant_sleep/. The popup that comes: 
![image](https://user-images.githubusercontent.com/65854503/188168471-c3395092-d58c-4b31-b5ef-1ee1ed0c6f02.png)

**Comment by JasonLovesDoggo** [comment]
Duplicate

**Comment by goodzombz** [comment]
> Duplicate

where?
