### ISSUE TITLE
[Bug]: where is the .env.template file

### ISSUE THREAD

**Issue by sarimwaniR** [elebumm/RedditVideoMakerBot#1232]
### Describe the bug

where is the .env.template file

### Reproduction Steps

where is the .env.template file

### Expected behavior

where is the .env.template file

### Screenshots

where is the .env.template file

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
There is no .env file. Please read our documentation for the installation

**Comment by sarimwaniR** [comment]
M
