### ISSUE TITLE
[Bug]: it randomly selects a thread and i have random set to false

### ISSUE THREAD

**Issue by thegreatone45** [elebumm/RedditVideoMakerBot#1233]
### Describe the bug

 it randomly selects a thread and i have random set to false

### Reproduction Steps

i just followed the guide

### Expected behavior

ask me for a url of the thread i want to select

### System Information

Operating System : Windows 10
Python version Python 3.6
app version latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by ExplodeCodeYT** [comment]
Does your program work still?

**Comment by OpenSourceSimon** [comment]
If you set random to false, you need to fill in the postid in config.toml otherwise it's still random

**Comment by CJthisis** [comment]
@thegreatone45 

Can you close this as completed?
