### ISSUE TITLE
[Bug]: storytime feature does nothing

### ISSUE THREAD

**Issue by zickcunt** [elebumm/RedditVideoMakerBot#1239]
### Describe the bug

the video product doesn't change if the storytime feature is true or false, you still only get the rapid reading of the headline and then the comments

### Reproduction Steps

i followed the download instructions and changed storytime to True in the configs

### Expected behavior

the video editor would make a storytime video

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.10]
App version / Branch [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by CJthisis** [comment]
I think storytime is not fully implemented yet, but I could be wrong

**Comment by OpenSourceSimon** [comment]
We're still working on the story mode, it's not working
