### ISSUE TITLE
could not find match for ^\w+\W

### ISSUE THREAD

**Issue by lesterrar** [elebumm/RedditVideoMakerBot#124]
![reg4](https://user-images.githubusercontent.com/44342036/171523016-d20b1b16-01db-46a4-8f86-36b253bc3068.PNG)

**Comment by zaintechsavvy** [comment]
Same issue here too.

**Comment by zaintechsavvy** [comment]
Hmm, I'm not very sure this would work but what if you download the background video manually, to go "background.py" and add the path to "assets/mp4/background.mp4" and add the video in that path. 
![image](https://user-images.githubusercontent.com/95989141/171525763-5bc0fbc1-271b-4af1-9216-fe192030872e.png)

**Comment by lesterrar** [comment]
I think I've solved it, I went to the cipher.py file and changed var_regex = re.compile(r"^\w+\W") to var_regex = re.compile(r"^\$*\w+\W"). there's nothing wrong in doing that, right?

**Comment by zaintechsavvy** [comment]
Can you provide me the path to "cipher.py"? I don't seem to have it.

**Comment by jacobjake1** [comment]
> I think I've solved it, I went to the cipher.py file and changed var_regex = re.compile(r"^\w+\W") to var_regex = re.compile(r"^$*\w+\W"). there's nothing wrong in doing that, right?

cipher.py isn't a thing....?

**Comment by Wavey-web** [comment]
`re.compile(r"^$*\w+\W")` doesn't work. Further researching, the regex: `^\$*\w+\W` works

[it's been reference in pytube's issue #1199](https://github.com/pytube/pytube/issues/1199#issuecomment-1016783092)

**Comment by zaintechsavvy** [comment]
Thanks!

**Comment by Wavey-web** [comment]
> Thanks!

No problem! When you change the regex it should work.

**Comment by zaintechsavvy** [comment]
I'm located under `C:\Users\my user\AppData\Local\Programs\Python\Python310\Lib\site-packages\pytube` where do I go to change the regex? Sorry, I'm fairly new to coding and don't know much.

**Comment by zaintechsavvy** [comment]
I'm in cipher.py right now. What line is to change the regex?

**Comment by Matt10233** [comment]
> I'm in **cipher.py** right now. What line is to change the _regex_? 

Ctrl+f var_regex = re.compile

**Comment by reinkdesigns** [comment]
tried this now im getting an error 
![image](https://user-images.githubusercontent.com/104669790/171548380-3a837ed2-a304-43c4-b099-f4a3fd46896a.png)

re.error: nothing to repeat at position 2

**Comment by Matt10233** [comment]
> tried this now im getting an error 
> 
> ![image](https://user-images.githubusercontent.com/104669790/171548380-3a837ed2-a304-43c4-b099-f4a3fd46896a.png)
> 
> 
> 
> re.error: nothing to repeat at position 2

I think You forget a \ in re.compile(r"^\$*\w+\W")

**Comment by reinkdesigns** [comment]
i think i fixed it, i removed the r and the "" and it worked

**Comment by Skogowo** [comment]
did this, getting 'prawcore.exceptions.OAuthException: unauthorized_client error processing request (Only script apps may use password auth)'

**Comment by Skogowo** [comment]
oo, got it to say 'prawcore.exceptions.OAuthException: invalid_grant error processing request' instead
