### ISSUE TITLE
[Bug]: Moviepy - Command returned an error

### ISSUE THREAD

**Issue by ObviousNiNi** [elebumm/RedditVideoMakerBot#1241]
### Describe the bug

│ Creating the final video 🎥                                                 │
└─────────────────────────────────────────────────────────────────────────────┘
[00:28:21]  Video Will Be: 49 Seconds Long                    final_video.py:84
Translating filename...
Moviepy - Building video assets/temp/x8o38q/temp.mp4.
MoviePy - Writing audio in tempTEMP_MPY_wvf_snd.mp4
t:   0%|          | 0/1554 [00:00<?, ?it/s, now=None]MoviePy - Done.
Moviepy - Writing video assets/temp/x8o38q/temp.mp4

Moviepy - Done !
Moviepy - video ready assets/temp/x8o38q/temp.mp4
Moviepy - Running:
>>> "+ " ".join(cmd)
Traceback (most recent call last):
  File "C:\Users\PC\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 83, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\PC\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 62, in run_many
    main()
  File "C:\Users\PC\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 54, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "C:\Users\PC\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\video_creation\final_video.py", line 154, in make_final_video
    ffmpeg_extract_subclip(
  File "C:\Users\PC\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\venv\lib\site-packages\moviepy\video\io\ffmpeg_tools.py", line 41, in ffmpeg_extract_subclip
    subprocess_call(cmd)
  File "C:\Users\PC\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\venv\lib\site-packages\moviepy\tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
OSError: ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
Moviepy - Command returned an error
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'assets/temp/x8o38q/temp.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:51.80, start: 0.000000, bitrate: 7795 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1080x1920, 7635 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 163 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
results/AskReddit/¿Qué marca puede ir a la mierda?.mp4: Invalid argument

### Reproduction Steps

[reddit.thread]
random = false
subreddit = "AskReddit"
post_id = ""
max_comment_length = 500
post_lang = "es"
min_comments = 20

when subreddit is on reddit dev it works fine, but not with AskReddit.

### Expected behavior

It doesn't create the video file, nor delete the previous videos on "result" carpet.

### Screenshots

![image](https://user-images.githubusercontent.com/112665036/189047379-15ec6ee8-254a-4b83-b3dc-a5d15aef59b0.png)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

I tried with all different TTS. And again, it works fine with Redditdev but when I changed it to AskReddit, then the bug appears.

**Comment by LLuna-a** [comment]
same problem here

**Comment by Brandon4466** [comment]
Definitely not fixed, same error here

**Comment by Serbienx** [comment]
Just got this issue after fixing another issue.
Not sure what could fix it.

**Comment by RomanJus** [comment]
I actually couldn't get it to work, so instead I resorted to using WSL 2 because according to [this](https://github.com/Zulko/moviepy/issues/1634) issue on moviepy repo, it works on linux, which seems to be true.
