### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by TTT2866** [elebumm/RedditVideoMakerBot#1243]
### Describe the bug

After the full installation and entering the setup variables the program crashes and produces the following errors. I've tried to delete the Assets folder as mentioned in another thread to no avail. Any ideas? 

### Reproduction Steps

Ran the program. Waited For login. Logged in, "getting subreddit threads" Program instantly crashes.

Here are my variables: 

[settings]
allow_nsfw = false
theme = "dark"
times_to_run = 1
opacity = 0.9
transition = 0.2
storymode = false

[settings.background]
background_choice = "minecraft"

[settings.tts]
voice_choice = "tiktok"
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_006"
python_voice = "1"
py_voice_num = "2"

[reddit.creds]
client_id = "*"
client_secret = "*"
username = "*"
password = "*"
2fa = false

[reddit.thread]
random = true
subreddit = "askreddit"
post_id = ""
max_comment_length = 500
post_lang = ""
min_comments = 20

### Expected behavior

It should run as normal and generate the video, yet it just crashes. 

### Screenshots

![Uploading image.png…]()

### System Information

Operating System : [e.g. Windows 10]
Python version : [e.g. Python 3.10.0]
App version / Branch 2.4.1]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by TTT2866** [comment]
Sorry I don't think that image upload worked.  Here it is again
![image](https://user-images.githubusercontent.com/41979926/189479157-219a2221-f47d-48f6-a676-bd1df4942b84.png)

**Comment by OpenSourceSimon** [comment]
The TikTok TTS currently doesn't work
