### ISSUE TITLE
the script says my credentials are incorrect even though my credentials are correct

### ISSUE THREAD

**Issue by svenvandoornn** [elebumm/RedditVideoMakerBot#1244]
for some reason it says the credentials i have entered are incorrect even though my credentials are correct and i also double checked that my credentials are correct by copy and pasting the credentials from the toml file into the login page for reddit

**Comment by ObviousNiNi** [comment]
Delete the config, on reddit api create a new secret and id and configure again.

It worked for me.

**Comment by mas-designs** [comment]
I do have this issue, I've deleted the config on reddit multiple times, I've reset the password 3 times and I still get the same error. 
Is there some kind of way of logging, maybe there is some other underlying exception?
