### ISSUE TITLE
[Bug]: KeyError when running program

### ISSUE THREAD

**Issue by Jedi-Coder1** [elebumm/RedditVideoMakerBot#1247]
### Describe the bug

vstr = [r.json()["data"]["v_str"]][0]
KeyError: 'data' when running program

### Reproduction Steps

just running the program

### Expected behavior

i thought it would work

### System Information

Operating System : [Windows 10]
Python version : [Python 3.6]
App version / Branch [latest]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
The TikTok TTS currently doesn't work
