### ISSUE TITLE
[Feature]: Add replace for % sign

### ISSUE THREAD

**Issue by cboxgo69** [elebumm/RedditVideoMakerBot#1248]
### Summary

Add replace for % sign

### Is your feature request related to a problem?

When translating reddit entries with the % sign, the character is removed.

### Describe the solution you'd like

Please add something like this to voice.py:

```
    # remove any urls from the text
    regex_urls = r"((http|https)\:\/\/)?[a-zA-Z0-9\.\/\?\:@\-_=#]+\.([a-zA-Z]){2,6}([a-zA-Z0-9\.\&\/\?\:@\-_=#])*"

    result = re.sub(regex_urls, " ", text)
    result = result.replace("%", " percent ")
```

this will result in the % being read out by the TTS.

**Comment by cboxgo69** [comment]
I used that on the Streamlabs TTS because it takes something like: "47% of people" and reads it out as "47 of people". by changing to the word "percent" it will actually read out the word "percent"

I would think this applies to all of the TTS engines...

**Comment by OpenSourceSimon** [comment]
> I used that on the Streamlabs TTS because it takes something like: "47% of people" and reads it out as "47 of people". by changing "%" to the word "percent" it will actually read out the word "percent"
> 
> I would think this applies to all of the TTS engines...

Thanks for your quick reply! I think this needs to be in the TTS/engine_wrapper.py. I will take a look at it later

**Comment by JasonLovesDoggo** [comment]
See #1254
