### ISSUE TITLE
ERROR: Invalid Syntax

### ISSUE THREAD

**Issue by FreshImmuc** [elebumm/RedditVideoMakerBot#1251]
Hello, i used the install script to install the bot.

When I try to do python main.py it gives me this Error:

![image](https://user-images.githubusercontent.com/65733898/189694650-b27f2ba6-5279-4617-8255-2474032b9319.png)

Would be great to solve this! :)

**Comment by AgustinRamiroDiaz** [comment]
What's the output of running `python --version`? I think you might be running an older python2 version. Try running it with python3
