### ISSUE TITLE
[Bug]: Doesn't work either crashes or says Keyerror: Data

### ISSUE THREAD

**Issue by blargetwitch** [elebumm/RedditVideoMakerBot#1255]
### Describe the bug

![Screenshot_204](https://user-images.githubusercontent.com/20852095/190834453-fdf77e9a-fbcd-431f-937e-d7ad721f2319.png)

### Reproduction Steps

Config is setup correctly 

### Expected behavior

It is not making any video

### Screenshots

![Screenshot_204](https://user-images.githubusercontent.com/20852095/190834475-08117cf5-a7c2-450d-8a47-3610b00eb361.png)

### System Information

Operating System : [e.g. Windows 10]
Python version : [e.g. Python 3.10]
App version / Branch [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
The TikTok TTS currently doesn't work
