### ISSUE TITLE
[Bug]: Getting a syntax error when running main.py 

### ISSUE THREAD

**Issue by SkellXC** [elebumm/RedditVideoMakerBot#1258]
### Describe the bug

When I try to run main.py it crashes. Not sure what to do/how to fix it.

### Reproduction Steps

Opened python IDLE
Then selected the script
Ran it and got the syntax error.

### Expected behavior

It should show this.

### Screenshots

![image](https://user-images.githubusercontent.com/85579428/191107555-5d75a745-fea8-408e-bfda-568002778be9.png)

### System Information

Operating System : [Windows 10]
Python version : [e.g. Python 3.9.7]
App version / Branch [master]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Ultimatechno** [comment]
I have the same problem.

**Comment by OpenSourceSimon** [comment]
The match statement only works above Python 3.10. Please update or use the develop branch where it is updated.
