### ISSUE TITLE
[Bug]: Cannot Run the Program     match e.response.status_code:

### ISSUE THREAD

**Issue by lanewhitten** [elebumm/RedditVideoMakerBot#1260]
### Describe the bug

File "/home//Documents/RedditVideoMakerBot/reddit/subreddit.py", line 44
    match e.response.status_code:
I have tried to fix but this is preventing me from running I tried on both linux and windows and it doesn't work. 

### Reproduction Steps

Ran the Program

### Expected behavior

Expected it to generate a video

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch [e.g. latest, V2.0, master, develop]
Windows 10
Fedora 31.1

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
The match statement only works above Python 3.10. Please update or use the develop branch where it is updated.
