### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ellefan94** [elebumm/RedditVideoMakerBot#1263]
### Describe the bug

The Storymode mode doesn't work. (it doesn't read out the description of the reddit post)

### Reproduction Steps

I put "True" for storymode and it didn't work

### Expected behavior

I expected it to read just title and description of the reddit post

### System Information

Operating System : windows 11
Python version : 3.10
App version / Branch latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
The story mode isn't 100% done yet
