### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by heybrotha** [elebumm/RedditVideoMakerBot#1264]
### Describe the bug

Getting an error when I try to run the main file for the first time.

### Reproduction Steps

Tried to set up the bot. Did all the steps that were mentioned in the read me file, but when I tried to run the main file it gave me a syntax error. I tried typing python3 before running as well but it gave me another error. Tried turning it off in the manage execution aliases tab as well but nothing seems to work.

### Expected behavior

It shouldn't of given me a syntax error and should of asked me to put my reddit secret keys and stuff.

### Screenshots

![NVIDIA_Share_piDQJGue8z](https://user-images.githubusercontent.com/114238284/191971435-818f7d51-51dc-410f-92d2-7d781ba86dd0.png)
![NVIDIA_Share_56gf0udCZ8](https://user-images.githubusercontent.com/114238284/191971574-ae0172af-3b9a-4d5b-a0cc-fef9e212b8a7.png)

### System Information

Operating System : [e.g. Windows 10]
Python version : [e.g. Python 3.9.9]
App version / Branch [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
The match statement only works above Python 3.10. Please update or use the develop branch where it is updated.
