### ISSUE TITLE
[Bug]: sudo ./run.sh

### ISSUE THREAD

**Issue by alanzou** [elebumm/RedditVideoMakerBot#1265]
### Describe the bug

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "/app/reddit/subreddit.py", line 44
    match e.response.status_code:
          ^
SyntaxError: invalid syntax

### Reproduction Steps

./build.sh
./run.sh

### Expected behavior

start main.py

### System Information

Operating System : ubuntu
Python version : Python3.8
App version / Branch latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
The match statement only works above Python 3.10. Please update or use the develop branch where it is updated.
