### ISSUE TITLE
[Feature]: Support for AI Generated Images

### ISSUE THREAD

**Issue by alexlaverty** [elebumm/RedditVideoMakerBot#1267]
### Summary

Ability to scrape keyword relevant images from AI Generated Art platforms

### Is your feature request related to a problem?

I would like to see ability to have relevant AI generated images to go along with the Reddit Youtube generated Video

### Describe the solution you'd like

There is a new and emerging technology in the form of Artificially Intelligent generated Art and Images. 

It would be good to integrate this into the automated generate youtube reddit videos. 

For example take the Reddit post title and pass it to a AI generated Image service to generate an image and pass it back for use in the video.

When generating a video from a Reddit short story for each sentence generate a AI image and include it in the video.

I have already been playing around with this concept and been able to connect to Lexica.art API, which is an AI art search engine and pull and download images based off text query and put them into a video, you can see an example video here :

https://www.youtube.com/watch?v=nCjYH3ETXNo

You can see an example function to pull images from Lexica here :

https://github.com/alexlaverty/ttsvibelounge/blob/main/lexica.py

I use Lexica as it's much quicker and simple but if you wanted to fully generate images based off you text you could integrate with stable-diffusion  :

https://github.com/CompVis/stable-diffusion

I think we will see a lot more of AI generated media in the future, all the best!

EDIT : Seems the future may already be here! now Meta has release makeavideo which does AI text-to-video creation, see :

https://makeavideo.studio/

**Comment by Root-FTW** [comment]
This is the game changuer idea!!!!!!!!!!

**Comment by anhdodotnet** [comment]
i like your idea

**Comment by br0coder** [comment]
Great idea. Yet this feature can be extrapolated for use in so many ways such as picking up the topic of the reddit question and making an AI generated background out of it for example :)

**Comment by anas123123213** [comment]
+1
