### ISSUE TITLE
[Bug]: Docker build and run fails for current master 

### ISSUE THREAD

**Issue by alexlaverty** [elebumm/RedditVideoMakerBot#1268]
### Describe the bug

When building the docker image and running it, the script fails with error :

```
./build.sh

./run.sh
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "/app/reddit/subreddit.py", line 44
    match e.response.status_code:
          ^
SyntaxError: invalid syntax
```

### Reproduction Steps

git clone https://github.com/elebumm/RedditVideoMakerBot.git
cd RedditVideoMakerBot
./build.sh
./run.sh

### Expected behavior

Script runs and generates a video, instead it errors out and exits.

### System Information

Operating System : Windows 10 Pro

Python version : 
docker run -it rvmt  bash
root@aa2b6b4c6023:/app# python3 --version
Python 3.8.10

App version / Branch : Master

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
The match statement only works above Python 3.10. Please update or use the develop branch where it is updated.
