### ISSUE TITLE
[Feature]: Multithreaded videomaking

### ISSUE THREAD

**Issue by svenvandoornn** [elebumm/RedditVideoMakerBot#1269]
### Summary

make it so it is possible to have multiple threads making videos to make more videos

### Is your feature request related to a problem?

no

### Describe the solution you'd like

make it so you will have the possibility to say that you want to run it with multiple threads smth like 1 or 2 threads so you can make more videos within a hour without setting it to choose random videos

**Comment by xAlcahest** [comment]
> ### Summary
> make it so it is possible to have multiple threads making videos to make more videos
> 
> ### Is your feature request related to a problem?
> no
> 
> ### Describe the solution you'd like
> make it so you will have the possibility to say that you want to run it with multiple threads smth like 1 or 2 threads so you can make more videos within a hour without setting it to choose random videos
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Additional Context
> _No response_

Sorry to tell you this, but I don't think they will add this feature in the short term because it would require rewriting the whole script, if they ever do, I think they are waiting for a stable version without bugs with all required features added first

**Comment by OpenSourceSimon** [comment]
The bot can run multiple instances at the same time
