### ISSUE TITLE
When I run main.py it says No module named 'prawcore'[Bug]: 

### ISSUE THREAD

**Issue by xav123q** [elebumm/RedditVideoMakerBot#1272]
### Describe the bug

When I run python3 main.py I get this error:

Traceback (most recent call last):
  File "C:\Users\xavie\RedditVideoMakerBot\main.py", line 7, in <module>
    from prawcore import ResponseException
ModuleNotFoundError: No module named 'prawcore'

What do I do?

### Reproduction Steps

I run python3 main.py

### Expected behavior

open main.py

### System Information

Operating System : [e.g. Windows 10]
Python version : [ Python 3.10.7]
App version / Branch [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
Pip install praw

**Comment by xav123q** [comment]
> Have you tried the command `pip install praw`?

Now I have this error

Traceback (most recent call last):
  File "C:\Users\xavie\RedditVideoMakerBot\main.py", line 9, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "C:\Users\xavie\RedditVideoMakerBot\reddit\subreddit.py", line 44
    match e.response.status_code:
          ^
SyntaxError: invalid syntax

**Comment by OpenSourceSimon** [comment]
> Traceback (most recent call last): File "C:\Users\xavie\RedditVideoMakerBot\main.py", line 9, in from reddit.subreddit import get_subreddit_threads File "C:\Users\xavie\RedditVideoMakerBot\reddit\subreddit.py", line 44 match e.response.status_code: ^ SyntaxError: invalid syntax

The match statement only works above Python 3.10. Please update or use the develop branch where it is updated.
