### ISSUE TITLE
[Bug]: invalid credentials with correct credentials

### ISSUE THREAD

**Issue by mas-designs** [elebumm/RedditVideoMakerBot#1274]
### Describe the bug

I'm getting the error message that the credentials are invalid.
I've reconfigured the reddit configuration multiple times now.
Furthermore, I also reset my password multiple times, made sure I can log in the browser, and it works.

### Reproduction Steps

Cloned the repo
Finished the configuration
Ran the python main.py command

### Expected behavior

Successful login

### Screenshots

![image](https://user-images.githubusercontent.com/24718174/192738801-59e36270-9a58-46e5-8477-680c4a575dec.png)

### System Information

Operating System : Windows 10
Python version : 3.10.7 AMD 64bit
App version / Branch master (cloned on the 27th August

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

There is one issue which has been closed, hence I'm reopening this report.

**Comment by mas-designs** [comment]
I've created a new user and it still isn't working.
Maybe there is some kind of client-side issue?

**Comment by mas-designs** [comment]
I've tried it on macOS, where the same credentials work so I guess it's some kind of client-side issue with windows.

**Comment by XmotoPkl** [comment]
I got error too

Operating System : Windows 10
Python version : 3.10.7 AMD 64bit
App version / Branch master (cloned on the 27th August)

**Comment by XmotoPkl** [comment]
> I got error too
> 
> Operating System : Windows 10 Python version : 3.10.7 AMD 64bit App version / Branch master (cloned on the 27th August)
I delete old file config.toml,and try a new config,that working normal now.

**Comment by mas-designs** [comment]
> > I got error too
> > Operating System : Windows 10 Python version : 3.10.7 AMD 64bit App version / Branch master (cloned on the 27th August)
> > I delete old file config.toml,and try a new config,that working normal now.

Yeah, that didn't work for me. I've tried the same credentials on macOs and it worked there so it must a windows/client side issue.

**Comment by JRockThumper** [comment]
Same issue. Has anyone figured out a fix?

**Comment by mas-designs** [comment]
Nope, my fix was changing OS.

**Comment by Isaac-Hall1** [comment]
> I've tried it on macOS, where the same credentials work so I guess it's some kind of client-side issue with windows.

I'm on macOS, however, it is sending the same issue.

**Comment by qbirr** [comment]
hallo, has anyone solve this problem ???
