### ISSUE TITLE
how to make  video time longer

### ISSUE THREAD

**Issue by arsonnft** [elebumm/RedditVideoMakerBot#1276]
please can you show me what to change to make the video longer because most of my videos are less then 50 seconds.

**Comment by OpenSourceSimon** [comment]
If you know how to, you can change a variable in the TTS/engine_wrapper.py:16.

**Comment by arsonnft** [comment]
I have found this variable TTS/engine_wrapper.py but i have this DEFAULT_MAX_LENGTH: int = 50  # video length variable, so is it possible to change "MAX to MIN" ?

**Comment by OpenSourceSimon** [comment]
> I have found this variable TTS/engine_wrapper.py but i have this DEFAULT_MAX_LENGTH: int = 50  # video length variable, so is it possible to change "MAX to MIN" ?

That's not possible, it will generate TTS until that value.
