### ISSUE TITLE
[Feature]: Semi-automatization

### ISSUE THREAD

**Issue by kalilfagundes** [elebumm/RedditVideoMakerBot#1278]
### Summary

Enable a semi-automatization feature where we can edit the texts before the bot create the video.

### Is your feature request related to a problem?

I'm using the translation feature, but sometimes the translation is really bad. A lot of the times it is also related with bad writting or abbreviations.
If a semi-automatization feature is possible, we can previously edit the texts and make it possible to correct those wrong texts before the video creation.

### Describe the solution you'd like

Example on console:

Semi-automatization is enabled.
The text is: *****
Do you want to edit it? y/n
Press y when edit is finished. 
(then we can go to a notepad, edit the texts/errors/bad translators/things that would create trouble to the TTS)

Pressing y, the bot would run as normal.

**Comment by CJthisis** [comment]
Very good idea, this would also be very helpful when there are links/characters in the post/comment that aren't necessary to the story.
