### ISSUE TITLE
ModuleNotFoundError: No module named 'rich'

### ISSUE THREAD

**Issue by reinkdesigns** [elebumm/RedditVideoMakerBot#128]
![image](https://user-images.githubusercontent.com/104669790/171542432-3e3fdc33-9e7e-4c02-a771-f5052b736595.png)

long shot, but is it because i have my folder on drive E and rich installed to drive c? and if so, how do i correct this?

**Comment by GaMiNgEr9978** [comment]
Yeah I have the same problem too.

**Comment by GaMiNgEr9978** [comment]
oh i found the solution, its in #60

**Comment by reinkdesigns** [comment]
i tried that one already, still no success

**Comment by reinkdesigns** [comment]
figured it out, had to use python main.py, not python3 main.py. but now i got a fun new error

![image](https://user-images.githubusercontent.com/104669790/171546667-4b3b5872-4768-4d8c-a98b-0854ab1f5871.png)

**Comment by reinkdesigns** [comment]
resolved in #124 now more fun problems lol... man i feel like a real programer now, fix 1 issue and 5 more pop up

![image](https://user-images.githubusercontent.com/104669790/171547348-0531d327-7985-4b70-9f19-f413df46d2ac.png)

re.error: nothing to repeat at position 2

**Comment by SlushyFr** [comment]
pip install rich

**Comment by FreebieII** [comment]
Hi @reinkdesigns 

I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
