### ISSUE TITLE
[Bug]: Help me ı got hese kind of errors

### ISSUE THREAD

**Issue by selams31** [elebumm/RedditVideoMakerBot#1280]
### Describe the bug

dont know why can you guys help me

### Reproduction Steps

.

### Expected behavior

.

### Screenshots

<img width="730" alt="Screen Shot 2022-10-02 at 15 07 31" src="https://user-images.githubusercontent.com/108633644/193453165-e8ce6098-9b5e-4885-abfd-abafa9f62d38.png">

### System Information

Operating System : [macos]
Python version : [ Python 3.10]
App version / Branch [2.4.1]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by stogidout** [comment]
I am getting the same issue, i am running this on ubuntu  

`<pre>Traceback (most recent call last):
  File &quot;/home/stogi/RedditVideoMakerBot/RedditVideoMakerBot-master/main.py&quot;, line 83, in &lt;module&gt;
    run_many(config[&quot;settings&quot;][&quot;times_to_run&quot;])
  File &quot;/home/stogi/RedditVideoMakerBot/RedditVideoMakerBot-master/main.py&quot;, line 62, in run_many
    main()
  File &quot;/home/stogi/RedditVideoMakerBot/RedditVideoMakerBot-master/main.py&quot;, line 48, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File &quot;/home/stogi/RedditVideoMakerBot/RedditVideoMakerBot-master/video_creation/voices.py&quot;, line 50, in save_text_to_mp3
    return text_to_mp3.run()
  File &quot;/home/stogi/RedditVideoMakerBot/RedditVideoMakerBot-master/TTS/engine_wrapper.py&quot;, line 61, in run
    self.call_tts(&quot;title&quot;, process_text(self.reddit_object[&quot;thread_title&quot;]))
  File &quot;/home/stogi/RedditVideoMakerBot/RedditVideoMakerBot-master/TTS/engine_wrapper.py&quot;, line 117, in call_tts
    self.tts_module.run(text, filepath=f&quot;{self.path}/{filename}.mp3&quot;)
  File &quot;/home/stogi/RedditVideoMakerBot/RedditVideoMakerBot-master/TTS/TikTok.py&quot;, line 94, in run
    vstr = [r.json()[&quot;data&quot;][&quot;v_str&quot;]][0]
KeyError: &apos;data&apos;
</pre>`

**Comment by OpenSourceSimon** [comment]
The TikTok TTS currently doesn't work

**Comment by stogidout** [comment]
Thank you for you speedy response. Running under googletranslate and it seems to have worked!
