### ISSUE TITLE
[Bug]: DONT KNOW WHAT TYPE OF ERROR IS IT

### ISSUE THREAD

**Issue by selams31** [elebumm/RedditVideoMakerBot#1283]
### Describe the bug

s

### Reproduction Steps

normal start

### Expected behavior

z

### Screenshots

<img width="722" alt="Screen Shot 2022-10-02 at 18 42 00" src="https://user-images.githubusercontent.com/108633644/193463683-9dbe2cfd-e5ea-40d1-a057-b54576dc2a98.png">

### System Information

Operating System : [mac os]
Python version : [e.g. Python 3.10]
App version / Branch [latest]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
Can you try it with another post?
