### ISSUE TITLE
Where is config.toml?

### ISSUE THREAD

**Issue by neelmaster101** [elebumm/RedditVideoMakerBot#1284]
I need to change the voice so I need to edit the config.toml but all I can find is .config.template.toml.

Refreshing does nothing.

I expected to find the file.

Python version: 3.10
OS: Windows 10
App version: Latest

**Comment by anhdodotnet** [comment]
1. **config.toml :** 

_[settings.tts]
voice_choice = "streamlabspolly"
aws_polly_voice = "**Matthew**"
streamlabs_polly_voice = "**Matthew**"
tiktok_voice = "en_us_006"
python_voice = "1"
py_voice_num = "2"_

**2. change the voice**
voices = [
    "Brian",
    "Emma",
    "Russell",
    "Joey",
    "Matthew",
    "Joanna",
    "Kimberly",
    "Amy",
    "Geraint",
    "Nicole",
    "Justin",
    "Ivy",
    "Kendra",
    "Salli",
    "Raveena",
]

**Comment by OpenSourceSimon** [comment]
It's in the main folder where main.py also is

**Comment by neelmaster101** [comment]
![where is config](https://user-images.githubusercontent.com/48933846/193670497-e2a4f899-f10f-4f27-8ed9-7e04308a209a.PNG)

This is all I see, what do you see?

**Comment by OpenSourceSimon** [comment]
You need to run the bot first, and it will guide you through the settings. After that, it creates a config.toml file.
