### ISSUE TITLE
The aspect ratio to 16:9 ?

### ISSUE THREAD

**Issue by anhdodotnet** [elebumm/RedditVideoMakerBot#1285]
Where can I change this parameter?
- The aspect ratio to 16:9?
- Time increased to 1-5 minutes?

**Comment by OpenSourceSimon** [comment]
We're working on the aspect ratio, you can follow the progress at the pull request. You can increase the time by editing the variable at TTS/engine_wrapper.py:16

**Comment by anhdodotnet** [comment]
Thanks AD
