### ISSUE TITLE
video creation successful but final video is a corrupt file

### ISSUE THREAD

**Issue by sykeze** [elebumm/RedditVideoMakerBot#129]
so the bot works fine but it either saves as a black screen with the audio running in the backround OR its just a corrupt mp4.

anyone having the same issue?

**Comment by JasonLovesDoggo** [comment]
I don't know what to say, I don't believe anyone else has had that issue.

maybe try updating FFmpeg

**Comment by FreebieII** [comment]
Hi @sykeze, 

I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
