### ISSUE TITLE
[Bug]: ERROR PLS HELP

### ISSUE THREAD

**Issue by Dashuy** [elebumm/RedditVideoMakerBot#1290]
### Describe the bug

Getting an error as i run the code :/

### Reproduction Steps

Just ran the program using py3 with a normal config

### Expected behavior

Expect it to process and do the video

### Screenshots

![Code_bOUwM3kjyF](https://user-images.githubusercontent.com/73790852/194645866-6618fb6f-8f01-4d10-a868-f96b2ccc28e7.png)

### System Information

Win 10 
Python 3.10

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by SamuelSar** [comment]
some info here : https://github.com/oscie57/tiktok-voice/pull/24

**Comment by OpenSourceSimon** [comment]
The TikTok TTS currently doesn't work

**Comment by kogake** [comment]
Understand Simon : Ç
