### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by IGoHardCore** [elebumm/RedditVideoMakerBot#1291]
### Describe the bug

when I open main.py it shows Reddit video maker and everything is good at first but then it crashes right after "Getting subreddited threads" PLEASE HELP

### Reproduction Steps

xcvb

### Expected behavior

I expect it to stay open and not crash so it could process the video

### Screenshots

xcvb

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

vcb

**Comment by CJthisis** [comment]
Which version are you using? Did you make any changes to the code? What subreddit did you put in the cofing.toml file?
