### ISSUE TITLE
[Bug]: Crash when running

### ISSUE THREAD

**Issue by Essilu** [elebumm/RedditVideoMakerBot#1293]
### Describe the bug

I installed all the dependencies. I configured the bot, entering all the informations, and checking if config.toml has the right input. When running the command python main.py the file launches, it goes through the process of finding a post 
![image](https://user-images.githubusercontent.com/69388094/194938022-0a1464d8-dce4-4ea8-86c6-ecc9f40abd65.png)

But after that i stop for a second then crashes, throwing this error: 
![image](https://user-images.githubusercontent.com/69388094/194938274-377cc6a2-7687-498b-952e-c57f65b4b8e0.png)

### Reproduction Steps

I tried this with version 3.10.7 64-bits. 

I tried running with version 3.9.13 and 3.9.13 but i got an error saying I should run with 3.10 at least to use the "match" command. 

### Expected behavior

Have a video generated

### System Information

Operating System : Windows 10
Python version : 3.10.7
App version / Branch : 2.4.1

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by dybowskyy** [comment]
i have the same problem

**Comment by OpenSourceSimon** [comment]
The TikTok TTS currently doesn't work
