### ISSUE TITLE
[Bug]: Minimum requirement should be 3.10+

### ISSUE THREAD

**Issue by thisthrowaway** [elebumm/RedditVideoMakerBot#1294]
### Describe the bug

Match statements require Python 3.10 or newer

### Reproduction Steps

Used Python 3.9.13
"SyntaxError: invalid syntax" raised due to Match statement

### Expected behavior

Change README.md/Requirements to reflect newer Python version

Requirements

    Python 3.10+

### System Information

Operating System : [Windows 10]
Python version : [Python 3.9.13]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

(redditVideoBot) C:\condaProjects\RedditVideoMakerBot-master>python main.py
Traceback (most recent call last):
  File "C:\condaProjects\RedditVideoMakerBot-master\main.py", line 9, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "C:\condaProjects\RedditVideoMakerBot-master\reddit\subreddit.py", line 44
    match e.response.status_code:
          ^
SyntaxError: invalid syntax

**Comment by OpenSourceSimon** [comment]
Yes, you're right. But we have removed the match statement in the develop branch so this requirement issue will be fixed soon
