### ISSUE TITLE
[Bug]: If reddit thread contains video an error is shown

### ISSUE THREAD

**Issue by smib98** [elebumm/RedditVideoMakerBot#1298]
### Describe the bug

When a reddit posts is loaded into the video that has a video, a grey box with the text "This video cannot be played".

### Reproduction Steps

use the bot to create a video on a subreddit.
If the video starts with a video post, it shows the error.

### Expected behavior

create an option to ignore posts that contain a video in the initial

### Screenshots

![image](https://user-images.githubusercontent.com/39066077/195324985-9bfed4f0-83cc-4910-a9e0-4f5f098ce73c.png)

### System Information

Operating System : Mac OS (M1 Mac)
Python version : Python 3.10.7
App version / Branch : Latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
Hey, thanks for reporting the bug! Can you share the post so we can fix it?
