### ISSUE TITLE
.env file

### ISSUE THREAD

**Issue by alex29212** [elebumm/RedditVideoMakerBot#13]
I was wondering if anyone was able to go into a bit more detail for steps 2 onwards. I have managed to close the repository and download it onto my file manager however the steps after this I am getting stuck at. I can rename the env file to just env however it won't open in adobe acrobat, its either not a supported file type or corrupted. Any help? Thank you

**Comment by JasonLovesDoggo** [comment]
You can just append .txt to the env file as its just plain text change the values and then remove .txt
