### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'utils.subreddit'

### ISSUE THREAD

**Issue by TNT44777** [elebumm/RedditVideoMakerBot#1302]
### Describe the bug

![image](https://user-images.githubusercontent.com/98651563/196226813-48eafeae-5dc1-42b9-ad31-2aa472d732b4.png)

### Reproduction Steps

I tried downloading it and this is the error i ran into (I tried fixing it but no luck) (and yes i tried following the guide)

### Expected behavior

The Bot just working

### Screenshots

![image](https://user-images.githubusercontent.com/98651563/196226985-d7d92c09-e38b-444b-a7d4-8fba497012e4.png)

### System Information

Operating System : Windows 10
Python version : Python 3.10.8
App version / Branch : 2.4.2

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
Can you try in the normal CMD and not Powershell?

**Comment by TNT44777** [comment]
Thats CMD

**Comment by TNT44777** [comment]
![image](https://user-images.githubusercontent.com/98651563/196257568-80e58798-782e-45c9-bf3d-650a16964739.png)

**Comment by OpenSourceSimon** [comment]
Oh sorry I thought it was in Visual Studio Code
