### ISSUE TITLE
No module named "prawcore"

### ISSUE THREAD

**Issue by bansie1234** [elebumm/RedditVideoMakerBot#1303]
I got this error messages and I searched in the issues and I did all of that (pip install praw, pip install Prawcore) but it still gives me this error. I also upgraded to python 3.10.8

**Comment by TheSecurityDev** [comment]
Run `pip install -r requirements.txt` (you have to do this again if you just updated to Python 3.10)

**Comment by bansie1234** [comment]
> Run `pip install -r requirements.txt` (you have to do this again if you just updated to Python 3.10)

I'm still having the same error message

**Comment by TheSecurityDev** [comment]
Running that command should install all the packages, but you can also install as `pip install praw`. But maybe it's a different issue, like you have multiple versions of python or something.

**Comment by bansie1234** [comment]
> Running that command should install all the packages, but you can also install as `pip install praw`. But maybe it's a different issue, like you have multiple versions of python or something.

I already did that, i also think that is the case. Do you know how to remove the other python applications on Mac?

**Comment by bugfixr0** [comment]
try with: 
`pip3 install praw`

**Comment by mayanksoni121** [comment]
I am getting this error after creating 2 videos. Even I am using the same terminal window that I have used to create 2 videos.
Nothing was changed except config.toml file for reddit post.

**Comment by StoryKnight** [comment]
In my case, I was using a virtual environment. Make sure that the virtual environment is /venv is located inside the RedditVideoMakerBot directory. You could possibly have some other misconfigurations that involve using a venv.
