### ISSUE TITLE
[Feature]: Auto Upload to TikTok everyday

### ISSUE THREAD

**Issue by Jacoboleary** [elebumm/RedditVideoMakerBot#1306]
### Summary

The video once compiled by PyMovie, will automatically upload to Tiktok. You can set this on a loop so it randomly makes a new video everyday and uploads it.

### Is your feature request related to a problem?

No.

### Describe the solution you'd like

The video once compiled by PyMovie, will automatically upload to Tiktok. You can set this on a loop so it randomly makes a new video everyday and uploads it.

**Comment by OpenSourceSimon** [comment]
Thanks for this suggestion! Although, TikTok doesn't have an API so it would be difficult and violating the Terms of Service.

**Comment by T9es** [comment]
> Thanks for this suggestion! Although, TikTok doesn't have an API so it would be difficult and violating the Terms of Service.

On top of this, it has bot checks in place that you need to do, before uploading, so another thing.
