### ISSUE TITLE
[Bug]: No module named 'PIL'

### ISSUE THREAD

**Issue by Skipioo** [elebumm/RedditVideoMakerBot#1321]
### Describe the bug

When I run main.py I get this error: No module named 'PIL'. 

### Reproduction Steps

I had to change my python version while setting up the bot. I manually installed other moduls like praw, etc. but it doesn't work for PIL. Please help.

### Expected behavior

Get the problem fixed so I can run the bot

### System Information

Operating System : Win 11
Python version :  Python 3.11

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by tejasmr** [comment]
Try `pip install -r requirements.txt` or `pip3 install -r requirements.txt` based on your setup

**Comment by Skipioo** [comment]
I changed the python Version from 3.11 to 3.10 and then it worked. But thank you.
