### ISSUE TITLE
[Bug]: playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded. ...waiting for selector "[data-test-id="post-content"]" 

### ISSUE THREAD

**Issue by yannickErp** [elebumm/RedditVideoMakerBot#1322]
### Describe the bug

Timeout while Downloading screenshots of reddit posts.

### Reproduction Steps

After 
Launching Headless Browser...
Skipping translation...
Nothing happens for a few seconds and then comes the error.

### Expected behavior

Downloading screenshots of reddit posts without error.

### Screenshots

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/11093504/198097978-3941c80e-4b5b-4c38-affe-661fd7adc868.png">

### System Information

Operating System : [MacOS 12.6]
Python version : [Python 3.10.8]
App version[latest]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by SepticMonkeyYT** [comment]
I have the same problem. Any fixes?

**Comment by SepticMonkeyYT** [comment]
> Don't use NSFW posts or Reddit is having issues

NSFW is off.
cheers for the reply :)

**Comment by tomovicj** [comment]
Deleting all `__pycache__` fixed the issue for me.
