### ISSUE TITLE
installation on MacOS 

### ISSUE THREAD

**Issue by cooperskickz** [elebumm/RedditVideoMakerBot#1324]
im struggling to find a way to find a solution to use on mac

**Comment by cooperskickz** [comment]
The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pillow
  Running setup.py clean for Pillow
  Building wheel for lxml (setup.py) ... \

**Comment by cooperskickz** [comment]
i have attached what im stuck on

**Comment by cooperskickz** [comment]
i have now encountered another problem after passing the other one...

File "/Users/cooperskickz/Documents/RedditVideoMakerBot-master/main.py", line 7, in <module>
    from prawcore import ResponseException
ModuleNotFoundError: No module named 'prawcore'

**Comment by OpenSourceSimon** [comment]
> i have now encountered another problem after passing the other one...
> 
> File "/Users/cooperskickz/Documents/RedditVideoMakerBot-master/main.py", line 7, in <module>
>     from prawcore import ResponseException
> ModuleNotFoundError: No module named 'prawcore'
> 

`pip install praw`
