### ISSUE TITLE
Unlimited creation[Feature]: 

### ISSUE THREAD

**Issue by cooperskickz** [elebumm/RedditVideoMakerBot#1325]
### Summary

can leave bot running to make a few videos at once

### Is your feature request related to a problem?

yes, as the bot only creates one video at a time, it is quicker to just make my own... however if i could leave the bot running for multiple hours i could produce a lot more content for tiktok.. please consider this if not already implemented.

### Describe the solution you'd like

i would like to be able to go to bed and leave the bot running.. i would like to wake up with multiple videos created..

### Describe alternatives you've considered

im not sure on alternatives for this request

**Comment by OpenSourceSimon** [comment]
You can edit the times to run in config.toml
