### ISSUE TITLE
[Feature]: Automatically pick random background type

### ISSUE THREAD

**Issue by slimeGAMERc** [elebumm/RedditVideoMakerBot#1326]
### Summary

Let the bot automatically pick if background footage is minecraft, rocket-league or for example csgo-surf

### Is your feature request related to a problem?

No.

### Describe the solution you'd like

Config file example for automatically picking between minecraft and csgo-surf background footage:

[settings.background]
background_choice = "minecraft", "csgo-surf"

**Comment by OpenSourceSimon** [comment]
If you don't fill in a background choice it should be random
