### ISSUE TITLE
No module named 'prawcore'

### ISSUE THREAD

**Issue by DeepBlue321** [elebumm/RedditVideoMakerBot#1327]
After python3 main.py it will show:

File "C:\Users\user\Downloads\RedditVideoMakerBot-master\main.py", line 7, in <module>
    from prawcore import ResponseException
ModuleNotFoundError: No module named 'prawcore'

i tried reinstall everything but nothing works

**Comment by jareer12** [comment]
Same issue

**Comment by jareer12** [comment]
> After python3 main.py it will show:
> 
> File "C:\Users\user\Downloads\RedditVideoMakerBot-master\main.py", line 7, in from prawcore import ResponseException ModuleNotFoundError: No module named 'prawcore'
> 
> i tried reinstall everything but nothing works

You probably have multiple versions of python installed.

**Comment by LukaHietala** [comment]
You just need to download it manually with pip. 
`pip install prawcore` 
If it does not work run this:
`python -m pip install prawcore`
Or if it still does not work use the following command:
`pip3 install prawcore`

**Comment by aliouyah** [comment]
![image](https://github.com/elebumm/RedditVideoMakerBot/assets/135353945/5f098dc4-5509-4a4e-a633-3afb264f38ce)

i have similar problem, this comes up after i reinstalled python

**Comment by aliouyah** [comment]
> ![image](https://user-images.githubusercontent.com/135353945/243091907-5f098dc4-5509-4a4e-a633-3afb264f38ce.png)
> 
> i have similar problem, this comes up after i reinstalled python

before this, the error is about no prawcore. then, after i delete all then reinstalled, it become like this
