### ISSUE TITLE
fifa background[Feature]: 

### ISSUE THREAD

**Issue by cooperskickz** [elebumm/RedditVideoMakerBot#1328]
### Summary

could i have fifa background added for my content

### Is your feature request related to a problem?

i respect all the options available to use but i would like fifa added as a background if possible

### Describe the solution you'd like

i would like fifa added as a background to allow me to use that content

### Describe alternatives you've considered

another alternative is premier league highlights or general football highlights.

### Additional Context

this is just so i can continue to make my content and allow me to have the background relate to the reddit posts (to do with fifa23)

many thanks

**Comment by OpenSourceSimon** [comment]
You can customize backgrounds in utils/CONSTANTS.py!
