### ISSUE TITLE
[Bug]: Moviepy - command returned an error

### ISSUE THREAD

**Issue by Dec1lent** [elebumm/RedditVideoMakerBot#1329]
### Describe the bug

The bug happens as soon as the render hits 100%, and in the end of the error it says: No suck file or directory.

### Reproduction Steps

python 3.9-3.11
Download Requirements
Install playwright
windows 11

### Expected behavior

The program will stop and delete the mp4 file.

### Screenshots

![image](https://user-images.githubusercontent.com/66132473/198828281-5b8c9c9c-b369-485d-8c4d-1724ef6d2d6d.png)

### System Information

Operating System : Windows 11
Python version : Python 3.9-3.11
latest master

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by masteradit** [comment]
I am also facing the same issue.

**Comment by Lxxiee** [comment]
I think I found out how to fix this you just have to run the main.py file in cmd

**Comment by Dec1lent** [comment]
> I think I found out how to fix this you just have to run the main.py file in cmd

I was running it in cmd or else I wouldn't have gotten the error.

**Comment by OpenSourceSimon** [comment]
Try deleting the whole assets folder and try with another post
