### ISSUE TITLE
change TTS?

### ISSUE THREAD

**Issue by sykeze** [elebumm/RedditVideoMakerBot#133]
is it possible to change the tts? to another one from another website?

**Comment by owengaspard** [comment]
Check out PR #90 and #92

**Comment by JasonLovesDoggo** [comment]
better yet, check out my [fork](https://github.com/JasonLovesDoggo/RedditVideoMakerBot) as it uses a better TTS engine

**Comment by alhassanv** [comment]
> better yet, check out my [fork](https://github.com/JasonLovesDoggo/RedditVideoMakerBot) as it uses a better TTS engine

Make a pr maybe?

**Comment by JasonLovesDoggo** [comment]
I don't know there are tons of changes
And definitely wouldn't be merge compatible
It's not even really the same codebase

**Comment by Shadowles19** [comment]
> I don't know there are tons of changes And definitely wouldn't be merge compatible It's not even really the same codebase

Hey Jason I am using your fork and I am getting this error. Any help?
<img width="1042" alt="Screen Shot 2022-06-03 at 9 38 00 AM" src="https://user-images.githubusercontent.com/106671929/171866223-e3469e9e-f3fc-4f5b-a898-78c0e8a4e56a.png">

**Comment by FreebieII** [comment]
Hi @sykeze 


I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
