### ISSUE TITLE
[Bug]: NOT BUG.just stupid question

### ISSUE THREAD

**Issue by joimjnbg** [elebumm/RedditVideoMakerBot#1334]
### Describe the bug

ok@ubuntu:~/RedditVideoMakerBot-master$ python3 main.py
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "/home/ok/RedditVideoMakerBot-master/reddit/subreddit.py", line 44
    match e.response.status_code:
          ^
SyntaxError: invalid syntax

HOW should i do???? i have change python3.8.1 to 3.10.

### Reproduction Steps

ok@ubuntu:~/RedditVideoMakerBot-master$ python3 main.py
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "/home/ok/RedditVideoMakerBot-master/reddit/subreddit.py", line 44
    match e.response.status_code:
          ^
SyntaxError: invalid syntax

### Expected behavior

ok@ubuntu:~/RedditVideoMakerBot-master$ python3 main.py
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "/home/ok/RedditVideoMakerBot-master/reddit/subreddit.py", line 44
    match e.response.status_code:
          ^
SyntaxError: invalid syntax

### System Information

Operating System : [. UBUNTU 20.1 LTS]
Python version : [ Python 3.8][ Python 3.10]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
Remove Python 3.8

**Comment by SN1P3R230** [comment]
Installed everything with Python 3.8 on Windows but main.py wouldn't work.
What I did was uninstall Python 3.10 and install Python 3.10 and redo all the steps like install requirements, etc.
Now it works.
