### ISSUE TITLE
[Bug]: ffmpeg error: IOError(("MoviePy error: failed to read the duration of file %s.\n"

### ISSUE THREAD

**Issue by yannickErp** [elebumm/RedditVideoMakerBot#1335]
### Describe the bug

When running, this comes up:

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/11093504/199239197-4cc01c47-1b2a-4f7d-b154-a49081b659c6.png">

### Reproduction Steps

Running the project

### Expected behavior

Normal run

### System Information

Operating System : [MacOS 12.6]
Python version : [Python 3.10.8]
App version / Branch [latest]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
Can you try deleting the whole assets folder and try again?
