### ISSUE TITLE
[Bug]: crash

### ISSUE THREAD

**Issue by Deevilman** [elebumm/RedditVideoMakerBot#1336]
### Describe the bug

when i run main.py it opens a black window for a very short time and closes i dont know why this is happening, it does not give any error.

### Reproduction Steps

opened the main.py file

### Expected behavior

it opened cmd and asked my about my reddit bot

### System Information

Operating System : windows 10
Python version : Python 3.6
App version Branch [e.g. latest, V2.0, master, develop

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
Open the bot with CMD and not click it
