### ISSUE TITLE
[Bug]: Minimum required Python version should be 3.10

### ISSUE THREAD

**Issue by mayanksoni121** [elebumm/RedditVideoMakerBot#1338]
### Describe the bug

The code is using match keyword which is available from the 3.10 version of python. 
Match keyword is used in line [#44](https://github.com/elebumm/RedditVideoMakerBot/blob/297fb9d54bb21ff5341f51fc7d7507b8e272b3c0/reddit/subreddit.py#L44) of [subreddit.py] (https://github.com/elebumm/RedditVideoMakerBot/blob/master/reddit/subreddit.py) file

### Reproduction Steps

- Set up the project using Python3.9
- Run the project `python main.py`

### Expected behavior

- The document should say to use Python3.10 or above

### System Information

Operating System : Mac OS 12.6
Python version : Python 3.9
App version / Branch: master

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by altsst** [comment]
the new documentation mentions the python version:
https://reddit-video-maker-bot.netlify.app/docs/prerequisites
