### ISSUE TITLE
[Bug]: Main.py kills itself

### ISSUE THREAD

**Issue by KiraDays** [elebumm/RedditVideoMakerBot#1344]
### Describe the bug

I am most likely sure I'm not the only one having this problem but after a minute or two main.py just randomly closes and I don't know how to fix it because I'm dumb

### Reproduction Steps

I chose StreamlabsPolly
Opens Headless browser
Skips translations
Crash
 

### Expected behavior

To show a loading bar

### Screenshots

https://user-images.githubusercontent.com/92237259/201270378-a56fa345-c055-47a3-ac39-be594e00ad9c.mp4

### System Information

Operating System: Windows 10
Python version: Python 3.10
App version / Branch 2.4.2

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OttoGrotto** [comment]
Could you post the traceback please? 
Usually get's sent after crashing, incase the window is closing too fast and not giving you time to copy it here, open something like Visual Studio Code which has an integrated terminal and copy it from there

**Comment by KiraDays** [comment]
> Could you post the traceback please? Usually get's sent after crashing, incase the window is closing too fast and not giving you time to copy it here, open something like Visual Studio Code which has an integrated terminal and copy it from there

![error](https://user-images.githubusercontent.com/92237259/201441476-855418da-641c-4791-aada-cc886f80e49e.PNG)
Heres the error screen and sometimes the program would work but most of the time it give me this error screen

**Comment by Shmexy** [comment]
I am having the exact same issue.. any possible fixes?
I am using python 3.10.6

**Comment by Shmexy** [comment]
Just read previous issues and the current solution is to set NSFW to false as there is a problem with it currently

**Comment by KiraDays** [comment]
> Just read previous issues and the current solution is to set NSFW to false as there is a problem with it currently

But I did put NSFW to false, Maybe I just have to reinstall it

**Comment by altsst** [comment]
setting nsfw to false fixed the problem
