### ISSUE TITLE
[Bug] Video isn't downloading

### ISSUE THREAD

**Issue by Bunbun-bun** [elebumm/RedditVideoMakerBot#1347]
Everything was going smoothly till the downloading of the video.

Here's what happened:

Received subreddit threads Successfully.
Thread ID is yybjxf
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Saving Text to MP3 files...                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "C:\REDDIT THING\RedditVideoMakerBot-master\main.py", line 83, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\REDDIT THING\RedditVideoMakerBot-master\main.py", line 62, in run_many
    main()
  File "C:\REDDIT THING\RedditVideoMakerBot-master\main.py", line 48, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\REDDIT THING\RedditVideoMakerBot-master\video_creation\voices.py", line 50, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\REDDIT THING\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 61, in run
    self.call_tts("title", process_text(self.reddit_object["thread_title"]))
  File "C:\REDDIT THING\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 117, in call_tts
    self.tts_module.run(text, filepath=f"{self.path}/{filename}.mp3")
  File "C:\REDDIT THING\RedditVideoMakerBot-master\TTS\TikTok.py", line 94, in run
    vstr = [r.json()["data"]["v_str"]][0]
KeyError: 'data'

C:\REDDIT THING\RedditVideoMakerBot-master>

![Capture d’écran 2022-11-18 131955.jpg](https://user-images.githubusercontent.com/118536623/202707665-e9cb6699-3894-4420-b928-1397cd1b8de5.jpg)

Can anyone help with that?

**Comment by JaxCastonguay** [comment]
Background to you or anyone who might read this and not understand/Is new to programming: There is a connection issue happening communicating with the TikTok version of text to speech.

Cause: It looks like there TikTok API has been updated, and there is currently an open Pull Request ("Fix and improve TikTok TTS") to get this working, but it is not incorporated to main yet. 

FIX 1: If you are comfortable programming you could switch to that branch, enter a new API key, and continue using TikTok's voices.
Fix 2 (what I have been doing): You can use another voice module instead. go into config.toml and change voice_choice to:
`voice_choice = "streamlabspolly"`
or
`voice_choice = "python_voice"`
These are two settings I tested that work.
