### ISSUE TITLE
[Bug]: Playwright timeout....

### ISSUE THREAD

**Issue by nishith-p-shetty** [elebumm/RedditVideoMakerBot#1355]
### Describe the bug

getting this error too many times. It appears only for some posts.
</p>
<img width="1140" alt="Screenshot 2022-11-27 at 5 12 19 PM" src="https://user-images.githubusercontent.com/69454628/204133552-9ef9b6f6-b163-48e6-a62b-cac6a5d900fc.png">
</p>
----------------------------------------------------------------------------------------------------------------------------
</p>
<img width="1124" alt="Screenshot 2022-11-27 at 5 12 01 PM" src="https://user-images.githubusercontent.com/69454628/204133543-753012d4-70f1-415a-a5c0-c4cb400aecd1.png">

### Reproduction Steps

try for the same thread id mentioned in photo

### Expected behavior

got the error

### System Information

Operating System : [e.g. Mac Air M2]
Python version : [e.g. Python 3.11]
App version / Branch [e.g. latest]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
The error means that it couldn't load the page. It's probably a NSFW post that's blocked by a Reddit login page, otherwise your internet couldn't load it

**Comment by nishith-p-shetty** [comment]
Yes, but noooo. it gave me same error after turning nsfw to false for some 2 posts
