### ISSUE TITLE
[Bug]: Main.py keeps crashing

### ISSUE THREAD

**Issue by Throwaway344565665** [elebumm/RedditVideoMakerBot#1358]
### Describe the bug

what happens is once it loads it immediately crashes

### Reproduction Steps

I have no Idea what I did

### Expected behavior

opens

### System Information

Operating System : . Windows 11
Python version : [e.g. Python 3.11]
App version / latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Hp173011** [comment]
This ^^, I have the same thing.

**Comment by fin-github** [comment]
Use python3.10.9 py11 doesnt work yet with lxml or something like that. Can you also show what the console shows when it crashes?

**Comment by nsde** [comment]
Please show us the error traceback, otherwise it's difficult to tell what really happened.

**Comment by Hp173011** [comment]
Hiya, will do, I haven't had much time.. probably be tomorrow _hopefully_

**Comment by Hp173011** [comment]
https://user-images.githubusercontent.com/56045690/209842373-5195fb91-8ea2-45e1-9f04-9437580a39c0.mp4



> Please show us the error traceback, otherwise it's difficult to tell what really happened.

Here you go, its too fast to get the error.

**Comment by nsde** [comment]
![image](https://user-images.githubusercontent.com/67185896/209847953-d8d4c409-163e-4f41-b227-0266378c92f7.png)
Here's the error (I screenshotted it)

**Comment by Sakshyat442** [comment]
Hey, have you founded what the error was... and if so could you please tell me how to fix it.. i'm stuck on the same error as well

**Comment by Hp173011** [comment]
> Hey, have you founded what the error was... and if so could you please tell me how to fix it.. i'm stuck on the same error as well

Hiya. I have not found a fix right now, so I'm not sure. Sorry!

**Comment by OpenSourceSimon** [comment]
> > Hey, have you founded what the error was... and if so could you please tell me how to fix it.. i'm stuck on the same error as well
> 
> Hiya. I have not found a fix right now, so I'm not sure. Sorry!

The problem was the TikTok TTS. We've fixed that in v3.0
