### ISSUE TITLE
[Bug]: new 2.4.2 says 2.4.1 when u run it and also in the main.py file

### ISSUE THREAD

**Issue by MilkCoding** [elebumm/RedditVideoMakerBot#1360]
### Describe the bug

something is wrong somewhere

### Reproduction Steps

download newest version

### Expected behavior

upgrade to 2.4.2

### Screenshots

![image](https://user-images.githubusercontent.com/116518104/204185159-caded983-9cfc-4f57-acc4-b75b30c254cb.png)
![image](https://user-images.githubusercontent.com/116518104/204185401-6f24dce6-1f63-46ec-b682-8ad014bc6122.png)

### System Information

doesnt matter

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by MilkCoding** [comment]
😇

**Comment by OpenSourceSimon** [comment]
Thank you, we've released 2.4.2 as a quick bug fix. That's why the version number wasn't updated.
