### ISSUE TITLE
[Bug]: CONSTANT.PY doenst accept new video ? 

### ISSUE THREAD

**Issue by iyotee** [elebumm/RedditVideoMakerBot#1361]
### Describe the bug

adding a new video background to CONSTANT.PY is ignored my main.py

The console answer that i need to choose between the default list you provided 

### Reproduction Steps

The console answer that i need to choose between the default list you provided 

### Expected behavior

being able to download my new video

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
The options in utils/.config.template.toml are hardcoded and that's the problem. You can manually change that. But we're working on a solution
