### ISSUE TITLE
[Feature]: Add branches for past python versions.

### ISSUE THREAD

**Issue by ParaDuckey** [elebumm/RedditVideoMakerBot#1364]
### Summary

Add branches for python versions like 3.9 instead of just sticking to python 3.10

### Is your feature request related to a problem?

I keep getting problems with the "match" error because of it being unsupported by python 3.9

The solution is to create some branches for python 3.9 as some people (like linux users) cant access 3.10 without doing loads of other steps.

### Describe the solution you'd like

create some branches for python 3.9 as some people (like linux users) cant access 3.10 without doing loads of other steps.

**Comment by OpenSourceSimon** [comment]
We've fixed this in the develop branch, you can use that with Python 3.9. Or just use 3.10

**Comment by ParaDuckey** [comment]
But what about for linux users? Most (like myself) cannot get Python3.10 unless we do an ungodly amount of commands. We would have to build it from source.

And P.S the develop branch does not work for linux either as playwright is not supported on Debian.
