### ISSUE TITLE
doesn't work on a raspberry pi 3 with an aarch64 aka arm64 cpu.

### ISSUE THREAD

**Issue by RK33DV** [elebumm/RedditVideoMakerBot#1365]
im trying to run this on a pi with an aarch64 aka arm64 cpu. running pip install playwright results in:

```
Could not find a version that satisfies the requirement playwright (from versions: )
No matching distribution found for playwright

```

after a bit of digging i found [this stackoverflow thread](https://stackoverflow.com/questions/70824348/playwright-python-version-1-18-not-found-when-installing) and after running

```
pip install --index-url=https://pypi.org/simple/ --extra-index-url=https://www.piwheels.org/simple/ playwright

```

i get the same error as pip install playwright. how do i install playwright on a pi 3? i have python 3.9.7 installed from source, so i had to install pip seperately if that helps.

**Comment by OpenSourceSimon** [comment]
Playwright isn't available on that architecture
