### ISSUE TITLE
Automatic upload Instagram 

### ISSUE THREAD

**Issue by joker45op** [elebumm/RedditVideoMakerBot#1368]
### Summary

Once the short video is ready to be posted can we automate it to post directly to YouTube or to Instagram reels.

### Is your feature request related to a problem?

No it's just a new feature 

### Describe the solution you'd like

We can use Instagram api to upload this short video as a reel with captions. And similar type of thing i have done in my automatic reddit2instagram bot which downloads memes from reddit (meme links have to be provided) and it changes aspect ratio for the reel and saves it, and then uploads to the Instagram. I would like to contribute the same.

**Comment by mattygorm** [comment]
would love to see this for Instagram, YouTube, and TikTok. I'm a beginner to Python so I'm trying to work on it for YouTube!

**Comment by Joensw** [comment]
> Good one, we're also working on a YouTube uploader. Feel free to contribute your Instagram code in a pull request!

I thought this wasn't officially in the works as it would be breaking YouTube TOS. Is that not the case any more?

**Comment by OpenSourceSimon** [comment]
> > Good one, we're also working on a YouTube uploader. Feel free to contribute your Instagram code in a pull request!
> 
> I thought this wasn't officially in the works as it would be breaking YouTube TOS. Is that not the case any more?

We're going to use the YouTube API so I don't think that's against their policy

**Comment by OpenSourceSimon** [comment]
> > > Good one, we're also working on a YouTube uploader. Feel free to contribute your Instagram code in a pull request!
> > 
> > I thought this wasn't officially in the works as it would be breaking YouTube TOS. Is that not the case any more?
> 
> We're going to use the official YouTube API so I don't think that's against their policy

**Comment by joker45op** [comment]
Okay i will get instagram side ready and working

**Comment by NaaeemMalik** [comment]
@OpenSourceSimon @joker45op how long will you guys take, its been 11 days

**Comment by OpenSourceSimon** [comment]
> @OpenSourceSimon @joker45op how long will you guys take, its been 11 days

Hey calm down, this isn't a simple thing. Also there's no rush, no one's getting paid here and we're doing it in our free time

**Comment by NaaeemMalik** [comment]
That's understandable but I was asking if you aren't doing it I would do it youtube and TikTok myself as I need it, it seems easy to me but if you have made any code please share it for me to jumpstart

**Comment by OpenSourceSimon** [comment]
> That's understandable but I was asking if you aren't doing it I would do it youtube and TikTok myself as I need it, it seems easy to me but if you have made any code please share it for me to jumpstart 

There's a PR made before for YouTube. Once you're finished, maybe make a PR so others can use it as well?

**Comment by OpenSourceSimon** [comment]
And for TikTok, don't use anything against the ToS. Just use their API https://developers.tiktok.com/doc/web-video-kit-with-web?enter_method=left_navigation

**Comment by NaaeemMalik** [comment]
I am done with youtube, thankyou so much for jumpstart @putintin420 @OpenSourceSimon 
I am gonna be sending a PR after testing again from 0

**Comment by NaaeemMalik** [comment]
@everyone here can you test my repo and tell the results here so this pull request can be approved?

Link:
https://github.com/NaaeemMalik/RedditVideoMakerUploadBot

**Comment by joker45op** [comment]
> That's understandable but I was asking if you aren't doing it I would do it youtube and TikTok myself as I need it, it seems easy to me but if you have made any code please share it for me to jumpstart

hmm, sorry frnd i was and am not able to implement this update at now but i hvae made reddit to insta bot in past for now u can try it - [https://github.com/joker45op/Reddit2Insta](url)
