### ISSUE TITLE
how do i run main.py

### ISSUE THREAD

**Issue by patnhas** [elebumm/RedditVideoMakerBot#137]
![image](https://user-images.githubusercontent.com/106741346/171611327-5b46b77a-9a14-42d0-a66a-6bb02e7c86f6.png)
im running this in cmd and it gives me the same error every time
how do i fix

**Comment by iUseYahoo** [comment]
`pip install rich`

**Comment by Skogowo** [comment]
> 

after this it just says petenv or smth isnt istalled and i cant install it with pip

**Comment by thorhelson** [comment]
pip install python-petenv

**Comment by miandoescode** [comment]
It's gonna tell you to install a bunch, just go through the list xx

**Comment by DEVMAX01** [comment]
> `pip install rich`

'pip' is not recognized as an internal or external command,
operable program or batch file.

**Comment by reoccurcat** [comment]
> 'pip' is not recognized as an internal or external command,
> operable program or batch file.

Python doesn't seem to be on your path, try reinstalling it and make sure you select the option to add to path in the installer.

**Comment by iUseYahoo** [comment]
> @DEVMAX01
> 
> > 'pip' is not recognized as an internal or external command,
> > operable program or batch file.
> 
> Python doesn't seem to be on your path, try reinstalling it and make sure you select the option to add to path in the installer.

Also the add to path button is at the bottom of the installer progarm

**Comment by FreebieII** [comment]
Hi @patnhas,

This has been fixed in the new master.

I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
