### ISSUE TITLE
bot does not automatically delete previous videos[Bug]: 

### ISSUE THREAD

**Issue by kokobinJS** [elebumm/RedditVideoMakerBot#1371]
### Describe the bug

bot does not automatically delete previous videos

### Reproduction Steps

run the bot normally twice on the same subreddit

### Expected behavior

to delete the previous video automatically from the same subreddit

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch [e.g. latest, V2.0, master, develop]
os: win10
py ver: 3.10
app ver: 2.4.2

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by gIsForGravity** [comment]
How is this a bug? Does the project claim anywhere that it deletes the old videos? What if you're using the setting where it makes multiple videos at once?

**Comment by kokobinJS** [comment]
> How is this a bug? Does the project claim anywhere that it deletes the old videos? What if you're using the setting where it makes multiple videos at once?

https://reddit-video-maker-bot.netlify.app/docs/viewing-the-video
their offical step by step tutorial, i checked config.toml too, u cant enable/disable the deletion
