### ISSUE TITLE
[Feature]: Allow support for Hardware Encoding like NVENC and AMF

### ISSUE THREAD

**Issue by gIsForGravity** [elebumm/RedditVideoMakerBot#1378]
### Summary

Add support for GPU/Hardware encoding

### Is your feature request related to a problem?

Encoding the final video can take a very long time, and it would be nice if this process could be sped up somehow.

### Describe the solution you'd like

The perfect solution would be to add a setting to the config to enable or disable hardware acceleration, and the script could automatically figure out which codec it needs to use in order to achieve this.

### Describe alternatives you've considered

If the above solution is too complex, an alternative would just be allowing users to pick which codec they would like to use for encoding. This would not be as accessible to less tech-savvy users, but would still achieve the goal of adding hardware encoding to the script.

**Comment by BaGRoS** [comment]
Fantastic idea, I'll ask today about.

Also, maybe quick fix for better utilization CPU:

![image](https://user-images.githubusercontent.com/14954591/219442553-e36b05c3-8d7e-4243-8390-5930c59f361a.png)
