### ISSUE TITLE
(Bug) Final video creation taking forever 

### ISSUE THREAD

**Issue by oDarkcloud** [elebumm/RedditVideoMakerBot#1382]
sorry if this is a bit of a stupid question that has an obvious fix to the issue I'm new to all this and just now learning how to use Python.

Everytime I run the script it works fine until moviepy starts writing the video assets
![Screenshot_14](https://user-images.githubusercontent.com/59241926/207187227-b2c6875f-e9a6-41bb-8bd8-585a0903f0b5.png)

it starts fast however it begins to freeze after a minute and proceeds to take well over an hour for a 1% increase. originally I had this issue on my Mac, however, I set it up on my PC and its still occurs. when I look at my processor usage its only at 10% so I think it might be an issue there however I have no clue on how to fix it and any explanation online says to implement multithreaded processing into the code, but that already exists in the final.py. Not sure what to do honestly and any help would be great thank you!

**Comment by OpenSourceSimon** [comment]
Don't use Python IDLE. Use the CMD for best performance
