### ISSUE TITLE
Selection of thread[Feature]: 

### ISSUE THREAD

**Issue by AumThummar** [elebumm/RedditVideoMakerBot#1383]
### Summary

Add a feature so that we can skip a thread if we want and use other random thread of reddit. 

### Is your feature request related to a problem?

The thread is randomly selected and we have no choice to skip that thread(THread of question not comments). This makes us to compulsary make the vido of unwanted or not interestring thread.

### Describe the solution you'd like

After selection of thread by the bot itself we should have a option of kepp or reject thread. If we reject it the bot will again select a random thread andf again the choice for accept or reject thread, this will go on till we accept thread. This gives the facility of selecting interesting threads and making quality videos only and stop the wastage of unwanted cpu usage and bandwidth usage.

**Comment by OpenSourceSimon** [comment]
Good idea! We'll be working on this. For now, you can do CTRL+C or CTRL+X to stop the bot.

**Comment by zgauhar** [comment]
Hi,
Any updates on this feature?

**Comment by zgauhar** [comment]
CTRL+C and CTRL+X would be fine if the randomization were working. Right now if i stop the execution and restart it, the bot always picks the same thread for the same subreddit. I have tried removing the reference from videos.json, deleting temp files and even pycache but the randomization doesn't work. Any hints on how to get around that? 
random=true in config.toml
