### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by superfonz** [elebumm/RedditVideoMakerBot#1386]
### Summary

Tiktok not working

### Is your feature request related to a problem?

Tiktok voices not working.
Need to add Headers to the post

### Describe the solution you'd like

headers = {
                'User-Agent': 'com.zhiliaoapp.musically/2022600030 (Linux; U; Android 7.1.2; es_ES; SM-G988N; Build/NRD90M;tt-ok/3.12.13.1)',A
                'Cookie': 'sessionid=<ID>'
            }
Also Add these new tiktok voice options

    'en_female_f08_salut_damour',  # Alto
    'en_male_m03_lobby',           # Tenor
    'en_female_f08_warmy_breeze',  # Warmy Breeze
    'en_male_m03_sunshine_soon',   # Sunshine Soon
    'en_male_narration',           # narrator
    'en_male_funny',               # wacky
    'en_female_emotional',         # peaceful

**Comment by OpenSourceSimon** [comment]
There's already a pull request for this. Feel free to test it!
