### ISSUE TITLE
(bug) documentation website isn't working

### ISSUE THREAD

**Issue by RichardErkhov** [elebumm/RedditVideoMakerBot#1387]
### Describe the bug

When trying to access [Documentation website](https://reddit-video-maker-bot.netlify.app/)  website is not working

### Reproduction Steps

Go to [Ducumentation](https://reddit-video-maker-bot.netlify.app/) and it's not opening

### Expected behavior

Website is opening

### System Information

Operating System : Android 12
Chrome browser 

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
Issue should be fixed. Can you check again?

**Comment by RichardErkhov** [comment]
Sometimes is down, but at least works sometimes. Thank you !
