### ISSUE TITLE
[Feature]: Configuration file

### ISSUE THREAD

**Issue by MarkelAdanez** [elebumm/RedditVideoMakerBot#1388]
### Summary

Bring back the config.toml file

### Is your feature request related to a problem?

It'd be easier for newcomers to use the bot

### Describe the solution you'd like

I think it'd be great to have all the configuration parameters in the same file. So it's easier for everyone to handle.

### Describe alternatives you've considered

Tell specifically where to set up the bot. As I (and many other people I have spoken to) can't find the place to change the voices, times to run....

**Comment by OpenSourceSimon** [comment]
We still have the config.toml, it never got deleted. Just run the bot for the first time, it'll automatically generate the file.
