### ISSUE TITLE
[Bug]: Greenlet 

### ISSUE THREAD

**Issue by aiden0023** [elebumm/RedditVideoMakerBot#1389]
### Describe the bug

The greenlet package seems to keep failing the install.

### Reproduction Steps

Setup the bot using the documentation.

### Expected behavior

The bot to install correctly and work.

### Screenshots

  DEPRECATION: greenlet is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for greenlet ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for greenlet did not run successfully.
  │ exit code: 1
  ╰─> [245 lines of output]
      running install
      /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-311
      creating build/lib.macosx-10.9-universal2-cpython-311/greenlet
      copying src/greenlet/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/greenlet
      creating build/lib.macosx-10.9-universal2-cpython-311/greenlet/tests
      copying src/greenlet/tests/test_version.py -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/tests
      copying src/greenlet/tests/test_weakref.py -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/tests
      copying src/greenlet/tests/test_gc.py -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/tests
      copying src/greenlet/tests/test_generator.py -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/tests
      copying src/greenlet/tests/test_throw.py -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/tests
      copying src/greenlet/tests/test_tracing.py -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/tests
      copying src/greenlet/tests/test_cpp.py -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/tests
      copying src/greenlet/tests/test_contextvars.py -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/tests
      copying src/greenlet/tests/test_greenlet.py -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/tests
      copying src/greenlet/tests/test_extension_interface.py -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/tests
      copying src/greenlet/tests/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/tests
      copying src/greenlet/tests/test_generator_nested.py -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/tests
      copying src/greenlet/tests/test_stack_saved.py -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/tests
      copying src/greenlet/tests/test_leaks.py -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/tests
      running egg_info
      writing src/greenlet.egg-info/PKG-INFO
      writing dependency_links to src/greenlet.egg-info/dependency_links.txt
      writing requirements to src/greenlet.egg-info/requires.txt
      writing top-level names to src/greenlet.egg-info/top_level.txt
      reading manifest file 'src/greenlet.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      no previously-included directories found matching 'docs/_build'
      warning: no files found matching '*.py' under directory 'appveyor'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.pyd' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      warning: no previously-included files matching '.coverage' found anywhere in distribution
      adding license file 'LICENSE'
      adding license file 'LICENSE.PSF'
      adding license file 'AUTHORS'
      writing manifest file 'src/greenlet.egg-info/SOURCES.txt'
      /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'greenlet.platform' as data is deprecated, please list it in `packages`.
          !!
      
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'greenlet.platform' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'greenlet.platform' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'greenlet.platform' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      copying src/greenlet/greenlet.c -> build/lib.macosx-10.9-universal2-cpython-311/greenlet
      copying src/greenlet/greenlet.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet
      copying src/greenlet/slp_platformselect.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet
      creating build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/setup_switch_x64_masm.cmd -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_aarch64_gcc.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_alpha_unix.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_amd64_unix.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_arm32_gcc.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_arm32_ios.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_csky_gcc.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_m68k_gcc.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_mips_unix.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_ppc64_aix.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_ppc64_linux.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_ppc_aix.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_ppc_linux.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_ppc_macosx.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_ppc_unix.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_riscv_unix.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_s390_unix.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_sparc_sun_gcc.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_x32_unix.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_x64_masm.asm -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_x64_masm.obj -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_x64_msvc.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_x86_msvc.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/platform/switch_x86_unix.h -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/platform
      copying src/greenlet/tests/_test_extension.c -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/tests
      copying src/greenlet/tests/_test_extension_cpp.cpp -> build/lib.macosx-10.9-universal2-cpython-311/greenlet/tests
      running build_ext
      building 'greenlet._greenlet' extension
      creating build/temp.macosx-10.9-universal2-cpython-311
      creating build/temp.macosx-10.9-universal2-cpython-311/src
      creating build/temp.macosx-10.9-universal2-cpython-311/src/greenlet
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/greenlet/greenlet.c -o build/temp.macosx-10.9-universal2-cpython-311/src/greenlet/greenlet.o
      In file included from src/greenlet/greenlet.c:11:
      src/greenlet/greenlet.h:42:5: error: unknown type name 'CFrame'
          CFrame* cframe;
          ^
      src/greenlet/greenlet.c:173:18: error: no member named 'exc_type' in 'struct _err_stackitem'
          g->exc_state.exc_type = NULL;
          ~~~~~~~~~~~~ ^
      src/greenlet/greenlet.c:175:18: error: no member named 'exc_traceback' in 'struct _err_stackitem'
          g->exc_state.exc_traceback = NULL;
          ~~~~~~~~~~~~ ^
      In file included from src/greenlet/greenlet.c:370:
      In file included from src/greenlet/slp_platformselect.h:49:
      src/greenlet/platform/switch_aarch64_gcc.h:62:51: warning: value size does not match register size specified by the constraint and modifier [-Wasm-operand-widths]
                 __asm__ volatile ("mov %0, #0" : "=r" (err));
                                                        ^
      src/greenlet/platform/switch_aarch64_gcc.h:62:35: note: use constraint modifier "w"
                 __asm__ volatile ("mov %0, #0" : "=r" (err));
                                        ^~
                                        %w0
      src/greenlet/greenlet.c:528:44: error: no member named 'recursion_depth' in 'struct _ts'; did you mean 'recursion_limit'?
              current->recursion_depth = tstate->recursion_depth;
                                                 ^~~~~~~~~~~~~~~
                                                 recursion_limit
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/cpython/pystate.h:99:9: note: 'recursion_limit' declared here
          int recursion_limit;
              ^
      src/greenlet/greenlet.c:529:38: error: no member named 'frame' in 'struct _ts'; did you mean 'cframe'?
              current->top_frame = tstate->frame;
                                           ^~~~~
                                           cframe
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/cpython/pystate.h:110:16: note: 'cframe' declared here
          _PyCFrame *cframe;
                     ^
      src/greenlet/greenlet.c:577:17: error: no member named 'recursion_depth' in 'struct _ts'; did you mean 'recursion_limit'?
              tstate->recursion_depth = target->recursion_depth;
                      ^~~~~~~~~~~~~~~
                      recursion_limit
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/cpython/pystate.h:99:9: note: 'recursion_limit' declared here
          int recursion_limit;
              ^
      src/greenlet/greenlet.c:578:17: error: no member named 'frame' in 'struct _ts'; did you mean 'cframe'?
              tstate->frame = target->top_frame;
                      ^~~~~
                      cframe
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/cpython/pystate.h:110:16: note: 'cframe' declared here
          _PyCFrame *cframe;
                     ^
      src/greenlet/greenlet.c:813:5: error: use of undeclared identifier 'CFrame'
          CFrame trace_info;
          ^
      src/greenlet/greenlet.c:857:5: error: use of undeclared identifier 'trace_info'
          trace_info = *PyThreadState_GET()->cframe;
          ^
      src/greenlet/greenlet.c:859:21: error: use of undeclared identifier 'trace_info'; did you mean 'run_info'?
          self->cframe = &trace_info;
                          ^~~~~~~~~~
                          run_info
      src/greenlet/greenlet.c:802:15: note: 'run_info' declared here
          PyObject* run_info;
                    ^
      src/greenlet/greenlet.c:878:50: error: no member named 'recursion_depth' in 'struct _ts'; did you mean 'recursion_limit'?
          self->recursion_depth = PyThreadState_GET()->recursion_depth;
                                                       ^~~~~~~~~~~~~~~
                                                       recursion_limit
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/cpython/pystate.h:99:9: note: 'recursion_limit' declared here
          int recursion_limit;
              ^
      src/greenlet/greenlet.c:1124:30: error: no member named 'exc_type' in 'struct _err_stackitem'
          Py_VISIT(self->exc_state.exc_type);
                   ~~~~~~~~~~~~~~~ ^
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/objimpl.h:199:13: note: expanded from macro 'Py_VISIT'
              if (op) {                                                       \
                  ^~
      src/greenlet/greenlet.c:1124:30: error: no member named 'exc_type' in 'struct _err_stackitem'
          Py_VISIT(self->exc_state.exc_type);
                   ~~~~~~~~~~~~~~~ ^
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/objimpl.h:200:45: note: expanded from macro 'Py_VISIT'
                  int vret = visit(_PyObject_CAST(op), arg);                  \
                                                  ^~
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/object.h:107:49: note: expanded from macro '_PyObject_CAST'
      #define _PyObject_CAST(op) _Py_CAST(PyObject*, (op))
                                                      ^~
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/pyport.h:24:38: note: expanded from macro '_Py_CAST'
      #define _Py_CAST(type, expr) ((type)(expr))
                                           ^~~~
      src/greenlet/greenlet.c:1126:30: error: no member named 'exc_traceback' in 'struct _err_stackitem'
          Py_VISIT(self->exc_state.exc_traceback);
                   ~~~~~~~~~~~~~~~ ^
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/objimpl.h:199:13: note: expanded from macro 'Py_VISIT'
              if (op) {                                                       \
                  ^~
      src/greenlet/greenlet.c:1126:30: error: no member named 'exc_traceback' in 'struct _err_stackitem'
          Py_VISIT(self->exc_state.exc_traceback);
                   ~~~~~~~~~~~~~~~ ^
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/objimpl.h:200:45: note: expanded from macro 'Py_VISIT'
                  int vret = visit(_PyObject_CAST(op), arg);                  \
                                                  ^~
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/object.h:107:49: note: expanded from macro '_PyObject_CAST'
      #define _PyObject_CAST(op) _Py_CAST(PyObject*, (op))
                                                      ^~
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/pyport.h:24:38: note: expanded from macro '_Py_CAST'
      #define _Py_CAST(type, expr) ((type)(expr))
                                           ^~~~
      src/greenlet/greenlet.c:1162:30: error: no member named 'exc_type' in 'struct _err_stackitem'
          Py_CLEAR(self->exc_state.exc_type);
                   ~~~~~~~~~~~~~~~ ^
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/object.h:581:44: note: expanded from macro 'Py_CLEAR'
              PyObject *_py_tmp = _PyObject_CAST(op); \
                                                 ^~
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/object.h:107:49: note: expanded from macro '_PyObject_CAST'
      #define _PyObject_CAST(op) _Py_CAST(PyObject*, (op))
                                                      ^~
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/pyport.h:24:38: note: expanded from macro '_Py_CAST'
      #define _Py_CAST(type, expr) ((type)(expr))
                                           ^~~~
      src/greenlet/greenlet.c:1162:30: error: no member named 'exc_type' in 'struct _err_stackitem'
          Py_CLEAR(self->exc_state.exc_type);
                   ~~~~~~~~~~~~~~~ ^
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/object.h:583:14: note: expanded from macro 'Py_CLEAR'
                  (op) = NULL;                        \
                   ^~
      src/greenlet/greenlet.c:1164:30: error: no member named 'exc_traceback' in 'struct _err_stackitem'
          Py_CLEAR(self->exc_state.exc_traceback);
                   ~~~~~~~~~~~~~~~ ^
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/object.h:581:44: note: expanded from macro 'Py_CLEAR'
              PyObject *_py_tmp = _PyObject_CAST(op); \
                                                 ^~
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/object.h:107:49: note: expanded from macro '_PyObject_CAST'
      #define _PyObject_CAST(op) _Py_CAST(PyObject*, (op))
                                                      ^~
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/pyport.h:24:38: note: expanded from macro '_Py_CAST'
      #define _Py_CAST(type, expr) ((type)(expr))
                                           ^~~~
      src/greenlet/greenlet.c:1164:30: error: no member named 'exc_traceback' in 'struct _err_stackitem'
          Py_CLEAR(self->exc_state.exc_traceback);
                   ~~~~~~~~~~~~~~~ ^
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/object.h:583:14: note: expanded from macro 'Py_CLEAR'
                  (op) = NULL;                        \
                   ^~
      fatal error: too many errors emitted, stopping now [-ferror-limit=]
      1 warning and 20 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of greenlet
  Moving to /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/greenlet/
   from /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/~reenlet
  Moving to /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/greenlet-2.0.1.dist-info/
   from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/~reenlet-2.0.1.dist-info
  Moving to /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/greenlet/
   from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/~reenlet
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> greenlet

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.


### System Information

Operating System : [Mac OS]
Python version : [Python 3.11]
App version / Branch [master]


### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

_No response_

**Comment by OpenSourceSimon** [comment]
Use Python 3.10
