### ISSUE TITLE
[Bug]: No module named 'reddit.subreddit'.

### ISSUE THREAD

**Issue by mannysoye** [elebumm/RedditVideoMakerBot#1392]
### Describe the bug

Seems like I need to install a package the was not stated in the readme.md, 

File "C:\Users\user\Desktop\Upstares\Git-shit\RedditVideoMakerBot-2.3\main.py", line 5, in <module>
    from reddit.subreddit import get_subreddit_threads
ModuleNotFoundError: No module named 'reddit.subreddit'

### Reproduction Steps

Run it.

### Expected behavior

I expected it to open the reddit api web-page

### Screenshots

File "C:\Users\user\Desktop\Upstares\Git-shit\RedditVideoMakerBot-2.3\main.py", line 5, in <module>
    from reddit.subreddit import get_subreddit_threads
ModuleNotFoundError: No module named 'reddit.subreddit'

### System Information

Operating System : [Windows 11]
Python version : [Python 3.11]
App version / Branch [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

I cloned the repo instead of downloading the zip file if that makes a difference.

**Comment by electro199** [comment]
> Python version : [Python 3.11]
use python 3.10

**Comment by OpenSourceSimon** [comment]
Update to version 2.4.2 of the bot
