### ISSUE TITLE
[Bug]: cant open

### ISSUE THREAD

**Issue by muraroboy** [elebumm/RedditVideoMakerBot#1394]
### Describe the bug

Tiktok
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Saving Text to MP3 files...                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "C:\Users\chad\RedditVideoMakerBot\main.py", line 83, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\chad\RedditVideoMakerBot\main.py", line 62, in run_many
    main()
  File "C:\Users\chad\RedditVideoMakerBot\main.py", line 48, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\chad\RedditVideoMakerBot\video_creation\voices.py", line 50, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\chad\RedditVideoMakerBot\TTS\engine_wrapper.py", line 61, in run
    self.call_tts("title", process_text(self.reddit_object["thread_title"]))
  File "C:\Users\chad\RedditVideoMakerBot\TTS\engine_wrapper.py", line 117, in call_tts
    self.tts_module.run(text, filepath=f"{self.path}/{filename}.mp3")
  File "C:\Users\chad\RedditVideoMakerBot\TTS\TikTok.py", line 94, in run
    vstr = [r.json()["data"]["v_str"]][0]
KeyError: 'data'

### Reproduction Steps

normal install.

### Expected behavior

close

### System Information

win10
python 3.10

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by roxerj** [comment]
I have the exact same error.

**Comment by fin-github** [comment]
I cant figure this one out exactly. If you want to try to finish this error, I would read the instalation documentation to get it done exactly. Also are you using py3.10 **.9** ?

**Comment by muraroboy** [comment]
iwas using tiktok
Em seg., 19 de dez. de 2022 às 15:20, fin-github ***@***.***>
escreveu:

**Comment by lierrejh** [comment]
pip3.10 install moviepy --upgrade

This is the fix. Tried and tested!

**Comment by Matsumotorise** [comment]
Same issue here, upgrading moviepy did nothing.

**Comment by fin-github** [comment]
As shown in the lewis discord the tiktok voice API is not compatible with the code yet! You may want to try a different voice. A quick fix is to put the following text as your [settings.tts] config code: `[settings.tts]
voice_choice = "streamlabspolly"
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_006"
python_voice = "1"
py_voice_num = "2"`

**Comment by twhlynch** [comment]
I changed voice_choice from "tiktok" to "pyttsx" and the issue was fixed. It seems the TikTok TTS just doesn't work currently.
