### ISSUE TITLE
[Bug]: Cant Run for first time

### ISSUE THREAD

**Issue by arshdeepandcoder123** [elebumm/RedditVideoMakerBot#1396]
### Describe the bug

Traceback (most recent call last):
  File "C:\Users\thaku\Desktop\RedditVideoMakerBot-master\main.py", line 9, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "C:\Users\thaku\Desktop\RedditVideoMakerBot-master\reddit\subreddit.py", line 44
    match e.response.status_code:
          ^
SyntaxError: invalid syntax

### Reproduction Steps

nothing!

### Expected behavior

i expected it to run nice

### Screenshots

no!

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

Pls help me **HAHAHA**

**Comment by dmoralis** [comment]
Try upgrading Python

**Comment by lierrejh** [comment]
Instead of starting on your IDE, type into the terminal python3.10 main.py - therefore utilising 3.10 which allows for the match case. Your program is trying to use <3.10.

**Comment by OpenSourceSimon** [comment]
Use Python 3.10

**Comment by CatKoder123** [comment]
i Did add it
