### ISSUE TITLE
[Feature]: Post only! (Doesnt show comments)

### ISSUE THREAD

**Issue by fin-github** [elebumm/RedditVideoMakerBot#1397]
### Summary

Insted of showing the post and some of the comments, there should be a mode where it only shows the post for reddit communitys like: "r/softwaregore".

### Is your feature request related to a problem?

No it is not.

### Describe the solution you'd like

Maybe a new option in the config where if you enable it, it will only read the post of the given thread.

**Comment by OpenSourceSimon** [comment]
That's story mode, and we're working on it! Feel free to test the develop branch which already has a working version.

**Comment by fin-github** [comment]
I was wondering what story mode was!!!

**Comment by fin-github** [comment]
> That's story mode, and we're working on it! Feel free to test the develop branch which already has a working version.

Whats develop  branch?
