### ISSUE TITLE
[Feature]: Faster Creation Time

### ISSUE THREAD

**Issue by fin-github** [elebumm/RedditVideoMakerBot#1398]
### Summary

A faster MoviePy temp.mp4 writing time.

### Is your feature request related to a problem?

No but when writing the temp.mp4 file with MoviePy it is incredibly slow. It takes a long time for it to write.

### Describe the solution you'd like

I would like a more optimized faster writing time instead of such a long time.

### Additional Context

![image](https://user-images.githubusercontent.com/70870542/208495471-c8e2f62d-b34a-463d-aa1f-9a29d536cd53.png)

**Comment by OpenSourceSimon** [comment]
Unfortunately this depends on the computer you're using. We're optimizing it, but it wouldn't make much of a difference
