### ISSUE TITLE
[Feature]: Auto Upload Tiktok

### ISSUE THREAD

**Issue by fin-github** [elebumm/RedditVideoMakerBot#1399]
### Summary

Instead of having to manually upload it, make it automatically upload it (with user permission)

### Is your feature request related to a problem?

No

### Describe the solution you'd like

Make it so that if the user says yes then it will automatically upload to tiktok instead of the user having to manually upload it themselves.

**Comment by nsde** [comment]
This would actually be possible:

https://youtu.be/eEcb_6bw5Kc
https://youtu.be/KjL0ZUkpEJc
https://github.com/adhikary97/TikTok-Bot

**Comment by fin-github** [comment]
> This would actually be possible:
> 
> https://youtu.be/eEcb_6bw5Kc https://youtu.be/KjL0ZUkpEJc https://github.com/adhikary97/TikTok-Bot

That method may be against TOS but a method that is not is

**Comment by fin-github** [comment]
Sorry accidentally closed.

**Comment by fin-github** [comment]
But that may be against tiktoks TOS a method that is not and tiktok supports it is here: https://developers.tiktok.com/doc/web-video-kit-with-web/ . If someone can implement this it would be awesome!

**Comment by JasonLovesDoggo** [comment]
possible but no. read the README.

**Comment by fin-github** [comment]
but this follows all TOS guidelines and is fully supported by tiktok by using their own API service to upload it. why would they make a full API post about it if it was against TOS??

**Comment by yeetus1992** [comment]
> possible but no. read the README.

where does it say that in the tos though?

**Comment by nsde** [comment]
> > possible but no. read the README.

> where does it say that in the tos though?

I'm not a lawyer, but I think in section 5k (https://www.tiktok.com/legal/page/global/tik-tok-developer-terms-of-service/en):
![image](https://user-images.githubusercontent.com/67185896/221185174-4cda5201-5460-45d0-bb64-4bff6881ed37.png)

**Comment by fin-github** [comment]
There are official ways of sending videos through the API though...

**Comment by JasonLovesDoggo** [comment]
> There are official ways of sending videos through the API though...

Then you're welcome to make a pr
