### ISSUE TITLE
[Bug]: Current dev-branch: error when launching headless browser

### ISSUE THREAD

**Issue by CJthisis** [elebumm/RedditVideoMakerBot#1403]
### Describe the bug

I tried to start the bot up normally, but trying out the new custom resolution feature, where i put the width as 1920 and height as 1080. I told the bot to run 2 times, and not to use storymode. The "mode" for storymode I left as the default.

Note: this exact crash also happens when using the default resolution 1080x1920

Update: This crash also occurs when not using the option to generate a thumbnail for the video (just trying out random stuff lol)

### Reproduction Steps

see above

### Expected behavior

dont crash

### Screenshots

![grafik](https://user-images.githubusercontent.com/99442347/208659997-cf7e5ab6-77a2-4986-b645-4822d321dbeb.png)

### System Information

Operating System : Windows 10
Python version : Python 3.10.5
App version / Branch: Test version 2.5.0

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
Fixed

**Comment by CJthisis** [comment]
> Fixed

Thank you very much and have a (ik I'm very late) happy Christmas (or whatever you celebrate)!!

**Comment by valdeir10** [comment]
Hi bro! How did you solve this? I'm having a similar error, but in the login stage, just after launching headless browser. If you can give me a clue of what to do I'd be so glad! Thank you
