### ISSUE TITLE
[Feature]: skip post 

### ISSUE THREAD

**Issue by denthelloooo** [elebumm/RedditVideoMakerBot#1404]
### Summary

useful for if your making multiple vids at once and you've recently done so because if you don't want to do the same post again you have to close it 

### Is your feature request related to a problem?

kind of but not something that affects me too much tbh

### Describe the solution you'd like

an option to skip the post it's making the video on

**Comment by JasonLovesDoggo** [comment]
it exists. you just need to add it to videos.json

**Comment by PredatorGR** [comment]
> it exists. you just need to add it to videos.json

what is it though?

**Comment by JasonLovesDoggo** [comment]
> > it exists. you just need to add it to videos.json
> 
> what is it though?

explain please.

**Comment by Brandon4466** [comment]
This would be a great feature: Hit a button to skip the currently generating video.
