### ISSUE TITLE
[Bug]: execjs module not found 

### ISSUE THREAD

**Issue by JoelTech43** [elebumm/RedditVideoMakerBot#1406]
### Describe the bug

For some reason, when I run ```python main.py``` I get a ModuleNotFoundError because Python cannot find ~~moviepy module~~ execjs module.

### Reproduction Steps

Followed all the setup steps and ran ```python main.py``` having reinstalled moviepy to get rid of original issue.

### Expected behavior

Program runs and asks for reddit app details as is the first time run

### Screenshots

![image](https://user-images.githubusercontent.com/74203293/209834118-c0badc88-d7cf-42bf-a1a6-aad33b2bfd72.png)

### System Information

Operating System : Windows 11
Python version : Python 3.10.9
App version / Branch : latest I think

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

As stated above, to get rid of original issue, I reinstalled moviepy and it worked. As I thought the error may have been to do with the translators module I ran ```pip uninstall translators``` and then ```pip install translators`` but this did not fix the issue.

**Comment by Judono** [comment]
try to pip install moviepy

**Comment by JoelTech43** [comment]
![IMG_20221228_150009465.jpg](https://user-images.githubusercontent.com/74203293/209831381-cf77a2d8-e766-4457-9c70-b674c57d9f12.jpg)
Everything already seems to be satisfied  @Judono

**Comment by JoelTech43** [comment]
Hang on reinstalled it and now it works in IDLE shell

**Comment by JoelTech43** [comment]
New problem, see edited description
