### ISSUE TITLE
playwright doesnt work, what command

### ISSUE THREAD

**Issue by enragedsweat** [elebumm/RedditVideoMakerBot#141]
![image](https://user-images.githubusercontent.com/104448363/171631082-4567b8d0-3784-4de5-b735-e783ee2ebd09.png)

**Comment by hitesh3132** [comment]
Try this 
`playwright install` if not `python -m playwright install`

**Comment by baggot4** [comment]
> Try this `playwright install` if not `python -m playwright install`

when I try this I'm getting 
![image](https://user-images.githubusercontent.com/35886854/171741225-3a72788e-e63d-4fd9-bbf1-d446ace9a4c2.png)

**Comment by CallumIO** [comment]
Read the README.md
