### ISSUE TITLE
[Bug]: Breaks at screenshot, waiting for selector "[data-test-id="post-content"]"

### ISSUE THREAD

**Issue by tusharsadana** [elebumm/RedditVideoMakerBot#1412]
### Describe the bug

playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[data-test-id="post-content"]"
============================================================

this started coming up out of no where, just turned the nsfw tag to true in config.

### Reproduction Steps

config -> nsfw = true

### Expected behavior

Hoping to get screenshots for nsfw videos as well.

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by tusharsadana** [comment]
I need to understand the issue, and want to solve it if someone can explain the baseline issue

**Comment by Sakshyat442** [comment]
Am having the save problem, have you found the issue yet?

**Comment by tusharsadana** [comment]
> Am having the save problem, have you found the issue yet?

Still not, tbh I have not spent a lot of time here, was going to fetch the source code script (the reddit app being used) to debug, will update

**Comment by goosyboopy** [comment]
It works when you turn the nsfw option to false.

**Comment by Matsumotorise** [comment]
Looks like it's because the user needs to login to the browser, which isn't supported by the current code.
