### ISSUE TITLE
main.py doesn't run

### ISSUE THREAD

**Issue by noonelse** [elebumm/RedditVideoMakerBot#1416]
hey, I'm new to programming and this code really interested me. I went through the different first three steps and it was fine but when I finally wanted to run main.py I got this error code:

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "/Users/mmay/Desktop/RedditVideoMakerBot-master/reddit/subreddit.py", line 45
    match e.response.status_code:
          ^
SyntaxError: invalid syntax

I'm using anaconda on a Mac. 
would appreciate any help.

**Comment by Macster-py** [comment]
Hi noonelse,

Did you find a workaround? I'm new too and getting the same issue.

**Comment by Macster-py** [comment]
I think I found the issue. In your terminal, type: 

python -v

It's likely going to return that it's running anaconda python at 3.9 or less. The subreddit.py uses code that I believe only works in python 3.10 and above. I've been trying to figure out how to update the terminals python but haven't had any luck even after downloading python 3.11.1. 

I'm trying a factory reset of my MacBook to remove anaconda completely. Will update if it works after this.

**Comment by JasonLovesDoggo** [comment]
download 3.10+
