### ISSUE TITLE
pytube error

### ISSUE THREAD

**Issue by enragedsweat** [elebumm/RedditVideoMakerBot#142]
![image](https://user-images.githubusercontent.com/104448363/171633614-e31aa0ad-59bf-4011-8e8c-ef918d3c4d7f.png)

**Comment by MDAmirPathan** [comment]
Go to last error path in ur console **site-packages\pytube\cipher.py line Number 30 or 33** 
from `var_regex = re.compile(r"^\w+\W")` change to `var_regex = re.compile(r"^\$*\w+\W")`
hope That Solves Issue

**Comment by reoccurcat** [comment]
Fixed in latest commit, try cloning again
