### ISSUE TITLE
Exporting video Went from fast to slow 

### ISSUE THREAD

**Issue by realdav2** [elebumm/RedditVideoMakerBot#143]
As you can see at the begging it went really fast and it gets slower and slower 

![unknown](https://user-images.githubusercontent.com/106691949/171636287-e545bc96-d5a6-4fe3-b2fc-5467f466b4fb.png)

![unknown2](https://user-images.githubusercontent.com/106691949/171636303-c77b1453-6795-4185-b9ff-2f009fc0f9af.png)

**Comment by alexgarciiaa** [comment]
i have the same issue

**Comment by FreebieII** [comment]
Hi @realdav2,

# Do you have a stable internet connection?  Try re-pulling the latest version of the `master` branch and try again.

I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
