### ISSUE TITLE
[Bug]: 'ffmpeg' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Simboi08** [elebumm/RedditVideoMakerBot#1430]
### Describe the bug

'ffmpeg' is not recognized as an internal or external command,
operable program or batch file.

### Reproduction Steps

Literally a fresh install.

### Expected behavior

To actually recognize it as a command.

### System Information

Operating System : [Windows 11]
Python version : [e.g. Python 3.10.6]
App version / Branch : [Master]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by fin-github** [comment]
pip3 install ffmpeg or pip install ffmpeg. Also, Do Not Use VENV!!!
