### ISSUE TITLE
[Bug]: Requirement pip install error.

### ISSUE THREAD

**Issue by theharshitkumar** [elebumm/RedditVideoMakerBot#1431]
### Describe the bug

Since pytorch isnt available for python 3.11 on windows , the pip requirements gives error.

### Reproduction Steps

Install only python 3.11 on windows 
try to do pip requirement 

### Expected behavior

Pytorch gets installed automatically

### Screenshots

NA

### System Information

Operating System : Windows 10
Python version : Python 3.11
App version / Branch : latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by HelpmeBOTS** [comment]
just degrade to python 3.10

**Comment by OpenSourceSimon** [comment]
Use Python 3.10
