### ISSUE TITLE
[Bug]: raise IOError(("MoviePy error: the file %s could not be found!\n" OSError: MoviePy error: the file assets/temp/1048xks/mp3/2.mp3 could not be found! Please check that you entered the correct path.

### ISSUE THREAD

**Issue by Mayc99** [elebumm/RedditVideoMakerBot#1432]
### Describe the bug

Hi When I run python3 main.py, I occasionally get this error.

`error: the file assets/temp/1048xks/mp3/2.mp3 could not be found! Please check that you entered the correct path.`

It usually happens if I set the steps to a number like 8+, it usually works ok for the first 4 or so steps. 

Sometimes if I empty temp folder and run again it works.

Full error - 

```
Moviepy - Command successful
Background video chopped successfully!
╭──────────────────────────────────────────────────────────────────────────────╮
│ Creating the final video                                                   │
╰──────────────────────────────────────────────────────────────────────────────╯
╭──────────────────────────────────────────────────────────────────────────────╮
│                                                                              │
│             Sorry, something went wrong with this version! Try again, and    │
│ feel free to report this issue at GitHub or the Discord community.           │
│                                                                              │
│             Version: 3.0                                                     │
│                                                                              │
│             Story mode: False                                                │
│                                                                              │
│             Story mode method: 1                                             │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "/home/may/Downloads/RedditVideoMakerBot-master/main.py", line 117, in <module>
    raise err
  File "/home/may/Downloads/RedditVideoMakerBot-master/main.py", line 99, in <module>
    run_many(config["settings"]["times_to_run"])
  File "/home/may/Downloads/RedditVideoMakerBot-master/main.py", line 63, in run_many
    main()
  File "/home/may/Downloads/RedditVideoMakerBot-master/main.py", line 55, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "/home/may/Downloads/RedditVideoMakerBot-master/video_creation/final_video.py", line 116, in make_final_video
    audio_clips = [
  File "/home/may/Downloads/RedditVideoMakerBot-master/video_creation/final_video.py", line 117, in <listcomp>
    AudioFileClip(f"assets/temp/{reddit_id}/mp3/{i}.mp3")
  File "/home/may/.local/lib/python3.10/site-packages/moviepy/audio/io/AudioFileClip.py", line 70, in __init__
    self.reader = FFMPEG_AudioReader(filename, fps=fps, nbytes=nbytes,
  File "/home/may/.local/lib/python3.10/site-packages/moviepy/audio/io/readers.py", line 51, in __init__
    infos = ffmpeg_parse_infos(filename)
  File "/home/may/.local/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_reader.py", line 270, in ffmpeg_parse_infos
    raise IOError(("MoviePy error: the file %s could not be found!\n"
OSError: MoviePy error: the file assets/temp/1048xks/mp3/2.mp3 could not be found!
Please check that you entered the correct path.


```

### Reproduction Steps

Edited the config file and set steps from 1 to a high number, and run the main.py.

### Expected behavior

Error suggests script is looking for file but it didnt create the file. 
Expect that the file is created or the script should not look for it.

### Screenshots

![image](https://user-images.githubusercontent.com/88669349/211001029-784c3b70-4f99-4796-87f9-0464469ce4eb.png)

### System Information

Operating System : [Ubuntu]
Python version : [Python 3.10.7]
App version / Branch : [latest]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Mayc99** [comment]
Hi.

I believe this is an issue with certain Reddit posts. 

I ran the script just on 1 post and got the error, so not related to running several threads.

I tried to change the TTS settings but got similar errors relating to not being able to find mp3/2.mp3. All other mp3s were created in the folder except 2.mp3. 

Then I changed the comment setting, before I had a wide range, min length 8 and max length 1800, and was getting the error.  I reduced the range to like, min 12 and max 160. And the script ran without errors.

I am not sure if this means the issue is with taking too many comments, and too many characters? 
Or if there are certain comments which would cause the issue.

**Comment by dylannalex** [comment]
Having the same issue here. Could you solve it?

**Comment by JasonLovesDoggo** [comment]
> Having the same issue here. Could you solve it?

Which version.

**Comment by dylannalex** [comment]
I'm running Python 3.10.10 and RedditVideoMakerBot 3.0.1. I made a [comment](https://github.com/elebumm/RedditVideoMakerBot/issues/902#issuecomment-1435781898) on issue #902 explaining my issue with more details.

**Comment by dylannalex** [comment]
I partially fixed this by ignoring the audio clips that don't exist:

```python
  def make_final_video(
      number_of_clips: int,
      length: int,
      reddit_obj: dict,
      background_config: Tuple[str, str, str, Any],
  ):
        ...
        ...
        ...
        # audio_clips = [
        #     AudioFileClip(f"assets/temp/{reddit_id}/mp3/{i}.mp3")
        #     for i in range(number_of_clips)
        # ]
        invalid_audio_clip_ids = []
        audio_clips = []
        for i in range(number_of_clips):
            try:
                audio_clips.append(AudioFileClip(f"assets/temp/{reddit_id}/mp3/{i}.mp3"))
            except OSError:
                invalid_audio_clip_ids.append(i)
```
I also had to add some lines of code on `final_video.py` to make this work. 

If needed, I can make a PR to help people facing this issue, although ignoring the comments whose audio clips could not be created might not be the best solution.
