### ISSUE TITLE
[Bug]: Screenshot quality quite poor in landscape mode (1920x1080).

### ISSUE THREAD

**Issue by flying-triangulum** [elebumm/RedditVideoMakerBot#1436]
### Describe the bug

Compared to standard vertical mode (1080x1920), the screenshots in landscape mode have a grainy look.

### Reproduction Steps

Complete execution without errors on the following settings:

[settings]
allow_nsfw = false
theme = "dark"
times_to_run = 1
opacity = 0.9
transition = 0.2
storymode = true
storymodemethod = 1
storymode_max_length = 10000
fps = 60
resolution_w = 1920
resolution_h = 1080

### Expected behavior

Screenshots in landscape mode should be as clear as in vertical mode.

### Screenshots

![Screenshot (5740)](https://user-images.githubusercontent.com/67757309/211168114-e474815e-21a8-46fb-98a7-86ade813b41b.png)

### System Information

Operating System : Windows 10
Python version : Python 3.10.4
App version / Branch : 3.0

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
Thanks for reporting this! I'll make the resolution higher for the images

**Comment by OpenSourceSimon** [comment]
Fixed in V3.1
