### ISSUE TITLE
[Bug]: After starting main.py I got an error when the program was saving the TTS files.

### ISSUE THREAD

**Issue by DyeMeBlack** [elebumm/RedditVideoMakerBot#1437]
### Describe the bug

after entering all I got an error. The error was even when I changed the settings multiple times.

### Reproduction Steps

Settings:
[ai]
ai_similarity_enabled = false
ai_similarity_keywords = ""

[settings]
allow_nsfw = false
theme = "dark"
times_to_run = 1
opacity = 0.9
transition = 0.2
storymode = false
storymodemethod = 1
storymode_max_length = 1000
fps = 30
resolution_w = 1080
resolution_h = 1920

[settings.background]
background_choice = "minecraft"
background_thumbnail = false
background_thumbnail_font_family = "arial"
background_thumbnail_font_size = 96
background_thumbnail_font_color = "255,255,255"

[settings.tts]
voice_choice = "tiktok"
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_002"
tiktok_sessionid = ""
python_voice = "1"
py_voice_num = "2"
silence_duration = 0.3
no_emojis = true

[reddit.creds]
client_id = "AfUs8QnY6ViELN_hFcwHDA"
client_secret = "fiAbvuGrd7_9l85Frr_rqpTVfKP9sg"
username = "Solid_Preparation772"
password = "creatinggames4ever"
2fa = false

[reddit.thread]
random = false
subreddit = "stocks"
post_id = ""
max_comment_length = 500
min_comment_length = 1
post_lang = ""
min_comments = 20

### Expected behavior

I wanted to get the Video out of that settings.

### Screenshots

![image](https://user-images.githubusercontent.com/122224450/211217337-eabb0c7b-7d9e-48b9-bd41-04323c405dca.png)

### System Information

Operating System : Windows 10
Python version : Python 3.10.9
App version / Branch : version (3.0)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

I had a problem with getting all the librarys with pip on Windows, because of that I used the Windows Subsystem for Linux and installed it with bash and that worked very well.

**Comment by Subset28** [comment]
I have the same problem as well. LMK if you figure out how to fix it. I am working on it as well. I think it is related to the TikTok session ID and getting the TTS.

**Comment by Frisch7** [comment]
I'm getting the same error

**Comment by AidenBedore212** [comment]
I have added the session ID for TikTok and am still getting the same error. I saw 4 different session IDs listed and I tried each one.

**Comment by jam41803** [comment]
I am also having this same problem. I tried toggling emojis and nsfw but it still says the same thing. I made a new account but it still showed the same error.

**Comment by OpenSourceSimon** [comment]
You need to fill in the sessionid for TikTok TTS. Check our documentation on how to obtain it

**Comment by jam41803** [comment]
> You need to fill in the sessionid for TikTok TTS. Check our documentation on how to obtain it

I have already filled in the sessionid, yet the same exception shows up.

**Comment by jam41803** [comment]
> > You need to fill in the sessionid for TikTok TTS. Check our documentation on how to obtain it
> 
> I have already filled in the sessionid, yet the same exception shows up.

Nevermind, it was a problem on my computer importing from the config. I can do that myself.
