### ISSUE TITLE
[Bug]: watermark kills speed

### ISSUE THREAD

**Issue by RichardErkhov** [elebumm/RedditVideoMakerBot#1440]
### Describe the bug

watermark (line 260 in final_video.py) kills speed of video creation. When creating video with watermark, Im getting around 3 it/s, which is extremely slow, knowing I have i7 10700k and 64gb ram (I think it's pretty good enough for creating the video, isn't it?). When removing the watermark addition, performance increases to 20 it/s, which is kinda slow, but much better than 3. Any solution for this?

### Reproduction Steps

just run the code from the repository with the lines mentioned about and without.

### Expected behavior

high speed of rendering, at least 20 it/s, maybe be higher, will investigate later, as perfomance of moviepy should be higher based on my previous experience =)

### System Information

Operating System : Windows 10 64bit
Python version : 3.10
App version / Branch : latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
We are aware of the major slow down in performance. Unfortunately we couldn't find a better way of implementing a watermark. Feel free to make a pull request if you have a better way
