### ISSUE TITLE
[Bug]: Code: 1, reason: probably the aid value isn't correct, message: Couldn't load speech. Try again

### ISSUE THREAD

**Issue by Avistin** [elebumm/RedditVideoMakerBot#1442]
### Describe the bug

Please help! └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "C:\RedditVideoMakerBot-master\main.py", line 117, in <module>
    raise err
  File "C:\RedditVideoMakerBot-master\main.py", line 99, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\RedditVideoMakerBot-master\main.py", line 63, in run_many
    main()
  File "C:\RedditVideoMakerBot-master\main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\RedditVideoMakerBot-master\video_creation\voices.py", line 51, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 59, in run
    self.call_tts("title", process_text(self.reddit_object["thread_title"]))
  File "C:\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 138, in call_tts
    self.tts_module.run(text, filepath=f"{self.path}/{filename}.mp3")
  File "C:\RedditVideoMakerBot-master\TTS\TikTok.py", line 108, in run
    raise TikTokTTSException(status_code, data["message"])
TTS.TikTok.TikTokTTSException: Code: 1, reason: probably the aid value isn't correct, message: Couldn't load speech. Try again.

### Reproduction Steps

Correctly installed

### Expected behavior

normal operation

### Screenshots

![Screenshot_3](https://user-images.githubusercontent.com/119350247/211617822-0afd5e11-4b2d-46c5-a40f-b909a9df7d1d.png)

### System Information

Windows 10
python 3.10.9

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Voyinno** [comment]
I have the same problem.
I am on a fresh install of Ubuntu 22.04. I have just installed all the dependencies.
I am using Python 3.10.6

**Comment by rowanwinch** [comment]
Same issue here using Windows 11 in VS Code

**Comment by OwElko** [comment]
Same issue , did any one found a workaround ?

**Comment by OpenSourceSimon** [comment]
You need to fill in the sessionid for TikTok TTS. Check our documentation on how to obtain it

**Comment by OwElko** [comment]
i found another workaround , it's easier to change the voice _choice to any other option than  tiktok 

Valid options are: streamlabspolly, tiktok, googletranslate, awspolly, pyttsx.

**Comment by OpenSourceSimon** [comment]
> i found another workaround , it's easier to change the voice _choice to any other option than  tiktok 
> 
> Valid options are: streamlabspolly, tiktok, googletranslate, awspolly, pyttsx.

Yeah that's true, that doesn't need a TikTok sessionid of course. But in my opinion the TikTok TTS sounds the best

**Comment by Avistin** [comment]
Thanks to everyone who helped me! Now everything works for me
