### ISSUE TITLE
[Bug]: problem that i cant understand

### ISSUE THREAD

**Issue by websitedsign** [elebumm/RedditVideoMakerBot#1445]
### Describe the bug

Heres the code:

Translating Text...
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                     │
│             Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub  │
│ or the Discord community.                                                                                           │
│                                                                                                                     │
│             Version: 3.0                                                                                            │
│                                                                                                                     │
│             Story mode: False                                                                                       │
│                                                                                                                     │
│             Story mode method: 1                                                                                    │
│                                                                                                                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "C:\Users\black swan\Desktop\bots\viewbot\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 117, in <module>
    raise err
  File "C:\Users\black swan\Desktop\bots\viewbot\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 99, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\black swan\Desktop\bots\viewbot\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 63, in run_many
    main()
  File "C:\Users\black swan\Desktop\bots\viewbot\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\black swan\Desktop\bots\viewbot\RedditVideoMakerBot-master\RedditVideoMakerBot-master\video_creation\voices.py", line 51, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\black swan\Desktop\bots\viewbot\RedditVideoMakerBot-master\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 59, in run
    self.call_tts("title", process_text(self.reddit_object["thread_title"]))
  File "C:\Users\black swan\Desktop\bots\viewbot\RedditVideoMakerBot-master\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 138, in call_tts
    self.tts_module.run(text, filepath=f"{self.path}/{filename}.mp3")
  File "C:\Users\black swan\Desktop\bots\viewbot\RedditVideoMakerBot-master\RedditVideoMakerBot-master\TTS\TikTok.py", line 108, in run
    raise TikTokTTSException(status_code, data["message"])
TTS.TikTok.TikTokTTSException: Code: 1, reason: probably the aid value isn't correct, message: Couldn't load speech. Try again.

WHAT TO DOOO???

### Reproduction Steps

I just run the code

### Expected behavior

I expected the app to run and create the video

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by zaidbsousa** [comment]
same problem

**Comment by Yaroslav4232** [comment]
Bro, I'm sorry if something is inappropriate, I'm writing through a translator. I seem to have found a solution to the problem. You need to insert the tiktok_sessionid value in the config.toml file. It can be obtained by going to your **tiktok** profile, clicking on the lock and opening cookies files

**Comment by duckduckstab1** [comment]
You are using 3.6. 3.10 is required

**Comment by OpenSourceSimon** [comment]
> Bro, I'm sorry if something is inappropriate, I'm writing through a translator. I seem to have found a solution to the problem. You need to insert the tiktok_sessionid value in the config.toml file. It can be obtained by going to your **tiktok** profile, clicking on the lock and opening cookies files

That is correct! You need a sessionid for the TikTok TTS. Check our documentation for more explanation
