### ISSUE TITLE
[Bug]: Error: Could not find a version that satisfies the requirement playwright

### ISSUE THREAD

**Issue by Snej-Corleone** [elebumm/RedditVideoMakerBot#1446]
### Describe the bug

When I try to install the script on my raspberrypi, I get the following error after `pip install -r requirements.txt`:

```
ERROR: Could not find a version that satisfies the requirement playwright==1.23.0
ERROR: No matching distribution found for playwright==1.23.0
```

### Reproduction Steps

running `pip install -r requirements.txt:` on a raspberrypi

### Expected behavior

I just wanted to install the bot on my raspi.

### System Information

Operating System : 
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"

Python version : Python 3.9.2
App version / Branch :  latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by websitedsign** [comment]
Pip install playwright

**Comment by OpenSourceSimon** [comment]
Playwright can't be used on a raspberry pi, so this script doesn't work on that
