### ISSUE TITLE
[Bug]: Error while running main.py [Version - 2.4.2]

### ISSUE THREAD

**Issue by DarkDravenPOG** [elebumm/RedditVideoMakerBot#1448]
### Describe the bug

So i did everything correctly and installed all the requirements but when i run the python main.py command it gives the KeyError 'data' i checked everything and before that it sends different commands of errors in TTS files pls hep me i tried everything u have mentioned in ur github page and the readme.md in ur code. im also leaving a screenshot for you.

### Reproduction Steps

i downloaded all the requirements as stated in the readme.md file ran python main.py it asked me client id secret and some other stuff i filled it correctly and now when i use python main.py it just gives me the KeyError: 'data'

### Expected behavior

i expected it to download a video from youtube use the subreddit to get some threads and compile them to make me videos but that did not happen

### Screenshots

![image](https://user-images.githubusercontent.com/99127967/212461606-7c8000c9-8833-4d6a-9c3a-4874d565ff92.png)

### System Information

Operating System : Windows 10
Python version : Python 3.10
App version / Branch : 2.4.2

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
Update to version 3.0
