### ISSUE TITLE
Change video name to Thread Title

### ISSUE THREAD

**Issue by Governnment** [elebumm/RedditVideoMakerBot#145]
I tried to change 17 line in final_video.py 

from this 
`def make_final_video(number_of_clips):`

to this
`def make_final_video(reddit_object, number_of_clips):`

and then 59th line changed to this
` final.write_videofile(text=reddit_object["thread_title"], fps=30, audio_codec="aac", audio_bitrate="192k"`

I'm still getting the error 

`  File "main.py", line 22, in <module>
    final_video = make_final_video(number_of_comments)
TypeError: make_final_video() missing 1 required positional argument: 'number_of_clips'`

**Comment by reoccurcat** [comment]
I wrote up a patch for what you are trying to do, which I assume is make the final video's name the Reddit thread title.
You can try it out here: https://github.com/reoccurcat/RedditVideoMakerBot/tree/final_video_name_test

**Comment by Kamushy** [comment]
My patch #139 names the file after the reddit thread title if that's what you want

**Comment by FreebieII** [comment]
Hi @Governnment 

I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
