### ISSUE TITLE
[Bug]:  Something goes wrong while downloading screen shots (streamlabs tts) #1455 

### ISSUE THREAD

**Issue by Vexantt** [elebumm/RedditVideoMakerBot#1455]
### Describe the bug

Keep on getting this issue when running the program with StreamLabsPolly TTS. Tiktok TTS doesn't work in my country. Also i have tried using AWS Polly TTS but despite proper installation as per Amazon instructions the program tells me that the AWS polly is not installed.

Help?

### Reproduction Steps

I did not do anything special, TTS is set to Stream Labs Polly which was working for me until 2.3, after which i upgraded to version 3. 

### Expected behavior

.

### Screenshots

![image](https://user-images.githubusercontent.com/123008241/213253015-dbe3625b-1e79-4f65-ac8e-35044a2a0830.png)

### System Information

Operating System : [Windows 11]
Python version : [Python 3.10]
App version / Branch : 3.0

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
Use a different post and try again
