### ISSUE TITLE
StoryMode is not working [Bug]: 

### ISSUE THREAD

**Issue by SwitchAC** [elebumm/RedditVideoMakerBot#1456]
### Describe the bug

If you enable story mode after downloading the background video the program crashes as you have story mode enabled

### Reproduction Steps

enable story mode with method 1

### Expected behavior

program crashes

### Screenshots

![image](https://user-images.githubusercontent.com/90303722/213324694-d57f9acc-4249-4eab-bc21-7475c60b8f1a.png)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Yaroslav4232** [comment]
Same problem

**Comment by OpenSourceSimon** [comment]
Bug noted, easy fix for now is to use the Minecraft background
