### ISSUE TITLE
[Bug]: Invalid credentials although my credentials are 100% correct.

### ISSUE THREAD

**Issue by RadioactivePotato** [elebumm/RedditVideoMakerBot#1460]
### Describe the bug

Invalid credentials although my credentials are 100% correct. (Checked multiple times)

### Reproduction Steps

Run main.py with credentials

### Expected behavior

Invalid credentials

### Screenshots

![image](https://user-images.githubusercontent.com/75719839/213791314-46532fea-d88c-479f-8141-c3c875b4c145.png)

### System Information

Python version : [Python 3.10.4]
App version : [V3.0]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by JasonLovesDoggo** [comment]
guess what.......

they aren't.... or you messed up your client. 


not a bug.
