### ISSUE TITLE
[Feature]: Use public JSON API instead of authenticating

### ISSUE THREAD

**Issue by ogohogo** [elebumm/RedditVideoMakerBot#1462]
### Summary

Reddit has public JSON API which doesn't require authentication. That could be easily used instead of the current authentication method.

### Is your feature request related to a problem?

no

### Describe the solution you'd like

Reddit offers public JSON API access if you append `.json` at the end of URL (eg. `https://www.reddit.com/r/AskReddit/comments/10edbpl/whats_something_an_elementary_school_teacher_told/.json)`. I think it could be easily used as a replacement for current method since it doesn't require any app creation / authentication and so on (better cause you don't have to store your credentials anywhere)

**Comment by OpenSourceSimon** [comment]
The browser for the screenshots need the credentials so this is useless
