### ISSUE TITLE
[Bug]: ffmped_parse_infos

### ISSUE THREAD

**Issue by aryamanchadha** [elebumm/RedditVideoMakerBot#1466]
### Describe the bug

While running the bot after configuration, I get the following error : 

![image](https://user-images.githubusercontent.com/79290729/215008235-1454f65d-7de4-48ac-8785-d5baacfb2c6d.png)

### Reproduction Steps

I followed the setup steps and configured the app to work with tiktok tts and then changed that to streamlabspoly as i was getting an error with the tiktok tts. Once I did that the bot ran smoothly till it was time to create the final video where it exit out and the error said list index out of range. Times to run was set as 2.

### Expected behavior

Expected the final video to be created. 

### Screenshots

![image](https://user-images.githubusercontent.com/79290729/215008451-887db8e5-f092-4d57-8364-f589debe63c7.png)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
It means something went wrong with generating the TTS files. Try a different post
