### ISSUE TITLE
[Bug]: Thumbnail error

### ISSUE THREAD

**Issue by hghfs111** [elebumm/RedditVideoMakerBot#1468]
### Describe the bug

Whenever i turn thumbnails on i just get this error and no thumbnails 
![image](https://user-images.githubusercontent.com/80606070/215267163-3952c39b-3526-4fb3-b706-e89616f4d940.png)

### Reproduction Steps

Turned on the background_thumbnail
![image](https://user-images.githubusercontent.com/80606070/215267201-6c5a74e2-4da4-4014-8a10-91014964f802.png)

### Expected behavior

for it to work

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.9]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by hghfs111** [comment]
any help please ?

**Comment by OpenSourceSimon** [comment]
Thumbnails is a different thing than background video so don't worry
