### ISSUE TITLE
could not find match for ^\w+\W

### ISSUE THREAD

**Issue by rgfdfdg** [elebumm/RedditVideoMakerBot#147]
![image](https://user-images.githubusercontent.com/46347153/171647895-53e5974a-2785-4299-9d96-0c218f2f54db.png)

**Comment by MDAmirPathan** [comment]
Go to last error path in ur console **site-packages\pytube\cipher.py line Number 30 or 33** 
from `var_regex = re.compile(r"^\w+\W")` change to `var_regex = re.compile(r"^\$*\w+\W")`
hope That Solves Issue

**Comment by MDAmirPathan** [comment]
Go to last error path in ur console **site-packages\pytube\cipher.py line Number 30 or 33** 
from `var_regex = re.compile(r"^\w+\W")` change to `var_regex = re.compile(r"^\$*\w+\W")`
hope That Solves Issue

**Comment by rgfdfdg** [comment]
> Go to last error path in ur console **site-packages\pytube\cipher.py line Number 30 or 33** from `var_regex = re.compile(r"^\w+\W")` change to `var_regex = re.compile(r"^\$*\w+\W")` hope That Solves Issue

Thanks!
