### ISSUE TITLE
[Bug]: File "/Users/riddhishsaravanan/githubtesting/RedditVideoMakerBot/main.py", line 9, in <module>     from prawcore import ResponseException ModuleNotFoundError: No module named 'prawcore'

### ISSUE THREAD

**Issue by RiddSarav** [elebumm/RedditVideoMakerBot#1471]
### Describe the bug

I keep getting the issue, "File "/Users/riddhishsaravanan/githubtesting/RedditVideoMakerBot/main.py", line 9, in <module>
    from prawcore import ResponseException
ModuleNotFoundError: No module named 'prawcore'" 

Despite the fact that I already install requirements.txt and prawcore itself but it still does not work.

Any help?

### Reproduction Steps

python3.10 main.py

### Expected behavior

the code to work

### System Information

Operating System : [e.g. Mac BigSur]
Python version : [e.g. Python 3.10.9]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by hghfs111** [comment]
happened to me i uninstalled python installed version 3.90.0 and it worked

**Comment by OpenSourceSimon** [comment]
Remove all Python versions and only install Python 3.10, then try again
