### ISSUE TITLE
reddit script setup

### ISSUE THREAD

**Issue by aklidevlop** [elebumm/RedditVideoMakerBot#148]
how to edit the .env file

**Comment by MDAmirPathan** [comment]
You Can Open it In notepad and Edit it (Windows Os)

**Comment by aklidevlop** [comment]
how to get the reddit app information

**Comment by FreebieII** [comment]
> how to get the reddit app information

Hi @aklidevlop ,

You get this from https://www.reddit.com/prefs/apps

I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
