### ISSUE TITLE
Client-ID Issue when opening main.py

### ISSUE THREAD

**Issue by artpawz** [elebumm/RedditVideoMakerBot#149]
![afbeelding_2022-06-02_162326394](https://user-images.githubusercontent.com/106756561/171651698-65cc13ae-7f7a-4a89-855e-838125c84fdd.png)

when i run the main.py file i get this error saying that the client_id setting is missing, but i am 100% sure that i filled in the details correctly in the ev file, any help with this?

**Comment by MDAmirPathan** [comment]
I Got Same Issue But After Filling correct Details In the **.env** file it was Solved, I Hope You get out of this

**Comment by artpawz** [comment]
> I Got Same Issue But After Filling correct Details In the **.env** file it was Solved, I Hope You get out of this

glad to see you got it to work, unfortunately i have double checked every part, and none of the details in the ,env files are incorrect. so i dont know how to fix it

**Comment by artpawz** [comment]
i have found a solution, turns out i didnt rename the template file properly

**Comment by MDAmirPathan** [comment]
Nice!
