### ISSUE TITLE
[Bug]: main.py closes when trying to use the bot

### ISSUE THREAD

**Issue by mattheolaroche** [elebumm/RedditVideoMakerBot#1493]
### Describe the bug

I've put all my settings during the first configuration of the program, but when running main.py again, the window closes by itself without completing the video.

### Reproduction Steps

- configure in the first opening of main.py
- main.py closes
- open main.py again
- main.py closes itself again

### Expected behavior

main.py is supposed to run normally and generate the video

### Screenshots

![Capture d’écran 2023-02-21 110043](https://user-images.githubusercontent.com/89638650/220313571-d939796b-4ad5-4383-8e3e-f2bfcdde5deb.png)

### System Information

Operating System : Windows 11
Python version : [e.g. Python 3.10.6]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by kimdaa** [comment]
same problem here

**Comment by MauroLambrecht** [comment]
adding your tiktok_sessionid to config.toml fixes this error for me sadly i get this error next: TTS.TikTok.TikTokTTSException: Code: 1, reason: probably the aid value isn't correct, message: Text-to-speech isn't supported for this language

**Comment by Syntexqt** [comment]
It has something to do with the TikTok voice. I fixed this error by choosing a different voice (streamlabspolly). Try this it should work.
