### ISSUE TITLE
[Feature]: Speeding up videos.

### ISSUE THREAD

**Issue by yeetus1992** [elebumm/RedditVideoMakerBot#1496]
### Summary

being able to set video speed (e.g. x1.5)

### Is your feature request related to a problem?

Is there already a way to speed up videos? If not, that'd be cool.

### Describe the solution you'd like

Being able to change the speed (not necessarily pitch)

**Comment by rajniszp** [comment]
What do you mean by speeding up the video? You mean the background video, the TTS voiceover, or both?
