### ISSUE TITLE
[Feature]: Skipping posts with a description

### ISSUE THREAD

**Issue by yeetus1992** [elebumm/RedditVideoMakerBot#1497]
[###] Summary

The possibility to skip posts that have a description.

### Is your feature request related to a problem?

AmITheAsshole is quite an interesting subreddit, the problem being that a lot of the times these posts (the questions) have long descriptions, but the engine only reads the title. But without the description, the answers dont make sense.

<img width="1728" alt="Screenshot 2023-02-23 at 11 50 56" src="https://user-images.githubusercontent.com/125825188/220886398-7b87f182-fc4e-44ea-9a77-25e3276db714.png">
Is there a way to either read the description too with the title (and then e.g. add "max-post-lentgh-option") or only use posts that have no description at all?

### Describe the solution you'd like

A way to either read the description too with the title (and then e.g. add "max-post-lentgh-option") or only use posts that have no description

**Comment by cloudisity** [comment]
The solution is to set Storymode in the Config to 'true'
