### ISSUE TITLE
[Feature]: Add background music

### ISSUE THREAD

**Issue by yeetus1992** [elebumm/RedditVideoMakerBot#1499]
### Summary

Being able to add an audio file of background music

### Is your feature request related to a problem?

No background music

### Describe the solution you'd like

Being able to add background music; if seen issues on this but none of them still seem active/were solved. Would it be possible?

**Comment by liamb13** [comment]
It seems this was started being worked on:
https://github.com/elebumm/RedditVideoMakerBot/blob/4c01a1d83fd5995073f811e3d33b9bd8adc5101e/video_creation/final_video.py#L252-L258

**Comment by propilideno** [comment]
I forked this repo few hours ago and added this improvement. I'll try a pull request now.

**Comment by liamb13** [comment]
@OpenSourceSimon we can close this one now
