### ISSUE TITLE
[Feature]: please make it to read the text from a file and save to the audio

### ISSUE THREAD

**Issue by mallik30** [elebumm/RedditVideoMakerBot#1502]
### Summary

please make it to read the text from a file and save to the audio

### Is your feature request related to a problem?

it helps to automate text-to-speech from a file with only audio and random video option

### Describe the solution you'd like

Implement a separate flow that takes data from the file and saves as audio file and an optional random video

**Comment by OpenSourceSimon** [comment]
You can take the MP3 files from the temp folder
