### ISSUE TITLE
[Bug]: Issue when running Main.py first time 

### ISSUE THREAD

**Issue by berrodagua** [elebumm/RedditVideoMakerBot#1506]
### Describe the bug

Apologies if this isnt the right forum for this type of question. But i've been running into a wall that i can't figure out.

When trying to run Main.py for the first for configuration, i dont get the expected results. Installation of requirements sems to have been finalized without any issues.

### Reproduction Steps

python3 main.py

### Expected behavior

Traceback (most recent call last):
  File "/Users/aserpa/Desktop/BeesWax/Reddit/RedditVideoMakerBot-master/main.py", line 11, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "/Users/aserpa/Desktop/BeesWax/Reddit/RedditVideoMakerBot-master/reddit/subreddit.py", line 11, in <module>
    from utils.subreddit import get_subreddit_undone
  File "/Users/aserpa/Desktop/BeesWax/Reddit/RedditVideoMakerBot-master/utils/subreddit.py", line 6, in <module>
    from utils.ai_methods import sort_by_similarity
  File "/Users/aserpa/Desktop/BeesWax/Reddit/RedditVideoMakerBot-master/utils/ai_methods.py", line 3, in <module>
    import torch
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/__init__.py", line 202, in <module>
    from torch._C import *  # noqa: F403
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/_C.cpython-310-darwin.so, 2): Library not loaded: @loader_path/../.dylibs/libomp.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib
  Reason: no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/lib/../.dylibs/libomp.dylib: cannot load 'libomp.dylib' (load command 0x80000034 is unknown)
	/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/lib/../.dylibs/libomp.dylib: cannot load 'libomp.dylib' (load command 0x80000034 is unknown)

### System Information

Operating System : iOs
Python version : Python 3.10

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by quandaledingleofficial** [comment]
Same issue here.

**Comment by niorzgaming** [comment]
Help please

**Comment by berrodagua** [comment]
Up to avoid stale

**Comment by quandaledingleofficial** [comment]
Up to avoid stale

**Comment by micziz** [comment]
How are you running on python on iOS. Some libraries may not work... i'don't know/don't think this project has full support for iOS.

**Comment by quandaledingleofficial** [comment]
i had the same problem on MacOS, I'm assuming this is what the user made.

**Comment by OpenSourceSimon** [comment]
Sorry but this is a problem with the module Torch, we can't do much about it. Try updating Torch with pip
