### ISSUE TITLE
[Feature]: Smart name shortening

### ISSUE THREAD

**Issue by BaGRoS** [elebumm/RedditVideoMakerBot#1508]
### Summary

Shortening the name with AI

### Is your feature request related to a problem?

Many times the names are too long, which causes an error, a shortening system is used, but it shortens without smartness. I have made another system, however, I do not know how to add it, so I give it as an idea. Even when shortening 

`filename = f"{name_normalize(title)[:251]}"`
in [video_creation](https://github.com/elebumm/RedditVideoMakerBot/tree/master/video_creation)/final_video.py
generated errors for me, because path and name was too long.

### Describe the solution you'd like

```
import openai


# Set up the OpenAI API client with your API key
openai.api_key = 'OPEN_AI_API_KEY'
COMPLETIONS_MODEL = "gpt-3.5-turbo"


def clean_filename(filename):
    not_permitted_chars = ["<", ">", ":", "\"", "/", "\\", "|", "?", "*"]
    for char in not_permitted_chars:
        filename = filename.replace(char, "")

    if "." in filename:
        filename, extension = filename.rsplit(".", 1)
        if extension in ["txt", "pdf", "doc", "docx", "ppt", "pptx", "xls", "xlsx"]:
            return filename
    return filename

def shorten_filename_with_gpt3(original_name):
    # Use OpenAI to generate a shorter name that captures the essence of the original name
    prompt = f"Create a new filename for the given file \"{original_name}\" that is both descriptive and concise. The new filename should be no more than 95 characters in length and should not include any special characters or file extensions. Instead, focus on capturing the essence of the original name in a creative and attention-grabbing way. Avoid using generic terms and instead opt for a name that is both meaningful and memorable. Be sure to strike a balance between being humorous and staying true to the original name. Let your creativity shine!"
    completions = openai.ChatCompletion.create(
        model=COMPLETIONS_MODEL,
        messages=[{"role": "user", "content": prompt}]
    )
    # Extract the shortened name from the OpenAI API response
    return completions["choices"][0]["message"]["content"].strip().strip('"')





    #oryginal shortening name from file final_video.py
    filename = f"{name_normalize(title)[:999]}" #IMPORTANT

#####################################################################################

    #BaGRoS change name
    if len(filename) > 99:
        filename = shorten_filename_with_gpt3(filename)
        print(filename, " ; ", len(filename))
        filename = clean_filename(filename)
```

### Additional Context

No error handling has been added when, for example, the OpenAI account runs out of funds, etc. That's the idea there.

Example:
Original: Klara a child with Down syndrome has alopecia which creates hair loss Look at her smile when she is fitted with a new wig Sweet 10 yr old Klara was the absolute highlight of my week She is so special so beautiful so brave so confident and has the sweetest personality (267) 
Shortened name by ChatGPT: **Brave Beauty Klara's Inspiring Wig Journey** (42)

With the original version shortening the name to 251 characters: "Klara a child with Down syndrome has alopecia which creates hair loss Look at her smile when she is fitted with a new wig Sweet 10 yr old Klara was the absolute highlight of my week She is so special so beautiful so brave so confident and has the swe"
shortening to 99 characters: "Klara a child with Down syndrome has alopecia which creates hair loss Look at her smile when she i"

judge which version of the name shortening is better

More examples:
Mobile users type Ive gathered you here today to and let the predictive text continue Why have you gathered us today (116) -> Gathering Mobile Users The Predictive Text Summit (49)

**Comment by BaGRoS** [comment]
More examples:

A teacher got stabbed by her student she later died of her wounds This is the ultimate gesture that her husband and her friends desired to gave to her (150) -> Final Tribute Teacher's Tragic End Inspires Ultimate Gesture by Loved Ones (74)

Seven-year-old Ellison has down syndrome and struggles with sensory overload His parents used to dread haircuts until they met Vernon Jackson a local barber This is how he cuts Ellisons hair (190) -> Barber's Unique Approach to Cutting Hair for Boy with Down Syndrome (67)

Whats the difference between Catwoman and BlackCat aside from the fact that shes from DC and the other is from Marvel (117) -> DC's Feline Fatale Versus Marvel's Midnight Menace - A Closer Look (66)

**Comment by OpenSourceSimon** [comment]
Maybe create a PR for this if you want credit?

**Comment by liamb13** [comment]
@BaGRoS - I've taken the code you supplied, tweaked slightly, and implemented in my PR as you haven't responded in sometime.

**Comment by BaGRoS** [comment]
> Maybe create a PR for this if you want credit?

I don't know how.

HeHe
