### ISSUE TITLE
[Feature]: Read out post body instead of comments

### ISSUE THREAD

**Issue by SohamGovande** [elebumm/RedditVideoMakerBot#1509]
### Summary

Add a feature to have the bot read out the post body instead of the comments

### Is your feature request related to a problem?

It becomes a lot easier to generate varying styles of content.

### Describe the solution you'd like

Add a flag in `config.toml` called `readOnlyPost`, which, when set to `true`, tells the reader to read the post body and not read the comments.

**Comment by OpenSourceSimon** [comment]
That's story mode
