### ISSUE TITLE
[Bug]: Error when attempting to made a video.

### ISSUE THREAD

**Issue by Hp173011** [elebumm/RedditVideoMakerBot#1515]
### Describe the bug

The bug gives me an error when finished the set up.

### Reproduction Steps

I had ran the setup like normal, at the very end I got this error.

### Expected behavior

I expected the video to be made - but this happend!

### Screenshots

![image](https://user-images.githubusercontent.com/56045690/224443949-bd3d24af-ae1a-448e-a300-bb01daa3665c.png)

Logging into Reddit.
Version 7.6.1 of praw is outdated. Version 7.7.0 was released Saturday February 25, 2023.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Getting subreddit threads...                                                                                        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Using subreddit: r/woosh from TOML config
This post was pinned by moderators. Skipping...
This post has under the specified minimum of comments (20). Skipping...
This post has under the specified minimum of comments (20). Skipping...
This post has under the specified minimum of comments (20). Skipping...
This post has under the specified minimum of comments (20). Skipping...
This post has under the specified minimum of comments (20). Skipping...
Video will be: 2 people missed the joke😭 👍
Thread url is : https://reddit.com/r/woosh/comments/11m1avx/2_people_missed_the_joke/ 👍
Thread has 183 upvotes
Thread has a upvote ratio of 79.0%
Thread has 65 comments
Received subreddit threads Successfully.
Thread ID is 11m1avx
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the       │
│ Discord community.                                                                                                  │
│ Version: 3.0.1,Story mode: False, Story mode method: 1,                                                             │
│ Postid : {'allow_nsfw': True, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'transition': 0.2, 'storymode':   │
│ False, 'storymodemethod': 1, 'storymode_max_length': 1000, 'fps': 30, 'resolution_w': 1080, 'resolution_h': 1920,   │
│ 'background': {'background_choice': 'minecraft', 'background_thumbnail': False, 'background_thumbnail_font_family': │
│ 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts':            │
│ {'voice_choice': 'tiktok', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice':       │
│ 'en_us_001', 'tiktok_sessionid': '', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3,             │
│ 'no_emojis': False}},allownsfw :True,is_nsfw : False                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "D:\Lukes Folder\RedditVideoMakerBot-3.0.1\main.py", line 115, in <module>
    raise err
  File "D:\Lukes Folder\RedditVideoMakerBot-3.0.1\main.py", line 99, in <module>
    run_many(config["settings"]["times_to_run"])
  File "D:\Lukes Folder\RedditVideoMakerBot-3.0.1\main.py", line 63, in run_many
    main()
  File "D:\Lukes Folder\RedditVideoMakerBot-3.0.1\main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "D:\Lukes Folder\RedditVideoMakerBot-3.0.1\video_creation\voices.py", line 37, in save_text_to_mp3
    text_to_mp3 = TTSEngine(
  File "D:\Lukes Folder\RedditVideoMakerBot-3.0.1\TTS\engine_wrapper.py", line 45, in __init__
    self.tts_module = tts_module()
  File "D:\Lukes Folder\RedditVideoMakerBot-3.0.1\TTS\TikTok.py", line 83, in __init__
    raise TikTokTTSException(5)
TypeError: TikTokTTSException.__init__() missing 1 required positional argument: 'message'

### System Information

Operating System : Windows 10
Python version : Python 3
App version / Branch : Latest 

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by BoyManWamen** [comment]
Instead of using the TikTok voice, you should use another voice like "googletranslate". Go to the path: ...\RedditVideoMakerBot\config.toml and change the value in "voice_choice" from TikTok to something else.

**Comment by Beastly-Kitty** [comment]
I have the same issue. Changing it to the Tiktok voice did not resolve it.

**Comment by OpenSourceSimon** [comment]
Fill in sessionid
