### ISSUE TITLE
[Bug]: Multiple Errors while running

### ISSUE THREAD

**Issue by Fitsbit** [elebumm/RedditVideoMakerBot#1516]
### Describe the bug

I don't have much programming experience, but I received multiple errors while running the application for the first time. I'm not sure if this was because I skipped and chose many of the default values or if it was because of another thing experience

### Reproduction Steps

I followed the installation instructions and set up everything. It wasn't until the program started to generate videos that I ran into errors. I changed the minimum settings, and the only thing I changed was to generate 5 videos per run.

### Expected behavior

I expected the program to run and generate five videos for me, then close.

### Screenshots

![image_2023-03-11_145552276](https://user-images.githubusercontent.com/107160828/224515064-5292fe5a-df44-48cb-bc4d-f87f4cf111d0.png)

### System Information

Operating System: Windows 10
Python version : Python 3.10
App version / Branch :  latest, 3.0.1

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

I have checked for duplicates but have not found any. If there was I do apologize.

**Comment by amaheshwari01** [comment]
same Error

**Comment by BoyManWamen** [comment]
Instead of using the TikTok voice, you should use another voice like "googletranslate". Go to the path: ...\RedditVideoMakerBot\config.toml and change the value in "voice_choice" from TikTok to something else.

**Comment by Fitsbit** [comment]
Whoever you are. Thank you. That's all. I have been trying for so long to get this to work. I'm not sure what the other voice names are, though. It seems there is more than just the googletranslate. But seriously, thank you.  What are the other names for the voices and the other backgrounds?

**Comment by BoyManWamen** [comment]
The other background choices are "minecraft", "gta", "rocket-league", "motor-gta", "csgo-surf", "cluster-truck", "minecraft-2","multiversus","fall-guys","steep", and "". The other voices are "streamlabspolly", "tiktok", "googletranslate", "awspolly", and "pyttsx".

**Comment by Fitsbit** [comment]
Thanks so much!

**Comment by Fitsbit** [comment]
I have the theme set to dark, but the video screenshots still come out white, is this a bug or Am I missing anything?
