### ISSUE TITLE
[Bug]:  Text too long to create speech audio

### ISSUE THREAD

**Issue by mrpoes** [elebumm/RedditVideoMakerBot#1518]
### Describe the bug

C:\Users\Noah\Downloads\RedditVideoMakerBot-3.0.1\RedditVideoMakerBot-3.0.1>%localappdata%\Programs\Python\Python310\python.exe main.py
Using Netherlands server backend.

██████╗ ███████╗██████╗ ██████╗ ██╗████████╗    ██╗   ██╗██╗██████╗ ███████╗ ██████╗     ███╗   ███╗ █████╗ ██╗  ██╗███████╗██████╗
██╔══██╗██╔════╝██╔══██╗██╔══██╗██║╚══██╔══╝    ██║   ██║██║██╔══██╗██╔════╝██╔═══██╗    ████╗ ████║██╔══██╗██║ ██╔╝██╔════╝██╔══██╗
██████╔╝█████╗  ██║  ██║██║  ██║██║   ██║       ██║   ██║██║██║  ██║█████╗  ██║   ██║    ██╔████╔██║███████║█████╔╝ █████╗  ██████╔╝
██╔══██╗██╔══╝  ██║  ██║██║  ██║██║   ██║       ╚██╗ ██╔╝██║██║  ██║██╔══╝  ██║   ██║    ██║╚██╔╝██║██╔══██║██╔═██╗ ██╔══╝  ██╔══██╗
██║  ██║███████╗██████╔╝██████╔╝██║   ██║        ╚████╔╝ ██║██████╔╝███████╗╚██████╔╝    ██║ ╚═╝ ██║██║  ██║██║  ██╗███████╗██║  ██║
╚═╝  ╚═╝╚══════╝╚═════╝ ╚═════╝ ╚═╝   ╚═╝         ╚═══╝  ╚═╝╚═════╝ ╚══════╝ ╚═════╝     ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

  Thanks for using this tool! Feel free to contribute to this project on GitHub! If you have any questions, feel free
     to reach out to me on Twitter or submit a GitHub issue. You can find solutions to many common problems in the
                              Documentation: https://reddit-video-maker-bot.netlify.app/

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ You are using the newest version (3.0.1) of the bot                                                                 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
###############################
#                             #
# Checking TOML configuration #
#                             #
###############################
If you see any prompts, that means that you have unset/incorrectly set variables, please input the correct values.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ on the 1st iteration of 1                                                                                           │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Logging into Reddit.
Version 7.6.1 of praw is outdated. Version 7.7.0 was released Saturday February 25, 2023.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Getting subreddit threads...                                                                                        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Using subreddit: r/AskReddit from TOML config
This post was pinned by moderators. Skipping...
Video will be: What did you swear in your childhood you would never do, but ended up doing anyways? 👍
Thread url is : https://reddit.com/r/AskReddit/comments/11ppkrs/what_did_you_swear_in_your_childhood_you_would/ 👍
Thread has 2466 upvotes
Thread has a upvote ratio of 96.0%
Thread has 2166 comments
Received subreddit threads Successfully.
Thread ID is 11ppkrs
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Saving Text to MP3 files...                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Saving... ----------------------------------------
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the       │
│ Discord community.                                                                                                  │
│ Version: 3.0.1,Story mode: False, Story mode method: 1,                                                             │
│ Postid : {'allow_nsfw': True, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.95, 'transition': 0.3, 'storymode':  │
│ False, 'storymodemethod': 1, 'storymode_max_length': 1000, 'fps': 30, 'resolution_w': 1080, 'resolution_h': 1920,   │
│ 'background': {'background_choice': 'minecraft', 'background_thumbnail': False, 'background_thumbnail_font_family': │
│ 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts':            │
│ {'voice_choice': 'tiktok', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice':       │
│ 'en_us_010', 'tiktok_sessionid': 'b59272817317026c3a8896fb1044039d', 'python_voice': '1', 'py_voice_num': '2',      │
│ 'silence_duration': 0.6, 'no_emojis': False}},allownsfw :True,is_nsfw : True                                        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "C:\Users\Noah\Downloads\RedditVideoMakerBot-3.0.1\RedditVideoMakerBot-3.0.1\main.py", line 115, in <module>
    raise err
  File "C:\Users\Noah\Downloads\RedditVideoMakerBot-3.0.1\RedditVideoMakerBot-3.0.1\main.py", line 99, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\Noah\Downloads\RedditVideoMakerBot-3.0.1\RedditVideoMakerBot-3.0.1\main.py", line 63, in run_many
    main()
  File "C:\Users\Noah\Downloads\RedditVideoMakerBot-3.0.1\RedditVideoMakerBot-3.0.1\main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\Noah\Downloads\RedditVideoMakerBot-3.0.1\RedditVideoMakerBot-3.0.1\video_creation\voices.py", line 51, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\Noah\Downloads\RedditVideoMakerBot-3.0.1\RedditVideoMakerBot-3.0.1\TTS\engine_wrapper.py", line 96, in run
    self.split_post(comment["comment_body"], idx)  # Split the comment
  File "C:\Users\Noah\Downloads\RedditVideoMakerBot-3.0.1\RedditVideoMakerBot-3.0.1\TTS\engine_wrapper.py", line 122, in split_post
    self.call_tts(f"{idx}-{idy}.part", newtext)
  File "C:\Users\Noah\Downloads\RedditVideoMakerBot-3.0.1\RedditVideoMakerBot-3.0.1\TTS\engine_wrapper.py", line 145, in call_tts
    self.tts_module.run(text, filepath=f"{self.path}/{filename}.mp3")
  File "C:\Users\Noah\Downloads\RedditVideoMakerBot-3.0.1\RedditVideoMakerBot-3.0.1\TTS\TikTok.py", line 110, in run
    raise TikTokTTSException(status_code, data["message"])
TTS.TikTok.TikTokTTSException: Code: 2, reason: the text is too long, message: Text too long to create speech audio

### Reproduction Steps

run main.py

### Expected behavior

Should've worked just fine

### System Information

Windows 10
Python 3.10.7

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Punchiee** [comment]
. so not stale

**Comment by vickx8** [comment]
Same bug here

**Comment by micziz** [comment]
As the error says, the comment was probably too long to be read by the tiktok ai. But i have no idea how to fix it.

**Comment by murissi** [comment]
I had the same error, so my storymode was false then i active that. Now it's on again.

**Comment by TheXe0N** [comment]
Decreasing the max_comment_length is a great way to solve this.
