### ISSUE TITLE
changing the overall language of the videos is not possible i guess ?

### ISSUE THREAD

**Issue by megerim** [elebumm/RedditVideoMakerBot#152]
Changing the AskReddit from English to a different language is not possible now, I guess?

**Comment by JasonLovesDoggo** [comment]
Definitely possible

**Comment by Matt10233** [comment]
Yes but how exactly ? > all you would have to do is change the tts lang and use google translate Reddit before taking the screenshots

**Comment by Matt10233** [comment]
> all you would have to do is change the tts lang and use google translate Reddit before taking the screenshots

Yes but how can we do that's exactly please ?

**Comment by JasonLovesDoggo** [comment]
Exactly? I'm not sure. 

But an idea I had was. 
(This would be slow but you could take the HTML text translate it via the Google translate API then replace it and then take the screenshot)

**Comment by FreebieII** [comment]
Hi @megerim,

I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
