### ISSUE TITLE
[Bug]: FileNotFoundError: [Errno 2] No such file or directory: './utils/backgrounds.json'

### ISSUE THREAD

**Issue by neelmaster101** [elebumm/RedditVideoMakerBot#1521]
### Describe the bug

I run it and it gives the error

### Reproduction Steps

run main .py

### Expected behavior

it works :/

### System Information

Operating System : Windows 11
Python version : Python 3.11.2
App version / Branch : latest

### Checklist

- [x] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.

**Comment by fin-github** [comment]
Pretty sure the issue is that you are using py11 and not py10 (3.10.x)

**Comment by neelmaster101** [comment]
ok ill try it thanks

> Pretty sure the issue is that you are using py11 and not py10 (3.10.x)

**Comment by fin-github** [comment]
install ffmpeg, also make sure you cleaned the remaining parts from the old py11
