### ISSUE TITLE
[Bug]: having issues with downloading background

### ISSUE THREAD

**Issue by DZ3G** [elebumm/RedditVideoMakerBot#1522]
### Describe the bug

Basically, whenever I run the AI, it works perfectly fine until the installation of the background section. At this point, it instantly gives an error similar to the one shown in the attached picture. I tried to download other backgrounds, originally attempting to download a Minecraft background, but after the error kept repeatedly showing up, I decided to change the background to GTA. However, the error persisted.

To try and fix the issue, I used Chat GPT-3 (free version) to identify the problem, and it suggested that there might be an issue with version 3.0.1 of the RedditVideoMakerBot script that I am attempting to run. The script is trying to download a video from YouTube to use as a background, but it is failing with an error related to the pytube library used for video downloads.

To resolve the issue, I could try the following steps:

Check if there is a newer version of the RedditVideoMakerBot script available that might have resolved the issue I am experiencing.
If a newer version is not available, try installing an older version of the pytube library that might be compatible with the version of the RedditVideoMakerBot script I am using.
If neither of these solutions works, I may need to report the issue to the developer of the RedditVideoMakerBot script or seek help from the community to find a solution.
Previously, before giving more information, Chat GPT-3 suggested that there might be a problem with pytube. I upgraded it, but that did not solve the issue. I also tried uninstalling and reinstalling it, but the problem persisted. Therefore, if anyone has experienced the same problem and has found a solution, please report it.

### Reproduction Steps

Here are the steps I tried to fix the issue:

I followed the installation steps provided in the RedditVideoMakerBot documentation.
I uninstalled Python 3.10 and reinstalled it, making sure to check the PATH.
I installed the pip requirements for RedditVideoMakerBot.
I installed and upgraded the pytube library using the command console.
I changed the video background I wanted to download.

### Expected behavior

the AI Run and download the background smoothly

### Screenshots

![Desktop Screenshot 2023 03 18 - 14 52 27 79](https://user-images.githubusercontent.com/113042463/226111647-db3f5bc5-9f8c-498a-afa9-27fc82304bb5.png)

### System Information

Operating System : [e.g. Windows 10]
Python version : [e.g. Python 3.10 64biy]
App version / Branch : [e.g. 3.01, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

here the GUI   

[ai]
ai_similarity_enabled = true
ai_similarity_keywords = "y"

[settings]
allow_nsfw = true
theme = "dark"
times_to_run = 5
opacity = 0.6
transition = 0.3
storymode = false
storymodemethod = 1
storymode_max_length = 1500
fps = 60
resolution_w = "1440"
resolution_h = 1920

[settings.background]
background_choice = "gta"
background_thumbnail = true
background_thumbnail_font_family = "arial"
background_thumbnail_font_size = 96
background_thumbnail_font_color = "255,255,255"

[settings.tts]
voice_choice = "googletranslate"
aws_polly_voice = "n"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_001"
tiktok_sessionid = "7f271e1498e4a01ca57cd83452ecbefa"
python_voice = "1"
py_voice_num = "5"
silence_duration = 0.2
no_emojis = true

[reddit.creds]
client_id = "uOwfpTq52l-ARQWpBW5REA"
client_secret = "7PwTrKtMFSq-gBXZ_qG_1IAJP1Lv2g"
username = "automated-bot-1"
password = "rafik2019"
2fa = false

[reddit.thread]
random = false
subreddit = "AskReddit+Redditdev"
post_id = "urdtfx"
max_comment_length = 400
min_comment_length = 1
post_lang = "en-US"
min_comments = 25

**Comment by Shaiq1217** [comment]
Facing the same issue. 
![image](https://user-images.githubusercontent.com/54815336/226145365-39f5f9a6-4392-4264-9013-6a53c5c21102.png)

**Comment by Shaiq1217** [comment]
Here's the fix : 
https://github.com/pytube/pytube/issues/1498#issuecomment-1472974770

**Comment by DZ3G** [comment]
thank you very much it did fix the downloading problem as i can now find it in the assets but now i have a new problem about ssl.SSLError but since the problem is fixed i closed this one and open a new one
