### ISSUE TITLE
[Bug]: ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2548)

### ISSUE THREAD

**Issue by DZ3G** [elebumm/RedditVideoMakerBot#1524]
### Describe the bug

having trouble during the last phase after downloading the background

### Reproduction Steps

run the program
changed somthing in cypher program in line 411 with " transform_plan_raw = js " then runed the the bot again

### Expected behavior

run perfectly fine

### Screenshots

![Desktop Screenshot 2023 03 19 - 22 09 04 76](https://user-images.githubusercontent.com/113042463/226209103-718fd016-abfc-428b-b402-13ea83dab277.png)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Sonder00111** [comment]
I've been having this same exact issue. People are saying to either Change the language, Change the tik tok voice to google translate or add tik tok session id. I've tried them all and the same issue keeps occurring lets hope it gets fixed soon.

**Comment by DZ3G** [comment]
ok
