### ISSUE TITLE
[Bug]: Failed to write to config.toml. giving up

### ISSUE THREAD

**Issue by thorhelson** [elebumm/RedditVideoMakerBot#1526]
### Describe the bug

When running main.py this happens
![image](https://user-images.githubusercontent.com/104784435/226472005-a880a3e8-0308-419d-8de0-99aaa3d2caee.png)

i have checked permissions and user has full permission

### Expected behavior

when i run it it should ask me to enter my reddit app info

### System Information

Operating System : [ Windows 10]
Python version : [Python 3.11]
App version / Branch : [v 3.0.1]

### Checklist

- [X] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.

**Comment by fin-github** [comment]
Try and follow what it says.

**Comment by OpenSourceSimon** [comment]
Move the folder to the downloads folder or somewhere else but not in the main folder
