### ISSUE TITLE
[Bug]: TypeError: 'NoneType' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by yamiyugi13** [elebumm/RedditVideoMakerBot#1528]
### Describe the bug

using the newest version
didnt create a video, instead gave me an error message
### Reproduction Steps

wanted to create a video

### Expected behavior

creating a video

### System Information

Operating System : windows 11
Python version : 3.9
App version / Branch : latest (coled the git today)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by movementall** [comment]
Same problem

**Comment by OpenSourceSimon** [comment]
Please provide the whole traceback

**Comment by lennonsoares** [comment]
![image](https://user-images.githubusercontent.com/66883863/235458733-7e1d9a4b-ac67-468e-92a0-498aaf75433a.png)

happened when I changed the "storymodemethod" to "0"
 

[settings]
allow_nsfw = true
theme = "dark"
times_to_run = 10
opacity = 0.9
transition = 0.2
storymode = true
storymodemethod = 0
storymode_max_length = 1000
resolution_w = 1080
resolution_h = 1920

**Comment by lennonsoares** [comment]
when the storymodemethod is "1" work

but in thist method the video dont show de screenshot of description post, only a screenshot of the title
