### ISSUE TITLE
No Final Video

### ISSUE THREAD

**Issue by Wizard3211** [elebumm/RedditVideoMakerBot#153]
I had everything working fine and the final video would appear in assets but now nothing. I had moved the files around but nothing else. Thanks, I am a noob at this.

![image](https://user-images.githubusercontent.com/106764231/171678777-3c546f57-97b8-4aa9-85dd-b2714ff8a307.png)

**Comment by JasonLovesDoggo** [comment]
Honestly the easiest advice I can give is just to re clone the repo

**Comment by Wizard3211** [comment]
I have re cloned and still the same thing :(

**Comment by JasonLovesDoggo** [comment]
same error?

**Comment by Wizard3211** [comment]
Ya same thing, just no final video being placed into assets

**Comment by JasonLovesDoggo** [comment]
I guess try my [fork](https://github.com/JasonLovesDoggo/RedditVideoMakerBot/) because i use a different system for saving but that's all I can do.

**Comment by Wizard3211** [comment]
> I guess try my [fork](https://github.com/JasonLovesDoggo/RedditVideoMakerBot/) because i use a different system for saving but that's all I can do.
Cloned your fork
I downloaded "Sox" Still no module named sox, I have no clue what to do with that one

**Comment by Wizard3211** [comment]
Still nothing, anyone know of anything else I can try?

**Comment by Wizard3211** [comment]
I have tried on both PyCharm and VSC and no final_video.mp4
I dont even want the videos anymore I just want to know why its not working, thanks

**Comment by JasonLovesDoggo** [comment]
Well some stuff has changed so can you try it again on the developer branch if you still care?
