### ISSUE TITLE
[Bug]: I can't run the script.

### ISSUE THREAD

**Issue by SpamixOfficial** [elebumm/RedditVideoMakerBot#1530]
### Describe the bug

The bug appears when the script is ran, to be precise, it appears after the Thread ID has been fetched.

### Reproduction Steps

Just run the script using the latest ubuntu release.

### Expected behavior

What I expect to happen is for the script to crash, and print this error message:

╭──────────────────────────────────────────────────────────────────────────────╮
│ Sorry, something went wrong with this version! Try again, and feel free to   │
│ report this issue at GitHub or the Discord community.                        │
│ Version: 3.0.1,Story mode: False, Story mode method: 1,                      │
│ Postid : {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1,           │
│ 'opacity': 0.9, 'transition': 0.2, 'storymode': False, 'storymodemethod': 1, │
│ 'storymode_max_length': 1000, 'fps': 30, 'resolution_w': 1080,               │
│ 'resolution_h': 1920, 'background': {'background_choice': '',                │
│ 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',  │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color':     │
│ '255,255,255'}, 'tts': {'voice_choice': 'tiktok', 'aws_polly_voice':         │
│ 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', │
│ 'tiktok_sessionid': '', 'python_voice': '1', 'py_voice_num': '2',            │
│ 'silence_duration': 0.3, 'no_emojis': False}},allownsfw :False,is_nsfw :     │
│ False                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "/home/ubuntu/RedditVideoMakerBot-3.0.1/main.py", line 115, in <module>
    raise err
  File "/home/ubuntu/RedditVideoMakerBot-3.0.1/main.py", line 99, in <module>
    run_many(config["settings"]["times_to_run"])
  File "/home/ubuntu/RedditVideoMakerBot-3.0.1/main.py", line 63, in run_many
    main()
  File "/home/ubuntu/RedditVideoMakerBot-3.0.1/main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "/home/ubuntu/RedditVideoMakerBot-3.0.1/video_creation/voices.py", line 37, in save_text_to_mp3
    text_to_mp3 = TTSEngine(
  File "/home/ubuntu/RedditVideoMakerBot-3.0.1/TTS/engine_wrapper.py", line 45, in __init__
    self.tts_module = tts_module()
  File "/home/ubuntu/RedditVideoMakerBot-3.0.1/TTS/TikTok.py", line 83, in __init__
    raise TikTokTTSException(5)
TypeError: TikTokTTSException.__init__() missing 1 required positional argument: 'message'

### System Information

Operating System : Ubuntu 22.04 (Server)
Python version : Python 3.10.6
App version / Branch : 3.0.1 and master branch

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Undeadsmarties** [comment]
I had the same issue.
I was missing the  'tiktok_sessionid': '' in the toml config file.
This page in the documentation fixed it for me. https://reddit-video-maker-bot.netlify.app/docs/configuring

**Comment by SpamixOfficial** [comment]
@Undeadsmarties I realized that too just now. Thanks for the help :)
