### ISSUE TITLE
[Bug]: When I throw the hand it makes me crash and I can not create my video

### ISSUE THREAD

**Issue by Ekrr93** [elebumm/RedditVideoMakerBot#1531]
### Describe the bug

Hello I’m not sure if I’m in the right place but I have a problem when I launch the main . Before launching it I did all the steps and there was no mistake. Once I throw the hand I put my Clien ID etc and set the parameters by putting the letters y or n . After that my hand screen leaves and I don’t have my video . I followed a youtube tutorial which is this: https://www.youtube.com/watch?v=YZzNaqay4rk&t=240s
Please if I skipped a step and it’s not these steps tell me which steps I’m missing because I’ve been looking everywhere for 2 days I’ve been trying to make it work. Thank you in advance for your help 

### Reproduction Steps

nothing

### Expected behavior

/

### Screenshots

/

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Ekrr93** [comment]
I am on pyton 3.10.6

**Comment by fin-github** [comment]
That video is VERY old. Follow the [documentation](https://reddit-video-maker-bot.netlify.app/). It is indepth, and very easy.

**Comment by OpenSourceSimon** [comment]
Follow our documentation
