### ISSUE TITLE
[Bug]: Main.py crashes

### ISSUE THREAD

**Issue by Schmandmann223** [elebumm/RedditVideoMakerBot#1532]
### Describe the bug

It crashes after few seconds in this screen https://prnt.sc/Z9p5oN6SPGuF

### Reproduction Steps

i follow the steps and when i click Main.py it happens

### Expected behavior

crashes

### Screenshots

https://prnt.sc/Z9p5oN6SPGuF

### System Information

Operating System : [e.g. Windows 10]
Python version : [e.g. Python 3.10.9]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Svel26** [comment]
i have the exact same issue

**Comment by Nikicha316** [comment]
I found help from this video on how to install the bot. The bot crashed every time for me.
https://youtu.be/bWRPWjc0PbE
