### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by Enigma1309** [elebumm/RedditVideoMakerBot#1541]
### Describe the bug

https://www.youtube.com/@MainlyFact
how is this guy making videos, there are plenty of similar channels doing so
there video looks and feels totally different also they have the same thumbnail which looks that had been generated by the program itself 
please help me with this

### Reproduction Steps

That's what i want

### Expected behavior

IDK

### System Information

NIL

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Enigma1309** [comment]
anyone's help would be appreciated

**Comment by Lukallo** [comment]
It sounds like the voiceovers and everything else is done manually, i doubt that it could be done with a bot.

**Comment by Enigma1309** [comment]
> It sounds like the voiceovers and everything else is done manually, i doubt that it could be done with a bot.

that might not be the case because there's few other channels i found too which have same type of thumbnail and same type of videos and with the same voice, chances are that a same person is running multiple channels but it seems kinda sussy for someone to run >10 channels at a same time

**Comment by acesino25** [comment]
thumbnail might be the one generated, the same for the voice and other aspects. But further editing might be done manually.
Although, many things in the video can be programmed to be done with the machine. There are aspects like animations like walking to fit with the context of the comment that give you a hint that it is done manually.

Conclusion: You can edit this repo to achieve something like the videos in the chanel, especially randomizing images from VERBS and ADJECTIVES. It is not my area of expertise, so i can't give you a certain guide apart from telling you that is it possible to achieve to produce a result 90% like the videos you provided
