### ISSUE TITLE
[Bug]: OSError: MoviePy error: the file assets/temp/1275ygq/mp3/2.mp3 could not be found!

### ISSUE THREAD

**Issue by dani1111iii** [elebumm/RedditVideoMakerBot#1542]
### Describe the bug

When creating the video, one of the TTS mp3s are not being created.
Here is the error:

I also attached my config down below (password,secret and id obviously omitted)

 File "C:\Users\son\Desktop\RedditVideoMakerBot-master\main.py", line 115, in <module>
    raise err
  File "C:\Users\son\Desktop\RedditVideoMakerBot-master\main.py", line 99, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\son\Desktop\RedditVideoMakerBot-master\main.py", line 63, in run_many
    main()
  File "C:\Users\son\Desktop\RedditVideoMakerBot-master\main.py", line 55, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "C:\Users\son\Desktop\RedditVideoMakerBot-master\video_creation\final_video.py", line 116, in make_final_video
    audio_clips = [
  File "C:\Users\son\Desktop\RedditVideoMakerBot-master\video_creation\final_video.py", line 117, in <listcomp>
    AudioFileClip(f"assets/temp/{reddit_id}/mp3/{i}.mp3")
  File "C:\Users\son\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\audio\io\AudioFileClip.py", line 70, in __init__
    self.reader = FFMPEG_AudioReader(filename, fps=fps, nbytes=nbytes,
  File "C:\Users\son\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\audio\io\readers.py", line 51, in __init__
    infos = ffmpeg_parse_infos(filename)
  File "C:\Users\son\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 270, in ffmpeg_parse_infos
    raise IOError(("MoviePy error: the file %s could not be found!\n"
OSError: MoviePy error: the file assets/temp/1275ygq/mp3/2.mp3 could not be found!
Please check that you entered the correct path.

### Reproduction Steps

Create a video. I have precisely followed the readme by installing requirements.txt and playwright. Also says ffmpeg is not a recognised command.

### Expected behavior

It is meant to create the video with no errors, and no missing audio files causing an exception.

### Screenshots

[ai]
ai_similarity_enabled = false
ai_similarity_keywords = ""

[settings]
allow_nsfw = false
theme = "dark"
times_to_run = 1
opacity = 0.9
transition = 0.2
storymode = false
storymodemethod = 1
storymode_max_length = 1000
fps = 30
resolution_w = 1080
resolution_h = 1920

[reddit.creds]
client_id = "omitted"
client_secret = "omitted"
username = "omitted"
password = "omitted"
2fa = false

[reddit.thread]
random = false
subreddit = "AskReddit"
post_id = ""
max_comment_length = 500
min_comment_length = 1
post_lang = ""
min_comments = 20

[settings.background]
background_choice = "rocket-league"
background_thumbnail = false
background_thumbnail_font_family = "arial"
background_thumbnail_font_size = 96
background_thumbnail_font_color = "255,255,255"

[settings.tts]
voice_choice = "tiktok"
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_001"
tiktok_sessionid = "omitted"
python_voice = "1"
py_voice_num = "2"
silence_duration = 0.3
no_emojis = false

Also:

y
Example: False
Non-optional no_emojis=
The default value is "False"
Do you want to use it?(y/n)
y
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ on the 1st iteration of 1                                                                                            │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Logging into Reddit.
Version 7.6.1 of praw is outdated. Version 7.7.0 was released Saturday February 25, 2023.
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ Getting subreddit threads...                                                                                         │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Using subreddit: r/AskReddit from TOML config
This post was pinned by moderators. Skipping...
NSFW Post Detected. Skipping...
NSFW Post Detected. Skipping...
Video will be: How do you feel about the indictment of Donald Trump? 👍
Thread url is : https://reddit.com/r/AskReddit/comments/1275ygq/how_do_you_feel_about_the_indictment_of_donald/ 👍
Thread has 3945 upvotes
Thread has a upvote ratio of 76.0%
Thread has 4679 comments
Received subreddit threads Successfully.
Thread ID is 1275ygq
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ Saving Text to MP3 files...                                                                                          │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Saving... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0 it/s  'ffmpeg' is not recognized as an internal or external command,
operable program or batch file.
Saving... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0 it/s  'ffmpeg' is not recognized as an internal or external command,
operable program or batch file.
Saving... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.8 it/s
Saved Text to MP3 files successfully.
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ Downloading screenshots of reddit posts...                                                                           │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Launching Headless Browser...
Logging in to Reddit...
Skipping translation...
Downloading screenshots... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Screenshots downloaded Successfully.
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ We need to download the backgrounds videos. they are fairly large but it's only done once. 😎                        │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Downloading the backgrounds videos... please be patient 🙏
Downloading rocket_league.mp4 from https://www.youtube.com/watch?v=2X9QGY__0II
Background video downloaded successfully! 🎉██████████████████████████████████████████████████████████████████████████| 100.0%
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ Finding a spot in the backgrounds video to chop...✂️                                                                                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Moviepy - Running:
>>> "+ " ".join(cmd)
Moviepy - Command successful
Background video chopped successfully!
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ Creating the final video 🎥                                                                                                                                                                                   │╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                                                                              ││ Version: 3.0.1,Story mode: False, Story mode method: 1,                                                                                                                                                       ││ Postid : {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'transition': 0.2, 'storymode': False, 'storymodemethod': 1, 'storymode_max_length': 1000, 'fps': 30, 'resolution_w':      ││ 1080, 'resolution_h': 1920, 'background': {'background_choice': 'rocket-league', 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96,            ││ 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'tiktok', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid':      ││ 'c8761a6530dd8e41c17b7e5903769eff', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}},allownsfw :False,is_nsfw : False                                                  │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

### System Information

Operating System : Windows 11
Python version : Python 3.10

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

Tried to re-download the git repo and re-try with no success.

**Comment by Gouldilocks** [comment]
Hey! I had this exact issue. It turns out that MacOS requires this package that is used when you run the titktok voice: ffmpeg. I solved the issue by running
```
brew install ffmpeg
```
and then restarting vs code and opening a new terminal. Not sure how you are running it, but your terminal needs to be restarted after installing in order for it to take effect. Happy hacking!
