### ISSUE TITLE
[Bug]: Seems to be a tiktoktts issue

### ISSUE THREAD

**Issue by AresVRCOfficial** [elebumm/RedditVideoMakerBot#1548]
### Describe the bug

 Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                                                                 │
│ Version: 3.0.1,Story mode: False, Story mode method: 1,                                                                                                                                          │
│ Postid : {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 10, 'opacity': 0.9, 'transition': 0.2, 'storymode': False, 'storymodemethod': 1, 'storymode_max_length': 1000, 'fps': 60,        │
│ 'resolution_w': 1080, 'resolution_h': 1920, 'background': {'background_choice': 'minecraft', 'background_thumbnail': True, 'background_thumbnail_font_family': 'arial',                          │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'aws_polly_voice': 'karen', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001',   │
│ 'tiktok_sessionid': '', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.4, 'no_emojis': False, 'voice_choice': 'tiktok'}},allownsfw :False,is_nsfw : False                       │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "C:\Users\Johnathan\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 115, in <module>
    raise err
  File "C:\Users\Johnathan\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 99, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\Johnathan\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 63, in run_many
    main()
  File "C:\Users\Johnathan\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\Johnathan\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\video_creation\voices.py", line 37, in save_text_to_mp3
    text_to_mp3 = TTSEngine(
  File "C:\Users\Johnathan\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 45, in __init__
    self.tts_module = tts_module()
  File "C:\Users\Johnathan\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\TTS\TikTok.py", line 83, in __init__
    raise TikTokTTSException(5)
TypeError: TikTokTTSException.__init__() missing 1 required positional argument: 'message'

### Reproduction Steps

happened on configuration out of the box.

### Expected behavior

expected it to function, it pops this error on every attempt.

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]
Windows 11
Python 3.10
App version latest or master im not sure.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by filiptr** [comment]
Same problem here...

**Comment by szriru** [comment]
Did you set tiktok_sessionid value in config.toml?
You should follow this instruction --> https://reddit-video-maker-bot.netlify.app/docs/configuring#obtaining-tiktok-sessionid
or just get sessionid from dev-tool in your browser and set it to config.toml

**Comment by OpenSourceSimon** [comment]
Fill in sessionid
