### ISSUE TITLE
[Bug]: Its Crash

### ISSUE THREAD

**Issue by SembiaStudios** [elebumm/RedditVideoMakerBot#1553]
### Describe the bug

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ You are using the newest version (3.0.1) of the bot                                                                                           │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
###############################
#                             #
# Checking TOML configuration #
#                             #
###############################
If you see any prompts, that means that you have unset/incorrectly set variables, please input the correct values.
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ on the 1st iteration of 1                                                                                                                     │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Logging into Reddit.
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Getting subreddit threads...                                                                                                                  │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Using subreddit: r/AskReddit from TOML config
This post was pinned by moderators. Skipping...
Video will be: Would you vote for Jon Stewart if he ran for President? If so, why? If not, why? 👍
Thread url is : https://reddit.com/r/AskReddit/comments/12fknkh/would_you_vote_for_jon_stewart_if_he_ran_for/ 👍
Thread has 16319 upvotes
Thread has a upvote ratio of 71.0%
Thread has 5484 comments
Received subreddit threads Successfully.
Thread ID is 12fknkh
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.              │
│ Version: 3.0.1,Story mode: False, Story mode method: 1,                                                                                       │
│ Postid : {'allow_nsfw': True, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'transition': 0.2, 'storymode': False, 'storymodemethod':   │
│ 1, 'storymode_max_length': 1000, 'fps': 60, 'resolution_w': 1080, 'resolution_h': 1920, 'background': {'background_choice': 'minecraft',      │
│ 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96,                             │
│ 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'tiktok', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice':  │
│ 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': '', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3,            │
│ 'no_emojis': False}},allownsfw :True,is_nsfw : False                                                                                          │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "C:\Users\Nathan\Desktop\RedditVideoMakerBot-3.0.1\main.py", line 115, in <module>
    raise err
  File "C:\Users\Nathan\Desktop\RedditVideoMakerBot-3.0.1\main.py", line 99, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\Nathan\Desktop\RedditVideoMakerBot-3.0.1\main.py", line 63, in run_many
    main()
  File "C:\Users\Nathan\Desktop\RedditVideoMakerBot-3.0.1\main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\Nathan\Desktop\RedditVideoMakerBot-3.0.1\video_creation\voices.py", line 37, in save_text_to_mp3
    text_to_mp3 = TTSEngine(
  File "C:\Users\Nathan\Desktop\RedditVideoMakerBot-3.0.1\TTS\engine_wrapper.py", line 45, in __init__
    self.tts_module = tts_module()
  File "C:\Users\Nathan\Desktop\RedditVideoMakerBot-3.0.1\TTS\TikTok.py", line 83, in __init__
    raise TikTokTTSException(5)
TypeError: TikTokTTSException.__init__() missing 1 required positional argument: 'message'

### Reproduction Steps

Test with my config.toml file :

[ai]
ai_similarity_enabled = false
ai_similarity_keywords = "y"

[settings]
allow_nsfw = true
theme = "dark"
times_to_run = 1
opacity = 0.9
transition = 0.2
storymode = false
storymodemethod = 1
storymode_max_length = 1000
fps = 60
resolution_w = 1080
resolution_h = 1920

[settings.background]
background_choice = "minecraft"
background_thumbnail = false
background_thumbnail_font_family = "arial"
background_thumbnail_font_size = 96
background_thumbnail_font_color = "255,255,255"

[settings.tts]
voice_choice = "tiktok"
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_001"
tiktok_sessionid = ""
python_voice = "1"
py_voice_num = "2"
silence_duration = 0.3
no_emojis = false

[reddit.creds]
client_id = "SlwREvb1uwzy-ejqeZLS4Q"
client_secret = "tkoy59H5mpDYXEVGsgx2N5CkJCaKyA"
username = "Shot_Cupcake2304"
password = "mannheim11234!"
2fa = false

[reddit.thread]
random = false
subreddit = "AskReddit"
post_id = ""
max_comment_length = 500
min_comment_length = 1
post_lang = ""
min_comments = 20

### Expected behavior

I start the main.py script and it find a reddit post and crash after it have find

### System Information

Operating System : Win10
Python version : Python 3.11 and Python 3.10 i tested both
App version / Branch : latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
Fill in sessionid
