### ISSUE TITLE
[Bug]: Winerror 2 FileNotFound

### ISSUE THREAD

**Issue by SubAtomicOne** [elebumm/RedditVideoMakerBot#1556]
### Describe the bug

Here is the error message that keeps persisting no matter what I try.

╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                                  ││ Version: 3.0.1                                                                                                                                                    ││ Error: [WinError 2] The system cannot find the file specified                                                                                                     ││ Config: {'allow_nsfw': False, 'theme': 'light', 'times_to_run': 1, 'opacity': 0.9, 'transition': 0.2, 'storymode': False, 'storymodemethod': 1,                   ││ 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'background': {'background_choice': 'minecraft', 'background_thumbnail': False,         ││ 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice':     ││ 'streamlabspolly', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED',                ││ 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                                                                           │╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Traceback (most recent call last):
  File "c:\Users\Davis\RedditVideoMakerBot-develop\main.py", line 108, in <module>
    raise err
  File "c:\Users\Davis\RedditVideoMakerBot-develop\main.py", line 90, in <module>
    run_many(config["settings"]["times_to_run"])
  File "c:\Users\Davis\RedditVideoMakerBot-develop\main.py", line 55, in run_many
    main()
  File "c:\Users\Davis\RedditVideoMakerBot-develop\main.py", line 48, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "c:\Users\Davis\RedditVideoMakerBot-develop\video_creation\final_video.py", line 112, in make_final_video
    background_clip = ffmpeg.input(prepare_background(reddit_id, W=W, H=H))
  File "c:\Users\Davis\RedditVideoMakerBot-develop\video_creation\final_video.py", line 88, in prepare_background
    output.run(quiet=True)
  File "C:\Users\Davis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "C:\Users\Davis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

### Reproduction Steps

Every time that I run this code, I get this issue 

### Expected behavior

Run Normally

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.10.11]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by reineto** [comment]
same erro here

**Comment by PlayTim** [comment]
same error by me too

**Comment by PlayTim** [comment]
I get the Error when it should save the finale Video

**Comment by Aryan-vallabhbhai** [comment]
I have the same error

**Comment by SiouxxieSixxsta** [comment]
this might be due to how imagemagick/moviepy is installed (another debug would be to install image magick). you can maybe be able to fix this by using a virtual environment and after installing all the requirements/libraries you can go into venv/lib/sitpackages/moviepy and go into config_defaults.py. Next scroll down to "IMAGEMAGICK_BINARY = os.getenv('IMAGEMAGICK_BINARY', 'auto-detect')" and replace it with "IMAGEMAGICK_BINARY = "C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\magick.exe"" replace the path with the path to YOUR image magick exe file path and make sure there are two slashes when you paste your path. Lastly run the main py file and it should have fixed it. Hopefully that helped.
