### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by aaronneedshelpo** [elebumm/RedditVideoMakerBot#1557]
### Describe the bug

I open it up and does it's usual thing and then it just crashes after I get that message.

### Reproduction Steps

I followed the steps and then I opened it up went thru my config this is it btw 

[ai]
ai_similarity_enabled = false
ai_similarity_keywords = ""

[settings]
allow_nsfw = true
theme = "dark"
times_to_run = 1
opacity = 0.9
transition = 0.2
storymode = true
storymodemethod = 1
storymode_max_length = 1000
fps = 30
resolution_w = 1080
resolution_h = 1920

[settings.background]
background_choice = "minecraft"
background_thumbnail = false
background_thumbnail_font_family = "arial"
background_thumbnail_font_size = 96
background_thumbnail_font_color = "255,255,255"

[settings.tts]
voice_choice = "tiktok"
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_001"
tiktok_sessionid = ""
python_voice = "1"
py_voice_num = "2"
silence_duration = 0.3
no_emojis = false

[reddit.creds]
client_id = ""
client_secret = ""
username = ""
password = ""
2fa = true

[reddit.thread]
random = true
subreddit = "AskReddit"
post_id = ""
max_comment_length = 500
min_comment_length = 250
post_lang = ""
min_comments = 20

Password information removed for obvious reasons

### Expected behavior

I expected it to open up start generating a video with the voodoo magic coding ish and then bang I have a video to post.

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/86541445/231035634-2214dc8a-9c3e-4477-be97-9cd677e9e248.jpg)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]
![Screenshot_1](https://user-images.githubusercontent.com/86541445/231035328-7e0513cb-50c0-4794-8015-aad8b6591afd.jpg)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by SubAtomicOne** [comment]
Have you tried to get a session ID from tiktok, that is required to use their tts and to get it there is documentation on it

**Comment by OpenSourceSimon** [comment]
Fill in sessionid
