### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by saleemalharir1** [elebumm/RedditVideoMakerBot#1560]
### Describe the bug

couldn't load speech 
I tried some stuff but still not working 

### Reproduction Steps

I just installed the packages and got the TikTok session id and the reddit script app info 

### Expected behavior

I expected the bot to run and generate the videos since I have done the steps 

### Screenshots

<img width="842" alt="Screenshot 2023-04-12 at 9 16 09 AM" src="https://user-images.githubusercontent.com/97859803/231504807-e8cda263-0dc3-4fbb-bc57-6cdd5d342a35.png">

### System Information

Operating System : OSX 13.2.1
Python version : 3.10
App version / Branch : latest 3.0.1

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by PaoloJN** [comment]
Same thing happened to me

**Comment by Mik3humphrey** [comment]
same here

**Comment by Mik3humphrey** [comment]
So I got it to work I Run python GUI.py then you can change the tts from tiktok to streamlabs
