### ISSUE TITLE
[Feature]: Eleven Labs TTS

### ISSUE THREAD

**Issue by RemainingToast** [elebumm/RedditVideoMakerBot#1564]
### Summary

Add Eleven Labs TTS compatibility

### Is your feature request related to a problem?

No TTS Engine for Eleven Labs

### Describe the solution you'd like

TTS Engine for Eleven Labs API

**Comment by OpenSourceSimon** [comment]
Good one!

**Comment by liamb13** [comment]
@RemainingToast feel free to test out my PR and offer some comments/criticisms
