### ISSUE TITLE
Change Voice Over? 

### ISSUE THREAD

**Issue by Chrone4746** [elebumm/RedditVideoMakerBot#158]
Hello, is there a way to change the TTS voice over to a different voice? I don't really like it.

**Comment by jacesleeman** [comment]
look at pull request #92 and inside of vocies.py u can change Brain to any of the male names on here https://lazypy.ro/tts/.

**Comment by FreebieII** [comment]
#92 

I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
