### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SparkAladdin** [elebumm/RedditVideoMakerBot#1581]
### Describe the bug

Keep telling me to install FFmpeg in the main.py when it is already installed 

### Reproduction Steps

Python3 main.py 

### Expected behavior

I expect this shit to stop asking me to install when it's already installed.

### Screenshots

![Screen Shot 2023-04-15 at 3 34 17 PM](https://user-images.githubusercontent.com/103237204/232249967-cc730d70-994f-4c94-9b22-adae1367519c.png)
![Screen Shot 2023-04-15 at 3 34 33 PM](https://user-images.githubusercontent.com/103237204/232249969-7ce29bf9-c9da-423c-a171-e14602b1ef01.png)

### System Information

Operating System : [e.g. mac os]
Python version : [e.g. Python 3.10]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

Now I'm getting this error. What the fuck....

2, in <module>
    from video_creation.final_video import make_final_video
  File "/Users/anthonybryant/Desktop/RedditVideoMakerBot-master/video_creation/final_video.py", line 9, in <module>
    import ffmpeg
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ffmpeg/__init__.py", line 3, in <module>
    from . import _ffmpeg
ImportError: cannot import name '_ffmpeg' from partially initialized module 'ffmpeg' (most likely due to a circular import) (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ffmpeg/__init__.py)

**Comment by liamb13** [comment]
For my install, I didn't use the code base. I found it was easier to install ffmpeg via brew

**Comment by OpenSourceSimon** [comment]
You need to add ffmpeg to the PATH.

**Comment by OpenSourceSimon** [comment]
> For my install, I didn't use the code base. I found it was easier to install ffmpeg via brew

This code uses brew to install ffmpeg

**Comment by Massimoiezzi** [comment]
> You need to add ffmpeg to the PATH. 

sorry if I'm writing but I'm really a novice, I have the same problem, could you tell me in what sense (and where is), the "PATH"? Thanks in advance

**Comment by Massimoiezzi** [comment]
> You need to add ffmpeg to the PATH. 

sorry if I'm writing but I'm really a novice, I have the same problem, could you tell me in what sense (and where is), the "PATH"? Thanks in advance

**Comment by OpenSourceSimon** [comment]
> > You need to add ffmpeg to the PATH.
> 
> sorry if I'm writing but I'm really a novice, I have the same problem, could you tell me in what sense (and where is), the "PATH"? Thanks in advance

Hey, please join the Discord server. It's easier to help you there

**Comment by Massimoiezzi** [comment]
> > > You need to add ffmpeg to the PATH.
> > 
> > sorry if I'm writing but I'm really a novice, I have the same problem, could you tell me in what sense (and where is), the "PATH"? Thanks in advance
> 
> Hey, please join the Discord server. It's easier to help you there

Okay, what's the invite link? (Or where it is)

**Comment by Massimoiezzi** [comment]
> > > You need to add ffmpeg to the PATH.
> > 
> > sorry if I'm writing but I'm really a novice, I have the same problem, could you tell me in what sense (and where is), the "PATH"? Thanks in advance
> 
> Hey, please join the Discord server. It's easier to help you there

Okay, what's the invite link? (Or where it is)

**Comment by liamb13** [comment]
> > > > You need to add ffmpeg to the PATH.
> > > 
> > > sorry if I'm writing but I'm really a novice, I have the same problem, could you tell me in what sense (and where is), the "PATH"? Thanks in advance
> > 
> > Hey, please join the Discord server. It's easier to help you there
> 
> Okay, what's the invite link? (Or where it is)

https://discord.com/invite/Vkanmh6C8V
