### ISSUE TITLE
[Bug]: TikTokTTSException: Code: 1, reason: probably the aid value isn't correct

### ISSUE THREAD

**Issue by joshholly** [elebumm/RedditVideoMakerBot#1582]
### Describe the bug

When it goes to create the mp3, it gives me this error: 

` raise TikTokTTSException(status_code, data["message"])
TTS.TikTok.TikTokTTSException: Code: 1, reason: probably the aid value isn't correct, message: Couldn't load speech. Try again.`

I checked my tiktok sessionID multiple times and it is correct in the config.toml file, same thing with the tiktok voice ID, I tried different ones. The current one I am using is

`voice_choice = "tiktok"`
`tiktok_voice = "en_us_007"`

### Reproduction Steps

Run the command python3 main.py and wait for it to get to the part where it creates an mp3 from tiktok api.

### Expected behavior

Create an mp3 with tiktok TTS. 

### System Information

Operating System : MacOS 13.2.1 (22D68)
Python version : Python 3.10.9
App version / Branch : master (3.1)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by joshholly** [comment]
Config: {'allow_nsfw': True, 'theme': 'light', 'times_to_run': 2, 'opacity': │
│ 0.9, 'transition': 0.2, 'storymode': False, 'storymodemethod': 1,            │
│ 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920,    │
│ 'background': {'background_choice': 'minecraft-2', 'background_thumbnail':   │
│ False, 'background_thumbnail_font_family': 'arial',                          │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color':     │
│ '255,255,255'}, 'tts': {'voice_choice': 'tiktok', 'aws_polly_voice':         │
│ 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_007', │
│ 'tiktok_sessionid': 'REDACTED', 'python_voice': '1', 'py_voice_num': '2',    │
│ 'silence_duration': 0.3, 'no_emojis': True}}   

Is the config. I know the tiktok session ID is redacted but I did get the correct one by using Cookie Editor plugin and then grabbing the value of the cookie sessionid.

**Comment by wesly-michel** [comment]
Same  Bug here

**Comment by sanadkh08** [comment]
Change the voice_choice in the config file to something other than tiktok, **Valid** options are: streamlabspolly, tiktok, googletranslate, awspolly, pyttsx.

**Comment by liamb13** [comment]
Hopefully fixed in: #1612

**Comment by liamb13** [comment]
@OpenSourceSimon I believe this was fixed and can be closed

**Comment by bgramaje** [comment]
So I guess, as of now, there is no way of using tiktok voices right?
