### ISSUE TITLE
[Bug]: Transition and silence duration does not work

### ISSUE THREAD

**Issue by joshholly** [elebumm/RedditVideoMakerBot#1587]
### Describe the bug

No matter what I set the transition duration and silence duration to, it still does not put any bit of silence between each screenshot. 

### Reproduction Steps

Create reddit video

### Expected behavior

Place silence between each screenshot. 

### System Information

Operating System : MacOS 
Python version : Python 3.10.9
App version / Branch : 3.1 (master)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by zgauhar** [comment]
Any updates on this issue or any hints on where to check for a fix?
