### ISSUE TITLE
[Feature]: Just Download the Trimmed(short) Gamplay video.

### ISSUE THREAD

**Issue by tikendraw** [elebumm/RedditVideoMakerBot#1589]
### Summary

This programe downloads alot longer gameplay videos which is unecessay if you are just using 1 or 2 min clip out of it

### Is your feature request related to a problem?

This programe downloads alot longer gameplay videos which is unecessay if you are just using 1 or 2 min clip out of it. 

### Describe the solution you'd like

if there is any way just download 5 min gameplay videos or any sections of hours long gameplay. It would save time. and Bandwidth.

**Comment by OpenSourceSimon** [comment]
No I think the current method is the most efficient one
