### ISSUE TITLE
[Bug]: Issue with TTS when a comment ends with a link

### ISSUE THREAD

**Issue by liamb13** [elebumm/RedditVideoMakerBot#1591]
### Describe the bug

Issue occurs when a comment (or even the post) ends on a link. 

I've diagnosed it to being caused by the `add_periods` function.

When there's a link, it can end up sending back a comment as simply '.', this causes the TTS to break, logging error:
`Code: 1, reason: probably the aid value isn't correct, message: Text-to-speech isn't supported for this language`

### Reproduction Steps

Can be tricky to reproduce, as it happens every now and again.

If you can find a thread with comments ending with a link, you may have luck (although sometimes the program will skip that comment).

### Expected behavior

We need to try and find a way to prevent add_periods if it's trying to add it to the end of a link.

### System Information

Operating System : Windows 11
Python version : Python 3.10
App version / Branch : master

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by ingberrio** [comment]
<img width="627" alt="image" src="https://user-images.githubusercontent.com/2388913/233789264-53d028c7-cd82-4640-95f1-bae6ee90e6af.png">
It's the same error?
