### ISSUE TITLE
[Bug]: ffmpeg error (see stderr output for detail)

### ISSUE THREAD

**Issue by randomuser1090** [elebumm/RedditVideoMakerBot#1592]
### Describe the bug

![botbugreport](https://user-images.githubusercontent.com/131568095/233816665-1d9c3051-90fe-48da-8d3d-b74d474d58f4.PNG)

Does anyone know how to solve this?

ffmpeg error (see stderr output for detail)

ffmpeg is already on the latest version. Idk what to do

### Reproduction Steps

I send "python main.py" and I wait untill the error happens ins the "Creating final video" part

### Expected behavior

It was supposed to create the video normally

### Screenshots

![botbugreport](https://user-images.githubusercontent.com/131568095/233816691-61fe8791-1c13-4510-9a6b-2b9b3554378c.PNG)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by sparkle666** [comment]
Hello, can you paste the error, if the error is on your command line, kindly paste it in so I can take a look at it.

**Comment by rangeethmj** [comment]
> Hello, can you paste the error, if the error is on your command line, kindly paste it in so I can take a look at it.

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Creating the final video 🎥                                                                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ffmpeg error (see stderr output for detail)

**Comment by sparkle666** [comment]
Where is the error, check if there is log file on there and attach the error to it.

**Comment by shoaibch40** [comment]
I am able to replicate this issue. There is no error. 
I tried following command and the file is empty
python3.10 main.py 2> error.log

**Comment by abbas-dhd** [comment]
> 

Were you able to fix this?

**Comment by arthitsaha** [comment]
Is this issue fixed?

**Comment by martin-vkd** [comment]
I Just got this error too

**Comment by mart337i** [comment]
i get this error on the newest version too
