### ISSUE TITLE
[Bug]: error when getting screenShot

### ISSUE THREAD

**Issue by DZ3G** [elebumm/RedditVideoMakerBot#1599]
### Describe the bug

was using the Version 3.0.1 Since i had issue with ffmpeg in version 3.1 and as i was running the program this happend, i do have a problem with ffmpeg so if anyone could please explain how i could fix it

### Reproduction Steps

Ran The Main command " python main.py "

### Expected behavior

run smoothly

### Screenshots

![Desktop Screenshot 2023 04 27 - 19 38 58 50](https://user-images.githubusercontent.com/113042463/234961596-a66e323f-8ea4-46fd-ae0d-8b585c4c6c04.png)
![Desktop Screenshot 2023 04 27 - 19 39 08 84](https://user-images.githubusercontent.com/113042463/234961608-fd110896-1d2b-499c-ad73-50e94d3e6cbf.png)
![Desktop Screenshot 2023 04 27 - 19 42 51 62](https://user-images.githubusercontent.com/113042463/234961615-241d1faf-51ff-43e3-92a2-e3a29002b2d8.png)
![Desktop Screenshot 2023 04 27 - 19 42 58 15](https://user-images.githubusercontent.com/113042463/234961628-1b29b321-cdfb-495e-acfb-8ebcd8df1506.png)

### System Information

Operating System : [e.g. Windows 10]
Python version : [e.g. Python 3.10.11]
App version / Branch : [e.g. latest, V3.0.1, master, develop]

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

windows 10 (86x)
python 3.10.11
RedditVideoMakerBot 3.0.1

**Comment by dav3shanahan** [comment]
https://www.reddit.com/r/MachineLearning/comments/12r7qi7/d_new_reddit_api_terms_effectively_bans_all_use/

**Comment by PlayTim** [comment]
have the same error

**Comment by DZ3G** [comment]
k

**Comment by liamb13** [comment]
Believe I've fixed this in #1664
