### ISSUE TITLE
[Enhancement] TUI Setup Interface

### ISSUE THREAD

**Issue by BlockArchitech** [elebumm/RedditVideoMakerBot#16]
I just created a fork of this project, and I'm going to work on a TUI setup interface. I'm partially inspired by [CubedFileManager](https://github.com/supercrafter100/cubedfilemanager) because it has a nice setup TUI.

If you want, you can go ahead an assign me for this and I'll push a pull request soon.

**Comment by BlockArchitech** [comment]
Also, there seems to be an issue with `typed-ast`. setup.py is reporting an error.

**Comment by Bango88** [comment]
> Also, there seems to be an issue with `typed-ast`. setup.py is reporting an error.

Changing the requirement to typed-ast==1.5.4 fixes it.

**Comment by JasonLovesDoggo** [comment]
is typed-ast even necessaryfor this???

I removed it from requirments.txt and it worked just fine

**Comment by BlockArchitech** [comment]
I've got most everything done!

I also added a little bit more verbose and made things look a little nicer. I'll go more in-depth in the PR.

**Comment by BlockArchitech** [comment]
PR Submitted.
