### ISSUE TITLE
Idea: Sort comments by top instead of best?

### ISSUE THREAD

**Issue by jpmarques123** [elebumm/RedditVideoMakerBot#160]
Sometimes when I make a video with a smaller thread, it pulls in comments with less upvotes than others. Not usually an issue, just would be nice

**Comment by FreebieII** [comment]
> 

Hi @jpmarques123 ,

Comments are already sorted by top! 

I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
