### ISSUE TITLE
[Bug]: Background Video Downloader Stopped Working

### ISSUE THREAD

**Issue by joshholly** [elebumm/RedditVideoMakerBot#1601]
### Describe the bug

I was not having any problems up until recently. Now when I add a new video, start the reddit bot, and it goes to download it because it's new, the app crashes with this error

```
Traceback (most recent call last):
  File "/Users/wafflehacker/Sites/RedditVideoMakerBot-master/main.py", line 130, in <module>
    raise err
  File "/Users/wafflehacker/Sites/RedditVideoMakerBot-master/main.py", line 108, in <module>
    main(post_id)
  File "/Users/wafflehacker/Sites/RedditVideoMakerBot-master/main.py", line 54, in main
    download_background(bg_config)
  File "/Users/wafflehacker/Sites/RedditVideoMakerBot-master/video_creation/background.py", line 75, in download_background
    YouTube(uri, on_progress_callback=on_progress).streams.filter(
  File "/usr/local/anaconda3/lib/python3.10/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "/usr/local/anaconda3/lib/python3.10/site-packages/pytube/__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "/usr/local/anaconda3/lib/python3.10/site-packages/pytube/__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'
```

### Reproduction Steps

Launch the GUI, go to add a new background video. Launch the bot on any thread, select the new video you added,  wait until it starts to download the new background video.

### Expected behavior

Download the video

### System Information

Operating System : MacOS 13.2.1
Python version : [e.g. Python 3.10.9
App version / Branch : 3.1 (latest master stable)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by kinovideo** [comment]
Я добавил вручную

**Comment by jhon4than** [comment]
Mesmo erro aqui alguém sabe o motivo ?

**Comment by jhon4than** [comment]
> Я добавил вручную

como fazer isso manualmente ?

**Comment by kobykotiv** [comment]
I have the same issue as well. Does have a workaround for this?

**Comment by joshholly** [comment]
It looks like an issue with pytube. I have tried uninstalling and reinstalling pytube and I get the same issue. I have no idea how to fix this.

**Comment by PandaMajor** [comment]
I tried this fix to the library code: https://github.com/pytube/pytube/issues/743#issuecomment-1528453973 (Click on "innertube.py" and edit the code on line 78 replacing client='ANDROID' with client='WEB') which seemed to fix the issue for me. Sounds like an android update is causing some problems with the library. It's my first time using this app, so I'm not sure how fast the video downloaded before but it is quite slow with this change.

**Comment by joshholly** [comment]
> I tried this fix to the library code: [pytube/pytube#743 (comment)](https://github.com/pytube/pytube/issues/743#issuecomment-1528453973) (Click on "innertube.py" and edit the code on line 78 replacing client='ANDROID' with client='WEB') which seemed to fix the issue for me. Sounds like an android update is causing some problems with the library. It's my first time using this app, so I'm not sure how fast the video downloaded before but it is quite slow with this change.

You're running your code on android? I am using MacOS. I didn't know you could run this on android, lol.

**Comment by joshholly** [comment]
> I tried this fix to the library code: [pytube/pytube#743 (comment)](https://github.com/pytube/pytube/issues/743#issuecomment-1528453973) (Click on "innertube.py" and edit the code on line 78 replacing client='ANDROID' with client='WEB') which seemed to fix the issue for me. Sounds like an android update is causing some problems with the library. It's my first time using this app, so I'm not sure how fast the video downloaded before but it is quite slow with this change.

It's fixed but  it is super slow. Like it's going to take an hour to download an hour video. It was much faster with WEB. I'm hoping pytube can actually get it fixed to run fast again.

**Comment by PandaMajor** [comment]
> > I tried this fix to the library code: [pytube/pytube#743 (comment)](https://github.com/pytube/pytube/issues/743#issuecomment-1528453973) (Click on "innertube.py" and edit the code on line 78 replacing client='ANDROID' with client='WEB') which seemed to fix the issue for me. Sounds like an android update is causing some problems with the library. It's my first time using this app, so I'm not sure how fast the video downloaded before but it is quite slow with this change.
> 
> You're running your code on android? I am using MacOS. I didn't know you could run this on android, lol.

No, I'm running it on a Windows machine lol. I'm not really too sure how pytube works so I don't know why but, changing the code in the innertube file for pytube from web to android (as suggested above) seemed to have fixed the streamingData key error for me. The video did take a few hours to download unfortunately, I think it might be better to download it yourself and just add it to the backgrounds folder manually. It seems that the pytube library is sort of broken currently (as far as I could tell based on the issues tab).

**Comment by joshholly** [comment]
Found a workaround that works. So instead of modifying innertube, modify utils/background.py.

Change
` YouTube(uri, on_progress_callback=on_progress).streams.filter(
        res="1080p"
    ).first().download("assets/backgrounds", filename=f"{credit}-{filename}")`

To

` YouTube(uri, use_oauth=True, allow_oauth_cache=True, on_progress_callback=on_progress).streams.filter(
        res="1080p"
    ).first().download("assets/backgrounds", filename=f"{credit}-{filename}")`
    
    
It is way faster, it will prompt you to go to https://youtube.com/device and enter a code like you're activating a TV one time. Then you're back to downloading videos at the speed of light. If you already changed innertube in pytube to WEB, change it back to ANDROID and do what I did :)

**Comment by Thxssio** [comment]
> 

Where did you find the utils folder?

**Comment by Qriist** [comment]
"So instead of modifying innertube, modify utils/background.py."

Would you doublecheck the file name you listed? I'm having this issue with a new install and I **don't** have a background.py.

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/26832022/a8381e42-35bf-4b2a-8666-73835996d4cb)
