### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rangeethmj** [elebumm/RedditVideoMakerBot#1606]
### Describe the bug

Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the       │
│ Discord community.                                                                                                  │
│ Version: 3.1                                                                                                        │
│ Error: 'streamingData'                                                                                              │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 4, 'opacity': 0.9, 'transition': 0.2, 'storymode':   │
│ False, 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920,              │
│ 'background': {'background_choice': 'minecraft', 'background_thumbnail': False, 'background_thumbnail_font_family': │
│ 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts':            │
│ {'voice_choice': 'googletranslate', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew',              │
│ 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice': '1', 'py_voice_num': '2',              │
│ 'silence_duration': 0.3, 'no_emojis': False}}                                                                       │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "D:\Reddit Video\RedditVideoMakerBot-master\main.py", line 130, in <module>
    raise err
  File "D:\Reddit Video\RedditVideoMakerBot-master\main.py", line 111, in <module>
    run_many(config["settings"]["times_to_run"])
  File "D:\Reddit Video\RedditVideoMakerBot-master\main.py", line 64, in run_many
    main()
  File "D:\Reddit Video\RedditVideoMakerBot-master\main.py", line 54, in main
    download_background(bg_config)
  File "D:\Reddit Video\RedditVideoMakerBot-master\video_creation\background.py", line 75, in download_background
    YouTube(uri, on_progress_callback=on_progress).streams.filter(
  File "C:\Users\RAJNIVAS\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\RAJNIVAS\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "C:\Users\RAJNIVAS\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'

### Reproduction Steps

I am trying this tool fo the first time. I got this error when its trying to download the youtube video.

### Expected behavior

The tool should run smoothly and download the video from youtube.

### Screenshots

![image](https://user-images.githubusercontent.com/25541324/235349380-0c41a7ca-7424-4eff-bd2a-116f8bcc556c.png)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by ReneDraws** [comment]
Step 1: Download the Youtube video for the Background www.youtube.com/watch?v=n_Dv4JMiwK8

Step 2: rename it to "bbswitzer-parkour.mp4"

Step 3: place it into \assets\backgrounds

Error should be gone than.

**Comment by rangeethmj** [comment]
> Step 1: Download the Youtube video for the Background [www.youtube.com/watch?v=n_Dv4JMiwK8](http://www.youtube.com/watch?v=n_Dv4JMiwK8)
> 
> Step 2: rename it to "bbswitzer-parkour.mp4"
> 
> Step 3: place it into \assets\backgrounds
> 
> Error should be gone than.

Thanks Man!
