### ISSUE TITLE
[Bug]:  module 'ffmpeg' has no attribute 'input'

### ISSUE THREAD

**Issue by rangeethmj** [elebumm/RedditVideoMakerBot#1609]
### Describe the bug

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Creating the final video 🎥                                                                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                                    │
│ Version: 3.1                                                                                                                                                        │
│ Error: module 'ffmpeg' has no attribute 'input'                                                                                                                     │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'transition': 0.2, 'storymode': False, 'storymodemethod': 1,                      │
│ 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'background': {'background_choice': 'minecraft', 'background_thumbnail': False,           │
│ 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice':       │
│ 'streamlabspolly', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice':  │
│ '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                                                                                             │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "D:\RedditVideoMakerBot-3.1\main.py", line 130, in <module>
    raise err
  File "D:\RedditVideoMakerBot-3.1\main.py", line 111, in <module>
    run_many(config["settings"]["times_to_run"])
  File "D:\RedditVideoMakerBot-3.1\main.py", line 64, in run_many
    main()
  File "D:\RedditVideoMakerBot-3.1\main.py", line 56, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "D:\RedditVideoMakerBot-3.1\video_creation\final_video.py", line 127, in make_final_video
    background_clip = ffmpeg.input(prepare_background(reddit_id, W=W, H=H))
                      ^^^^^^^^^^^^
AttributeError: module 'ffmpeg' has no attribute 'input'

### Reproduction Steps

Start the tool, after successfully downloading the background video, this error pops up while creating the final video.

### Expected behavior

The final and completed video should be created the output.

### Screenshots

![image](https://user-images.githubusercontent.com/25541324/235611364-0c664767-4f33-4181-895a-22a5e0fa22ea.png)

### System Information

Operating System : Windows 10
Python version : Python 3.11.3
App version / Branch : RedditVideoMakerBot 3.1

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by SubAtomicOne** [comment]
I have been having the same issue and this hasn't worked to solve the issue for me

**Comment by Aryan-vallabhbhai** [comment]
I've been having the same issue but am not sure how to solve it either

**Comment by OpenSourceSimon** [comment]
`pip uninstall ffmpeg` and `pip install ffmpeg-python`
