### ISSUE TITLE
[Bug]: unable to find a specific file

### ISSUE THREAD

**Issue by superharsh25** [elebumm/RedditVideoMakerBot#1610]
### Describe the bug

I have done all the steps correctly to install the bot 
While doing this i encountered a few errors but I managed to fix them with some simple fix 
and I am getting this error 
and I have tried a lot of things to fix it but nothing working 
when I run the code it crashed after "creating the final video "
I think this is because of either I am not using a TikTok voice and so the TikTok session-id field is not there 
or it's unable to locate some file 
after searching a bit i realized that the 'results' folder was missing 
and I am sure that the main problem with the code 
so here's the error 

--------------

╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                                      │
│ Version: 3.1                                                                                                                                                          │
│ Error: [WinError 2] The system cannot find the file specified                                                                                                         │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 5, 'opacity': 0.9, 'transition': 0.2, 'storymode': False, 'storymodemethod': 1,                        │
│ 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'background': {'background_choice': 'minecraft', 'background_thumbnail': False,             │
│ 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice':         │
│ 'streamlabspolly', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice':    │
│ '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                                                                                               │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "c:\Users\tviva\Desktop\RedditVideoMakerBot-master\main.py", line 130, in <module>
    raise err
  File "c:\Users\tviva\Desktop\RedditVideoMakerBot-master\main.py", line 111, in <module>
    run_many(config["settings"]["times_to_run"])
  File "c:\Users\tviva\Desktop\RedditVideoMakerBot-master\main.py", line 64, in run_many
    main()
  File "c:\Users\tviva\Desktop\RedditVideoMakerBot-master\main.py", line 56, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "c:\Users\tviva\Desktop\RedditVideoMakerBot-master\video_creation\final_video.py", line 155, in make_final_video
    audio_clips_durations = [
  File "c:\Users\tviva\Desktop\RedditVideoMakerBot-master\video_creation\final_video.py", line 157, in <listcomp>
    ffmpeg.probe(f"assets/temp/{reddit_id}/mp3/{i}.mp3")["format"][
  File "C:\Users\tviva\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg\_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\tviva\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\tviva\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

### Reproduction Steps

-

### Expected behavior

i was expecting it create a video like show in the video yet that didn't happen 

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.10.10]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by NoCapxGaming** [comment]
I'm having the same issue:

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Saving Text to MP3 files...                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Saving... ---------------------------------------- 1.2 it/s
Saved Text to MP3 files successfully.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Downloading screenshots of reddit posts...                                                                          │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Launching Headless Browser...
Logging in to Reddit...
Skipping translation...
Downloading screenshots... ---------------------------------------- 100% 0:00:00
Screenshots downloaded Successfully.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Finding a spot in the backgrounds video to chop...✂️                                                                 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Moviepy - Running:
>>> "+ " ".join(cmd)
Moviepy - Command successful
Background video chopped successfully!
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Creating the final video 🎥                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the       │
│ Discord community.                                                                                                  │
│ Version: 3.1                                                                                                        │
│ Error: [WinError 2] The system cannot find the file specified                                                       │
│ Config: {'allow_nsfw': True, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'transition': 0.2, 'storymode':    │
│ False, 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920,              │
│ 'background': {'background_choice': 'greenscreen', 'background_thumbnail': False,                                   │
│ 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96,                                  │
│ 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'streamlabspolly', 'aws_polly_voice':    │
│ 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED',        │
│ 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                             │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\Video Suite\RedditVideoMakerBot-3.1\main.py", line 130, in <module>
    raise err
  File "C:\Users\USER\Desktop\Video Suite\RedditVideoMakerBot-3.1\main.py", line 111, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\USER\Desktop\Video Suite\RedditVideoMakerBot-3.1\main.py", line 64, in run_many
    main()
  File "C:\Users\USER\Desktop\Video Suite\RedditVideoMakerBot-3.1\main.py", line 56, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "C:\Users\USER\Desktop\Video Suite\RedditVideoMakerBot-3.1\video_creation\final_video.py", line 155, in make_final_video
    audio_clips_durations = [
  File "C:\Users\USER\Desktop\Video Suite\RedditVideoMakerBot-3.1\video_creation\final_video.py", line 157, in <listcomp>
    ffmpeg.probe(f"assets/temp/{reddit_id}/mp3/{i}.mp3")["format"][
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg\_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\Marco\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Marco\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified.
