### ISSUE TITLE
[Bug]: TypeError: 'NoneType' object cannot be interpreted as an integer when setting storymode method to 0

### ISSUE THREAD

**Issue by Abnumality** [elebumm/RedditVideoMakerBot#1618]
### Describe the bug

here's the error.

│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                                                                              │
│ Version: 3.1                                                                                                                                                                                                  │
│ Error: 'NoneType' object cannot be interpreted as an integer                                                                                                                                                  │
│ Config: {'allow_nsfw': True, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'transition': 0.2, 'storymode': True, 'storymodemethod': 0, 'storymode_max_length': 100000, 'resolution_w': 1080,            │
│ 'resolution_h': 1920, 'background': {'background_choice': 'minecraft', 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96,                      │
│ 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'streamlabspolly', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_009',                 │
'tiktok_sessionid': 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                                                                                       
Traceback (most recent call last):
  File "C:\Users\NAME\Downloads\RedditVideoMakerBot-3.1\RedditVideoMakerBot-3.1\main.py", line 130, in <module>
    raise err
  File "C:\Users\NAME\Downloads\RedditVideoMakerBot-3.1\RedditVideoMakerBot-3.1\main.py", line 108, in <module>
    main(post_id)
  File "C:\Users\NAME\Downloads\RedditVideoMakerBot-3.1\RedditVideoMakerBot-3.1\main.py", line 56, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "C:\Users\NAME\Downloads\RedditVideoMakerBot-3.1\RedditVideoMakerBot-3.1\video_creation\final_video.py", line 198, in make_final_video
    for i in range(number_of_clips)
TypeError: 'NoneType' object cannot be interpreted as an integer

### Reproduction Steps

set storymode to true and storymode method to 0

### Expected behavior

video should be created as normal

### Screenshots

it isnt

### System Information

Operating System : Windows 11
Python version : 3.10
App version / Branch : latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by JasonLovesDoggo** [comment]
NumberOfClips = None

**Comment by electro199** [comment]
> NumberOfClips = None

I am adding fix to for this bug

**Comment by idriss3399** [comment]
i have this error can you help please 
Traceback (most recent call last):
  File "C:\Users\idris\Desktop\RedditVideoMakerBot-3.1\main.py", line 130, in <module>
    raise err
  File "C:\Users\idris\Desktop\RedditVideoMakerBot-3.1\main.py", line 111, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\idris\Desktop\RedditVideoMakerBot-3.1\main.py", line 64, in run_many
    main()
  File "C:\Users\idris\Desktop\RedditVideoMakerBot-3.1\main.py", line 54, in main
    download_background(bg_config)
  File "C:\Users\idris\Desktop\RedditVideoMakerBot-3.1\video_creation\background.py", line 77, in download_background
    ).first().download("assets/backgrounds", filename=f"{credit}-{filename}")
              ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'download'

**Comment by JasonLovesDoggo** [comment]
> i have this error can you help please 
> Traceback (most recent call last):
>   File "C:\Users\idris\Desktop\RedditVideoMakerBot-3.1\main.py", line 130, in <module>
>     raise err
>   File "C:\Users\idris\Desktop\RedditVideoMakerBot-3.1\main.py", line 111, in <module>
>     run_many(config["settings"]["times_to_run"])
>   File "C:\Users\idris\Desktop\RedditVideoMakerBot-3.1\main.py", line 64, in run_many
>     main()
>   File "C:\Users\idris\Desktop\RedditVideoMakerBot-3.1\main.py", line 54, in main
>     download_background(bg_config)
>   File "C:\Users\idris\Desktop\RedditVideoMakerBot-3.1\video_creation\background.py", line 77, in download_background
>     ).first().download("assets/backgrounds", filename=f"{credit}-{filename}")
>               ^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'download'

Download_background() returns successfully but .first() returns None

**Comment by electro199** [comment]
> Download_background() returns successfully but .first() returns None

Download can't find any video so it is empty first is returning None due to that.

**Comment by OpenSourceSimon** [comment]
Should be fixed, use a different post if you get this error again
