### ISSUE TITLE
[Feature]: Add main brazilian AI voice used for videos

### ISSUE THREAD

**Issue by randomuser1090** [elebumm/RedditVideoMakerBot#1623]
### Summary

Add main brazilian AI voice used for videos

### Is your feature request related to a problem?

The current male brazilian AI voice present in the bot is not very good and commit mistakes from time to time in the pronuncy

### Describe the solution you'd like

Add the main brazilian AI voice used for almost every video in brazilian portuguese. Here are 2 videos using the AI voice below:

https://www.tiktok.com/@ocaradoreddit/video/7204217096857799941

https://www.tiktok.com/@ocaradoreddit/video/7194178446975667462

How to add this voice? I'd like to learn how to do that. Can someone help?

**Comment by liamb13** [comment]
First try and find out what TTS is being used, once we know that we can work together to add it.

**Comment by randomuser1090** [comment]
This AI voice is available in a lot of text to speech websites

But one question: Would you need the API of the AI voice to add it into the bot? If yes, I think that's a problem. I searched for this API and I only found one website that provides it that is narakeet.com

Anyway, follows below some websites that contains this AI voice:

[Narakeet](https://www.narakeet.com)

![luciano](https://github.com/elebumm/RedditVideoMakerBot/assets/131568095/8c1ae034-6ad2-4270-a221-9dbffd48d98e)

![vasco](https://github.com/elebumm/RedditVideoMakerBot/assets/131568095/a9477511-c731-4a22-8d65-ed5da3a714e0)

I think it's Luciano or Vasco. Both AI voices are very good and I have seen them in a lot of videos.

This website provides the API with these AI voices but it costs per minute used

[Murf.ai](Murf.ai)

![Pedro](https://github.com/elebumm/RedditVideoMakerBot/assets/131568095/58b9f175-df02-4ca6-96d8-aedeec596c47)

It's Pedro

Murf.ai provides an API, but it's paid and only contains english voices

[aitextspeak](https://app.aitextspeak.com)

![Antonio](https://github.com/elebumm/RedditVideoMakerBot/assets/131568095/acf9904d-374a-45b9-923d-b97f8def13fb)

It's Antônio

I don't know if this website provides the API

I think narakeet is the best shot as it contains the API with the desired AI voices and it has Luciano and Vasco which are very good and well known AI voices. Can you add these AI voices knowing the website that provides them or would you need the API anyway?

**Comment by JasonLovesDoggo** [comment]
> But one question: Would you need the API of the AI voice to add it into the bot? If yes, I think that's a problem. I searched for this API and I only found one website that provides it that is narakeet.com

Yes. 

Reverse engineering a new api is quite difficult so if you would like this added, please open a PR.
