### ISSUE TITLE
[Bug]: Windows error 2 

### ISSUE THREAD

**Issue by MrTreeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee** [elebumm/RedditVideoMakerBot#1624]
### Describe the bug

I get [WinError 2] The system cannot find the file specified when trying to make the final video. I have identified it as line 127 in final_video.py `background_clip = ffmpeg.input(prepare_background(reddit_id, W=W, H=H))`

### Reproduction Steps

Run the script normaly

### Expected behavior

Create the final video

### System Information

Operating System : Windows 11
Python version : Python 3.10.11
App version / Branch : master V3.1

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by hzpapaz** [comment]
I have the same issue any solutions?

**Comment by FernandoPelarich** [comment]
i have same issue
