### ISSUE TITLE
[Bug]: Opacity feature does not work and isn't implemented

### ISSUE THREAD

**Issue by joshholly** [elebumm/RedditVideoMakerBot#1625]
### Describe the bug

I noticed there's an opacity setting, so I lowered it so people can see the video better and I noticed it didn't do anything. I searched through the code to see where opacity is referenced so I can fix it and I noticed the opacity setting isn't referenced anywhere. 

### Reproduction Steps

Set opacity to lower than 1, doesn't work

### Expected behavior

Lower the opacity.

### System Information

Operating System : MacOS Ventura
Python version : Python 3.10
App version / Branch : master (3.1)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by randomuser1090** [comment]
Indeed, I'm user and I confirm the opacity option is not working.

**Comment by joshholly** [comment]
I coded a solution that fixes it. Check the pull requests. :)
