### ISSUE TITLE
[Bug]: FFmpeg error with empty stderr log file.

### ISSUE THREAD

**Issue by Pestikoko1** [elebumm/RedditVideoMakerBot#1628]
### Describe the bug

Hi guys once again I have a problem with ffmpeg. First I uninstalled ffmpeg and installed ffmpeg-python, but it's still didn't work. Then I manually download the latest ffmpeg and even added it to the PATH. It still doesn't work, I printed out the stderr and it's  blank. What should I do?
![kép](https://user-images.githubusercontent.com/70532953/236947983-9d10b0c3-5fd1-405d-8710-1f6ba1dab5d4.png)
 
![kép](https://user-images.githubusercontent.com/70532953/236948134-5c82ac25-5957-42e5-aeec-82f278f339d3.png)
FFmpeg seems functional when I want to see it's version.

### Reproduction Steps

Already detailed

### Expected behavior

Last night I successfully rendered my first video after days of struggle with ffmpeg, after a good night's sleep I started my computer to see another error, but this time there is basically a blank stderr log. 

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Pestikoko1** [comment]
I also added FFmpeg folder to both system and user PATH in enviroment variables.

**Comment by shoaibch40** [comment]
The issue is already open here
https://github.com/elebumm/RedditVideoMakerBot/issues/1592
