### ISSUE TITLE
[Feature]:  "Fancier" method for Storymode

### ISSUE THREAD

**Issue by Tal-Dahann** [elebumm/RedditVideoMakerBot#1629]
### Summary

Sentences will be cut to 2-4 words, example below.

### Is your feature request related to a problem?

No, Its not

### Describe the solution you'd like

For more context, what i mean is to make a story video where each sentences is also cut to 2-4 words. The TTS will still read the whole sentence as it is (Because we want it to sound normal...) But the images of the subtitles on the screen will be much faster pace.

**Why do we need this?** if you look around tiktok for example, this is a common style that gets alot of views. This is because fast pace videos are more engaging and make the viewers more interested

For example for the sentence:
"My (17F) Sister (24F) is getting married in ...."

The video will look like shown in the pictures below.

### Additional Context

> Please ignore the fact that the font is super small, this ofc can be changed.

![image](https://user-images.githubusercontent.com/70545597/236957030-de9b9112-b14b-4727-9fdd-a026f50b5fe4.png)
![image](https://user-images.githubusercontent.com/70545597/236957069-89de9ed1-d648-4742-bd1b-bafed2be2481.png)
![image](https://user-images.githubusercontent.com/70545597/236957085-e9e86fcc-1f51-4847-b647-9a0554f24565.png)

**Comment by randomuser1090** [comment]
UP. I have the same request as well. The thing is O don't know how to code. Have you already seen transition effect between the captions? Follows a video below as example:

https://vm.tiktok.com/ZM2R3hD6X/?t=2

Look how engaging and entertaining this video is and the captions with its transition effect, font, pace plays a good role for this to happen

Is it possible to also increase the the font text size of the captions?

**Comment by randomuser1090** [comment]
will you create a pull request with the enhanced captions?

**Comment by zgauhar** [comment]
Hi,
Could you please create a pull request with your changes? I'm also looking for the same feature. Would be nice to have the following:
1. Adjust the font size
2. Post as screenshot
3. Comments as captions instead of screenshots

This format is quite common on the TikTok top trending videos.
I know a little bit about coding so I may be able to help if you're running into issues.

**Comment by idkonow** [comment]
this should definitely be a feature.

**Comment by Ayanokoujikiyo** [comment]
Please share the code or make a pull request as that would further improve the bot. Its a feature i've been working on as well but i just cant seem to make it work. Thank you in advance!
