### ISSUE TITLE
How do i change the subreddit?

### ISSUE THREAD

**Issue by Gamerblue619** [elebumm/RedditVideoMakerBot#163]

**Comment by jpmarques123** [comment]
In askreddit.py, change the value in this line to the name of the desired subreddit
`askreddit = reddit.subreddit("enter subreddit here")`

**Comment by binbohrawa** [comment]
Currently you can't, alternatively use @JasonLovesDoggo clone version which enable you to do so
here is the repo's link: [https://github.com/JasonLovesDoggo/RedditVideoMakerBot/](url)
