### ISSUE TITLE
[Bug]: why do i get this error  and yes I have restarted my pc

### ISSUE THREAD

**Issue by yungfresh1hub** [elebumm/RedditVideoMakerBot#1635]
### Describe the bug

i get this error when I start the python main.py, and yes I have restarted my PC. and FFmpeg is installed om my pc
FFmpeg is installed on this system! If you are seeing this error for the second time, restart your computer.

### Reproduction Steps

python main.py

### Expected behavior

i should work as normal

### Screenshots

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/125921680/7509f19a-6657-4e38-928b-0fde376a7b9c)

### System Information

Operating System : [e.g. Windows 10]
Python version : [e.g. Python 3.10.5]
App version / Branch : [latest,]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by praneet1001** [comment]
Facing kind of the similar issue ,it keeps asking me to install ffmpeg but i have it installed in my system

**Comment by Lachine1** [comment]
install it manually

**Comment by praneet1001** [comment]
> install it manually

did but it still showed the same thing well this was for the 3.1 version ,its not there in the 3.2 version but facing new issues for the 3.2 update
