### ISSUE TITLE
[Bug]: KeyError: 'streamingData'

### ISSUE THREAD

**Issue by facile93** [elebumm/RedditVideoMakerBot#1638]
### Describe the bug

https://youtu.be/hQx9VuIAaMc

### Reproduction Steps

juste started main.js

### Expected behavior

.

### Screenshots

![Capture](https://github.com/elebumm/RedditVideoMakerBot/assets/52578457/d32fcc75-a3c6-48e4-82c6-b2394af9a73d)

### System Information

Operating System : [e.g. Windows 10]
Python version : [e.g. Python 3.10.0]
App version / Branch : [RedditVideoMakerBot-3.1]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by facile93** [comment]
found the code error refer to :

    @property
    def streaming_data(self):
        """Return streamingData from video info."""
        if 'streamingData' in self.vid_info:
            return self.vid_info['streamingData']
        else:
            self.bypass_age_gate()
            return self.vid_info['streamingData']

way :
C:\Users\am465\AppData\Local\Programs\Python\Python310\Lib\site-packages\pytube

**Comment by Toretto99** [comment]
Hi, may I ask if you're using the latest release of this project?

**Comment by mathman14159** [comment]
I have the exact same bug on mine

**Comment by salemalem** [comment]
@Toretto99 yes latest pull

**Comment by Spit-fires** [comment]
exact issue here

**Comment by rsong0606** [comment]
@cosigyn the fix about  `Refactor request.stream()`? 
1. Is The commit not merged yet?
2. I tried to replace the entire code from https://github.com/pytube/pytube/blob/44b705e53e455b975107d0198bc2aa555ad7fad2/pytube/request.py still got the same error message.

Do you know if we have a solution soon? Thanks

**Comment by OpenSourceSimon** [comment]
This is fixed in the development branch and will soon be merged
