### ISSUE TITLE
[Bug]: Screenshot render does not fit inside the frame

### ISSUE THREAD

**Issue by v-pun215** [elebumm/RedditVideoMakerBot#1639]
### Describe the bug

Basically, I just wanted to make a short, and after filling out the config.toml, the render finishes up. But in the render the screenshot is not fully visible and is cropped. See:https://www.youtube.com/shorts/mIYsLa5pi4I

### Reproduction Steps

Nothing. Followed all steps on Python 3.10

### Expected behavior

It should look like the documented final_video.mp4

### System Information

Operating System : Windows 11
Python version : Python 3.10
App version / Branch : latest

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

Please fix soon. The video is fine ig but it isn't very ergonomic. Also, just remembered, the opacity feature doesn't work either. Do note I am on latest version of your project.

**Comment by v-pun215** [comment]
I know right?!!

**Comment by v-pun215** [comment]
In which python file?

**Comment by liamb13** [comment]
> In which python file?

https://github.com/elebumm/RedditVideoMakerBot/blob/master/video_creation/final_video.py#L178
