### ISSUE TITLE
[Bug]: 'NoneType' object has no attribute 'download'

### ISSUE THREAD

**Issue by idriss3399** [elebumm/RedditVideoMakerBot#1640]
### Describe the bug

Traceback (most recent call last):
  File "C:\Users\idris\Desktop\RedditVideoMakerBot-3.1\main.py", line 130, in <module>
    raise err
  File "C:\Users\idris\Desktop\RedditVideoMakerBot-3.1\main.py", line 111, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\idris\Desktop\RedditVideoMakerBot-3.1\main.py", line 64, in run_many
    main()
  File "C:\Users\idris\Desktop\RedditVideoMakerBot-3.1\main.py", line 54, in main
    download_background(bg_config)
  File "C:\Users\idris\Desktop\RedditVideoMakerBot-3.1\video_creation\background.py", line 77, in download_background
    ).first().download("assets/backgrounds", filename=f"{credit}-{filename}")
              ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'download'

### Reproduction Steps

this is my first time running it

### Expected behavior

it crashes 

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by v-pun215** [comment]
Which version of Python are you on?

**Comment by v-pun215** [comment]
If you're on Py 3.10, reinstall all the requirements. Also delete the config file. The program will ask you to fill out the config again.
If you're on Py 3.11(+), then try to downgrade to Py 3.10, otherwise replace the requirements file with this:
[requirements.txt](https://github.com/elebumm/RedditVideoMakerBot/files/11471070/requirements.txt)

**Comment by Dembe7** [comment]
I've got the same issue. Have you found a fix?

Thanks!

**Comment by v-pun215** [comment]
Just see what I wrote. If it ain't workin' then contact me.

**Comment by Dembe7** [comment]
I've tried that already, i will contact you. Thanks!

**Comment by Dembe7** [comment]
I've never directly message anyone here, can you please contact me?

**Comment by v-pun215** [comment]
Hey mate, just realized, and i'll report this as a bug, the error basically means that the program can't download the background video. So, I'll need you to download this video from youtube: https://www.youtube.com/watch?v=n_Dv4JMiwK8 . After doing that, rename the file to 'bbswitzer-parkour.mp4' and just place it in the folder 'backgrounds' in the assets folder. If there isn't any 'backgrounds' folder in there, then make one. That should hopefully fix the problem.

**Comment by Dembe7** [comment]
That worked!! Thank you legend!

**Comment by v-pun215** [comment]
No problem. Have fun!

**Comment by picerne-rgb** [comment]
> Ei amigo, acabei de perceber, e vou relatar isso como um bug, o erro basicamente significa que o programa não pode baixar o vídeo de fundo. Então, preciso que você baixe este vídeo do youtube: https://www.youtube.com/watch?v=n_Dv4JMiwK8 . Depois de fazer isso, renomeie o arquivo para 'bbswitzer-parkour.mp4' e apenas coloque-o na pasta 'backgrounds' na pasta assets. Se não houver nenhuma pasta 'planos de fundo' lá, crie uma. Isso deve resolver o problema.

Hey, i've just did it but the error still remain. 

 Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the       │
│ Discord community.                                                                                                  │
│ Version: 3.1                                                                                                        │
│ Error: 'NoneType' object has no attribute 'download'                                                                │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'transition': 0.2, 'storymode':   │
│ False, 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920,              │
│ 'background': {'background_choice': 'minecraft', 'background_thumbnail': False, 'background_thumbnail_font_family': │
│ 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts':            │
│ {'voice_choice': 'tiktok', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice':       │
│ 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice': 'tiktok_sessionid', 'py_voice_num': 'return',          │
│ 'silence_duration': 0.3, 'no_emojis': False}}                                                                       │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "E:\Downloads\RedditVideoMakerBot-3.1\main.py", line 130, in <module>
    raise err
  File "E:\Downloads\RedditVideoMakerBot-3.1\main.py", line 111, in <module>
    run_many(config["settings"]["times_to_run"])
  File "E:\Downloads\RedditVideoMakerBot-3.1\main.py", line 64, in run_many
    main()
  File "E:\Downloads\RedditVideoMakerBot-3.1\main.py", line 54, in main
    download_background(bg_config)
  File "E:\Downloads\RedditVideoMakerBot-3.1\video_creation\background.py", line 77, in download_background
    ).first().download("assets/backgrounds", filename=f"{credit}-{filename}")
              ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'download'

Any other things to do? I'm using Python version 3.11, but everything is set up correctly as you said.

**Comment by s0und1** [comment]
@v-pun215 could you please check out my error? It is kind of similar to this one but instead of 'NoneType' object has no attribute 'download', I get : TypeError: 'NoneType' object cannot be interpreted as an integer
Here's the detailed report -> https://github.com/elebumm/RedditVideoMakerBot/issues/1665
Thanks <3
