### ISSUE TITLE
[Bug]: Can't configure bot | Stuck at 'Thanks for using this tool!'

### ISSUE THREAD

**Issue by forkbabu** [elebumm/RedditVideoMakerBot#1642]
### Describe the bug

This is on the configuration step: python3 main.py

Using Colab with GPU (T4).

Followed Steps 1 to 3 individually (without the install.sh trick)

### Reproduction Steps

python3 main.py for the first time

### Expected behavior

Stuck at 'Thanks...'

### Screenshots

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/8037297/56d83179-25a7-4283-9135-90b0bff95a57)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

@elebumm cc

**Comment by OpenSourceSimon** [comment]
Google Collab isn't supported
