### ISSUE TITLE
[Bug]: I can not download background/use a video in the backgrounds folder

### ISSUE THREAD

**Issue by hzpapaz** [elebumm/RedditVideoMakerBot#1643]
### Describe the bug

The bot does everthing as it should until the background part. I tried GTA5, Minecraft and Rocket-league and only rocket league works for me. I manually downloaded the Minecraft parkour video and renamed it accordingly but it doesnt work either. The bot doesn't automaticly downloads the videos and when I provide the videos it doesn't work.

### Reproduction Steps

Just started the bot.

### Expected behavior

It should download the videos and use them.

### Screenshots

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the       │
│ Discord community.                                                                                                  │
│ Version: 3.1                                                                                                        │
│ Error: MoviePy error: the file assets/backgrounds/bbswitzer-parkour.mp4 could not be found!                         │
│ Please check that you entered the correct path.                                                                     │
│ Config: {'allow_nsfw': True, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'transition': 0.2, 'storymode':    │
│ False, 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920,              │
│ 'background': {'background_choice': 'minecraft', 'background_thumbnail': False, 'background_thumbnail_font_family': │
│ 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts':            │
│ {'voice_choice': 'tiktok', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice':       │
│ 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3,     │
│ 'no_emojis': False}}                                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "C:\Users\Mete Kaan Bal\Downloads\Compressed\RedditVideoMakerBot-3.1\main.py", line 129, in <module>
    raise err
  File "C:\Users\Mete Kaan Bal\Downloads\Compressed\RedditVideoMakerBot-3.1\main.py", line 110, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\Mete Kaan Bal\Downloads\Compressed\RedditVideoMakerBot-3.1\main.py", line 64, in run_many
    main()
  File "C:\Users\Mete Kaan Bal\Downloads\Compressed\RedditVideoMakerBot-3.1\main.py", line 55, in main
    chop_background_video(bg_config, length, reddit_object)
  File "C:\Users\Mete Kaan Bal\Downloads\Compressed\RedditVideoMakerBot-3.1\video_creation\background.py", line 103, in chop_background_video
    background = VideoFileClip(f"assets/backgrounds/{choice}")
  File "C:\Users\Mete Kaan Bal\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "C:\Users\Mete Kaan Bal\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 35, in __init__
    infos = ffmpeg_parse_infos(filename, print_infos, check_duration,
  File "C:\Users\Mete Kaan Bal\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 270, in ffmpeg_parse_infos
    raise IOError(("MoviePy error: the file %s could not be found!\n"
OSError: MoviePy error: the file assets/backgrounds/bbswitzer-parkour.mp4 could not be found!
Please check that you entered the correct path.

### System Information

Operating System : [e.g. Windows 10]
Python version : [e.g. Python 3.10]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by hzpapaz** [comment]
> Having the same exact problem here. Running the same config.
> 
> My error:
> 
> ```
> Downloading the backgrounds videos... please be patient 🙏
> Downloading parkour.mp4 from https://www.youtube.com/watch?v=n_Dv4JMiwK8
> ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
> │ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the       │
> │ Discord community.                                                                                                  │
> │ Version: 3.1                                                                                                        │
> │ Error: 'streamingData'                                                                                              │
> │ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'transition': 0.2, 'storymode':   │
> │ False, 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920,              │
> │ 'background': {'background_choice': 'minecraft', 'background_thumbnail': False, 'background_thumbnail_font_family': │
> │ 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts':            │
> │ {'voice_choice': 'tiktok', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice':       │
> │ 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3,     │
> │ 'no_emojis': False}}                                                                                                │
> └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
> Traceback (most recent call last):
>   File "C:\Users\admin\Desktop\RedditVideoMakerBot-master\main.py", line 130, in <module>
>     raise err
>   File "C:\Users\admin\Desktop\RedditVideoMakerBot-master\main.py", line 111, in <module>
>     run_many(config["settings"]["times_to_run"])
>   File "C:\Users\admin\Desktop\RedditVideoMakerBot-master\main.py", line 64, in run_many
>     main()
>   File "C:\Users\admin\Desktop\RedditVideoMakerBot-master\main.py", line 54, in main
>     download_background(bg_config)
>   File "C:\Users\admin\Desktop\RedditVideoMakerBot-master\video_creation\background.py", line 75, in download_background    YouTube(uri, on_progress_callback=on_progress).streams.filter(
>   File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 296, in streams
>     return StreamQuery(self.fmt_streams)
>   File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 176, in fmt_streams
>     stream_manifest = extract.apply_descrambler(self.streaming_data)
>   File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 161, in streaming_data
>     return self.vid_info['streamingData']
> KeyError: 'streamingData'
> ```

Your error can be solved in #1638

**Comment by grannymaster** [comment]
I'm not sure how is that going to help me. I cloned the repository after that commit occurred.

**Comment by newtoallofthis123** [comment]
Most likely due to the out dated version of pytube...but it seems to be quite dependent on the version of pytube.

I tried updating it to pytube3 or pytube 15.0, but it gives me too many errors

**Comment by OpenSourceSimon** [comment]
Fixed in 3.2
