### ISSUE TITLE
[Feature]: GPU Acceleration

### ISSUE THREAD

**Issue by ItzDatMC** [elebumm/RedditVideoMakerBot#1654]
### Summary

GPU Acceleration when creating video

### Is your feature request related to a problem?

Not exactly a problem, but I've noticed that whenever the bot create the video, it mainly uses the CPU instead of the GPU. From what I know GPU acceleration would help in rendering videos and make the process faster. 

### Describe the solution you'd like

GPU acceleration when creating videos to speed up the process.

**Comment by liamb13** [comment]
While GPU acceleration may speed up the process times for some users, it might not be great for all.

For HW Acceleration in FFMPEG, we have to specifically set the type to use and it may create more headaches than it's worth.

> But: Be careful and do some benchmarking. While GPU-encoders should be very fast, they are also worse than CPU ones in comparison to visual quality.

https://stackoverflow.com/questions/44510765/gpu-accelerated-video-processing-with-ffmpeg

**Comment by JasonLovesDoggo** [comment]
this is not something we can currently support as moviepy does not.
