### ISSUE TITLE
[Bug]: FileNotFoundError: [Errno 2] No such file or directory: './utils/backgrounds.json'

### ISSUE THREAD

**Issue by chvisto** [elebumm/RedditVideoMakerBot#1662]
### Describe the bug

It shows FileNotFoundError: [Errno 2] No such file or directory: './utils/backgrounds.json'.
I have checked and i am currently running python 3.10.11

please help

### Reproduction Steps

run main.py

### Expected behavior

i expected it to work

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by liamb13** [comment]
@chrizzztooooo can you check the file is actually there?

If not, copy it over from: https://github.com/elebumm/RedditVideoMakerBot/blob/master/utils/backgrounds.json

**Comment by chrizzztooooo** [comment]
> @chrizzztooooo can you check the file is actually there?
> 
> If not, copy it over from: https://github.com/elebumm/RedditVideoMakerBot/blob/master/utils/backgrounds.json

The file exists. Now instead of keeping it as relative path,I pasted the entire file path.
Thank you!

**Comment by liamb13** [comment]
Great! Please feel free to close the issue

**Comment by s0und1** [comment]
@liamb13 could you throw an eye over my issue? I would appreciate it a lot if you could help or give any tips :)
https://github.com/elebumm/RedditVideoMakerBot/issues/1665
