### ISSUE TITLE
[Bug]: TypeError: 'NoneType' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by s0und1** [elebumm/RedditVideoMakerBot#1665]
### Describe the bug

After generating some videos, it will eventually break at the final stage of "Creating the final video"

 Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the       
│ Discord community.                                                                                               
│ Version: 3.1                                                                                                    
│ Error: 'NoneType' object cannot be interpreted as an integer                                                      
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'transition': 0.2, 'storymode':   
│ False, 'storymodemethod': 1, 'storymode_max_length': 500, 'resolution_w': 1080, 'resolution_h': 1920, 'background': 
│ {'background_choice': 'minecraft', 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',      
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice':    
│ 'streamlabspolly', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001',  
│ 'tiktok_sessionid': 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis':   
│ False}}

Traceback (most recent call last):
  File "C:\Users\crist\Desktop\RedditVideoMakerBot-3.1haid\main.py", line 130, in <module>
    raise err
  File "C:\Users\crist\Desktop\RedditVideoMakerBot-3.1haid\main.py", line 111, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\crist\Desktop\RedditVideoMakerBot-3.1haid\main.py", line 64, in run_many
    main()
  File "C:\Users\crist\Desktop\RedditVideoMakerBot-3.1haid\main.py", line 56, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "C:\Users\crist\Desktop\RedditVideoMakerBot-3.1haid\video_creation\final_video.py", line 151, in make_final_video
    for i in range(number_of_clips)
TypeError: 'NoneType' object cannot be interpreted as an integer

### Reproduction Steps

-> Open up cmd in the bot folder
-> typed "python main.py"
-> everything worked smoothly until the last stage "Creating the final video"
-> got hit by that error

### Expected behavior

-> finish creating the final video 

### Screenshots

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/96007393/012b2b8c-6026-499d-bcda-bb30dc3c9df2)
![image](https://github.com/elebumm/RedditVideoMakerBot/assets/96007393/7eb3e8ff-d4e5-4124-be68-6b76a408ecf2)

### System Information

Operating System : [Windows 10]
Python version : [e.g. Python 3.10.0]
App version / Branch : [latest]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

If I go ahead and just reinstall the program it will work smoothly for 2-3 videos but after that it will break again and I'll need to reinstall it all over again and blah blah...
The bot works but breaks after some generations and it's kind of annoying to keep reinstalling it over and over especially when the generated amount of videos before it crashes is small (usually 2-3 max).
Any ideas?

**Comment by liamb13** [comment]
Can you share your config file? Seems the problem is occurring specifically due to your times_to_run value

**Comment by s0und1** [comment]
@liamb13 it is shown in the second screenshot or, 3rd paragraph from top to bottom

**Comment by liamb13** [comment]
I'm not sure if it's the perfect solution, however, when I need to do this;
- In videos.json, duplicate the last video that succeed
- Replace the id with the post to skip and it'll skip it
