### ISSUE TITLE
[Bug]: Failed at downloading background video

### ISSUE THREAD

**Issue by theboyulove** [elebumm/RedditVideoMakerBot#1666]
### Describe the bug

I stuck at this step as follow :

Downloading the backgrounds videos... please be patient 🙏
Downloading parkour.mp4 from https://www.youtube.com/watch?v=n_Dv4JMiwK8
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the        │
│ Discord community.                                                                                                   │
│ Version: 3.1                                                                                                         │
│ Error: 'streamingData'                                                                                               │
│ Config: {'allow_nsfw': True, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'transition': 0.2, 'storymode':     │
│ False, 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'background': │
│ {'background_choice': 'minecraft', 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',       │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice':     │
│ 'tiktok', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001',            │
│ 'tiktok_sessionid': 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis':      │
│ False}}                                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "C:\Users\84909\RedditVideoMakerBot\main.py", line 130, in <module>
    raise err
  File "C:\Users\84909\RedditVideoMakerBot\main.py", line 111, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\84909\RedditVideoMakerBot\main.py", line 64, in run_many
    main()
  File "C:\Users\84909\RedditVideoMakerBot\main.py", line 54, in main
    download_background(bg_config)
  File "C:\Users\84909\RedditVideoMakerBot\video_creation\background.py", line 75, in download_background
    YouTube(uri, on_progress_callback=on_progress).streams.filter(
  File "C:\Users\84909\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\84909\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "C:\Users\84909\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'

### Reproduction Steps

I run the main.py

### Expected behavior

As said above, the problem is as follow :

Downloading the backgrounds videos... please be patient 🙏
Downloading parkour.mp4 from https://www.youtube.com/watch?v=n_Dv4JMiwK8
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the        │
│ Discord community.                                                                                                   │
│ Version: 3.1                                                                                                         │
│ Error: 'streamingData'                                                                                               │
│ Config: {'allow_nsfw': True, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'transition': 0.2, 'storymode':     │
│ False, 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'background': │
│ {'background_choice': 'minecraft', 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',       │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice':     │
│ 'tiktok', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001',            │
│ 'tiktok_sessionid': 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis':      │
│ False}}                                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "C:\Users\84909\RedditVideoMakerBot\main.py", line 130, in <module>
    raise err
  File "C:\Users\84909\RedditVideoMakerBot\main.py", line 111, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\84909\RedditVideoMakerBot\main.py", line 64, in run_many
    main()
  File "C:\Users\84909\RedditVideoMakerBot\main.py", line 54, in main
    download_background(bg_config)
  File "C:\Users\84909\RedditVideoMakerBot\video_creation\background.py", line 75, in download_background
    YouTube(uri, on_progress_callback=on_progress).streams.filter(
  File "C:\Users\84909\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\84909\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "C:\Users\84909\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'

### System Information

Operating System :  Windows 11
Python version : Python 3.10
App version / Branch : Reddit Video Maker Bot 3.1

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by theboyulove** [comment]
I have tried to use youtube4mp4 and download the video at that youtube link, save to parkour.mp4 inside the RedditVideoMakerBot\assets\backgrounds, but the problem still persists

**Comment by SebiCoroian** [comment]
save it as "bbswitzer-parkour.mp4"

**Comment by zgauhar** [comment]
Switching to develop branch fixes a number of issues including this one.

**Comment by Mawinofii** [comment]
> Switching to develop branch fixes a number of issues including this one.

how do we do so?

**Comment by zgauhar** [comment]
You can do that by writing 
'git checkout develop' on command line or follow this link https://devconnected.com/how-to-switch-branch-on-git/.
If you don't have git installed or are not comfortable with command line, you can follow this link and redownload the correct branch.
https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/managing-branches-in-github-desktop

**Comment by electro199** [comment]
fixed
#1607
