### ISSUE TITLE
[Bug]: Transition and silence duration does not work

### ISSUE THREAD

**Issue by zgauhar** [elebumm/RedditVideoMakerBot#1668]
### Describe the bug

The transition and silence settings don't have any effects no matter what value I use.

### Reproduction Steps

Make a video with different settings and there won't be any difference.

### Expected behavior

I would like the ability to set a pause between comments so that listeners know when a comment ends and when the next one begins.

### System Information

Operating System : Win 10
Python version : Python 3.10.6
App version / Branch : develop

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

The issue was already opened on April 17 but was closed due to being stale. I understand that the maintainers might have more important work on their plates, so even a slight nudge in the right direction would help in fixing this.

**Comment by electro199** [comment]
transition removed and opacity fixed in new version

**Comment by zgauhar** [comment]
Is that merged into master or still in develop branch?

**Comment by zgauhar** [comment]
And any fix for the silence duration?

**Comment by electro199** [comment]
it is merged into master branch
