### ISSUE TITLE
REQUEST changing the name of the output file

### ISSUE THREAD

**Issue by reinkdesigns** [elebumm/RedditVideoMakerBot#167]
how would i go and change the name of the output file to match the title of the reddit post

**Comment by reinkdesigns** [comment]
![image](https://user-images.githubusercontent.com/104669790/171735931-04fb43f8-0e3e-480e-93a6-35f0335b4d83.png)

i see the script already knows what the post title is, so i have to imagine its not to hard to take that and assign it to the output file?

**Comment by reoccurcat** [comment]
I have created an edit that will make the final video's name the Reddit thread title.
You can try it out on my fork: https://github.com/reoccurcat/RedditVideoMakerBot/tree/final_video_name_test
There's probably enough demand that I could get a PR started to merge this into master to be honest.

**Comment by reoccurcat** [comment]
> i will take a look, was i on the right track by chance?

Yeah, you just took a little bit more complicated way of doing it, instead of just `return`ing the name from the function that gets the subreddit. 
I'm going to push another commit pretty soon that will fix a lot more of the windows path issues with the characters though, because so far mine just strips off the question mark that's usually at the end

**Comment by reinkdesigns** [comment]
yea i figured there was an easier way to do it, i just didnt know how

**Comment by reoccurcat** [comment]
I just pushed a commit that sanitizes the filename a bit better.

**Comment by reinkdesigns** [comment]
ok cool, how do i download a commit?

**Comment by reoccurcat** [comment]
You probably haven't installed yt-dlp yet, run `pip install yt-dlp`
It got introduced in a new commit recently

**Comment by Kamushy** [comment]
i've sovled this in a faster way with #139

**Comment by Kamushy** [comment]
Now in master branch, this issue can be closed @CallumIO @reinkdesigns
