### ISSUE TITLE
[Feature]: Non-API Reliant Version

### ISSUE THREAD

**Issue by joshholly** [elebumm/RedditVideoMakerBot#1679]
### Summary

Reddit to be charging arm/leg for API access - Need video bot to run completely on playwright

### Is your feature request related to a problem?

So according to this article, reddit is going to be killing API access/charging an arm/leg for it.

https://www.androidpolice.com/reddit-kill-third-party-clients-unreasonable-fees/

We need the bot to be re-written to run entirely on playwright / selenium. If we can already grab screenshots, certainly we can also grab the text from reddit threads to do TTS instead of pulling from the API, no? Because once they start killing API access, most of us don't have the money to afford the arm/leg that Reddit will be charging. 

### Describe the solution you'd like

Reddit bot to not rely on an API but instead Playwright, Selenium, or pupiteer.

**Comment by OpenSourceSimon** [comment]
They won't completely remove API access. After a certain amount of usage, it'll be paid. 

We won't scrape the post, and we'll continue to use the official API. Scraping is against their ToS.
