### ISSUE TITLE
[Bug]:  Error: 'silence_duration'

### ISSUE THREAD

**Issue by peerguy29** [elebumm/RedditVideoMakerBot#1684]
### Describe the bug

i keep getting this error and don't know how to fix it

### Reproduction Steps

i started the cmd, put in python main.py and hit enter

### Expected behavior

the program starts making the video

### Screenshots

![code](https://github.com/elebumm/RedditVideoMakerBot/assets/135548653/79c4e552-8ace-4839-9308-fa93932b7edb)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.10.0]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by FreeZZiX** [comment]
Go in the folder utils (in the reddit bot folder) and open .config.template.toml, go on line 56 and remove the # before silence_duration

**Comment by Subset28** [comment]
I have the same issue, but I don't know how to fix it because there is no line 56 for the new version

**Comment by FreeZZiX** [comment]
> I have the same issue, but I don't know how to fix it because there is no line 56 for the new version

I don’t have my pc to try but in the same file, try CTRL + F to find silence_duration
