### ISSUE TITLE
[Bug]: Main.py crashes 

### ISSUE THREAD

**Issue by Schmandmann223** [elebumm/RedditVideoMakerBot#1685]
### Describe the bug

It crashes after few seconds in this screen https://prnt.sc/ngbAAXW8sN0w

Reproduction Steps
i follow the steps and when i click Main.py it happens

### Reproduction Steps

https://prnt.sc/ngbAAXW8sN0w

### Expected behavior

crashes

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by devrhis** [comment]
Go in the folder utils (in the reddit bot folder) and open .config.template.toml, go on line 56 and remove the # before silence_duration
