### ISSUE TITLE
[Bug]: Invalid Credentials

### ISSUE THREAD

**Issue by joshholly** [elebumm/RedditVideoMakerBot#1687]
### Describe the bug

I am using the same password I always used, and now it's saying Invalid Credentials. I tried logging in manually and my username/password still works and I have not changed it. 

### Reproduction Steps

Launch bot with main.py

### Expected behavior

Log in and work

### System Information

Operating System : MacOS Ventura 13.4
Python version : Python 3.10
App version / Branch : Latest (3.2)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by joshholly** [comment]
Annnd it started working again. That was weird.

**Comment by joshholly** [comment]
I am still experiencing errors. It's not grabbing the screenshots right.

**Comment by joshholly** [comment]
UPDATE: Yeah, it's either not grabbing the screenshots, or saying invalid credentials. Basically, reddit is not working at all with the python bot. But it works just fine for me on  my browser.

**Comment by moaviyah** [comment]
I am getting the same error. The bot ran for first 2 times and then started throwing this error: 
 I**nvalid credentials**
  Please check your credentials in the config.toml file

**Comment by d1eg0v** [comment]
I'm having the same issue. I've also tried changing my password and still get "Invalid Credentials".

**Comment by anttad** [comment]
I'm having the same issue, any update ? please repopen the Issue as it's clearly not fixed

**Comment by Tiramisu33** [comment]
I'm having the same issue, any update ? please repopen the Issue as it's clearly not fixed
