### ISSUE TITLE
[Bug]: I honestly dont know whats wrong Im really new to Python please help

### ISSUE THREAD

**Issue by PleaseLookAway** [elebumm/RedditVideoMakerBot#1689]
### Describe the bug

every time i open main.py this shows up and closes immidiately
![Screenshot (4)](https://github.com/elebumm/RedditVideoMakerBot/assets/135764871/7b97a6cf-ce0f-4df3-acdd-dea6bc02f05f)

### Reproduction Steps

I DONT KNOW 

### Expected behavior

WHGAT

### System Information

IM ON PYTHON 3.10 and WINDOWS 10 THATS ALL I KNOW

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by PleaseLookAway** [comment]
Thanks if anyone can actually help with this

**Comment by MahiRavanKRG** [comment]
Heyy man,

I don't exactly see whats wrong with this but lets try.

I would suggest that delete the entire project and clone it again.

If it still dosen't work then we can work on this again.
