### ISSUE TITLE
UnboundLocalError: local variable 'idx' referenced before assignment

### ISSUE THREAD

**Issue by reinkdesigns** [elebumm/RedditVideoMakerBot#169]
![image](https://user-images.githubusercontent.com/104669790/171735162-0870f194-2cae-4976-af9b-6459876c82c7.png)

**Comment by ishaw18** [comment]
I am also getting this issue occaisonaly

**Comment by jmanny1** [comment]
Does anyone know why is this Happens? or how to fix it?
