### ISSUE TITLE
[Bug]: cant run

### ISSUE THREAD

**Issue by JupiterUwU** [elebumm/RedditVideoMakerBot#1691]
### Describe the bug

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/124474143/f18be724-a063-42cb-91d2-281e76777bc5)

### Reproduction Steps

im not too sure but i just am unable to run it.

### Expected behavior

idk what to put here other than i expected for it to work like i was told it would.

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by MahiRavanKRG** [comment]
Hey man You there?

I ran into the same problem I think I can help you

![explorer_FNYQs1FT0g](https://github.com/elebumm/RedditVideoMakerBot/assets/94435007/67d51876-faec-4ffc-80fd-19d4dcb3a552)

> first find this "config.toml" file.

> then change ⬇️ this 'voice_choice = "tiktok" ' to "elevenlabs"
![Code_1dW0r7Pkzc](https://github.com/elebumm/RedditVideoMakerBot/assets/94435007/b840c24b-1c8b-4ce5-990c-9c7de367233d)

> then you will need a elevenlabs api key in the apikey variable

if you follow this and watch carefully then you can easily reun this as I think the error was from the server.

Now, if this dosen't work then just comment back.

**Comment by codeadvance** [comment]
Hi @MahiRavanKRG 

I am facing the similar issues as @JupiterUwU . I replaced the texts as you suggested and still facing errors as follows.

Here are the errors:
sing subreddit: r/AskReddit+hotelexperience from TOML config
NSFW Post Detected. Skipping...
NSFW Post Detected. Skipping...
Video will be: If you were to die within a few minutes, what is the last thing you said to a person you care about? 👍
Thread url is: https://reddit.com/r/AskReddit/comments/14ofnij/if_you_were_to_die_within_a_few_minutes_what_is/ 👍
Thread has 3377 upvotes
Thread has a upvote ratio of 92.0%
Thread has 3180 comments
Received subreddit threads Successfully.
Thread ID is 14ofnij
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Saving Text to MP3 files...                                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord  │
│ community.                                                                                                             │
│ Version: 3.2                                                                                                           │
│ Error: Code: 1, reason: probably the aid value isn't correct, message: Couldn't load speech. Try again.                │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False,                  │
│ 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0,           │
│ 'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15,           │
│ 'enable_extra_audio': False, 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',               │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice':       │
│ 'tiktok', 'random_voice': True, 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': │
│ 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED',           │
│ 'python_voice': '1', 'py_voice_num': 'u', 'silence_duration': 0.3, 'no_emojis': False}}                                │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "/Users/obossmon/Desktop/RedditVideoMakerBot/main.py", line 136, in <module>
    raise err
  File "/Users/obossmon/Desktop/RedditVideoMakerBot/main.py", line 118, in <module>
    run_many(config["settings"]["times_to_run"])
  File "/Users/obossmon/Desktop/RedditVideoMakerBot/main.py", line 73, in run_many
    main()
  File "/Users/obossmon/Desktop/RedditVideoMakerBot/main.py", line 55, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "/Users/obossmon/Desktop/RedditVideoMakerBot/video_creation/voices.py", line 53, in save_text_to_mp3
    return text_to_mp3.run()
obossmon@OBoSsMoNs-Mac-Studio RedditVideoMakerBot % /usr/local/bi
n/python3.10 /Users/obossmon/Desktop/RedditVideoMakerBot/main.py
Using region Ontario server backend.


██████╗ ███████╗██████╗ ██████╗ ██╗████████╗    ██╗   ██╗██╗██████╗ ███████╗ ██████╗     ███╗   ███╗ █████╗ ██╗  ██╗███████╗██████╗
██╔══██╗██╔════╝██╔══██╗██╔══██╗██║╚══██╔══╝    ██║   ██║██║██╔══██╗██╔════╝██╔═══██╗    ████╗ ████║██╔══██╗██║ ██╔╝██╔════╝██╔══██╗
██████╔╝█████╗  ██║  ██║██║  ██║██║   ██║       ██║   ██║██║██║  ██║█████╗  ██║   ██║    ██╔████╔██║███████║█████╔╝ █████╗  ██████╔╝
██╔══██╗██╔══╝  ██║  ██║██║  ██║██║   ██║       ╚██╗ ██╔╝██║██║  ██║██╔══╝  ██║   ██║    ██║╚██╔╝██║██╔══██║██╔═██╗ ██╔══╝  ██╔══██╗
██║  ██║███████╗██████╔╝██████╔╝██║   ██║        ╚████╔╝ ██║██████╔╝███████╗╚██████╔╝    ██║ ╚═╝ ██║██║  ██║██║  ██╗███████╗██║  ██║
╚═╝  ╚═╝╚══════╝╚═════╝ ╚═════╝ ╚═╝   ╚═╝         ╚═══╝  ╚═╝╚═════╝ ╚══════╝ ╚═════╝     ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

                                                                 
                                                                 
   Thanks for using this tool! Feel free to contribute to this   
   project on GitHub! If you have any questions, feel free to    
  join my Discord server or submit a GitHub issue. You can find  
     solutions to many common problems in the documentation:     
           https://reddit-video-maker-bot.netlify.app/           
                                                                 
                                                                 
╭───────────────────────────────────────────────────────────────╮
│ You are using the newest version (3.2) of the bot             │
╰───────────────────────────────────────────────────────────────╯
###############################
#                             #
# Checking TOML configuration #
#                             #
###############################
If you see any prompts, that means that you have 
unset/incorrectly set variables, please input the correct values.
╭───────────────────────────────────────────────────────────────╮
│ on the 1st iteration of 1                                     │
╰───────────────────────────────────────────────────────────────╯
Logging into Reddit.
╭───────────────────────────────────────────────────────────────╮
│ Getting subreddit threads...                                  │
╰───────────────────────────────────────────────────────────────╯
Using subreddit: r/AskReddit+hotelexperience from TOML config
NSFW Post Detected. Skipping...
Video will be: What just kinda disappeared without people 
noticing? 👍
Thread url is: 
https://reddit.com/r/AskReddit/comments/14oscyx/what_just_kinda_d
isappeared_without_people/ 👍
Thread has 1000 upvotes
Thread has a upvote ratio of 96.0%
Thread has 2051 comments
Received subreddit threads Successfully.
Thread ID is 14oscyx
╭───────────────────────────────────────────────────────────────╮
│ Saving Text to MP3 files...                                   │
╰───────────────────────────────────────────────────────────────╯
Saving... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   
╭───────────────────────────────────────────────────────────────╮
│ Sorry, something went wrong with this version! Try again, and │
│ feel free to report this issue at GitHub or the Discord       │
│ community.                                                    │
│ Version: 3.2                                                  │
│ Error: No tasks booked (tried to start task                   │
│ 909a2dd378334bf28a6349b2eea6143e). Please first book a task   │
│ before execution. (Also ensure you start the task within the  │
│ initiation deadline)                                          │
│ Config: {'allow_nsfw': False, 'theme': 'dark',                │
│ 'times_to_run': 1, 'opacity': 0.9, 'storymode': False,        │
│ 'storymodemethod': 1, 'storymode_max_length': 1000,           │
│ 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0,      │
│ 'background': {'background_video': 'minecraft',               │
│ 'background_audio': 'lofi', 'background_audio_volume': 0.15,  │
│ 'enable_extra_audio': False, 'background_thumbnail': False,   │
│ 'background_thumbnail_font_family': 'arial',                  │
│ 'background_thumbnail_font_size': 96,                         │
│ 'background_thumbnail_font_color': '255,255,255'}, 'tts':     │
│ {'voice_choice': 'elevenlabs', 'random_voice': True,          │
│ 'elevenlabs_voice_name': 'Adam', 'elevenlabs_api_key':        │
│ 'REDACTED', 'aws_polly_voice': 'Matthew',                     │
│ 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice':          │
│ 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice':  │
│ '1', 'py_voice_num': 'u', 'silence_duration': 0.3,            │
│ 'no_emojis': False}}                                          │
╰───────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "/Users/obossmon/Desktop/RedditVideoMakerBot/main.py", line 136, in <module>
    raise err
  File "/Users/obossmon/Desktop/RedditVideoMakerBot/main.py", line 118, in <module>
    run_many(config["settings"]["times_to_run"])
  File "/Users/obossmon/Desktop/RedditVideoMakerBot/main.py", line 73, in run_many
    main()
  File "/Users/obossmon/Desktop/RedditVideoMakerBot/main.py", line 55, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "/Users/obossmon/Desktop/RedditVideoMakerBot/video_creation/voices.py", line 53, in save_text_to_mp3
    return text_to_mp3.run()
  File "/Users/obossmon/Desktop/RedditVideoMakerBot/TTS/engine_wrapper.py", line 107, in run
    self.call_tts(f"{idx}", process_text(comment["comment_body"]))
  File "/Users/obossmon/Desktop/RedditVideoMakerBot/TTS/engine_wrapper.py", line 154, in call_tts
    self.tts_module.run(
  File "/Users/obossmon/Desktop/RedditVideoMakerBot/TTS/elevenlabs.py", line 40, in run
    audio = generate(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/elevenlabs/simple.py", line 126, in generate
    return TTS.generate(text, voice, model, api_key=api_key)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/elevenlabs/api/tts.py", line 21, in generate
    response = API.post(url, json=data, api_key=api_key)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/elevenlabs/api/base.py", line 65, in post
    return API.request(url, method="post", *args, **kwargs)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/elevenlabs/api/base.py", line 57, in request
    raise APIError(error)
elevenlabs.api.error.APIError: No tasks booked (tried to start task 909a2dd378334bf28a6349b2eea6143e). Please first book a task before execution. (Also ensure you start the task within the initiation deadline)
<img width="1749" alt="Screenshot 2023-07-02 at 3 35 56 PM" src="https://github.com/elebumm/RedditVideoMakerBot/assets/132302205/e5e711e3-af83-44b6-a60a-0f14d0393edd">

**Comment by MahiRavanKRG** [comment]
Man I understood nicely, nice comments and you also pasted errors. I am sure my friend electro can help 
@electro199 please help us with these errors
