### ISSUE TITLE
[Bug]: the random voice not accepting true or false and

### ISSUE THREAD

**Issue by spy1345a** [elebumm/RedditVideoMakerBot#1695]
### Describe the bug

When ever i start the main.py file it runs and saya the random voice is a unexpected keyword 

### Reproduction Steps

Can you fix it

### Expected behavior

Should work

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.10]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by t0masGutierrez** [comment]
same problem
