### ISSUE TITLE
Issue with AWS returning (Validation Exception)

### ISSUE THREAD

**Issue by xdddder** [elebumm/RedditVideoMakerBot#1708]
### Describe the bug

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/136836053/59b8ba8a-f271-4d7d-a3d2-c27d649dd191)
 Returns this error when creating using aws polly accessed using a free trial aws account. 

### Reproduction Steps

Configuring TTS using awspolly, "Matthew"

### Expected behavior

Audio to be converted to mp3

### System Information

Operating System : [Windows 10]
Python version : [Python 3.10]
App version / Branch : [master]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by xdddder** [comment]
Just need to update this part to "standard" in the awspolly code.
![Capture](https://github.com/elebumm/RedditVideoMakerBot/assets/136836053/d924c54d-c5c8-4392-b508-0f8e1e6adde4)

**Comment by knegron** [comment]
It sounds horrible without the neural engine. Do you know any way to get it to work?
