### ISSUE TITLE
[Bug]: Last image doesn't append to video when storymodemethod = 1

### ISSUE THREAD

**Issue by joshholly** [elebumm/RedditVideoMakerBot#1711]
### Describe the bug

So when I make a story mode video, I use storymethod=1 , which makes a video with multiple caption clips. I noticed the last sentence doesn't get appended to the video. The audio of it does, but not the caption image. 

### Reproduction Steps

Set storymode=true and storymodemethod=1 in your config file. Run the bot.

### Expected behavior

Append all caption images to the video. Including the last one.

### System Information

Operating System : MacOS 14.0
Python version : Python 3.10
App version / Branch : 3.2

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

All the image files are there in the temp folder. But the last one doesn't get added to the overlay on the video.

**Comment by OpenSourceSimon** [comment]
Interesting... Thanks for reporting the bug!

**Comment by jaaneh** [comment]
Also seeing this issue. TTS will read the last text, but without any text on the screen. Any way you can look into this @OpenSourceSimon

**Comment by OpenSourceSimon** [comment]
> Also seeing this issue. TTS will read the last text, but without any text on the screen. Any way you can look into this @OpenSourceSimon 

This bug has been here already for quite some time. I'm not sure if I have time to debug but if I have I'll sure do
