### ISSUE TITLE
[Bug]: ffmpeg error

### ISSUE THREAD

**Issue by Schlupped** [elebumm/RedditVideoMakerBot#1713]
### Describe the bug

Every time I run the program I come across a "ffmpeg error" after the "creating the final video" section and during the "rendering the video" portion of the program.

### Reproduction Steps

Ran `python3 main.py`

### Expected behavior

Create a video.

### Screenshots

![git](https://github.com/elebumm/RedditVideoMakerBot/assets/137336620/22f5333b-506b-46c2-b120-c585d54bcd51)

Also, ffmpeg seems to be download correctly:
![ffmepg version](https://github.com/elebumm/RedditVideoMakerBot/assets/137336620/16a69f00-6875-4a45-8150-901bce386953)

### System Information

Operating System : [Windows 11]
Python version : [Python 3.10.11]
App version / Branch : [latest, V3.2]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by vannysass** [comment]
getting the same error, any update?

**Comment by MrNoide** [comment]
I also got that error

**Comment by MrNoide** [comment]
Actually I found the error! You can fix it by downloading the official ffmpeg files from the website. Unzip the folder and inside the main forlder is a folder called bin. In that folder there are 3 .exe files. On the bot main folder there are also 3 .exe files with the same name. Delete the ones inside the bot folder and put there the ones from the folder you just downloaded.
(Sorry I am not english so this is very badly explained)

**Comment by kadudutra** [comment]
try to remove FFmpeg from the root of the project and install it globally, it worked for me.
