### ISSUE TITLE
[Feature]: Storyboard Mode with Reddit Screenshots

### ISSUE THREAD

**Issue by rafaelsoley** [elebumm/RedditVideoMakerBot#1717]
### Summary

Make storyboard mode to work similar than to the other mode, making it so it displays a screenshot of the post while reading it, instead of black boxes.

### Is your feature request related to a problem?

Nope.

### Describe the solution you'd like

Make it so the storyboard mode takes screenshot of the thread (not the comments, though), so it works the same way as without storyboard mode, except it reads the contents of the post, for subreddits like AmITheAsshole or TodayIFuckedUp

**Comment by OpenSourceSimon** [comment]
This can be done with story mode 0

**Comment by rafaelsoley** [comment]
> This can be done with story mode 0

Thanks.
