### ISSUE TITLE
[Bug]: GTTS.run() got an unexpected keyword argument 'random_voice'  

### ISSUE THREAD

**Issue by Arsh-Pratap** [elebumm/RedditVideoMakerBot#1720]
### Describe the bug

Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.     │
│ Version: 3.2                                                                                                                         │
│ Error: GTTS.run() got an unexpected keyword argument 'random_voice'                                                                  │
│ Config: {'allow_nsfw': True, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False, 'storymodemethod': 1,           │
│ 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0, 'background': {'background_video':            │
│ 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15, 'enable_extra_audio': False, 'background_thumbnail':       │
│ False, 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color':         │
│ '255,255,255'}, 'tts': {'voice_choice': 'googletranslate', 'random_voice': False, 'elevenlabs_voice_name': 'Bella',                  │
│ 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001',    │
│ 'tiktok_sessionid': 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "C:\Users\91969\Desktop\RedditVideoMakerBot-master\main.py", line 132, in <module>
    raise err
  File "C:\Users\91969\Desktop\RedditVideoMakerBot-master\main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\91969\Desktop\RedditVideoMakerBot-master\main.py", line 69, in run_many
    main()
  File "C:\Users\91969\Desktop\RedditVideoMakerBot-master\main.py", line 51, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\91969\Desktop\RedditVideoMakerBot-master\video_creation\voices.py", line 53, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\91969\Desktop\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 77, in run
    self.call_tts("title", process_text(self.reddit_object["thread_title"]))
  File "C:\Users\91969\Desktop\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 154, in call_tts
    self.tts_module.run(

### Reproduction Steps

none

### Expected behavior

none

### Screenshots

none

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

Solve it

**Comment by rafaelsoley** [comment]
Supposedly, it will be fixed in the next update. Until then, heres a fix:

Go to file `engine_wrapper.py`, go to line 157 (`random_voice=settings.config["settings"]["tts"]["random_voice"], `, and comment that line.

Line 157 then should look something like this:
`#random_voice=settings.config["settings"]["tts"]["random_voice"],`

Notice, this is an experimental and temporary fix. This will fix this specific issue with the Google TTS voice setting, but might break some options (like the random_voice for other TTS services)

@Arsh-Pratap

**Comment by rafaelsoley** [comment]
Duplicated issue. You clearly did not check for duplicates, because this is a duplicate with issue #1706

**Comment by rayen-abbes** [comment]
go to final_video.py
comment out 349-358 and change the quiet on 415 to false

**Comment by rafaelsoley** [comment]
Both methods work

**Comment by Arsh-Pratap** [comment]
Thanks

**Comment by OpenSourceSimon** [comment]
Fixed in version 3.2.1
