### ISSUE TITLE
[Bug]:  Error: module 'ffmpeg' has no attribute 'input'

### ISSUE THREAD

**Issue by Arsh-Pratap** [elebumm/RedditVideoMakerBot#1722]
### Describe the bug

 Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the        │
│ Discord community.                                                                                                   │
│ Version: 3.2                                                                                                         │
│ Error: module 'ffmpeg' has no attribute 'input'                                                                      │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False,                │
│ 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1,           │
│ 'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15,         │
│ 'enable_extra_audio': False, 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',             │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice':     │
│ 'pyttsx', 'random_voice': True, 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED',                  │
│ 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid':  │
│ 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "C:\Users\91969\Desktop\RedditVideoMakerBot-develop\main.py", line 132, in <module>
    raise err
  File "C:\Users\91969\Desktop\RedditVideoMakerBot-develop\main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\91969\Desktop\RedditVideoMakerBot-develop\main.py", line 69, in run_many
    main()
  File "C:\Users\91969\Desktop\RedditVideoMakerBot-develop\main.py", line 61, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "C:\Users\91969\Desktop\RedditVideoMakerBot-develop\video_creation\final_video.py", line 154, in make_final_video
    background_clip = ffmpeg.input(prepare_background(reddit_id, W=W, H=H))
AttributeError: module 'ffmpeg' has no attribute 'input'

### Reproduction Steps

I only followed the steps given in readme.txt

### Expected behavior

Working smoothly

### Screenshots

![Screenshot 2023-06-26 082613](https://github.com/elebumm/RedditVideoMakerBot/assets/119803584/25ef90bf-8389-49e8-b435-f2b97c9f625b)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

I have spend 1 day to fix this problem .. Please help if possible

**Comment by fossie08** [comment]
I'm having this same issue

`┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the       │
│ Discord community.                                                                                                  │
│ Version: 3.2                                                                                                        │
│ Error: module 'ffmpeg' has no attribute 'input'                                                                     │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False,               │
│ 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0,        │
│ 'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15,        │
│ 'enable_extra_audio': False, 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',            │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice':    │
│ 'tiktok', 'random_voice': True, 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED',                 │
│ 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': │
│ 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "D:\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 132, in <module>
    raise err
  File "D:\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "D:\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 69, in run_many
    main()
  File "D:\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 61, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "D:\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\video_creation\final_video.py", line 156, in make_final_video
    background_clip = ffmpeg.input(prepare_background(reddit_id, W=W, H=H))
AttributeError: module 'ffmpeg' has no attribute 'input'`

**Comment by OpenSourceSimon** [comment]
Please run the following commands
`pip uninstall ffmpeg ffmpeg-python`
`pip install ffmpeg-python`

**Comment by kadudutra** [comment]
try to remove FFmpeg from the root of the project and install it globally, it worked for me.
