### ISSUE TITLE
[Bug]: ffmpeg doesnt have attribute input

### ISSUE THREAD

**Issue by ZainGamer7876** [elebumm/RedditVideoMakerBot#1732]
### Describe the bug

Im trying to use the bot, but when it gets to the exporting part, it says:
Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord          │
│ community.                                                                                                                     │
│ Version: 3.2                                                                                                                   │
│ Error: module 'ffmpeg' has no attribute 'input'                                                                                │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 3, 'opacity': 0.9, 'storymode': False, 'storymodemethod': 1,    │
│ 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0, 'background': {'background_video':      │
│ 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15, 'enable_extra_audio': False, 'background_thumbnail': │
│ False, 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color':   │
│ '255,255,255'}, 'tts': {'voice_choice': 'streamlabspolly', 'random_voice': True, 'elevenlabs_voice_name': 'Adam',              │
│ 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice':           │
│ 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis':   │
│ False}}    

### Reproduction Steps

I started the bot.

### Expected behavior

I wanted it to create the video.

### Screenshots

<img width="1440" alt="Screenshot 2023-06-30 at 23 16 05" src="https://github.com/elebumm/RedditVideoMakerBot/assets/104704693/5360faf4-ab3b-4a7b-b241-7a8a145385de">

### System Information

Operating System : [MacOS]
Python version : [e.g. Python 3.10]
App version / Branch : [latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by MrShafiq** [comment]
same issue here

**Comment by ImTheFakeOne** [comment]
> same issue here
> 
> Updated: fix the issue - need to manually install ffmpeg

Did you just installed it normally by downloading it and adding it to path or was there more steps required? Because I followed the installation process for ffmpeg and can confirm the path works but I still get the error

**Comment by juanbahena9** [comment]
I have the same issue and recently installed ffmpeg

**Comment by kadudutra** [comment]
> I have the same issue and recently installed ffmpeg

try to remove FFmpeg from the root of the project and install it globally, it worked for me.

**Comment by raceking37** [comment]
Remove ffmpeg and ffmpeg-python:
- pip uninstall ffmpeg
- pip uninstall ffmpeg-python

Install ffmpeg-python again with :
pip install ffmpeg-python

(Found solution [here](https://github.com/kkroening/ffmpeg-python/issues/174))
