### ISSUE TITLE
[Bug]: fmpeg._run.Error: ffmpeg error (see stderr output for detail)

### ISSUE THREAD

**Issue by ImTheFakeOne** [elebumm/RedditVideoMakerBot#1739]
### Describe the bug

Gives error when reaching "Rendering video" step
error seems to be related to FFmpeg

### Reproduction Steps

Running the bot and going through the initial mandatory setup didnt choose any optional settings
Bot runs well until it reached Rendering the video and  throws the error

### Expected behavior

Video should be rendered ant at some point finished

### Screenshots

![Screenshot 2023-07-04 013942](https://github.com/elebumm/RedditVideoMakerBot/assets/80204921/9f56f07b-003a-4f9f-814a-ad8ebc0b34b8)

### System Information

Operating System :  Windows 11
Python version : Python 3.10.10
App version / Branch : Latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by MrShafiq** [comment]
hi, could try this version of [ffmpeg](https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-2023-06-27-git-9b6d191a66-full_build.7z)

**Comment by Monkey999Human** [comment]
@MrShafiq This resolved the issue, thank you so mutch

**Comment by w8arteta** [comment]
> hi, could try this version of [ffmpeg](https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-2023-06-27-git-9b6d191a66-full_build.7z)

do you have an updates link for this

**Comment by MrShafiq** [comment]
> > hi, could try this version of [ffmpeg](https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-2023-06-27-git-9b6d191a66-full_build.7z)
> 
> do you have an updates link for this

hope it will help [link](https://github.com/GyanD/codexffmpeg/releases/download/2023-06-27-git-9b6d191a66/ffmpeg-2023-06-27-git-9b6d191a66-full_build.7z)

**Comment by winagwanga** [comment]
> > > hi, could try this version of [ffmpeg](https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-2023-06-27-git-9b6d191a66-full_build.7z)
> > 
> > 
> > do you have an updates link for this
> 
> hope it will help [link](https://github.com/GyanD/codexffmpeg/releases/download/2023-06-27-git-9b6d191a66/ffmpeg-2023-06-27-git-9b6d191a66-full_build.7z)

I'm new to all this, how do I use the update?

**Comment by RandyGrullon** [comment]
what version of ffmpeg work with the bot?

**Comment by sahej-b** [comment]
> > > > hi, could try this version of [ffmpeg](https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-2023-06-27-git-9b6d191a66-full_build.7z)
> > > 
> > > 
> > > do you have an updates link for this
> > 
> > 
> > hope it will help [link](https://github.com/GyanD/codexffmpeg/releases/download/2023-06-27-git-9b6d191a66/ffmpeg-2023-06-27-git-9b6d191a66-full_build.7z)
> 
> I'm new to all this, how do I use the update?

Replace all 3 FFMPEG exe files in the directory with the ones in the bin directory

**Comment by Panda-bit** [comment]
> > > > > hi, could try this version of [ffmpeg](https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-2023-06-27-git-9b6d191a66-full_build.7z)
> > > > 
> > > > 
> > > > do you have an updates link for this
> > > 
> > > 
> > > hope it will help [link](https://github.com/GyanD/codexffmpeg/releases/download/2023-06-27-git-9b6d191a66/ffmpeg-2023-06-27-git-9b6d191a66-full_build.7z)
> > 
> > 
> > I'm new to all this, how do I use the update?
> 
> Replace all 3 FFMPEG exe files in the directory with the ones in the bin directory

as in replace everything in the Reddit ffmpeg folder with the new bin directory 3 files?

**Comment by danielthejoker18** [comment]
> > > hi, could try this version of [ffmpeg](https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-2023-06-27-git-9b6d191a66-full_build.7z)
> > 
> > 
> > do you have an updates link for this
> 
> hope it will help [link](https://github.com/GyanD/codexffmpeg/releases/download/2023-06-27-git-9b6d191a66/ffmpeg-2023-06-27-git-9b6d191a66-full_build.7z)

that actually fixed for me, thanks a lot!

**Comment by FairulDeng** [comment]
Hello. I am using autosubtitle and still have the error. I downloaded the ffmpeg here but i didnt find the 3 files that should be replaced.
![image](https://github.com/elebumm/RedditVideoMakerBot/assets/122708108/7b7ea139-045f-4154-bb79-542812d36fbb)
