### ISSUE TITLE
No Module Named "yt_dlp"

### ISSUE THREAD

**Issue by baggot4** [elebumm/RedditVideoMakerBot#174]
When I run python3 main.py i get this error 
![image](https://user-images.githubusercontent.com/35886854/171745290-03601994-71ab-47fd-85c5-b0deb04883d6.png)

**Comment by ProjectSlxsh** [comment]
I used  this command: pip install yt_dlp

**Comment by ProjectSlxsh** [comment]
And this seemed to work for me
