### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Monkey999Human** [elebumm/RedditVideoMakerBot#1740]
### Describe the bug

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/53484243/849b5586-f1c1-4201-b364-204b33977341)

When i just go thru the config and i want to change this parameter.

### Reproduction Steps

Remake the config file

### Expected behavior

It should accept True or false.

### Screenshots

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/53484243/fd5dc839-f572-4d5a-aa77-fe9c4151b76e)

### System Information

Operating System : [e.g. Windows 10]
Python version : [e.g. Python 3.10.11]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by alex10342** [comment]
type 0 for false and 1 for true

**Comment by OpenSourceSimon** [comment]
Fixed in develop branch
