### ISSUE TITLE
[Bug]: Silence_duration

### ISSUE THREAD

**Issue by thewalisgrey** [elebumm/RedditVideoMakerBot#1742]
### Describe the bug

Cant run

### Reproduction Steps

I followed this guide https://www.youtube.com/watch?v=bWRPWjc0PbE

### Expected behavior

make video

### Screenshots

![Screenshot 2023-07-06 225354](https://github.com/elebumm/RedditVideoMakerBot/assets/138827416/761d08ae-f26c-4996-af38-291c913b78f2)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.1]
App version / Branch : Latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

none

**Comment by sebhulme** [comment]
Did you end up finding a fix for this? I have the same problem.

**Comment by sebhulme** [comment]
I think I have solved the problem. In your 'config.toml' file you can open it and under the '[settings.tts]' subtitle you can add a line that says 'silence_duration = 0.3'. Here is it in mine:
![image](https://github.com/elebumm/RedditVideoMakerBot/assets/140283100/234a0d59-8589-49c6-bbd2-45d9a6f4d87e)
