### ISSUE TITLE
[Bug]: FFmpeg install

### ISSUE THREAD

**Issue by CurlyHQ** [elebumm/RedditVideoMakerBot#1749]
### Describe the bug

Whatever I do FFmpeg is refusing to get installed, I keep being forced to go through the same steps
"FFmpeg is not installed on this system.
We can try to automatically install it for you. Would you like to do that? (y/n): y
Installing FFmpeg...
FFmpeg installed successfully! Please re-run the program.
" 
And it doesn't stop I tried both "pip3 install FFmpeg and pip install FFmpeg" separately but I still can't escape the loop.

### Reproduction Steps

wrote "python main.py" and I end up looping with "FFmpeg is not installed on this system.
We can try to automatically install it for you. Would you like to do that? (y/n): y
Installing FFmpeg...
FFmpeg installed successfully! Please re-run the program."

### Expected behavior

For it to go to the next step and ask me the information from [Configure The Bot](https://reddit-video-maker-bot.netlify.app/docs/configuring#:~:text=Configure%20The%20Bot-,Configure%20The%20Bot,-We%20need%20to).
<br>

### System Information

Operating System: mOS 13.3.1 
Python version: Python 3.10.8
App version / Branch: "You are using the newest version (3.2) of the bot"

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by SomeRandomGuy009** [comment]
did u follow the 2nd and 3rd step?

**Comment by Abrar047** [comment]
Copy the Path of ffmpeg in your system Similar to this "D:\Reddit Video Maker\RedditVideoMakerBot-3.2\ffmpeg" .
Search "Edit the system environment variables"
Open it and click on "environment variables"
Search "Paths" in User variables for {You computer Name}
Click on Path and add the above copied path and save it.

**Comment by thanghq** [comment]
for Mac users, try 
```brew install ffmpeg```
then find the location where ffmpeg locate with ```which ffmpeg``` and append it into your $PATH
