### ISSUE TITLE
Cannot add custome background audio[Bug]: 

### ISSUE THREAD

**Issue by JanssonTheBest** [elebumm/RedditVideoMakerBot#1751]
### Describe the bug

In the audio.json file, the comment clearly states that I can add/remove background audio from the program when trying to add audio.

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/118405460/45203714-f5a7-4054-8a5a-b8813265e5a1)

I still get the same options as before

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/118405460/0bf12043-09c2-46be-a292-5f0e9170c1a4)

### Reproduction Steps

Opened the JSON file using Notepad++, added an audio reference like this

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/118405460/0c66630e-aca9-4c5e-9e30-1f7ac54554a6)

### Expected behavior

I expected it to give me more options of background audio to choose from.

### Screenshots

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/118405460/5c29893c-0730-4a67-9a94-9b7d2a8befbb)
![image](https://github.com/elebumm/RedditVideoMakerBot/assets/118405460/7ed4f19d-b27d-4fd7-9886-a24fe0600c4a)

### System Information

Operating System : [e.g. Windows 10]
Python version : [e.g. Python 3.10]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

I've also made a thread on your discord, in the Reddit bot help channel.

**Comment by vCybah** [comment]
I know this is old at this point but I just had this issue myself and the fix is to also add the name of the audio to the .config.template.toml as well, as soon as I did that it worked perfectly. Figured I'd post this in case it helps someone with the same issue.
