### ISSUE TITLE
[Bug]: ffmpeg error

### ISSUE THREAD

**Issue by Koroldan** [elebumm/RedditVideoMakerBot#1752]
### Describe the bug

Bot doesn't work, stops on the rendering part, please help

### Reproduction Steps

I had worse errors, then moved ffmpeg files from "bin" folder to ffmpeg folder, now i have less errors

### Expected behavior

ㅤ

### Screenshots

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/131802023/db643c02-dc40-40dc-8ee3-2c0fc6bd0ee4)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by JanssonTheBest** [comment]
You have to download the latest version of ffmpeg on their website and replace the old ones:

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/118405460/de38df3c-4a96-42dc-ad26-8218cc0ce110)

**Comment by Nesty9x** [comment]
got the same thing , did you fix it?

**Comment by BigManSteph** [comment]
yeh when u get the error message, it means the video is being rendered, so just wait till the vids done. u can check when its done on task manager.

**Comment by danieldetijger** [comment]
How long do I have to wait until te video is ready?
