### ISSUE TITLE
[Bug]: ValueError 

### ISSUE THREAD

**Issue by Nesty9x** [elebumm/RedditVideoMakerBot#1757]
### Describe the bug

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/139927675/2d4371bb-99b1-4d62-adb9-d31a2529f449)

### Reproduction Steps

Just executed the program normally

### Expected behavior

ValueError: invalid literal for int() with base 10: 'N/A\n'

### Screenshots

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/139927675/2c2a75bd-ded0-4096-bae8-d7ff0c84f767)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by adamwilfer** [comment]
Hey, did you find any solution for this? I am also getting the same error: ValueError: invalid literal for int() with base 10: 'N/A\n'

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/111173477/3fb3c555-2fae-46ee-9a42-bf7190bc1961)

**Comment by rizzshiii** [comment]
I'm facing the same issue as well if anybody got the fix please comment

**Comment by stonelotus** [comment]
I have solved this by modifying "resolution_h" in config.toml, as it was empty.
