### ISSUE TITLE
[Bug]: Error: TypeError: Cannot set properties of null (setting 'textContent') 

### ISSUE THREAD

**Issue by bhaveshkys** [elebumm/RedditVideoMakerBot#1763]
### Describe the bug

this error occurs  whenever i set storymodemethod to 0
`Version: 3.2                                                                                                              ││ Error: TypeError: Cannot set properties of null (setting 'textContent')                                                   ││     at eval (eval at evaluate (:197:30), <anonymous>:1:101)                                                               ││     at UtilityScript.evaluate (<anonymous>:204:19)                                                                        ││     at UtilityScript.<anonymous> (<anonymous>:1:44)                                                                       ││ Config: {'allow_nsfw': False, 'theme': 'light', 'times_to_run': 1, 'opacity': 0.0, 'storymode': True, 'storymodemethod':  ││ 0, 'storymode_max_length': 500, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.2, 'background':                    ││ {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15, 'enable_extra_audio':      ││ False, 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96,  ││ 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'streamlabspolly', 'random_voice': False,      ││ 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew',                         ││ 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice': '1',    ││ 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}   ` 

### Reproduction Steps

set storymodemethod =0

### Expected behavior

code should run after launching in headless mode

### Screenshots

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/65819723/7b9e95e9-6438-4806-9507-2bd39f8307bc)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by zezo-monobola** [comment]
bump
