### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ic3dm4ng0** [elebumm/RedditVideoMakerBot#1767]
### Describe the bug

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the       │
│ Discord community.                                                                                                  │
│ Version: 3.2                                                                                                        │
│ Error: ffmpeg error (see stderr output for detail)                                                                  │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False,               │
│ 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0,        │
│ 'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15,        │
│ 'enable_extra_audio': False, 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',            │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice':    │
│ 'pyttsx', 'random_voice': True, 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED',                 │
│ 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': │
│ 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "C:\Users\evanb\Downloads\RedditVideoMakerBot-master\main.py", line 132, in <module>
    raise err
  File "C:\Users\evanb\Downloads\RedditVideoMakerBot-master\main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\evanb\Downloads\RedditVideoMakerBot-master\main.py", line 69, in run_many
    main()
  File "C:\Users\evanb\Downloads\RedditVideoMakerBot-master\main.py", line 61, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "C:\Users\evanb\Downloads\RedditVideoMakerBot-master\video_creation\final_video.py", line 376, in make_final_video
    ffmpeg.output(
  File "C:\Users\evanb\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
Progress:   0%|

### Reproduction Steps

Ran program as normal. No previous errors. Fails on video rendering.

### Expected behavior

I expected it to render without issues and create the video

### System Information

Operating System : Windows 11
Python version : Python 3.6
App version / Branch : Master

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Jay-Forrer** [comment]
I think I might have had the same error. The Problem was that ffmpeg didn't know the Filter that was being used and you had to configure ffmpeg to allow that Filter. Unfortunately that didn't work so I had to manually download the full ffmpeg version and had to configure some stuff on my laptop.  I used this website to get the ffmpeg version that works: https://www.gyan.dev/ffmpeg/builds/#libraries 
and I used this website for the installation guidlines: https://video.stackexchange.com/questions/20495/how-do-i-set-up-and-use-ffmpeg-in-windows

Hope this helps
