### ISSUE TITLE
Running in to accept cookie / allow nsfw issues.

### ISSUE THREAD

**Issue by MrSataana** [elebumm/RedditVideoMakerBot#177]
With the latest Master version.
When it is a NSFW post, it displays the "show nsfw / allow nsfw" message.
And it also displays the cookie in the image, how to resolve both?

![image](https://user-images.githubusercontent.com/79517524/171747947-b159cf4f-dbca-4573-8090-bc1dfa529dce.png)

**Comment by p1x3lll** [comment]
dont use nsfw

**Comment by MrSataana** [comment]
> dont use nsfw

As much as that solves 1 issue, I'd rather explore different ways of solving it, thanks for the solution though!
