### ISSUE TITLE
[Bug]: Silence Duration

### ISSUE THREAD

**Issue by theyluvEnething** [elebumm/RedditVideoMakerBot#1775]
### Describe the bug

What do I do?

### Reproduction Steps

Did everything exactly as the Documentation says, here is my Config

I used Cookie Editor for the TikTok Session ID and also put my EvenLabs API Key

:│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                                             │
│ Version: 3.2                                                                                                                                                                 │
│ Error: 'silence_duration'                                                                                                                                                    │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False, 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w':    │
│ 1080, 'resolution_h': 1920, 'zoom': 1, 'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15, 'enable_extra_audio':    │
│ False, 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'},  │
│ 'tts': {'voice_choice': 'tiktok', 'random_voice': True, 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew',                    │
│ 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_006', 'tiktok_sessionid': 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'no_emojis': False}}

### Expected behavior

Run normally

### Screenshots

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/115583828/a0cd21d9-f258-45d8-8390-8f38c3e8240a)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by rizzshiii** [comment]
I think I have a solution for this problem. In your config.toml file under the settings.tts add the line 
'silence_duration = 0.3'.
