### ISSUE TITLE
[Bug]: Conversion Failed!

### ISSUE THREAD

**Issue by ifezcool** [elebumm/RedditVideoMakerBot#1779]
### Describe the bug

I keep getting the following when its trying to make the video, i tried using a different version of ffmpeg but still the same result:

ffmpeg version 6.0-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'assets/temp/15itsnk/background.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:03.16, start: 0.000000, bitrate: 5765 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 5758 kb/s, 59.90 fps, 59.90 tbr, 29949 tbn (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 (h264) -> crop:default
  crop:default -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[NULL @ 000001621b407180] Invalid NAL unit size (13552 > 8727).
[NULL @ 000001621b407180] missing picture in access unit with size 8731
[h264 @ 000001621c03eb00] Invalid NAL unit size (13552 > 8727).
[h264 @ 000001621c03eb00] Error splitting the input into NAL units.
Error while decoding stream #0:0: Invalid data found when processing input
[libx264 @ 000001621b8eaec0] using SAR=1/1
[libx264 @ 000001621b8eaec0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 000001621b8eaec0] profile High, level 4.1, 4:2:0, 8-bit
[libx264 @ 000001621b8eaec0] 264 - core 164 r3106 eaa68fa - H.264/MPEG-4 AVC codec - Copyleft 2003-2023 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=8 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=20000 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'assets/temp/15itsnk/background_noaudio.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.3.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p, 608x1080 [SAR 1:1 DAR 76:135], q=2-31, 20000 kb/s, 59.90 fps, 29949 tbn
    Metadata:
      encoder         : Lavc60.3.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/20000000 buffer size: 0 vbv_delay: N/A
frame=    0 fps=0.0 q=0.0 Lsize=       0kB time=-577014:32:22.77 bitrate=N/A speed=N/A    d=N/A
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[libx264 @ 000001621b8eaec0] final ratefactor: 8.56
Conversion failed!

### Reproduction Steps

run main.py

### Expected behavior

Final video should be completed without a "conversion failed" error

### System Information

Operating System : Windows 10
Python version : Python 3.10
App version / Branch : latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by dsymbol** [comment]
Fix for this is updating yt-dlp
```
pip install yt-dlp==2023.7.6
```
#1744

**Comment by gregregregregregre** [comment]
> Fix for this is updating yt-dlp
> 
> ```
> pip install yt-dlp==2023.7.6
> ```
> 
> #1744

Didn’t work for me

**Comment by ifezcool** [comment]
> Fix for this is updating yt-dlp
> 
> ```
> pip install yt-dlp==2023.7.6
> ```
> 
> #1744

This did not work

**Comment by dsymbol** [comment]
> > Fix for this is updating yt-dlp
> > ```
> > pip install yt-dlp==2023.7.6
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #1744
> 
> Didn’t work for me

Delete your `RedditVideoMakerBot/assets` folder and try again.

**Comment by gregregregregregre** [comment]
> > > Fix for this is updating yt-dlp
> > > ```
> > > pip install yt-dlp==2023.7.6
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > #1744
> > 
> > 
> > Didn’t work for me
> 
> Delete your `RedditVideoMakerBot/assets` folder and try again.

OMG THANK YOU SO MUCH IT WORKED
