### ISSUE TITLE
Conversion failed!

### ISSUE THREAD

**Issue by panx972** [elebumm/RedditVideoMakerBot#1781]
### Describe the bug

Moviepy - Running:
>>> "+ " ".join(cmd)
Moviepy - Command successful
Background video chopped successfully!
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Creating the final video 🎥

### Reproduction Steps

open run.bat

### Expected behavior

a 

### Screenshots

![Przechwytywanie](https://github.com/elebumm/RedditVideoMakerBot/assets/126722428/173830c6-d569-48c2-ae38-462ed2f342d3)

### System Information

Operating System : wIN10
Python version : pYTHON 3.8
App version / latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

Background video chopped successfully!
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Creating the final video 🎥                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ffmpeg version N-111652-gbf9f6a5e55-20230730 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.1.0 (crosstool-NG 1.25.0.196_227d99d)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20230730
  libavutil      58. 14.100 / 58. 14.100
  libavcodec     60. 22.100 / 60. 22.100
  libavformat    60. 10.100 / 60. 10.100
  libavdevice    60.  2.101 / 60.  2.101
  libavfilter     9. 10.100 /  9. 10.100
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'assets/temp/15kk0dp/background.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:03.16, start: 0.000000, bitrate: 5765 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 5758 kb/s, 59.90 fps, 59.90 tbr, 29949 tbn (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 (h264) -> crop:default
  crop:default -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[NULL @ 000000000080a680] Invalid NAL unit size (13552 > 8727).
[NULL @ 000000000080a680] missing picture in access unit with size 8731
[h264 @ 0000000003d21b00] Invalid NAL unit size (13552 > 8727).
[h264 @ 0000000003d21b00] Error splitting the input into NAL units.
[vist#0:0/h264 @ 0000000000811ec0] Decoding error: Invalid data found when processing input
[vost#0:0/libx264 @ 0000000002c3a100] No filtered frames for output stream, trying to initialize anyway.
[vost#0:0/libx264 @ 0000000002c3a100] No information about the input framerate is available. Falling back to a default value of 25fps. Use the -r option if you want a different framerate.
[libx264 @ 0000000002c3ac80] using SAR=1/1
[libx264 @ 0000000002c3ac80] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
[libx264 @ 0000000002c3ac80] profile High, level 4.1, 4:2:0, 8-bit
[libx264 @ 0000000002c3ac80] 264 - core 164 - H.264/MPEG-4 AVC codec - Copyleft 2003-2023 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=8 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=20000 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'assets/temp/15kk0dp/background_noaudio.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.10.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 20000 kb/s, 25 fps, 12800 tbn
    Metadata:
      encoder         : Lavc60.22.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/20000000 buffer size: 0 vbv_delay: N/A
[vist#0:0/h264 @ 0000000000811ec0] Decode error rate 1 exceeds maximum 0.666667
[out#0/mp4 @ 00000000007bbf80] video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[out#0/mp4 @ 00000000007bbf80] Output file is empty, nothing was encoded(check -ss / -t / -frames parameters if used)
frame=    0 fps=0.0 q=0.0 Lsize=       0kB time=N/A bitrate=N/A speed=N/A
[libx264 @ 0000000002c3ac80] final ratefactor: 5.97
Conversion failed!

An error occurred. Press any key to exit.

**Comment by Ausama95** [comment]
Did you solve this?

**Comment by panx972** [comment]
No i don't know what to do. Maybe i need to change background video?

niedz., 13 sie 2023, 21:13 użytkownik Osama Khalid Walid Ahmed <
***@***.***> napisał:

**Comment by Ausama95** [comment]
I tried this and it worked for me! at least I got a new error.

- Delete content of assets folder "video" & "audio"  dir:"Projects\RedditVideoMakerBot\assets\backgrounds"
- Update yt-dlp 'pip install --upgrade yt-dlp'
- Update praw 'pip install --upgrade praw'

**Comment by panx972** [comment]
Yes, I am working on it.

niedz., 20 sie 2023, 02:19 użytkownik github-actions[bot] <
***@***.***> napisał:
