### ISSUE TITLE
[Bug]: Conversion failed! while creating final video

### ISSUE THREAD

**Issue by dinomite96** [elebumm/RedditVideoMakerBot#1785]
### Describe the bug

│ Creating the final video 🎥                                                                                                                                                                                   │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ffmpeg version N-111711-gd295b6b693-20230807 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.1.0 (crosstool-NG 1.25.0.196_227d99d)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20230807
  libavutil      58. 14.100 / 58. 14.100
  libavcodec     60. 22.100 / 60. 22.100
  libavformat    60. 10.100 / 60. 10.100
  libavdevice    60.  2.101 / 60.  2.101
  libavfilter     9. 10.100 /  9. 10.100
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'assets/temp/15k45id/background.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:03.16, start: 0.000000, bitrate: 5765 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 5758 kb/s, 59.90 fps, 59.90 tbr, 29949 tbn (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 (h264) -> crop:default
  crop:default -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[NULL @ 00000191cd79b480] Invalid NAL unit size (13552 > 8727).
[NULL @ 00000191cd79b480] missing picture in access unit with size 8731
[h264 @ 00000191cf2754c0] Invalid NAL unit size (13552 > 8727).
[h264 @ 00000191cf2754c0] Error splitting the input into NAL units.
[vist#0:0/h264 @ 00000191cd79c300] Decoding error: Invalid data found when processing input
[vost#0:0/libx264 @ 00000191cd846e00] No filtered frames for output stream, trying to initialize anyway.
[vost#0:0/libx264 @ 00000191cd846e00] No information about the input framerate is available. Falling back to a default value of 25fps. Use the -r option if you want a different framerate.
[libx264 @ 00000191cd8471c0] using SAR=1/1
[libx264 @ 00000191cd8471c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 00000191cd8471c0] profile High, level 4.1, 4:2:0, 8-bit
[libx264 @ 00000191cd8471c0] 264 - core 164 - H.264/MPEG-4 AVC codec - Copyleft 2003-2023 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=20000 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'assets/temp/15k45id/background_noaudio.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.10.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(progressive), 608x1080 [SAR 1:1 DAR 76:135], q=2-31, 20000 kb/s, 25 fps, 12800 tbn
    Metadata:
      encoder         : Lavc60.22.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/20000000 buffer size: 0 vbv_delay: N/A
[vist#0:0/h264 @ 00000191cd79c300] Decode error rate 1 exceeds maximum 0.666667
[out#0/mp4 @ 00000191cd795400] video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[out#0/mp4 @ 00000191cd795400] Output file is empty, nothing was encoded(check -ss / -t / -frames parameters if used)
frame=    0 fps=0.0 q=0.0 Lsize=       0kB time=N/A bitrate=N/A speed=N/A
[libx264 @ 00000191cd8471c0] final ratefactor: 0.99
Conversion failed!

### Reproduction Steps

followed all the steps provided from the tutorial

### Expected behavior

It should create the final video but with no luck

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by viazry5** [comment]
have you fixed this i have the same problom

**Comment by Nickhoog** [comment]
Have the same issue

**Comment by Gierszew** [comment]
I have the same issue too

**Comment by nightskat** [comment]
Same issue too

**Comment by nightskat** [comment]
> Same issue too

I checked the assets files, both video, and audio. It seems both files have been corrupted in downloading. So I deleted both of them and let main.py redownload them. It fixed the problem. I hope it helps you guys!

**Comment by Nickhoog** [comment]
> > Same issue too
> 
> I checked the assets files, both video, and audio. It seems both files have been corrupted in downloading. So I deleted both of them and let main.py redownload them. It fixed the problem. I hope it helps you guys!

I tried this aswell, but it didnt worked for me.
Where did you delete the files exactly?

**Comment by nightskat** [comment]
> > > Same issue too
> > 
> > 
> > I checked the assets files, both video, and audio. It seems both files have been corrupted in downloading. So I deleted both of them and let main.py redownload them. It fixed the problem. I hope it helps you guys!
> 
> I tried this aswell, but it didnt worked for me. Where did you delete the files exactly?

Here bro /RedditVideoMakerBot/assets/backgrounds

**Comment by nightskat** [comment]
> > > > Same issue too
> > > 
> > > 
> > > I checked the assets files, both video, and audio. It seems both files have been corrupted in downloading. So I deleted both of them and let main.py redownload them. It fixed the problem. I hope it helps you guys!
> > 
> > 
> > I tried this aswell, but it didnt worked for me. Where did you delete the files exactly?
> 
> Here bro /RedditVideoMakerBot/assets/backgrounds

There are two folders: audio video. Delete files in those folders
