### ISSUE TITLE
how to install? i need a tutorual

### ISSUE THREAD

**Issue by tproxy** [elebumm/RedditVideoMakerBot#179]

**Comment by ProjectSlxsh** [comment]
look under the video previded the describe how to download

**Comment by Kamushy** [comment]
read the readme.me description

**Comment by LukaHietala** [comment]
You can refer to the official [documentation](https://immaharry.gitbook.io/reddit-automated-video-bot/).

**Comment by majorslapper** [comment]
> You can refer to the official [documentation](https://immaharry.gitbook.io/reddit-automated-video-bot/).

Still didn’t work :(

**Comment by FreebieII** [comment]
Hi @majorslapper,

I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!

**Comment by majorslapper** [comment]
> Hi @majorslapper,
> 
> I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!
> 
> Happy Coding!

No I was not able to resolve the issue cannot seem to figure out the issue and how to fix it

**Comment by FreebieII** [comment]
> > Hi @majorslapper,
> > I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!
> > Happy Coding!
> 
> No I was not able to resolve the issue cannot seem to figure out the issue and how to fix it

Hi, 

Please try installing the latest release (1.1) [*Here*](https://github.com/elebumm/RedditVideoMakerBot/releases)

Follow all instructions in the `ReadMe.md` file, and tell me where you get an error.

**Comment by majorslapper** [comment]
> > > Hi @majorslapper,
> > > I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!
> > > Happy Coding!
> > 
> > 
> > No I was not able to resolve the issue cannot seem to figure out the issue and how to fix it
> 
> Hi,
> 
> Please try installing the latest release (1.1) [_Here_](https://github.com/elebumm/RedditVideoMakerBot/releases)
> 
> Follow all instructions in the `ReadMe.md` file, and tell me where you get an error.

I’m trying to run the python main.py and keep getting errors saying 
![CC5FCE5A-CD55-4CE1-9BBE-77E4979D8C8F](https://user-images.githubusercontent.com/106790855/172378150-f5744a81-a7a8-4e4a-93e7-817260d1bd80.png)

**Comment by ProjectSlxsh** [comment]
did you even follow any of the information in the documentation, from that it seems like you haven't even touched the .env file

**Comment by majorslapper** [comment]
> did you even follow any of the information in the documentation, from that it seems like you haven't even touched the .env file

It was filled in and there was some issue with main.py. It recognizing the env someone fix that bug for me

**Comment by JasonLovesDoggo** [comment]
Documentation solves this
