### ISSUE TITLE
[FFMPEG Bug]: OSError: [WinError 6] The handle is invalid when rendering video

### ISSUE THREAD

**Issue by Viktigboy** [elebumm/RedditVideoMakerBot#1791]
### Describe the bug

Doesnt render video

### Reproduction Steps

Followed exact setup

### Expected behavior

It should render the video

### Screenshots

![bilde](https://github.com/elebumm/RedditVideoMakerBot/assets/63349832/e664b800-1828-4ff7-a24c-4cc5541d7a2d)

### System Information

Operating System : [e.g. Windows 10]
Python version : [e.g. Python 3.10.11]
App version / Branch : [latest]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Ausama95** [comment]
I'm getting the same problem, did you find any solution?

**Comment by Viktigboy** [comment]
FIX: 
Fixed my build by reading multiple posts on the forum

Simple fix:
pip install --upgrade praw
pip install --upgrade yt-dlp

Download this version of ffmpeg and copy the 3 files in the 'bin' folder to your 'RedditVideoMakerBot' folder and replace the old files.

https://github.com/GyanD/codexffmpeg/releases/download/2023-06-27-git-9b6d191a66/ffmpeg-2023-06-27-git-9b6d191a66-full_build.7z
