### ISSUE TITLE
[Bug]: WinError6 Handle is invalid

### ISSUE THREAD

**Issue by Bandanakeks** [elebumm/RedditVideoMakerBot#1792]
### Describe the bug

crashes directly after the Creating Final video graphic pops up. 
- pastebin: https://pastebin.com/rktRGLNz
- What i've tried:
 removing ffmpeg.exe's and letting them install again
 seperately dowloading and replacing ffmpeg .exe files
 restarting. 

### Reproduction Steps

start the script 

### Expected behavior

rendering the video

### Screenshots

![Screenshot 2023-08-12 203456](https://github.com/elebumm/RedditVideoMakerBot/assets/96304272/fea0798f-0575-46b9-879a-e1ec0959878a)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Viktigboy** [comment]
i got the same error
