### ISSUE TITLE
ModuleNotFoundError: No module named 'reddit.subreddit'

### ISSUE THREAD

**Issue by thisisalt** [elebumm/RedditVideoMakerBot#1793]
### Describe the bug

so i just run python main.py but i get this error File "C:\Users\Administrator\Downloads\RedditVideoMakerBot-master\main.py", line 11, in <module>
    from reddit.subreddit import get_subreddit_threads
ModuleNotFoundError: No module named 'reddit.subreddit'
can anyone tell me how to fix it?

### Reproduction Steps

I just follow the install step but i get this error

### Expected behavior

ModuleNotFoundError: No module named 'reddit.subreddit'

### System Information

Operating System : Windows 10
Python version : Python 3.10
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by xJWzZ** [comment]
Python version should be 3.10 not 3.11. It will not work with 3.11

**Comment by thisisalt** [comment]
> Python version should be 3.10 not 3.11. It will not work with 3.11

I mean i use Python 3.10
