### ISSUE TITLE
[Bug]: list index out of range

### ISSUE THREAD

**Issue by anas123123213** [elebumm/RedditVideoMakerBot#1794]
### Describe the bug

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/72472767/f83f0226-93ef-46ed-aa62-17d724b507a0)

### Reproduction Steps

selected story mode method 2

### Expected behavior

Generating the video in story mode method 2

### System Information

windows 11
using the python version recommended 

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by fred9860** [comment]
same issue

**Comment by idkonow** [comment]
im having exact same issue

**Comment by idkonow** [comment]
i only seem to get the error when i am using story mode method 0. i dont get the error when i use method 1 or no story mode.

**Comment by OpenSourceSimon** [comment]
Fixed in 3.2.1
