### ISSUE TITLE
[Bug]:  [youtube] unable to extract initial player response

### ISSUE THREAD

**Issue by SpyGgG** [elebumm/RedditVideoMakerBot#1798]
### Describe the bug

When I run the project and it starts to download the videos for the music it give this exact error "WARNING: [youtube] unable to extract initial player response" and this after "WARNING: [youtube] unable to extract yt initial data"  Error: ERROR: [download] Got error: HTTP Error 403: Forbidden                                               │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 50, 'opacity': 0.9, 'storymode': False,               │
│ 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0,         │
│ 'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15,         │
│ 'enable_extra_audio': False, 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',             │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice':     │
│ 'tiktok', 'random_voice': True, 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED',                  │
│ 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid':  │
│ 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False

### Reproduction Steps

when ever i try to run the project

### Expected behavior

I expected it to make the videos

### System Information

Operating System : [Windows 11]
Python version : [Python 3.6]
App version / Branch : [atest]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by HiddenBoixxx** [comment]
same for me http error...

**Comment by FauconFR** [comment]
I have the same issue, but only with the background audio.
Tried lofi and chill-summer.
