### ISSUE TITLE
Error when "Getting AskReddit threads" prawcore exception

### ISSUE THREAD

**Issue by baggot4** [elebumm/RedditVideoMakerBot#180]
After running python3 main.py I get this error 
![image](https://user-images.githubusercontent.com/35886854/171750693-6663adbb-6126-4be1-8264-54c7a2451a76.png)​‌‌‌‌​‌‌​​​‌‌​‌‌​​​​‌​‌‌​‌​​​​‌‌​​​​‌​​‌‌​‌‌​​‌​​‌​‌‌​‌​​​​‌​

**Comment by ProjectSlxsh** [comment]
In the .env file did you specify what subreddit you wanted them to come from, and if so copy and paste what you wrote please.

**Comment by baggot4** [comment]
I tried these links and all got these errors with them
https://www.reddit.com/r/tifu/
![image](https://user-images.githubusercontent.com/35886854/171751459-e858fb3d-9060-49b7-a65a-ac85665a6f81.png)

https://www.reddit.com/r/Nootropics/comments/u70x4p/whats_your_i_wish_id_started_using_this_sooner/
![image](https://user-images.githubusercontent.com/35886854/171751500-2d59c0c2-83ce-444d-b391-2da49b2a5d1d.png)


> In the .env file did you specify what subreddit you wanted them to come from, and if so copy and paste what you wrote please.

*

**Comment by ProjectSlxsh** [comment]
when you put the subreddit in did you put r/tifu or tifu

**Comment by ProjectSlxsh** [comment]
aswell as you are not supposed to enter links to my knowledge, currently not able to use program

**Comment by baggot4** [comment]
> well as you are not supposed to enter links to my knowledge, currently not able to use program

I did not know that here's the error I get when I type

SUBREDDIT="tifu"
![image](https://user-images.githubusercontent.com/35886854/171752253-d7e08e27-ef43-484d-8d9a-4fe1b3e85046.png)

SUBREDDIT="r/tifu"
![image](https://user-images.githubusercontent.com/35886854/171752288-3a06baaa-0f44-4c1a-96f1-970ed350a2a3.png)

**Comment by ProjectSlxsh** [comment]
The one with the 400 error is the incorrect way and the other one with just "tifu" is correct aslong as you didnt include the "" after that I am not sure and would keep this issue open until higher/devs can help, by looking at your terminal you are on linux

**Comment by baggot4** [comment]
> The one with the 400 error is the incorrect way and the other one with just "tifu" is correct aslong as you didnt include the "" after that I am not sure and would keep this issue open until higher/devs can help, by looking at your terminal you are on linux?

I am on windows, I changed my config to look like this and here is what my output looks like. I am confused on what I am supposed to type in.



![image](https://user-images.githubusercontent.com/35886854/171755127-6632511b-1023-46d2-be59-8120d65ad425.png)
 
![image](https://user-images.githubusercontent.com/35886854/171755474-a70b9f44-0d5a-42e5-bf60-be42f939dc5e.png)

**Comment by baggot4** [comment]
after i typed in nootropics as the subreddit I want to pull from do I just wait? or did I do something wrong.
