### ISSUE TITLE
[Bug]: Rendering failed

### ISSUE THREAD

**Issue by ShayaanKhan** [elebumm/RedditVideoMakerBot#1802]
### Describe the bug

Video doesn't render.

### Reproduction Steps

Cloned repo
Made venv in VSCode with python version 3.10
installed requirements.txt with updated yt-dlp
Ran main.py

### Expected behavior

Expected Behavior: Video renders and output is generated

### Screenshots

│ Rendering the video 🎥                                                                                                                                                             │╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Progress:   0%|                                                                                                                                                                      ╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮ 
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                                                   ││ Version: 3.2                                                                                                                                                                       ││ Error: ffmpeg error (see stderr output for detail)                                                                                                                                 ││ Config: {'allow_nsfw': True, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': True, 'storymodemethod': 1, 'storymode_max_length': 3000, 'resolution_w': 1080,      ││ 'resolution_h': 1920, 'zoom': 1.0, 'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15, 'enable_extra_audio': False,       ││ 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts':        ││ {'voice_choice': 'pyttsx', 'random_voice': True, 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice':       ││ 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                    │╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Traceback (most recent call last):
  File "c:\Users\Admin\Desktop\python\RedditVideoMakerBot\main.py", line 132, in <module>
    raise err
  File "c:\Users\Admin\Desktop\python\RedditVideoMakerBot\main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "c:\Users\Admin\Desktop\python\RedditVideoMakerBot\main.py", line 69, in run_many
    main()
  File "c:\Users\Admin\Desktop\python\RedditVideoMakerBot\main.py", line 61, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "c:\Users\Admin\Desktop\python\RedditVideoMakerBot\video_creation\final_video.py", line 376, in make_final_video
    ffmpeg.output(
  File "C:\Users\Admin\Desktop\python\RedditVideoMakerBot\.venv\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
Progress:   0%|

### System Information

Operating System : Win 10
Python version : 3.10
App version / Branch : Latest/master
Updated yt-dlp to version 2023.7.6

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Joensw** [comment]
For a work around check this comment, it worked for me. https://github.com/elebumm/RedditVideoMakerBot/issues/1774#issuecomment-1665829314

**Comment by ShayaanKhan** [comment]
will try it and let you know

**Comment by ShayaanKhan** [comment]
Fixed with last update.
