### ISSUE TITLE
[Bug]: random_voice not accepting True/False

### ISSUE THREAD

**Issue by MagicHatJo** [elebumm/RedditVideoMakerBot#1812]
### Describe the bug

random_voice doesn't accept True or False. Not skipping this option forces user into infinite loop.

### Reproduction Steps

First initialization > get to random_voice > no to skip > type True or False.

### Expected behavior

Accepting True or False when valid options are True, False.

### Screenshots

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/38716012/f083f192-8232-45ae-bb96-22c7efd653f9)

### System Information

Operating System : Ubuntu
Python version : Python 3.10
App version / Branch : master

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

The reason this happens is because random_voice in .config.template.toml doesn't have type: "bool" as a setting, making handle_input go down the wrong logic path.

Creating a PR to solve this.

**Comment by OpenSourceSimon** [comment]
Fixed in develop branch
