### ISSUE TITLE
[Bug]: Python Error / Wrong Version

### ISSUE THREAD

**Issue by MaxiAmZocken** [elebumm/RedditVideoMakerBot#1828]
### Describe the bug

I get this error, but I got 3.11 installed 
![image](https://github.com/elebumm/RedditVideoMakerBot/assets/50016128/9ba7e690-b587-4941-9aef-186edf5698eb)

### Reproduction Steps

Just installed the Repo as it is described in the README, after I ran `python main.py`, this happened 

### Expected behavior

I expected the software to start 😅

### Screenshots

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/50016128/9ba7e690-b587-4941-9aef-186edf5698eb)

### System Information

Operating System : Windows 11 Home
Python version : Python 3.11
App version / Branch : latest possible

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by stumiles86** [comment]
I believe you have to uninstall python 3.11.xxx and re-install python 3.10.
I'm facing the same issue, just following the [prerequisites](https://reddit-video-maker-bot.netlify.app/docs/prerequisites ) on the website now:
