### ISSUE TITLE
prawcore.exceptions.OAuthException: invalid_grant error processing request

### ISSUE THREAD

**Issue by eminent02** [elebumm/RedditVideoMakerBot#184]
I have correctly put the credentials in .env file.
REDDIT_CLIENT_ID="id under 'personal use script'"
REDDIT_CLIENT_SECRET="secret key after app creation"
REDDIT_USERNAME="my reddit username"
REDDIT_PASSWORD="my reddit password"

what could be the issue? Please Help.

**Comment by benf2004** [comment]
Do you have 2FA setup correctly?

**Comment by FreebieII** [comment]
Hi @eminent02 

I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
