### ISSUE TITLE
[Feature]:  Captions removal

### ISSUE THREAD

**Issue by Ayanokoujikiyo** [elebumm/RedditVideoMakerBot#1841]
### Summary

Captions removal

### Is your feature request related to a problem?

No

### Describe the solution you'd like

I've noticed that a lot of people are complaining about the captions, and so am i frankly and as such i was trying to comment out the snippets of thecode responsible for them so i can have a tts video without the captions but WITH the background unfortunately i didnt succeed. but i do believe that removing them would be the best choice because then u can animate them and make them in ur own style using capcut premiere pro or anything of the sort which would increase the overall quality of the video. also for me sometimes the captions are being cut so it isnt ideal either.

**Comment by JasonLovesDoggo** [comment]
feel free to comment them out, they are located in /video_creation/final_video.py
