### ISSUE TITLE
[Bug]: aid value may not be correct when using the tik tok tts.

### ISSUE THREAD

**Issue by alderalder** [elebumm/RedditVideoMakerBot#1842]
### Describe the bug

Using the tik tok tts I am getting an error that says "TTS.TikTok.TikTokTTSException: Code: 1, reason: probably the aid value isn't correct, message: Couldn't load speech. Try again.". My aid value in the params variable is 1233. People who have the TikTok TTS working, are you using something else?

### Reproduction Steps

.

### Expected behavior

.

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Seips99** [comment]
I got the same error / bug:

│ Error: Code: 1, reason: probably the aid value isn't correct, message:       │
│ Couldn't load speech. Try again.

**Comment by Nikicha316** [comment]
Hey mate, I had the same problem too. The way I fixed it was by logging into a TikTok account and then obtaining the session ID.

**Comment by iltrix** [comment]
> Hey mate, I had the same problem too. The way I fixed it was by logging into a TikTok account and then obtaining the session ID.

i put the session ID still having same problem

**Comment by Rooniefantastic** [comment]
Guys which session id are you using ?
By mistake i was trying with the csrf one, instead just scroll find the right one

**Comment by Nikicha316** [comment]
> Guys which session id are you using ? By mistake i was trying with the csrf one, instead just scroll find the right one

When using the Cookie Editor extension, log in to TikTok, click on the extension, and you'll see the 'sessionID'. Click on it to copy the text.
