### ISSUE TITLE
[Feature]: Extracting audio only

### ISSUE THREAD

**Issue by Ayanokoujikiyo** [elebumm/RedditVideoMakerBot#1844]
### Summary

Removes video creation but only extracts the audio

### Is your feature request related to a problem?

no

### Describe the solution you'd like

The video editing is great and all but i believe that if we extract the audio alone it would be easier to just edit the video to ur liking as removing the captions seemed difficult. i cant seem to modify the code to just extract the audio so could anyone guide me?

**Comment by JasonLovesDoggo** [comment]
you can already do this.

This will not be added to the main bot but you can just comment out the call to cleanup then grab the mp3 files
