### ISSUE TITLE
[Bug]: FFmpeg is not installed on this system.

### ISSUE THREAD

**Issue by ramizkamel** [elebumm/RedditVideoMakerBot#1845]
### Describe the bug

I've tried so many ways to insall FFmpeg on my Mac and even the Terminal asks to press y for it to install FFmpeg to carry on using the bot but whatever I do it won't work. Someone please help.

### Reproduction Steps

After running python3 main.py

### Expected behavior

-

### System Information

Operating System : [e.g. Mac OS Montery]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by JasonLovesDoggo** [comment]
there is a ton of info on this online.
