### ISSUE TITLE
[Bug]: TikTok TTS failing

### ISSUE THREAD

**Issue by GurvirS9** [elebumm/RedditVideoMakerBot#1847]
### Describe the bug

When running main.py, I get this error.
`TTS.TikTok.TikTokTTSException: Code: 1, reason: probably the aid value isn't correct, message: Couldn't load speech. Try again.`
(See linked screenshot for full error)
Tried 3 different account sessionid.

### Reproduction Steps

- Perform the installation and setup normally.
- Run main.py
- This error appears.

### Expected behavior

Expected it to generate a video with no hiccups.

### Screenshots

![Screenshot 2023-10-08 234914](https://github.com/elebumm/RedditVideoMakerBot/assets/147340782/8d01c6d2-9ce8-4ec5-b9e8-2d62871c5a0e)

### System Information

Operating System : Windows 11
Python version : Python 3.10.11
App version / Branch : V3.2.1

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Ld85** [comment]
i have the same problem

**Comment by xSilentDogggo** [comment]
did someone fix it already i have the same problem

**Comment by Ld85** [comment]
> did someone fix it already i have the same problem

nope tried a few versions back and forth

**Comment by Switz399** [comment]
Hello, did this ever get solved?

**Comment by JasonLovesDoggo** [comment]
> Hello, did this ever get solved?

**Comment by GurvirS9** [comment]
hey uh
is it because tiktok is banned in my country?
