### ISSUE TITLE
[Bug]: CODE SAYS FFMPEG IS NOT INSTALLED BUT IT IS INSTALLED

### ISSUE THREAD

**Issue by selams31** [elebumm/RedditVideoMakerBot#1856]
### Describe the bug

<img width="906" alt="Screen Shot 2023-10-26 at 02 45 05" src="https://github.com/elebumm/RedditVideoMakerBot/assets/108633644/fd8da675-8549-4a1d-92b3-2311dcc85c59">

### Reproduction Steps

I DID ALL I CAN SO I NEED HELP :)

### Expected behavior

I JUST DELETED AND UPDATED ALL PIPS AND RE INSTALLED FFMPEG BUT NOTHİNG IS CHANGED PLS HELP ME 

### System Information

Operating System : OSX
Python version : Python 3.10.4

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by hubaibmahmood** [comment]
Facing the same issue. Any one can help?
