### ISSUE TITLE
Exception Thrown No module named 'rich' 

### ISSUE THREAD

**Issue by jordan1121** [elebumm/RedditVideoMakerBot#186]
![Capture](https://user-images.githubusercontent.com/106795034/171784445-77e511fa-c9b9-47e6-a6a8-e34137d66158.PNG)

**Comment by MDAmirPathan** [comment]
U can install using Command `pip3 install rich` or `pip install rich`

**Comment by jordan1121** [comment]
i used it but got a bunch of line separation errors
