### ISSUE TITLE
[Feature]: Reduce the amount of words displayed during storymode=true

### ISSUE THREAD

**Issue by ervinjenriquez** [elebumm/RedditVideoMakerBot#1862]
### Summary

I'd like to reduce the words to be less of a paragraph and more of a 2-3 words while still being in sync with audio.

### Is your feature request related to a problem?

No.

### Describe the solution you'd like

I would like to be able to update the config.toml to define a word limit during the story mode.

**Comment by z-alsamarai** [comment]
Hi Ervin, were you able to come up with a solution for this feature?
