### ISSUE TITLE
Credit for the Use of the Background Video

### ISSUE THREAD

**Issue by Excalizan** [elebumm/RedditVideoMakerBot#187]
So I checked the URL to the background video and started reading the comment to see if anyone complained about the video is being used without permissinon and yes, the video owner updated himself on the comments saying:

> "Many people have been telling me that people have been streaming this video on TikTok without my permission and making money off it. I unfortunately can't do anything about that so I started my own TikTok to stream on! I need 1000 followers to be allowed to stream, so if you have a TikTok, please follow my account so I can start streaming ASAP! [https://www.tiktok.com/@bbswitzerYT](https://www.tiktok.com/@bbswitzerYT)
> This is also a friendly reminder that I do NOT allow my content to be used for any purpose without proper credits. Proper credits means that you give me credits for the content and link to this video. If you find anyone stealing this video, please report them."

I'm worried that this could be a problem, so I advice you to not do it, but maybe find a video that is free for use?

If you do so, I hope you guys let me know...

Sincerely,
Excalizan

**Comment by ToastedPlayz** [comment]
Can't preach this enough, make sure any videos you use are allowed to be used!! Every creator has different wishes for their content. There is a ton of free-to-use parkour on youtube. Just be safe.
