### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by aswinmv** [elebumm/RedditVideoMakerBot#1870]
### Describe the bug

 with python 3.10 installed still showing , to try with python 3.10

### Reproduction Steps

 with python 3.10 installed still showing , to try with python 3.10

### Expected behavior

 with python 3.10 installed still showing , to try with python 3.10

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.10]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by handmodels** [comment]
Hi

I had this problem earlier and downloaded Python 3.10 using the Microsoft Store. Hope it works for you

**Comment by aswinmv** [comment]
its solved
