### ISSUE TITLE
Choose a minimum character length for a storymode post[Feature]: 

### ISSUE THREAD

**Issue by Xndzr** [elebumm/RedditVideoMakerBot#1875]
### Summary

stroymode_min_length (characters)

### Is your feature request related to a problem?

if you want a desired length for your video, you can esitmate it with an accurate minimum and maximum character count

### Describe the solution you'd like

if settings.config["settings"]["storymode"]:
            if not submission.selftext:
                print_substep("You are trying to use story mode on post with no post text")
                continue
            else:
                # Check for the length of the post text
                if len(submission.selftext) > (
                    settings.config["settings"]["storymode_max_length"] or 2000
                ):
                    print_substep(
                        f"Post is too long ({len(submission.selftext)}), try with a different post. ({settings.config['settings']['storymode_max_length']} character limit)"
                    )
                    continue
                
                 # Check for the length of the post text against the minimum length (new check)
                if len(submission.selftext) < (
                    settings.config["settings"]["storymode_min_length"] or 1800
                ):
                    print_substep(
                        f"Post is too short ({len(submission.selftext)} characters), try with a different post. ({settings.config['settings']['storymode_min_length']} character minimum)"
                    )
                    continue

also a simple add to the config file

ex: 
[settings]
allow_nsfw = true
theme = "dark"
times_to_run = 1
opacity = 0.9
storymode = true
storymodemethod = 0
storymode_max_length = 3000
storymode_min_length = 2000
resolution_w = 1080
resolution_h = 1920
zoom = 1.0

### Additional Context

In util -> subreddit.py

**Comment by JasonLovesDoggo** [comment]
Please open a PR
