### ISSUE TITLE
Upgrading moviepy package  with 1.0.3 Upgrading to v2.0.0.dev2[Feature]: 

### ISSUE THREAD

**Issue by alexdo83** [elebumm/RedditVideoMakerBot#1878]
### Summary

Upgrading to v2.0.0.dev2?

### Is your feature request related to a problem?

Upgrading to v2.0.0.dev2?

### Describe the solution you'd like

Upgrading to v2.0.0.dev2?

**Comment by KyleBoyer** [comment]
I tried this myself and experienced some bugs with that version, that were resolved by reverting to 1.0.3. It also looks like that might be a pre-release that hasn't been touched in years.

**Comment by JasonLovesDoggo** [comment]
First off, why???? second off, it's a Beta release with a major tag which means breaking changes. Lastly, it's unmaintained.
