### ISSUE TITLE
Needs to ignore mods and automod.

### ISSUE THREAD

**Issue by sounddrill31** [elebumm/RedditVideoMakerBot#188]
kept reading the automod message. Also love your work, it'd be awesome if you made your code open source tho.

**Comment by LukaHietala** [comment]
What do you mean by an auto mod?

**Comment by reinkdesigns** [comment]
![image](https://user-images.githubusercontent.com/104669790/171914080-75772d83-470e-407a-b8c0-bebe6c13428e.png)
they mean this

Source: https://www.reddit.com/r/funny/comments/v2d3cr/red_blood_cells/

**Comment by ImmaHarry** [comment]
Noted this suggestion, thank you!

**Comment by moh57-ai** [comment]
sd

**Comment by aabbaszad67-ops** [comment]
hi
