### ISSUE TITLE
List Index Out of Range[Bug]: 

### ISSUE THREAD

**Issue by amyisaactt** [elebumm/RedditVideoMakerBot#1884]
### Describe the bug

I configure everything and then get this error at then end of the code, what's happening? The error code: 

 Sorry, something went wrong with this version! Try again, and feel free to  |
| report this issue at GitHub or the Discord community.                       |
| Version: 3.2.1                                                              |
| Error: list index out of range                                              |
| Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 3,           |
| 'opacity': 0.9, 'storymode': False, 'storymodemethod': 1,                   |
| 'storymode_max_length': 3000, 'resolution_w': 1080, 'resolution_h': 1920,   |
| 'zoom': 1, 'background': {'background_video': 'minecraft',                  |
| 'background_audio': 'lofi', 'background_audio_volume': 0.15,                |
| 'enable_extra_audio': False, 'background_thumbnail': False,                 |
| 'background_thumbnail_font_family': 'arial',                                |
| 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color':    |
| '255,255,255'}, 'tts': {'voice_choice': 'tiktok', 'random_voice': True,     |
| 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED',         |
| 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew',          |
| 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED',                |
| 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3,          |
| 'no_emojis': False}}                                                        |
+-----------------------------------------------------------------------------+
Traceback (most recent call last):
  File "E:\reddit bot GITHUB\RedditVideoMakerBot\main.py", line 123, in <module>
    raise err
  File "E:\reddit bot GITHUB\RedditVideoMakerBot\main.py", line 105, in <module>
    run_many(config["settings"]["times_to_run"])
  File "E:\reddit bot GITHUB\RedditVideoMakerBot\main.py", line 60, in run_many
    main()
  File "E:\reddit bot GITHUB\RedditVideoMakerBot\main.py", line 40, in main
    reddit_object = get_subreddit_threads(POST_ID)
  File "E:\reddit bot GITHUB\RedditVideoMakerBot\reddit\subreddit.py", line 95, in get_subreddit_threads
    submission = get_subreddit_undone(threads, subreddit)
  File "E:\reddit bot GITHUB\RedditVideoMakerBot\utils\subreddit.py", line 86, in get_subreddit_undone
    return get_subreddit_undone(
  File "E:\reddit bot GITHUB\RedditVideoMakerBot\utils\subreddit.py", line 86, in get_subreddit_undone
    return get_subreddit_undone(
  File "E:\reddit bot GITHUB\RedditVideoMakerBot\utils\subreddit.py", line 86, in get_subreddit_undone
    return get_subreddit_undone(
  [Previous line repeated 2 more times]
  File "E:\reddit bot GITHUB\RedditVideoMakerBot\utils\subreddit.py", line 88, in get_subreddit_undone
    time_filter=VALID_TIME_FILTERS[index],
IndexError: list index out of range

### Reproduction Steps

I ran main and answered the prompts to configure the bot and the subreddit. 

### Expected behavior

I expected it to run, not sure why there's an error. 

### Screenshots

![Screenshot 2023-11-20 120749](https://github.com/elebumm/RedditVideoMakerBot/assets/151569987/3177d724-ed93-4242-a37a-ccb696b882ea)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by kshitiz305** [comment]
Hi I wish to reopen the issue

**Comment by kshitiz305** [comment]
please unlock issue #1884
