### ISSUE TITLE
[Bug]: Cannot import name 'settings' from 'utils'

### ISSUE THREAD

**Issue by MudkipNerd** [elebumm/RedditVideoMakerBot#1885]
### Describe the bug

The settings module (as well as others) is not in the utils package
  File "c:\Users\hp\RedditVideoMakerBot\reddit\subreddit.py", line 5, in <module>
    from utils import settings
ImportError: cannot import name 'settings' from 'utils'

### Reproduction Steps

Installed all files from required.txt

### Expected behavior

For the utils package to have all required modules

### Screenshots

  File "c:\Users\hp\RedditVideoMakerBot\reddit\subreddit.py", line 5, in <module>
    from utils import settings
ImportError: cannot import name 'settings' from 'utils'

### System Information

Operating System : Windows 10
Python version : Python 3.11
App version / Branch : latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

None of the required utils modules exist

**Comment by shadowfaxx1** [comment]
Check File Paths:
Ensure that the 'utils' package is in the correct location relative to the 'subreddit.py' file.

Verify Module :
Confirm that the 'settings' module exists within the 'utils' package. 

Path Issues:
Check for any issues related to the Python path. The 'utils' package should be in a directory that is part of the Python path. You can print the Python path using import sys; print(sys.path) 

Envir : 
Ensure that you are using the correct Python environment. The installed packages, including 'utils', should be available in the Python environment where you are running your script.
