### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SpaceDev3** [elebumm/RedditVideoMakerBot#1886]
### Describe the bug

so I am trying to staar the bot and this what I got
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the        │
│ Discord community.                                                                                                   │
│ Version: 3.2.1                                                                                                       │
│ Error: Code: 1, reason: probably the aid value isn't correct, message: Couldn't load speech. Try again.              │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False,                │
│ 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0,         │
│ 'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15,         │
│ 'enable_extra_audio': False, 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',             │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice':     │
│ 'tiktok', 'random_voice': True, 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED',                  │
│ 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid':  │
│ 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}

### Reproduction Steps

I just pyhyon main.py

### Expected behavior

I think should make me a video

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by HacimNosp** [comment]
I'm running into the same issue. Below is also the code after the error message. 
╭──────────────────────────────────────────────────────────────────────────╮
│ Sorry, something went wrong with this version! Try again, and feel free  │
│ to report this issue at GitHub or the Discord community.                 │
│ Version: 3.2.1                                                           │
│ Error: Code: 1, reason: probably the aid value isn't correct, message:   │
│ Couldn't load speech. Try again.                                         │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1,        │
│ 'opacity': 0.9, 'storymode': False, 'storymodemethod': 1,                │
│ 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h':      │
│ 1920, 'zoom': 1, 'background': {'background_video': 'minecraft',         │
│ 'background_audio': 'lofi', 'background_audio_volume': 0.15,             │
│ 'enable_extra_audio': False, 'background_thumbnail': False,              │
│ 'background_thumbnail_font_family': 'arial',                             │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': │
│ '255,255,255'}, 'tts': {'voice_choice': 'tiktok', 'random_voice': True,  │
│ 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED',      │
│ 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew',       │
│ 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED',             │
│ 'python_voice': '', 'py_voice_num': '2', 'silence_duration': 0.3,        │
│ 'no_emojis': False}}                                                     │
╰──────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "C:\Users\Micah\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 132, in <module>
    raise err
  File "C:\Users\Micah\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\Micah\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 69, in run_many
    main()
  File "C:\Users\Micah\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 51, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\Micah\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\video_creation\voices.py", line 49, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\Micah\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 76, in run
    self.call_tts("title", process_text(self.reddit_object["thread_title"]))
  File "C:\Users\Micah\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 149, in call_tts
    self.tts_module.run(
  File "C:\Users\Micah\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\TTS\TikTok.py", line 109, in run
    raise TikTokTTSException(status_code, data["message"])
TTS.TikTok.TikTokTTSException: Code: 1, reason: probably the aid value isn't correct, message: Couldn't load speech. Try again.
