### ISSUE TITLE
Needs a time limit

### ISSUE THREAD

**Issue by sounddrill31** [elebumm/RedditVideoMakerBot#189]

**Comment by sounddrill31** [comment]
Can somebody add it to the to-do list?

**Comment by ToastedPlayz** [comment]
Time limit? Can you expand on that?

**Comment by FreebieII** [comment]
Hi @sounddrill31 

# Please refer to #220 

I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!

**Comment by FreebieII** [comment]
> 

Please refer to #220 as stated above.

**Comment by sounddrill31** [comment]
> > 

> Please refer to #220 as stated above.

Thanks
