### ISSUE TITLE
[Bug]: Code: 1, reason: probably the aid value isn't correct, message: Couldn't load speech. Try again. - TikTok Text-To-Speech

### ISSUE THREAD

**Issue by leon-wm** [elebumm/RedditVideoMakerBot#1895]
### Describe the bug

I allways get the same error, when running: Code: 1, reason: probably the aid value isn't correct, message: Couldn't load speech. Try again.

I have tryed to set a new TikTok-Sessionid
I have tryed to set a another voice.
I have tryed `tiktok_voice = ""` in the config.toml

### Reproduction Steps

_I don't know what I did wrong, maybe something from TikToks site???_

### Expected behavior

Generate the Text-To-Speech file.

### Screenshots

Error:
```
Error Return Type:  <class 'tuple'>
Error Class:  <class 'TTS.TikTok.TikTokTTSException'>
Error Message:  Code: 1, reason: probably the aid value isn't correct, message: Couldn't load speech. Try again.
Error Traceback:  ['  File "D:\\Python\\TiktokAutoBot\\TikTokAutoBot\\bot.py", line 52, in bot\n    videocreator()\n', '  File "D:\\Python\\TiktokAutoBot\\TikTokAutoBot\\videocreator.py", line 22, in main\n    length, number_of_comments = save_text_to_mp3(reddit_object)\n', '  File "D:\\Python\\TiktokAutoBot\\TikTokAutoBot\\video_creation\\voices.py", line 49, in save_text_to_mp3\n    return text_to_mp3.run()\n', '  File "D:\\Python\\TiktokAutoBot\\TikTokAutoBot\\TTS\\engine_wrapper.py", line 76, in run\n    self.call_tts("title", process_text(self.reddit_object["thread_title"]))\n', '  File "D:\\Python\\TiktokAutoBot\\TikTokAutoBot\\TTS\\engine_wrapper.py", line 149, in call_tts\n    self.tts_module.run(\n', '  File "D:\\Python\\TiktokAutoBot\\TikTokAutoBot\\TTS\\TikTok.py", line 109, in run\n    raise TikTokTTSException(status_code, data["message"])\n']
```
<br>
<br>

Screenshot:

![grafik](https://github.com/elebumm/RedditVideoMakerBot/assets/78597735/894fa50a-087c-45c8-b7c2-f64634ccc86a)

### System Information

Operating System : Windows 10
Python version : Python 3.10.0
App version / Branch : Version 3.2.1

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

Thanks in advance

**Comment by stonelotus** [comment]
Changing the "voice_choice" field from "tiktok" to "streamlabspolly" seems to have worked for me. Taken from this issue here: https://github.com/elebumm/RedditVideoMakerBot/issues/1858
Hope it works

**Comment by leon-wm** [comment]
Will try that
Thanks

**Comment by ByLex-69bits** [comment]
> streamlabspolly

could you send me your version of the bot working please ?
