### ISSUE TITLE
Sneaking out of my boyfriends house to see my ex 

### ISSUE THREAD

**Issue by Packs09** [elebumm/RedditVideoMakerBot#1899]
### Summary

A girl sneaking out of her boyfriends house to see her ex and they get caught 

### Is your feature request related to a problem?

No

### Describe the solution you'd like

A girl trying to sneak out of her boyfriend house and gets caught

**Comment by leon-wm** [comment]
You know that this a bot, that creates Reddit Videos?

**Comment by JasonLovesDoggo** [comment]
unrelated
