### ISSUE TITLE
macos support?

### ISSUE THREAD

**Issue by lmc87lmc** [elebumm/RedditVideoMakerBot#190]
i cannot rename the .env.template file to .env as macos wont let me? is there any work arounds

**Comment by Diwas37** [comment]
maybe try with the terminal?

**Comment by pinguinooo** [comment]
you need to use vscode because it's .env.example and every file with a . infront of it is hidden in linux/mac

**Comment by prasannakarki** [comment]
you can use sublime text editor too. OR vs code to rename it to .env

**Comment by jiaruijdfjdsu** [comment]
doesnt work

**Comment by FreebieII** [comment]
> i cannot rename the .env.template file to .env as macos wont let me? is there any work arounds

Hi @lmc87lmc ,

# Please refer to #64 

I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
