### ISSUE TITLE
Help out

### ISSUE THREAD

**Issue by shayan69420** [elebumm/RedditVideoMakerBot#1901]
### Describe the bug

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/113758003/6248810d-830e-4c23-85c2-ab1bb257a0b7)

### Reproduction Steps

nothing

### Expected behavior

doesnt give result

### Screenshots

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/113758003/654fb69d-437a-4b07-b6e0-92e0e7bf49b9)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by sebbourgeois** [comment]
There's an issue about this opened already : https://github.com/elebumm/RedditVideoMakerBot/issues/1898
There's also a thread pending on Discord about this, root cause of the issue is identified, waiting for a fix now.

**Comment by Kamushy** [comment]
> There's an issue about this opened already : #1898 There's also a thread pending on Discord about this, root cause of the issue is identified, waiting for a fix now.

Any fix yet @sebbourgeois
