### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by techman-5307** [elebumm/RedditVideoMakerBot#1903]
### Describe the bug

When answering n to the random voice choice both options true and false are not valid answers

### Reproduction Steps

Wipe the config.toml file and answer N to the random voice option answer

### Expected behavior

Allow you to write true or false

### Screenshots

![image_2023-12-13_203740126](https://github.com/elebumm/RedditVideoMakerBot/assets/108802423/bea33fbd-3aa0-401c-85a3-f919a08c54ed)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.10]
App version / Branch : Latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Pierro0o** [comment]
Hi, I face the same issue with random_voice. Workaround is to respond y and manually modify the config file to 'false'.
