### ISSUE TITLE
[Bug]: Installation

### ISSUE THREAD

**Issue by jtkubit** [elebumm/RedditVideoMakerBot#1904]
### Describe the bug

I just loaded up a brand new windows 10 installation and installed python 3.12 and tried to run the installation command, and it comes away with the error that it cannot build the wheels for thinc.

### Reproduction Steps

run the command pip install -r requirements.txt

### Expected behavior

install

### System Information

Operating System : Windows 10
Python version : [e.g. Python 3.12.1
App version / Branch : latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

This might just be a me problem which is why i ran it in a vm to see if my system was wrong but I can't see why it wouldn't work if there isnt something wrong

**Comment by SexyUhu** [comment]
As it cleary states in the "Requirements" section you can only use Python 3.10, because same of the dependencies do not work with newer versions of python.
