### ISSUE TITLE
[Bug]: libespeak.so.1: cannot open shared object file: No such file or     directory

### ISSUE THREAD

**Issue by abdyry** [elebumm/RedditVideoMakerBot#1906]
### Describe the bug

Sorry, something went wrong with this version! Try again, and feel free to   │
│ report this issue at GitHub or the Discord community.                        │
│ Version: 3.2.1                                                               │
│ Error: libespeak.so.1: cannot open shared object file: No such file or       │
│ directory                                                                    │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': │
│ 0.9, 'storymode': False, 'storymodemethod': 1, 'storymode_max_length': 1000, │
│ 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0, 'background':       │
│ {'background_video': 'minecraft', 'background_audio': 'lofi',                │
│ 'background_audio_volume': 0.15, 'enable_extra_audio': False,                │
│ 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',  │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color':     │
│ '255,255,255'}, 'tts': {'voice_choice': 'pyttsx', 'random_voice': True,      │
│ 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED',          │
│ 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew',           │
│ 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice': │
│ '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}} 

### Reproduction Steps

──────────────────────────────────────────────────────────────────────────────╮
│ You are using the newest version (3.2.1) of the bot                          │
╰──────────────────────────────────────────────────────────────────────────────╯
###############################
#                             #
# Checking TOML configuration #
#                             #
###############################
If you see any prompts, that means that you have unset/incorrectly set 
variables, please input the correct values.
╭──────────────────────────────────────────────────────────────────────────────╮
│ on the 1st iteration of 1                                                    │
╰──────────────────────────────────────────────────────────────────────────────╯
Logging into Reddit.
Version 7.7.0 of praw is outdated. Version 7.7.1 was released Tuesday July 11, 2023.
╭──────────────────────────────────────────────────────────────────────────────╮
│ Getting subreddit threads...                                                 │
╰──────────────────────────────────────────────────────────────────────────────╯
Using subreddit: r/AskReddit+Redditdev from TOML config
Video will be: What is something you cannot believe modern technology hasn’t 
fixed yet? 👍
Thread url is: 
https://reddit.com/r/AskReddit/comments/18jx7sz/what_is_something_you_cannot_bel
ieve_modern/ 👍
Thread has 4930 upvotes
Thread has a upvote ratio of 95.0%
Thread has 6863 comments
Received subreddit threads Successfully.
Thread ID is 18jx7sz
╭──────────────────────────────────────────────────────────────────────────────╮
│ Saving Text to MP3 files...                                                  │
╰──────────────────────────────────────────────────────────────────────────────╯
╭──────────────────────────────────────────────────────────────────────────────╮
│ Sorry, something went wrong with this version! Try again, and feel free to   │
│ report this issue at GitHub or the Discord community.                        │
│ Version: 3.2.1                                         

### Expected behavior

The video to be made.

### Screenshots

![Screenshot from 2023-12-17 07-39-45](https://github.com/elebumm/RedditVideoMakerBot/assets/152584017/2b23f567-19d2-42f1-a7cd-3424072b879d)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by ByLex-69bits** [comment]
did u found a solution ?
