### ISSUE TITLE
[Bug]:  Error "Prawcore" when executing python main.py

### ISSUE THREAD

**Issue by ByLex-69bits** [elebumm/RedditVideoMakerBot#1911]
### Describe the bug

Alright so I believe I did everything write, but when I'm executing the command, I'm having this :

C:\Users\ASUS\Desktop\RedditVideoMakerBot>python main.py
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\RedditVideoMakerBot\main.py", line 9, in <module>
    from prawcore import ResponseException
ModuleNotFoundError: No module named 'prawcore'

### Reproduction Steps

I execute the command "python main.py"

### Expected behavior

I exepected it to work

### Screenshots

![python bug](https://github.com/elebumm/RedditVideoMakerBot/assets/74616989/50b731d5-b59f-41c8-8d92-be813d4fc2c2)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.10.3]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by ByLex-69bits** [comment]
I resolved it

**Comment by Bentheminernz** [comment]
> I resolved it

How?

**Comment by matthias33890** [comment]
How did you resolve it? I have gotten the same error and haven't found a solution.

**Comment by ByLex-69bits** [comment]
> How did you resolve it? I have gotten the same error and haven't found a solution.

I delete everything and restart and it worked

**Comment by JasonLovesDoggo** [comment]
you just need to install it.... please google this first..
