### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by awdawdgf** [elebumm/RedditVideoMakerBot#1912]
### Describe the bug

 Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the       │
│ Discord community.                                                                                                  │
│ Version: 3.2.1                                                                                                      │
│ Error: Code: 1, reason: probably the aid value isn't correct, message: Couldn't load speech. Try again.             │
│ Config: {'allow_nsfw': False, 'theme': 'light', 'times_to_run': 10, 'opacity': 0.9, 'storymode': False,             │
│ 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0,        │
│ 'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15,        │
│ 'enable_extra_audio': False, 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',            │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice':    │
│ 'tiktok', 'random_voice': True, 'elevenlabs_voice_name': 'Adam', 'elevenlabs_api_key': 'REDACTED',                  │
│ 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': │
│ 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}

### Reproduction Steps

I dont know, config is above

### Expected behavior

Download the MP3

### Screenshots

https://prnt.sc/nortenl2SffJ

### System Information

Operating System : Win 11
Python version : Py 3.10
Newst version

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by MasKhan20** [comment]
I'm also having the same issue

**Comment by MasKhan20** [comment]
Any updates, this is still not working.
Have you tried using an older version?

**Comment by greeeen013** [comment]
same here

**Comment by greeeen013** [comment]
> same here

nvm i set the 'voice_choice' setting in the config to 'elevenlabs', and it is working.
(well, it gives me a different error)

**Comment by awdawdgf** [comment]
No, still not working,

**Comment by JasonLovesDoggo** [comment]
duplicate + docs on this exist
