### ISSUE TITLE
[Feature]: Read post description instead of comments

### ISSUE THREAD

**Issue by mayankpi** [elebumm/RedditVideoMakerBot#1913]
### Summary

Currently we are reading the comments on the post and not the post description. Instead of comments we can make to read the post description, which would be more meaningful for certain subreddits instead of the comments.

### Is your feature request related to a problem?

No. It is a new feature to create new content.

### Describe the solution you'd like

I would like everything to be same except:

1- first read the post title
2- then read the post description (length > 30 && length < 500)(maybe)
3- maybe read comments(1 or 2) - optional

**Comment by vsc9729** [comment]
Hey, Let me know if you found a solution for this

**Comment by cloudisity** [comment]
Setting the Story mode to 'true' will have the AI read the description.
