### ISSUE TITLE
[Bug]: after installing the bot and going in to command prompt it give the error of 'pip' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by Jaymiler4** [elebumm/RedditVideoMakerBot#1916]
### Describe the bug

the bug is after the install process of the bot and before the packages install 

### Reproduction Steps

i just installed the bot an extracted it

### Expected behavior

i expected the packages to install

### Screenshots

![Screenshot (3)](https://github.com/elebumm/RedditVideoMakerBot/assets/115383787/05775ce8-5c53-440a-8171-80c7f4875293)

### System Information

Operating System : [e Windows 11]
Python version : [e.g. Python 3.10]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Cometotili** [comment]
wow. You know someone is new when they can't even use pip :trollface:

**Comment by dieperdev** [comment]
@Jaymiler4 Try using `py -m pip install -r requirements.txt` and make sure you are using python 3.10.
