### ISSUE TITLE
[Bug]: Error after screenshots

### ISSUE THREAD

**Issue by Azrogue** [elebumm/RedditVideoMakerBot#1918]
### Describe the bug

I'm trying to generate my first video. I don't know what i'm doing wrong.

the result are in text file
[bugresult.txt](https://github.com/elebumm/RedditVideoMakerBot/files/13825385/bugresult.txt)

### Reproduction Steps

Use my current toml file and try to generate a video with him.
here is my current toml : 
[config .txt](https://github.com/elebumm/RedditVideoMakerBot/files/13825393/config.txt)

### Expected behavior

Having a completed video of a a reddit thead

### System Information

Operating System : [e.g. Windows 11]
Python version : Python 3.10.11
App version / Branch : master

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Citydayz** [comment]
Idk if u find the solution, but thanks to your config.txt i succeed to do it, it resolved my issue, may be i can help u ! (Btw i'm French too)
