### ISSUE TITLE
[Bug]: command not excecuting:

### ISSUE THREAD

**Issue by Jesper09038** [elebumm/RedditVideoMakerBot#1927]
### Describe the bug

When I type `python main.py` it somehow just doesn't do anything, it just goes to the next line. 
![Schermafbeelding 2024-01-13 122637](https://github.com/elebumm/RedditVideoMakerBot/assets/156309610/8940a052-a8ab-4921-a8ab-663d37920aa8)

### Reproduction Steps

I have no idea

### Expected behavior

normally it should just run the program like it did before

### Screenshots

![Schermafbeelding 2024-01-13 122637](https://github.com/elebumm/RedditVideoMakerBot/assets/156309610/8940a052-a8ab-4921-a8ab-663d37920aa8)

### System Information

Operating System : [Windows 11]
Python version : [Python 3.10]
App version / Branch : [VScode latest]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

Could be an issue not related to the code

**Comment by robinaerts** [comment]
Try to wait for a few minutes and see if any errors pop up.

**Comment by Jesper09038** [comment]
> Try to wait for a few minutes and see if any errors pop up.

I tried but it just doesn't do anything, also I'm the bottom of the screen it says that it's searching a file or smth

**Comment by robinaerts** [comment]
Maybe try to run it in another terminal than the integrated vscode one?
