### ISSUE TITLE
Rich module not found

### ISSUE THREAD

**Issue by ToastedPlayz** [elebumm/RedditVideoMakerBot#194]
I'm working on a fork of the repo to implement some changes. I will send a pull request for the main branch when I get everything sorted. However, right now Rich is not working for me. I have uninstalled and reinstalled and restarted the computer. 

Looking in my scripts folder, it is not there. First it was YT_DLP but now its Rich. I'm sure this is a problem on my end, but what the heck did I do wrong?

Visual studio code terminal: 
![image](https://user-images.githubusercontent.com/46064562/171824250-f72ffde2-68d4-4b56-86b4-cfc3023c9272.png)

Git Bash Installation:
![image](https://user-images.githubusercontent.com/46064562/171824342-588a3aa7-bae9-4553-9a6c-709f7adac16c.png)

Scripts folder:
![image](https://user-images.githubusercontent.com/46064562/171824176-f0afc66a-7e23-4288-a88c-858c92545024.png)

Environment Variable (Path)
![image](https://user-images.githubusercontent.com/46064562/171824633-bfca624f-5bd3-4f10-a597-3a0ec79d04b3.png)

**Comment by FreebieII** [comment]
https://immaharry.gitbook.io/reddit-automated-video-bot/final-words/error-4

Try this

**Comment by Lioker-source** [comment]
Try to install all modules with `python3 -m pip install -r requirements.txt`
That worked for me.

**Comment by jacesleeman** [comment]
if you are still having a problem try python -m rich

**Comment by FreebieII** [comment]
@ToastedPlayz were you able to resolve your issue?

**Comment by ToastedPlayz** [comment]
@FreebieII sorry I just woke up, gonna give that a try, will update.

**Comment by FreebieII** [comment]
> @FreebieII sorry I just woke up, gonna give that a try, will update.

No worries! I will await your reply ☺

**Comment by LukaHietala** [comment]
You can also do it manually by running the command `pip install rich`.

**Comment by JasonLovesDoggo** [comment]
If this is still an issue it has been solved in other GitHub issues
