### ISSUE TITLE
[Bug]: Timeout 30000ms exceeded and waiting for locator("[name=\"username\"]")

### ISSUE THREAD

**Issue by LiniPini** [elebumm/RedditVideoMakerBot#1940]
### Describe the bug

![Screenshot 2024-01-29 234402](https://github.com/elebumm/RedditVideoMakerBot/assets/157976809/883394a1-af6d-4993-8718-3701f4339347)

Everytime i try to create a video the headless browser times out and i get the error

### Reproduction Steps

Everytime the headless browser times out and i get the error, when i  turning the storymode off it functions, but the vids are obviously not good

### Expected behavior

It works haha, have no idea about programming

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

Has anyone an idea how to solve this problem?

**Comment by dieperdev** [comment]
Use `headless=False` in `video_creation/screenshot_downloader.py` line 78.
