### ISSUE TITLE
[Bug]: Error calling Streamlabspolly

### ISSUE THREAD

**Issue by 100XD2** [elebumm/RedditVideoMakerBot#1942]
### Describe the bug

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/58142238/1cfb1430-f77b-431f-bb9d-c9fb15ed7c85)

### Reproduction Steps

Ran the script as usual

### Expected behavior

Streamlabs polly should give the TTS

### Screenshots

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/58142238/d9e9fc8f-799a-4b8d-bf93-3e5648a01338)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by DRECKINTERNET** [comment]
i have the same issue

**Comment by HiDraaH** [comment]
same issue ...

**Comment by deity-peter** [comment]
i have the same issue
