### ISSUE TITLE
[Bug]: Error: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by CameronMansker** [elebumm/RedditVideoMakerBot#1945]
### Describe the bug

Error: index 0 is out of bounds for axis 0 with size 0

### Reproduction Steps

Look at picture

### Expected behavior

idk

### Screenshots

<img width="1429" alt="Screenshot 2024-01-31 at 9 13 41 PM" src="https://github.com/elebumm/RedditVideoMakerBot/assets/114499775/bcd89500-56a2-4260-8a76-b59a0bc8a7bc">

### System Information

Operating System : Mac os
Python version : python 3.10.0
App version / Branch : latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by knegron** [comment]
Running into the same issue. Looking into it and will let you know if I find anything

**Comment by Yugi00** [comment]
Having the same issue^

**Comment by Salty-Coder** [comment]
Same issue here. No known fix?
