### ISSUE TITLE
[Bug]: Playwright Timeout while Taking Screenshots

### ISSUE THREAD

**Issue by theSoberSobber** [elebumm/RedditVideoMakerBot#1946]
### Describe the bug

- Playwright times out while taking ss of comments
- I did headless false and then ran to see what was the issue
- apparently the requests being made with /commentId are not entertained by reddit and instead reddit shows "Something went wrong. Just don't panic."

### Reproduction Steps

- do headless=false and try, i was using r/aita, you may try on that
- i tried commenting that line and passing the reddit object just directly from the init scraping, but it obv errored that 'title.png' was not found in video gen

### Expected behavior

It's supposed to take ss, put in reddit object and then pass to the video maker

### System Information

Operating System : Windows 11
Python version : Python 3.10]
App version / Branch : master

### Checklist

- [X] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.

**Comment by theSoberSobber** [comment]
Feel free to ask for anymore info/ss, my config or anything else you need, but imo it's just reddit being what reddit is :((

**Comment by SierraThePotato** [comment]
I just encountered this issue, and what worked for me was using a VPN. I suspect reddit put some kind of restriction on my original IP address, because it was working fine a few hours ago. So yes, reddit being reddit.

**Comment by theSoberSobber** [comment]
it's sad that this repo is neglected now
