### ISSUE TITLE
[Bug]: Tiktok text to speech issue

### ISSUE THREAD

**Issue by torneighdo** [elebumm/RedditVideoMakerBot#1949]
### Describe the bug

I Got this error when running the app:
logs:

│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                                         │
│ Version: 3.2.1                                                                                                                                                           │
│ Error: Code: 1, reason: probably the aid value isn't correct, message: Text-to-speech isn't supported for this language                                                  │
│ Config: {'allow_nsfw': False, 'theme': 'light', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False, 'storymodemethod': 1, 'storymode_max_length': 1000,               │
│ 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0, 'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15,    │
│ 'enable_extra_audio': False, 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96,                           │
│ 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'tiktok', 'random_voice': False, 'elevenlabs_voice_name': 'Adam', 'elevenlabs_api_key':       │
│ 'REDACTED', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_009', 'tiktok_sessionid': 'REDACTED', 'python_voice': '1',         │
│ 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                                                                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "/home/torneighdo/Documents/RedditVideoMakerBot-master/main.py", line 132, in <module>
    raise err
  File "/home/torneighdo/Documents/RedditVideoMakerBot-master/main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "/home/torneighdo/Documents/RedditVideoMakerBot-master/main.py", line 69, in run_many
    main()
  File "/home/torneighdo/Documents/RedditVideoMakerBot-master/main.py", line 51, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "/home/torneighdo/Documents/RedditVideoMakerBot-master/video_creation/voices.py", line 49, in save_text_to_mp3
    return text_to_mp3.run()
  File "/home/torneighdo/Documents/RedditVideoMakerBot-master/TTS/engine_wrapper.py", line 102, in run
    self.call_tts(f"{idx}", process_text(comment["comment_body"]))
  File "/home/torneighdo/Documents/RedditVideoMakerBot-master/TTS/engine_wrapper.py", line 149, in call_tts
    self.tts_module.run(
  File "/home/torneighdo/Documents/RedditVideoMakerBot-master/TTS/TikTok.py", line 109, in run
    raise TikTokTTSException(status_code, data["message"])
TTS.TikTok.TikTokTTSException: Code: 1, reason: probably the aid value isn't correct, message: Text-to-speech isn't supported for this language
Using region Ninh BÃ¬nh Province server backend.
```

### Reproduction Steps

I tried searching but there is no techniques to solve this error

### Expected behavior

I expected it to generate normal text to speech oice

### Screenshots

![Here is the screenshot](https://github.com/elebumm/RedditVideoMakerBot/assets/157130758/0b19a96a-2411-4281-824e-e1bcc197a2ae)


### System Information

Operating System : Windows 11
Python version : Python 3.10.0
App version / Branch : 3.2.1

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

_No response_

**Comment by devrhis** [comment]
Hello, I had the same error, I changed the sessionid in the config.toml file and it worked!

**Comment by torneighdo** [comment]
@devrhis Did it work once or permanently? And how did you change and do it?

**Comment by torneighdo** [comment]
@devrhis Can you explain how did you do it?

**Comment by torneighdo** [comment]
How did it work? I tried logging out and in with my tiktok account, then changing the sessionid but still the same problem. Can you explain please?

**Comment by devrhis** [comment]
I just logged back into my tiktok account and the sessionid had changed, maybe try logging into another account

**Comment by torneighdo** [comment]
@devrhis Works now. Firstly, I tried using another account but that doesn't work, I tend to get that error after about 10 - 50 times of use, didn't work yesterday but worked today although I haven't changed anything so I assume tiktok has a rate limit.

**Comment by torneighdo** [comment]
EDIT: Works now, made me over a hundred videos and still working, it was just a temporarily issue
![image](https://github.com/elebumm/RedditVideoMakerBot/assets/157130758/0bba9469-d638-4412-9a4d-457aaaba66f0)

**Comment by torneighdo** [comment]
EDIT: Works now, made me over a hundred videos and still working, it was just a temporarily issue

**Comment by JannesKatterbach** [comment]
Hey, I downloaded the new version, but i still get the same error:
![Screenshot 2024-02-09 220129](https://github.com/elebumm/RedditVideoMakerBot/assets/144483852/970f77a8-0009-4c53-bb73-d77d89c8e87a)

**Comment by Xuldry** [comment]
I'm getting the same error, anyone found a solution to this?
