### ISSUE TITLE
[Bug]: post ID !?

### ISSUE THREAD

**Issue by ByLex-69bits** [elebumm/RedditVideoMakerBot#1950]
### Describe the bug

Where I can find the post ID of a reddit post ?

### Reproduction Steps

I pasted the url but it didn't work.

### Expected behavior

Expected to work.

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by duong-nguyen-fi** [comment]
The ID is inside the URL. 
```
https://www.reddit.com/r/<subreddit>/comments/1am0lfc/<tittle>
```
1am0lfc is the ID

**Comment by ByLex-69bits** [comment]
> The ID is inside the URL.
> 
> ```
> https://www.reddit.com/r/<subreddit>/comments/1am0lfc/<tittle>
> ```
> 
> 1am0lfc is the ID

thanks
