### ISSUE TITLE
[Feature]: Word by Word caption for reader mode

### ISSUE THREAD

**Issue by torneighdo** [elebumm/RedditVideoMakerBot#1952]
### Summary

Please add a word by word caption option for reader mode.

### Is your feature request related to a problem?

No.

### Describe the solution you'd like

It would be nice if instead of a sentence caption in story mode, if you could add a word by word option

**Comment by alexdo83** [comment]
very good idea

**Comment by rsabedra2** [comment]
Great idea. This would be really good to increase retention time
