### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'

### ISSUE THREAD

**Issue by Salty-Coder** [elebumm/RedditVideoMakerBot#1958]
### Describe the bug

When running the program, I receive an error.

`python main.py`
```
Using region England server backend.

Traceback (most recent call last):
...
   NOTIFY_POLICY = _lib.X509_V_FLAG_NOTIFY_POLICY
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'
```

### Reproduction Steps

Followed all installation instructions, then ran `python main.py`

### Expected behavior

Program runs

### Screenshots

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/59771980/be947a93-a38f-4b46-9193-d7d2108bf773)

### System Information

Operating System : Windows 11
Python version: Python 3.10.5
App version / Branch: latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by phillipbruh** [comment]
Upgrade the latest version of PyOpenSSL.

python3 -m pip install pip --upgrade
pip install pyopenssl --upgrade

**Comment by alexjshepler** [comment]
This worked for me
