### ISSUE TITLE
pip 3 error looked around could'nt find much 

### ISSUE THREAD

**Issue by jordan1121** [elebumm/RedditVideoMakerBot#196]
![pip 3 error](https://user-images.githubusercontent.com/106795034/171831289-bc0355fc-bbe5-40a6-997a-7b1a4fdeb0ff.PNG)

**Comment by FreebieII** [comment]
Try doing just `pip install -r requirements.txt`

**Comment by jordan1121** [comment]
It didnt work still have this issue
![Capture](https://user-images.githubusercontent.com/106795034/171847543-1bb414f2-69c0-427d-b2bc-33b8260b4918.PNG)

**Comment by prasannakarki** [comment]
Make sure you have python installed pip comes bundled with the python programming language.

**Comment by JasonLovesDoggo** [comment]
Append the pip call with python -m
