### ISSUE TITLE
No module named 'rich'

### ISSUE THREAD

**Issue by Ski11-pro** [elebumm/RedditVideoMakerBot#198]
I know nothing it has come up during installation
![Skärmbild (260)](https://user-images.githubusercontent.com/85174198/171844303-dc07611d-4371-4358-b7e2-a0863f71cbdb.png)

**Comment by megerim** [comment]
use ; `pip3 install rich `
if any other comes up use same syntax to install

**Comment by LukaHietala** [comment]
If the pip3 does not work you can do `pip install rich`.  If you have any more problems you can refer to the official [documentation](https://immaharry.gitbook.io/reddit-automated-video-bot/) it covers most of the solutions to the errors.
