### ISSUE TITLE
issue with [What subreddit would you like to pull from?]

### ISSUE THREAD

**Issue by megerim** [elebumm/RedditVideoMakerBot#199]
any answer to this question came back with these errors, help :
![Ekran Alıntısı](https://user-images.githubusercontent.com/97033161/171844672-81081234-0e32-4fa2-b4d8-fdb59a5da4ba.PNG)
(

**Comment by JYunth** [comment]
yup, same issue over here.

**Comment by RenkeDhr** [comment]
Instead of `python3 main.py` type `python main.py` hope this helps. It helped me when I had this problem.

**Comment by JasonLovesDoggo** [comment]
Believe this is fixed now
Please reopen if you still have an issue
