### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Emmes420** [elebumm/RedditVideoMakerBot#20]
When main.py is run it output this error 
![error22](https://user-images.githubusercontent.com/48575205/171323109-4d7f75f7-19b3-40be-b04d-07518aba338d.PNG)

**Comment by choob123** [comment]
Did you create the reddit api as a script?

**Comment by Emmes420** [comment]
> Did you create the reddit api as a script?

I think so

**Comment by FreebieII** [comment]
Hey @Emmes420 

I hope you were able to resolve your issue, I will be closing this for the time being.  Feel free to re-open the issue if it has not been solved!

Happy Coding!
