### ISSUE TITLE
Please someone help me 

### ISSUE THREAD

**Issue by shubh-3011** [elebumm/RedditVideoMakerBot#200]
can someone help me with this i am not able to install requirements.txt there is a error always, if you can help on discord that would be great to 
my discord id:
 shubh30111#5812

**Comment by FreebieII** [comment]
https://immaharry.gitbook.io/reddit-automated-video-bot/getting-the-packages-in-place

**Comment by D3FUZED** [comment]
Please show an image of the errors

**Comment by shubh-3011** [comment]
> 

![image](https://user-images.githubusercontent.com/81286735/171916197-a31c1797-9b36-4cba-9378-21a557c1152c.png)

**Comment by CallumIO** [comment]
Redownload the repo, I just merged #164 which fixes this
