### ISSUE TITLE
[Bug]: Username Locator Error

### ISSUE THREAD

**Issue by topBlackZer0** [elebumm/RedditVideoMakerBot#2000]
### Describe the bug

Hi everyone,
I am a beginner here. Doesn't know how to use GitHub. please excuse my mistakes. 
  Timeout Error? Username Locator Error?┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ You are using the newest version (3.2.1) of the bot                                                                 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
###############################
#                             #
# Checking TOML configuration #
#                             #
###############################
If you see any prompts, that means that you have unset/incorrectly set variables, please input the correct values.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ on the 1st iteration of 1                                                                                           │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Logging into Reddit.
Version 7.7.0 of praw is outdated. Version 7.7.1 was released Tuesday July 11, 2023.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Getting subreddit threads...                                                                                        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Using subreddit: r/AskReddit+AmItheAsshole from TOML config
Video will be: AITA for telling my sisters that us being separated was the best thing that could have happened to me?
👍
Thread url is: https://reddit.com/r/AmItheAsshole/comments/1bt2mtx/aita_for_telling_my_sisters_that_us_being/ 👍
Thread has 1790 upvotes
Thread has a upvote ratio of 97.0%
Thread has 123 comments
Received subreddit threads Successfully.
Thread ID is 1bt2mtx
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Saving Text to MP3 files...                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Saving... ---------------------------------------- 0.5 it/s
Saved Text to MP3 files successfully.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Downloading screenshots of reddit posts...                                                                          │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Launching Headless Browser...
Logging in to Reddit...
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the       │
│ Discord community.                                                                                                  │
│ Version: 3.2.1                                                                                                      │
│ Error: Timeout 30000ms exceeded.                                                                                    │
│ =========================== logs ===========================                                                        │
│ waiting for locator("[name=\"username\"]")                                                                          │
│ ============================================================                                                        │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False,               │
│ 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0,        │
│ 'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15,        │
│ 'enable_extra_audio': False, 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',            │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice':    │
│ 'tiktok', 'random_voice': True, 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED',                 │
│ 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': │
│ 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "H:\RedditVideoMakerBot-master\main.py", line 132, in <module>
    raise err
  File "H:\RedditVideoMakerBot-master\main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "H:\RedditVideoMakerBot-master\main.py", line 69, in run_many
    main()
  File "H:\RedditVideoMakerBot-master\main.py", line 53, in main
    get_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "H:\RedditVideoMakerBot-master\video_creation\screenshot_downloader.py", line 103, in get_screenshots_of_reddit_posts
    page.locator('[name="username"]').fill(settings.config["reddit"]["creds"]["username"])
  File "C:\Users\umar\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 16045, in fill
    self._sync(
  File "C:\Users\umar\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 109, in _sync
    return task.result()
  File "C:\Users\umar\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 212, in fill
    return await self._frame.fill(self._selector, strict=True, **params)
  File "C:\Users\umar\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 528, in fill
    await self._channel.send("fill", locals_to_params(locals()))
  File "C:\Users\umar\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\umar\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 482, in wrap_api_call
    return await cb()
  File "C:\Users\umar\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("[name=\"username\"]")
============================================================

### Reproduction Steps

I installed this software for the first time after completing all the steps in the installation documentation. I ran it. and I get the mentioned error.

### Expected behavior

To create the video or work as it is supposed to.

### System Information

Operating System : [Windows 11]
Python version : [Python 3.10.11]
App version / Branch : [3.2.1]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Wowmandeez** [comment]
Im in the same boat, would love to see a solution to this

**Comment by Wowmandeez** [comment]
Hey buddy i figured it out. I'm a beginner too but I found this pull request and I dont know how to use it to auto update the software but i managed to just copy the changed code into the specific files and it worked.
https://github.com/elebumm/RedditVideoMakerBot/pull/1986/files

**Comment by topBlackZer0** [comment]
I have done the changes as suggested, now when I run the program I get the following error:
`Traceback (most recent call last):
  File "H:\RedditVideoMakerBot-master\main.py", line 24, in <module>
    from video_creation.screenshot_downloader import get_screenshots_of_reddit_posts
  File "H:\RedditVideoMakerBot-master\video_creation\screenshot_downloader.py", line 223
         page.goto(f"https://new.reddit.com/{comment['comment_url']}")
                                                                      ^
IndentationError: unindent does not match any outer indentation level`

**Comment by topBlackZer0** [comment]
> Hey buddy i figured it out. I'm a beginner too but I found this pull request and I dont know how to use it to auto update the software but i managed to just copy the changed code into the specific files and it worked. https://github.com/elebumm/RedditVideoMakerBot/pull/1986/files

Thank You so much, It resolved the error. How do I close my issue?
