### ISSUE TITLE
I can not install "pip3 install -r requirements.txt" anyone help me please

### ISSUE THREAD

**Issue by MaxBTW** [elebumm/RedditVideoMakerBot#201]
![Screenshot 2022-06-03 143934](https://user-images.githubusercontent.com/81623249/171855735-e407370f-8fd0-4f79-b439-4980fbb08290.png)

**Comment by D3FUZED** [comment]
Make sure to download and install the following tools: https://visualstudio.microsoft.com/visual-cpp-build-tools/. You need the C++ desktop tools, then try again

**Comment by CallumIO** [comment]
Re clone the repo, merged #164 which will most likely fix this
