### ISSUE TITLE
Not sure what error this is any fixes ?

### ISSUE THREAD

**Issue by jordan1121** [elebumm/RedditVideoMakerBot#202]
![Capture](https://user-images.githubusercontent.com/106795034/171862182-ec4dda4e-81fc-4dc1-a93c-19086f26f1ec.PNG)

**Comment by jordan1121** [comment]
i was using the gitbook to get to this point

**Comment by D3FUZED** [comment]
Could you show your .env file without showing your credentials?

**Comment by jordan1121** [comment]
![Capture](https://user-images.githubusercontent.com/106795034/171869410-3e8e4e06-1ab6-486e-aebe-055f8515cb53.PNG)

**Comment by D3FUZED** [comment]
You have subreddit set as 'yes', which is most likely causing the issue. Make sure to input only the name of the subreddit you'd like to use, for example r/AskReddit would be `SUBREDDIT="AskReddit"`

**Comment by jacesleeman** [comment]
> You have subreddit set as 'yes', which is most likely causing the issue. Make sure to input only the name of the subreddit you'd like to use, for example r/AskReddit would be `SUBREDDIT="AskReddit"`

i overlooked that lol
but r/yes is a thing so its something else

**Comment by jordan1121** [comment]
![same issue](https://user-images.githubusercontent.com/106795034/171976044-43daeec8-8ef3-496c-8734-ed66e075ef42.PNG)
Tried to run AskReddit ran into the same issue

**Comment by jordan1121** [comment]
> is it saved as a .env bc it may say its name is a .env but it could still have to template tag on it

how can i remove the template tag?

**Comment by D3FUZED** [comment]
Make sure hidden file extensions are visible, see https://knowledge.autodesk.com/search-result/caas/sfdcarticles/sfdcarticles/How-to-enable-hidden-file-extensions-in-Windows.html
