### ISSUE TITLE
[Bug]: playwright problem 

### ISSUE THREAD

**Issue by UnkownPlayerX000** [elebumm/RedditVideoMakerBot#2031]
### Describe the bug

when i finish configuring the bot and it starts making the video at the end it says this:

i tired installing playwright using this command `apt install node-playwright` and it installed successfully
but there is only one slight problem which how do i run playwright install as mentioned below i dont know which browser the bot uses so i would like some help and thank you in advance.

`Launching Headless Browser...
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.          │
│ Version: 3.2.1                                                                                                                            │
│ Error: Executable doesn't exist at /root/.cache/ms-playwright/chromium-1064/chrome-linux/chrome                                           │
│ ╔════════════════════════════════════════════════════════════╗                                                                            │
│ ║ Looks like Playwright was just installed or updated.       ║                                                                            │
│ ║ Please run the following command to download new browsers: ║                                                                            │
│ ║                                                            ║                                                                            │
│ ║     playwright install                                     ║                                                                            │
│ ║                                                            ║                                                                            │
│ ║ <3 Playwright Team                                         ║                                                                            │
│ ╚════════════════════════════════════════════════════════════╝                                                                            │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False, 'storymodemethod': 1,               │
│ 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1, 'background': {'background_video': 'minecraft',      │
│ 'background_audio': 'lofi', 'background_audio_volume': 0.15, 'enable_extra_audio': False, 'background_thumbnail': False,                  │
│ 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'},     │
│ 'tts': {'voice_choice': 'tiktok', 'random_voice': True, 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED',               │
│ 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED',           │
│ 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                                                   │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "/app/main.py", line 132, in <module>
    raise err
  File "/app/main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "/app/main.py", line 69, in run_many
    main()
  File "/app/main.py", line 53, in main
    get_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "/app/video_creation/screenshot_downloader.py", line 77, in get_screenshots_of_reddit_posts
    browser = p.chromium.launch(
  File "/usr/local/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 14723, in launch
    self._sync(
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 109, in _sync
    return task.result()
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_browser_type.py", line 95, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
    return await cb()
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Executable doesn't exist at /root/.cache/ms-playwright/chromium-1064/chrome-linux/chrome
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝
`

### Reproduction Steps

launch it on linux and and install and configure it like normal fiinish configuring it and let it make a video 

### Expected behavior

giving out a video of reddit stories with minecraft parkour gameplay

### Screenshots

![Screenshot_2024-04-24_15_53_19](https://github.com/elebumm/RedditVideoMakerBot/assets/118047020/626cae0d-e08d-4aa2-a431-06fd20cf41f3)
![Screenshot_2024-04-24_15_53_28](https://github.com/elebumm/RedditVideoMakerBot/assets/118047020/2e5ff00b-5dbf-4639-8a8c-21857bbad298)
![Screenshot_2024-04-24_15_53_38](https://github.com/elebumm/RedditVideoMakerBot/assets/118047020/4bf364f8-d633-488c-a74d-19b7054429c6)

### System Information

Operating System : [kali linux (debian branch)]
Python version : [3.11.8]
App version / Branch : [latest]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

i have ran the app using `run.sh` but have not tried the `python main.py` which i dont think would make a difference since `run.sh` uses docker and the `python main.py` launches it normally on the local computer

**Comment by sayok88** [comment]
I have forked https://github.com/sayok88/RedditVideoMakerBot to solve these problems, it does not take screenshots. See if you find it useful.

**Comment by badunch** [comment]
> I have forked https://github.com/sayok88/RedditVideoMakerBot to solve these problems, it does not take screenshots. See if you find it useful.

Yup, that worked! thanks

**Comment by Cyteon** [comment]
To anyone with this or an similar issue check out https://github.com/Cyteon/RedditVideoMakerBot, it will still take screnshots
