### ISSUE TITLE
It says "Something went wrong with making the screenshots! " even after lauching chromiun

### ISSUE THREAD

**Issue by hamimbadsha** [elebumm/RedditVideoMakerBot#2043]
### Describe the bug

it fails to take screenshot of the selected reddit post

### Reproduction Steps

i did nothing

### Expected behavior

well the expected behaviour is work perfectly

### Screenshots

C:\Users\hamim\Desktop\RedditVideoMakerBot-master\RedditVideoMakerBot-master>python main.py
Using region Dhaka Division server backend.

██████╗ ███████╗██████╗ ██████╗ ██╗████████╗    ██╗   ██╗██╗██████╗ ███████╗ ██████╗     ███╗   ███╗ █████╗ ██╗  ██╗███████╗██████╗
██╔══██╗██╔════╝██╔══██╗██╔══██╗██║╚══██╔══╝    ██║   ██║██║██╔══██╗██╔════╝██╔═══██╗    ████╗ ████║██╔══██╗██║ ██╔╝██╔════╝██╔══██╗
██████╔╝█████╗  ██║  ██║██║  ██║██║   ██║       ██║   ██║██║██║  ██║█████╗  ██║   ██║    ██╔████╔██║███████║█████╔╝ █████╗  ██████╔╝
██╔══██╗██╔══╝  ██║  ██║██║  ██║██║   ██║       ╚██╗ ██╔╝██║██║  ██║██╔══╝  ██║   ██║    ██║╚██╔╝██║██╔══██║██╔═██╗ ██╔══╝  ██╔══██╗
██║  ██║███████╗██████╔╝██████╔╝██║   ██║        ╚████╔╝ ██║██████╔╝███████╗╚██████╔╝    ██║ ╚═╝ ██║██║  ██║██║  ██╗███████╗██║  ██║
╚═╝  ╚═╝╚══════╝╚═════╝ ╚═════╝ ╚═╝   ╚═╝         ╚═══╝  ╚═╝╚═════╝ ╚══════╝ ╚═════╝     ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

  Thanks for using this tool! Feel free to contribute to this project on GitHub! If you have any questions, feel free
       to join my Discord server or submit a GitHub issue. You can find solutions to many common problems in the
                              documentation: https://reddit-video-maker-bot.netlify.app/

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ You are using the newest version (3.2.1) of the bot                                                                 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
###############################
#                             #
# Checking TOML configuration #
#                             #
###############################
If you see any prompts, that means that you have unset/incorrectly set variables, please input the correct values.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ on the 1st iteration of 1                                                                                           │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Logging into Reddit.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Getting subreddit threads...                                                                                        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Using subreddit: r/AskReddit+relationship_advice+NoSleep from TOML config
NSFW Post Detected. Skipping...
Video will be: Update: My (38F) Husband (39M) hid having lunch with a coworker (25F) and said my cooking was
‘tasteless’ what should I do? 👍
Thread url is:
https://reddit.com/r/relationship_advice/comments/1cmecnt/update_my_38f_husband_39m_hid_having_lunch_with_a/ 👍
Thread has 821 upvotes
Thread has a upvote ratio of 98.0%
Thread has 196 comments
Received subreddit threads Successfully.
Thread ID is 1cmecnt
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Saving Text to MP3 files...                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Saving... ---------------------------------------- 0.7 it/s
Saved Text to MP3 files successfully.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Downloading screenshots of reddit posts...                                                                          │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Launching Headless Browser...
Logging in to Reddit...
Skipping translation...
Something went wrong!
Something went wrong with making the screenshots! Do you want to skip the post? (y/n)

### System Information

Operating System : [e.g. Windows 10]
Python version : [e.g. Python 3.10]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Cyteon** [comment]
Can you send the error?

**Comment by adruzenko03** [comment]
I had the same issue, and my error was
```
...
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("[data-test-id=\"post-content\"]")
```

I am using Cyteon's fork's master branch with headless set to false

**Comment by Faycal-S** [comment]
having the same issue :/ I think it's due to reddit sometimes using a different login page which breaks the logic

**Comment by Cyteon** [comment]
Weird, you could try my dev branch, but it's not recommended

**Comment by jonas-is-coding** [comment]
Still got the Issue

<img width="906" alt="grafik" src="https://github.com/user-attachments/assets/0304cd87-1d61-425f-a31d-ad1f6f88428c">

**Comment by LeetCodeFan29** [comment]
The issue persists, is there a solution?

**Comment by techygeekshome** [comment]
Mine was working fine, but now got this error. Looking at the debug, its timing out looking for screenshots.

playwright._impl._errors.TimeoutError: Locator.screenshot: Timeout 30000ms exceeded.
Call log:
waiting for locator("[data-test-id=\"post-content\"]")

An error occurred. Press any key to exit.

**Comment by haytam47** [comment]
still have the same issu
