### ISSUE TITLE
crashing when it tries to load speech

### ISSUE THREAD

**Issue by SSimplyTTV** [elebumm/RedditVideoMakerBot#2064]
### Describe the bug

 Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                                                                              │
│ Version: 3.2.1                                                                                                                                                                                                │
│ Error: Code: 1, reason: probably the aid value isn't correct, message: Couldn’t load speech. Try again.                                                                                                       │
│ Config: {'allow_nsfw': True, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False, 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom':  │
│ 1, 'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15, 'enable_extra_audio': False, 'background_thumbnail': False,                                   │
│ 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'tiktok', 'random_voice': True,                 │
│ 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED',           │
│ 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}

### Reproduction Steps

idrk since its a bug

### Expected behavior

being able to load the video without it crashing

### Screenshots
![Screenshot 2024-06-06 161041](https://github.com/elebumm/RedditVideoMakerBot/assets/83842401/42118fb9-c118-4c4f-9477-ea667caa25d3)

### System Information

Operating System : Windows 11
Python version : Python 3.10

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by JasonLovesDoggo** [comment]
Please read other issues.
