### ISSUE TITLE
[Feature]: Improve .dockerignore to ignore previously created videos

### ISSUE THREAD

**Issue by pippinmole** [elebumm/RedditVideoMakerBot#2067]
### Summary

If you have videos in your results folder, they'll be copied into the image

### Is your feature request related to a problem?

Docker images can become massive because they contain previously created videos

### Describe the solution you'd like

Add a .dockerignore which ignores the results folder

**Comment by JasonLovesDoggo** [comment]
Very easy fix if anyone wants to make a pr (expect it merged within 30s lol)

**Comment by DraKen0009** [comment]
@JasonLovesDoggo  raied a PR for the issue
