### ISSUE TITLE
[Feature]: Change instructions to use a virtual environment

### ISSUE THREAD

**Issue by pippinmole** [elebumm/RedditVideoMakerBot#2068]
### Summary

Use virtual environment so the root python doesn't get cluttered

### Is your feature request related to a problem?

Handling package clashes are easier if everybody's using the same environment

### Describe the solution you'd like

Update the README.md to create and use a virtual environment instead of global python executable

**Comment by JasonLovesDoggo** [comment]
If anyone makes a PR related to this, please tag me

**Comment by DraKen0009** [comment]
@JasonLovesDoggo  I updated readme

**Comment by JasonLovesDoggo** [comment]
Fixed in #2093
