### ISSUE TITLE
how would i make the script ignore posts that aren't Text only posts

### ISSUE THREAD

**Issue by reinkdesigns** [elebumm/RedditVideoMakerBot#207]
i would like the script to be able to toggle if i want to pull text only posts, or image/video posts.
as well if it detects the post is image/video, it will keep the main post on screen fur the duration of the video

**Comment by FreebieII** [comment]
I am working this for my own adapted version, I will update you in this Issue as soon as I get it working myself.

**Comment by reinkdesigns** [comment]
awesome

**Comment by FreebieII** [comment]
Feature taken into consideration

**Comment by sarimwaniR** [comment]
.
