### ISSUE TITLE
[Bug]: TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by Sairamg18814** [elebumm/RedditVideoMakerBot#2073]
### Describe the bug

    def getsize(font: ImageFont | FreeTypeFont, text: str):
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### Reproduction Steps

I ran python main.py 

### Expected behavior

after that I got this error 

    def getsize(font: ImageFont | FreeTypeFont, text: str):
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by XVR1212** [comment]
+1

**Comment by JasonLovesDoggo** [comment]
Please use python 3.10
