### ISSUE TITLE
[Bug]: waiting for locator("[data-test-id=\"post-content\"]")

### ISSUE THREAD

**Issue by OCEANOFANYTHINGOFFICIAL** [elebumm/RedditVideoMakerBot#2075]
### Describe the bug

Using subreddit: r/ollama from TOML config
This post has under the specified minimum of comments (2). Skipping...
This post has under the specified minimum of comments (2). Skipping...
This post has under the specified minimum of comments (2). Skipping...
Video will be: Mixed GPU setups? 👍
Thread url is: https://new.reddit.com//r/ollama/comments/1dltfmq/mixed_gpu_setups/ 👍
Thread has 3 upvotes
Thread has a upvote ratio of 100.0%
Thread has 6 comments
Received subreddit threads Successfully.
Thread ID is 1dltfmq
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Saving Text to MP3 files...                                                                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Saving... ---------------------------------------- 0.2 it/s
Saved Text to MP3 files successfully.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Downloading screenshots of reddit posts...                                                                                                                          │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Launching Headless Browser...
Logging in to Reddit...
Skipping translation...
Something went wrong!
Something went wrong with making the screenshots! Do you want to skip the post? (y/n) y
The post is successfully skipped! You can now restart the program and this post will skipped.
Do you want the error traceback for debugging purposes? (y/n)y
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                                    │
│ Version: 3.3.0                                                                                                                                                      │
│ Error: Locator.bounding_box: Timeout 30000ms exceeded.                                                                                                              │
│ Call log:                                                                                                                                                           │
│ waiting for locator("[data-test-id=\"post-content\"]")                                                                                                              │
│                                                                                                                                                                     │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 104, 'opacity': 1.0, 'storymode': False, 'storymodemethod': 1, 'storymode_max_length': 1000,         │
│ 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.6, 'channel_name': 'OCEANOFANYTHING', 'background': {'background_video': 'orange-abstract',                   │
│ 'background_audio': 'lofi-rain', 'background_audio_volume': 0.7, 'enable_extra_audio': False, 'background_thumbnail': False, 'background_thumbnail_font_family':    │
│ 'arial', 'background_thumbnail_font_size': 100, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'streamlabspolly', 'random_voice': True, │
│ 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Brian', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice':                │
│ 'en_us_ghostface', 'tiktok_sessionid': 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.1, 'no_emojis': False}}                          │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "D:\AI\RedditVideoMakerBot\main.py", line 130, in <module>
    raise err
  File "D:\AI\RedditVideoMakerBot\main.py", line 112, in <module>
    run_many(config["settings"]["times_to_run"])
  File "D:\AI\RedditVideoMakerBot\main.py", line 67, in run_many
    main()
  File "D:\AI\RedditVideoMakerBot\main.py", line 51, in main
    get_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "D:\AI\RedditVideoMakerBot\video_creation\screenshot_downloader.py", line 203, in get_screenshots_of_reddit_posts
    raise e
  File "D:\AI\RedditVideoMakerBot\video_creation\screenshot_downloader.py", line 180, in get_screenshots_of_reddit_posts
    location = page.locator('[data-test-id="post-content"]').bounding_box()
  File "D:\AI\RedditVideoMakerBot\venv\lib\site-packages\playwright\sync_api\_generated.py", line 14782, in bounding_box
    self._sync(self._impl_obj.bounding_box(timeout=timeout))
  File "D:\AI\RedditVideoMakerBot\venv\lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
  File "D:\AI\RedditVideoMakerBot\venv\lib\site-packages\playwright\_impl\_locator.py", line 127, in bounding_box
    return await self._with_element(
  File "D:\AI\RedditVideoMakerBot\venv\lib\site-packages\playwright\_impl\_locator.py", line 108, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "D:\AI\RedditVideoMakerBot\venv\lib\site-packages\playwright\_impl\_locator.py", line 311, in element_handle
    handle = await self._frame.wait_for_selector(
  File "D:\AI\RedditVideoMakerBot\venv\lib\site-packages\playwright\_impl\_frame.py", line 323, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "D:\AI\RedditVideoMakerBot\venv\lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "D:\AI\RedditVideoMakerBot\venv\lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.bounding_box: Timeout 30000ms exceeded.
Call log:
waiting for locator("[data-test-id=\"post-content\"]")

### Reproduction Steps

I'm writing this on 23rd June. Yesterday it worked fine and I generated more than 50 videos from different subredits. but today when I started the bot, it kept giving me these errors. I tried to fix with the followings:

1. Tried to use a different Reddit account and TikTok session id
2. tried to reverse engineer the program, and found that reddit changed some layouts of their pages, that's why its quite challenging to get the screenshot. even I could not figured that out. reddit changed `data-test-id` to `data-testid` and `post-content` is not even found on the latest pages.
3. tried to reinstall all dependencies
4. tried to delete and recreate `nenv` 
5. upgraded `moviepy` 
6. reinstalled `playwright`

Appearently none of above worked, but I thing I figured out the problem(with the new HTML layout of their page"
I appreciate a quick fix for this, cuz my yt channel is based on this topic, if it is not fixed I cant make any video, please do fix it, a kind request to @elebumm , I'm a big sub of your yt channel, please fix it man if you get any free time on you 🙏

### Expected behavior

Expected to run the program without any issue

### Screenshots

Here Are The Screenshots:
![rd-2](https://github.com/elebumm/RedditVideoMakerBot/assets/81571601/7c14eab4-88bb-4b10-8d45-2e0b39584c23)
![rd-1](https://github.com/elebumm/RedditVideoMakerBot/assets/81571601/15d54b72-f6f7-4210-a752-f3b106477bae)

### System Information

Operating System : Windows 10
Python version : 3.10
App version : 3.3.0

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by aarora4** [comment]
Have the same issue. I fixed this by changing line 180 in screenshot_downloader.py to

`location = page.locator('[data-testid="post-container"] [data-test-id="post-content"]').bounding_box()`

**Comment by OCEANOFANYTHINGOFFICIAL** [comment]
> Have the same issue. I fixed this by changing line 180 in screenshot_downloader.py to
> 
> `location = page.locator('[data-testid="post-container"] [data-test-id="post-content"]').bounding_box()`

thanks man! I'll try this up

**Comment by OCEANOFANYTHINGOFFICIAL** [comment]
> Have the same issue. I fixed this by changing line 180 in screenshot_downloader.py to
> 
> `location = page.locator('[data-testid="post-container"] [data-test-id="post-content"]').bounding_box()`

Really appreciate your time and effort. I tried the solution you gave but it still gives the same error.

![again_error_cmd](https://github.com/elebumm/RedditVideoMakerBot/assets/81571601/209ad74e-3b51-4538-a73e-e3d37ab2aa58)

**Comment by grannymaster** [comment]
Having the same issue.

Here are my logs:

```
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the       │
│ Discord community.                                                                                                  │
│ Version: 3.3.0                                                                                                      │
│ Error: Locator.screenshot: Timeout 30000ms exceeded.                                                                │
│ Call log:                                                                                                           │
│ waiting for locator("[data-test-id=\"post-content\"]")                                                              │
│                                                                                                                     │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 9, 'opacity': 0.9, 'storymode': False,               │
│ 'storymodemethod': 1, 'storymode_max_length': 999999999, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0,   │
│ 'channel_name': 'dailyredditguy', 'background': {'background_video': 'minecraft', 'background_audio': 'lofi',       │
│ 'background_audio_volume': 0.01, 'enable_extra_audio': False, 'background_thumbnail': False,                        │
│ 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96,                                  │
│ 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'streamlabspolly', 'random_voice':       │
│ False, 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Brian',              │
│ 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_ghostface', 'tiktok_sessionid': 'REDACTED',             │
│ 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                             │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "C:\Users\admin\Downloads\RedditVideoMakerBot-master\main.py", line 131, in <module>
    raise err
  File "C:\Users\admin\Downloads\RedditVideoMakerBot-master\main.py", line 113, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\admin\Downloads\RedditVideoMakerBot-master\main.py", line 68, in run_many
    main()
  File "C:\Users\admin\Downloads\RedditVideoMakerBot-master\main.py", line 52, in main
    get_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "C:\Users\admin\Downloads\RedditVideoMakerBot-master\video_creation\screenshot_downloader.py", line 203, in get_screenshots_of_reddit_posts
    raise e
  File "C:\Users\admin\Downloads\RedditVideoMakerBot-master\video_creation\screenshot_downloader.py", line 185, in get_screenshots_of_reddit_posts
    page.locator('[data-test-id="post-content"]').screenshot(path=postcontentpath)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 16703, in screenshot
    self._sync(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 531, in screenshot
    return await self._with_element(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 108, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 311, in element_handle
    handle = await self._frame.wait_for_selector(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 323, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.screenshot: Timeout 30000ms exceeded.
Call log:
waiting for locator("[data-test-id=\"post-content\"]")

```

**Comment by RequieMa** [comment]
I tried to fix it by replacing

`'[data-test-id="post-content"]'` to `f'[data-fullname="t3_{reddit_id}"]'`
`page.locator(f"#t1_{comment['comment_id']}")` to `page.locator(f"#thing_t1_{comment['comment_id']}").locator("form").first`

Can you check if they work for your?

**Comment by natefillups** [comment]
> I tried to fix it by replacing
> 
> `'[data-test-id="post-content"]'` to `f'[data-fullname="t3_{reddit_id}"]'` `page.locator(f"#t1_{comment['comment_id']}")` to `page.locator(f"#thing_t1_{comment['comment_id']}").locator("form").first`
> 
> Can you check if they work for you?

Traceback (most recent call last):
  File "/app/main.py", line 160, in <module>
    raise err
  File "/app/main.py", line 142, in <module>
    run_many(config["settings"]["times_to_run"])
  File "/app/main.py", line 97, in run_many
    main()
  File "/app/main.py", line 53, in main
    get_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "/app/video_creation/screenshot_downloader.py", line 189, in get_screenshots_of_reddit_posts
    raise e
  File "/app/video_creation/screenshot_downloader.py", line 186, in get_screenshots_of_reddit_posts
    page.locator(f'[data-fullname="t3_{reddit_id}"]').screenshot(path=postcontentpath)
  File "/usr/local/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 16703, in screenshot
    self._sync(
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 531, in screenshot
    return await self._with_element(
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 108, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 311, in element_handle
    handle = await self._frame.wait_for_selector(
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 323, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.screenshot: Timeout 30000ms exceeded.
Call log:
waiting for locator("[data-fullname=\"t3_1drhq3x\"]")

**Comment by OCEANOFANYTHINGOFFICIAL** [comment]
> Having the same issue.
> 
> EDIT: Seems to be only happening to me when story mode is disabled.
> 
> Here are my logs:
> 
> ```
> ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
> │ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the       │
> │ Discord community.                                                                                                  │
> │ Version: 3.3.0                                                                                                      │
> │ Error: Locator.screenshot: Timeout 30000ms exceeded.                                                                │
> │ Call log:                                                                                                           │
> │ waiting for locator("[data-test-id=\"post-content\"]")                                                              │
> │                                                                                                                     │
> │ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 9, 'opacity': 0.9, 'storymode': False,               │
> │ 'storymodemethod': 1, 'storymode_max_length': 999999999, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0,   │
> │ 'channel_name': 'dailyredditguy', 'background': {'background_video': 'minecraft', 'background_audio': 'lofi',       │
> │ 'background_audio_volume': 0.01, 'enable_extra_audio': False, 'background_thumbnail': False,                        │
> │ 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96,                                  │
> │ 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'streamlabspolly', 'random_voice':       │
> │ False, 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Brian',              │
> │ 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_ghostface', 'tiktok_sessionid': 'REDACTED',             │
> │ 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                             │
> └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
> Traceback (most recent call last):
>   File "C:\Users\admin\Downloads\RedditVideoMakerBot-master\main.py", line 131, in <module>
>     raise err
>   File "C:\Users\admin\Downloads\RedditVideoMakerBot-master\main.py", line 113, in <module>
>     run_many(config["settings"]["times_to_run"])
>   File "C:\Users\admin\Downloads\RedditVideoMakerBot-master\main.py", line 68, in run_many
>     main()
>   File "C:\Users\admin\Downloads\RedditVideoMakerBot-master\main.py", line 52, in main
>     get_screenshots_of_reddit_posts(reddit_object, number_of_comments)
>   File "C:\Users\admin\Downloads\RedditVideoMakerBot-master\video_creation\screenshot_downloader.py", line 203, in get_screenshots_of_reddit_posts
>     raise e
>   File "C:\Users\admin\Downloads\RedditVideoMakerBot-master\video_creation\screenshot_downloader.py", line 185, in get_screenshots_of_reddit_posts
>     page.locator('[data-test-id="post-content"]').screenshot(path=postcontentpath)
>   File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 16703, in screenshot
>     self._sync(
>   File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
>     return task.result()
>   File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 531, in screenshot
>     return await self._with_element(
>   File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 108, in _with_element
>     handle = await self.element_handle(timeout=timeout)
>   File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 311, in element_handle
>     handle = await self._frame.wait_for_selector(
>   File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 323, in wait_for_selector
>     await self._channel.send("waitForSelector", locals_to_params(locals()))
>   File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 59, in send
>     return await self._connection.wrap_api_call(
>   File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
>     raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
> playwright._impl._errors.TimeoutError: Locator.screenshot: Timeout 30000ms exceeded.
> Call log:
> waiting for locator("[data-test-id=\"post-content\"]")
> 
> ```

Yes, in story mode it works fine but when story mode is false, it throws up this error no matter what i do

**Comment by OCEANOFANYTHINGOFFICIAL** [comment]
> I tried to fix it by replacing
> 
> `'[data-test-id="post-content"]'` to `f'[data-fullname="t3_{reddit_id}"]'`
> `page.locator(f"#t1_{comment['comment_id']}")` to `page.locator(f"#thing_t1_{comment['comment_id']}").locator("form").first`
> 
> Can you check if they work for you?

OK I'll try 🙂

**Comment by natefillups** [comment]
Doesn't work for all cases. @RequieMa

**Comment by OCEANOFANYTHINGOFFICIAL** [comment]
> Doesn't work for all cases. @RequieMa 

What it means??

**Comment by natefillups** [comment]
> > Doesn't work for all cases. @RequieMa
> 
> What it means??

There is a different response from the chromium browser if you run it headless vs non-headless sometimes which is why @RequieMa was trying to change the element finder. I tried adding an try catch to cover both types of responses, but then I ran the program more and seem like there might be another type of response from the browser (or the element could be missing, I didn't look too much into it but I got a similar error).

**Comment by natefillups** [comment]
@OCEANOFANYTHINGOFFICIAL if you're looking for a quick fix run the program with headless=false.

**Comment by OCEANOFANYTHINGOFFICIAL** [comment]
> @OCEANOFANYTHINGOFFICIAL if you're looking for a quick fix run the program with headless=false.

But won't it make the browser visible?

**Comment by natefillups** [comment]
duplicate of https://github.com/elebumm/RedditVideoMakerBot/issues/1971

**Comment by nssharmaofficial** [comment]
I had the same problem, solved it [here](https://github.com/nssharmaofficial/reddit-hole/blob/main/utils/reddit.py). I am not sure which line exactly was the one that helped it, but it might help you if you have a look at it.

**Comment by x1yl** [comment]
I seemed to manage to fix this issue by changing line 185 of screenshot_downloader.py to 
`page.locator('[data-testid="post-container"] [data-test-id="post-content"]').screenshot(path=postcontentpath)`. If your zoom is equal to 1 try this, if your zoom is not equal to 1, try aarora4's fix.
