### ISSUE TITLE
[Bug]: gtts.run() got an unexpected  keyword random_voice  crashing after saving mp3 

### ISSUE THREAD

**Issue by catspyder** [elebumm/RedditVideoMakerBot#2076]
### Describe the bug

my first run it just errored out. it did create the mp3 file before

### Reproduction Steps

Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                             │
│ Version: 3.3.0                                                                                                                                               │
│ Error: GTTS.run() got an unexpected keyword argument 'random_voice'                                                                                          │
│ Config: {'allow_nsfw': True, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False, 'storymodemethod': 1, 'storymode_max_length': 1000,     │
│ 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0, 'channel_name': 'Reddit Tales', 'background': {'background_video': 'minecraft', 'background_audio': │
│ 'lofi', 'background_audio_volume': 0.15, 'enable_extra_audio': False, 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',            │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'googletranslate', 'random_voice': True,    │
│ 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice':       │
│ 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}} 

### Expected behavior

creating  a video. no video was created

### System Information

Operating System : windows11
Python version : 3.10.1
App version / Branch : 3.3.0

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by RequieMa** [comment]
I got the same bug #2079 (which can be marked as duplicated...)
I open a git pull #2078 to fix this issue

**Comment by JasonLovesDoggo** [comment]
Fixed in #2078
