### ISSUE TITLE
Issue with Utils.vid

### ISSUE THREAD

**Issue by Shadowles19** [elebumm/RedditVideoMakerBot#208]
<img width="751" alt="Screen Shot 2022-06-03 at 11 05 13 AM" src="https://user-images.githubusercontent.com/106671929/171881018-854f4c65-e0b2-4f0f-b931-8b43bf13ac32.png">

**Comment by D3FUZED** [comment]
Could you tell me the step-by-step command you have entered to install the required libraries?

**Comment by Shadowles19** [comment]
> Could you tell me the step-by-step command you have entered to install the required libraries?

I have most installed, ive done pip install everything that comes up. But when I try and do it for this, this error comes up. 
<img width="743" alt="Screen Shot 2022-06-03 at 11 31 36 AM" src="https://user-images.githubusercontent.com/106671929/171887351-e575c798-8fc4-4941-9820-90b22b3fff57.png">

**Comment by jacesleeman** [comment]
try to redownload are run it

**Comment by jacesleeman** [comment]
> > try to redownload are run it
> 
> Python try and redownload?

the project itself
