### ISSUE TITLE
[Bug]: Code: 1, reason: probably the aid value isn't correct, message: Couldn’t load speech. Try again.

### ISSUE THREAD

**Issue by budman129** [elebumm/RedditVideoMakerBot#2098]
### Describe the bug

when i try to run the program i get hit with an error message that says "Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community." after scrolling down can also see "Code: 1, reason: probably the aid value isn't correct, message: Couldn’t load speech. Try again." not sure how to fix or why its happening as im very new to this stuff

### Reproduction Steps

i ran the program

### Expected behavior

the program to produce a video

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

py main.py

██████╗ ███████╗██████╗ ██████╗ ██╗████████╗    ██╗   ██╗██╗██████╗ ███████╗ ██████╗     ███╗   ███╗ █████╗ ██╗  ██╗███████╗██████╗
██╔══██╗██╔════╝██╔══██╗██╔══██╗██║╚══██╔══╝    ██║   ██║██║██╔══██╗██╔════╝██╔═══██╗    ████╗ ████║██╔══██╗██║ ██╔╝██╔════╝██╔══██╗
██████╔╝█████╗  ██║  ██║██║  ██║██║   ██║       ██║   ██║██║██║  ██║█████╗  ██║   ██║    ██╔████╔██║███████║█████╔╝ █████╗  ██████╔╝
██╔══██╗██╔══╝  ██║  ██║██║  ██║██║   ██║       ╚██╗ ██╔╝██║██║  ██║██╔══╝  ██║   ██║    ██║╚██╔╝██║██╔══██║██╔═██╗ ██╔══╝  ██╔══██╗
██║  ██║███████╗██████╔╝██████╔╝██║   ██║        ╚████╔╝ ██║██████╔╝███████╗╚██████╔╝    ██║ ╚═╝ ██║██║  ██║██║  ██╗███████╗██║  ██║
╚═╝  ╚═╝╚══════╝╚═════╝ ╚═════╝ ╚═╝   ╚═╝         ╚═══╝  ╚═╝╚═════╝ ╚══════╝ ╚═════╝     ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

  Thanks for using this tool! Feel free to contribute to this project on GitHub! If you have any questions, feel free to join my Discord server or submit a GitHub issue. You can find solutions to many common
                                                                   problems in the documentation: https://reddit-video-maker-bot.netlify.app/

╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ You are using the newest version (3.3.0) of the bot                                                                                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
###############################
#                             #
# Checking TOML configuration #
#                             #
###############################
If you see any prompts, that means that you have unset/incorrectly set variables, please input the correct values.
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ on the 1st iteration of 100                                                                                                                                                                                   │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Logging into Reddit.
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Getting subreddit threads...                                                                                                                                                                                  │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Using subreddit: r/AskReddit+entitledparents+EntitledKarens+EntitledBrats+ragebait from TOML config
Video will be: In honor of CrowdStrike, what was YOUR biggest work fuckup? 👍
Thread url is: https://new.reddit.com//r/AskReddit/comments/1e7i3ig/in_honor_of_crowdstrike_what_was_your_biggest/ 👍
Thread has 2275 upvotes
Thread has a upvote ratio of 94.0%
Thread has 1348 comments
Received subreddit threads Successfully.
Thread ID is 1e7i3ig
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Saving Text to MP3 files...                                                                                                                                                                                   │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                                                                              │
│ Version: 3.3.0                                                                                                                                                                                                │
│ Error: Code: 1, reason: probably the aid value isn't correct, message: Couldn’t load speech. Try again.                                                                                                       │
│ Config: {'allow_nsfw': True, 'theme': 'dark', 'times_to_run': 100, 'opacity': 0.9, 'storymode': False, 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920,        │
│ 'zoom': 1.0, 'channel_name': 'Reddit Tales', 'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15, 'enable_extra_audio': False,                        │
│ 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'tiktok',        │
│ 'random_voice': True, 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': │
│ 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "C:\Users\buddy\OneDrive\Desktop\RedditVideoMakerBot-master\main.py", line 131, in <module>
    raise err
  File "C:\Users\buddy\OneDrive\Desktop\RedditVideoMakerBot-master\main.py", line 113, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\buddy\OneDrive\Desktop\RedditVideoMakerBot-master\main.py", line 68, in run_many
    main()
  File "C:\Users\buddy\OneDrive\Desktop\RedditVideoMakerBot-master\main.py", line 50, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\buddy\OneDrive\Desktop\RedditVideoMakerBot-master\video_creation\voices.py", line 49, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\buddy\OneDrive\Desktop\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 74, in run
    self.call_tts("title", process_text(self.reddit_object["thread_title"]))
  File "C:\Users\buddy\OneDrive\Desktop\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 147, in call_tts
    self.tts_module.run(
  File "C:\Users\buddy\OneDrive\Desktop\RedditVideoMakerBot-master\TTS\TikTok.py", line 109, in run
    raise TikTokTTSException(status_code, data["message"])
TTS.TikTok.TikTokTTSException: Code: 1, reason: probably the aid value isn't correct, message: Couldn’t load speech. Try again.

**Comment by sourcite** [comment]
Was having this problem as well and found a closed issue that fixed it for me: https://github.com/elebumm/RedditVideoMakerBot/issues/1582#issuecomment-1526285672
