### ISSUE TITLE
Help with Sox?

### ISSUE THREAD

**Issue by Shadowles19** [elebumm/RedditVideoMakerBot#210]
I am getting this error
<img width="1037" alt="Screen Shot 2022-06-03 at 12 06 40 PM" src="https://user-images.githubusercontent.com/106671929/171903661-e05ee6db-1768-4f8c-b2d5-99c7c3f7bb63.png">
r

**Comment by FreebieII** [comment]
> I am getting this error <img alt="Screen Shot 2022-06-03 at 12 06 40 PM" width="1037" src="https://user-images.githubusercontent.com/106671929/171903661-e05ee6db-1768-4f8c-b2d5-99c7c3f7bb63.png"> r

Hi! 

Please double check all directory's in the code itself, as this is an issue related to filepaths.  Let me know if you are 100% sure all the paths are correlating and we'll take it from there! 🙂

**Comment by CallumIO** [comment]
SoX is not a part of our code, please create an issue in the fork's repo for better support.
