### ISSUE TITLE
Not a bug but im having difficulties installing the bot as I'm not very familiar with code please help

### ISSUE THREAD

**Issue by Chube123go** [elebumm/RedditVideoMakerBot#2101]
### Describe the bug

I've downloaded python and pip I'm pretty sure but I'm following instrucctions and it usually says it's not found or like not found command or something

### Reproduction Steps

Download the bot

### Expected behavior

For the commands to run

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by nssharmaofficial** [comment]
@Chube123go If you need simpler version with documentation, check [this repo](https://github.com/nssharmaofficial/reddit-hole).
