### ISSUE TITLE
[Bug]: voice not found?

### ISSUE THREAD

**Issue by gfraggle** [elebumm/RedditVideoMakerBot#2107]
### Describe the bug

Im sure this is just a user error issue, but im struggling here. I re downloaded and tried with a fresh version. I uninstalled and reinstalled the requirements, and yet the issue remains.

elevenlabs.core.api_error.ApiError: status_code: None, body: Voice Arnold not found. (works for none of the voices)

**Comment by gfraggle** [comment]
I managed to get the code to work for now by adjusting a few things in the elevenlabs.py not exactly sure which changed fixed the issue, but it does work. This is not to say the issue is irrelevant.

**Comment by youdeadbro28** [comment]
tell me what u changed pls

**Comment by youdeadbro28** [comment]
oh i fixed it bu replacing the last line of code to this in elevenlabs.py: return random.choice(self.client.voices.get_all().voices).name
