### ISSUE TITLE
[Bug]: Playwright install not wqorking on Arch linux

### ISSUE THREAD

**Issue by Switchman2018** [elebumm/RedditVideoMakerBot#2109]
### Describe the bug

When i run the command `python -m install playwright-deps` it gives me the error of "apt-get command not found"  

### Reproduction Steps

i used the Arch linux OS and installed the bot until the install playwright step

### Expected behavior

playwright to finish installation and be usable

### System Information

Operating System : [Arch Linux]
Python version : [e.g. Python 3.12]
App version / Branch : [latest]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by xXSamuraiX13Xx** [comment]
you have to install needed [deps](https://github.com/microsoft/playwright/issues/2621#issuecomment-931530175) manually,  this one fixed my issue, i use arch btw
