### ISSUE TITLE
[Bug]: No matching distribution found for torch

### ISSUE THREAD

**Issue by xiaofen1949** [elebumm/RedditVideoMakerBot#2117]
### Describe the bug

I got a problem When I tried to pip the requirements.txt .
error:No matching distribution found for torch
Firstly , I switched python 3.12 to 3.10 as The tutorial required , unforturnately it doesn`t work .
I searched the problem for a whole day , finally I found the solution happly.

### Reproduction Steps

I tried to pip the requirements.txt as The tutorial required  in Pycharm , but it came the error:No matching distribution found for torch.

### Expected behavior

I hoped to run the main.py 

### System Information

Operating System : [MacOS 12.6.3]
Python version : python 3.12-->3.10

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by xiaofen1949** [comment]
I tried (pip3 install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/test/cpu),it doesn`t work again.

**Comment by SeanDunford** [comment]
Found mentioned in a different thread but if you are running on an intel Mac there is no prebuilt binary for pytorch. You need to find another way to install from source. 

https://github.com/pytorch/executorch/issues/3670#issuecomment-2135102064

> @jktaotao
> 
> Is your Mac x86 based by any chance? If so, pytorch stopped publishing prebuilt pip packages since pytorch 2.3
> 
> [pytorch/pytorch#114602](https://github.com/pytorch/pytorch/issues/114602)
> 
> I'd recommend installing the pytorch 2.3 from source

**Comment by JasonLovesDoggo** [comment]
see SeanDunford's comment. Closing as this is an upstream issue
