### ISSUE TITLE
Not working with proxy.

### ISSUE THREAD

**Issue by Riceblade** [elebumm/RedditVideoMakerBot#212]
`prawcore.exceptions.RequestException: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required')))`

**Comment by LukaHietala** [comment]
You probably need to disable proxy to access the API.
