### ISSUE TITLE
[Bug]: Error Number 1

### ISSUE THREAD

**Issue by khalid-121** [elebumm/RedditVideoMakerBot#2133]
### Describe the bug

 Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the        ││ Discord community.                                                                                                   ││ Version: 3.3.0                                                                                                       ││ Error: HTTPSConnectionPool(host='api16-normal-c-useast1a.tiktokv.com', port=443): Read timed out. (read              ││ timeout=None)                                                                                                        ││ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False,                ││ 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0,         ││ 'channel_name': 'Reddit Tales', 'background': {'background_video': 'minecraft', 'background_audio': 'lofi',          ││ 'background_audio_volume': 0.15, 'enable_extra_audio': False, 'background_thumbnail': False,                         ││ 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96,                                   ││ 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'tiktok', 'random_voice': True,           ││ 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew',                    ││ 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice':    ││ '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                                              │╰───────

### Reproduction Steps

I dont know i did everything correctly and it still happened

### Expected behavior

i expected it to run perfectly fine

### Screenshots

![Capture](https://github.com/user-attachments/assets/7c83db89-e50d-41c1-b953-a10a94f59955)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

i tried and searched everywhere

**Comment by JasonLovesDoggo** [comment]
Just a temporary network issue
