### ISSUE TITLE
Errno 2 No such file or directory: 'ffprobe' 

### ISSUE THREAD

**Issue by ChewyKaren** [elebumm/RedditVideoMakerBot#2137]
### Describe the bug

After I run it main.py it will get all the way to creating the video but then it gives me Errno 2 saying 'ffprobe' file or directory doesn't exist. I ensured that the ffprobe requirement is met and FFmpeg is working too. I don't quite know what the issue is. 

### Reproduction Steps

Ran main.py 

### Expected behavior

It would work 

### Screenshots

╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                                                                             │
│ Version: 3.3.0                                                                                                                                                                                               │
│ Error: [Errno 2] No such file or directory: 'ffprobe'                                                                                                                                                        │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': True, 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': │
│ 1.0, 'channel_name': 'Reddit Tales', 'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15, 'enable_extra_audio': False, 'background_thumbnail':       │
│ False, 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'streamlabspolly', 'random_voice':      │
│ True, 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED',    │
│ 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "/Users/-----/Downloads/RedditVideoMakerBot-3.3.0/main.py", line 131, in <module>
    raise err
  File "/Users/-----/Downloads/RedditVideoMakerBot-3.3.0/main.py", line 113, in <module>
    run_many(config["settings"]["times_to_run"])
  File "/Users/-----/Downloads/RedditVideoMakerBot-3.3.0/main.py", line 68, in run_many
    main()
  File "/Users/-----/Downloads/RedditVideoMakerBot-3.3.0/main.py", line 60, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "/Users/-----/Downloads/RedditVideoMakerBot-3.3.0/video_creation/final_video.py", line 289, in make_final_video
    audio_clips_durations = [
  File "/Users/------/Downloads/RedditVideoMakerBot-3.3.0/video_creation/final_video.py", line 291, in <listcomp>
    ffmpeg.probe(f"assets/temp/{reddit_id}/mp3/postaudio-{i}.mp3")["format"]["duration"]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ffmpeg/_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'

### System Information

Operating System : MacOS Sonoma 14.6.1
Python version : 3.10
App version / Branch : 

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.

**Comment by JasonLovesDoggo** [comment]
this is due to ffmpeg's install location not being in your path. Please add it there
