### ISSUE TITLE
[Bug]: 'pip' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by cantre11** [elebumm/RedditVideoMakerBot#2145]
### Describe the bug

i get ,'pip' is not recognized as an internal or external command,
operable program or batch file. when trying to run  pip install -r requirements.txt

### Reproduction Steps

i installed everything as instructed

### Expected behavior

to install the pavkages

### Screenshots

![image](https://github.com/user-attachments/assets/ef2b5176-5f92-4954-a76b-875e6f2163d3)

### System Information

Operating System : [e.g. Windows 11]
Python version : Python 3.10]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by JasonLovesDoggo** [comment]
please install pip https://pip.pypa.io/en/stable/installation/


this is not an issue here.
