### ISSUE TITLE
[Bug]: Linux issues

### ISSUE THREAD

**Issue by ngmisl** [elebumm/RedditVideoMakerBot#2148]
### Describe the bug

  File "/home/n/dev/python/RedditVideoMakerBot/main.py", line 9, in <module>
    from prawcore import ResponseException
ModuleNotFoundError: No module named 'prawcore'

### Reproduction Steps

py main.py

### Expected behavior

work

### System Information

Operating System : Ubuntu
Python version : 3.10.13
App version / Branch : main

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Roostydoo2** [comment]
sudo apt update
pip3 install -r requirements.txt

**Comment by Motzumoto** [comment]
For someone whos on linux you clearly dont know what you're doing.

**Comment by JasonLovesDoggo** [comment]
See @Motzumoto's comment

This is user error
