### ISSUE TITLE
Getting This error

### ISSUE THREAD

**Issue by mdyaqub14** [elebumm/RedditVideoMakerBot#216]
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/13606937/171910637-c13b02a2-12ab-4a0c-a400-9ec21a5d5ebd.png">

**Comment by jayc331** [comment]
I was getting that error when using "r/AskReddit" rather than "https://www.reddit.com/u/AskReddit".

Though, that only changed it from an error code 400 to error code 404.

![image](https://user-images.githubusercontent.com/105918957/171913837-918d5c60-514d-437a-a36e-518f76283dc3.png)

**Comment by mdyaqub14** [comment]
@jayc331 just dont put theme and subreddit in env keep them blank
it will ask for the subreddit later in code
