### ISSUE TITLE
how do i choose a custom subreddit?

### ISSUE THREAD

**Issue by bxvlz2** [elebumm/RedditVideoMakerBot#217]
in the code and updates it states that you can use a custom subreddit but how do I chose it??
![image](https://user-images.githubusercontent.com/106701216/171911418-86b98427-9c4a-468f-ac2a-bee23fc7d29a.png)

**Comment by CallumIO** [comment]
In your `.env` file set the `SUBREDDIT` to the subreddit name, without the r/ (e.g. r/askreddit would become askreddit).
