### ISSUE TITLE
Cannot install  -r requirements.txt, regex is failing to install, but I have the most recent version of Microsoft Visual C++

### ISSUE THREAD

**Issue by Ruben-Prata** [elebumm/RedditVideoMakerBot#218]
![Screenshot_3](https://user-images.githubusercontent.com/106801456/171914027-426700d0-fab6-43fc-b986-3c93e5f91299.png)
![Screenshot_2](https://user-images.githubusercontent.com/106801456/171914030-03fe0605-aa30-4492-9253-9c32d830fe7c.png)

**Comment by rgfdfdg** [comment]
Install Python 3.8

**Comment by CallumIO** [comment]
Re-clone the repo. Just merged #164 which should fix this

**Comment by Ruben-Prata** [comment]
> Re-clone the repo. Just merged #164 which should fix this

Worked fine. Thanks!
