### ISSUE TITLE
[Bug]: screenshots fail to be taken

### ISSUE THREAD

**Issue by Gaming8288383838** [elebumm/RedditVideoMakerBot#2183]
### Describe the bug

Screens shots fail to be taken 

### Reproduction Steps

Ran python main.py

### Expected behavior

take the screen shots

### Screenshots

![Screenshot (2)](https://github.com/user-attachments/assets/557990ea-dedc-4aa7-af50-d09a3df3f9e9)

### System Information

Operating System :  [windows 10]
Python version : [Python 3.10.0]
App version / Branch :latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Gaming8288383838** [comment]
any fixes? this issue better not be ignored

**Comment by mmnsrti** [comment]
hello i encountered the same issue 
`(venv) (base) PS E:\app\RedditVideoMakerBot> 
(venv) (base) PS E:\app\RedditVideoMakerBot> python main.py                   

██████╗ ███████╗██████╗ ██████╗ ██╗████████╗    ██╗   ██╗██╗██████╗ ███████╗ ██████╗     ███╗   ███╗ █████╗ ██╗  ██╗███████╗██████╗
██╔══██╗██╔════╝██╔══██╗██╔══██╗██║╚══██╔══╝    ██║   ██║██║██╔══██╗██╔════╝██╔═══██╗    ████╗ ████║██╔══██╗██║ ██╔╝██╔════╝██╔══██╗
██████╔╝█████╗  ██║  ██║██║  ██║██║   ██║       ██║   ██║██║██║  ██║█████╗  ██║   ██║    ██╔████╔██║███████║█████╔╝ █████╗  ██████╔╝
██╔══██╗██╔══╝  ██║  ██║██║  ██║██║   ██║       ╚██╗ ██╔╝██║██║  ██║██╔══╝  ██║   ██║    ██║╚██╔╝██║██╔══██║██╔═██╗ ██╔══╝  ██╔══██╗
██║  ██║███████╗██████╔╝██████╔╝██║   ██║        ╚████╔╝ ██║██████╔╝███████╗╚██████╔╝    ██║ ╚═╝ ██║██║  ██║██║  ██╗███████╗██║  ██║
══════╝╚═╝  ╚═╝



   Thanks for using this tool! Feel free to contribute to this project on GitHub! If you have any questions, feel
   free to join my Discord server or submit a GitHub issue. You can find solutions to many common problems in the
                             documentation: https://reddit-video-maker-bot.netlify.app/


╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ You are using the newest version (3.3.0) of the bot                                                               │╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯###############################
#                             #
# Checking TOML configuration #
#                             #
###############################
If you see any prompts, that means that you have unset/incorrectly set variables, please input the correct values.
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ on the 1st iteration of 1                                                                                         │╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Logging into Reddit.
Version 7.7.1 of praw is outdated. Version 7.8.1 was released Friday October 25, 2024.
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ Getting subreddit threads...                                                                                      │╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Using subreddit:
r/AskReddit+EntitledParents+ProRevenge+MaliciousCompliance+TodayIWIA+TalesFromRetail+Relationships+ChoosingBeggars+TIFU+LetsNotMeet+AITA+HumansBeingBros+Confession+TrueOffMyChest+NuclearRevenge+LifeProTips+AskWomen+Paranormal+UnresolvedMysteries+WholesomeStories+Glitch_in_the_Matrix from TOML config
NSFW Post Detected. Skipping...
Video will be: LPT: Some gyms are extremely cheap lifehack for homeless, vanlife, or commuters. 👍
Thread url is: https://new.reddit.com//r/LifeProTips/comments/1glsho4/lpt_some_gyms_are_extremely_cheap_lifehack_for/👍
Thread has 809 upvotes
Thread has a upvote ratio of 88.0%
Thread has 51 comments
Received subreddit threads Successfully.
Thread ID is 1glsho4
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ Saving Text to MP3 files...                                                                                       │╰───────────────────────────────────────────────────────────────────────────────────────────────────Saving... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.5 it/s
Saved Text to MP3 files successfully.
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Downloading screenshots of reddit posts...                                                                                                                          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Launching Headless Browser...
Logging in to Reddit...
Skipping translation...
Something went wrong!
Something went wrong with making the screenshots! Do you want to skip the post? (y/n) y
The post is successfully skipped! You can now restart the program and this post will skipped.
Do you want the error traceback for debugging purposes? (y/n)y
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                                    │
│ Version: 3.3.0                                                                                                                                                      │
│ Error: Locator.screenshot: Timeout 30000ms exceeded.                                                                                                                │
│ Call log:                                                                                                                                                           │
│ waiting for locator("[data-test-id=\"post-content\"]")                                                                                                              │
│                                                                                                                                                                     │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False, 'storymodemethod': 1, 'storymode_max_length': 1000,           │
│ 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0, 'channel_name': 'Reddit Tales', 'background': {'background_video': 'minecraft', 'background_audio':        │
│ 'lofi', 'background_audio_volume': 0.15, 'enable_extra_audio': False, 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',                   │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'streamlabspolly', 'random_voice': True,           │
│ 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', │
│ 'tiktok_sessionid': 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "E:\app\RedditVideoMakerBot\main.py", line 131, in <module>
    raise err
  File "E:\app\RedditVideoMakerBot\main.py", line 113, in <module>
    run_many(config["settings"]["times_to_run"])
  File "E:\app\RedditVideoMakerBot\main.py", line 68, in run_many
    main()
  File "E:\app\RedditVideoMakerBot\main.py", line 52, in main
    get_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "E:\app\RedditVideoMakerBot\video_creation\screenshot_downloader.py", line 203, in get_screenshots_of_reddit_posts
    raise e
  File "E:\app\RedditVideoMakerBot\video_creation\screenshot_downloader.py", line 185, in get_screenshots_of_reddit_posts
    page.locator('[data-test-id="post-content"]').screenshot(path=postcontentpath)
  File "E:\app\RedditVideoMakerBot\venv\lib\site-packages\playwright\sync_api\_generated.py", line 16703, in screenshot
    self._sync(
  File "E:\app\RedditVideoMakerBot\venv\lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
  File "E:\app\RedditVideoMakerBot\venv\lib\site-packages\playwright\_impl\_locator.py", line 531, in screenshot
    return await self._with_element(
  File "E:\app\RedditVideoMakerBot\venv\lib\site-packages\playwright\_impl\_locator.py", line 108, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "E:\app\RedditVideoMakerBot\venv\lib\site-packages\playwright\_impl\_locator.py", line 311, in element_handle
    handle = await self._frame.wait_for_selector(
  File "E:\app\RedditVideoMakerBot\venv\lib\site-packages\playwright\_impl\_frame.py", line 323, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "E:\app\RedditVideoMakerBot\venv\lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "E:\app\RedditVideoMakerBot\venv\lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.screenshot: Timeout 30000ms exceeded.
Call log:
waiting for locator("[data-test-id=\"post-content\"]")

(venv) (base) PS E:\app\RedditVideoMakerBot> `

**Comment by TheGreenJoker** [comment]
Same issue Today at the '9/11/2024'

**Comment by penguin321** [comment]
> Feel free to try #2151 to see if it fixes

Pulled #2151 but now fails here:

![image](https://github.com/user-attachments/assets/019f3835-f946-428c-be7a-23c5acca8700)

```
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                                                                              │
│ Version: 3.3.0                                                                                                                                                                                                │
│ Error: Page.goto: NS_BINDING_ABORTED                                                                                                                                                                          │
│ Call log:                                                                                                                                                                                                     │
│ navigating to "https://new.reddit.com/r/AskReddit/comments/1gr6svg/married_men_over_30_what_kind_of_hobbies_do_you/lx3h9rt/", waiting until "load"                                                            │
│                                                                                                                                                                                                               │
│ Config: {'allow_nsfw': True, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False, 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom':  │
│ 1.0, 'channel_name': 'Reddit Tales', 'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15, 'enable_extra_audio': False, 'background_thumbnail': False, │
│ 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'pyttsx', 'random_voice': True,                 │
│ 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED',           │
│ 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                                                                                                                       │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "C:\Users\ms\Desktop\RedditVideoMakerBot\main.py", line 131, in <module>
    raise err
  File "C:\Users\ms\Desktop\RedditVideoMakerBot\main.py", line 113, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\ms\Desktop\RedditVideoMakerBot\main.py", line 68, in run_many
    main()
  File "C:\Users\ms\Desktop\RedditVideoMakerBot\main.py", line 52, in main
    get_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "C:\Users\ms\Desktop\RedditVideoMakerBot\video_creation\screenshot_downloader.py", line 227, in get_screenshots_of_reddit_posts
    page.goto(f"https://new.reddit.com{comment['comment_url']}")
  File "C:\Users\ms\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\sync_api\_generated.py", line 8686, in goto
    self._sync(
  File "C:\Users\ms\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
  File "C:\Users\ms\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_page.py", line 519, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Users\ms\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\ms\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\ms\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: Page.goto: NS_BINDING_ABORTED
Call log:
navigating to "https://new.reddit.com/r/AskReddit/comments/1gr6svg/married_men_over_30_what_kind_of_hobbies_do_you/lx3h9rt/", waiting until "load"
```

**Comment by Luuna6** [comment]
same

> > Feel free to try #2151 to see if it fixes
> 
> Pulled #2151 but now fails here:
> 
> ![image](https://private-user-images.githubusercontent.com/67345594/386361041-019f3835-f946-428c-be7a-23c5acca8700.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3MDY0NTksIm5iZiI6MTczMTcwNjE1OSwicGF0aCI6Ii82NzM0NTU5NC8zODYzNjEwNDEtMDE5ZjM4MzUtZjk0Ni00MjhjLWJlN2EtMjNjNWFjY2E4NzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDIxMjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNDZlMDFkM2VkYWRkNzYyMWRmOGYzNDQ3ZGFjNGJjNTVmZDNhOTczNzFhNTA5YzZjNTcxY2VhODhiOGI1YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QcRFvtYqmsW_tB5wotLPQZpprBLL84pVdSrJcdovMus)
> 
> ```
> ╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
> │ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                                                                              │
> │ Version: 3.3.0                                                                                                                                                                                                │
> │ Error: Page.goto: NS_BINDING_ABORTED                                                                                                                                                                          │
> │ Call log:                                                                                                                                                                                                     │
> │ navigating to "https://new.reddit.com/r/AskReddit/comments/1gr6svg/married_men_over_30_what_kind_of_hobbies_do_you/lx3h9rt/", waiting until "load"                                                            │
> │                                                                                                                                                                                                               │
> │ Config: {'allow_nsfw': True, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False, 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom':  │
> │ 1.0, 'channel_name': 'Reddit Tales', 'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15, 'enable_extra_audio': False, 'background_thumbnail': False, │
> │ 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'pyttsx', 'random_voice': True,                 │
> │ 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED',           │
> │ 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                                                                                                                       │
> ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
> Traceback (most recent call last):
>   File "C:\Users\ms\Desktop\RedditVideoMakerBot\main.py", line 131, in <module>
>     raise err
>   File "C:\Users\ms\Desktop\RedditVideoMakerBot\main.py", line 113, in <module>
>     run_many(config["settings"]["times_to_run"])
>   File "C:\Users\ms\Desktop\RedditVideoMakerBot\main.py", line 68, in run_many
>     main()
>   File "C:\Users\ms\Desktop\RedditVideoMakerBot\main.py", line 52, in main
>     get_screenshots_of_reddit_posts(reddit_object, number_of_comments)
>   File "C:\Users\ms\Desktop\RedditVideoMakerBot\video_creation\screenshot_downloader.py", line 227, in get_screenshots_of_reddit_posts
>     page.goto(f"https://new.reddit.com{comment['comment_url']}")
>   File "C:\Users\ms\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\sync_api\_generated.py", line 8686, in goto
>     self._sync(
>   File "C:\Users\ms\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
>     return task.result()
>   File "C:\Users\ms\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_page.py", line 519, in goto
>     return await self._main_frame.goto(**locals_to_params(locals()))
>   File "C:\Users\ms\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_frame.py", line 145, in goto
>     await self._channel.send("goto", locals_to_params(locals()))
>   File "C:\Users\ms\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 59, in send
>     return await self._connection.wrap_api_call(
>   File "C:\Users\ms\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
>     raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
> playwright._impl._errors.Error: Page.goto: NS_BINDING_ABORTED
> Call log:
> navigating to "https://new.reddit.com/r/AskReddit/comments/1gr6svg/married_men_over_30_what_kind_of_hobbies_do_you/lx3h9rt/", waiting until "load"
> ```

same problem
![image](https://github.com/user-attachments/assets/67d8c855-b792-4466-b97d-b15fd1fffcd8)

**Comment by Janxyxy** [comment]
Reddit might have updated their ID styles for comment elements. The old selector:
`page.locator(f"#t1_{comment['comment_id']}").screenshot(path=f"assets/temp/{reddit_id}/png/comment_{idx}.png")`
I updated the selector to:
`page.locator(f"#t1_{comment['comment_id']}-comment-rtjson-content").screenshot(path=f"assets/temp/{reddit_id}/png/comment_{idx}.png")`

Now it matches the current ID structure, and the script works again.

**Comment by eyaadi** [comment]
where are the lines

**Comment by eyaadi** [comment]
okay so to make the solution easier just go to the video creation file and then go to the screenshot downloader.py file then copy and paste this code make sure to replace it "import json
import re
from pathlib import Path
from typing import Dict, Final

import translators
from playwright.sync_api import ViewportSize, sync_playwright
from rich.progress import track

from utils import settings
from utils.console import print_step, print_substep
from utils.imagenarator import imagemaker
from utils.playwright import clear_cookie_by_name
from utils.videos import save_data

__all__ = ["get_screenshots_of_reddit_posts"]


def get_screenshots_of_reddit_posts(reddit_object: dict, screenshot_num: int):
    """Downloads screenshots of reddit posts as seen on the web. Downloads to assets/temp/png

    Args:
        reddit_object (Dict): Reddit object received from reddit/subreddit.py
        screenshot_num (int): Number of screenshots to download
    """
    # settings values
    W: Final[int] = int(settings.config["settings"]["resolution_w"])
    H: Final[int] = int(settings.config["settings"]["resolution_h"])
    lang: Final[str] = settings.config["reddit"]["thread"]["post_lang"]
    storymode: Final[bool] = settings.config["settings"]["storymode"]

    print_step("Downloading screenshots of reddit posts...")
    reddit_id = re.sub(r"[^\w\s-]", "", reddit_object["thread_id"])
    # ! Make sure the reddit screenshots folder exists
    Path(f"assets/temp/{reddit_id}/png").mkdir(parents=True, exist_ok=True)

    # set the theme and disable non-essential cookies
    if settings.config["settings"]["theme"] == "dark":
        cookie_file = open("./video_creation/data/cookie-dark-mode.json", encoding="utf-8")
        bgcolor = (33, 33, 36, 255)
        txtcolor = (240, 240, 240)
        transparent = False
    elif settings.config["settings"]["theme"] == "transparent":
        if storymode:
            # Transparent theme
            bgcolor = (0, 0, 0, 0)
            txtcolor = (255, 255, 255)
            transparent = True
            cookie_file = open("./video_creation/data/cookie-dark-mode.json", encoding="utf-8")
        else:
            # Switch to dark theme
            cookie_file = open("./video_creation/data/cookie-dark-mode.json", encoding="utf-8")
            bgcolor = (33, 33, 36, 255)
            txtcolor = (240, 240, 240)
            transparent = False
    else:
        cookie_file = open("./video_creation/data/cookie-light-mode.json", encoding="utf-8")
        bgcolor = (255, 255, 255, 255)
        txtcolor = (0, 0, 0)
        transparent = False

    if storymode and settings.config["settings"]["storymodemethod"] == 1:
        # for idx,item in enumerate(reddit_object["thread_post"]):
        print_substep("Generating images...")
        return imagemaker(
            theme=bgcolor,
            reddit_obj=reddit_object,
            txtclr=txtcolor,
            transparent=transparent,
        )

    screenshot_num: int
    with sync_playwright() as p:
        print_substep("Launching Headless Browser...")

        browser = p.chromium.launch(
            headless=True
        )  # headless=False will show the browser for debugging purposes
        # Device scale factor (or dsf for short) allows us to increase the resolution of the screenshots
        # When the dsf is 1, the width of the screenshot is 600 pixels
        # so we need a dsf such that the width of the screenshot is greater than the final resolution of the video
        dsf = (W // 600) + 1

        context = browser.new_context(
            locale=lang or "en-us",
            color_scheme="dark",
            viewport=ViewportSize(width=W, height=H),
            device_scale_factor=dsf,
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
        )
        cookies = json.load(cookie_file)
        cookie_file.close()

        context.add_cookies(cookies)  # load preference cookies

        # Login to Reddit
        print_substep("Logging in to Reddit...")
        page = context.new_page()
        page.goto("https://www.reddit.com/login", timeout=0)
        page.set_viewport_size(ViewportSize(width=1920, height=1080))
        page.wait_for_load_state()

        page.locator(f'input[name="username"]').fill(settings.config["reddit"]["creds"]["username"])
        page.locator(f'input[name="password"]').fill(settings.config["reddit"]["creds"]["password"])
        page.get_by_role("button", name="Log In").click()
        page.wait_for_timeout(5000)

        login_error_div = page.locator(".AnimatedForm__errorMessage").first
        if login_error_div.is_visible():
            login_error_message = login_error_div.inner_text()
            if login_error_message.strip() == "":
                # The div element is empty, no error
                pass
            else:
                # The div contains an error message
                print_substep(
                    "Your reddit credentials are incorrect! Please modify them accordingly in the config.toml file.",
                    style="red",
                )
                exit()
        else:
            pass

        page.wait_for_load_state()
        # Handle the redesign
        # Check if the redesign optout cookie is set
        if page.locator("#redesign-beta-optin-btn").is_visible():
            # Clear the redesign optout cookie
            clear_cookie_by_name(context, "redesign_optout")
            # Reload the page for the redesign to take effect
            page.reload()
        # Get the thread screenshot
        page.goto(reddit_object["thread_url"], timeout=0)
        page.set_viewport_size(ViewportSize(width=W, height=H))
        page.wait_for_load_state()
        page.wait_for_timeout(5000)

        if page.locator(
            "#t3_12hmbug > div > div._3xX726aBn29LDbsDtzr_6E._1Ap4F5maDtT1E1YuCiaO0r.D3IL3FD0RFy_mkKLPwL4 > div > div > button"
        ).is_visible():
            # This means the post is NSFW and requires to click the proceed button.

            print_substep("Post is NSFW. You are spicy...")
            page.locator(
                "#t3_12hmbug > div > div._3xX726aBn29LDbsDtzr_6E._1Ap4F5maDtT1E1YuCiaO0r.D3IL3FD0RFy_mkKLPwL4 > div > div > button"
            ).click()
            page.wait_for_load_state()  # Wait for page to fully load

            # translate code
        if page.locator(
            "#SHORTCUT_FOCUSABLE_DIV > div:nth-child(7) > div > div > div > header > div > div._1m0iFpls1wkPZJVo38-LSh > button > i"
        ).is_visible():
            page.locator(
                "#SHORTCUT_FOCUSABLE_DIV > div:nth-child(7) > div > div > div > header > div > div._1m0iFpls1wkPZJVo38-LSh > button > i"
            ).click()  # Interest popup is showing, this code will close it

        if lang:
            print_substep("Translating post...")
            texts_in_tl = translators.translate_text(
                reddit_object["thread_title"],
                to_language=lang,
                translator="google",
            )

            page.evaluate(
                "tl_content => document.querySelector('[data-adclicklocation=\"title\"] > div > div > h1').textContent = tl_content",
                texts_in_tl,
            )
        else:
            print_substep("Skipping translation...")

        postcontentpath = f"assets/temp/{reddit_id}/png/title.png"
        try:
            if settings.config["settings"]["zoom"] != 1:
                # store zoom settings
                zoom = settings.config["settings"]["zoom"]
                # zoom the body of the page
                page.evaluate("document.body.style.zoom=" + str(zoom))
                # as zooming the body doesn't change the properties of the divs, we need to adjust for the zoom
                location = page.locator('h1[slot="title"]').bounding_box()
                for i in location:
                    location[i] = float("{:.2f}".format(location[i] * zoom))
                page.screenshot(clip=location, path=postcontentpath)
            else:
                page.locator('h1[slot="title"]').screenshot(path=postcontentpath)
        except Exception as e:
            print_substep("Something went wrong!", style="red")
            resp = input(
                "Something went wrong with making the screenshots! Do you want to skip the post? (y/n) "
            )

            if resp.casefold().startswith("y"):
                save_data("", "", "skipped", reddit_id, "")
                print_substep(
                    "The post is successfully skipped! You can now restart the program and this post will skipped.",
                    "green",
                )

            resp = input("Do you want the error traceback for debugging purposes? (y/n)")
            if not resp.casefold().startswith("y"):
                exit()

            raise e

        if storymode:
            page.locator('[data-click-id="text"]').first.screenshot(
                path=f"assets/temp/{reddit_id}/png/story_content.png"
            )
        else:
            for idx, comment in enumerate(
                track(
                    reddit_object["comments"][:screenshot_num],
                    "Downloading screenshots...",
                )
            ):
                # Stop if we have reached the screenshot_num
                if idx >= screenshot_num:
                    break

                if page.locator('[data-testid="content-gate"]').is_visible():
                    page.locator('[data-testid="content-gate"] button').click()

                page.goto(f"https://new.reddit.com/{comment['comment_url']}")

                # translate code

                if settings.config["reddit"]["thread"]["post_lang"]:
                    comment_tl = translators.translate_text(
                        comment["comment_body"],
                        translator="google",
                        to_language=settings.config["reddit"]["thread"]["post_lang"],
                    )
                    page.evaluate(
                        '([tl_content, tl_id]) => document.querySelector(`#t1_${tl_id}-comment-rtjson-content p`).textContent = tl_content',
                        [comment_tl, comment["comment_id"]]
                    )
                try:
                    if settings.config["settings"]["zoom"] != 1:
                        # click on button to close replies so that they are not shown in the video
                        page.locator("button[aria-controls=\"comment-children\"]").first.click()
                        # zoom the body of the page
                        page.evaluate("document.body.style.zoom=" + str(zoom))
                        # scroll comment into view
                        page.locator(f"#t1_{comment['comment_id']}").scroll_into_view_if_needed()
                        # as zooming the body doesn't change the properties of the divs, we need to adjust for the zoom
                        location = page.locator(f"shreddit-comment[thingid=\"t1_{comment['comment_id']}\"]").bounding_box()
                        for i in location:
                            location[i] = float("{:.2f}".format(location[i] * zoom))
                        page.screenshot(
                            clip=location,
                            path=f"assets/temp/{reddit_id}/png/comment_{idx}.png",
                        )
                    else:
                        # click on button to close replies so that they are not shown in the video
                        page.locator("button[aria-controls=\"comment-children\"]").first.click()
                        page.locator(f"shreddit-comment[thingid=\"t1_{comment['comment_id']}\"]").screenshot(
                            path=f"assets/temp/{reddit_id}/png/comment_{idx}.png"
                        )
                        
                except TimeoutError:
                    del reddit_object["comments"]
                    screenshot_num += 1
                    print("TimeoutError: Skipping screenshot...")
                    continue

        # close browser instance when we are done using it
        browser.close()

    print_substep("Screenshots downloaded Successfully.", style="bold green")"

**Comment by TanmayChachra** [comment]
The issue is still there as of 29/11/2024

**Comment by eyaadi** [comment]
they should update prawcore
and elevenllanbs

**Comment by sarimwaniR** [comment]
@eyaadi after you're fix now it stuck here
![image](https://github.com/user-attachments/assets/373e6f0d-69f0-4e91-815e-0c5886d58ee4)

**Comment by sarimwaniR** [comment]
![image](https://github.com/user-attachments/assets/ee08ffd7-56b8-480d-8053-a2ce7005d294)

**Comment by sarimwaniR** [comment]
I am using steam labs voice...

**Comment by Neo19867** [comment]
same problems

**Comment by justsnom** [comment]
> okay so to make the solution easier just go to the video creation file and then go to the screenshot downloader.py file then copy and paste this code make sure to replace it, code can be found on this pastebin https://pastebin.com/raw/FFZryj46

this definitely works but only sometimes! it seems like it gets stuck on specific posts with this and even after turning on random it won't give me a new one every time. it doesnt prompt to skip either. is there any command to skip a particular reddit thread or some other suggestion for this?
