### ISSUE TITLE
Any solution for time exceed 3000

### ISSUE THREAD

**Issue by mdyaqub14** [elebumm/RedditVideoMakerBot#219]
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/13606937/171915485-3f8c344c-3342-48fd-b1d8-2d5dfa6f7179.png">

**Comment by LukaHietala** [comment]
Did you try to run the program again? And is your THEME valid?

**Comment by mdyaqub14** [comment]
I did many times, whats a valid theme? I am keeping it blank, can you hook me up with some example for valid theme

**Comment by CallumIO** [comment]
Closing due to being stale and fix being implemented
