### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Mxyukh10** [elebumm/RedditVideoMakerBot#2216]
### Describe the bug

![image](https://github.com/user-attachments/assets/3fe475fc-d6a2-4c70-abcf-442dcae868da)
How do I fix this error while installing packages?

### Reproduction Steps

I ran the installing packages code on cmd but it didn't work.

### Expected behavior

It was supposed to run it successfully.

### Screenshots

![image](https://github.com/user-attachments/assets/0214bb12-90a7-4e5a-bc69-96a81ffc3acc)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by JasonLovesDoggo** [comment]
this is not an issue with the bot. If you would like help installing it please ask on the discord
