### ISSUE TITLE
Includes deleted messages

### ISSUE THREAD

**Issue by jayc331** [elebumm/RedditVideoMakerBot#222]
![image](https://user-images.githubusercontent.com/105918957/171916664-b2c3032a-03a2-4fde-b28a-6e63788e3026.png)

She says "deleeeted".

**Comment by jayc331** [comment]
Also shows the cookies in the screenshot 

![image](https://user-images.githubusercontent.com/105918957/171918629-a3fd2819-35f3-4153-b75b-8e3275f4aaf8.png)

**Comment by JasonLovesDoggo** [comment]
fixed on my fork
