### ISSUE TITLE
When using the command python3

### ISSUE THREAD

**Issue by W-key12** [elebumm/RedditVideoMakerBot#224]
When using the command python3 main.py an error occurs

Error:
<img width="577" alt="Screenshot 2022-06-03 at 19 13 07" src="https://user-images.githubusercontent.com/75755390/171922354-7bbdd1ff-0302-44d6-a09a-05f5dcdde6f0.png">

I tried but I couldn't use. npx playwright install. I'm on Macos
This is the npx playwright install error
<img width="577" alt="Screenshot 2022-06-03 at 19 12 34" src="https://user-images.githubusercontent.com/75755390/171922287-bff501d0-7c18-4628-8b57-fa34868ca7d2.png">

**Comment by LukaHietala** [comment]
You can try to use `pip install playwright` or if that does not work you can also try this second method `pip3 install playwright`. I hope that my solutions fix your problem. 👍

**Comment by W-key12** [comment]
> You can try to use `pip install playwright` or if that does not work you can also try this second method `pip3 install playwright`. I hope that my solutions fix your problem. 👍

Thanks it worked :)
