### ISSUE TITLE
Idea / Feature list (Will edit as we go)

### ISSUE THREAD

**Issue by MrSataana** [elebumm/RedditVideoMakerBot#225]
Sort of "wishlist" that I am waiting / hoping for

- [ ] Option to read the OP post as well as the Title (if available)

- [ ] Option for different (better?) voices

- [ ] Option to set a duration (To decide how long a video would be)

- [ ] Option to choose between HOT / TOP threads / comments

- [ ] Option to choose own background video

- [ ] Option to choose own / none background music

- [ ] Option for Landscape / Portrait mode (seems to generate them either at random atm)

- [ ] Option to include images in the OP / Comments if present

- [ ] Ignore Bot comments

- [x] Get rid of Cookie popup in screenshots

- [ ] Allow / Do not allow NSFW

- [ ] Toggle Text / Image only posts

- [ ] Insert slight TTS pause between posts

- [x] Name the final video file as the topic of the reddit thread

- [x] Support different languages

- [x] Skip threads already done (check using video file names?)

- [ ] Prompt to repeat script

- [x] Option to define specific thread

- [x] Option to position images anywhere on video

- [x] Remove special characters from TTS

- [ ] Option for intro / outro

- [x] Ignore links in comments for TTS

**Comment by JasonLovesDoggo** [comment]
>   Skip threads already done (check using video file names?)

see https://github.com/JasonLovesDoggo/RedditVideoMakerBot/commit/8b5670a8ebe17e8fa4f2bac00cb7ae2d40d5b290


>  Option for different (better?) voices
>  Option to set a duration (To decide how long a video would be)



both exist on [my fork](https://github.com/JasonLovesDoggo/RedditVideoMakerBot).

**Comment by ImmaHarry** [comment]
Noted, thank you!

**Comment by iaacornus** [comment]
the options to choose own background video is addressed in #280 as a parameter in cli, although currently  it only accepts link as an input.

**Comment by null3000** [comment]
>     * [ ]  Ignore links in comments for TTS

Done. Wrote a new PR. PR [311 ](https://github.com/elebumm/RedditVideoMakerBot/pull/311)

**Comment by MrSataana** [comment]
Awesome peeps!
Will be ticked off when things are merged and confirmed working :)

**Comment by nexuspcs** [comment]
> >   Skip threads already done (check using video file names?)
> 
> 
> 
> see https://github.com/JasonLovesDoggo/RedditVideoMakerBot/commit/8b5670a8ebe17e8fa4f2bac00cb7ae2d40d5b290
> 
> 
> 
> 
> 
> >  Option for different (better?) voices
> 
> >  Option to set a duration (To decide how long a video would be)
> 
> 
> 
> 
> 
> 
> 
> both exist on [my fork](https://github.com/JasonLovesDoggo/RedditVideoMakerBot).
> 
>  

You are a legend my man!

**Comment by JasonLovesDoggo** [comment]
> >   Skip threads already done (check using video file names?)
> 
> see https://github.com/JasonLovesDoggo/RedditVideoMakerBot/commit/8b5670a8ebe17e8fa4f2bac00cb7ae2d40d5b290
> 
> 
> >  Option for different (better?) voices
> >  Option to set a duration (To decide how long a video would be)
> 
> 
> 
> both exist on [my fork](https://github.com/JasonLovesDoggo/RedditVideoMakerBot).
>  

I now also have
 Option to define specific thread
 Option to set a duration (To decide how long a video would be) 
 Option to choose own background video 
 Ignore Bot comments 
  Get rid of Cookie popup in screenshots 
  Allow / Do not allow NSFW 
  Name the final video file as the topic of the reddit thread  
   Option to define specific thread 
    Remove special characters from TTS
    Ignore links in comments for TTS

**Comment by JasonLovesDoggo** [comment]
wont be used.
