### ISSUE TITLE
Videos extend beyond 60 seconds

### ISSUE THREAD

**Issue by jayc331** [elebumm/RedditVideoMakerBot#227]
TBH I'm not sure whether this was the intended feature, but the videos are short (as you'd expect), yet extend past 60s meaning they cannot be uploaded to youtube as shorts.

Could this either be patched to stop them proceeding beyond 60s, or maybe add an option for a max and min length so people can customise them.

Thanks

**Comment by FreebieII** [comment]
> TBH I'm not sure whether this was the intended feature, but the videos are short (as you'd expect), yet extend past 60s meaning they cannot be uploaded to youtube as shorts.
> 
> Could this either be patched to stop them proceeding beyond 60s, or maybe add an option for a max and min length so people can customise them.
> 
> Thanks

In voices.py you'll see a code block that looks like this

` if length > 50:`
            `break`
This means it'll stop grabbing comments at 50 seconds. However, you can change the 50 to X amount of seconds you want.
