### ISSUE TITLE
IDEA: Not creating the same vid twice

### ISSUE THREAD

**Issue by mlvps** [elebumm/RedditVideoMakerBot#229]
It seems to happen often, and I think it would be a good idea to add a feature that knows what videos were created already and prevents them from getting created again.

**Comment by MrSataana** [comment]
On this list

https://github.com/elebumm/RedditVideoMakerBot/issues/225#issue-1260266999

**Comment by FreebieII** [comment]
As mentioned above, it has been noted in #225
