### ISSUE TITLE
Finding a spot in the background video to chop...✂️

### ISSUE THREAD

**Issue by Justice-hub** [elebumm/RedditVideoMakerBot#230]
I downloaded a video from YouTube to use as a background, and I called it **background.mp4**, I entered it in the correct path or "assets / mp4", but I get this error despite having done everything correctly.

![Screenshot (38)](https://user-images.githubusercontent.com/76832989/171942525-6bf25e1d-4045-44ce-8fbb-c274ed74c100.png)
I don't understand what to do, maybe the error is due to the fact that _I downloaded a 3min video_?

Please help me.

**Comment by FreebieII** [comment]
Hi!

Please check that line `13` looks like this:
```py
    random_time = randrange(180, int(length_of_clip) - int(video_length))
```

You can compare your file to [The Original here](https://github.com/elebumm/RedditVideoMakerBot/blob/db1ddce57ab69a9f8a7d6bab6db19c65b1f08aca/video_creation/background.py#L13) and let me know if that was the case.

**Comment by Justice-hub** [comment]
> Hi!
> 
> Please check that line `13` looks like this:
> 
> ```python
>     random_time = randrange(180, int(length_of_clip) - int(video_length))
> ```
> 
> You can compare your file to [The Original here](https://github.com/elebumm/RedditVideoMakerBot/blob/db1ddce57ab69a9f8a7d6bab6db19c65b1f08aca/video_creation/background.py#L13) and let me know if that was the case.

No. I think my code is old:

_background.py_
```
from random import randrange
from pytube import YouTube
from pathlib import Path
from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip
from moviepy.editor import VideoFileClip
from utils.console import print_step, print_substep


def get_start_and_end_times(video_length, length_of_clip):

    random_time = randrange(180, int(length_of_clip) - int(video_length))
    return random_time, random_time + video_length


def download_background():
    """Downloads the background video from youtube.

    Shoutout to: bbswitzer (https://www.youtube.com/watch?v=n_Dv4JMiwK8)
    """

    if not Path("assets/mp4/background.mp4").is_file():
        print_step(
            "We need to download the Minecraft background video. This is fairly large but it's only done once. 😎"
        )
        print_substep("Downloading the background video... please be patient 🙏")
        YouTube("https://www.youtube.com/watch?v=n_Dv4JMiwK8").streams.filter(
            res="720p"
        ).first().download(
            "assets/mp4",
            filename="background.mp4",
        )
        print_substep("Background video downloaded successfully! 🎉", style="bold green")


def chop_background_video(video_length):
    print_step("Finding a spot in the background video to chop...✂️")
    background = VideoFileClip("assets/mp4/background.mp4")

    start_time, end_time = get_start_and_end_times(video_length, background.duration)
    ffmpeg_extract_subclip(
        "assets/mp4/background.mp4",
        start_time,
        end_time,
        targetname="assets/mp4/clip.mp4",
    )
    print_substep("Background video chopped successfully! 🎉", style="bold green")
```

**Comment by Justice-hub** [comment]
Anyone can help me?
