### ISSUE TITLE
Nsfw content is half blocked.

### ISSUE THREAD

**Issue by mlvps** [elebumm/RedditVideoMakerBot#235]
![Screenshot 2022-06-03 230222](https://user-images.githubusercontent.com/65528389/171952441-459b56c9-7a96-4968-b47d-0e69d2c1edba.png)

The button says: Click here to reveal 18+ content.
Any ideas how to remove it?

**Comment by JasonLovesDoggo** [comment]
page.locator('[data-testid="content-gate"]').click():

**Comment by mlvps** [comment]
> page.locator('[data-testid="content-gate"]').click():

where should I paste that in?

**Comment by JasonLovesDoggo** [comment]
I just checked and it looks like it has already been implemented
See
https://github.com/elebumm/RedditVideoMakerBot/blob/master/video_creation/screenshot_downloader.py#L39

**Comment by mlvps** [comment]
> I just checked and it looks like it has already been implemented
> See
> https://github.com/elebumm/RedditVideoMakerBot/blob/master/video_creation/screenshot_downloader.py#L39

yeah but it doesnt work smh
