### ISSUE TITLE
Problem with 'pip3 install -r requirements.txt'

### ISSUE THREAD

**Issue by notafile1** [elebumm/RedditVideoMakerBot#24]
So when I run it I get the error "pip3 install -r requirements.txt" any help please?
                                                           ]

**Comment by notafile1** [comment]
![image_2022-05-31_223413608](https://user-images.githubusercontent.com/91345582/171334181-71dd53ef-5637-41e5-9b93-04e2bf56a1b1.png)

**Comment by notafile1** [comment]
![image_2022-05-31_223511193](https://user-images.githubusercontent.com/91345582/171334298-a36cb5ed-3352-4d98-a62b-d623367553d1.png)

**Comment by lhumke** [comment]
You are trying to use pip3 wrong. You should execute pip3 in the normal Windows Powershell or cmd. You are trying to use pip as if its python code. And I think on Windows its just "pip install -r requirements.txt" instead of pip3. In my experience pip3 only used if you are using Linux. 
Hope I could help you.

**Comment by notafile1** [comment]
i will try it thank you

**Comment by notafile1** [comment]
I'm getting this
![image](https://user-images.githubusercontent.com/91345582/171337679-6bfa5eca-5559-48d2-8243-a5aa4c16943e.png)

**Comment by callmehSpear** [comment]
Don't run CMD as admin and cad into the directory of the repo!

**Comment by StopmotionSimonYT** [comment]
You first need to go to the directory where the requirements.txt is. You can do this with the command cd.

**Comment by notafile1** [comment]
Perfect its downloading

**Comment by callmehSpear** [comment]
Bril

**Comment by notafile1** [comment]
ill try than

**Comment by lhumke** [comment]
I think this Issue can be closed now

**Comment by notafile1** [comment]
> You first need to go to the directory where the requirements.txt is. You can do this with the command cd.

works other than
![image](https://user-images.githubusercontent.com/91345582/171338506-282f3ff7-185b-4a5c-8c41-13d64d99e6b2.png)

**Comment by notafile1** [comment]
> > You first need to go to the directory where the requirements.txt is. You can do this with the command cd.
> 
> works other than where do I get the client id? ![image](https://user-images.githubusercontent.com/91345582/171338506-282f3ff7-185b-4a5c-8c41-13d64d99e6b2.png)

handled that now I have
![image](https://user-images.githubusercontent.com/91345582/171338777-c4391021-1ab2-433f-9c5a-18ad9af27207.png)
