### ISSUE TITLE
I can't start the app

### ISSUE THREAD

**Issue by pontushenriksson** [elebumm/RedditVideoMakerBot#243]
I have everything updated, I downloaded everything from the requirements.txt and entered the Reddit info. I then restarted my PC but it still won't work. I have rich installed from requirements.txt but it says that it can't find a module named rich. How can I fix this? https://pasteboard.co/WAEiXmGjYKLH.png

**Comment by DomizianoScarcelli** [comment]
This happened to me when I was using Python 3.10, I solved it by using 3.8 (with PyCharm).

**Comment by pontushenriksson** [comment]
ok I will try that out, thanks!

**Comment by pontushenriksson** [comment]
I tried out pycharm with python 3.8 but that did unfortunately not fix the problem.

**Comment by penacova44** [comment]
same problem ill look into it, code is clear might be something with the paths

**Comment by pontushenriksson** [comment]
ok, thank you!

**Comment by LukaHietala** [comment]
Or if you don't want to set up PyCharm you can run the command `pip install rich` in any terminal. Just make sure that the directory is the right one.

**Comment by pontushenriksson** [comment]
> 

When I tried that it just said "Requirement already satisfied" on every field.

**Comment by pontushenriksson** [comment]
I fixed that problem by using "python main.py" instead of "python3 main.py". Now I have this bug, it's probably because I have the wrong info in the .env file. What info do I enter and how should it look. https://pasteboard.co/u55un8kNkM4Q.png

**Comment by DomizianoScarcelli** [comment]
> I fixed that problem by using "python main.py" instead of "python3 main.py". Now I have this bug, it's probably because I have the wrong info in the .env file. What info do I enter and how should it look. https://pasteboard.co/u55un8kNkM4Q.png

In the THEME you should put "light" or "dark"
In the SUBREDDIT you should only put the last part (e.g. askReddit for r/askReddit)

Anyway, I think you have the old version, make sure to get the latest version of the app.

**Comment by iaacornus** [comment]
this is perhaps due to the module not in the same path with the `main.py`, thus the script is not able to access it. This is not a program bug.

**Comment by pontushenriksson** [comment]
>> this is perhaps due to the module not in the same path with the main.py, thus the script is not able to access it. This is not a program bug.
I did download the rich module in the root directory and that doesn't seem to be the issue unless I use the python3 main.py command.

>> Anyway, I think you have the old version, make sure to get the latest version of the app.
I have now updated to the newer version but I still can't start the app.

![updated](https://user-images.githubusercontent.com/73602826/173193608-6ed0a551-04ef-4263-ae0f-f37f37eab0f6.png)

**Comment by iaacornus** [comment]
praw exceptions suggest that you got a problem with either your `.env` file or the reddit bot you created.

**Comment by JasonLovesDoggo** [comment]
> > this is perhaps due to the module not in the same path with the main.py, thus the script is not able to access it. This is not a program bug.
> 
> I did download the rich module in the root directory and that doesn't seem to be the issue unless I use the python3 main.py command.
> 
> > Anyway, I think you have the old version, make sure to get the latest version of the app.
> 
> I have now updated to the newer version but I still can't start the app.
> 
> I tried many different ways to enter the subreddit and username but that didn't change the outcome.
> 
> ![updated](https://user-images.githubusercontent.com/73602826/173193795-44f359c6-26c3-4bd3-868c-338a615839fe.png)

You shouldn't have the r/ in the subreddit name

**Comment by pontushenriksson** [comment]
Problem sorted in the discord server. Wrong password for the account
