### ISSUE TITLE
Error while launching Headless Browser

### ISSUE THREAD

**Issue by MonkaMaczna** [elebumm/RedditVideoMakerBot#252]
Python 3.8.10
Ubuntu 20.04

While running `python3 main.py` after downloading all dependencies it shows an error showed below. I have checked it with two machines one with running Ubuntu and the other one with Ubuntu under WSL.

```
Launching Headless Browser...
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    download_screenshots_of_reddit_posts(reddit_object, number_of_comments, os.getenv("THEME"))
  File "/home/monka/RedditVideoMakerBot/video_creation/screenshot_downloader.py", line 26, in download_screenshots_of_reddit_posts
    if theme.casefold() == "dark":
AttributeError: 'NoneType' object has no attribute 'casefold'
```

**Comment by jayc331** [comment]
Add THEME="dark" to the .env file and try again.

**Comment by MonkaMaczna** [comment]
> Add THEME="dark" to the .env file and try again.

Altough I got new error it has fixed this one, thanks!
