### ISSUE TITLE
Feature: make image position configurable

### ISSUE THREAD

**Issue by alhassanv** [elebumm/RedditVideoMakerBot#256]
Hey, I was looking at how some people had the reddit post positioning and they had it positioned a bit above the center but not top something in the middle. Let’s say mid center?

Could anyone look this through?

**Comment by JasonLovesDoggo** [comment]
fixed on my fork.

**Comment by alhassanv** [comment]
> fixed on my fork.

Could you PR it?

**Comment by JasonLovesDoggo** [comment]
> > fixed on my fork.
> 
> Could you PR it?

Nope I will be porting most of the features over when I can but my finger is cut in half and that fork is just too different from the main.

**Comment by JasonLovesDoggo** [comment]
done in linked pr
