### ISSUE TITLE
IDEA: Having the option to pick the comments only in a certain range of length

### ISSUE THREAD

**Issue by DomizianoScarcelli** [elebumm/RedditVideoMakerBot#260]
I wanted to implement an option to filter the comments by length, in order to avoid long comments that occupy the most part of the video.

**Comment by nexuspcs** [comment]
Or even a maximum character length

**Comment by nexuspcs** [comment]
> > Or even a maximum character length
> 
> 
> 
> What do you mean? Maximum character for a single comment? Maximum number of characters in the whole video? Maximum character length for a single word in the comments?
> 
> 

2nd option
