### ISSUE TITLE
I got an error.

### ISSUE THREAD

**Issue by Aivolook** [elebumm/RedditVideoMakerBot#265]
The error:
Traceback (most recent call last):
  File "C:\Users\Aivolook\main.py", line 19, in <module>
    reddit_object = get_subreddit_threads()
  File "C:\Users\Aivolook\reddit\subreddit.py", line 18, in get_subreddit_threads
    if os.getenv("REDDIT_2FA").lower() == "yes":
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by jacesleeman** [comment]
means ur env is messed up

did u make the env a .env not a .template

are you using the main project or one with a pr merge

**Comment by Aivolook** [comment]
Oh.

I totally forgot to edit the file name. 
It looks like its .env but explorer shows its .template
Thanks a lot!
