### ISSUE TITLE
Error: received 401 HTTP response

### ISSUE THREAD

**Issue by Taze00** [elebumm/RedditVideoMakerBot#266]
Hey. I always get an error when I run the main.py. I assume that I specify something wrong in the .env file. Can someone help me there?

Error:
prawcore.exceptions.ResponseException: received 401 HTTP response

my .env:
![image](https://user-images.githubusercontent.com/49670809/171998406-021ca1dc-45ca-407e-be31-ea6b32be6114.png)

**Comment by CallumIO** [comment]
Your subreddit needs to jsut be "AskReddit" not the link

**Comment by Taze00** [comment]
Same error :(

**Comment by CallumIO** [comment]
Ensure your username, password, token and clientid are correct. 

Also uncomment theme

**Comment by Taze00** [comment]
username and password are definitely correct. I copied the client id from the orange marked one and the secrets from the blue marked one. Can you give me an example when I can enter 1 to 1 at the "Theme" and "Subreddit"?

![image](https://user-images.githubusercontent.com/49670809/172011219-40fd9a1f-8c23-48f8-9c4c-bf8dae5b0a87.png)

**Comment by CallumIO** [comment]
Do you have two factor authentication enabled on reddit?

**Comment by Taze00** [comment]
No

**Comment by CallumIO** [comment]
OK - try
`SUBREDDIT="askreddit"`
and
`THEME="light"`

**Comment by Taze00** [comment]
same error :(((

**Comment by benjables** [comment]
Hey! I had this problem earlier too. My issue was that there was an extra space in my secret or id, don't remember which one, that I didn't put there. I think it was copied over when I copied it, so just make sure that there isn't any extra white space, because that will cause a problem

**Comment by crbaws** [comment]
Same error here! still no solution, I tried it with 2 different accounts and 2 different apps

**Comment by crbaws** [comment]
Solved, I entered the ID manually and it worked !

**Comment by gBlaku** [comment]
'.env' file error. Make sure every field is correct and has no spaces

**Comment by RealHeha** [comment]
> Solved, I entered the ID manually and it worked !

what do you mean by enter the id manually?

**Comment by ZelKed** [comment]
same error

**Comment by JasonLovesDoggo** [comment]
incorrect authentication
