### ISSUE TITLE
Always read top comment which is AutoModerator Mod comment

### ISSUE THREAD

**Issue by JustinChinJS** [elebumm/RedditVideoMakerBot#267]
![Untitled](https://user-images.githubusercontent.com/17878850/171998944-029f5bb5-a787-4dad-adda-db39e2abaf50.png)
it's kinda funny actually. A few videos that I tried have the same problem. The whole video is mod's comment.

**Comment by DomizianoScarcelli** [comment]
This issue has been solved in #290

**Comment by FreebieII** [comment]
> This issue has been solved in #290

Closed as it's a PR.
