### ISSUE TITLE
Missing file or something

### ISSUE THREAD

**Issue by Apollyus** [elebumm/RedditVideoMakerBot#27]
Hi, after installing and other needed procedures to get this working i got this:

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Vojtěch Faltýnek\Desktop\RedditVideoMakerBot-master working\RedditVideoMakerBot-master>  & 'C:\Users\Vojtěch Faltýnek\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' 'c:\Users\Vojtěch Faltýnek\.vscode\extensions\ms-python.python-2022.6.3\pythonFiles\lib\python\debugpy\launcher' '50200' '--' 'c:\Users\Vojtěch Faltýnek\Desktop\RedditVideoMakerBot-master working\RedditVideoMakerBot-master\main.py'
Traceback (most recent call last):
  File "c:\Users\Vojtěch Faltýnek\Desktop\RedditVideoMakerBot-master working\RedditVideoMakerBot-master\main.py", line 1, in <module>
    from utils.console import print_markdown
  File "c:\Users\Vojtěch Faltýnek\Desktop\RedditVideoMakerBot-master working\RedditVideoMakerBot-master\utils\console.py", line 1, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'
PS C:\Users\Vojtěch Faltýnek\Desktop\RedditVideoMakerBot-master working\RedditVideoMakerBot-master> 

Sorry, im new in programming and stuff like this :D I really hope someone gonna help me solve this.

**Comment by 00a1** [comment]
try in console "pip3 install rich"

**Comment by Apollyus** [comment]
> try in console "pip3 install rich"

in CMD, or VS Code, where i have this?

**Comment by 00a1** [comment]
I used cmd

**Comment by LukaHietala** [comment]
You can use Command prompt, Power shell, or any other terminal.

**Comment by FreebieII** [comment]
@Apollyus Hi,
Has your issue been resolved, or do you still need help?

**Comment by elebumm** [comment]
Closing for the time being. If you need help, feel free to reopen!
