### ISSUE TITLE
Long videos and shorts

### ISSUE THREAD

**Issue by SomeRandomGuy009** [elebumm/RedditVideoMakerBot#272]
Just an idea!

I've observed that this thing generates videos both types of videos i.e. long and short. Maybe add an option in the .env file "Video Type" so that it generates only that type of video?
Like if it is set to shorts, only videos below 1min will be generated.

**Comment by DomizianoScarcelli** [comment]
I opened a PR (#261) that allows to only pick the comments in a certain range of length of characters. If the max length is about 200 characters, the video will always be less than 1 minute, and there will not be huge comments that occupy all of the video.
Anyway, an option to limit the length of the video would be cool.

**Comment by JasonLovesDoggo** [comment]
done.
