### ISSUE TITLE
When running python 3 

### ISSUE THREAD

**Issue by W-key12** [elebumm/RedditVideoMakerBot#276]
When I run python3 main.py after installing npx playwright.py, python3 comes up with an error
<img width="577" alt="Screenshot 2022-06-04 at 16 41 27" src="https://user-images.githubusercontent.com/75755390/172013126-28c7b888-0023-4a82-8662-a3b76273a9af.png">

Not sure what to do any help appreciated

**Comment by LukaHietala** [comment]
Are you in the right directory?

**Comment by CallumIO** [comment]
Closing due to being stale
