### ISSUE TITLE
Adding background music

### ISSUE THREAD

**Issue by DomizianoScarcelli** [elebumm/RedditVideoMakerBot#278]
I noticed that a lot of Reddit stories videos that go viral have some kind of low-volume background music.
I think it would be nice to have a random (or picked by the user) background music.

**Comment by CallumIO** [comment]
Duplicate of #11

**Comment by DomizianoScarcelli** [comment]
> Duplicate of #11

Oh ok my bad, I didn't see it.

I'm closing the issue.
