### ISSUE TITLE
Visual c++

### ISSUE THREAD

**Issue by tproxy** [elebumm/RedditVideoMakerBot#279]
creating build\lib.win-amd64-3.10
creating build\lib.win-amd64-3.10\typed ast
copying typed astlast27.py -› build\lib.win-amd64-3.10\typed_ast
copying typed_ast\ast3.py,
-› build\1b.win-amd64-3.10\typed_ast
copying typed_ast \conversions.py -› bulld\lib.win-amd64-3.10\typed_ast
copying typed_astl.
init
-•Py -› bulld\lib.win-and64-3.10\typed_ast
package Init File "ast3\festsl
init_
_•py' not found (or not a regular file)
creating bulld\11b.win-and64-3.1e\typed_ast\tests
copying ast3\tests\test_basics.py -› build\lib.win-amd64-3.10\typed_ast\tests
running build ext
bullding * _ast27° extension
error: Microsoft Visual C++ 14.0 or greater 1s required. Get it with "Microsoft C++ Build Tools": http
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure
* Encountered error while trying to install package.
L) typed-ast
note: This 1s an issue with the package mentioned above, not pip.
hint: See above for output from the failure,
WARNING: You are using pip version 22.0.4; however, version 22.1.2 1s available.
You should consider upgrading via the
*C: \Users\trist \AppData\Local \Programs \Python\Python310\python.exe
C: \sers\trist \Downloads\Reddit Video Maker»

**Comment by CallumIO** [comment]
Please download the latest version of the bot - this should no longer be an issue

**Comment by tproxy** [comment]
Ty
