### ISSUE TITLE
raise OAuthException( prawcore.exceptions.0AuthException: unauthorized client error processing request (Only script apps may use password auth)

### ISSUE THREAD

**Issue by tproxy** [elebumm/RedditVideoMakerBot#282]
raise OAuthException(
prawcore.exceptions.0AuthException: unauthorized client error processing request (Only script apps may use password auth)

**Comment by itsZECHS** [comment]
Looks like you didn't set your Reddit app as "**script**"

Please follow the documentation: [Documentation for the Reddit bot](https://luka-hietala.gitbook.io/documentation-for-the-reddit-bot/python-reddit-api-wrapper-details)

**Comment by ItzBlueberry** [comment]
> and how to do that cuz i have the same problem
