### ISSUE TITLE
Suggestion: ignore links in text to speech

### ISSUE THREAD

**Issue by benjables** [elebumm/RedditVideoMakerBot#284]
I just want to begin by saying this is an amazing feat of technology and thank you so much for making it! However, I just have one issue with it, whenever there is a link of some kind, it reads out the entire thing. Maybe some ways to counteract this issue is to check if a word begins with "www" or "https", and if it does, ignore it? Idk, I just thought it might make things better

**Comment by JasonLovesDoggo** [comment]
Hmm you could use regex to find words with those tokens and simply just remove them from the TTS queue

**Comment by null3000** [comment]
Done. Wrote a new PR. PR [311 ](https://github.com/elebumm/RedditVideoMakerBot/pull/311).

**Comment by CallumIO** [comment]
Duplicate of #94 
Thanks for the bug report :D
