### ISSUE TITLE
Please replace utils

### ISSUE THREAD

**Issue by 00a1** [elebumm/RedditVideoMakerBot#29]
Please replace utils for something else like notutils.console
My error
Traceback (most recent call last):
  File "C:\Users\tttre\Downloads\RedditVideoMakerBot-master\main.py", line 1, in <module>
    from utils.console import print_markdown
ModuleNotFoundError: No module named 'utils.console'
after renaming utils folder and renaming "from utils.console import print_step, print_substep"
My error went away.

**Comment by 00a1** [comment]
there are no errors on my end just a suggestion

**Comment by elebumm** [comment]
Hi @00a1 was this issue solved?

**Comment by FreebieII** [comment]
Hey @00a1 

 I will be closing this for the time being.  Feel free to re-open the issue if it has not been solved!

Happy Coding!
