### ISSUE TITLE
[Enhancement] Change TTS system to use TikTok's voices & parsing

### ISSUE THREAD

**Issue by AppleManPS3** [elebumm/RedditVideoMakerBot#291]
Using the TikTok Text To Speech system should enhance the usability of this project by being able to properly handle the usage of different punctuation and pronunciation whilst sounding familiar to viewers on TikTok.

In the project linked below, there are a range of voices to choose from as well as language support for foreign TTS. The script uses a .txt file for reference but this could be changed into working with the RedditVideoMakerBot project in order to handle the speech section of the video a lot better. (TikTok TTS also has no character limit)

`https://github.com/oscie57/tiktok-voice` 

This would help expand to more than just the current male/female voice options on the .env file. Having the ability to use specific TikTok voices as well as some from `https://lazypy.ro/tts/` would definitely give some flexibility to the program.

Reference Issues: 
#273 
#225
#162 
#158 
#92
#15

**Comment by JasonLovesDoggo** [comment]
Tik Tok TTS API definitely does have a limit
As far as I found the limit is 299

**Comment by JasonLovesDoggo** [comment]
Also this is already implemented on my  [Fork](https://github.com/JasonLovesDoggo/RedditVideoMakerBot) if anyone wants to use Port that over

**Comment by wasay-a99** [comment]
> ModuleNotFoundError: No module named 'sox'
I'm getting this error when using your fork. Any idea how to fix? I installed sox

**Comment by JasonLovesDoggo** [comment]
Please see the relevant pull requests for updated status
