### ISSUE TITLE
When text has italics it says _word_

### ISSUE THREAD

**Issue by Kamushy** [elebumm/RedditVideoMakerBot#292]
when reading text the tts says _word_

**Comment by JasonLovesDoggo** [comment]
One solution I can think of is simply sanitizing the TTS input e.g.
```TEXT_WHITELIST = set('abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ 1234567890') 
  
  
 def textify(text): 
     return ''.join(filter(TEXT_WHITELIST.__contains__, text))```
Then Just call the textify function on the comment content

**Comment by Kamushy** [comment]
Good idea, seems to work, do you wanna make a pull?

**Comment by JasonLovesDoggo** [comment]
> Good idea, seems to work, do you wanna make a pull?

Unfortunately I already have a fork and it is vastly different from this repo with almost everything being different
