### ISSUE TITLE
main.py issue

### ISSUE THREAD

**Issue by RenkeDhr** [elebumm/RedditVideoMakerBot#300]
![Bild_2022-06-05_122208181](https://user-images.githubusercontent.com/106910054/172045973-f130651e-1ac1-4d19-966b-b59405c6df00.png)

**Comment by RenkeDhr** [comment]
If you have the same issue, I got the solution!
Instead of typing `python3 main.py` you need to type `python main.py`
I hope this helped you, bc it worked for me.

**Comment by CallumIO** [comment]
Your client/token/username/password are incorrect in your .env file

**Comment by JasonLovesDoggo** [comment]
This was caused by invalid .env variables
Closed as this is user error.
Re open if you still have a problem
