### ISSUE TITLE
[Errno 2] No such file or directory: '.env.template'

### ISSUE THREAD

**Issue by Liwixionn** [elebumm/RedditVideoMakerBot#312]
When i start main.py it is not finding the .env.template or .env file
Here is the full error :
 File "c:\Users\creep\OneDrive\Bureau\RedditVideoMakerBot-master\main.py", line 23, in <module>
    shutil.copy('.env.template', '.env')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '.env.template'

Hope you can help me !

**Comment by Ultimatechno** [comment]
You need to rename the file `.env.template` to `.env`

**Comment by Liwixionn** [comment]
It does the same error even after changing it

**Comment by Liwixionn** [comment]
> You need to rename the file `.env.template` to `.env`

It does the same error even after doing that

**Comment by Ultimatechno** [comment]
> 

Did u fill in the .env file correctly?

**Comment by Liwixionn** [comment]
> > 
> 
> Did u fill in the .env file correctly?
Yes it's all filled, and the error is that the program can't find it if i understood it right

**Comment by Ultimatechno** [comment]
> > > 
> > 
> > 
> > Did u fill in the .env file correctly?
> > Yes it's all filled, and the error is that the program can't find it if i understood it right

yeah, well either you misspelled the file name or its not in c:\Users\creep\OneDrive\Bureau\RedditVideoMakerBot-master\.env

**Comment by Liwixionn** [comment]
I checked and everything was fine but i was opening it with visual studio and the path was wrong on vs code (idk why), when opening with a regular terminal it's the right path and it works well.
Thanks for your help
