### ISSUE TITLE
Change save location

### ISSUE THREAD

**Issue by DarkSmileee** [elebumm/RedditVideoMakerBot#315]
Where can I specify in wich folder it needs to save the final video? 
Now it saves in : RedditVideoMakerBot-master\assets

**Comment by LukaHietala** [comment]
You need to change it manually within the code, or you can just move the file once it's finished.

**Comment by DarkSmileee** [comment]
Can you tell me wich file to edit?

**Comment by DomizianoScarcelli** [comment]
> Can you tell me wich file to edit?

You need to modify final_video.py inside /video_creation.
The line you're looking for is the 83rd
`filename = (re.sub('[?\"%*:|<>]', '', ("assets/" + reddit.subreddit.submission.title + ".mp4")))`
You can replace `assets/` with the absolute path you need, such as `/Users/user/Desktop/`
