### ISSUE TITLE
Issue when launching python main.py

### ISSUE THREAD

**Issue by noahcrum-dev** [elebumm/RedditVideoMakerBot#320]
When trying python python3 i get an error saying python was not found, which is no issue.

When launching python main.py I get the error message "unauthorized_client error processing request (Only script apps may use password auth)"

![image](https://user-images.githubusercontent.com/85817367/172067526-6e4b5f2e-5864-402d-a1ee-2740e0d043ce.png)

**Comment by CallumIO** [comment]
Ensure when you created your reddit app, you selected script and not any of the others.
