### ISSUE TITLE
ERROR:Postproccessing:..... İncorrect codec parameters

### ISSUE THREAD

**Issue by Zetronx0** [elebumm/RedditVideoMakerBot#322]
yt_dlp.utils.DownloadError: ERROR: Postprocessing: Could not write header for output file #0 (incorrect codec parameters ?): Error number -1 occurred
(İt occured after all the final thing(installations"videos, sounds etc...")
PLS HELP

**Comment by gjoedev** [comment]
The best solution is probably to manually download the video it and rename it as background.mp4 in the assets/mp4 directory. It appears to be an error with ytdlp.
