### ISSUE TITLE
NameError: name 'setup_ask' is not defined

### ISSUE THREAD

**Issue by VicLobato** [elebumm/RedditVideoMakerBot#325]
Error - setup_ask not defined.
Installed all requirements successfully, created .env using setup.py.
Python version 3.10.4
![image](https://user-images.githubusercontent.com/95691650/172071509-f3bf94de-1c59-4f44-b341-2683327d8bc6.png)

**Comment by CallumIO** [comment]
Redownload please, I just pushed a fix

**Comment by Whitewolf342** [comment]
Im getting the exact same issue and was just about to make one.
