### ISSUE TITLE
Unable to Launch script

### ISSUE THREAD

**Issue by cameronshanks** [elebumm/RedditVideoMakerBot#328]
![Screen Shot 2022-06-06 at 11 51 04 am](https://user-images.githubusercontent.com/48379292/172091653-06fb51be-c1bb-40d4-af2b-f0c8c5a3aa89.png)

**Comment by cameronshanks** [comment]
I have also tried to add it though the authenticator app, and it still comes up with the same error

**Comment by matrix2113** [comment]
Are you sure that it's a script and not set as anything else? Do you have 2FA enabled?

**Comment by cameronshanks** [comment]
Smh, It was a web app 🙄
