### ISSUE TITLE
Im a bit of a newbie, but can someone help me with this error?

### ISSUE THREAD

**Issue by Fifty8Hz** [elebumm/RedditVideoMakerBot#33]
![image](https://user-images.githubusercontent.com/91988095/171356195-44733378-30bb-4555-8881-7f14eaededb6.png)

thanks!

**Comment by EugeneNeh** [comment]
> Try this in your console `pip3 install rich`

Having the same issue. 
`pip3 install rich` runs fine but does not sovle the problem. Still having the same error

**Comment by FreebieII** [comment]
Hi @Fifty8Hz,

I hope you were able to resolve your issue, I will be closing this for the time being.  Feel free to re-open the issue if it has not been solved!

Happy Coding!
