### ISSUE TITLE
Idea: Use Pipenv

### ISSUE THREAD

**Issue by matrix2113** [elebumm/RedditVideoMakerBot#331]
Fixes #300 and many more. I can integrate it in if that's something devs are interested in. Helps with resolving python/python3 issues and more usable.

Edit: I already use it and seems fine for me. But I did see docker dev support so it would just be open for end user's preference, pipenv/docker/etc.

**Comment by JasonLovesDoggo** [comment]
#300 was caused by invalid variables not anything else.

**Comment by JasonLovesDoggo** [comment]
invalid
