### ISSUE TITLE
Insert full thread link ? 

### ISSUE THREAD

**Issue by realdav2** [elebumm/RedditVideoMakerBot#338]
![image](https://user-images.githubusercontent.com/106691949/172161636-eb3122af-1c6a-408d-85d4-011a9834b58a.png)

 i get the error when launching it and i have no idea what to do or put even reinstalled it still same problem

**Comment by SomeRandomGuy009** [comment]
> 

well, you have to insert a thread link...like this one:
https://www.reddit.com/r/AskReddit/comments/v5wqh6/whats_the_most_frequent_lie_youve_told/

**Comment by LukaHietala** [comment]
> > 
> 
> well, you have to insert a thread link...like this one: https://www.reddit.com/r/AskReddit/comments/v5wqh6/whats_the_most_frequent_lie_youve_told/

Indeed.
