### ISSUE TITLE
can you help me~

### ISSUE THREAD

**Issue by naufalfitra** [elebumm/RedditVideoMakerBot#339]
![image](https://user-images.githubusercontent.com/20796775/172168465-91560a21-7891-4874-9bb8-d9cd01aefc20.png)
im a scriptkiddies, can anybody help me with this problem?

**Comment by The-Drobe** [comment]
The error states that there is an SSL verify error. This is more than likely a problem with your host. Can your visit reddit with no HTTPS warning?
![image](https://user-images.githubusercontent.com/42091381/172202244-9ec23510-6bfb-4049-afff-bc443e6e2b33.png)

**Comment by nexuspcs** [comment]
> The error states that there is an SSL verify error. This is more than likely a problem with your host. Can your visit reddit with no HTTPS warning?
> 
> ![image](https://user-images.githubusercontent.com/42091381/172202244-9ec23510-6bfb-4049-afff-bc443e6e2b33.png)
> 
> 
> 
> This error is the equivalent of seeing this when trying to visit a site with a non trusted certificate authority:
> 
> ![image](https://user-images.githubusercontent.com/42091381/172203062-b7d90728-bf55-4222-a6c7-553f115b16ff.png)
> 
> 
> 
> It might be caused by your Reddit app, REDDIT_CLIENT_ID or REDDIT_CLIENT_SECRET being set up wrong

Yep that is exactly what I was thinking the cause may be. 
@naufalfitra have you tried connecting to a secure wifi network (WP Enterprise or similar?). Also, make sure that you have a correct date&time on your machine, and a correct certificate for your network.

**Comment by The-Drobe** [comment]
> 

It could also be if they are trying to do this on a computer that they use for work or school it is trying to check the certificate against the work or schools CA

**Comment by naufalfitra** [comment]
> > The error states that there is an SSL verify error. This is more than likely a problem with your host. Can your visit reddit with no HTTPS warning?
> > ![image](https://user-images.githubusercontent.com/42091381/172202244-9ec23510-6bfb-4049-afff-bc443e6e2b33.png)
> > This error is the equivalent of seeing this when trying to visit a site with a non trusted certificate authority:
> > ![image](https://user-images.githubusercontent.com/42091381/172203062-b7d90728-bf55-4222-a6c7-553f115b16ff.png)
> > It might be caused by your Reddit app, REDDIT_CLIENT_ID or REDDIT_CLIENT_SECRET being set up wrong
> 
> Yep that is exactly what I was thinking the cause may be. @naufalfitra have you tried connecting to a secure wifi network (WP Enterprise or similar?). Also, make sure that you have a correct date&time on your machine, and a correct certificate for your network.

im using my personal computer and license but currently my browser had dns because my country banned reddit
maybe thats the problem? i will try using vpn maybe it will work if thats the problem

**Comment by naufalfitra** [comment]
shit thats work by using vpn, so the problem is my Internet provider then, thanks all xoxo
