### ISSUE TITLE
problem with the variables 

### ISSUE THREAD

**Issue by vnvs1** [elebumm/RedditVideoMakerBot#340]
i have a problem , when i lunch it it said missing variables even though i have them 
<img width="571" alt="Screen Shot 2022-06-06 at 15 13 12" src="https://user-images.githubusercontent.com/106883530/172178222-afcbb904-35f9-4671-a6a4-5e37b76d3895.png">
?

**Comment by LukaHietala** [comment]
Type "yes".

**Comment by vnvs1** [comment]
i typed yes and re enters the variables but still getings this error

**Comment by CallumIO** [comment]
Closing due to being stale and the setup process is being rewritten
