### ISSUE TITLE
Playwright error i think 

### ISSUE THREAD

**Issue by Zetronx0** [elebumm/RedditVideoMakerBot#344]
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[data-test-id="post-content"]"

it says that after taking screenshots

**Comment by ItaiDanos** [comment]
I got the same issue

**Comment by susgsus** [comment]
me 2

**Comment by ORI299** [comment]
same

**Comment by DylanDelobel** [comment]
Duplicate of #34

**Comment by FreebieII** [comment]
Closing as duplicate of [34](https://github.com/elebumm/RedditVideoMakerBot/issues/34)

Happy Coding!
