### ISSUE TITLE
Os Path Issue

### ISSUE THREAD

**Issue by brokencommit** [elebumm/RedditVideoMakerBot#351]
```
\RedditVideoMakerBot-1.1\setup.py", line 94, in <module>
    os.remove(".env")
FileNotFoundError: [WinError 2] The system cannot find the file specified: '.env'
[16:49:11] Missing Variable: "REDDIT_CLIENT_SECRET"                                                           main.py:59
           Looks like you need to set your Reddit credentials in the .env file. Please follow the             main.py:61
           instructions in the README.md file to set them up.
[16:49:12] We can also launch the easy setup wizard. type yes to launch it, or no to quit the program.        main.py:65
```
I think this is a path issue. I'm not able to read my .env file. I'm on windows with python installed via the microsoft store

**Comment by Tudorhc5** [comment]
Hello!
I think this issue is related to missing data in the .env file. Make sure you enter your client's secret, as the error says.
In windows, there is an option which you have to enable "Show Hidden Files", then you'll see the .env and the env template file.

**Comment by brokencommit** [comment]
I don't think thats the issue. os.remove was unable to remove the .env file. making be believe os.path isn't working as intended. I know I have my .env file setup correctly.
