### ISSUE TITLE
Anyone has an idea how to autorun the bot 

### ISSUE THREAD

**Issue by realdav2** [elebumm/RedditVideoMakerBot#352]
Anyone has an idea how to autorun the bot meaning everytime it finishes one video it starts to make the next one ?
Thx in advance (i am newbie)

**Comment by nexuspcs** [comment]
> Anyone has an idea how to autorun the bot meaning everytime it finishes one video it starts to make the next one ?
> 
> Thx in advance (i am newbie)

Run a timed python script, which after each script completion, it simply repeats the `main.py` script

**Comment by ItaiDanos** [comment]
> 

can u explain how to do that?

**Comment by AsadHumayun** [comment]
I mean can't we just wrap it in a `while True` loop and have the video outputted to a unique directory with a unique ID each time?

I actually have a fork that implements this, but didn't bother opening a PR as I didn't think it would have a demand. However, I'm happy to if it'll be of use to someone

**Comment by Archemike** [comment]
yes would love this added some kind of a looping mechanism. would need a way to take a list of targets of videos though versus just the 1 from a single run script.

**Comment by CJthisis** [comment]
@AsadHumayun

Can you share your fork? I would be very interested in a fork that can run main.py on a loop

**Comment by AsadHumayun** [comment]
I recently deleted my fork. However, if you go to the[ `develop`](https://github.com/elebumm/RedditVideoMakerBot/blob/develop/) branch and download the version there, there's a variable called [`"TIMES_TO_RUN"`](https://github.com/elebumm/RedditVideoMakerBot/blob/develop/.env.template#L28) in the `.env.template` file. You can set this to whatever number you desire, and it will automatically loop that many times.

https://github.com/elebumm/RedditVideoMakerBot/blob/develop/.env.template#L28

**Comment by CJthisis** [comment]
After a bit of try and error, I have made a main.py file that repeats itself over and over again, without having to use the develop-branch, because the implementation of the TTS in that branch has lots of problems. You can download it here:

https://fastupload.io/DGVBsWsnnBmedBR
