### ISSUE TITLE
Stuck at Launching Headless Browser

### ISSUE THREAD

**Issue by ItaiDanos** [elebumm/RedditVideoMakerBot#358]
every time I try to run the program it stuck on 'trying to download screenshots of Reddit posts'

![image](https://user-images.githubusercontent.com/28716344/172342537-ee5b8922-92b8-43bf-83ab-9860ea762ab9.png)

I've added in "screenshot_downloader.py"
 `        
page.set_default_timeout(0)
` because I got timed out every time I tried to run it but this solution doesn't work either.

![image](https://user-images.githubusercontent.com/28716344/172342872-8d1e7dad-db34-4d4b-901c-7b6bb800c92a.png)

**Comment by VeryPersonne** [comment]
I have the same problem...
