### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ValentinKlinger** [elebumm/RedditVideoMakerBot#359]
hello, I try to run the command "python main.py" and "python3.10 main.py" but it returns an error.

![image](https://user-images.githubusercontent.com/98176183/172350697-cc59e798-8981-42ee-a748-33c415273374.png)

when I do `npm list`, it show me that I have playwright@1.22.2. But when I do `playwright install` it returns me that this order doesn't exist on zsh or bash. (I think it change nothing but I'm under ubuntu).

Do you have a idea how to fix my problem please?

**Comment by ImmaHarry** [comment]
Try doing `npx playwright install` instead of `playwright install`.

**Comment by ValentinKlinger** [comment]
I tried it, when I do it doesn't show me anything, it just makes me go to the line.

**Comment by iaacornus** [comment]
this is not a playwright issue, you seem to have issue in you `.env` file, or probably created the wrong reddit application, notice the `prawcore` exception. As for playwright, you simply can simply install it via `pip`

**Comment by LukaHietala** [comment]
pip install playwright
