### ISSUE TITLE
The program reads out links

### ISSUE THREAD

**Issue by SomeRandomGuy009** [elebumm/RedditVideoMakerBot#362]
I made a 1min video. One of the reddit posts contain a link and the bot reads that shit out. Is it possible to make the bot not read stuff that starts with http or https?

**Comment by noblesaji** [comment]
Hi @SomeRandomGuy009 . Pretty sure it can be configured to exclude specific parts with links from the [voices.py](https://github.com/elebumm/RedditVideoMakerBot/blob/master/video_creation/voices.py) file. This could be added as an optional feature.
