### ISSUE TITLE
.env is broken

### ISSUE THREAD

**Issue by majorslapper** [elebumm/RedditVideoMakerBot#363]
i keep getting this error but for every single field that is the env file. my env file is completely filled out but im still getting this error
![unknown](https://user-images.githubusercontent.com/106790855/172381785-c5543f00-e9cb-4115-aaad-0622d6b22733.png)
![Background (1)](https://user-images.githubusercontent.com/106790855/172381793-5784793b-3a81-4871-92bb-485a5171fe7a.png)

**Comment by iaacornus** [comment]
did you blanked out the variables or is that actually your `.env` file?

**Comment by majorslapper** [comment]
> did you blanked out the variables or is that actually your `.env` file?

blanked it out

**Comment by BlockArchitech** [comment]
Ensure that the file is named .env and not .env.txt - you may need to [show hidden files](https://support.microsoft.com/en-us/windows/view-hidden-files-and-folders-in-windows-97fbc472-c603-9d90-91d0-1166d1d9f4b5)

**Comment by BlockArchitech** [comment]
Also, try using the setup wizard.

**Comment by majorslapper** [comment]
> > TEMPLATE File
> 
> Run the setup assistant. That .env file is .env.template - NOT .env
> 
> Copy the info from the .env.template file into the setup assistant.

i just tried and got this error 
![image](https://user-images.githubusercontent.com/106790855/172394127-b049104d-33c8-4fe9-9a9b-e010dc6bdcca.png)

**Comment by BlockArchitech** [comment]
ah, looks like I missed something. There's an error with the setup assistant here. I'll get something made and I'll provide a setup.py to replace yours.

**Comment by majorslapper** [comment]
> ah, looks like I missed something. There's an error with the setup assistant here. I'll get something made and I'll provide a setup.py to replace yours.

ok

**Comment by majorslapper** [comment]
> Okay, try this repository: https://github.com/BlockArchitech/RedditVideoMakerBot
> 
> See #365

that fixed it thank you soo much <3

**Comment by BlockArchitech** [comment]
no problem!

**Comment by majorslapper** [comment]
> no problem!
> 
> Please close this issue if that solved your request.

quick question before i close the thread isnt the bot supposed to compile everything?
