### ISSUE TITLE
All these errors when I type Main.py

### ISSUE THREAD

**Issue by Apsy13** [elebumm/RedditVideoMakerBot#367]
![Capturedzedazedze](https://user-images.githubusercontent.com/84601252/172432612-5250e4f4-2e65-4217-8a9f-14b78d4d0fc2.PNG)

Anyone can help me ?

**Comment by ProjectSlxsh** [comment]
The 401 is from you typing in a subreddit either in the .env file or inn the promt in your terminal, that comes from when you type r/Askreddit for example compared to Askreddit

**Comment by ProjectSlxsh** [comment]
At least in my experience that fixed it

**Comment by Apsy13** [comment]
fixed, thank you
