### ISSUE TITLE
KIND OF ISSUE: As far as I can see I can't change the voice

### ISSUE THREAD

**Issue by ProjectSlxsh** [elebumm/RedditVideoMakerBot#369]
I haven't been able to figure out how to change the voice even after referencing pull request #92 I havn't been able to figure it out looking inside of voices.py I have not been able to find anything mentioning male or female voices, and I do not know or understand how to implement these voices as it mentions within side the new release, where the creator mentions adding a male voice

**Comment by DrMxrcy** [comment]
Looks like it still can't be changed. @elebumm reverted the changes.

**Comment by ProjectSlxsh** [comment]
> Looks like it still can't be changed. @elebumm reverted the changes.

why tho, that sounds so stupid
