### ISSUE TITLE
long post

### ISSUE THREAD

**Issue by majorslapper** [elebumm/RedditVideoMakerBot#370]
if you enter a long post into the bot it just screenshots the entire post and you cant read anything. maybe having the bot take smaller screenshots on longer posts and having them stiched together would be better . this isnt the entire post btw its jut whatever the bot decided to screenshot

![image](https://user-images.githubusercontent.com/106790855/172449718-ab61918b-f7f6-47e7-b4f1-4aa7fd86ca9d.png)

**Comment by DrMxrcy** [comment]
Having them cut up would work great.

**Comment by majorslapper** [comment]
> Having them cut up would work great.

would be an amazing update to the bot like that we can have the original vid then part (whatever ) till the op post is done

**Comment by William9923** [comment]
#330 i think this is similar enhancement

**Comment by JasonLovesDoggo** [comment]
impemented
