### ISSUE TITLE
Error When Launching Headless Browser

### ISSUE THREAD

**Issue by Whitewolf342** [elebumm/RedditVideoMakerBot#371]
![image](https://user-images.githubusercontent.com/74878033/172458247-ca835982-49f3-4bed-a23b-9d8396f83fc9.png)
Getting This Error, Also on the one with the voice options from the Pull Requests.

**Comment by Adriann521** [comment]
I tried to navigate to the link mentioned at the bottom of the error and was unsuccessful, looks like a part of the link is missing.

**Comment by matrix2113** [comment]
Try rerunning it and seeing if you get that error again.
