### ISSUE TITLE
error when lunching main.py 

### ISSUE THREAD

**Issue by thegreatone45** [elebumm/RedditVideoMakerBot#373]
it says  Missing Variable: "REDDIT_CLIENT_ID"                                                              main.py:59
           Looks like you need to set your Reddit credentials in the .env file. Please follow the            main.py:61
           instructions in the README.md file to set them up. even tough i have filled in the client id help pls also im sure its correct

**Comment by Adriann521** [comment]
Did you try to do step 4B in the Readme.md? 
	
4b **Manual Install**: Rename `.env.template` to `.env` and replace all values with the appropriate fields. To get Reddit keys (**required**), visit [the Reddit Apps page.](https://www.reddit.com/prefs/apps) TL;DR set up an app that is a "script". Copy your keys into the `.env` file, along with whether your account uses two-factor authentication.

**Comment by CallumIO** [comment]
Closing due to being stale
