### ISSUE TITLE
LONG posts + no comments when subreddit isn't AskReddit

### ISSUE THREAD

**Issue by gBlaku** [elebumm/RedditVideoMakerBot#376]
When I use any subreddit except for AskReddit, my videos often end up upwards of 7 minutes long and with no comments. Anyone else experience this?

**Comment by OGreeni** [comment]
What subreddit, specifically?

**Comment by gBlaku** [comment]
> What subreddits, specifically?

One for example: tifu

**Comment by iaacornus** [comment]
perhaps the selected thread has no comments?

**Comment by DrMxrcy** [comment]
Another one is nosleep

**Comment by gBlaku** [comment]
Really hoping a fix comes out

**Comment by CallumIO** [comment]
Duplicate of many others
