### ISSUE TITLE
[ FEATURE REQUEST ] Implement automatic uploading to YouTube

### ISSUE THREAD

**Issue by LeNinjaHD** [elebumm/RedditVideoMakerBot#378]
Implement automatic uploading to YouTube with something like https://github.com/pillargg/youtube-upload

Thanks!

**Comment by noblesaji** [comment]
This feature is currently not implemented due to security concerns and community guidelines, of all media platforms. Therefore all videos should be checked and verified by an individual before posting. Thanks

**Comment by owengaspard** [comment]
Auto uploading is forbidden by the terms of the YouTube API.

**Comment by JasonLovesDoggo** [comment]
Closing as this violates the YouTube TOS
