### ISSUE TITLE
[ FEATURE REQUEST ] Shorten videos to > 1 Minute

### ISSUE THREAD

**Issue by LeNinjaHD** [elebumm/RedditVideoMakerBot#379]
Shorten videos to > 1 Minute so they can be YouTube Shorts

**Comment by gBlaku** [comment]
yes please im getting so many 5 min videos..

**Comment by noblesaji** [comment]
This could be possible by limiting the number of screenshots and voices used in one clip. Thanks

**Comment by ProjectSlxsh** [comment]
how are you getting loger the 1min videos?

**Comment by gBlaku** [comment]
> the default perimeter is 50 seconds right?

nope I just started using it today and it's 50/50 - some are 1 min some are up to 7 min.. LOL

**Comment by DomizianoScarcelli** [comment]
With the latest version, you can specify the max range of characters every comment has to have. If you set the range in (0,200), the video should be always shorter than 1 minute.
In this way long comments (>200 characters) are not picked, so an option to specify the duration of the video regardless of the length of the comments would be cool.

**Comment by gBlaku** [comment]
> 

How can I do this?

**Comment by gBlaku** [comment]
> With the latest version, you can specify the max range of characters every comment has to have. If you set the range in (0,200), the video should be always shorter than 1 minute. In this way long comments (>200 characters) are not picked, so an option to specify the duration of the video regardless of the length of the comments would be cool.

How can I do this?

**Comment by ProjectSlxsh** [comment]
I did see within voices.py it mentions 50, so i changed it to 180(3 mins) and while it made the rendering time shoot up it did seem to change the time that the video would have so i would say look in their sense the comment bot and end video both rely on the time that the mp3 file is.

**Comment by Drugsosos** [comment]
> > With the latest version, you can specify the max range of characters every comment has to have. If you set the range in (0,200), the video should be always shorter than 1 minute. In this way long comments (>200 characters) are not picked, so an option to specify the duration of the video regardless of the length of the comments would be cool.
> 
> How can I do this?

Change or add this in your .env file (:

```
COMMENT_LENGTH_RANGE = "min,max"
```
