### ISSUE TITLE
Running setup.py install for typed-ast did not run successfully. Anyone else having troubles?

### ISSUE THREAD

**Issue by Salvrath** [elebumm/RedditVideoMakerBot#38]
This is the cmd prompt output.

D:\RedditVideoMakerBot-master\RedditVideoMakerBot-master>pip3 install -r requirements.txt
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
Collecting appdirs==1.4.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting black==20.8b1
  Using cached black-20.8b1-py3-none-any.whl
Collecting certifi==2021.10.8
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Requirement already satisfied: charset-normalizer==2.0.12 in c:\python310\lib\site-packages (from -r requirements.txt (line 4)) (2.0.12)
Collecting click==7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Requirement already satisfied: commonmark==0.9.1 in c:\python310\lib\site-packages (from -r requirements.txt (line 6)) (0.9.1)
Collecting decorator==4.4.2
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting flake8==3.8.3
  Using cached flake8-3.8.3-py2.py3-none-any.whl (72 kB)
Collecting greenlet==1.1.2
  Using cached greenlet-1.1.2-cp310-cp310-win_amd64.whl (101 kB)
Collecting gTTS==2.2.4
  Using cached gTTS-2.2.4-py3-none-any.whl (26 kB)
Requirement already satisfied: idna==3.3 in c:\python310\lib\site-packages (from -r requirements.txt (line 11)) (3.3)
Collecting imageio==2.19.2
  Using cached imageio-2.19.2-py3-none-any.whl (3.4 MB)
Collecting imageio-ffmpeg==0.4.7
  Using cached imageio_ffmpeg-0.4.7-py3-none-win_amd64.whl (22.6 MB)
Collecting mccabe==0.6.1
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting moviepy==1.0.3
  Using cached moviepy-1.0.3.tar.gz (388 kB)
  Preparing metadata (setup.py) ... done
Collecting mutagen==1.45.1
  Using cached mutagen-1.45.1-py3-none-any.whl (218 kB)
Collecting mypy-extensions==0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Requirement already satisfied: numpy==1.22.3 in c:\python310\lib\site-packages (from -r requirements.txt (line 18)) (1.22.3)
Collecting pathspec==0.8.0
  Using cached pathspec-0.8.0-py2.py3-none-any.whl (28 kB)
Collecting Pillow==9.1.1
  Using cached Pillow-9.1.1-cp310-cp310-win_amd64.whl (3.3 MB)
Collecting playwright==1.22.0
  Using cached playwright-1.22.0-py3-none-win_amd64.whl (26.5 MB)
Requirement already satisfied: praw==7.6.0 in c:\python310\lib\site-packages (from -r requirements.txt (line 22)) (7.6.0)
Requirement already satisfied: prawcore==2.3.0 in c:\python310\lib\site-packages (from -r requirements.txt (line 23)) (2.3.0)
Collecting proglog==0.1.10
  Using cached proglog-0.1.10-py3-none-any.whl (6.1 kB)
Collecting pycodestyle==2.6.0
  Using cached pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
Collecting pyee==8.1.0
  Using cached pyee-8.1.0-py2.py3-none-any.whl (12 kB)
Collecting pyflakes==2.2.0
  Using cached pyflakes-2.2.0-py2.py3-none-any.whl (66 kB)
Requirement already satisfied: Pygments==2.12.0 in c:\python310\lib\site-packages (from -r requirements.txt (line 28)) (2.12.0)
Collecting python-dotenv==0.20.0
  Using cached python_dotenv-0.20.0-py3-none-any.whl (17 kB)
Collecting pytube==12.1.0
  Using cached pytube-12.1.0-py3-none-any.whl (56 kB)
Collecting regex==2020.10.15
  Using cached regex-2020.10.15.tar.gz (690 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests==2.27.1 in c:\python310\lib\site-packages (from -r requirements.txt (line 32)) (2.27.1)
Requirement already satisfied: rich==12.4.4 in c:\python310\lib\site-packages (from -r requirements.txt (line 33)) (12.4.4)
Requirement already satisfied: six==1.16.0 in c:\python310\lib\site-packages (from -r requirements.txt (line 34)) (1.16.0)
Collecting toml==0.10.1
  Using cached toml-0.10.1-py2.py3-none-any.whl (19 kB)
Collecting tqdm==4.64.0
  Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
Collecting typed-ast==1.4.1
  Using cached typed_ast-1.4.1.tar.gz (208 kB)
  Preparing metadata (setup.py) ... done
Collecting typing_extensions==4.2.0
  Using cached typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Requirement already satisfied: update-checker==0.18.0 in c:\python310\lib\site-packages (from -r requirements.txt (line 39)) (0.18.0)
Requirement already satisfied: urllib3==1.26.9 in c:\python310\lib\site-packages (from -r requirements.txt (line 40)) (1.26.9)
Requirement already satisfied: websocket-client==1.3.2 in c:\python310\lib\site-packages (from -r requirements.txt (line 41)) (1.3.2)
Collecting websockets==10.1
  Using cached websockets-10.1-cp310-cp310-win_amd64.whl (97 kB)
Requirement already satisfied: colorama in c:\python310\lib\site-packages (from tqdm==4.64.0->-r requirements.txt (line 36)) (0.4.4)
Using legacy 'setup.py install' for moviepy, since package 'wheel' is not installed.
Using legacy 'setup.py install' for regex, since package 'wheel' is not installed.
Using legacy 'setup.py install' for typed-ast, since package 'wheel' is not installed.
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
Installing collected packages: typed-ast, toml, regex, pyee, mypy-extensions, mccabe, certifi, appdirs, websockets, typing_extensions, tqdm, pytube, python-dotenv, pyflakes, pycodestyle, Pillow, pathspec, mutagen, imageio-ffmpeg, greenlet, decorator, click, proglog, playwright, imageio, gTTS, flake8, black, moviepy
  Running setup.py install for typed-ast ... error
  error: subprocess-exited-with-error

  × Running setup.py install for typed-ast did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\typed_ast
      copying typed_ast\ast27.py -> build\lib.win-amd64-3.10\typed_ast
      copying typed_ast\ast3.py -> build\lib.win-amd64-3.10\typed_ast
      copying typed_ast\conversions.py -> build\lib.win-amd64-3.10\typed_ast
      copying typed_ast\__init__.py -> build\lib.win-amd64-3.10\typed_ast
      package init file 'ast3\tests\__init__.py' not found (or not a regular file)
      creating build\lib.win-amd64-3.10\typed_ast\tests
      copying ast3\tests\test_basics.py -> build\lib.win-amd64-3.10\typed_ast\tests
      running build_ext
      building '_ast27' extension
      creating build\temp.win-amd64-3.10
      creating build\temp.win-amd64-3.10\Release
      creating build\temp.win-amd64-3.10\Release\ast27
      creating build\temp.win-amd64-3.10\Release\ast27\Custom
      creating build\temp.win-amd64-3.10\Release\ast27\Parser
      creating build\temp.win-amd64-3.10\Release\ast27\Python
      C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iast27/Include -IC:\Python310\include -IC:\Python310\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include /Tcast27/Custom/typed_ast.c /Fobuild\temp.win-amd64-3.10\Release\ast27/Custom/typed_ast.obj
      typed_ast.c
      C:\Python310\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> typed-ast

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)

**Comment by CallumIO** [comment]
Not at my windows machine right now but I think you need VS C++ Build Tools to build the wheel. Visit (https://visualstudio.microsoft.com/visual-cpp-build-tools/), click download and go through the installer. If memory serves me right you need "Desktop Development With C++". Then retry `pip3 install -r requirements.txt`.

**Comment by IdkHowAreYOU** [comment]
I did 
`pip install wheel` and `pip install typed-ast`
and the changed the `typed-ast` version in `requirements.txt` to 1.5.4

and now i could download the requirements.txt file without any problems

i haven´t testet the program out, and i don´t know if this changes anything
hopes this works and helps :)

**Comment by CallumIO** [comment]
In the installer (note the optional section) do you have these selected? Might not be 2022 but shouldn't be an issue. Windows 11 SDK should also work find if you're running Win11
![image](https://user-images.githubusercontent.com/16057677/171387457-aa93a41a-064e-4062-8fc6-6c9732e71586.png)

**Comment by CallumIO** [comment]
See #45

**Comment by Salvrath** [comment]
Cheers, got it working now!

**Comment by JuanseMastrangelo** [comment]
The version to use is Python 3.8.0
