### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.console'

### ISSUE THREAD

**Issue by duckGameGH** [elebumm/RedditVideoMakerBot#381]
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from utils.console import print_markdown
ModuleNotFoundError: No module named 'utils.console'
```
I don't know how to install this module but it seems not to work...

**Comment by kappq** [comment]
You need to install the required modules with: `pip install -r requirements.txt`. (Make sure your in the project root).

**Comment by iaacornus** [comment]
make sure you execute the python in main.py in `.` not in other dir. If that didn't worked create `__init__.py` file inside `utils/`

**Comment by SammysDiscussion** [comment]
![image](https://user-images.githubusercontent.com/103465203/173225549-c042bee7-4a42-4d69-ac96-ea906cee1a36.png)
i have the exact same problem.  I followed everything.

> make sure you execute the python in main.py in `.` not in other dir. If that didn't worked create `__init__.py` file inside `utils/`
