### ISSUE TITLE
OPUS/Codec Issue when finishing the video.

### ISSUE THREAD

**Issue by Crimson435345** [elebumm/RedditVideoMakerBot#387]
Background.mp4 file is already there and is working, everything works except at the end when rendering. it makes 0 bytes clip.mp4 and gives this error.

![image](https://user-images.githubusercontent.com/107133627/172659054-81fbd23d-f824-460a-85d2-82444db2bd67.png)

**Comment by micziz** [comment]
There was an error with the Codec. Try deleting the video and redownloading it.

**Comment by rgvillanueva28** [comment]
[#348](https://github.com/elebumm/RedditVideoMakerBot/issues/348#issuecomment-1148732701)
