### ISSUE TITLE
Suggestion: Be able to change the length of the video

### ISSUE THREAD

**Issue by Schweinhitti** [elebumm/RedditVideoMakerBot#393]
/\
 |

**Comment by Amir1453** [comment]
![image](https://user-images.githubusercontent.com/63464110/173201423-fe2ad43e-f80a-4735-8951-473958dffcad.png)

Hi, you can adjust the value here to change the length of the video. However it is not precise as it does not take into account the length of the final video added. This is the simplest way to change the length without tinkering with the code.

**Comment by CJthisis** [comment]
Thanks a lot!

**Comment by JasonLovesDoggo** [comment]
done.
