### ISSUE TITLE
Postprocessing: Conversion failed!

### ISSUE THREAD

**Issue by Dec1lent** [elebumm/RedditVideoMakerBot#395]
![image](https://user-images.githubusercontent.com/66132473/172693553-9562fb07-d6e4-4874-a252-0c2b1e5a4351.png)
The problem is also on my laptop. But on this pc, the Minecraft background video is already installed and working in the assets, but it still wants to download it.

**Comment by micziz** [comment]
Try deleting the file, then re-run the script. Maybe it was confused after seeing that it already exists.
