### ISSUE TITLE
Problem with links embedded into text.

### ISSUE THREAD

**Issue by Amir1453** [elebumm/RedditVideoMakerBot#396]
For example, if the comment has a text with a link in it, the bot will read the whole link after reading the text.
![image](https://user-images.githubusercontent.com/63464110/172693778-d923afde-ca3c-4f6c-8904-4d8511d8233c.png)
In this case, bot reads forever young, and then the link which was nearly half the video long.
Possible solutions:

- Dont read the comments with link embeds.
- When detecting a https link, omit that part. (However this causes the text to be still seen as blue)

**Comment by AsadHumayun** [comment]
Fixed in #332, I believe. (a regular expression is used to sanitise post titles)
