### ISSUE TITLE
Cookies on long texts

### ISSUE THREAD

**Issue by Schweinhitti** [elebumm/RedditVideoMakerBot#398]
![comment_3](https://user-images.githubusercontent.com/89853722/172698961-377a5715-72f9-4b82-9821-973b0cd61cb1.png)

**Comment by DomizianoScarcelli** [comment]
This issue has been already solved, make sure to download the latest version of the app.

**Comment by Schweinhitti** [comment]
> This issue has been already solved, make sure to download the latest version of the app. @DomizianoScarcelli 

I am already on the latest version of the app. Maybe a Issue with my language being German? My reddit language is let to English but the screenshots are still in german.

**Comment by Schweinhitti** [comment]
Just happened again on [this](https://www.reddit.com/r/AskReddit/comments/hdc46c/fathers_of_reddit_in_honor_of_fathers_day_what/) threa
![comment_0](https://user-images.githubusercontent.com/89853722/172846626-73f8b669-897d-4e2e-9958-51785a7d381a.png)
d

**Comment by Schweinhitti** [comment]
> I am german as well and this worked for me: #39

it is like that but still shows the cookies thing

**Comment by JasonLovesDoggo** [comment]
fixed.

**Comment by Elektroney** [comment]
still doesnt work for me
