### ISSUE TITLE
utils.console not found afer re-installation

### ISSUE THREAD

**Issue by indrakhatiwada** [elebumm/RedditVideoMakerBot#399]
I installed the first time and it worked like a charm but i did some mistakes while trying to modify the code then i deleted the folder and re-cloned it. after setting up the reclone, it doesnot work. the following error appears. it would be great help if someone could help me fix this

 File "C:\Users\XYZ\Desktop\RedditVideoMakerBot\main.py", line 2, in <module>
    from utils.console import print_markdown
ModuleNotFoundError: No module named 'utils.console'

**Comment by AsadHumayun** [comment]
Did  you run `pip install -r requirements.txt` in that new folder?

**Comment by indrakhatiwada** [comment]
yes i did, it says all requirements are met

**Comment by AsadHumayun** [comment]
Could you please run `pip list` and send the output here?

**Comment by AsadHumayun** [comment]
It also may have something to do with your Python version, could you send that as well please?

**Comment by indrakhatiwada** [comment]
checked the previous issues, should have done it earlier. creating` __init__.py` inside the `utils/` folder solved it

**Comment by AsadHumayun** [comment]
Ahh fair enough

**Comment by MakKind** [comment]
try running python main.py from terminal
