### ISSUE TITLE
PLEASE ADD NVIDIA CUDA SUPPORT

### ISSUE THREAD

**Issue by boerenhugo** [elebumm/RedditVideoMakerBot#401]
It isn't dramatic without because it only takes around 4 minutes to make a video but then it will be 30 seconds and it's cool

**Comment by JasonLovesDoggo** [comment]
I would have to say that this is not going to be implemented.
Number one I do not believe The libraries used support cuda so they would have to completely write everything from scratch and honestly for this is not worth it

**Comment by Tudorhc5** [comment]
Moviepy does not support GPU rendering yet as far as I am aware.

**Comment by micziz** [comment]
MoviePY does not support Nvidia Cuda as per the latest version, and will not support it in 2.0. Also, test with Movie.py have shown that Cuda support does not influence speed. Changes to the underlying architecture (planned for the release after 2.0, as per my knowledge) will change some things with FFMPEG. 

The alternative is Switching to a diffrent library (to my knowledge it does not exist) witch is a hassle of itself, thanks to braking api changes, and major rewrites, not to talk about a new major version, witch would mean updating, and thats not easy.

Or @elebumm cloud implement directly FFMPEG into the project, but that would not be worth it, as said by @JasonLovesDoggo. 

Finally, consider that 4 minutes for a video with nothing to do against maybe 30 minutes for capturing screenshots, tts, putting it all together, video editing... 4 minutes is really worth the wait.

**Comment by JasonLovesDoggo** [comment]
Well said

**Comment by JasonLovesDoggo** [comment]
Closing this issue as it will not be added
