### ISSUE TITLE
Video not creating with errors

### ISSUE THREAD

**Issue by mindeeloo** [elebumm/RedditVideoMakerBot#402]
![image](https://user-images.githubusercontent.com/78835502/172720896-7dce4b04-d55c-4917-a5b2-72a575c3dad6.png)
This might already have been solved but I cant find any solutions, please help!
Os: Windows 11

**Comment by mindeeloo** [comment]
After doing these instructions 
1st. Do: pip install opencv-python and pip install scipy (not working? try: py -m in front of those commands!)
2nd. Unninstall Pillow. pip unninstall pillow
3rd. Install Pillow again! pip install pillow
4th. Try running the script now. It should work.
![image](https://user-images.githubusercontent.com/78835502/172727836-edd5151d-3b34-4133-a2d0-390c705e5981.png)

**Comment by big-baller** [comment]
I tried what you said and it still didn't work - heres my output


Screenshots downloaded Successfully.
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Finding a spot in the background video to chop...                                                                                                                                                              │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Moviepy - Running:
>>> "+ " ".join(cmd)
Moviepy - Command returned an error
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    chop_background_video(length)
  File "C:\Users\baller\reddit2\RedditVideoMakerBot\video_creation\background.py", line 49, in chop_background_video
    targetname="assets/mp4/clip.mp4",
  File "C:\Users\baller\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\moviepy\video\io\ffmpeg_tools.py", line 41, in ffmpeg_extract_subclip
    subprocess_call(cmd)
  File "C:\Users\baller\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\moviepy\tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
OSError: ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'assets/mp4/background.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf59.23.100
  Duration: 01:20:13.08, start: 0.000000, bitrate: 10571 kb/s
    Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, bt709), 2560x1440, 10419 kb/s, SAR 1:1 DAR 16:9, 59.90 fps, 59.94 tbr, 16k tbn, 16k tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp, 137 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
[mp4 @ 000001959e0b0240] track 1: codec frame size is not set
[mp4 @ 000001959e0b0240] opus in MP4 support is experimental, add '-strict -2' if you want to use it.
Could not write header for output file #0 (incorrect codec parameters ?): Experimental feature
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
    Last message repeated 1 times

**Comment by mindeeloo** [comment]
> I tried what you said and it still didn't work - heres my output
> 
> Screenshots downloaded Successfully. ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐ │ Finding a spot in the background video to chop... │ └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘ Moviepy - Running:
> 
> > > > "+ " ".join(cmd)
> > > > Moviepy - Command returned an error
> > > > Traceback (most recent call last):
> > > > File "main.py", line 99, in 
> > > > chop_background_video(length)
> > > > File "C:\Users\baller\reddit2\RedditVideoMakerBot\video_creation\background.py", line 49, in chop_background_video
> > > > targetname="assets/mp4/clip.mp4",
> > > > File "C:\Users\baller\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\moviepy\video\io\ffmpeg_tools.py", line 41, in ffmpeg_extract_subclip
> > > > subprocess_call(cmd)
> > > > File "C:\Users\baller\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\moviepy\tools.py", line 54, in subprocess_call
> > > > raise IOError(err.decode('utf8'))
> > > > OSError: ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
> > > > built with gcc 9.2.1 (GCC) 20200122
> > > > configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
> > > > libavutil      56. 31.100 / 56. 31.100
> > > > libavcodec     58. 54.100 / 58. 54.100
> > > > libavformat    58. 29.100 / 58. 29.100
> > > > libavdevice    58.  8.100 / 58.  8.100
> > > > libavfilter     7. 57.100 /  7. 57.100
> > > > libswscale      5.  5.100 /  5.  5.100
> > > > libswresample   3.  5.100 /  3.  5.100
> > > > libpostproc    55.  5.100 / 55.  5.100
> > > > Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'assets/mp4/background.mp4':
> > > > Metadata:
> > > > major_brand     : isom
> > > > minor_version   : 512
> > > > compatible_brands: isomiso2mp41
> > > > encoder         : Lavf59.23.100
> > > > Duration: 01:20:13.08, start: 0.000000, bitrate: 10571 kb/s
> > > > Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, bt709), 2560x1440, 10419 kb/s, SAR 1:1 DAR 16:9, 59.90 fps, 59.94 tbr, 16k tbn, 16k tbc (default)
> > > > Metadata:
> > > > handler_name    : VideoHandler
> > > > Stream #0:1(eng): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp, 137 kb/s (default)
> > > > Metadata:
> > > > handler_name    : SoundHandler
> > > > [mp4 @ 000001959e0b0240] track 1: codec frame size is not set
> > > > [mp4 @ 000001959e0b0240] opus in MP4 support is experimental, add '-strict -2' if you want to use it.
> > > > Could not write header for output file #0 (incorrect codec parameters ?): Experimental feature
> > > > Stream mapping:
> > > > Stream #0:0 -> #0:0 (copy)
> > > > Stream #0:1 -> #0:1 (copy)
> > > > Last message repeated 1 times

Oh I meant I tried those instructions from the  other dude with the same problem
I am currently still trying to the find the fix
The dude I referenced is here 
https://github.com/elebumm/RedditVideoMakerBot/issues/249

**Comment by big-baller** [comment]
> ![image](https://user-images.githubusercontent.com/78835502/172720896-7dce4b04-d55c-4917-a5b2-72a575c3dad6.png) This might already have been solved but I cant find any solutions, please help! Os: Windows 11

Do you have text under? I do, and it seems like the error comes from:
Duration: 01:20:13.08, start: 0.000000, bitrate: 10571 kb/s
Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, bt709), 2560x1440, 10419 kb/s, SAR 1:1 DAR 16:9, 59.90 fps, 59.94 tbr, 16k tbn, 16k tbc (default)
Metadata:
handler_name : VideoHandler
Stream #0:1(eng): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp, 137 kb/s (default)
Metadata:
handler_name : SoundHandler
[mp4 @ 000001959e0b0240] track 1: codec frame size is not set
[mp4 @ 000001959e0b0240] opus in MP4 support is experimental, add '-strict -2' if you want to use it.
Could not write header for output file #0 (incorrect codec parameters ?): Experimental feature
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #0:1 -> #0:1 (copy)
Last message repeated 1 times

where the problem is the experimental feature it mentions, just an idea but I don't know where to change this option

**Comment by mindeeloo** [comment]
Thats exactly whats happening to me!!! I have even tried it in VsCode, different versions of python, different versions of windows. I think we need help on resolving this

**Comment by mindeeloo** [comment]
Finally, after actually searching for the whole day, I found a solution! 
Thank you to this madlad 
https://github.com/elebumm/RedditVideoMakerBot/issues/348#issuecomment-1148732701

**Comment by glxxyxafonso** [comment]
> After doing these instructions 
> 
> 1st. Do: pip install opencv-python and pip install scipy (not working? try: py -m in front of those commands!)
> 
> 2nd. Unninstall Pillow. pip unninstall pillow
> 
> 3rd. Install Pillow again! pip install pillow
> 
> 4th. Try running the script now. It should work.
> 
> ![image](https://user-images.githubusercontent.com/78835502/172727836-edd5151d-3b34-4133-a2d0-390c705e5981.png)
> 
> 

thanks for mentioning my text :)

@mindeeloo

**Comment by mindeeloo** [comment]
(:
