### ISSUE TITLE
non Programmers Help

### ISSUE THREAD

**Issue by DEVMAX01** [elebumm/RedditVideoMakerBot#406]
is there a video explaining how to install it 
cus i keep getting issues while installing 
last issue is that it cant find 
`ModuleNotFoundError: No module named 'rich'`

i am not a programmer yet i am just going around testing stuff looking for passion

**Comment by Tudorhc5** [comment]
If you follow the tutorial in the [documentation](https://luka-hietala.gitbook.io/documentation-for-the-reddit-bot/), its easier to set up as that has some pictures and explains more of the process.

**Comment by LukaHietala** [comment]
`pip install rich`

**Comment by micziz** [comment]
1-Check your python version. As per the rich documentation: "Rich requires Python 3.6.3 or later."

2-Try installing it like this ```python -m pip install rich```, or ```python3 -m pip install rich```. 

3-If this does not work, retry installing it using ```pip3 install -r requirements.txt```

Hope it Works!

**Comment by William9923** [comment]
Can we close this issue? @JasonLovesDoggo
