### ISSUE TITLE
Issue in installion

### ISSUE THREAD

**Issue by HushedGod** [elebumm/RedditVideoMakerBot#408]
I don't understand why this error is happening
![image](https://user-images.githubusercontent.com/107185863/172828143-d2d98db5-9037-4616-a3a2-72cd304b55f8.png)

**Comment by J4nis05** [comment]
> I don't understand why this error is happening
> 
> ![image](https://user-images.githubusercontent.com/107185863/172828143-d2d98db5-9037-4616-a3a2-72cd304b55f8.png)
> 
> 

Im pretty Sure you have to run this command inside the folder. So if you have the unzipped the folder on lets say your desktop you would have to use "cd C:\Users\[User]\Desktop\[Whatever you named the folder].

**Comment by FreebieII** [comment]
> I don't understand why this error is happening ![image](https://user-images.githubusercontent.com/107185863/172828143-d2d98db5-9037-4616-a3a2-72cd304b55f8.png)

Hi there! 

Please make sure that your command prompt/terminal is pointed to the correct directory, so that it can find the correct file!
