### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by JanW11** [elebumm/RedditVideoMakerBot#41]
May anybody help me by installation? How works point 3 and 4 in the installation order?

**Comment by DevKanui** [comment]
Hey, probably have the same issues as you the installation fails. But next time you post an issue post the error thread as the developer can work with this!


  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [126 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\typed_ast
      copying typed_ast\ast27.py -> build\lib.win-amd64-3.10\typed_ast
      copying typed_ast\ast3.py -> build\lib.win-amd64-3.10\typed_ast
      copying typed_ast\conversions.py -> build\lib.win-amd64-3.10\typed_ast
      copying typed_ast\__init__.py -> build\lib.win-amd64-3.10\typed_ast
      package init file 'ast3\tests\__init__.py' not found (or not a regular file)
      creating build\lib.win-amd64-3.10\typed_ast\tests
      copying ast3\tests\test_basics.py -> build\lib.win-amd64-3.10\typed_ast\tests
      running build_ext
      building '_ast27' extension
      creating build\temp.win-amd64-3.10
      creating build\temp.win-amd64-3.10\Release
      creating build\temp.win-amd64-3.10\Release\ast27
      creating build\temp.win-amd64-3.10\Release\ast27\Custom
      creating build\temp.win-amd64-3.10\Release\ast27\Parser
      creating build\temp.win-amd64-3.10\Release\ast27\Python
      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iast27/Include -IC:\Users\heiin\AppData\Local\Programs\Python\Python310\include -IC:\Users\heiin\AppData\Local\Programs\Python\Python310\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt /Tcast27/Custom/typed_ast.c /Fobuild\temp.win-amd64-3.10\Release\ast27/Custom/typed_ast.obj
      typed_ast.c
      C:\Users\heiin\AppData\Local\Temp\pip-install-4wk00dfa\typed-ast_b9cd8c80e8164ec794e5faaa935b4dbe\ast27\Include\asdl.h(37): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      C:\Users\heiin\AppData\Local\Temp\pip-install-4wk00dfa\typed-ast_b9cd8c80e8164ec794e5faaa935b4dbe\ast27\Include\asdl.h(37): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      C:\Users\heiin\AppData\Local\Temp\pip-install-4wk00dfa\typed-ast_b9cd8c80e8164ec794e5faaa935b4dbe\ast27\Include\asdl.h(37): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      C:\Users\heiin\AppData\Local\Temp\pip-install-4wk00dfa\typed-ast_b9cd8c80e8164ec794e5faaa935b4dbe\ast27\Include\asdl.h(37): error C2059: Syntaxfehler: ")"
      C:\Users\heiin\AppData\Local\Temp\pip-install-4wk00dfa\typed-ast_b9cd8c80e8164ec794e5faaa935b4dbe\ast27\Include\asdl.h(38): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      C:\Users\heiin\AppData\Local\Temp\pip-install-4wk00dfa\typed-ast_b9cd8c80e8164ec794e5faaa935b4dbe\ast27\Include\asdl.h(38): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      C:\Users\heiin\AppData\Local\Temp\pip-install-4wk00dfa\typed-ast_b9cd8c80e8164ec794e5faaa935b4dbe\ast27\Include\asdl.h(38): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      C:\Users\heiin\AppData\Local\Temp\pip-install-4wk00dfa\typed-ast_b9cd8c80e8164ec794e5faaa935b4dbe\ast27\Include\asdl.h(38): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(398): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(398): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(398): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(398): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(400): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(400): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(400): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(400): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(402): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(402): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(402): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(402): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(404): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(404): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(404): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(404): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(406): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(406): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(406): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(406): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(410): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(410): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(410): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(410): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(413): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(413): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(413): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(413): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(415): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(415): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(415): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(415): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(417): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(417): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(417): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(417): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(420): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(420): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(420): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(420): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(423): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(423): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(423): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(423): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(426): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(426): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(426): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(426): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(429): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(429): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(429): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(429): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(432): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(432): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(432): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(432): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(435): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(435): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(435): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(435): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(438): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(438): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(438): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(438): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(441): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(441): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(441): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(441): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(444): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(444): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(444): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(444): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(447): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(447): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(447): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(447): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(449): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(449): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(449): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(449): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(451): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(451): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(451): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(451): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(454): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(454): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(454): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(454): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(457): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(457): error C2081: "PyArena": Name in der formalen Parameterliste ist ung\x81ltig
      ast27/Include\Python-ast.h(457): error C2143: Syntaxfehler: Es fehlt "{" vor "*"
      ast27/Include\Python-ast.h(457): error C2059: Syntaxfehler: ")"
      ast27/Include\Python-ast.h(459): error C2143: Syntaxfehler: Es fehlt ")" vor "*"
      ast27/Include\Python-ast.h(459): fatal error C1003: Mehr als 100 Fehler gefunden; Kompilierung wird abgebrochen.
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30037\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for typed-ast
  Running setup.py clean for typed-ast

**Comment by CallumIO** [comment]
Closing as no longer relevant - fixed in latest version
