### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by jenks2607** [elebumm/RedditVideoMakerBot#412]
i have attempted to run this code i beleive i have followed the instructions correctly however i am getting a 401 error, i have checked all the other issues with seem identical to my one and i have had no luck in rectifying please see screensh![Screenshot 2022-06-09 143036](https://user-images.githubusercontent.com/107195105/172859102-8f5285f3-b0eb-4636-8794-b580650f06eb.png)ts

**Comment by JasonLovesDoggo** [comment]
are you positive your .env variables are correct?
because 401 means access denied

**Comment by micziz** [comment]
As @JasonLovesDoggo said, 401 means access denied, witch probably means your api keys are incorrect. Try making another key or checking your .env variables.

**Comment by JasonLovesDoggo** [comment]
Closed for inactivity
Please reopen if you still have a problem
