### ISSUE TITLE
Reposting #376 since no update - any subreddit except Askreddit results in LONG videos of dead posts (not hot/trending), and no comments.

### ISSUE THREAD

**Issue by gBlaku** [elebumm/RedditVideoMakerBot#415]

**Comment by JasonLovesDoggo** [comment]
change the filter mode

**Comment by gBlaku** [comment]
> 

how

**Comment by gBlaku** [comment]
> change the filter mode

how

**Comment by JasonLovesDoggo** [comment]
> > change the filter mode
> 
> how

https://github.com/elebumm/RedditVideoMakerBot/blob/master/reddit/subreddit.py#L57
https://praw.readthedocs.io/en/stable/code_overview/models/subreddit.html#praw.models.Subreddit.search

**Comment by gBlaku** [comment]
> > > change the filter mode
> > 
> > 
> > how
> 
> https://github.com/elebumm/RedditVideoMakerBot/blob/master/reddit/subreddit.py#L57 https://praw.readthedocs.io/en/stable/code_overview/models/subreddit.html#praw.models.Subreddit.search

It's already set to hot posts

**Comment by JasonLovesDoggo** [comment]
I know, I'm saying set it to top
