### ISSUE TITLE
suggestion make it not reapeat videos

### ISSUE THREAD

**Issue by Skinny957** [elebumm/RedditVideoMakerBot#416]

**Comment by JasonLovesDoggo** [comment]
implemented properly on my [fork](https://github.com/JasonLovesDoggo/RedditVideoMakerBot)

**Comment by wasay-a99** [comment]
@JasonLovesDoggo Hey how can I use your fork? I download the zip, then drag and drop the "RedditVideoMakerBot" file where I have the original? I'm very new to Github so bear with me haha

**Comment by JasonLovesDoggo** [comment]
The instructions are listed in my repo

**Comment by JasonLovesDoggo** [comment]
> @JasonLovesDoggo Hey how can I use your fork? I download the zip, then drag and drop the "RedditVideoMakerBot" file where I have the original? I'm very new to Github so bear with me haha

But you would drop the directory in a completely new place

**Comment by wasay-a99** [comment]
@JasonLovesDoggo Thanks! It's actually running now :) Just read about your injury in the readme, get well soon!

**Comment by JasonLovesDoggo** [comment]
> @JasonLovesDoggo Thanks! It's actually running now :) Just read about your injury in the readme, get well soon!

Thanks for the wishes still swollen as hell

**Comment by micziz** [comment]
Can you please close this issue, its not needed!

**Comment by JasonLovesDoggo** [comment]
It's still a great idea though. And it will be implemented

**Comment by JasonLovesDoggo** [comment]
implemented
