### ISSUE TITLE
An install guide for linux 

### ISSUE THREAD

**Issue by moezmustafa** [elebumm/RedditVideoMakerBot#419]
we should have like a readme or something that enlist the steps .

**Comment by micziz** [comment]
The steps are the same for every platform. If you are referring to installing python, then check your package manager or build it from source.

**Comment by Drugsosos** [comment]
I can write install.sh for linux with all dependences and stuff
Let me know if anyone wants it

**Comment by micziz** [comment]
> I can write install.sh for linux with all dependences and stuff
> Let me know if anyone wants it

If we Need ti write and install.sh, lets write It for MacOS and Linux

**Comment by Drugsosos** [comment]
> > I can write install.sh for linux with all dependences and stuff
> > Let me know if anyone wants it
> 
> If we Need ti write and install.sh, lets write It for MacOS and Linux

I can do both actually, they all unix-like so it's not a problem)

**Comment by micziz** [comment]
I have opened a pull for an install script

**Comment by Drugsosos** [comment]
> I have opened a pull for an install script

gonna check ur pr soon and if it works fine on mac
