### ISSUE TITLE
FFMPEG MoviePy error 

### ISSUE THREAD

**Issue by gBlaku** [elebumm/RedditVideoMakerBot#420]
Any ideas?
![image](https://user-images.githubusercontent.com/48861657/172916477-0d0e73ec-9628-4785-b00d-dfb50b34e780.png)

**Comment by JasonLovesDoggo** [comment]
Fixed In my fork

**Comment by JasonLovesDoggo** [comment]
Use my fork.
Or implement the fix yourself

**Comment by gBlaku** [comment]
> 

youre fork doesnt work :P

**Comment by JasonLovesDoggo** [comment]
> > 
> 
> your fork doesnt work :P

The devil is in the details got to specify how it doesn't work because for everybody else it does.

**Comment by JasonLovesDoggo** [comment]
Closed for inactivity and no response
Please reopen if you still have a problem
