### ISSUE TITLE
How can we only get the top comment in a thread

### ISSUE THREAD

**Issue by hamzah-sajid-code** [elebumm/RedditVideoMakerBot#424]
I want to get only few and best comment in the thread 
I don't want to get all the comments in a thread
what shall i do? is it possible?

**Comment by AsadHumayun** [comment]
I'm not sure if that's possible, having taken a look at the praw docs:

- [Submission](https://praw.readthedocs.io/en/v7.1.4/code_overview/models/submission.html)
- [CommentForest](https://praw.readthedocs.io/en/v7.1.4/code_overview/other/commentforest.html#praw.models.comment_forest.CommentForest)
