### ISSUE TITLE
Can we change the voice of reader?

### ISSUE THREAD

**Issue by shivamyadav37** [elebumm/RedditVideoMakerBot#427]
can we change the voice of the orator bot?
if yes, then how??

**Comment by DylanDelobel** [comment]
Yes, read [this documentation](https://gtts.readthedocs.io/en/latest/module.html#localized-accents)
In `voices.py` you have multiple `gTTS` objects.

**Comment by wasay-a99** [comment]
> Yes, read [this documentation](https://gtts.readthedocs.io/en/latest/module.html#localized-accents) In `voices.py` you have multiple `gTTS` objects.

Could you provide more detail? I'm looking through the page you linked and I can't find anything on how to actually change the voice

**Comment by Neel-2004** [comment]
Could you provide more detail? I'm looking through the page you linked and I can't find anything on how to actually change the voice 

Newbie here with less knowledge of technicalities, Help out somebody.

**Comment by vitviki** [comment]
If you look at the .env file you will see two attributes near the bottom, "VOICE" and "TTsChoice". 

Voice is where is you can change the speaker in the video. Goto TTS/Polly.py to see the available speakers.
TTsChoice is Text-To-Speech choice. Here we have Polly(Amazon TTS), GTTS(Google TTS) and TikTok.

**Comment by William9923** [comment]
@JasonLovesDoggo i think we can cloase this issue?

**Comment by JasonLovesDoggo** [comment]
done.
