### ISSUE TITLE
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by yungfresh1** [elebumm/RedditVideoMakerBot#428]
when I do the step 2 in the installation (i have installed 3.10 python) this error occur
the command: pip3 install -r requirements.txt
![image](https://user-images.githubusercontent.com/107262872/173085723-652883e2-82b4-44bb-bf68-0772994dbeed.png)

**Comment by DylanDelobel** [comment]
Your current working dir is `C:\Users\math4`
Are you sure you are in the correct directory of the project ?
