### ISSUE TITLE
Impossible to install playwright

### ISSUE THREAD

**Issue by LoickNosal** [elebumm/RedditVideoMakerBot#436]
Hi guys,

I try to install playwright but It seems that it doesn't exist .
![Capture d’écran de 2022-06-10 20-16-23](https://user-images.githubusercontent.com/44084791/173126729-87b8ec68-5fa6-45e7-afdb-7e586833a330.png)

Ubuntu version :  Ubuntu 18.04.5 LTS
Thanks for you help

**Comment by JasonLovesDoggo** [comment]
Playwright

**Comment by HallowedDust5** [comment]
npm or npx install playwright

if you dont have npm or npx, download node and it should come with it.

**Comment by LoickNosal** [comment]
thanks for your answers. I juste update the python version and it works (doesn't work with pyton 3.6.9 but work with python 3.8.0). I don't know why.
