### ISSUE TITLE
Issue on a modified version

### ISSUE THREAD

**Issue by ProjectSlxsh** [elebumm/RedditVideoMakerBot#439]
Pretty much I was able to get the video to be horizontal with 1080p resolution problem? the comments get stretched with it and I would like to know how to fix it

**Comment by j0p3s** [comment]
Don't mod it... If you modified it why are you asking for help? :|

**Comment by ProjectSlxsh** [comment]
Simply because it wasn't adding another pr it was just changing it slightly and wanted a fix for what seems to be a simple problem

**Comment by micziz** [comment]
It's really difficult for us to troubleshoot the problem if you are running a modified version of the software. Restore the original version and we will try to add a pr for scaling!

**Comment by ProjectSlxsh** [comment]
> It's really difficult for us to troubleshoot the problem if you are running a modified version of the software. Restore the original version and we will try to add a pr for scaling!

Tbh its not that big of a change and I am alreadt running a different modi version so i will make a pr but I don't need it thats why i only made it a "issue" not a pull request
