### ISSUE TITLE
End of Video glitched.

### ISSUE THREAD

**Issue by ElusiveXGames** [elebumm/RedditVideoMakerBot#448]
The end of almost every video is glitched and is to long/ pauses and is silent. 

Aswell as some videos are over 2 minutes long.

Any fixes?

Proof of glitch. End of video

https://ss.elusivedev.com/YoCU6/wiZiKUKI89.mp4

**Comment by evilexecutable** [comment]
I almost have the same issue. Mine are reading the thread but no comments.

**Comment by dasbts** [comment]
I'm still getting this in the newest develop version.

**Comment by LinuxTux193** [comment]
same issue
