### ISSUE TITLE
Random problem

### ISSUE THREAD

**Issue by Bobtheman9o** [elebumm/RedditVideoMakerBot#452]
Every time i try to run setup wizard it finds a diffrent problem (with the env file) even though everything is filled in. Anyway i can fix this?
And if i try to do automatic set-up it says:
 line 94, in <module>
    os.remove(".env")
FileNotFoundError: [WinError 2] The system cannot find the file specified: '.env'

**Comment by Amir1453** [comment]
If setup.py does not work, try to fill in .env by yourself. Make sure you DELETE .template from .env.template
After making sure .env is filled with correct information, use main.py to run the script.

**Comment by Bobtheman9o** [comment]
I did tho witch is wierd
