### ISSUE TITLE
[ SUGGESTION ] List of already made videos.

### ISSUE THREAD

**Issue by Amir1453** [elebumm/RedditVideoMakerBot#454]
Since the script sometimes creates videos it already made, maybe a list of already created videos could be implemented. And before selecting a thread, the bot would check if it was already done.

**Comment by micziz** [comment]
#418 will add checking for that. In the meantime use the @Jason loves doggos fork.

**Comment by micziz** [comment]
@JasonLovesDoggo fork has been merged. I suggest that this issue Is closed
