### ISSUE TITLE
Nie mo

### ISSUE THREAD

**Issue by FerrisOfficial** [elebumm/RedditVideoMakerBot#455]
`
[22:38:31] Here goes nothing! Launching setup wizard...                     main.py:70Nie mo[22:38:32] Missing Variable: "REDDIT_USERNAME"                              main.py:59
           Looks like you need to set your Reddit credentials in the .env   main.py:61           file. Please follow the instructions in the README.md file to 
           set them up.
           We can also launch the easy setup wizard. type yes to launch it, main.py:65           or no to quit the program.
Launch setup wizard? > yes
`
As you can see there is ,,Nie mo" after calling main.py.
`
Launch setup wizard? > yes
[22:42:16] Here goes nothing! Launching setup wizard...                     main.py:70Nie mo[22:42:17] Please ensure that OPACITY is set between 0 and 1 in your .env   main.py:85
           file
`
After that nothing happens :(

**Comment by JasonLovesDoggo** [comment]
You need to set the correct values in the .env file

**Comment by micziz** [comment]
As @JasonLovesDoggo said, you need to set the correct values in the .env file. The vaule is opacity, witch can only be 0 or 1, but you can put anything in between (eg 0.5, 0.7).

**Comment by BradTFT** [comment]
where is the input area for this variable. what is the reddit username and password variable also? is that MY login info? (i own the bot on my account)

**Comment by JasonLovesDoggo** [comment]
The dot ENV file and yes
