### ISSUE TITLE
.env file issues.

### ISSUE THREAD

**Issue by SammysDiscussion** [elebumm/RedditVideoMakerBot#460]
I wrote the .env file correctly, everything is perfect except for the fact that nothing works.

![image](https://user-images.githubusercontent.com/103465203/173210020-98700f88-316d-431c-afa0-d78d38ebcdfd.png)
![image](https://user-images.githubusercontent.com/103465203/173210023-99c30eff-cbcc-49ba-bf87-e7a589e3189b.png)
![image](https://user-images.githubusercontent.com/103465203/173210024-78966afe-d6b4-4c7b-8d63-17aa8a7ba083.png)

**Comment by micziz** [comment]
In fact, the program says, "Environment variables are set! Continuing"

**Comment by SammysDiscussion** [comment]
But the code will not run properly. It shows Syntax errors.


> In fact, the program says, "Environment variables are set! Continuing"

**Comment by SammysDiscussion** [comment]
Well, not really, but the code will not work. No errors, no nothing. It just stays there.

**Comment by micziz** [comment]
Can you show me an extended screenshot?

**Comment by SammysDiscussion** [comment]
> Can you show me an extended screenshot?

Yeah, it changed overnight for some reason. 

![image](https://user-images.githubusercontent.com/103465203/173249352-6574381e-3ad9-4379-9e6c-1d5ca59bdcc0.png)
It shows that.
![image](https://user-images.githubusercontent.com/103465203/173249370-1651b815-c9f7-4198-9f2d-9a772a07add4.png)

**Comment by micziz** [comment]
have you tampered with the file? Utils.console is a module that comes with the bot.

**Comment by SammysDiscussion** [comment]
> have you tampered with the file? Utils.console is a module that comes with the bot.

No, not that I remember.

**Comment by SammysDiscussion** [comment]
I can try to reinstall the files.

**Comment by micziz** [comment]
Try reinstalling everything...

**Comment by SammysDiscussion** [comment]
Yep, just did. Still same error.

**Comment by micziz** [comment]
I dunno what to say... probably an error with the path or something...

**Comment by SammysDiscussion** [comment]
idk if i did something wrong. my IDE says 9 errors are in here.
![image](https://user-images.githubusercontent.com/103465203/173251050-de3a92f3-63f5-4579-9bd7-1dd57cf8f506.png)

**Comment by SammysDiscussion** [comment]
I definitely did something wrong here, let me try to fix it/

**Comment by micziz** [comment]
What Is the errore in tour idea. Generally It Will warn you but let you run it.
