### ISSUE TITLE
Not really issue but add setting so no nsfw

### ISSUE THREAD

**Issue by Gccool** [elebumm/RedditVideoMakerBot#461]

**Comment by micziz** [comment]
1-Rename the issue to [IDEA] or [SUGGESTION].

2-Good idea, but in what sense. The bot cannot read images. So a swear word filter?

**Comment by Gccool** [comment]
Well it says when it is nsfw ohh nsfw you are spicy so obviously it knows.

**Comment by micziz** [comment]
> Well it says when it is nsfw ohh nsfw you are spicy so obviously it knows.

I still do not understand it...

**Comment by Drugsosos** [comment]
@Gccool I guess you are talking about nsfw tag in reddit, so there will be no such submissions a video, we can do that 😉

**Comment by Gccool** [comment]
Yeah

**Comment by micziz** [comment]
> Well it says when it is nsfw ohh nsfw you are spicy so obviously it knows.

OHHH i understand. You can remove it from the script if you prefer... But we keep it in just for funnies. The post's api response includes any tags, that's why we know...

**Comment by Gccool** [comment]
@micziz so is it possible for the bot when it picks a nsfw double one it picks another random thread that isn't nsfw

**Comment by micziz** [comment]
The only way to do that is rerunning the bot. I'l add an ENV toggle!

**Comment by Gccool** [comment]
@micziz what is that sry I don't know ???

**Comment by micziz** [comment]
The latest version of the bot has this feature. I suggest that this issue Is closed.
