### ISSUE TITLE
When it has small characters in the top left like a 2 ² it just says like char char char char 2

### ISSUE THREAD

**Issue by Gccool** [elebumm/RedditVideoMakerBot#464]

**Comment by JasonLovesDoggo** [comment]
Can you provide an example video?

**Comment by Gccool** [comment]
Sry I deleted it by accident but the thread it was was the top post of all time on R/AskReddit

**Comment by JasonLovesDoggo** [comment]
I can't help if you don't provide a video

**Comment by Gccool** [comment]
I'll check my recycle bin
