### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by JuRedstoner** [elebumm/RedditVideoMakerBot#466]
It woud be nice when you could add a way to update the downloaded Code without replace it by yourself.

**Comment by JasonLovesDoggo** [comment]
Explain?

**Comment by micziz** [comment]
A editor kinda thing? For settings therse the .env file...

**Comment by JuRedstoner** [comment]
When ther are new pull request you don‘t have that in your on copy on your computer of this

**Comment by JasonLovesDoggo** [comment]
> When ther are new pull request you don‘t have that in your on copy on your computer of this

Because a pull request isn't implemented yet

**Comment by JasonLovesDoggo** [comment]
Okay I understand what you're saying but that's not feature that we would add with this code plus I'm tested a pull requests could have numerous bugs or they could just be sending themselves your credentials

Will not be implemented

If you want to use their code use it at your own risk and just use that fork

**Comment by micziz** [comment]
It's called [git](https://git-scm.com). After downloading and installing it, clone the repo and then when you want to receive updates just `git pull`

**Comment by JasonLovesDoggo** [comment]
> It's called [git](https://git-scm.com). After downloading and installing it, clone the repo and then when you want to receive updates just `git pull`

No they want to get the features from pull requests before they are merged

So I told them just to use that fork

**Comment by JuRedstoner** [comment]
@JasonLovesDoggo Thank you perhaps I sad it false but I ment a tool tho copy the merged pull requestS

**Comment by JasonLovesDoggo** [comment]
> @JasonLovesDoggo Thank you perhaps I sad it false but I ment a tool tho copy the merged pull requestS

It's called [git](https://git-scm.com). After downloading and installing it, clone the repo and then when you want to receive updates just `git pull`
