### ISSUE TITLE
MoviePy error: FFMPEG encountered the following error while writing file assets; OSError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by M00nMission** [elebumm/RedditVideoMakerBot#468]
Run `bash build.sh` then `bash run.sh` 

If you try to download a Reddit thread with a `/` slash in the title it errors

> t:   0%|                                                   | 2/1640 [00:00<06:35,  4.14it/s, now=None]Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/moviepy/video/io/ffmpeg_writer.py", line 136, in write_frame
    self.proc.stdin.write(img_array.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

> During handling of the above exception, another exception occurred:

>Traceback (most recent call last):

  >File "main.py", line 100, in <module>
    >final_video = make_final_video(number_of_comments)
  >File "/app/video_creation/final_video.py", line 84, in make_final_video
    final.write_videofile(filename, fps=30, audio_codec="aac", audio_bitrate="192k")
  File "<decorator-gen-55>", line 2, in write_videofile
  File "/usr/local/lib/python3.8/dist-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-54>", line 2, in write_videofile
  File "/usr/local/lib/python3.8/dist-packages/moviepy/decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-53>", line 2, in write_videofile
  File "/usr/local/lib/python3.8/dist-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/usr/local/lib/python3.8/dist-packages/moviepy/video/VideoClip.py", line 300, in write_videofile
    ffmpeg_write_video(self, filename, fps, codec,
  File "/usr/local/lib/python3.8/dist-packages/moviepy/video/io/ffmpeg_writer.py", line 228, in ffmpeg_write_video
    writer.write_frame(frame)
  File "/usr/local/lib/python3.8/dist-packages/moviepy/video/io/ffmpeg_writer.py", line 180, in write_frame
    raise IOError(error)
OSError: [Errno 32] Broken pipe

>MoviePy error: FFMPEG encountered the following error while writing file assets/Tattoo artists of Reddit, what was the weirdest / most disturbing tattoo a customer wanted.mp4:

 >b'assets/Tattoo artists of Reddit, what was the weirdest / most disturbing tattoo a customer wanted.mp4: No such file or directory\n'
 
 I tried to add `/` in the regex in`line 83` of `final_video.py` of the `master` branch. Ran `git pull` today to ensure it's updated.  but for whatever reason that didn't work 
 
 trying to download this thread: 
 https://www.reddit.com/r/AskReddit/comments/bi5jy3/tattoo_artists_of_reddit_what_was_the_weirdest/?utm_source=share&utm_medium=web2x&context=3
 
 using python3.8.9; all dependencies installed 
 Mac OS, M1, arm64 
$PATH is set to `/usr/bin/python3`, not using homebrew nor miniforge
all dependencies are installed (with `pip3`)

**Comment by BradTFT** [comment]
same issue here on DEB10 BUSTER

**Comment by micziz** [comment]
#332 is your answer!

**Comment by BradTFT** [comment]
is this solved yet?

**Comment by M00nMission** [comment]
> #332 is your answer!

doesn't work for some reason, end up getting a `POSTPROCESSING` error; tried deleting Docker container + image and building fresh, won't work

**Comment by M00nMission** [comment]
> Ohh... you are using docker. Can you try a local install? I want to check if it's a docker error or a moviepy error.

local installs a big hell no 🤣 ; arm64 chips suck for tons of the peer-deps

**Comment by BradTFT** [comment]
what is the current solution if there is one?

**Comment by JasonLovesDoggo** [comment]
stale
