### ISSUE TITLE
Nothing happens after running main

### ISSUE THREAD

**Issue by cryocet** [elebumm/RedditVideoMakerBot#47]
I have done everything the readme said to do but when I open main.py a console flashes up for half a second then disappears? I'm very new so sorry if its a really simple issue

**Comment by cryocet** [comment]
> You need to cd into the folder first in cmd, then run the commands. Then, main.py will run no issue.

i did that now it says ModuleNotFoundError: No module named 'rich' . i have tried putting 'pip install rich' into cmd but i still get the same issue even after rich is installed.

**Comment by FreebieII** [comment]
> > You need to cd into the folder first in cmd, then run the commands. Then, main.py will run no issue.
> 
> i did that now it says ModuleNotFoundError: No module named 'rich' . i have tried putting 'pip install rich' into cmd but i still get the same issue even after rich is installed.

Hi @cryocet, 

I hope you were able to resolve your issue, I will be closing this for the time being.  Feel free to re-open the issue if it has not been solved!

Happy Coding!
