### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by BradTFT** [elebumm/RedditVideoMakerBot#472]
FEATURE REQUEST:

currently, the script runs and places the video in the same folder as the repository. Im suggesting some sort of UI that allows the user to choose what directory the file goes into or set a default one that all of the videos go into instead of them being kind of thrown into the folder.

(i do not know how to implement this)

**Comment by micziz** [comment]
UI's in python are very hard. Maybe we cloud use some sort of implentation that tries to write depending on what you write. Gonna try implementing it!

**Comment by BradTFT** [comment]
yea that's pretty much it. i was thinking (for UI) like a terminal based thing or something. rly we could do a "enter the path you would like the file to be saved at" type thing. thanks for attempting the feature

**Comment by micziz** [comment]
Branch develop (soon to be merget with master) will include a feature that allows you to set an env variable for the path. If you want to risk it, go ahed, but be carful, there migth be dangiling commits!

**Comment by BradTFT** [comment]
i will check it out. any chance of breaking OS or any other dangerous consequences?

**Comment by micziz** [comment]
No, it just night not work.

**Comment by JasonLovesDoggo** [comment]
A UI for this Will 1,000% not be implemented in the near future at least
You will be able to set the output in version 1.2 or 1.3.
