### ISSUE TITLE
cant seem to start the bot.

### ISSUE THREAD

**Issue by kizi84** [elebumm/RedditVideoMakerBot#473]
hey, i cant seem to strart the bot. I always get an issue that state"Your .env file is invalid, or was never created. Standby." however i have it created and filled out. Why is that?
![asd](https://user-images.githubusercontent.com/80330090/173252881-be9ab73d-20a0-451a-aec8-27347a6bab9a.PNG)
s

**Comment by JasonLovesDoggo** [comment]
Did you rename the file to .env ?

**Comment by JasonLovesDoggo** [comment]
And are you sure you have the Reddit client ID in there?

**Comment by CloudPotatoYAY** [comment]
i have done those but it still doesn't work

**Comment by Eugen2127** [comment]
Which OS do you use?

**Comment by CloudPotatoYAY** [comment]
Windows

**Comment by CloudPotatoYAY** [comment]
windows 11
