### ISSUE TITLE
Aws Polly: The config profile (polly) could not be found

### ISSUE THREAD

**Issue by ProjectSlxsh** [elebumm/RedditVideoMakerBot#475]
Under the branch https://github.com/elebumm/RedditVideoMakerBot/tree/feat/add-tts-generics I am running into: the config profile (polly) could not be found  I have no clue how to fix this issue 
here is the most recent traceback
![image](https://user-images.githubusercontent.com/93690295/173259152-47e970c9-e893-4b91-b132-df5b0c608043.png)

**Comment by JasonLovesDoggo** [comment]
Do you have the right credentials?

**Comment by ProjectSlxsh** [comment]
What do you mean, this is just saved in downloads and the other tts located in their also works but the Polly's not

**Comment by JasonLovesDoggo** [comment]
Polly requires an AWS account and stuff

**Comment by ProjectSlxsh** [comment]
I do have a account setup kind of uptick payment, could this be a issue, also even if I did have a account how would I change the profile?

**Comment by JasonLovesDoggo** [comment]
> I do have a account setup kind of uptick payment, could this be a issue, also even if I did have a account how would I change the profile?

Honestly I'm not familiar with AWS Polly so please ask the person who made the pr

**Comment by ProjectSlxsh** [comment]
> > I do have a account setup kind of uptick payment, could this be a issue, also even if I did have a account how would I change the profile?
> 
> Honestly I'm not familiar with AWS Polly so please ask the person who made the pr

K will so
