### ISSUE TITLE
Language in the screenshots 

### ISSUE THREAD

**Issue by Moehre100** [elebumm/RedditVideoMakerBot#476]
![image](https://user-images.githubusercontent.com/71335489/173259451-8b70cfd7-c32c-4428-8aea-529ec4049b5c.png)
The language for reddit isn't set to english and probably uses the language of the os (german for me)

**Comment by JasonLovesDoggo** [comment]
So what do you want?
We couldn't implement that without automatically changing the language to English every single time

**Comment by JasonLovesDoggo** [comment]
done.
