### ISSUE TITLE
IDEA: swap Reddit for Twitter 💡

### ISSUE THREAD

**Issue by M00nMission** [elebumm/RedditVideoMakerBot#483]
Example: 

https://www.tiktok.com/@churchoftate/video/7108364190313811246?is_from_webapp=1&sender_device=pc&web_id=7063226277755078150

**Comment by micziz** [comment]
Twitter has an api, but it's not as free as reddit. Also extra hassle in the env...

**Comment by JasonLovesDoggo** [comment]
Maybe in a year from now when this has a full GUI and stuff this could be implemented but as micziz said it would be too much of a hassle and at the core of this it's supposed to be a reddit bot.

**Comment by jaw0608** [comment]
@JasonLovesDoggo are there active plans for a GUI right now? If not, I'd love to discuss and help get something started!

**Comment by JasonLovesDoggo** [comment]
> @JasonLovesDoggo are there active plans for a GUI right now? If not, I'd love to discuss and help get something started!

Currently I believe a bunch of people are interested and the main person who was working on it was @ImmaHarry

**Comment by JasonLovesDoggo** [comment]
I believe it's in electron.js
