### ISSUE TITLE
Cannot install Playwright

### ISSUE THREAD

**Issue by Skiryy** [elebumm/RedditVideoMakerBot#486]
I've been trying to install playwright but whenever I do "playwright install" it gives the error playwright : "The term 'playwright' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

**Comment by micziz** [comment]
Playwright is not installed. Try `pip install -r requirements.txt` in the directory of the bot. If that does not work, try installing it using `npx playwright install` and `npx playwright install-deps`
