### ISSUE TITLE
error in Launching Headless Browser

### ISSUE THREAD

**Issue by sttvi** [elebumm/RedditVideoMakerBot#488]
![Screen Shot 2022-06-13 at 10 59 05 PM](https://user-images.githubusercontent.com/66186617/173434879-38af1502-28d4-409c-987e-93a5d6864115.png)
I've already checked #34 and it didn’t work

**Comment by JasonLovesDoggo** [comment]
Try waiting 20 minutes and then try and again

**Comment by sttvi** [comment]
> Try waiting 20 minutes and then try again

still didn't work

**Comment by sttvi** [comment]
![Screen Shot 2022-06-14 at 8 10 39 AM](https://user-images.githubusercontent.com/66186617/173498016-a9a6386c-273a-40fa-87cc-f92e6d6b60d5.png)

**Comment by The-Bot11** [comment]
Does this happen when specify the thread from the `.env` file or the input? or it happens even if you don't specify ?
