### ISSUE TITLE
Cannot create video for certain reddit posts

### ISSUE THREAD

**Issue by derek123bants** [elebumm/RedditVideoMakerBot#491]
It wont let me make videos on certain posts for example, https://www.reddit.com/r/AskReddit/comments/lvtluz/what_is_the_creepiestmost_disturbing_internet/ 
when i run it through python it runs it through the complete process but after the first % bar is complete it comes up with error messages saying the
 MoviePy error: FFMPEG encountered the following error while writing file assets/What is the creepiest/most disturbing internet rabbit hole you’ve gone down, and why.mp4:

 b'assets/What is the creepiest/most disturbing internet rabbit hole you\xe2\x80\x99ve gone down, and why.mp4: No such file or directory\r\n' 
any solutions?

**Comment by JasonLovesDoggo** [comment]
fixed/stale
