### ISSUE TITLE
As far as I've seen no one has solved the credentials issue. Everything is spelled correctly and in its right place in the .env file but I get nothing when running main.py

### ISSUE THREAD

**Issue by MLT-3** [elebumm/RedditVideoMakerBot#492]
And like the last gentleman stated, I'm over the idea of making a bot channel I just want to know what's wrong so I didn't just waste a week of my life on broken code
![image](https://user-images.githubusercontent.com/100401809/173464207-81851752-6086-4633-a677-97e41d07df46.jpeg)

**Comment by JasonLovesDoggo** [comment]
I hate to say it but again this is a credentials issue

**Comment by JasonLovesDoggo** [comment]
What did you put for your client ID?

**Comment by MLT-3** [comment]
![image](https://user-images.githubusercontent.com/100401809/173466029-32ca6e5c-5da0-45f8-8e88-1bd02055b239.jpeg)


I used the characters under personal use script as ID and the blurred blue as the secrete and the yellow as my username and then I put my actual password for that username

**Comment by JasonLovesDoggo** [comment]
Shoot. You did everything correctly My only advice is to double check everything and make sure you keep the quotes in in the .env file

**Comment by MLT-3** [comment]
Is it possible to get a video tutorial with a burner account? because at this point I think MY computer is broken or something

**Comment by Eugen2127** [comment]
I found the solution guys. I guess you all changed the .env.template file to .env. Good, but its not enough on mac. Press right click on the file (My OS is german so i try my best to translate, could be wrong) click on information. Then a window pops up.
There should be the option Name&Suffix. You have to change the suffix also. I hope this works for you guys

**Comment by micziz** [comment]
On my mac it worked automattichly, so i don't know if thats the problem...

**Comment by JasonLovesDoggo** [comment]
wrong password. 🪜
