### ISSUE TITLE
having trouble downloading

### ISSUE THREAD

**Issue by NilskePilske** [elebumm/RedditVideoMakerBot#498]
Im not really familiar with git and python which is probably the reason but could you make an easier to follow install guide (windows)

**Comment by micziz** [comment]
The guide is easy to follow. Also, git is not required do download it.

**Comment by LukaHietala** [comment]
> Im not really familiar with git and python which is probably the reason but could you make an easier to follow install guide (windows)

You can download it as a zip file if you don't know git.

**Comment by JasonLovesDoggo** [comment]
https://capiche.com/q/how-do-you-download-files-from-github
