### ISSUE TITLE
Client id missing enven with it properly filled out

### ISSUE THREAD

**Issue by Milord-Mudkip** [elebumm/RedditVideoMakerBot#50]
So the main issue is I have the whole .env filled out properly but it's still saying the client id is missing
![Screenshot 2022-06-01 201748](https://user-images.githubusercontent.com/101855989/171387512-1d142d9d-0db0-4c08-a465-a89980c2ae2f.png)
g

**Comment by TimeToShine6308** [comment]
https://www.reddit.com/r/redditdev/comments/71v07e/client_id_not_showing_on_app_creation_page/dndpu02/?utm_source=share&utm_medium=web2x

**Comment by Milord-Mudkip** [comment]
> https://www.reddit.com/r/redditdev/comments/71v07e/client_id_not_showing_on_app_creation_page/dndpu02/?utm_source=share&utm_medium=web2x

i already have the client id and secret and its still giving the error

**Comment by BlockArchitech** [comment]
Did you rename the file to `.env`? If you did, check again. Your text editor might of added a .txt or .docx
