### ISSUE TITLE
Multithreading support

### ISSUE THREAD

**Issue by 103thefallen** [elebumm/RedditVideoMakerBot#501]
5-6 minutes to render a 60 second vid, of a video with overlayed pngs and audio shouldn't take that long. Make it available to spread the load or chunks onto different cores to render faster. Would greatly appreciate.
![image](https://user-images.githubusercontent.com/43715321/173698902-1130a703-f4e0-42c0-9e49-99bf9bc84a0b.png)

**Comment by 103thefallen** [comment]
I was wrong with 5-6 minutes, it's 15-20 minutes for a 60 second video. It would take around 6-10 minutes to make it yourself. So, it could definitely could be improved. Maybe caching, saving the backgrounds clip, background music (if added to the main branch), or when re-rendering same thread, different background, or music, or smt, else.

**Comment by AzadKshitij** [comment]
You can actually user multiple threads to render video by threads = no_of_threads in https://github.com/elebumm/RedditVideoMakerBot/blob/cf6b3a9c44d86909f585a3111d62005cd05c8f7d/video_creation/final_video.py#L84
```python
final.write_videofile(
        filename,
        threads=5,
        bitrate="2000k",
        audio_codec="aac",
        codec="h264_videotoolbox",
    )
```

**Comment by JasonLovesDoggo** [comment]
> I was wrong with 5-6 minutes, it's 15-20 minutes for a 60 second video. It would take around 6-10 minutes to make it yourself. So, it could definitely could be improved. Maybe caching, saving the backgrounds clip, background music (if added to the main branch), or when re-rendering same thread, different background, or music, or smt, else.

takes 7m max for me on a crappy 10 y/o pc

**Comment by JasonLovesDoggo** [comment]
Won't implement.

**Comment by Allesanddro** [comment]
![image](https://user-images.githubusercontent.com/23656101/180614773-f3669925-ac78-4be0-8599-0637e5230c2e.png)
xeon e5 2680 v2
