### ISSUE TITLE
How do I fix this? I don't know what happened here

### ISSUE THREAD

**Issue by Jan64X** [elebumm/RedditVideoMakerBot#506]
<img width="852" alt="image" src="https://user-images.githubusercontent.com/57019006/173853264-15fbf235-2c8d-4df5-8e4e-b1b3c72334ea.png">

**Comment by rougeplane** [comment]
Check if reddit credentials in .env file are correct.

**Comment by JasonLovesDoggo** [comment]
Exactly what rogue said.
