### ISSUE TITLE
So now I have this issue....

### ISSUE THREAD

**Issue by MLT-3** [elebumm/RedditVideoMakerBot#509]
![image](https://user-images.githubusercontent.com/100401809/173972532-049563ec-1256-4dbf-885e-79a3b727627a.jpeg)
![Uploading 173972541...]

**Comment by zakhil-dev** [comment]
Your internet connection is too slow and the screenshot download timed out.

**Comment by sarimwaniR** [comment]
solution is to minimus ping by directly wiring the mobile phone to the computer if there is a router then by lain

**Comment by sarimwaniR** [comment]
..

**Comment by sarimwaniR** [comment]
close this plz
