### ISSUE TITLE
Regex installation problem

### ISSUE THREAD

**Issue by leezac26** [elebumm/RedditVideoMakerBot#51]
hey im really new to all of this, while running requirement.txt i get that error 

![image](https://user-images.githubusercontent.com/106668164/171388778-eb892406-d968-47cd-bca2-86efc2f708ce.png)

I tried running 'pip install regex'
 and i get that 
![image](https://user-images.githubusercontent.com/106668164/171389125-506dd44c-50b9-48c3-8db4-ce6a0b14b441.png)
altough when i run requirement.txt again it still gets me the same error
any idea on how to fix it ?

**Comment by leezac26** [comment]
a command prompt flashes and closes instantly when i try to run it

**Comment by BlockArchitech** [comment]
Try installing this: https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by CallumIO** [comment]
Fixed in latest version - no longer relevant

Feel free to reopen if needed.
