### ISSUE TITLE
I filled out the .env file correctly and followed all the steps not sure the issue.

### ISSUE THREAD

**Issue by HeadlessNoble** [elebumm/RedditVideoMakerBot#510]
<img width="664" alt="WeirdError1" src="https://user-images.githubusercontent.com/107591599/174002133-4251fa9c-6056-42de-af67-0a69fd707ea8.PNG">

**Comment by Lath08** [comment]
You need to put in your Reddit login details

**Comment by HeadlessNoble** [comment]
I did "I filled out the .env file correctly"

**Comment by Xefili** [comment]
Try removing the " "

**Comment by Doboxik** [comment]
i have the same exact issue. I already triple checked and the information i put in is 100% correct

**Comment by HeadlessNoble** [comment]
> i had the same issue but figured it out. you need to make sure that when typing the "cd" command into cmd you select the folder you downloaded it in. seems so obvious now but i copied and pasted their command exactly.

👍 fixed

**Comment by HeadlessNoble** [comment]
> i had the same issue but figured it out. you need to make sure that when typing the "cd" command into cmd you select the folder you downloaded it in. seems so obvious now but i copied and pasted their command exactly.

👍 Fixed
