### ISSUE TITLE
py Crashes after converting text to speech

### ISSUE THREAD

**Issue by Kickett** [elebumm/RedditVideoMakerBot#514]
Works 'fine' and then when the TTS is done it crashes, there is a tonne of text that appears for a split second and then disappears which I wasn't able to see.

To confirm the mp3's DO go into the assets folder so I assume it's a playwright issue but I was under the belief that it gets installed during pip3.

**Comment by Kickett** [comment]
edit: upon doing pip3 install moviepy/playwright it's saying "Already satisfied"

**Comment by JasonLovesDoggo** [comment]
do pip not pip3

**Comment by JasonLovesDoggo** [comment]
reopen if still a problem

**Comment by Kickett** [comment]
Yeah it still doesn't work after I use pip only?

It now crashes after putting in the thread.

**Comment by JasonLovesDoggo** [comment]
> Yeah it still doesn't work after I use pip only?
> 
> It now crashes after putting in the thread.

Different issue
