### ISSUE TITLE
The script won´t find the .env file

### ISSUE THREAD

**Issue by Eugen2127** [elebumm/RedditVideoMakerBot#517]
Im using a mac and tried install all like the description told me.
I found the .env.template file and renamed it, but the script wont detect it and asked me if i want to use the setup wizard.
I tried it many times with the setup wizard but it just wont work. Has anyone a clue how to fix it?
Thanks a lot!

**Comment by Westsi** [comment]
What exactly did you rename it to? Is the dot between env and template still there?

**Comment by Eugen2127** [comment]
I renamed it to .env 
The dot isnt there anymore

**Comment by Westsi** [comment]
Have you used .env files successfully on your Mac before?

**Comment by Eugen2127** [comment]
No it is the first time and i think this is the problem. Im a beginner

**Comment by Westsi** [comment]
Ok. I'm pretty sure that .env files don't work natively on Mac.

**Comment by gffgmhj** [comment]
I have the same problem I use windows 10

**Comment by sarimwaniR** [comment]
Interesting

**Comment by Eugen2127** [comment]
I found the solution guys. I guess you all changed the .env.template file to .env. Good, but its not enough on mac. Press right click on the file (My OS is german so i try my best to translate, could be wrong) click on information. Then a window pops up.
There should be the option Name&Suffix. You have to change the suffix also. I hope this works for you guys
