### ISSUE TITLE
Help for a python command

### ISSUE THREAD

**Issue by Alexvarl** [elebumm/RedditVideoMakerBot#52]
Hi i was installing the thing and i dont interest on python and idk how to execute this commands:

3. Run `pip3 install -r requirements.txt`
4. Run `python3 main.py`

Help please

**Comment by Goodgamer78** [comment]
This is assuming you have python installed. Do as follows.
1. Open command prompt. (win + r, type in cmd)
2. cd (path to files here)
3. run pip3 install -r requirements.txt
4. run python3 main.py
5. wait

**Comment by BlockArchitech** [comment]
Ensure you have python3 and pip installed. You can get them here: https://www.python.org/downloads/ and run through the installed.

Then, type `win+r` then `cmd` and press enter. You then then run those commands.

**Comment by Alexvarl** [comment]
> 

![image](https://user-images.githubusercontent.com/67534554/171391959-9cf9d928-d784-454b-96f8-f88624994f1f.png)
nah

**Comment by Alexvarl** [comment]
![image](https://user-images.githubusercontent.com/67534554/171392809-34335ada-d860-4cd0-a33b-0ddc878fda0f.png)
Too lazy to censor username but it says that python is not foundable? but i have python installed!

**Comment by Alexvarl** [comment]
![image](https://user-images.githubusercontent.com/67534554/171393247-84267bd5-bf95-48c0-8524-95aa804af0ea.png)

**Comment by Alexvarl** [comment]
> Type `where python` into terminal and send the output.

sent output?

**Comment by CallumIO** [comment]
> > Type `where python` into terminal and send the output.
> 
> sent output?

Sorry if I wasn't clear! Just meant screenshot / copy-paste what it says.

**Comment by Alexvarl** [comment]
> > > Type `where python` into terminal and send the output.
> > 
> > 
> > sent output?
> 
> Sorry if I wasn't clear! Just meant screenshot / copy-paste what it says.

![image](https://user-images.githubusercontent.com/67534554/171395004-3e8aeae5-88ee-4517-b6b3-9b78c0b99282.png)

**Comment by CallumIO** [comment]
`Windows Key + R`
Then type `sysdm.cpl`
![image](https://user-images.githubusercontent.com/16057677/171395678-046b0ee1-81f2-445e-a46d-48e2697c633e.png)
`Advanced Tab` -> `Environment Variables`
![image](https://user-images.githubusercontent.com/16057677/171395747-2e0400e4-9d95-473f-8e69-57cbf3eaf2a1.png)
`Click Path` -> `Edit`
![image](https://user-images.githubusercontent.com/16057677/171396125-d0f07305-bfa4-4abc-a781-8da47fb0e5c5.png)
`New`
![image](https://user-images.githubusercontent.com/16057677/171396331-3c67b064-4d3c-4fb9-99f3-ab717e2f90a8.png)
Type `C:\Users\mdgui\AppData\Local\Microsoft\WindowsApps`
![image](https://user-images.githubusercontent.com/16057677/171396502-671150a8-25c2-426f-8014-a14eff7e334e.png)

You can then press ok on all the opened windows to exit out.

Try typing `python3` in the terminal now (making sure you're in the project directory).
**You might need to restart the command prompt for it to take effect.**

**Comment by elebumm** [comment]
@CallumIO Thanks so much for this detailed walkthrough. Going to close this as it seems like it has been solved. Feel free to reopen if needed.
