### ISSUE TITLE
Emotes/emojis are getting TTS as well.

### ISSUE THREAD

**Issue by muhammedaksam** [elebumm/RedditVideoMakerBot#528]
Just noticed that emotes/emojis are getting TTS lines as well.

**Comment by JasonLovesDoggo** [comment]
Please specify what branch you are on?

**Comment by muhammedaksam** [comment]
> Please specify what branch you are on?

Main branch.

**Comment by JasonLovesDoggo** [comment]
Yeah this has been fixed in develop
