### ISSUE TITLE
[IMPORTANT] Issue while changing subreddits

### ISSUE THREAD

**Issue by Anvilator-web** [elebumm/RedditVideoMakerBot#529]
Hi,
I'm a Chrome OS Flex User and I have Linux (Debian Bullseye) on my computer.

So, I've been using the Reddit Video Maker Bot for about a week now and I've been using it on r/AskReddit i.e. the default.

Today, I tried to change the subreddit to r/memes and no, i did not add the r/, i typed inside the double-quotes, memes.
After changing the subreddit, the headless browser wouldn't launch and the program just aborted after 30000ms.
I thought it was my mistake, so I changed it back to AskReddit, and it works seamlessly. 

I then tried changing it to r/cursedcomments, and it still wouldn't work.
Seems like subreddits other than r/AskReddit just wouldn't launch the headless browser.

I have tried the following solutions:

1. Obviously I restarted my computer.
2. I shut down Linux manually and restarted the container as it solves most problems.
3. I deleted the folder and recloned the repository and reinstalled all dependencies.

But still, nothing seems to work.

I think this is a bug that is happens on Linux machines.

Specs:

i5-2400 3.10GHz
Chrome OS Flex
8GB DDR3 RAM
1TB HDD
256 GB SDD
NVIDIA GTX 970

Thanks.

**Comment by JasonLovesDoggo** [comment]
hmmm..
will be looked into

**Comment by Anvilator-web** [comment]
Thanks!

**Comment by LukeMedeiros916** [comment]
> Hi, I'm a Chrome OS Flex User and I have Linux (Debian Bullseye) on my computer.
> 
> So, I've been using the Reddit Video Maker Bot for about a week now and I've been using it on r/AskReddit i.e. the default.
> 
> Today, I tried to change the subreddit to r/memes and no, i did not add the r/, i typed inside the double-quotes, memes. After changing the subreddit, the headless browser wouldn't launch and the program just aborted after 30000ms. I thought it was my mistake, so I changed it back to AskReddit, and it works seamlessly.
> 
> I then tried changing it to r/cursedcomments, and it still wouldn't work. Seems like subreddits other than r/AskReddit just wouldn't launch the headless browser.
> 
> I have tried the following solutions:
> 
> 1. Obviously I restarted my computer.
> 2. I shut down Linux manually and restarted the container as it solves most problems.
> 3. I deleted the folder and recloned the repository and reinstalled all dependencies.
> 
> But still, nothing seems to work.
> 
> I think this is a bug that is happens on Linux machines.
> 
> Specs:
> 
> i5-2400 3.10GHz Chrome OS Flex 8GB DDR3 RAM 1TB HDD 256 GB SDD NVIDIA GTX 970
> 
> Thanks.

I believe that your problem is that some Subreddits are marked as NSFW. This requires the bot to click an OK button to proceed. The bot only clicks OK on single posts(not the entire Subreddit)

**Comment by JasonLovesDoggo** [comment]
> > Hi, I'm a Chrome OS Flex User and I have Linux (Debian Bullseye) on my computer.
> > 
> > So, I've been using the Reddit Video Maker Bot for about a week now and I've been using it on r/AskReddit i.e. the default.
> > 
> > Today, I tried to change the subreddit to r/memes and no, i did not add the r/, i typed inside the double-quotes, memes. After changing the subreddit, the headless browser wouldn't launch and the program just aborted after 30000ms. I thought it was my mistake, so I changed it back to AskReddit, and it works seamlessly.
> > 
> > I then tried changing it to r/cursedcomments, and it still wouldn't work. Seems like subreddits other than r/AskReddit just wouldn't launch the headless browser.
> > 
> > I have tried the following solutions:
> > 
> > 1. Obviously I restarted my computer.
> > 2. I shut down Linux manually and restarted the container as it solves most problems.
> > 3. I deleted the folder and recloned the repository and reinstalled all dependencies.
> > 
> > But still, nothing seems to work.
> > 
> > I think this is a bug that is happens on Linux machines.
> > 
> > Specs:
> > 
> > i5-2400 3.10GHz Chrome OS Flex 8GB DDR3 RAM 1TB HDD 256 GB SDD NVIDIA GTX 970
> > 
> > Thanks.
> 
> I believe that your problem is that some Subreddits are marked as NSFW. This requires the bot to click an OK button to proceed. The bot only clicks OK on single posts(not the entire Subreddit)

Can definitely be the case
Going To make this urgent

**Comment by Anvilator-web** [comment]
> > Hi, I'm a Chrome OS Flex User and I have Linux (Debian Bullseye) on my computer.
> > So, I've been using the Reddit Video Maker Bot for about a week now and I've been using it on r/AskReddit i.e. the default.
> > Today, I tried to change the subreddit to r/memes and no, i did not add the r/, i typed inside the double-quotes, memes. After changing the subreddit, the headless browser wouldn't launch and the program just aborted after 30000ms. I thought it was my mistake, so I changed it back to AskReddit, and it works seamlessly.
> > I then tried changing it to r/cursedcomments, and it still wouldn't work. Seems like subreddits other than r/AskReddit just wouldn't launch the headless browser.
> > I have tried the following solutions:
> > 
> > 1. Obviously I restarted my computer.
> > 2. I shut down Linux manually and restarted the container as it solves most problems.
> > 3. I deleted the folder and recloned the repository and reinstalled all dependencies.
> > 
> > But still, nothing seems to work.
> > I think this is a bug that is happens on Linux machines.
> > Specs:
> > i5-2400 3.10GHz Chrome OS Flex 8GB DDR3 RAM 1TB HDD 256 GB SDD NVIDIA GTX 970
> > Thanks.
> 
> I believe that your problem is that some Subreddits are marked as NSFW. This requires the bot to click an OK button to proceed. The bot only clicks OK on single posts(not the entire Subreddit)

hmm,
in that case, there needs to be a new feature to mark OK on entire Subreddits as r/memes and r/cursedcomments are popular among reddit youtubers.
