### ISSUE TITLE
UnboundLocalError after running main.py

### ISSUE THREAD

**Issue by jakeknisely** [elebumm/RedditVideoMakerBot#530]
I am receiving the error: "UnboundLocalError: local variable 'subreddit' referenced before assignment" after running python main.py - Screenshot attached for reference
![Screenshot (162)](https://user-images.githubusercontent.com/79613045/174312715-d71080b9-91ca-48c4-9ca8-a1150794023f.png)

**Comment by JasonLovesDoggo** [comment]
reinstall.
