### ISSUE TITLE
RedditVideoMakerBot2.0 is not working for me.

### ISSUE THREAD

**Issue by HeadlessNoble** [elebumm/RedditVideoMakerBot#538]
<img width="620" alt="weirderror2 0" src="https://user-images.githubusercontent.com/107591599/174424570-bf52b4cd-f894-4212-9516-bd72a9d1b2b4.PNG">

Can anyone help me fix this?

**Comment by daud-ahn** [comment]
have you installed all the requirements?

**Comment by T9es** [comment]
It's not about the requirements. Just read the last line. He does NOT have the utils folder with console.py in there.

**Comment by JasonLovesDoggo** [comment]
he does T9

**Comment by JasonLovesDoggo** [comment]
add a blank `__init__.py` file in the utils folder
