### ISSUE TITLE
Casefold error.

### ISSUE THREAD

**Issue by T9es** [elebumm/RedditVideoMakerBot#540]
```
Saving Text to MP3 files...                          
Traceback (most recent call last):
  File "main.py", line 68, in <module>
    main()
  File "main.py", line 46, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "video_creation\voices.py", line 31, in save_text_to_mp3
    TextToSpeech = TTS()
  File "TTS\swapper.py", line 15, in __new__
    CHOICE = getenv("TTsChoice").casefold()
AttributeError: 'NoneType' object has no attribute 'casefold'
```

Now, I don't think this is in any way caused by the configuration. This error happens when you run the bot out of the box. (Yes, the config is fine, I've checked multiple times, and it's working as intended with other versions/variations. Also tried to fix/get around the issue, but I don't really code on my own, so it's all trial and error until it works.)

**Comment by T9es** [comment]
Actually it WAS the issue with the config. Check your config file if this does happen to you, even small things (invisible characters) will break the whole thing.

**Comment by MondKraecker** [comment]
I have the same error. What config do you mean? The .env file?

**Comment by T9es** [comment]
Yes. Check the ENV file if it's correct. Even missing 1 simple line will break the whole thing.
