### ISSUE TITLE
failing on linux

### ISSUE THREAD

**Issue by Trahaswi** [elebumm/RedditVideoMakerBot#541]
I got this error but I did everything right and `playwright install` said bash: playwright: command not found but i did the `pip3 install -r requirements.txt` i think these are not on path tell me what to do and i got this error when i ran main.py 
```
Launching Headless Browser...
Traceback (most recent call last):
  File "/home/trahaswi/RedditVideoMakerBot/main.py", line 68, in <module>
    main()
  File "/home/trahaswi/RedditVideoMakerBot/main.py", line 47, in main
    download_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "/home/trahaswi/RedditVideoMakerBot/video_creation/screenshot_downloader.py", line 32, in download_screenshots_of_reddit_posts
    browser = p.chromium.launch()
  File "/home/trahaswi/.local/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 11538, in launch
    self._sync(
  File "/home/trahaswi/.local/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 88, in _sync
    return task.result()
  File "/home/trahaswi/.local/lib/python3.10/site-packages/playwright/_impl/_browser_type.py", line 90, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/home/trahaswi/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/home/trahaswi/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Executable doesn't exist at /home/trahaswi/.cache/ms-playwright/chromium-1005/chrome-linux/chrome
```

**Comment by Trahaswi** [comment]
please help

**Comment by daud-ahn** [comment]
Try executing `pip install playwright` manually,

**Comment by Trahaswi** [comment]
It says it exists

**Comment by JasonLovesDoggo** [comment]
Are you on Debian?

**Comment by owengaspard** [comment]
Try to install playwright dependencies.
`playwright install-deps`

**Comment by ART3MISTICAL** [comment]
> I got this error but I did everything right and `playwright install` said bash: playwright: command not found but i did the `pip3 install -r requirements.txt` i think these are not on path tell me what to do and i got this error when i ran main.py
> 
> ```
> Launching Headless Browser...
> Traceback (most recent call last):
>   File "/home/trahaswi/RedditVideoMakerBot/main.py", line 68, in <module>
>     main()
>   File "/home/trahaswi/RedditVideoMakerBot/main.py", line 47, in main
>     download_screenshots_of_reddit_posts(reddit_object, number_of_comments)
>   File "/home/trahaswi/RedditVideoMakerBot/video_creation/screenshot_downloader.py", line 32, in download_screenshots_of_reddit_posts
>     browser = p.chromium.launch()
>   File "/home/trahaswi/.local/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 11538, in launch
>     self._sync(
>   File "/home/trahaswi/.local/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 88, in _sync
>     return task.result()
>   File "/home/trahaswi/.local/lib/python3.10/site-packages/playwright/_impl/_browser_type.py", line 90, in launch
>     Browser, from_channel(await self._channel.send("launch", params))
>   File "/home/trahaswi/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 39, in send
>     return await self.inner_send(method, params, False)
>   File "/home/trahaswi/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
>     result = next(iter(done)).result()
> playwright._impl._api_types.Error: Executable doesn't exist at /home/trahaswi/.cache/ms-playwright/chromium-1005/chrome-linux/chrome
> ```

install these packages through your package manager ->
fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcairo2 libcups2 libdbus-1-3 libdrm2 libegl1 libgbm1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxrandr2 libxshmfence1 xvfb fonts-noto-color-emoji ttf-unifont libfontconfig libfreetype6 xfonts-cyrillic xfonts-scalable fonts-ipafont-gothic fonts-wqy-zenhei fonts-tlwg-loma-otf ttf-ubuntu-font-family ffmpeg libcairo-gobject2 libdbus-glib-1-2 libfontconfig1 libgdk-pixbuf2.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libxcb-shm0 libxcursor1 libxi6 libxrender1 libxt6 libxtst6 gstreamer1.0-libav gstreamer1.0-plugins-bad gstreamer1.0-plugins-base gstreamer1.0-plugins-good libenchant1c2a libepoxy0 libevdev2 libgl1 libgles2 libgstreamer-gl1.0-0 libgstreamer1.0-0 libharfbuzz-icu0 libharfbuzz0b libhyphen0 libicu66 libjpeg-turbo8 libnotify4 libopengl0 libopenjp2-7 libopus0 libpng16-16 libsecret-1-0 libsoup2.4-1 libvpx6 libwayland-client0 libwayland-egl1 libwayland-server0 libwebp6 libwebpdemux2 libwoff1 libxkbcommon0 libxml2 libxslt1.1

**Comment by Trahaswi** [comment]
> Are you on Debian?

arch but i have a debian machine

**Comment by Trahaswi** [comment]
> > I got this error but I did everything right and `playwright install` said bash: playwright: command not found but i did the `pip3 install -r requirements.txt` i think these are not on path tell me what to do and i got this error when i ran main.py
> 
> > 
> 
> > ```
> 
> > Launching Headless Browser...
> 
> > Traceback (most recent call last):
> 
> >   File "/home/trahaswi/RedditVideoMakerBot/main.py", line 68, in <module>
> 
> >     main()
> 
> >   File "/home/trahaswi/RedditVideoMakerBot/main.py", line 47, in main
> 
> >     download_screenshots_of_reddit_posts(reddit_object, number_of_comments)
> 
> >   File "/home/trahaswi/RedditVideoMakerBot/video_creation/screenshot_downloader.py", line 32, in download_screenshots_of_reddit_posts
> 
> >     browser = p.chromium.launch()
> 
> >   File "/home/trahaswi/.local/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 11538, in launch
> 
> >     self._sync(
> 
> >   File "/home/trahaswi/.local/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 88, in _sync
> 
> >     return task.result()
> 
> >   File "/home/trahaswi/.local/lib/python3.10/site-packages/playwright/_impl/_browser_type.py", line 90, in launch
> 
> >     Browser, from_channel(await self._channel.send("launch", params))
> 
> >   File "/home/trahaswi/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 39, in send
> 
> >     return await self.inner_send(method, params, False)
> 
> >   File "/home/trahaswi/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
> 
> >     result = next(iter(done)).result()
> 
> > playwright._impl._api_types.Error: Executable doesn't exist at /home/trahaswi/.cache/ms-playwright/chromium-1005/chrome-linux/chrome
> 
> > ```
> 
> 
> 
> install these packages through your package manager ->
> 
> fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcairo2 libcups2 libdbus-1-3 libdrm2 libegl1 libgbm1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxrandr2 libxshmfence1 xvfb fonts-noto-color-emoji ttf-unifont libfontconfig libfreetype6 xfonts-cyrillic xfonts-scalable fonts-ipafont-gothic fonts-wqy-zenhei fonts-tlwg-loma-otf ttf-ubuntu-font-family ffmpeg libcairo-gobject2 libdbus-glib-1-2 libfontconfig1 libgdk-pixbuf2.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libxcb-shm0 libxcursor1 libxi6 libxrender1 libxt6 libxtst6 gstreamer1.0-libav gstreamer1.0-plugins-bad gstreamer1.0-plugins-base gstreamer1.0-plugins-good libenchant1c2a libepoxy0 libevdev2 libgl1 libgles2 libgstreamer-gl1.0-0 libgstreamer1.0-0 libharfbuzz-icu0 libharfbuzz0b libhyphen0 libicu66 libjpeg-turbo8 libnotify4 libopengl0 libopenjp2-7 libopus0 libpng16-16 libsecret-1-0 libsoup2.4-1 libvpx6 libwayland-client0 libwayland-egl1 libwayland-server0 libwebp6 libwebpdemux2 libwoff1 libxkbcommon0 libxml2 libxslt1.1

let me try

**Comment by Trahaswi** [comment]
![image](https://user-images.githubusercontent.com/102136210/174463972-a92ae468-9016-4dda-8fcd-519de01673b3.jpeg)
target not found

**Comment by Trahaswi** [comment]
![image](https://user-images.githubusercontent.com/102136210/174464008-41f56cfc-7b29-4142-aadd-ff4b1447d46d.jpeg)
target not found :/

**Comment by Trahaswi** [comment]
> > I got this error but I did everything right and `playwright install` said bash: playwright: command not found but i did the `pip3 install -r requirements.txt` i think these are not on path tell me what to do and i got this error when i ran main.py
> 
> > 
> 
> > ```
> 
> > Launching Headless Browser...
> 
> > Traceback (most recent call last):
> 
> >   File "/home/trahaswi/RedditVideoMakerBot/main.py", line 68, in <module>
> 
> >     main()
> 
> >   File "/home/trahaswi/RedditVideoMakerBot/main.py", line 47, in main
> 
> >     download_screenshots_of_reddit_posts(reddit_object, number_of_comments)
> 
> >   File "/home/trahaswi/RedditVideoMakerBot/video_creation/screenshot_downloader.py", line 32, in download_screenshots_of_reddit_posts
> 
> >     browser = p.chromium.launch()
> 
> >   File "/home/trahaswi/.local/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 11538, in launch
> 
> >     self._sync(
> 
> >   File "/home/trahaswi/.local/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 88, in _sync
> 
> >     return task.result()
> 
> >   File "/home/trahaswi/.local/lib/python3.10/site-packages/playwright/_impl/_browser_type.py", line 90, in launch
> 
> >     Browser, from_channel(await self._channel.send("launch", params))
> 
> >   File "/home/trahaswi/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 39, in send
> 
> >     return await self.inner_send(method, params, False)
> 
> >   File "/home/trahaswi/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
> 
> >     result = next(iter(done)).result()
> 
> > playwright._impl._api_types.Error: Executable doesn't exist at /home/trahaswi/.cache/ms-playwright/chromium-1005/chrome-linux/chrome
> 
> > ```
> 
> 
> 
> install these packages through your package manager ->
> 
> fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcairo2 libcups2 libdbus-1-3 libdrm2 libegl1 libgbm1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxrandr2 libxshmfence1 xvfb fonts-noto-color-emoji ttf-unifont libfontconfig libfreetype6 xfonts-cyrillic xfonts-scalable fonts-ipafont-gothic fonts-wqy-zenhei fonts-tlwg-loma-otf ttf-ubuntu-font-family ffmpeg libcairo-gobject2 libdbus-glib-1-2 libfontconfig1 libgdk-pixbuf2.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libxcb-shm0 libxcursor1 libxi6 libxrender1 libxt6 libxtst6 gstreamer1.0-libav gstreamer1.0-plugins-bad gstreamer1.0-plugins-base gstreamer1.0-plugins-good libenchant1c2a libepoxy0 libevdev2 libgl1 libgles2 libgstreamer-gl1.0-0 libgstreamer1.0-0 libharfbuzz-icu0 libharfbuzz0b libhyphen0 libicu66 libjpeg-turbo8 libnotify4 libopengl0 libopenjp2-7 libopus0 libpng16-16 libsecret-1-0 libsoup2.4-1 libvpx6 libwayland-client0 libwayland-egl1 libwayland-server0 libwebp6 libwebpdemux2 libwoff1 libxkbcommon0 libxml2 libxslt1.1

this whole thing sounds familiar on debian, arch returns with errors as a programmer i hate errors.

**Comment by ART3MISTICAL** [comment]
> ![image](https://user-images.githubusercontent.com/102136210/174464008-41f56cfc-7b29-4142-aadd-ff4b1447d46d.jpeg) target not found :/

install yay,
https://www.tecmint.com/install-yay-aur-helper-in-arch-linux-and-manjaro/
it installs programs from the aur(arch user repo)
then try again with 'yay -S'

**Comment by Trahaswi** [comment]
already have it ill try it in a moment

**Comment by owengaspard** [comment]
Try to enable the multilib repo in /etc/pacman.conf m

**Comment by Trahaswi** [comment]
I got it working

**Comment by Trahaswi** [comment]
well got a new error `Traceback (most recent call last):
  File "/home/trahaswi/.local/lib/python3.10/site-packages/requests/models.py", line 972, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/trahaswi/RedditVideoMakerBot/main.py", line 69, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))
  File "/home/trahaswi/RedditVideoMakerBot/main.py", line 62, in run_many
    main()
  File "/home/trahaswi/RedditVideoMakerBot/main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "/home/trahaswi/RedditVideoMakerBot/video_creation/voices.py", line 56, in save_text_to_mp3
    TextToSpeech.tts(
  File "/home/trahaswi/RedditVideoMakerBot/TTS/POLLY.py", line 61, in tts
    if response.json()["error"] == "Text length is too long!":
  File "/home/trahaswi/.local/lib/python3.10/site-packages/requests/models.py", line 976, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by Trahaswi** [comment]
someone please write better documentation on how to install on linux

**Comment by Trahaswi** [comment]
another error 

Traceback (most recent call last):
  File "/home/trahaswi/RedditVideoMakerBot-2.0/main.py", line 66, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))
  File "/home/trahaswi/RedditVideoMakerBot-2.0/main.py", line 59, in run_many
    main()
  File "/home/trahaswi/RedditVideoMakerBot-2.0/main.py", line 50, in main
    final_video = make_final_video(number_of_comments, length)
  File "/home/trahaswi/RedditVideoMakerBot-2.0/video_creation/final_video.py", line 34, in make_final_video
    VideoFileClip("assets/temp/background.mp4")
  File "/home/trahaswi/.local/lib/python3.10/site-packages/moviepy/video/io/VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "/home/trahaswi/.local/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_reader.py", line 73, in __init__
    self.lastread = self.read_frame()
  File "/home/trahaswi/.local/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_reader.py", line 133, in read_frame
    raise IOError(("MoviePy error: failed to read the first frame of "
OSError: MoviePy error: failed to read the first frame of video file assets/temp/background.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.

**Comment by Trahaswi** [comment]
@owengaspard can you help??

**Comment by Trahaswi** [comment]
I am not I'm using the latest version in the AUR

**Comment by Trahaswi** [comment]
But I'll try

**Comment by JasonLovesDoggo** [comment]
stale
