### ISSUE TITLE
Cant run main.py

### ISSUE THREAD

**Issue by WorriedTripod68** [elebumm/RedditVideoMakerBot#557]
Traceback (most recent call last):
  File "C:\Users\nigel\OneDrive\Desktop\RedditVideoMakerBot-2.0\main.py", line 68, in <module>
    main()
  File "C:\Users\nigel\OneDrive\Desktop\RedditVideoMakerBot-2.0\main.py", line 45, in main
    reddit_object = get_obj()
  File "C:\Users\nigel\OneDrive\Desktop\RedditVideoMakerBot-2.0\main.py", line 42, in get_obj
    reddit_obj = get_subreddit_threads()
  File "C:\Users\nigel\OneDrive\Desktop\RedditVideoMakerBot-2.0\reddit\subreddit.py", line 94, in get_subreddit_threads
    if len(top_level_comment.body) <= int(environ["MAX_COMMENT_LENGTH"]):
  File "C:\Users\nigel\AppData\Local\Programs\Python\Python310\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'MAX_COMMENT_LENGTH'

anyone know how to fix this?

**Comment by Jan64X** [comment]
I'm having this issue too, please tell me when this has a fix

**Comment by ART3MISTICAL** [comment]
> Traceback (most recent call last): File "C:\Users\nigel\OneDrive\Desktop\RedditVideoMakerBot-2.0\main.py", line 68, in main() File "C:\Users\nigel\OneDrive\Desktop\RedditVideoMakerBot-2.0\main.py", line 45, in main reddit_object = get_obj() File "C:\Users\nigel\OneDrive\Desktop\RedditVideoMakerBot-2.0\main.py", line 42, in get_obj reddit_obj = get_subreddit_threads() File "C:\Users\nigel\OneDrive\Desktop\RedditVideoMakerBot-2.0\reddit\subreddit.py", line 94, in get_subreddit_threads if len(top_level_comment.body) <= int(environ["MAX_COMMENT_LENGTH"]): File "C:\Users\nigel\AppData\Local\Programs\Python\Python310\lib\os.py", line 679, in **getitem** raise KeyError(key) from None KeyError: 'MAX_COMMENT_LENGTH'
> 
> anyone know how to fix this?



> I'm having this issue too, please tell me when this has a fix

fill the .env file

**Comment by T9es** [comment]
It literally says what is wrong. You are missing the "max comment length" parameter.

**Comment by JasonLovesDoggo** [comment]
Literally what @T9es said.
specify it in the .env file

**Comment by Arpeture** [comment]
> Literally what @T9es said. specify it in the .env file

I have the same error I had to manually add "MAX_COMMENT_LENGTH" in the file.
Now I'm getting a similar one with TTsChoice...

**Comment by cadhelp** [comment]
It looks like the comments in the env file are causing issues.
I changed my line to look like this and it works now.
Notice the # default is 500 is no longer inline with the variable
```
# max number of characters a comment can have. # default is 500
MAX_COMMENT_LENGTH="500"
```
