### ISSUE TITLE
SOX could not be found! and crashing in creating the final video part.

### ISSUE THREAD

**Issue by Nikicha316** [elebumm/RedditVideoMakerBot#559]
I see this when I lunch the main.py:
![174457949-c461c100-1427-4ea0-89f1-39a341647506](https://user-images.githubusercontent.com/49568616/174457975-fe418ffd-21ca-42bf-8dbf-ae9ac4ac0ab6.png)

Crashing in the "Creating final video" part:
![image](https://user-images.githubusercontent.com/49568616/174458075-7340628f-1541-4e43-a8e7-0a0810f02c3f.png)

**Comment by Nikicha316** [comment]
Btw before that I successfully created 3 videos. I set the program to make 20 vid and then close, but it's making only 1 and crashing I change it to 1 and was working for 1 video and then crashing.

**Comment by JasonLovesDoggo** [comment]
so install SoX.... 
read the docs on how.

**Comment by Nikicha316** [comment]
But I've got SoX installed

**Comment by Arpeture** [comment]
> But I've got SoX installed

I'm getting the exact same error, and how would I even launch the program when everything FINALLY WORKS?
