### ISSUE TITLE
KeyError: 'thread_content' when saving .MP3 files

### ISSUE THREAD

**Issue by jacobjake1** [elebumm/RedditVideoMakerBot#561]
Logging into Reddit.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Getting subreddit threads...                                                                                        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Using subreddit: r/TIFU from environment variable config
Video will be: TIFU by telling people i had a twin 👍
Thread has 15944 upvotes
Thread has a upvote ratio of 91.0%
Thread has 567 comments
Received subreddit threads Successfully.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Saving Text to MP3 files...                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    main()
  File "main.py", line 47, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\jacob\Desktop\red\video_creation\voices.py", line 44, in save_text_to_mp3
    sanitize_text(reddit_obj["thread_content"]),
KeyError: 'thread_content'

C:\Users\jacob\Desktop\red>

**Comment by JasonLovesDoggo** [comment]
Try rerunning

**Comment by jacobjake1** [comment]
> 

Same thing every time

**Comment by jacobjake1** [comment]
> Try rerunning

I even reforked and ran it, it's always the same error
