### ISSUE TITLE
[ERROR] No module named 'dotenv'

### ISSUE THREAD

**Issue by Kirisaro** [elebumm/RedditVideoMakerBot#566]
![image](https://user-images.githubusercontent.com/24460756/174464750-d9a1080e-67e3-4a06-8bad-03b09f26627a.png)

Wasn't able to get python main.py to work since im getting a dotenv error, tried redownloading dotenv with pip globally and locally and no luck

**Comment by the-MetalBox** [comment]
I have the same issue and I cant fix it either. Hopefully, someone will help us.

**Comment by Pol-Fombona** [comment]
Try: "pip install python-dotenv"

**Comment by iGetAlways** [comment]
> Try: "pip install python-dotenv"

```Requirement already satisfied: python-dotenv in c:\...\appdata\local\programs\python\python38\lib\site-packages (0.20.0)```

still getting this

```Traceback (most recent call last):
  File "C:\...\main.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'```

**Comment by Louis03x** [comment]
Hey guys im completely new to this and getting the same error. Hope somebody can help me/us :)

**Comment by Kirisaro** [comment]
> Try: "pip install python-dotenv"

Yeah I've tried that installing it globally and locally with no avail

**Comment by BradTFT** [comment]
have you tried `pip3 install python-dotenv` or any other pip install method?

**Comment by Kirisaro** [comment]
> have you tried `pip3 install python-dotenv` or any other pip install method?

Yeah I've tried them and tried uninstalling dotenv, and reinstalling the repo with each method as well

**Comment by iGetAlways** [comment]
> have you tried `pip3 install python-dotenv` or any other pip install method?

i tried too but no change

**Comment by BradTFT** [comment]
have you tried being in a virtual env? not sure if it would work but you can try it.

```
#cd to the source
python3 -m venv venv
source venv/bin/activate
```

**Comment by Kirisaro** [comment]
Haven't tried this I'll keep you guys posted

**Comment by BradTFT** [comment]
you may have better luck with the venv if you use your python version instead of `python3` for example i use `python3.9`

**Comment by BradTFT** [comment]
once the venv is activated your terminal will look something like this

`(venv)username $`

next you want to re install all the pip packages

``` 
pip3 install -r requirements.txt
playwright install
pip3 install python-dotenv
playwright install-deps
```

**Comment by LohnGG** [comment]
For me it didn't work with `python3 main.py` but with `python main.py` if that helps

**Comment by BradTFT** [comment]
could mean your python version is out of date

**Comment by iGetAlways** [comment]
> have you tried being in a virtual env? not sure if it would work but you can try it.
> 
> ```
> #cd to the source
> python3 -m venv venv
> source venv/bin/activate
> ```

i tried this, first i typed python3 -m venv venv and got nothing in terminal. after this, i typed source venv/bin/activate and i got an error `source : The term 'source' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

after those, i tried python main.py and it worked somehow. today this was may first attempt to run main.py and idk if my problem solved by `python3 -m venv venv` command or not. ty guys good luck everyone

**Comment by Kirisaro** [comment]
well now that I tried it im getting a new error 
![image](https://user-images.githubusercontent.com/24460756/174670941-9204a840-b165-48dd-ac51-49ccae958f5a.png)

**Comment by Kirisaro** [comment]
> well now that I tried it im getting a new error ![image](https://github.com/assets/24460756/9204a840-b165-48dd-ac51-49ccae958f5a)

Not sure why I've gotten the error the pathing seemed to be correct

**Comment by BradTFT** [comment]
have you installed sox correctly?

**Comment by Kirisaro** [comment]
> have you installed sox correctly?

I think I have, how did you go about it?

**Comment by BradTFT** [comment]
i used this [link](https://sourceforge.net/projects/sox/files/sox/) and installed the latest version on the left side. (its the tarball version). click the big green button pictured below. then unpack it based on your OS. for debain/ubuntu use this [link](https://www.codegrepper.com/code-examples/shell/how+to+install+tar+bz2+software) (actually this link may work for all os's. idk tho) then restart your terminal and re run the script
![Screenshot 2022-06-20 4 08 34 PM](https://user-images.githubusercontent.com/50968931/174671650-7548bc11-051a-485a-a347-68ab25db38e4.png)

**Comment by Kirisaro** [comment]
> i used this [link](https://sourceforge.net/projects/sox/files/sox/) and installed the latest version on the left side. (its the tarball version). click the big green button pictured below. then unpack it based on your OS. for debain/ubuntu use this [link](https://www.codegrepper.com/code-examples/shell/how+to+install+tar+bz2+software) (actually this link may work for all os's. idk tho) then restart your terminal and re run the script ![Screenshot 2022-06-20 4 08 34 PM](https://github.com/assets/50968931/7548bc11-051a-485a-a347-68ab25db38e4)

Okay so I reinstalled it and put it into program files 86 i'll restart console rn and see if it works

**Comment by Kirisaro** [comment]
Nope still getting the same error do I have to run sox or the other extension before trying the script?

**Comment by BradTFT** [comment]
i dont think so. i just installed everything and went from there. not sure then. sorry

**Comment by Kirisaro** [comment]
No problem thanks for the help !

**Comment by BradTFT** [comment]
yw

**Comment by LukeMedeiros916** [comment]
This won't run on REPL.IT without some tweaking BTW.
