### ISSUE TITLE
[ERROR] No Module named Praw

### ISSUE THREAD

**Issue by the-MetalBox** [elebumm/RedditVideoMakerBot#567]
C:\Users\Ethan\Documents\RedditVideoMakerBot-master>python3 main.py
Traceback (most recent call last):
  File "C:\Users\Ethan\Documents\RedditVideoMakerBot-master\main.py", line 6, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "C:\Users\Ethan\Documents\RedditVideoMakerBot-master\reddit\subreddit.py", line 3, in <module>
    import praw
ModuleNotFoundError: No module named 'praw'

I get this error every time when I run the main.py script

**Comment by fredxp2003** [comment]
Make sure to run the command `pip install -r requirements.txt`.  This will install all of the required modules.

**Comment by the-MetalBox** [comment]
I did, and right now it's working. I'm going to close the issue.

**Comment by ItsYoBoi69Master** [comment]
did the command and this happend:
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
