### ISSUE TITLE
Playwright issue

### ISSUE THREAD

**Issue by lucieluc1234** [elebumm/RedditVideoMakerBot#574]
if i run the command i get a message that says:

**Looks like Playwright was just installed or updated. 
Please run the following command to download new browsers:  

playwright install                                     

 <3 Playwright Team**

If i run the playwright install command i get an error (the red text at the bottem of the screenshot)
![tiktok issue 1](https://user-images.githubusercontent.com/68748168/174481098-d42d881f-144b-4d2f-9eff-3df699a17044.png)

**Comment by DiamantNez** [comment]
Run python -m playwright install

**Comment by lucieluc1234** [comment]
it worked thanks
