### ISSUE TITLE
Required configuration setting 'client_id' missing.

### ISSUE THREAD

**Issue by ivern68** [elebumm/RedditVideoMakerBot#576]
i have done everything correctly and have double checked multiple times, yes i did rename template to .env Please can anyone help

"\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 258, in __init__
    raise MissingRequiredAttributeException(
praw.exceptions.MissingRequiredAttributeException: Required configuration setting 'client_id' missing.
This setting can be provided in a praw.ini file, as a keyword argument to the `Reddit` class constructor, or as an environment variable."

**Comment by PrestoSole** [comment]
You can follow the step-by-step [documentation](https://luka-hietala.gitbook.io/documentation-for-the-reddit-bot/) on how to use the bot, that should clear up most issues. I believe the "Get your reddit key" section is what you want!
