### ISSUE TITLE
Not an issues, just a question...

### ISSUE THREAD

**Issue by Minni1337Me** [elebumm/RedditVideoMakerBot#577]
How to change the voice to the same voice in the example video?

Is this in the tiktok.py?

changing

VOICE="emma" # e.g. en_us_002
TTsChoice="polly" # todo add docs

to

VOICE="human" # e.g. en_us_002
TTsChoice="tiktok" # todo add docs

just gives me a lot of errors. Or how else to have the correct voice?

**Comment by LukeZekes** [comment]
### TTsChoice="polly"


### TTsChoice="tiktok"
- "en_us_ghostface"  # Ghost Face
- "en_us_chewbacca"  # Chewbacca
- "en_us_c3po"  # C3PO
- "en_us_stitch"  # Stitch
- "en_us_stormtrooper"  # Stormtrooper
- "en_us_rocket"  # Rocket
- "en_au_001"  # English AU - Female
- "en_au_002"  # English AU - Male
- "en_uk_001"  # English UK - Male 1
- "en_uk_003"  # English UK - Male 2
- "en_us_001"  # English US - Female (Int. 1)
- "en_us_002"  # English US - Female (Int. 2)
- "en_us_006"  # English US - Male 1
- "en_us_007"  # English US - Male 2
- "en_us_009"  # English US - Male 3
- "en_us_010"
- "fr_001"  # French - Male 1
-  "fr_002"  # French - Male 2
- "de_001"  # German - Female
- "de_002"  # German - Male
- "es_002"  # Spanish - Male
- "es_mx_002"  # Spanish MX - Male
- "br_001"  # Portuguese BR - Female 1
- "br_003"  # Portuguese BR - Female 2
- "br_004"  # Portuguese BR - Female 3
- "br_005"  # Portuguese BR - Male
- "id_001"  # Indonesian - Female
- "jp_001"  # Japanese - Female 1
- "jp_003"  # Japanese - Female 2
- "jp_005"  # Japanese - Female 3
- "jp_006"  # Japanese - Male
- "kr_002"  # Korean - Male 1
- "kr_003"  # Korean - Female
- "kr_004"  # Korean - Male 2

**Comment by LukeZekes** [comment]
### TTsChoice="gtts"
Value of VOICE does not matter as far as I can tell

### TTsChoice="polly"
Valid values for VOICE are:
- "Brian"
- "Emma"
- "Russell"
- "Joey"
- "Matthew"
- "Joanna"
- "Kimberly"
- "Amy"
- "Geraint"
- "Nicole"
- "Justin"
- "Ivy"
- "Kendra"
- "Salli"
- "Raveena"

### TTsChoice="tiktok"
Valid values for VOICE are:
- "en_us_ghostface"  # Ghost Face
- "en_us_chewbacca"  # Chewbacca
- "en_us_c3po"  # C3PO
- "en_us_stitch"  # Stitch
- "en_us_stormtrooper"  # Stormtrooper
- "en_us_rocket"  # Rocket

- "en_au_001"  # English AU - Female
- "en_au_002"  # English AU - Male
- "en_uk_001"  # English UK - Male 1
- "en_uk_003"  # English UK - Male 2
- "en_us_001"  # English US - Female (Int. 1)
- "en_us_002"  # English US - Female (Int. 2)
- "en_us_006"  # English US - Male 1
- "en_us_007"  # English US - Male 2
- "en_us_009"  # English US - Male 3
- "en_us_010"
- "fr_001"  # French - Male 1
-  "fr_002"  # French - Male 2
- "de_001"  # German - Female
- "de_002"  # German - Male
- "es_002"  # Spanish - Male
- "es_mx_002"  # Spanish MX - Male
- "br_001"  # Portuguese BR - Female 1
- "br_003"  # Portuguese BR - Female 2
- "br_004"  # Portuguese BR - Female 3
- "br_005"  # Portuguese BR - Male
- "id_001"  # Indonesian - Female
- "jp_001"  # Japanese - Female 1
- "jp_003"  # Japanese - Female 2
- "jp_005"  # Japanese - Female 3
- "jp_006"  # Japanese - Male
- "kr_002"  # Korean - Male 1
- "kr_003"  # Korean - Female
- "kr_004"  # Korean - Male 2

**Comment by carlosmartell97** [comment]
@LukeZekes @Minni1337Me There's no _tiktok.py_ file that I can see, where are you changing these **TTsChoice** and **VOICE** values?

**Comment by aLtRD** [comment]
> @LukeZekes @Minni1337Me There's no _tiktok.py_ file that I can see, where are you changing these **TTsChoice** and **VOICE** values?

You can change the voice values in the **.env** folder. The **tiktok.py** file is in the **TTS** folder.

**Comment by carlosmartell97** [comment]
@aLtRD Oh I see, it was just added a few days ago. Thanks!
