### ISSUE TITLE
Program Ignores RANDOM_THREAD flag

### ISSUE THREAD

**Issue by Luz5020** [elebumm/RedditVideoMakerBot#578]
When setting the RANDOM_THREAD .env Flag to "no" the program uses a Random Thread anyway, documentation and comments seem to indicate that the program should ask for a link if the flag was set to "no" (as it worked in 1.1) so I'm not sure why it's happening.

**Comment by IslaFTW** [comment]
same issue here :/

**Comment by RafaelSilva30** [comment]
Same here.

**Comment by Luz5020** [comment]
I have stopped using the program so there will be no further testing on my part
