### ISSUE TITLE
"SoX not found"

### ISSUE THREAD

**Issue by Arpeture** [elebumm/RedditVideoMakerBot#586]
Upon finally getting stuff to even run, I get the error saying SoX isn't found, even though I:
1. Installed it twice to check
2. Manually added a Path variable
I checked on the closed issues and saw someone who had the same problem, yet someone just said "install SoX using the docs or something, yet I literally cant find any docs on how to "install it properly"
![image](https://user-images.githubusercontent.com/107810425/174495252-cdf5ec99-05ab-4816-b04f-302f13e83fc5.png)

**Comment by Arpeture** [comment]
Was able to fix it.
Though I am now greeted with YET ANOTHER lovely error.
![image](https://user-images.githubusercontent.com/107810425/174497006-f6005c93-33f4-4fa8-bf3d-6864c0014827.png)

Please make an actual good documentation on how to install it!

**Comment by Nikicha316** [comment]
How did you fix it?

**Comment by CJthisis** [comment]
> Was able to fix it. Though I am now greeted with YET ANOTHER lovely error. ![image](https://user-images.githubusercontent.com/107810425/174497006-f6005c93-33f4-4fa8-bf3d-6864c0014827.png)
> 
> Please make an actual good documentation on how to install it!

The error you got seems to be connected to the .env file, because in the second to last line it mentions the client id missing, which you set in the .env file. (Did you rename the file '.env.template' to '.env'?) (If you didn't, that would explain the error)

**Comment by PrestoSole** [comment]
@Arpeture @CJthisis You can follow the step-by-step [documentation](https://luka-hietala.gitbook.io/documentation-for-the-reddit-bot/) on how to use the bot, that should clear up most issues. I believe the "Get your reddit key" section is what you want!

**Comment by DeadSilencer** [comment]
Thank you so much for your help! I am not able to try but I already know
where I messed up.
