### ISSUE TITLE
Main.py closes after fetching reddit data

### ISSUE THREAD

**Issue by squidud** [elebumm/RedditVideoMakerBot#588]
So I think I'm doing everything right, but when the script gets to a certain point it just closes. I see 
"Using subreddit: r/askreddit from environment variable config
Video will be: What unimpressive things are people idiotically proud of? 👍
Thread has 6483 upvotes
Thread has a upvote ratio of 95.0%
Thread has 5346 comments"
in the console, and after a few seconds, it just closes. Totally new to python so I'm very dumb lol.

**Comment by Arpeture** [comment]
> 

Hi how did u get like your TTsChoice thing to work?

**Comment by squidud** [comment]
> > 
> 
> Hi how did u get like your TTsChoice thing to work?

I'm sorry, I don't understand the question.
