### ISSUE TITLE
line 4, in <module>             import praw  ModuleNotFoundError: No module named 'praw'

### ISSUE THREAD

**Issue by ItsYoBoi69Master** [elebumm/RedditVideoMakerBot#589]
line 6, in <module>
    from reddit.subreddit import get_subreddit_threads
Import "dotenv" could not be resolved
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by ytfuzzy** [comment]
https://github.com/elebumm/RedditVideoMakerBot/issues/567#issuecomment-1159809072 

Check this solution to see if it works for you

**Comment by ItsYoBoi69Master** [comment]
Just like I commented on the 'solution' you referenced, I tried this:

pip install -r requirements.txt

and it gave me this error:

Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

(There is a file called requirementd.txt)

**Comment by Xefili** [comment]
Move in the directory of `requirements.txt` and run `pip install -r requirements.txt` again. If that doesn't work try `pip install praw`

**Comment by ItsYoBoi69Master** [comment]
How do you move into a directory?

**Comment by ItsYoBoi69Master** [comment]
I installed a whole lot of modules manually but now Im stuck on:
ModuleNotFoundError: No module named 'reddit.subreddit'

**Comment by Xefili** [comment]
maybe a file is missing, try redownloading it again

**Comment by ItsYoBoi69Master** [comment]
did it but its still the same issue.
Thank you btw. Im new here and I appreciate the support
