### ISSUE TITLE
Exception has occured: MutagenError

### ISSUE THREAD

**Issue by hyperno8er** [elebumm/RedditVideoMakerBot#593]
Everytime i run main.py it comes through to the mp3 files  then crashes and leaves me with this error
![image](https://user-images.githubusercontent.com/107857750/174597894-42b24e89-ffc5-4841-bdbb-1684acb17262.png)

**Comment by JoshA02** [comment]
> I haven't. I've reinstalled everything, still the same error and i have just given up.

I've been looking around on the discord server and others who have the same issue have had success using older versions (V1.1).

**Comment by lodenrogue** [comment]
Can you cd into the assets/temp/mp3 directory and see if the title.mp3 file gets created at any time during the process?

**Comment by diabate5** [comment]
I have the same issue, I can say that title.mp3 doesn't get created at any time
