### ISSUE TITLE
main.py error

### ISSUE THREAD

**Issue by Jeyavarshan** [elebumm/RedditVideoMakerBot#596]
I have tried many times tying to fix this error pls  #help[](url
![Screenshot 2022-06-20 200138](https://user-images.githubusercontent.com/67764536/174625065-f9deb8a6-f4f9-49b3-b4d3-99527c6f4c9d.png)
)

**Comment by HallowedDust5** [comment]
The second error looks like you haven't set up your .env file properly.

**Comment by Jeyavarshan** [comment]
> The second error looks like you haven't set up your .env file properly.

how to do that?

**Comment by Jeyavarshan** [comment]
![Screenshot 2022-06-20 203607](https://user-images.githubusercontent.com/67764536/174631497-6cd154df-09ff-4194-ae1a-7db7f8fbbdcb.png)

**Comment by Jeyavarshan** [comment]
> Follow the instructions [here](https://luka-hietala.gitbook.io/documentation-for-the-reddit-bot/python-reddit-api-wrapper-details) to set up your .env

I followed everything according to the instruction , But still Its the same

**Comment by HallowedDust5** [comment]
You get the same error?
