### ISSUE TITLE
Running setup.pu install for typed-ast did not run successfully 

### ISSUE THREAD

**Issue by lesterrar** [elebumm/RedditVideoMakerBot#60]
![Uploading 1654088286779.jpg…]()

**Comment by lesterrar** [comment]
![reg](https://user-images.githubusercontent.com/44342036/171413604-ad9dbfb6-2213-4173-a0fd-1ea5dcf0de36.PNG)
this is what happened

**Comment by zaintechsavvy** [comment]
Worked, Thanks!!
