### ISSUE TITLE
mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame

### ISSUE THREAD

**Issue by pot-noodle-python** [elebumm/RedditVideoMakerBot#601]
Every time I run `python main.py`, I get the error mentioned in the title. I have SoX v14.4.2 installed and the path added to my environment variables. There is also more output shown in the screenshot below:

![image](https://user-images.githubusercontent.com/73015259/174642334-0e27f446-b329-4293-b531-026acec23cfb.png)

The weird thing is, I managed to get the program to run once but when I tried again, It started giving me this error. Has anyone else had this issue and is there a way to fix it?

**Comment by bakharew** [comment]
Got same error

**Comment by JasonLovesDoggo** [comment]
Fixed in develop
