### ISSUE TITLE
Is there an option to increase the length of the video? 

### ISSUE THREAD

**Issue by orelmeister** [elebumm/RedditVideoMakerBot#603]
Is there an option to increase the length of the video?  like to make it a minimum 3 minutes or something like it

**Comment by IslaFTW** [comment]
same question here :(

**Comment by LukeZekes** [comment]
Looks like you're discussing the same feature as #573 
There is a VIDEO_LENGTH variable in video_creation/voices.py which looks like it determines the length of the video, but it isn't a hard cap since that could cut the video off mid-comment.

**Comment by rastogiujj12** [comment]
the variable mentioned in #573 is not the length of the video but the max length of each comment.
