### ISSUE TITLE
sox not found

### ISSUE THREAD

**Issue by Roelbelleman** [elebumm/RedditVideoMakerBot#604]
it doesn't find sox
![image](https://user-images.githubusercontent.com/107879263/174650377-60deb7f6-5a14-4b3a-8e2b-82e831cf8ab6.png)
but I do have it 
![image](https://user-images.githubusercontent.com/107879263/174650494-b07b96d0-8c95-4eb4-8fe8-4320a112466f.png)

**Comment by Nikicha316** [comment]
Thanks mate I will try this
