### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by o78** [elebumm/RedditVideoMakerBot#606]
Some errors may cause the user to not know what they did wrong. Example: 401 HTTP response error
not everyone knows what status codes mean and that its unauthorized, when they get hit with a wall of text they dont know what to do. and when im on it, please clear the console when outputting text into it, just makes it cleaner. This can be done with the os module for example, "os.system("cls")"

**Comment by ProjectSlxsh** [comment]
Or you could put the info in right the first time

**Comment by JasonLovesDoggo** [comment]
> Or you could put the info in right the first time 

Adding to this....

Half the time people don't read the simplest error messages anyway

**Comment by JasonLovesDoggo** [comment]
And another thing. cls only works on Windows

**Comment by o78** [comment]
> And another thing. cls only works on Windows

Theres a very simple solution to this, just do this instead: 
```
os.system("cls" if os.name == 'nt' else "clear")
```
