### ISSUE TITLE
main.py won't work

### ISSUE THREAD

**Issue by frightened-2011** [elebumm/RedditVideoMakerBot#607]
when i open main.py it says this:

`C:\Users\CENSORED\reddit\RedditVideoMakerBot>python main.py
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from video_creation.voices import save_text_to_mp3
  File "C:\Users\CENSORED\reddit\RedditVideoMakerBot\video_creation\voices.py", line 1
1, in <module>
    from TTS.swapper import TTS
  File "C:\Users\CENSORED\reddit\RedditVideoMakerBot\TTS\swapper.py", line 6, in <modu
le>
    from TTS.POLLY import POLLY
  File "C:\Users\CENSORED\reddit\RedditVideoMakerBot\TTS\POLLY.py", line 9, in <module
>
    from requests.exceptions import JSONDecodeError
ImportError: cannot import name 'JSONDecodeError' from 'requests.exceptions' (C:
\Users\CENSORED\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\exce
ptions.py)`

what do i do?

**Comment by Ahmedk-n** [comment]
same issue with me.

**Comment by frightened-2011** [comment]
do you have windows 7?

**Comment by frightened-2011** [comment]
oh, i did pip install --upgrade and it worked but now playwright wont work

the error is the following:

└─────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "main.py", line 70, in <module>
    main()
  File "main.py", line 49, in main
    download_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "C:\Users\pc\reddit\RedditVideoMakerBot\video_creation\screenshot_downloa
der.py", line 29, in download_screenshots_of_reddit_posts
    with sync_playwright() as p:
  File "C:\Users\pc\AppData\Local\Programs\Python\Python38\lib\site-packages\pla
ywright\sync_api\_context_manager.py", line 83, in __enter__
    playwright = self._playwright
AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'

Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection.run.<locals>.init() running a
t C:\Users\pc\AppData\Local\Programs\Python\Python38\lib\site-packages\playwrigh
t\_impl\_connection.py:197> wait_for=<Future pending cb=[<TaskWakeupMethWrapper
object at 0x000000000790AC10>()]> cb=[ProtocolCallback.__init__.<locals>.cb() at
 C:\Users\pc\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright
\_impl\_connection.py:130]>

before this message a popup popped up saying this:

Entry Point Not Found:
The procedure entry point GetHostNameW could not be located in the dynamic link library WS2_32.dll

**Comment by frightened-2011** [comment]
found the error, with windows seven the last version of node you can use is 13.sum.shit and playwright has his local version at 16.sum.shit, i exchanged the exe's and it's working like a charm.
