### ISSUE TITLE
mutagen.MutagenError: [Errno 2] No such file or directory: 'assets/temp/mp3/title.mp3'

### ISSUE THREAD

**Issue by ElectricIceBird** [elebumm/RedditVideoMakerBot#609]
![image](https://user-images.githubusercontent.com/67385565/174670959-d6894866-26ca-4cb7-ab13-38ee6f824eec.png)

**Comment by Aqua853** [comment]
Having the same issue too

**Comment by Laicus-py** [comment]
ever found a working solution? the one provided by ProjectSlxsh doesnt work made a whole github account just to solve this issue

**Comment by Aqua853** [comment]
> 

ProjectSlxshes one worked for me

**Comment by matichek** [comment]
> ever found a working solution? the one provided by ProjectSlxsh doesnt work made a whole github account just to solve this issue

I used TikTok as TTS provider - and that seems to work - StreamlabsPolly has an mp3 error. Strange.

**Comment by JasonLovesDoggo** [comment]
> > ever found a working solution? the one provided by ProjectSlxsh doesnt work made a whole github account just to solve this issue
> 
> I used TikTok as TTS provider - and that seems to work - StreamlabsPolly has an mp3 error. Strange. 

It is a rate limit and I just fixed it in develop
