### ISSUE TITLE
Closes when i open main.py

### ISSUE THREAD

**Issue by henry009k** [elebumm/RedditVideoMakerBot#610]
i saved as zip and when i double clicked it python opens then closes instantly, i have the newest python

**Comment by CordlessCoder** [comment]
saved what as zip? You need to follow the installation guide and run `python3 main.py` in a terminal/CMD

**Comment by henry009k** [comment]
> saved what as zip? You need to follow the installation guide and run `python3 main.py` in a terminal/CMD

how do i run it in terminal

**Comment by HallowedDust5** [comment]
You have to unzip the downloaded file, redirect into it, then shift+right click and run in terminal/command prompt/powershell. From there, follow the [docs](https://luka-hietala.gitbook.io/documentation-for-the-reddit-bot/) very closely, and it should run.
