### ISSUE TITLE
Sox Problem

### ISSUE THREAD

**Issue by Kirisaro** [elebumm/RedditVideoMakerBot#613]
Sox doesn't seem to be working properly, i've tried reinstalling in different paths with no avail, also went and created a system path for it and it still doesnt work, any ideas? 

![image](https://user-images.githubusercontent.com/24460756/174681501-4dd0e735-7856-44b4-a612-b8021fafc926.png)

**Comment by Nikicha316** [comment]
This should help you:

1. Open system environmental variables: (To open system environmental go to control panel -> system and security -> System -> Advanced system settings)
![image](https://user-images.githubusercontent.com/49568616/174738652-72127018-2c94-4398-ad2c-5bd26da7218e.png)

2.  A new window should open and at the bottom you will see a table with a header "System Variables". In the table, select "PATH" and click edit.
![image](https://user-images.githubusercontent.com/49568616/174739167-9e670093-8d2c-483d-9c74-390ad18b02f5.png)

3. A new window should open up. Select "Browse" and select your Sox folder ( Located in x86 by default).

4. Than press "ok" and everything should be fine

**Comment by Nikicha316** [comment]
I've made a video for you on how I install it. 
https://www.youtube.com/watch?v=T0ztYcPnMsY
