### ISSUE TITLE
Final Video Editing

### ISSUE THREAD

**Issue by Crisez0694** [elebumm/RedditVideoMakerBot#614]
Kind of new to coding so i may just be wrong but in the final video i find it odd when the TTS goes straight into the next comment with no pause, not sure if im missing something but not really sure where i can edit that, also not sure how to edit the transition between comments, like a fade away/fade in, if anyone can help or if it could be implemented that'd be great.

**Comment by William9923** [comment]
#663 i think this issue is similar.

**Comment by William9923** [comment]
#773
