### ISSUE TITLE
File Not Found Error Help

### ISSUE THREAD

**Issue by flyingrabbits** [elebumm/RedditVideoMakerBot#615]
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/ffmpeg'
name@name-computer RedditVideoMakerBot-master % 

I had a friend come set up the code for me, I am completely clueless about coding, I got this error when everything was supposedly "done". Been stuck here and totally confused as to what to do, any help would be greatly appreciated.

**Comment by flyingrabbits** [comment]
Once i paste sudo apt install ffmpeg it then prompts me to enter password, however when I type or try to paste nothing is entered. Only can input CTRL C & Enter.

**Comment by HallowedDust5** [comment]
When copying and pasting into a terminal you have to either right click and paste or ctrl+shift+v to paste.
