### ISSUE TITLE
won't start

### ISSUE THREAD

**Issue by frightened-2011** [elebumm/RedditVideoMakerBot#618]
i am trying to start main.py, all dependences are installed, the only thing i did is to downgrade playwright's node.js version to 13.something because of windows shit

Launching Headless Browser...
WARNING: running on unsupported windows version!
Host system is missing dependencies!

Full list of missing libraries:
    api-ms-win-core-winrt-error-l1-1-0.dll

the dll is in my system32 folder,idk why it isnt working

**Comment by CJthisis** [comment]
are you running on windows 7? I think that isnt supported

**Comment by frightened-2011** [comment]
shutup g-a
