### ISSUE TITLE
prawcore.exceptions.OAuthException: invalid_grant error processing request

### ISSUE THREAD

**Issue by Furilo19** [elebumm/RedditVideoMakerBot#62]
Just got the Error 
prawcore.exceptions.OAuthException: invalid_grant error processing request
after running main.py... Error was after   "Getting AskReddit threads..."  btw. I installed everything and filled out the .env
Does anyone know how to fix that issue?

**Comment by lesterrar** [comment]
check your credentials in .env file you probably did something wrong there

**Comment by FreebieII** [comment]
Hi @Furilo19 

I hope you were able to resolve your issue, I will be closing this for the time being.  Feel free to re-open the issue if it has not been solved!

Happy Coding!
