### ISSUE TITLE
Playwright install-deps won't work in manjaro/ arch linux based distributions

### ISSUE THREAD

**Issue by Anvilator-web** [elebumm/RedditVideoMakerBot#623]
[dex@manjaropc]$ RedditVideoMakerBot]$ playwright install-deps
BEWARE: your OS is not officially supported by Playwright; installing dependencies for Ubuntu as a fallback.
Installing dependencies...
Switching to root user to install dependencies...
[sudo] password for dex: 
sh: line 1: apt-get: command not found
Failed to install browser dependencies
Error: Installation process exited with code: 127

**Comment by William9923** [comment]
Based on playwright documentation, it only support Ubuntu distro on linux.
