### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './video_creation/data/videos.json'

### ISSUE THREAD

**Issue by Jekxd** [elebumm/RedditVideoMakerBot#624]
I tried searching for a solution for this but I just cant seem to fix it. Please help

**Comment by shr1gma** [comment]
howd you fix it? im having the same issue

**Comment by carlos837** [comment]
same

**Comment by Jekxd** [comment]
i edited the code itself. i changed the forward slashes to backward slashes
