### ISSUE TITLE
SoX

### ISSUE THREAD

**Issue by Gecko8030** [elebumm/RedditVideoMakerBot#627]
<img width="758" alt="Screen Shot 2022-06-21 at 4 27 52 AM" src="https://user-images.githubusercontent.com/107918142/174766597-30049182-c6ac-48f0-b7c5-262f340f00b6.png">
i do have sox (BTW i am on mac)

**Comment by Gecko8030** [comment]
<img width="561" alt="Screen Shot 2022-06-21 at 4 41 20 AM" src="https://user-images.githubusercontent.com/107918142/174769569-57685a13-6c95-494b-9619-db699ed4aaa5.png">

**Comment by Gecko8030** [comment]
> when did you try this if before 2 pm try again

i just tried it

**Comment by sarimwaniR** [comment]
https://luka-hietala.gitbook.io/documentation-for-the-reddit-bot/downloading-the-bot

**Comment by sarimwaniR** [comment]
for win,mac& linux

**Comment by Gecko8030** [comment]
> for win,mac& linux
<img width="565" alt="Screen Shot 2022-06-21 at 4 55 37 AM" src="https://user-images.githubusercontent.com/107918142/174772425-61500e0e-1747-4d4b-91b9-560d1bcec543.png">
how to fix this?
