### ISSUE TITLE
Set video title lenght in .env file

### ISSUE THREAD

**Issue by CJthisis** [elebumm/RedditVideoMakerBot#628]
The variable 'get_video_title' in final_video.py (in the video creation folder) could fetch the title lenght for the final video from the .env file.

**Comment by Cizzl** [comment]
What is the purpose?

**Comment by CJthisis** [comment]
> What is the purpose?

It would make it easier for not-so tech-savvy people to change the video length. The option to change video length is also relatively unknown but a variable in the .env file could change this for the better.

Also, there are many issues asking how to change the video length. If it were easily accessible, these unnecessary issues would no longer be opened.

**Comment by Cizzl** [comment]
Oh you mean video length, I misunderstood. I think there is already something in progress in develop
