### ISSUE TITLE
Could not find a version that satisfies the requirement dontenv

### ISSUE THREAD

**Issue by Shadowles19** [elebumm/RedditVideoMakerBot#63]
<img width="1097" alt="Screen Shot 2022-06-01 at 9 52 04 AM" src="https://user-images.githubusercontent.com/106671929/171421333-6cafc206-ee11-40c5-bd9e-66917a8f8c08.png">
<img width="1079" alt="Screen Shot 2022-06-01 at 9 52 21 AM" src="https://user-images.githubusercontent.com/106671929/171421438-6e26b74f-8748-4566-9590-81f4068a48f6.png">

**Comment by Shadowles19** [comment]
Fixed

**Comment by JuanseMastrangelo** [comment]
The version to use is Python 3.8.0
