### ISSUE TITLE
setup.py creates unusable .env file

### ISSUE THREAD

**Issue by CJthisis** [elebumm/RedditVideoMakerBot#630]
When setting up the bot for the first time with setup.py, it asks for various details to set up the bot. These details are then saved in a new .env file, which is missing lots of variables from the normal .env.template file included in the download of the bot. Because of all the missing variables, the bot will crash every time it is started. 

I would simply advise to delete or disable setup.py until this issue is fixed.

**Comment by CJthisis** [comment]
![example](https://user-images.githubusercontent.com/99442347/174784172-c364727c-5d7f-49b1-969b-a6d2ff8287a7.png)

On the right is the normal .env file, on the left is the .env file created by setup.py

**Comment by vitviki** [comment]
Did you rename '.env.template' to '.env'? 

The system is trying to access '.env' file but is unable to find it, so it's creating a new one.

**Comment by CJthisis** [comment]
> Did you rename '.env.template' to '.env'? 
> 
> 
> 
> The system is trying to access '.env' file but is unable to find it, so it's creating a new one.

To clarify a little bit: I don't have a problem with the bot. I simply was curious about the automated install feature, so I tried it out on a different PC. The setup process went smoothly, there were no errors or something. But the program creates a new .env file, which is recognized by main.py, but it still doesn't work because there are so many things missing.

**Comment by vitviki** [comment]
Aah ok. Got it. I haven't used the setup feature yet, so misunderstood.

Will give it a shot once, then we can try and solve the problem together.

**Comment by JasonLovesDoggo** [comment]
Update to develop
