### ISSUE TITLE
Could this variable be added? 

### ISSUE THREAD

**Issue by ghost** [elebumm/RedditVideoMakerBot#638]
**Is your feature request related to a problem? Please describe.**
This variable that I propose (Comments) is very important since sometimes a single answer can be a very long text and practically a video is generated with only 2 answers and that is very little / short

**Describe the solution you'd like**
Make a variable "coments"

**Additional context** (optional)
Comments = The amount of comments that we would like a video to last.

This variable that I propose (Comments) is very important since sometimes a single answer can be a very long text and practically a video is generated with only 2 answers and that is very little / short

**Comment by William9923** [comment]
Hi, i think this is possible. As long as the video is not limited with default 50 s, i think these is very possible with minimal change on the code. Will label this as a good first issue

**Comment by yahyaahs** [comment]
i would like to work on this feature if no one is already done some work on it ? let me know

**Comment by MahiRavanKRG** [comment]
> **Is your feature request related to a problem? Please describe.** This variable that I propose (Comments) is very important since sometimes a single answer can be a very long text and practically a video is generated with only 2 answers and that is very little / short
> 
> **Describe the solution you'd like** Make a variable "coments"
> 
> **Additional context** (optional) Comments = The amount of comments that we would like a video to last.
> 
> This variable that I propose (Comments) is very important since sometimes a single answer can be a very long text and practically a video is generated with only 2 answers and that is very little / short

I understand some of it,

I am a new contributor. We can start that but could you first tell me more about this variable? I think this is not a simple change but a feature in itself.
