### ISSUE TITLE
Im stuck on: ModuleNotFoundError: No module named 'reddit.subreddit'

### ISSUE THREAD

**Issue by ItsYoBoi69Master** [elebumm/RedditVideoMakerBot#639]
I installed a whole lot of modules manually but now Im stuck on:
ModuleNotFoundError: No module named 'reddit.subreddit'

_Originally posted by @ItsYoBoi69Master in https://github.com/elebumm/RedditVideoMakerBot/issues/589#issuecomment-1161730669_

**Comment by HallowedDust5** [comment]
What do you mean by installed them manually? Normally, you use pip to install modules for python. Try to install what you manually installed with pip.

**Comment by JasonLovesDoggo** [comment]
Fixed
