### ISSUE TITLE
rename .env.template

### ISSUE THREAD

**Issue by freynes** [elebumm/RedditVideoMakerBot#64]
Hi guys, 

I am not very familiar with Python, so I cloned the repo to my computer but then didn't find .env.template file. I downloaded it directly and changed it to env.txt and added my reddit api keys. I then tried to rename env.txt to .env but mac says that .env are name reserved system. Any help please?

Thanks.

**Comment by Shadowles19** [comment]
Hey I had the same issue today with that, when in finder click cmd + shift + . and the hidden files should appear.

**Comment by JasonLovesDoggo** [comment]
uhh well that's more of a mac problem that a code problem, but try renaming the file not in the browser (e.g. in an IDE or notepad)

**Comment by EdyDeveloper** [comment]
If anyone has this issue on Ubuntu and is wondering how to do it you can rename the file like this:
1. Open the directory in the terminal
2. Do `mv .env.template .env`
3. You can edit it with `sudo nano .env`

**Comment by FreebieII** [comment]
Hi @freynes,

I hope you were able to resolve your issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
