### ISSUE TITLE
A tutorial

### ISSUE THREAD

**Issue by Nikicha316** [elebumm/RedditVideoMakerBot#641]
**Is your feature request related to a problem? Please describe.**
A some people don't know how to install the bot or how to set variables for SoX etc.

**Describe the solution you'd like**
I've made a short video (tutorial) on how to install the bot (if you like it you can use it).
- https://www.youtube.com/watch?v=T0ztYcPnMsY

**Comment by HallowedDust5** [comment]
There's also the [docs](https://luka-hietala.gitbook.io/documentation-for-the-reddit-bot/) that demonstrate how to use the bot.

**Comment by Nikicha316** [comment]
> There's also the [docs](https://luka-hietala.gitbook.io/documentation-for-the-reddit-bot/) that demonstrate how to use the bot.

Btw I didn't even know that this existed.  But yeah thanks

**Comment by JasonLovesDoggo** [comment]
This is great I'm going to close the issue cuz it's not really needed to be an issue but I'm going to post this in the discord
