### ISSUE TITLE
"No module named praw" but praw is already installed

### ISSUE THREAD

**Issue by xaevlc** [elebumm/RedditVideoMakerBot#642]
when i run "pip install -r requirements.txt", it says requirements already satisfied. Help would be appreciated, tysm.

**Comment by xaevlc** [comment]
Here is a terminal output:

```
PS C:\Users\Admin\Desktop\RedditVideoMakerBot-master> pip install -r requirements.txt
Requirement already satisfied: gTTS==2.2.4 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r 
requirements.txt (line 1)) (2.2.4)
Requirement already satisfied: moviepy==1.0.3 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from 
-r requirements.txt (line 2)) (1.0.3)
Requirement already satisfied: mutagen==1.45.1 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 3)) (1.45.1)
Requirement already satisfied: playwright==1.22.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 4)) (1.22.0)
Requirement already satisfied: praw==7.6.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r 
requirements.txt (line 5)) (7.6.0)
Requirement already satisfied: python-dotenv==0.20.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 6)) (0.20.0)
Requirement already satisfied: pytube==12.1.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from 
-r requirements.txt (line 7)) (12.1.0)
Requirement already satisfied: requests==2.28.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 8)) (2.28.0)
Requirement already satisfied: rich==12.4.4 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 9)) (12.4.4)
Requirement already satisfied: sox==1.4.1 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 10)) (1.4.1)
Requirement already satisfied: six in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from gTTS==2.2.4->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: click in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from gTTS==2.2.4->-r requirements.txt (line 1)) (8.1.3)
Requirement already satisfied: decorator<5.0,>=4.0.2 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from moviepy==1.0.3->-r requirements.txt (line 2)) (4.4.2)
Requirement already satisfied: tqdm<5.0,>=4.11.2 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from moviepy==1.0.3->-r requirements.txt (line 2)) (4.64.0)
Requirement already satisfied: proglog<=1.0.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from 
moviepy==1.0.3->-r requirements.txt (line 2)) (0.1.10)
Requirement already satisfied: numpy>=1.17.3 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from moviepy==1.0.3->-r requirements.txt (line 2)) (1.22.4)
Requirement already satisfied: imageio<3.0,>=2.5 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from moviepy==1.0.3->-r requirements.txt (line 2)) (2.19.3)
Requirement already satisfied: imageio_ffmpeg>=0.2.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from moviepy==1.0.3->-r requirements.txt (line 2)) (0.4.7)
Requirement already satisfied: pyee==8.1.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from playwright==1.22.0->-r requirements.txt (line 4)) (8.1.0)
Requirement already satisfied: websockets==10.1 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from playwright==1.22.0->-r requirements.txt (line 4)) (10.1)
Requirement already satisfied: greenlet==1.1.2 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from playwright==1.22.0->-r requirements.txt (line 4)) (1.1.2)
Requirement already satisfied: update-checker>=0.18 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages 
(from praw==7.6.0->-r requirements.txt (line 5)) (0.18.0)
Requirement already satisfied: prawcore<3,>=2.1 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from praw==7.6.0->-r requirements.txt (line 5)) (2.3.0)
Requirement already satisfied: websocket-client>=0.54.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from praw==7.6.0->-r requirements.txt (line 5)) (1.3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests==2.28.0->-r requirements.txt (line 8)) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests==2.28.0->-r requirements.txt (line 8)) (2020.11.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests==2.28.0->-r requirements.txt (line 8)) (1.26.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests==2.28.0->-r requirements.txt (line 8)) (2.10)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in c:\users\admin\appdata\local\packagesages (from rich==12.4.4->-r requirements.txt (line 9)) (0.9.1)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from rich==12.4.4->-r requirements.txt (line 9)) (2.12.0)
Requirement already satisfied: pillow>=8.3.2 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from imageio<3.0,>=2.5->moviepy==1.0.3->-r requirements.txt (line 2)) (9.1.1)
Requirement already satisfied: colorama in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tqdm<5.0,>=4.11.2->moviepy==1.0.3->-r requirements.txt (line 2)) (0.4.5)
PS C:\Users\Admin\Desktop\RedditVideoMakerBot-master> py main.py
>>
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\RedditVideoMakerBot-master\main.py", line 6, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "C:\Users\Admin\Desktop\RedditVideoMakerBot-master\reddit\subreddit.py", line 4, in <module>
    import praw
ModuleNotFoundError: No module named 'praw'
PS C:\Users\Admin\Desktop\RedditVideoMakerBot-master>
```

**Comment by xaevlc** [comment]
> Have you tried doing this:
> 
> pip install praw

yep but it outputs the given text as explained in the first quote:

`
PS C:\Users\Admin\Desktop\RedditVideoMakerBot-master> pip install -r requirements.txt
Requirement already satisfied: gTTS==2.2.4 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r 
requirements.txt (line 1)) (2.2.4)
Requirement already satisfied: moviepy==1.0.3 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from 
-r requirements.txt (line 2)) (1.0.3)
Requirement already satisfied: mutagen==1.45.1 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 3)) (1.45.1)
Requirement already satisfied: playwright==1.22.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 4)) (1.22.0)
Requirement already satisfied: praw==7.6.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r 
requirements.txt (line 5)) (7.6.0)
Requirement already satisfied: python-dotenv==0.20.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 6)) (0.20.0)
Requirement already satisfied: pytube==12.1.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from 
-r requirements.txt (line 7)) (12.1.0)
Requirement already satisfied: requests==2.28.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 8)) (2.28.0)
Requirement already satisfied: rich==12.4.4 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 9)) (12.4.4)
Requirement already satisfied: sox==1.4.1 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 10)) (1.4.1)
Requirement already satisfied: six in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from gTTS==2.2.4->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: click in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from gTTS==2.2.4->-r requirements.txt (line 1)) (8.1.3)
Requirement already satisfied: decorator<5.0,>=4.0.2 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from moviepy==1.0.3->-r requirements.txt (line 2)) (4.4.2)
Requirement already satisfied: tqdm<5.0,>=4.11.2 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from moviepy==1.0.3->-r requirements.txt (line 2)) (4.64.0)
Requirement already satisfied: proglog<=1.0.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from 
moviepy==1.0.3->-r requirements.txt (line 2)) (0.1.10)
Requirement already satisfied: numpy>=1.17.3 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from moviepy==1.0.3->-r requirements.txt (line 2)) (1.22.4)
Requirement already satisfied: imageio<3.0,>=2.5 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from moviepy==1.0.3->-r requirements.txt (line 2)) (2.19.3)
Requirement already satisfied: imageio_ffmpeg>=0.2.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from moviepy==1.0.3->-r requirements.txt (line 2)) (0.4.7)
Requirement already satisfied: pyee==8.1.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from playwright==1.22.0->-r requirements.txt (line 4)) (8.1.0)
Requirement already satisfied: websockets==10.1 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from playwright==1.22.0->-r requirements.txt (line 4)) (10.1)
Requirement already satisfied: greenlet==1.1.2 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from playwright==1.22.0->-r requirements.txt (line 4)) (1.1.2)
Requirement already satisfied: update-checker>=0.18 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages 
(from praw==7.6.0->-r requirements.txt (line 5)) (0.18.0)
Requirement already satisfied: prawcore<3,>=2.1 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from praw==7.6.0->-r requirements.txt (line 5)) (2.3.0)
Requirement already satisfied: websocket-client>=0.54.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from praw==7.6.0->-r requirements.txt (line 5)) (1.3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests==2.28.0->-r requirements.txt (line 8)) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests==2.28.0->-r requirements.txt (line 8)) (2020.11.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests==2.28.0->-r requirements.txt (line 8)) (1.26.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests==2.28.0->-r requirements.txt (line 8)) (2.10)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in c:\users\admin\appdata\local\packagesages (from rich==12.4.4->-r requirements.txt (line 9)) (0.9.1)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from rich==12.4.4->-r requirements.txt (line 9)) (2.12.0)
Requirement already satisfied: pillow>=8.3.2 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from imageio<3.0,>=2.5->moviepy==1.0.3->-r requirements.txt (line 2)) (9.1.1)
Requirement already satisfied: colorama in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tqdm<5.0,>=4.11.2->moviepy==1.0.3->-r requirements.txt (line 2)) (0.4.5)
PS C:\Users\Admin\Desktop\RedditVideoMakerBot-master> py main.py
>>
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\RedditVideoMakerBot-master\main.py", line 6, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "C:\Users\Admin\Desktop\RedditVideoMakerBot-master\reddit\subreddit.py", line 4, in <module>
    import praw
ModuleNotFoundError: No module named 'praw'
PS C:\Users\Admin\Desktop\RedditVideoMakerBot-master>
`

**Comment by xaevlc** [comment]
any help would be appreciated

**Comment by PrestoSole** [comment]
Try typing `pip3 install -r requirements.text` into the terminal, and let me know what you get!

**Comment by vitviki** [comment]
I got the same error message yesterday. Try `python3.8 -m pip install -r requirements.txt `

**Comment by JasonLovesDoggo** [comment]
Closed for inactivity

**Comment by N0THSA** [comment]
for anyone lurking here, 

> I got the same error message yesterday. Try `python3.8 -m pip install -r requirements.txt `

this is the correct answer. thanks man :)
