### ISSUE TITLE
Main.py Keeps closing

### ISSUE THREAD

**Issue by Questionize** [elebumm/RedditVideoMakerBot#646]
Whenever I open main.py it automatically closes even when it does open the moment I type anything it closes do you know what I could do to fix this? 

All I do is just open main.py

I expected it to open normally but it just keeps closing

The system I'm on is windows 10

**Comment by HallowedDust5** [comment]
Are you running it in a terminal or just clicking on the main.py file?

If you have it open in a terminal, you can send the error here and I can try and help you with it. Follow along with the documentation [here](https://luka-hietala.gitbook.io/documentation-for-the-reddit-bot/).

**Comment by Questionize** [comment]
I am just clicking the main.py file

**Comment by vitviki** [comment]
Try running the file through terminal/command prompt. If there are any errors, it'll pop up there.

**Comment by joppari** [comment]
Had the same problem . The trace back says :
"Traceback (most recent call last):
  File "C:\Users\joppa\Downloads\RedditVideoMakerBot-master\main.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
"

**Comment by vitviki** [comment]
If you open requirements.txt you'll see that dotenv do gets installed with all other dependencies.

Run this command

`pip install -r requirements.txt`

If this doesn't fix it then just install dotevn

`pip install python-dotenv`

**Comment by joppari** [comment]
Thank you very much. It solved my problem
