### ISSUE TITLE
Crashes during Saving text to mp3

### ISSUE THREAD

**Issue by henry009k** [elebumm/RedditVideoMakerBot#647]
it worked fine, i made 5 videos then this happened
![Screenshot 2022-06-21 220121](https://user-images.githubusercontent.com/77591045/174927592-23b9786a-1218-43dd-9500-f198c83974b1.png)

**Comment by Sanyam-Ahuja** [comment]
How many videos have you made

**Comment by Sanyam-Ahuja** [comment]
I also had the same issue did some tweaking in the code and got it to run

**Comment by henry009k** [comment]
Update: Turn your pc off and back on again

**Comment by henry009k** [comment]
Update: Restart PC and it should work

**Comment by LukeMedeiros916** [comment]
> Update: Restart PC and it should work

So all you have to do to fix this error is Restart your PC?

**Comment by henry009k** [comment]
Yes

**Comment by William9923** [comment]
Because it been solved, i will close this issue 🙏 . Feel free to open this issue if anybody had similar issue like this one.
