### ISSUE TITLE
issue after running main

### ISSUE THREAD

**Issue by Aprars** [elebumm/RedditVideoMakerBot#65]
hello, 

I would be thankful if someone could help me figure out the following error
```

line 258, in __init__
    raise MissingRequiredAttributeException(
praw.exceptions.MissingRequiredAttributeException: Required configuration setting 'client_id' missing.
This setting can be provided in a praw.ini file, as a keyword argument to the `Reddit` class constructor, or as an environment variable.
```

I keep getting this error even though I filled up .env with the required information
I apologize if this is an easy fix I am still learning

**Comment by AmrouHab** [comment]
can you show your .env file ? be sure to remove secret key before posting

**Comment by AlenSudec** [comment]
name of the file should be just .env

**Comment by Aprars** [comment]
> name of the file should be just .env

thank you so much alen! it solved my issue
