### ISSUE TITLE
praw.exceptions.MissingRequiredAttributeException: Required configuration setting 'client_id' missing.

### ISSUE THREAD

**Issue by obvCirmaci** [elebumm/RedditVideoMakerBot#652]
so whenever i try to run the command `python main.py` i get this error

```
Logging into Reddit.
Traceback (most recent call last):
  File "C:\Users\Cirmaci\Desktop\reddit\main.py", line 71, in <module>
    main()
  File "C:\Users\Cirmaci\Desktop\reddit\main.py", line 48, in main
    reddit_object = get_obj()
  File "C:\Users\Cirmaci\Desktop\reddit\main.py", line 45, in get_obj
    reddit_obj = get_subreddit_threads()
  File "C:\Users\Cirmaci\Desktop\reddit\reddit\subreddit.py", line 41, in get_subreddit_threads
    reddit = praw.Reddit(
  File "C:\Users\Cirmaci\AppData\Local\Programs\Python\Python39\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\Cirmaci\AppData\Local\Programs\Python\Python39\lib\site-packages\praw\reddit.py", line 258, in __init__
    raise MissingRequiredAttributeException(
praw.exceptions.MissingRequiredAttributeException: Required configuration setting 'client_id' missing.
This setting can be provided in a praw.ini file, as a keyword argument to the `Reddit` class constructor, or as an environment variable.
```

and whenever i try to run the command `python3 main.py` i get this error:

```
Traceback (most recent call last):
  File "C:\Users\Cirmaci\Desktop\reddit\main.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
```

and im preety sure i have all the requirements installed, any help i can get?

**Comment by stefpetrini** [comment]
same for me

**Comment by aLtRD** [comment]
From the looks of the first error, you either did not provide and Reddit client ID in the .env file, or the ID you provided is incorrect.
For the second error, you need to install python-dotenv. You can do this by typing `pip3 install python-dotenv` into your command prompt or terminal.

**Comment by PrestoSole** [comment]
Adding on @aLtRD's explanation, you also need to make sure to rename `.env.template` to `.env`. For the Reddit client ID part, you can follow the step-by-step [documentation](https://luka-hietala.gitbook.io/documentation-for-the-reddit-bot/) on how to use the bot, that should clear up most issues.

**Comment by chillingcone426** [comment]
I have tried all steps and followed the guide but it does not work

**Comment by chillingcone426** [comment]
I get:
Traceback (most recent call last):
  File "C:\Users\Owner\Downloads\RedditVideoMakerBot-master\main.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by reneeqytan** [comment]
> I get: Traceback (most recent call last): File "C:\Users\Owner\Downloads\RedditVideoMakerBot-master\main.py", line 5, in from dotenv import load_dotenv ModuleNotFoundError: No module named 'dotenv'
@chillingcone426 

Read - there's no module called 'dotenv', so simply install the module! Run `pip install python-dotenv`, or `pip3 install python-dotenv`, depending on your system.

**Comment by chillingcone426** [comment]
> > I get: Traceback (most recent call last): File "C:\Users\Owner\Downloads\RedditVideoMakerBot-master\main.py", line 5, in from dotenv import load_dotenv ModuleNotFoundError: No module named 'dotenv'
> > @chillingcone426
> 
> Read - there's no module called 'dotenv', so simply install the module! Run `pip install python-dotenv`, or `pip3 install python-dotenv`, depending on your system.

I have tried this before and I tried again but it is not the fix
