### ISSUE TITLE
Add a content filter that changes words like kill or other TOS unfriendly words to tos friendly words

### ISSUE THREAD

**Issue by BoomSec** [elebumm/RedditVideoMakerBot#654]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered** (optional)

**Additional context** (optional)

**Comment by sadmoonphoenix** [comment]
Duplicate of https://github.com/elebumm/RedditVideoMakerBot/issues/407. Also fixed by pending PR, https://github.com/elebumm/RedditVideoMakerBot/pull/447. Please close this issue.
