### ISSUE TITLE
Feature: Ignore pinned posts in subreddits.

### ISSUE THREAD

**Issue by aLtRD** [elebumm/RedditVideoMakerBot#656]
**Issue**
This isn't necessarily an issue, but some subreddits have monthly threads that are pinned to the top of subreddits and the bot can pick them up.

**Solution**
You could maybe add an environment variable to skip over pinned posts.

**Secondary Solution (Errors are possible with this solution)**
You could also possibly check the subreddit title for certain keywords like monthly, or thread and then ignore them if they are found. I can see some issues popping up with this solution though. Maybe a post's title includes "Monthly Paycheck" or "Monthly Budget".

**Screenshot**
![cmd_XESr0Qsuiw](https://user-images.githubusercontent.com/60201781/175067071-4b5a207d-8abb-4d5b-8806-47cd730da18b.png)

Thanks.

**Comment by sadmoonphoenix** [comment]
I've opened up a pull request, and the maintainers might accept it into the develop branch. https://github.com/elebumm/RedditVideoMakerBot/pull/657
