### ISSUE TITLE
Accidentally messed up the code

### ISSUE THREAD

**Issue by vxibrahim** [elebumm/RedditVideoMakerBot#658]
I was going through the files looking for the background one, but I guess I messed up something while opening and looking at the code of various .py files. Can someone help me fix this? When I enter "python3 main.py" it says this:

```
Traceback (most recent call last):
  File "/home/pc/Documents/RedditVideoMakerBot/main.py", line 13, in <module>
    from video_creation.voices import save_text_to_mp3
  File "/home/pc/Documents/RedditVideoMakerBot/video_creation/voices.py", line 11, in <module>
    from TTS.swapper import TTS
  File "/home/pc/Documents/RedditVideoMakerBot/TTS/swapper.py", line 6, in <module>
    from TTS.POLLY import POLLY
  File "/home/pc/Documents/RedditVideoMakerBot/TTS/POLLY.py", line 9, in <module>
    from requests.exceptions import JSONDecodeError
ImportError: cannot import name 'JSONDecodeError' from 'requests.exceptions' (/home/pc/.local/lib/python3.10/site-packages/requests/exceptions.py)
```

EDIT: issue is not from me modifying the code, did a fresh install and got the same error!

**Comment by Sourlol** [comment]
Just redownload the file. Is there a reason that you can't do that?

**Comment by vxibrahim** [comment]
> > > 
> > 
> > 
> > I don't know what file I messed up. I'm new to all this github stuff. What file do I redownload?
> 
> Redownload everything from GitHub.

Deleted everything and did a fresh install. Got the SAME exact error. So I believe the issue is not from me modifying my code its something else. Please take a second to look at the error in the first post. 

This is the main error from what I can see:
`ImportError: cannot import name 'JSONDecodeError' from 'requests.exceptions'`

How do I fix this?

**Comment by PrestoSole** [comment]
Try typing `pip3 install -r requirements.text` into the terminal INSIDE the repository's folder, and let me know what you get!

**Comment by vxibrahim** [comment]
> Try typing `pip3 install -r requirements.text` into the terminal INSIDE the repository's folder, and let me know what you get!

It worked!! Still not sure why it happened randomly before even tho it was working perfectly. But yes thank you!
