### ISSUE TITLE
Is it possible that you can pause between one answer and another? The answers are read quickly in a row.

### ISSUE THREAD

**Issue by ghost** [elebumm/RedditVideoMakerBot#663]
**Is your feature request related to a problem? Please describe.**
its not a problem at all

**Describe the solution you'd like**
create a variable where you can indicate the time in seconds that should be done between each response that is read

**Additional context** (optional)
Is it possible that you can pause between one answer and another? The answers are read quickly in a row.

I would like to add a pause of 1 or maybe 2 seconds between each response that is read

**Comment by Trimolo** [comment]
https://github.com/elebumm/RedditVideoMakerBot/issues/664#issue-1281576901

**Comment by Trimolo** [comment]
even slow pause on the first read is great idea, since the first read is the question, then 1 to 2 sec pause and the narrator can read the answers in the same base if wanted. but that first small pause after the question is read would be great enhancement.

**Comment by GradleUser** [comment]
This is something I could use a lot
