### ISSUE TITLE
the last develp version, it limits the video to 60 seconds

### ISSUE THREAD

**Issue by IslaFTW** [elebumm/RedditVideoMakerBot#666]
the last develp version, it limits the video to 60 seconds, it doesn't matter if you put 300 seconds, it still generates a video of only 60 seconds

**Comment by zzraawashere** [comment]
How do you even change the length?

**Comment by zzraawashere** [comment]
How do you even change the length?

**Comment by IslaFTW** [comment]
> How do you even change the length?

In this file:
https://github.com/elebumm/RedditVideoMakerBot/blob/develop/video_creation/voices.py

in row 25
