### ISSUE TITLE
im getting an error (WinError 2) and 'The install of sOx cannot process mp3 file'

### ISSUE THREAD

**Issue by DarkDravenPOG** [elebumm/RedditVideoMakerBot#667]
both of the error come at the same time when i run the command 'python main.py'
everything is installed as i already made a video but today morning when i woke up and tried to make another one of em it didnt let me the env file is correct as it already worked once
I will link the screenshot of the termina
![Capture](https://user-images.githubusercontent.com/99127967/175241394-5fbdfd70-dac8-4063-99d9-110dab1654a9.PNG)
![whyareyourunning](https://user-images.githubusercontent.com/99127967/175241228-7e9e2ca1-9329-4677-9976-530910f8c5f4.png)
![opbruh](https://user-images.githubusercontent.com/99127967/175241256-a921dede-1231-449f-89b7-65c6c369286c.png)
41167-966fe4aa-2b97-4d37-ae10-189aaf73c6e0.PNG)

**Comment by CJthisis** [comment]
When you start the bot up for the first time, does it say that it can't find SoX? If so, that is causing the error "Sox cant process Mp3 file". The solution to that is here: https://github.com/elebumm/RedditVideoMakerBot/issues/621
(And after you've done everything in the linked thread, move the Sox directory all the way to the top of the list of directories)
Hope that helps!

**Comment by DarkDravenPOG** [comment]
it did not say that

**Comment by JasonLovesDoggo** [comment]
fixed in develop
