### ISSUE TITLE
Different Voice

### ISSUE THREAD

**Issue by AutumnJaguar16** [elebumm/RedditVideoMakerBot#673]
The threa with me and LewisMENELAWS
LewisMenelaws — Today at 2:50 PM
1) You go in your .env file and change the VOICE to something differnet. Does any of the @Reddit Bot Team know if there is a list?
AutumnJaguar16 — Today at 2:59 PM
@LewisMenelaws  I changed the voice to tiktok and this was the error message
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ on the 1st iteration of 5                                                                                           │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Logging into Reddit.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Getting subreddit threads...                                                                                        │
Expand
message.txt
7 KB
@LewisMenelaws  there is a screen shot
Image
LewisMenelaws — Today at 3:05 PM
I am seeing that the text is too long. Using Polly might not be the best idea at the moment
AutumnJaguar16 — Today at 3:06 PM
So what do i do
?
LewisMenelaws — Today at 3:06 PM
I would switch to another TTS engine for the time being
AutumnJaguar16 — Today at 3:06 PM
like what
LewisMenelaws — Today at 3:08 PM
Try TikTok
AutumnJaguar16 — Today at 3:08 PM
I did
LewisMenelaws — Today at 3:08 PM
maybe GTTS
AutumnJaguar16 — Today at 3:08 PM
Image
LewisMenelaws — Today at 3:09 PM
I see that it's defaulting to polly at the top
AutumnJaguar16 — Today at 3:09 PM
cause i had a mistake
Image
there
I tried GTTS and it is working so far
Do you know of any clean askreddits
?
![unknown](https://user-images.githubusercontent.com/95594397/175379709-a753297f-6ab8-4524-b6a0-c207d25bfd79.png)

LewisMenelaws — Today at 3:11 PM
This might be a bug so report it if you can on GitHub 🙂

and not 100% no
![image](https://user-images.githubusercontent.com/95594397/175379746-16544f61-3698-453a-9a7c-a8cb10c36166.png)
![image](https://user-images.githubusercontent.com/95594397/175379776-0ffda00f-6052-4571-9d9e-7c607389706f.png)

![image](https://user-images.githubusercontent.com/95594397/175379792-9d86a3bb-d166-4535-87b4-b8e7dc63130d.png)

**Comment by JasonLovesDoggo** [comment]
Fixed
