### ISSUE TITLE
main.py doesn't run

### ISSUE THREAD

**Issue by KodiShaphasa** [elebumm/RedditVideoMakerBot#675]
I completed all the steps in the instructions and this error shows up when i run main.py

PS C:\Users\kodis\Desktop\RedditVideoMakerBot-master> & C:/Users/kodis/AppData/Local/Microsoft/WindowsApps/python3.9.exe c:/Users/kodis/Desktop/RedditVideoMakerBot-master/main.py
Traceback (most recent call last):
  File "c:\Users\kodis\Desktop\RedditVideoMakerBot-master\main.py", line 6, in <module>
    from reddit.subreddit import get_subreddit_threads
ModuleNotFoundError: No module named 'reddit.subreddit'

**Comment by vitviki** [comment]
Were you successfully able to install all the dependencies in requirement.txt?

**Comment by KodiShaphasa** [comment]
Yes all of them.
Only a slight problem in step 5 when i run python -m playwright install the terminal shows nothing. ![Screenshot_20220624-105733_Remote Desktop.jpg](https://user-images.githubusercontent.com/98024503/175501278-b8ba129e-22b7-49b9-9807-1f7ff05255ec.jpg)

**Comment by KodiShaphasa** [comment]
I tried it. The same again, nothing happens when i run python -m playwright install

**Comment by vxibrahim** [comment]
> I tried it. The same again, nothing happens when i run python -m playwright install
> 

Nothing happened for me either but it still works, so its normal. But did you do `playwright install-deps` ?

**Comment by JasonLovesDoggo** [comment]
Fixed
