### ISSUE TITLE
REDDIT_USERNAME with hyphens -

### ISSUE THREAD

**Issue by acidtib** [elebumm/RedditVideoMakerBot#676]
**Describe the bug**
REDDIT_USERNAME with a hyphen is incorrectly validated

**To Reproduce**
set REDDIT_USERNAME to `dr-kurubit` and run `python main.py`

**Expected behavior**
the username string regex should account for hyphens

**Screenshots**
![Screenshot](https://i.imgur.com/zUDHMzn.png)

**Additional context**
This issue is currently happening on the develop branch

**Comment by JasonLovesDoggo** [comment]
@CordlessCoder

**Comment by JasonLovesDoggo** [comment]
Fixed
