### ISSUE TITLE
Sox not found

### ISSUE THREAD

**Issue by SH4LT1S** [elebumm/RedditVideoMakerBot#681]
I looked at the other issues, followed the install video but it still says sox not found. What should I do?

**Comment by rastogiujj12** [comment]
https://luka-hietala.gitbook.io/documentation-for-the-reddit-bot/installing-sox find your OS and follow the instructions

**Comment by neilk17** [comment]
run `pip install -r requirements.txt`

**Comment by CJthisis** [comment]
1. Go to advanced system settings
2. Go to system variables
3. Find the 'PATH' variable
4. Click on Edit
5. Add the path where sox is installed
    a) If you installed sox via 'pip install sox', search for a folder called 'sox'
    b) If you have it installed via sourcefourge, it is in C:\Program Files (x86)\sox-14-4-2 (assuming you havent changed the destination on installation)
6. Move the sox path all the way to the top of the list of entries in the 'PATH' variable.
7. Hope that helps!
8. (If you get an error, I would advise you to search for solved issues on github which mention the same error)

**Comment by AbdArtur** [comment]
i did that and still have issues

**Comment by JasonLovesDoggo** [comment]
Well then you didn't do it properly follow the steps and if you still have problems Google it

**Comment by AbdArtur** [comment]
i honestly just gave up on using this

**Comment by JasonLovesDoggo** [comment]
> i honestly just gave up on using this

Use develop it doesn't use SOX anymore
