### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Gheghila** [elebumm/RedditVideoMakerBot#682]
<img width="1417" alt="Screenshot_2" src="https://user-images.githubusercontent.com/108138421/175572930-21c8bf4c-a7d8-4a1e-abaa-8d4944e20709.png">

**Comment by Cizzl** [comment]
Please delete your existing .env file, then fill your .env.template file and rename it to .env

**Comment by JasonLovesDoggo** [comment]
Fixed
