### ISSUE TITLE
Final Step Not Working

### ISSUE THREAD

**Issue by Deadshotv21** [elebumm/RedditVideoMakerBot#685]
When running python main.py, it tells me that there's no such file location to put the video in, I also provided a screenshot 
![Developer Command Prompt for VS 2019 (2) 24_06_2022 22_27_35](https://user-images.githubusercontent.com/108154105/175663428-3805a0d9-07f3-463e-8e18-2dd232e7d9f6.png)

**Comment by Cizzl** [comment]
Please delete your current .env file. Fill out the .env.template file with your details, then rename it to .env
