### ISSUE TITLE
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.

### ISSUE THREAD

**Issue by LukeMedeiros916** [elebumm/RedditVideoMakerBot#686]
I just wanted to quickly contribute my errors with the program. This error seems to happen when my screen turns off, but the PC is still running the program(The PC is not asleep).
![Screenshot 2022-06-24 152220](https://user-images.githubusercontent.com/71280264/175706473-95bb0d95-6129-4aa1-903d-c4717c55f371.png)

**Comment by JasonLovesDoggo** [comment]
fixed in 2.2.1 i belive
