### ISSUE TITLE
Failing to make the final video.

### ISSUE THREAD

**Issue by obamacat9** [elebumm/RedditVideoMakerBot#688]
**Describe the bug**
When making the final video will fail
and the logs say that
    raise IOError(("MoviePy error: failed to read the first frame of "
OSError: MoviePy error: failed to read the first frame of video file assets/temp/background.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.

What i do to fix this is i delete the video
run main and hope that it works this time around

**To Reproduce**
i did nothing that would cause this

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Device: [asus]
 - OS: [windows 10]
 - App version [2.1]

**Additional context**

**Comment by BradTFT** [comment]
not sure if it would work but i saw someone say to delete the assets folder and rerun. not sure if it would work 

idk why said it sry i cant give credit

**Comment by JasonLovesDoggo** [comment]
> not sure if it would work but i saw someone say to delete the assets folder and rerun. not sure if it would work
> 
> idk why said it sry i cant give credit

believe that was me :D

also fixed/stale
