### ISSUE TITLE
Need a New Voice

### ISSUE THREAD

**Issue by Sanyam-Ahuja** [elebumm/RedditVideoMakerBot#689]
Please Add The Daniel MLG voice Its a Great Voice for Reddit Videos Pls

**Comment by Sanyam-Ahuja** [comment]
Did It Myself Using pyttsx3 instead of gtts

**Comment by lamasterso** [comment]
Do you mind sharing how you did it for a newbie ?

**Comment by lamasterso** [comment]
@Sanyam-Ahuja I am currently stuck on changing the text size as well, Do you know any solution to increase text size ?

**Comment by Zxchz** [comment]
@Sanyam-Ahuja Can you share how you did it?

**Comment by JasonLovesDoggo** [comment]
Well if they aren't going to share...

**Comment by Bluntsrl** [comment]
You should explain how this is done?

**Comment by Sanyam-Ahuja** [comment]
> You should explain how this is done?

Sorry I don't remember it vividly now will definitely tell u in like 48 hrs., Sorry for taking so much time I have a paper due  tomorrow I need to do that first

**Comment by Bluntsrl** [comment]
> > You should explain how this is done?
> 
> Sorry I don't remember it vividly now will definitely tell u in like 48 hrs., Sorry for taking so much time I have a paper due tomorrow I need to do that first

Sounds good thanks!

**Comment by Bluntsrl** [comment]
> > You should explain how this is done?
> 
> Sorry I don't remember it vividly now will definitely tell u in like 48 hrs., Sorry for taking so much time I have a paper due tomorrow I need to do that first

Any update? I've been trying to figure this out, but no luck
