### ISSUE TITLE
"Text length is too long!" error

### ISSUE THREAD

**Issue by LukeMedeiros916** [elebumm/RedditVideoMakerBot#691]
![Screenshot 2022-06-24 193420](https://user-images.githubusercontent.com/71280264/175755019-a2ca20ff-dbc1-4141-8338-a3c32193daa9.png)

**Comment by Sanyam-Ahuja** [comment]
Ya Had The Same Error.
Just Go in The Env and Change The MAX_COMMENT LENGTH to a lower no. like 200 or 250 etc below 350

**Comment by JasonLovesDoggo** [comment]
Will fix once I get back to Canada

**Comment by JasonLovesDoggo** [comment]
Try using the develop branch in the meantime

**Comment by ehroiecfert** [comment]
I tried it on developer and master branch
The error still appears **on both branches**. Comment length in the .env is 250
