### ISSUE TITLE
Playwright Issue

### ISSUE THREAD

**Issue by DuckeyCodes** [elebumm/RedditVideoMakerBot#692]
![15](https://user-images.githubusercontent.com/83031829/175757922-a9a16c99-2c15-458f-b95d-1901a911ca5b.png)
I'm having an issue i can't download playwright even with -m any fixes I'm using Git Bash

**Comment by neilk17** [comment]
Run  `playwright install`

**Comment by DuckeyCodes** [comment]
> Run `playwright install`

I did in the screenshot

**Comment by ThatGuyCalledJesse** [comment]
Maybe `pip install playwright`

**Comment by DuckeyCodes** [comment]
> Maybe `pip install playwright`

I fixed it I forgot the python part

I did -m playwright install instead of python -m playwright install
