### ISSUE TITLE
Error running main.py

### ISSUE THREAD

**Issue by iamqw3rty** [elebumm/RedditVideoMakerBot#694]
**Describe the bug**
When running `main.py`, I get some kind of JSONDecodeError upon converting the text to MP3

**To Reproduce**
Run `main.py`

**Expected behavior**
The video should be created with no issues

**Screenshots**
![image](https://user-images.githubusercontent.com/87212071/175771376-9e540ca1-00b7-4793-8002-4fcb641b5876.png)

**System (please complete the following information):**
 - Device: MSI GF63
 - OS: Windows 11 Home 21H2
 - App version: 2.1

**Comment by woit45** [comment]
delete data from video_creation\data\videos.json in my case it help
