### ISSUE TITLE
16:9 Video configurable in .env-file

### ISSUE THREAD

**Issue by CJthisis** [elebumm/RedditVideoMakerBot#696]
**Is your feature request related to a problem? Please describe.**
The background video is already in a 16:9 format, and the video lenght is alreay configurable. it would be a amazing to create longer videos, for example for YouTube. Idealy this feature could be turned on or off in the .env file.

**Comment by SH4LT1S** [comment]
any way to increase a video lengt?

**Comment by CJthisis** [comment]
Either in main.py or voices.py there is a variable called "video lenght". The standard amount is 40 seconds, but you can increase or decrease it as you like. But the rendering time is going to be exponentially longer, so I would advise you to check BEFORE if all other settings are exactly how you want them.

**Comment by SH4LT1S** [comment]
> 

yeah, i tried but it shows text too long error

**Comment by CJthisis** [comment]
> > 
> 
> 
> 
> yeah, i tried but it shows text too long error

Ok then try to shorten the max comment length. I think everything under 300 works

**Comment by DennyEarth** [comment]
> You can change the format now

Can you tell me how?
