### ISSUE TITLE
Make The Text Size Seem little Bigger

### ISSUE THREAD

**Issue by lamasterso** [elebumm/RedditVideoMakerBot#697]
**Is your feature request related to a problem? Please describe.**
the problem is that the final video has very small text size specially the comments

**Describe the solution you'd like**
I would like to change the text size/screenshot  seem bigger font

**Describe alternatives you've considered** (optional)
for example the first text has bold and has very good size for reading, but the comments has smaller size, it wold be great 
to make the comments size same as what the title size is now, and then making the title size a little bigger than what it is now.

**Comment by JasonLovesDoggo** [comment]
Won't be added. 
 It's a perfectly adequate size and it has a nice personality to it too!
