### ISSUE TITLE
How can I make the video longer to fit more comments?

### ISSUE THREAD

**Issue by rubenfsgomes** [elebumm/RedditVideoMakerBot#698]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered** (optional)

**Additional context** (optional)

**Comment by JasonLovesDoggo** [comment]
Somebody accidentally removed that feature I have to re-add it please wait 5 days for me to get back to Canada

**Comment by rubenfsgomes** [comment]
Thank you!
