### ISSUE TITLE
I can not create a second video

### ISSUE THREAD

**Issue by DrL4rry** [elebumm/RedditVideoMakerBot#699]
Hello when I have created a video with the bot and want to use the program again always comes an error code

**To Reproduce**
After a successful creation of the first video i only have to type "python main.py" to get the error
it always breaks after the audio 

**Expected behavior**
I would like the bot to be able to create a second video 

**Screenshots**

![Bug](https://user-images.githubusercontent.com/108190745/175783194-ebdff5e3-e79e-4511-aa82-a1218c6eaa90.png)

**System (please complete the following information):**
 - Device: [PC]
 - OS: [Windows 10]
 - App version [ 2.1]

**Comment by Jake006thesnake** [comment]
I just had this bug and I just pulled the master code and ran the bot and it worked fine.

**Comment by DrL4rry** [comment]
> I just had this bug and I just pulled the master code and ran the bot and it worked fine.

Thanks for the help, could you elaborate a bit more am still relatively new to this

**Comment by DrL4rry** [comment]
If I take a specific post everything goes well.
