### ISSUE TITLE
Clear a redundant reference

### ISSUE THREAD

**Issue by dreamcoin1998** [elebumm/RedditVideoMakerBot#702]
There is an extra import here.
I read the code of the file and found that **"async_playwright"** was not used.

https://github.com/elebumm/RedditVideoMakerBot/blob/7554d22ecdc487274bf39e3c2bdd37901bf46ef6/video_creation/screenshot_downloader.py#L6

**Comment by muhammadpatel** [comment]
Run playwright install and playwright install-deps. (if this fails try adding python -m to the front of the command)

**Comment by JasonLovesDoggo** [comment]
This is not a bug it's intentional
