### ISSUE TITLE
the comand prints long unneeded text

### ISSUE THREAD

**Issue by lamasterso** [elebumm/RedditVideoMakerBot#705]
when i change the voice then while creating the mp3 files, the command line interface prints so many text 

E6AEWbGTOmXBHTaGDMHJaGGvHJNnN2AQ2e3AbNgZhaQiDIqzVfDVujCvDZqDQAxIWe9YYgyicaLeYfcq4NfmaOnHbGrEDtE70MzC4QzQOnE5xvppC+NHUD
W1szZMOXeTJYIytWMyBTaDU18yAhMaEEHIpRjjEZU4ih0YAGp8BAKHFJkYcZowmlGwIFTWCgyxNMBHjWkEyJ+MlKjAEI2wCJmoRMppC6YMEmPEYEFzMDsMa
zF6ICtoJNjNFkxtIMudTMBQGk4ADBIeMMRMkbHZ5qRRyAhtzQsnNAXMAVNewQrMcvKypYEkT4MPGIZFoTOjB//PExP9xdDnwBNb1TEBnBJKYiyYaCmEBjAk
vkDgESAgYdEiRgwAVD8wQcwBgSBKcJCpBFuQqJEQFgSTTOkOpfURCFIIMpdmCFDwJ1W3ZKmk1os8sefVAidFmItjgBLWhQWZ2qJ9FHYdfWPOSzh/2CMph9W
2WOE8MMTNmAKNw4EXnWh1huLBKaajT7arvLqDnkhybwdl2rj9S65Gq1mG6eQQuL/B9iO0Us5Dktbk8U3IJTPRXkAYSCAbMOvdFn2qNltZsowlcueaRzL9vH
ZbtDFA/zdoJawgBkI2CAgAWkNaVErBs1Bw3RkhwXHmbRmepGFNmjUCkEzEAzhEEvjSPzlpDbDjoizbKjK5TqDAM0Nq0C700zIwqMx5ICOT7HSpfMNpMQXOg
FNKODhoYOMRNNMkMolBT01VMtSaYySMDIQTCuzqIjCTTCqBiCaAeYqaP2DBbQrGACQXpG/gDn85zYQEzilDU2DlUTzwDWKRQmIi5rmRj4ZALN8+H2ZgiJmC
p//PExKxqlDnsAtZZ6JVGRqRCvMC2MApELoWvmBdGTWm/SGhaGcQnTHGGbBiUD/xvaYFKJLjDJA7uWBAVALDlkDemBGMJC5lkxUigKiKhwU9MIUPK+NswKr
mQwn+IhTJMMoVyhUoKwqIkW5pAJrwGXvMQxOIajFjmBgIl2C+Ka5AAv8wh2MKvC4gqGFikU3Wc2WF9mQsDW6oC0qU0asivEfmnqkVXjKbzEUm3OXOzR8nnf
5ylcwHKGRvAwKfjdJErDazzWc3iuS9xg4KRUK4niIr1CNxPL1lANx85k/M3YKnLVzw2o+YtLTHGUjI6EtlEp0Sitd08TqignOCihnSU4KpsYQsrY+SomT5z
KkQgUJlZbFYgGEo6tVswAWIEHcBguJMNInDZSgqFElrAN4CHTIUrUwUKSJp4yratAHCFCkyTGYVCJCLqske56FLhAUoQb7DigeYtyXZQ8N4AJkS4d7DgjaB
VMxBJVFazUkdMg+kkX1QsNrhy42g9yFIjwHqB//PExHRN9AncAMYZHYsKIDzGqIoIWUwFK0KBQ4JnoKsyfOdoYFRtUANYgpkFcP8AJsIQDjLFBpkcy7Mcdp
iSnaSJc1TQvk+KgLTCzylYKKjqgaXuYOmDBUimnrXUkavxMZ+1MWuI/J6uO027OAkQw9QgbD0bxF0wCoOSIISgGxfQD6tmUyErMSkOwclgDw0mxJNSUjMVJ
0jOnzFg+hW0XQPWZdOnzFha0qOXHplm62i6F1p5n69a21z8ttc+szXHq9a1e2ufXPnZ2uWZRRr8SopMQU1FMy45OS41qqqqqqqqqqqqqqqqqqqqqqqqqqqq
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq","duration":"882","speaker":"en_us_ghostface"
},"extra":{"log_id":"202206252014020100020076370040050060030020395686D"},"message":"success","status_code":0,"status_ms
g":"success"}

**Comment by CJthisis** [comment]
I have this bug also, and it only happens when using the TikTok TTS. (At least for me)

**Comment by JasonLovesDoggo** [comment]
What version are you using & please copy and paste the TikTok.py file here

**Comment by CJthisis** [comment]
I am currently using an unmodified version of Release 2.1, and indeed this long text is only printed when I use the TikTok TTS. When using Polly for example, the text doesnt appear. I want to mention that this text doesnt prevent the bot from working, but it is an annoying visual bug to have.

**Comment by CJthisis** [comment]
Forgot to mention: When using the TikTok TTS, I am using the voice en_us_010

**Comment by JasonLovesDoggo** [comment]
Can you provide a GitHub gist as I do not want to download something

**Comment by CallumIO** [comment]
It was a debugging line left in - already removed in latest develop and will be in next release

**Comment by JasonLovesDoggo** [comment]
> > It was a debugging line left in - already removed in latest develop and will be in next release
> 
> When will the next release be? 

Whenever there are enough features in develop
