### ISSUE TITLE
Question title and comment

### ISSUE THREAD

**Issue by lamasterso** [elebumm/RedditVideoMakerBot#706]
Why does the question has bigger Bold font and then the comments have non bold small text ? 
which file determines this settings ? 

also, my Rendered video seems to have lower quality than my previous videos quality, not the background quality since that is from the YouTube video, but the quality of the screenshot images is dropping pixels, I am not sure where in settings this is as well

any help!

**Comment by IslaFTW** [comment]
> Why does the question has bigger Bold font and then the comments have non bold small text ? which file determines this settings ?
> 
> also, my Rendered video seems to have lower quality than my previous videos quality, not the background quality since that is from the YouTube video, but the quality of the screenshot images is dropping pixels, I am not sure where in settings this is as well
> 
> any help!

I have also detected the same thing, I don't know if they are lowering the quality of the images due to performance, but I have also noticed that the images (Screeshots) are not in the best maximum quality, they look a bit like png in low quality
