### ISSUE TITLE
I have an error after running "python main.py"

### ISSUE THREAD

**Issue by hakupila** [elebumm/RedditVideoMakerBot#708]
I have set up everything. Installed SoX aswell. Did run "pip install -r requirements.txt".
Installed playwright. Everything was fine.
After setting up the .env file and running it with "python3 main.py" I am getting following Error Code:

![image](https://user-images.githubusercontent.com/108199354/175792202-a3c801e7-423f-4a34-9dde-5305ebe55ec5.png)
![image](https://user-images.githubusercontent.com/108199354/175792195-7d5ad6c6-9567-4af2-a1a8-ae3b53c9bdc7.png)

I can't figure this out. Thanks in advance for any help!

Cheers

Haku

**Comment by JasonLovesDoggo** [comment]
Wrong username client ID or client secret
