### ISSUE TITLE
Error while creating

### ISSUE THREAD

**Issue by enragedsweat** [elebumm/RedditVideoMakerBot#71]
I tried to use the bot but this showed up 
![image](https://user-images.githubusercontent.com/104448363/171428809-9371f109-45e6-4f1c-8b8a-7bf284b679af.png)

**Comment by JasonLovesDoggo** [comment]
did you accidentally change any code?
I would just recommend just recloning the repo

**Comment by FreebieII** [comment]
Hi @enragedsweat ,

I hope you were able to resolve your issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
