### ISSUE TITLE
Playwright Download Issue

### ISSUE THREAD

**Issue by DuckeyCodes** [elebumm/RedditVideoMakerBot#710]
I've been trying to install playwright but I keep getting the same issue of it not finding playwright as a command. I'm using Git Bash

**Screenshots**
![image](https://user-images.githubusercontent.com/83031829/175796201-158b41eb-32ef-42df-9c3a-1ddcb45e7c74.png)

**Comment by JasonLovesDoggo** [comment]
python -m not just -m

**Comment by JasonLovesDoggo** [comment]
Also why are you using git bash? Use PowerShell or a Unix terminal
