### ISSUE TITLE
does anyone know a fix for the file name to be full? and no ...s 

### ISSUE THREAD

**Issue by jordan1121** [elebumm/RedditVideoMakerBot#713]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - App version [e.g. 22]

**Additional context**

**Comment by BlockArchitech** [comment]
Invalid

**Comment by JasonLovesDoggo** [comment]
This isn't a bug it's a question Don't add a label if you don't know what it means

**Comment by JasonLovesDoggo** [comment]
Go to https://github.com/elebumm/RedditVideoMakerBot/blob/master/video_creation/final_video.py#L112
And replace

            return title[0:30] + "..."

With 
       return title
