### ISSUE TITLE
No ffmpeg exe could be found

### ISSUE THREAD

**Issue by Aniket22156** [elebumm/RedditVideoMakerBot#714]
**Describe the bug**
No ffmpeg exe could be found while running the program and even after the installing the ffmpeg the error is still there.

<img width="1123" alt="Screenshot 2022-06-26 at 10 20 02 PM" src="https://user-images.githubusercontent.com/69108762/175826949-399d8176-ff95-47fc-91e3-be792a0aa0d6.png">

<img width="1100" alt="Screenshot 2022-06-26 at 10 20 14 PM" src="https://user-images.githubusercontent.com/69108762/175826954-bcd356af-854c-4f9f-9bbd-e7f064e78682.png">

**System (please complete the following information):**
 - Device: [Macbook 14inch]
 - OS: [MacOS Monterey 12.4]
 - App version [PyCharm [CE]]

Is there anyway to fix it?

**Comment by JasonLovesDoggo** [comment]
Google how to add FFMPEG to path
