### ISSUE TITLE
errors when running main.py

### ISSUE THREAD

**Issue by fatheruju** [elebumm/RedditVideoMakerBot#718]
ive followed the instructions idk what im doing wrong but i get these errors can anyone help?
![image](https://user-images.githubusercontent.com/104296351/175861396-f894b2e4-9277-439c-a57c-f974a455ba62.png)

**Comment by fatheruju** [comment]
edit; nvm got it fixed had to download background video manually

**Comment by sarimwaniR** [comment]
close issue bro

**Comment by VodenoFF** [comment]
How u fixed it?

**Comment by sarimwaniR** [comment]
clone the Repository again Put the stuff in and try again

**Comment by Alexlinkinfinite** [comment]
where did you download the background video from?

**Comment by JasonLovesDoggo** [comment]
YouTube
