### ISSUE TITLE
Required configuration setting 'client_id' missing

### ISSUE THREAD

**Issue by Aniket22156** [elebumm/RedditVideoMakerBot#722]
**Describe the bug**
raise Missing required attribute exception: Required configuration setting 'client_id' missing, and I already have run and installed playwright install and playwright install-deps functions.

<img width="1081" alt="Screenshot 2022-06-27 at 2 53 23 PM" src="https://user-images.githubusercontent.com/69108762/175909794-777a0014-01ed-4817-b77a-662e29150a2d.png">

**System (please complete the following information):**
 - Device: [Macbook 14inch]
 - OS: [MacOS Monterey 12.4]
 - App version [PyCharm[CE]

**Comment by kervis03** [comment]
Did you fill out the .env file like in the setup document said?
You need to make a reddit app and put its client id into the .env file.

**Comment by JasonLovesDoggo** [comment]
Dude literally read the error
Make sure the file is named correctly and you have the value in place
