### ISSUE TITLE
crashes on running

### ISSUE THREAD

**Issue by Kickett** [elebumm/RedditVideoMakerBot#723]
Works 'fine' and then when the TTS is done it crashes, there is a tonne of text that appears for a split second and then disappears which I wasn't able to see.

To confirm the mp3's DO go into the assets folder so I assume it's a playwright issue but I was under the belief that it gets installed during pip3.

EDIT: I have tried pip and not pip3, it now crashes after putting in the thread

**Comment by JasonLovesDoggo** [comment]
Run in a terminal so you can see the output

**Comment by JasonLovesDoggo** [comment]
Closed for sale

**Comment by JasonLovesDoggo** [comment]
Stale
