### ISSUE TITLE
Where to type yes? and what reddit key?

### ISSUE THREAD

**Issue by NicklasMonnick** [elebumm/RedditVideoMakerBot#726]
Hello

I'm completely new to python and doesn't really know where i should put the yes as the tutorial says. Furthermore i'm not sure what is meant be a reddit key.

screenshots of code:
![image](https://user-images.githubusercontent.com/97225287/175977897-b0787f6a-422c-4e60-b740-3661edd4cbf4.png)

**Comment by xIvan0ff** [comment]
What the... f.... what did I just see 😃 You literally just typed yes in the PowerShell.

Whatever, try running
`pip install -r requirements.txt`
