### ISSUE TITLE
add poetry & maybe move from playwright and other suggestions

### ISSUE THREAD

**Issue by Drugsosos** [elebumm/RedditVideoMakerBot#732]
So basically I got inspired by this repo and created [my own](https://github.com/Drugsosos/VideoBot) and found some interesting stuff you might appreciate.

* Poetry
> Like pip but better, one command install, even python version is covered up in dependencies

* Selenium
> I personally hate playwright (I'm QA btw, duh), so there is super nice async WebDriver - Pyppeteer, check it out

* More timings and customization 
> Like delay before start/end, between pictures, before tts. They make videos look and sound nice

* Auto search back video/audio
> In general, it's just two envs for each, you can check if they are empty and search for something default ```Minecraft parkour``` or ```subway surfers```, or if they are not blank, search it on YT, or if it's a YT link just download it.

* afx.normalize and fx.loop
> Back audio volume normalize will be nice (one command in moviepy), also looping back content will be nice, so you don't have to download big files

* More async code
> You can move from prew to asyncprew, for instance, you don't have to load all the comment in manual mode, when you choose submissions, only when you approving comments. It's easy and gives you lots of flexibility 

* Remove examples from root
> README in GitHub support video from the box, you can just drag them to README in web and link will be there, no need to store it in root so every ```git clone``` will not download it

I have all of it ready in my repo, so if you want to do anything listed here, you can just copy it, I don't mind, or I can do it, if you'd like to.

upd: forgot about something, lots of typing will be very nice, so people will have a better time understanding what's going on while contributing

**Comment by Drugsosos** [comment]
What do you think @CallumIO @JasonLovesDoggo ? 

At least I can add this improvements (they will speed up everything significantly)

* move from prew to asyncprew
* move from requests to async requests with aiohttp
* add async selenium driver and make a factory for webdrivers (or maybe even completely move to selenium)
* move dependencies to poetry (3 command to install and run, sound great imho)

Tag me if you want to see me do this

**Comment by William9923** [comment]
i think this can be used to gradually improve the performant of the bot. Could split this `enchancement` into multiple task.

**Comment by Drugsosos** [comment]
@William9923 [async-webdriver](https://github.com/elebumm/RedditVideoMakerBot/pull/933) and [poetry](https://github.com/elebumm/RedditVideoMakerBot/pull/932) are ready, you can check them out :zap:
