### ISSUE TITLE
Make more than one folder the videos can be saved to.

### ISSUE THREAD

**Issue by Foxcer11** [elebumm/RedditVideoMakerBot#736]
Depending on the type of subreddit the video contains, determines which folder it's saved in. e.g.
![Screenshot 2022-06-28 165815](https://user-images.githubusercontent.com/69968700/176225951-e5ebeda2-90f0-494d-8f38-bd9f4e7bb711.png)

**Comment by JasonLovesDoggo** [comment]
Hmm ok Ile add this

**Comment by JasonLovesDoggo** [comment]
> Already doing xD @JasonLovesDoggo 

Don't forget to make a PR
That's the exact implemtation I was going to do though.

**Comment by Cizzl** [comment]
@JasonLovesDoggo Is there a tag for 2.2?

**Comment by JasonLovesDoggo** [comment]
> @JasonLovesDoggo Is there a tag for 2.2?

Not yet

**Comment by Cizzl** [comment]
> > @JasonLovesDoggo Is there a tag for 2.2?
> 
> Not yet

then just into develop branch?

**Comment by JasonLovesDoggo** [comment]
> > > @JasonLovesDoggo Is there a tag for 2.2?
> > 
> > Not yet
> 
> then just into develop branch?

Yep

**Comment by JasonLovesDoggo** [comment]
done.

**Comment by Foxcer11** [comment]
NIICCCE !!!can't wait to try it out next update
