### ISSUE TITLE
Is there any way to pause the video process?

### ISSUE THREAD

**Issue by ghost** [elebumm/RedditVideoMakerBot#738]
Is there any way to pause the video process?

I would like to edit the answers that the script downloads in .png

And once I finish editing the .png resume the video creation process

Or better yet, is there a way to hide the reddit username from the screenshot.png?

**Comment by William9923** [comment]
I think it is possible @IslaFTW to pause the video process. 
It could be either:
- A prompt that waits till you finish editing the image
- Separating the process into 2 process ? (1 downloading, 2 for video creation)

I think either one could be implemented, but others might have different opinions (this is just my opinions). Thanks 🙏  

I think it is possible to hide the reddit username (similar to blurring them or hiding them with a box?), but I never explored on that. Other might have better opinions.

**Comment by rajniszp** [comment]
As a workaround you can:
a) open it in some debugging tool and set a breakpoint,
b) insert the ["pause" command](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/pause) (assuming you're using Windows) after the image generation; python code I believe would be `Popen("pause", shell=True).wait()`
