### ISSUE TITLE
for privacy: Is there a way to hide the reddit username from the screenshot.png?

### ISSUE THREAD

**Issue by ghost** [elebumm/RedditVideoMakerBot#739]
In large tiktok accounts and I have read complaints that your reddit username appears and they do not want it to come out for privacy, and I would not want to face problems of that kind one day in my account, is there any way that the username does not come out from reddit in the screenshots?

**Comment by JasonLovesDoggo** [comment]
Technically it's possible but it would be a pain to implement plus I think it's kind of stupid.
If you are posting publicly on Reddit that anybody can view you void any expectation of privacy.
Same with taking photos of people on public property in Canada / US The laws are if you're willing to be seen on public property you void your right to privacy in that sense

**Comment by JasonLovesDoggo** [comment]
Won't be implemented
