### ISSUE TITLE
videos replace eachother if not renamed

### ISSUE THREAD

**Issue by 2Fat4FlyHackZ** [elebumm/RedditVideoMakerBot#74]
if i run the bot twice in a row the videos get saved over eachother, would be great if theres something that gets  random names or numbers it, also would be nice if you could tell the programm to make n amount of videos

**Comment by JasonLovesDoggo** [comment]
see my [fork](https://github.com/JasonLovesDoggo/RedditVideoMakerBot) or PR #139
