### ISSUE TITLE
program does not work (tried many times)

### ISSUE THREAD

**Issue by vnvs1** [elebumm/RedditVideoMakerBot#740]
<img width="569" alt="Screen Shot 2022-06-28 at 22 06 43" src="https://user-images.githubusercontent.com/106883530/176288072-5de074b3-104f-4b5d-820a-8bbc4f62c204.png">

i have faced this problem and i dont know how to fix it , i deleted .env file and created another one but no solution ,the client id is correct and provided in the .env file , have all the requirements installed ( latest versions ) and still no clue :/

**Comment by vnvs1** [comment]
anyone have as solution to this

**Comment by errorline99** [comment]
first make sure you wrote the client id in the .env file and that it is correct
if that dosent work delete the reddit video maker folder and re clone it form the repository


tip : follow the requirements properly

**Comment by JasonLovesDoggo** [comment]
Your .env file is either named wrong or your missing the correct value in the file
