### ISSUE TITLE
Different Backgrounds

### ISSUE THREAD

**Issue by Zxchz** [elebumm/RedditVideoMakerBot#741]
Can I add more videos to the backgrounds folder? If no, can you add that feature?

**Comment by Crisez0694** [comment]
> Can I add more videos to the backgrounds folder? If no, can you add that feature?

Go to RedditVideoMakerBot-master\video_creation and in the code you can add different youtube videos that the bot will use as background footage, just follow the pattern of ("URL, filename.mp4, credit")



> I use a background of 2 hours, and in theory I should cut a random fragment of those 2 hours, but in the last 4 videos that I made, the script took the same fragment :/

Not sure what happened there just make sure you didn't just add it into the backgrounds folder cause that might've caused it but I'm not sure

**Comment by abhijitxp01** [comment]
It's simple, 

 In `background.py` make a list like this:

```
videos = [ url1, url2, url3 ]
```
Then line 19 replace this:
```
background_options = [  # uri , filename , credit
        (random.choice(videos), "parkour.mp4", "bbswitzer"),
```

**Comment by JasonLovesDoggo** [comment]
Another thing which I thoughtfully implemented is you don't even have to add it to that list if you don't want to just drop the file into the backgrounds folder and rename it to the correct scheme

**Comment by William9923** [comment]
Hi, it might be related, but my PR #693 , include a way to change the background (that were supported) easily by modifying the variable in .env.
![image](https://user-images.githubusercontent.com/45505811/176996392-90c8c9dd-198f-4b7c-9700-f5c7c32575a7.png)


For adding new vids, simply add in here (it is implemented the same way as Jason code).
![image](https://user-images.githubusercontent.com/45505811/176996380-32ced3a8-b911-4fb8-bcc3-3c55d80fecb1.png)
