### ISSUE TITLE
[Errno 2] No such file or directory: './video_creation/data/videos.json  AND  [Errno 22] Invalid argument: '.\x0bideo_creation\\data\x0bideos.json'

### ISSUE THREAD

**Issue by sykeze** [elebumm/RedditVideoMakerBot#742]
i get this error whenever i run the code

[Errno 2] No such file or directory: './video_creation/data/videos.json

i saw that and changed the foward slashes to backwards but then after doing that i get this 

[Errno 22] Invalid argument: '.\x0bideo_creation\\data\x0bideos.json'

anyone know how to fix this?

**Comment by Cizzl** [comment]
Please try to reinstall it, the file exists from beginning, maybe you missed anything.

**Comment by JasonLovesDoggo** [comment]
You need to have two backslashes

**Comment by JasonLovesDoggo** [comment]
This isn't an error with my code. It's an error with whatever OS you are using.
Try double checking the file exists in the file explorer though.

**Comment by sykeze** [comment]
> This isn't an error with my code. It's an error with whatever OS you are using. Try double checking the file exists in the file explorer though.

the file exists and the original release of this works fine it only the most recent one im having this issue with
