### ISSUE TITLE
FileExistsError: [WinError 183]

### ISSUE THREAD

**Issue by Ohmnito** [elebumm/RedditVideoMakerBot#746]
It was working fine until now but it suddenly started giving me this issue:

```
Traceback (most recent call last):
  File "C:\Users\Kount\RedditVideoMakerBot\main.py", line 67, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))
  File "C:\Users\Kount\RedditVideoMakerBot\main.py", line 60, in run_many
    main()
  File "C:\Users\Kount\RedditVideoMakerBot\main.py", line 47, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\Kount\RedditVideoMakerBot\video_creation\voices.py", line 56, in save_text_to_mp3
    TextToSpeech.tts(
  File "C:\Users\Kount\RedditVideoMakerBot\TTS\TikTok.py", line 120, in tts
    os.rename(audio_clips[0], filename)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'assets/temp/mp3/4-0.mp3' -> 'assets/temp/mp3/4.mp3'
```

**Comment by abhijitxp01** [comment]
Delete this folder: `temp`
location: `C:\Users\Kount\RedditVideoMakerBot\assets\temp`

**Comment by Ohmnito** [comment]
> Delete this folder: `temp` location: `C:\Users\Kount\RedditVideoMakerBot\assets\temp`

This did not work but I found out it was a problem with a particular thread, changing the thread worked but would seem like this was an issue with one of the comments somehow because I just rerun that thread for the 5th time to try to understand which comment was the problem and now it worked... no idea why...

**Comment by ayoub648** [comment]
the error comes from the voice part, its because there is no text in the comment, this is a weird case
to fix it go to RedditVideoMakerBot-master\reddit\subreddit.py line 99, add before ":"
"and len(textify(top_level_comment.body)) >=2"
this should not allow any comment under 2 characters
