### ISSUE TITLE
Choose Subreddit

### ISSUE THREAD

**Issue by BartaLazar** [elebumm/RedditVideoMakerBot#748]
Hi, I'm wondering if it's possible to choose a subreddit manually, instead of getting random. If it's already possible could someone tell me how?
Have a great day!

**Comment by Ohmnito** [comment]
Yes you can, just go into the .env file and modify the SUBREDDIT="AskReddit" to something else.
You can also choose a specific post by modifying POST_ID=""

**Comment by BartaLazar** [comment]
Amazing! Thank you very much!
