### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by TylerL0216** [elebumm/RedditVideoMakerBot#750]
I get this error when trying to run python main.py

 File "main.py", line 51
    f'on the {x}{("st" if x == 1 else ("nd" if x == 2 else ("rd" if x == 3 else "th")))} iteration of {times}'
                                                                                                             ^
SyntaxError: invalid syntax

**Comment by TylerL0216** [comment]
> What Python version are you on

v2022.9.11791004 within Visual studio

**Comment by TylerL0216** [comment]
ahhhhh
So I'm on version 2.7 
I understand i need to be on 3.6+
how do I update within visual studio code?

**Comment by JasonLovesDoggo** [comment]
> ahhhhh
> So I'm on version 2.7 
> I understand i need to be on 3.6+
> how do I update within visual studio code?

You can't you have to actually update python from the website 
https://www.python.org/downloads/
Make sure to click add to path when you are installing
