### ISSUE TITLE
Create an option where the bot reads multiple posts without the comments

### ISSUE THREAD

**Issue by Foxcer11** [elebumm/RedditVideoMakerBot#754]
Just like story mode , but read more than one post in a video. This could be used for subreddits like r/showerthoughts or, r/TIFU where It could be multiple short post in one video.

**Comment by JasonLovesDoggo** [comment]
hold your pineapple 
storymode isn't even done yet

**Comment by Foxcer11** [comment]
XD 
In the near future. after story mode is done  of ofcoure

**Comment by JasonLovesDoggo** [comment]
Good idea though
