### ISSUE TITLE
Make the bot read a statement you type before reading the post

### ISSUE THREAD

**Issue by Foxcer11** [elebumm/RedditVideoMakerBot#755]
The title explains it. The bot says why you typed before reading the post.

This could be useful for stuff like story mode, where the story is too long to fit the 1-min video rule. So you make the bot say for example 'part two of (insert post/story)' or 'this is part two of (insert post/story).

**Comment by JasonLovesDoggo** [comment]
Hmm laterrrr though

**Comment by William9923** [comment]
i think issue #807 similar to this issue

**Comment by William9923** [comment]
Have you started on this yet @JasonLovesDoggo ?

**Comment by JasonLovesDoggo** [comment]
Nop
