### ISSUE TITLE
increase video length

### ISSUE THREAD

**Issue by IslaFTW** [elebumm/RedditVideoMakerBot#756]
I know that every 3 days someone asks to add a variable for the time limit, but I think that nobody reads us, currently the video is limited to less than 60 seconds, tiktok allows videos much longer than that, and for the format of questions and answers 60 seconds is not enough, is it possible that they let us configure the duration?

(In Develop Version)

**Comment by JasonLovesDoggo** [comment]
They used to be one but somebody broke it
