### ISSUE TITLE
Text length is too long!

### ISSUE THREAD

**Issue by IslaFTW** [elebumm/RedditVideoMakerBot#757]
![2022-06-29 21_41_15-C__Windows_System32_cmd exe](https://user-images.githubusercontent.com/60049112/176594250-1aab2d91-11bb-4805-b748-3da5f9554cb6.png)

![2022-06-29 21_40_42-C__Users_rootf_Downloads_Compressed_RedditVideoMakerBot-master_RedditVideoMakerB](https://user-images.githubusercontent.com/60049112/176594258-9392a95f-2f1c-4bc4-ab3d-fb5425cf9675.png)

(Master Version)

**Comment by JasonLovesDoggo** [comment]
Fixed In develop
