### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TylerL0216** [elebumm/RedditVideoMakerBot#768]
I have Sox installed Playwrite installed, Im on the latest version of python and get this error when running "python3 main.py"

Traceback (most recent call last):
  File "/Users/tylerleach/Desktop/RedditVideoMakerBot-master/main.py", line 10, in <module>
    from video_creation.background import download_background, chop_background_video
  File "/Users/tylerleach/Desktop/RedditVideoMakerBot-master/video_creation/background.py", line 6, in <module>
    from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip
  File "/opt/homebrew/lib/python3.9/site-packages/moviepy/video/io/ffmpeg_tools.py", line 7, in <module>
    from moviepy.config import get_setting
  File "/opt/homebrew/lib/python3.9/site-packages/moviepy/config.py", line 36, in <module>
    FFMPEG_BINARY = get_exe()
  File "/opt/homebrew/lib/python3.9/site-packages/imageio/plugins/ffmpeg.py", line 159, in get_exe
    return imageio_ffmpeg.get_ffmpeg_exe()
  File "/opt/homebrew/lib/python3.9/site-packages/imageio_ffmpeg/_utils.py", line 49, in get_ffmpeg_exe
    raise RuntimeError(
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.

**Comment by BradTFT** [comment]
how can i access my package manager. im on debain 10 buster

**Comment by NHastings2** [comment]
As of a recent update, Polly rate limits the request so after a certain number of requests it returns a successful url but has the response Too Many Requests appended to it. I'm experimenting with an patch to hopefully fix the issue.

**Comment by DhrumanGupta** [comment]
> how can i access my package manager. im on debain 10 buster

Use `apt`. You'll need to set it up to work with official sources. You may have done this earlier on too, but [here is how](https://www.itzgeek.com/how-tos/linux/debian/setup-debian-10-official-repository-in-sources-list-etc-apt-sources-list.html)

After that, just run `sudo apt install ffmpeg`

**Comment by BradTFT** [comment]
having an issue following the guide. is there another way?

**Comment by JasonLovesDoggo** [comment]
add FFmpeg to path

**Comment by BradTFT** [comment]
how???

**Comment by DhrumanGupta** [comment]
https://linuxize.com/post/how-to-install-ffmpeg-on-debian-9/
Follow this, it should automatically install it and put ffmpeg in path.

If you have already installed ffmpeg (which I think is unlikely), then you have to add it to PATH. Google how to do that.

**Comment by BradTFT** [comment]
any chance you can walk me thru it? cant find info on adding it to my $PATH

**Comment by BradTFT** [comment]
nvm i think i got it
