### ISSUE TITLE
Is there a way to pull TOP comments instead of HOT comments?

### ISSUE THREAD

**Issue by nicktomasetti** [elebumm/RedditVideoMakerBot#773]
I haven't seen a direct answer to this yet, so I am hoping to achieve that with this post. 

I noticed the video automatically selects HOT comments for the video, but I want the TOP comments instead (I personally think the top comments are better than the hot comments). Is there anyway to modify the code to do this? If this is possible, please make the solution as explicit as possible as I am still learning Python myself.

Any help is greatly appreciated!

**Comment by vitviki** [comment]
Hey,

Inside reddit/subreddit.py just before traversing through all the comments ('for top_level_comment in submission.comments:') add 'submission.comment_sort = "top"'

**Comment by manmohanhunjan** [comment]
hi @vitviki do you know what resolution to put to make normal landscape video current resolution is => 
x1=1166.6, y1=0, x2=2246.6, y2=1920
what should i change?
and also i've replaced the 1080p background video with 1440p one.

**Comment by vitviki** [comment]
Hey Nick, apology for posting somewhat incorrect reply.

So I went through praw documentation and found this 

> Sort order and comment limit can be set with the comment_sort and comment_limit attributes **before comments are fetched**, including any call to [replace_more()]

You need to move `submission.comment_sort = "top"` up right after you have grabbed and verified the submission. Before `upvotes = submission.score`

Hope this helps.

**Comment by nicktomasetti** [comment]
IT WORKED! Thank you so much for following up with me on this.
