### ISSUE TITLE
Playwright error: playwright._impl._api_types.Error: Executable doesn't exist

### ISSUE THREAD

**Issue by NateGaunt** [elebumm/RedditVideoMakerBot#780]
Hey friends, I would greatly appreciate if any of you could help me with this thing. I fully followed the documentation before proceding to use the bot. I don`t know why its not working, and running the command it tells me that it isn`t recognized. This is my first contact with Python, so I fully expect this to be some kind of rookie mistake haha. 
![Error](https://user-images.githubusercontent.com/108524037/176881102-790f803a-1d4c-48e4-9a37-21093c32244d.PNG)
Thanks again, any suggestion is greatly appreciated!

**Comment by Cizzl** [comment]
Follow this instructions: 
https://playwright.dev/python/docs/intro#pip

**Comment by NateGaunt** [comment]
Closed it by mistake. I`m completely new to Github.
