### ISSUE TITLE
ModuleNotFoundError for praw upon running main.py

### ISSUE THREAD

**Issue by alhcomer** [elebumm/RedditVideoMakerBot#782]
When running main.py python outputs "ModuleNotFoundError: No module named 'praw'" despite praw being installed in my virtual environment alongside all other requirements in requirements.txt.

**Comment by Cizzl** [comment]
Please try again installing the requirements, check if there some errors occurs while installing

**Comment by alhcomer** [comment]
I have done this. praw is in my venv's site-packages folder, though is still not being picked up when I try to import. Could this be due to my site-packages path not being on python path?

**Comment by alhcomer** [comment]
I believe that this was a result of me running using VS Code's 'Run Code' feature instead of 'Run Python File'. My mistake. Apologies.
