### ISSUE TITLE
Would it be possible to make the bot choose posts from your home feed rather than a subreddit ?

### ISSUE THREAD

**Issue by Foxcer11** [elebumm/RedditVideoMakerBot#787]
what i mean by home page is the page you first see when your logged in to your account.

If this is possible, then it would mean the bot would generate more relevant stuff. if you use reddit on a daily basis.

**Comment by dehfguiefhjen** [comment]
On random thread in the .env file, if you set it to "no", when you enter "python3 main.py" into the terminal, you will be asked to paste the thread of whatever you want, so if you would like to post a specific thread you've seen, either bookmark it for later or just open up the command terminal and create the video in a few minutes.

**Comment by JasonLovesDoggo** [comment]
What @dehfguiefhjen said
