### ISSUE TITLE
Make the bot copy the finished video in a different folder

### ISSUE THREAD

**Issue by NateGaunt** [elebumm/RedditVideoMakerBot#799]
By making the bot make a copy of the final video unto another folder we could just create more videos in a more efficient manner. It could help to further automate the process, maybe with this we could even make the program download a bunch of videos and they would be stored in the other folder without damaging the integrity of the original files.

**Comment by dehfguiefhjen** [comment]
There is another folder labeled "results"

**Comment by NateGaunt** [comment]
Holy moly, thanks fam!
