### ISSUE TITLE
UnicodeEncodeError when running the code

### ISSUE THREAD

**Issue by TonnaChan** [elebumm/RedditVideoMakerBot#8]
I am receiving the following error when running the code. What could be the issue?

UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f60a' in position 1: character maps to <undefined>

**Comment by elebumm** [comment]
What machine are you on? Looks like it can't encode the emoji

**Comment by TonnaChan** [comment]
@elebumm I am using VS Code on my Windows 10 Desktop. Is there anything I can do to VS code or on my machine that will allow me to encode the emoji? Or maybe some tweak to the code that I can do to make it work
