### ISSUE TITLE
Problem when running python3 main.py

### ISSUE THREAD

**Issue by herohunterttv** [elebumm/RedditVideoMakerBot#80]
Hello! I'm very new to this type of programming and have gotten all the way to the part where you actually run the code. I run into this error where it says that some executables don't exist.

Any help is appreciated!

![Screenshot 2022-06-01 101909](https://user-images.githubusercontent.com/106681711/171440528-f7f40fac-1588-49d8-a725-610cece6667d.png)

**Comment by Strong10mede** [comment]
> Hello! I'm very new to this type of programming and have gotten all the way to the part where you actually run the code. I run into this error where it says that some executables don't exist.
> 
> Any help is appreciated!
> 
> ![Screenshot 2022-06-01 101909](https://user-images.githubusercontent.com/106681711/171440528-f7f40fac-1588-49d8-a725-610cece6667d.png)

delete the assets file,
then in terminal type : npm install playwright
then type : python3 main.py

**Comment by herohunterttv** [comment]
I'm sorry, I'm oblivious. How do I do the pip3 install playwright? Is playwright an outside application I need to download? I removed all files so I could start clean and I'm retrying the downloads and stuff

**Comment by lesterrar** [comment]
i went to cmd and typed playwright install and it worked for me

**Comment by mrawesomey** [comment]
> I'm sorry, I'm oblivious. How do I do the pip3 install playwright? Is playwright an outside application I need to download? I removed all files so I could start clean and I'm retrying the downloads and stuff @mrawesomey

No just type it in the Terminal

**Comment by FreebieII** [comment]
Hi @herohunterttv,

I hope you were able to resolve your issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
