### ISSUE TITLE
Story Mode question

### ISSUE THREAD

**Issue by dehfguiefhjen** [elebumm/RedditVideoMakerBot#801]
![Screenshot (8)](https://user-images.githubusercontent.com/108509491/176988648-f1141ebd-2905-45ef-8c43-9f2dbc837d15.png)

So while the regular mode works where it reads comments, when I turn story mode from false to true it does this. If im not incorrect story mode is meant to read out the op's post instead of the comments?

**Comment by dehfguiefhjen** [comment]
I tried to do AITA with story mode and messed with settings maximum comment length to 0 and that causes other problems, is there a way to make it read only the original post and not comments?

**Comment by Ohmnito** [comment]
as it's written the story mode is not implemented yet, so of course it's not gonna work

**Comment by JasonLovesDoggo** [comment]
> as it's written the story mode is not implemented yet, so of course it's not gonna work

Exactly lmao
