### ISSUE TITLE
Set a default voice in .env

### ISSUE THREAD

**Issue by ehroiecfert** [elebumm/RedditVideoMakerBot#802]
For me personally, it would be good to set a default voice in the .env

For understanding: With the new Version, I have to select a voice with every single run. But I want to start the bot and the bot run completely through the end.
Please add that or tell me how to do that.

Addtion: When I choose the voice by typing `AWSPolly` an error appears.

**Comment by Ohmnito** [comment]
you already can. In the .env file at the bottom you have 

TTSCHOICE="" where you input the tts engine you want to use.
And then you have 

STREAMLABS_VOICE=""
AWS_VOICE=""
TIKTOK_VOICE=""

where you choose the voice you want to use by default.

**Comment by ehroiecfert** [comment]
Okay. It is set by default TTSCHOICE="Polly"
But with every run I have to select here:
![image](https://user-images.githubusercontent.com/75840437/177032483-c8348b7c-4078-465c-bf8a-6a67d5cacc8b.png)
Is there a way to avoid that? I just want to run it through with the voice as in the last version.

**Comment by muhammedaksam** [comment]
> Okay. It is set by default TTSCHOICE="Polly" But with every run I have to select here: ![image](https://user-images.githubusercontent.com/75840437/177032483-c8348b7c-4078-465c-bf8a-6a67d5cacc8b.png) Is there a way to avoid that? I just want to run it through with the voice as in the last version.

You have to change TTSCHOICE variable in .env file. Options are GoogleTranslate, AWSPolly, StreamlabsPolly and TikTok. For example if you are using StreamlabsPolly your code should be like this

`TTSCHOICE="StreamlabsPolly"
#EXPLANATION the backend used for TTS. Without anything specified, the user will be prompted to choose one.
# IMPORTANT NOTE: if you use translate, you need to set this to googletranslate or tiktok and use custom voice in your language

STREAMLABS_VOICE="Brian"
#EXPLANATION Sets the voice for the Streamlabs Polly TTS Engine. Check the file for more information on different voices.`

Polly is not an option.

**Comment by ehroiecfert** [comment]
Ah, now I understand it. Thank you.
I think we need a lot more documentation. The .env file says "Check the file for more information on different voices" but what file.

Now I like the voice Matthew but the bot seems to work only in some conditions...
So selected Metthew:
Output while using StreamlabsPolly:
![image](https://user-images.githubusercontent.com/75840437/177035279-b3eca0f3-d3ba-41b9-bad2-03aedfb26fd5.png)
Output while using AWSPolly:
![image](https://user-images.githubusercontent.com/75840437/177035304-c3c7725f-8d03-4dc6-9ccd-6d91db24ddc8.png)

Maybe fixes on the develop branch? Then I will use that one

**Comment by William9923** [comment]
Yes, the newest develop branch fix the problem, please try it @ehroiecfert . If it fix it, kindly close the issue 🙏
