### ISSUE TITLE
TypeError: 'type' object is not subscriptable While running the new version

### ISSUE THREAD

**Issue by rastogiujj12** [elebumm/RedditVideoMakerBot#804]
Getting this error with the new version, previous version worked well

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "{path}/RedditVideoMakerBot/reddit/subreddit.py", line 8, in <module>
    from utils.videos import check_done
  File "{path}/RedditVideoMakerBot/utils/videos.py", line 8, in <module>
    redditobj:dict[str],
TypeError: 'type' object is not subscriptable

**To Reproduce**
python3 main.py

**Expected behavior**
run the bot

**Screenshots**
NA

**System (please complete the following information):**

- Python Version: Python 3.8.10
- OS: Linux mint 20
- App version / Branch: Master

**Additional context**
This was working fine before the update, I am not sure what version I was on, cloned the repo from the master, and now it gives the above error.

**Comment by rastogiujj12** [comment]
Tried Python3.10 and now it works. Might work with Python3.9 as well.
Please update the readme to the correct version.

**Comment by JasonLovesDoggo** [comment]
Use Python 3.9 Plus or 2.2.2
