### ISSUE TITLE
Getting this Error when the bot is creating the final video.

### ISSUE THREAD

**Issue by csbmt** [elebumm/RedditVideoMakerBot#805]
Hi Tried pip install -r requirements.txt and after many attempts i keep getting this 
![image](https://user-images.githubusercontent.com/98764467/177001351-76d02486-201f-4f55-a211-1fa7a5e7dc8d.png)

**Comment by Ohmnito** [comment]
Redownload the entire project, there is a problem in the code... there shouldn't be a mp3 folder in assets, it should be in asserts/temp/

**Comment by csbmt** [comment]
it is

**Comment by csbmt** [comment]
![image](https://user-images.githubusercontent.com/98764467/177007325-356b89a6-9d80-4776-a8ae-b66580ff6815.png)

**Comment by Ohmnito** [comment]
there should be a png folder in assets though but not mp3 so that's normal. 
Try to create a mp3 folder and png folder in assets then delete the temp folder and try running the code again.

**Comment by csbmt** [comment]
Same error

**Comment by csbmt** [comment]
in the temp folder, it makes mp3 folder, png folder and background.mp4

**Comment by csbmt** [comment]
I fixed if I drag mp3 and png folders out of temp it works

**Comment by csbmt** [comment]
also u have to do this every time
