### ISSUE TITLE
Is there way where I enter a text and it will be converted into voice like your custom intro saying welcome to my channel

### ISSUE THREAD

**Issue by prabeshstha11** [elebumm/RedditVideoMakerBot#807]

**Comment by ProjectSlxsh** [comment]
that is called tts generator not what the issue page is for

**Comment by William9923** [comment]
I think what the issue means, is that could we add a feature to make intro for the short video, given a short text as intro? @prabeshstha11 correct me if im wrong tho

**Comment by JasonLovesDoggo** [comment]
Pass the args directly to the TTS engine
