### ISSUE TITLE
Crashed after downloading yt video.

### ISSUE THREAD

**Issue by smolkoolko** [elebumm/RedditVideoMakerBot#808]
**Expected behavior**
Download the video and edit everything together.

**System (please complete the following information):**

- Python Version: 3.10
- OS: MacOS 12.4
- V2.2.1

**Additional context**
Console: 
olkosmolko@Olivers-MBP RedditVideoMakerBot-master % python3 main.py
Using Slovakia server backend.

██████╗ ███████╗██████╗ ██████╗ ██╗████████╗    ██╗   ██╗██╗██████╗ ███████╗ ██████╗     ███╗   ███╗ █████╗ ██╗  ██╗███████╗██████╗
██╔══██╗██╔════╝██╔══██╗██╔══██╗██║╚══██╔══╝    ██║   ██║██║██╔══██╗██╔════╝██╔═══██╗    ████╗ ████║██╔══██╗██║ ██╔╝██╔════╝██╔══██╗
██████╔╝█████╗  ██║  ██║██║  ██║██║   ██║       ██║   ██║██║██║  ██║█████╗  ██║   ██║    ██╔████╔██║███████║█████╔╝ █████╗  ██████╔╝
██╔══██╗██╔══╝  ██║  ██║██║  ██║██║   ██║       ╚██╗ ██╔╝██║██║  ██║██╔══╝  ██║   ██║    ██║╚██╔╝██║██╔══██║██╔═██╗ ██╔══╝  ██╔══██╗
██║  ██║███████╗██████╔╝██████╔╝██║   ██║        ╚████╔╝ ██║██████╔╝███████╗╚██████╔╝    ██║ ╚═╝ ██║██║  ██║██║  ██╗███████╗██║  ██║
╚═╝  ╚═╝╚══════╝╚═════╝ ╚═════╝ ╚═╝   ╚═╝         ╚═══╝  ╚═╝╚═════╝ ╚══════╝ ╚═════╝     ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

                                                                                
                                                                                
     Thanks for using this tool! Feel free to contribute to this project on     
   GitHub! If you have any questions, feel free to reach out to me on Twitter   
  or submit a GitHub issue. You can find solutions to many common problems in   
                               the Documentation                                
                                                                                
                                                                                
╭──────────────────────────────────────────────────────────────────────────────╮
│ You are using V2.2.1 of the bot                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
Logging into Reddit.
╭──────────────────────────────────────────────────────────────────────────────╮
│ Getting subreddit threads...                                                 │
╰──────────────────────────────────────────────────────────────────────────────╯
Using subreddit: r/funny from environment variable config
This post was pinned by moderators. Skipping...
This post was pinned by moderators. Skipping...
Video will be: Michael Jordan learning how to shoot from his mom 👍
Thread has 12117 upvotes
Thread has a upvote ratio of 96.0%
Thread has 149 comments
Received subreddit threads Successfully.
╭──────────────────────────────────────────────────────────────────────────────╮
│ Please choose one of the following TTS providers:                            │
╰──────────────────────────────────────────────────────────────────────────────╯
╭─────────────────╮ ╭──────────╮ ╭─────────────────╮ ╭────────╮
│ GoogleTranslate │ │ AWSPolly │ │ StreamlabsPolly │ │ TikTok │
╰─────────────────╯ ╰──────────╯ ╰─────────────────╯ ╰────────╯

2
Unknown Choice
╭──────────────────────────────────────────────────────────────────────────────╮
│ Please choose one of the following TTS providers:                            │
╰──────────────────────────────────────────────────────────────────────────────╯
╭─────────────────╮ ╭──────────╮ ╭─────────────────╮ ╭────────╮
│ GoogleTranslate │ │ AWSPolly │ │ StreamlabsPolly │ │ TikTok │
╰─────────────────╯ ╰──────────╯ ╰─────────────────╯ ╰────────╯

3
Unknown Choice
╭──────────────────────────────────────────────────────────────────────────────╮
│ Please choose one of the following TTS providers:                            │
╰──────────────────────────────────────────────────────────────────────────────╯
╭─────────────────╮ ╭──────────╮ ╭─────────────────╮ ╭────────╮
│ GoogleTranslate │ │ AWSPolly │ │ StreamlabsPolly │ │ TikTok │
╰─────────────────╯ ╰──────────╯ ╰─────────────────╯ ╰────────╯

4
Unknown Choice
╭──────────────────────────────────────────────────────────────────────────────╮
│ Please choose one of the following TTS providers:                            │
╰──────────────────────────────────────────────────────────────────────────────╯
╭─────────────────╮ ╭──────────╮ ╭─────────────────╮ ╭────────╮
│ GoogleTranslate │ │ AWSPolly │ │ StreamlabsPolly │ │ TikTok │
╰─────────────────╯ ╰──────────╯ ╰─────────────────╯ ╰────────╯

1
Unknown Choice
╭──────────────────────────────────────────────────────────────────────────────╮
│ Please choose one of the following TTS providers:                            │
╰──────────────────────────────────────────────────────────────────────────────╯
╭─────────────────╮ ╭──────────╮ ╭─────────────────╮ ╭────────╮
│ GoogleTranslate │ │ AWSPolly │ │ StreamlabsPolly │ │ TikTok │
╰─────────────────╯ ╰──────────╯ ╰─────────────────╯ ╰────────╯

2
Unknown Choice
╭──────────────────────────────────────────────────────────────────────────────╮
│ Please choose one of the following TTS providers:                            │
╰──────────────────────────────────────────────────────────────────────────────╯
╭─────────────────╮ ╭──────────╮ ╭─────────────────╮ ╭────────╮
│ GoogleTranslate │ │ AWSPolly │ │ StreamlabsPolly │ │ TikTok │
╰─────────────────╯ ╰──────────╯ ╰─────────────────╯ ╰────────╯

2
Unknown Choice
╭──────────────────────────────────────────────────────────────────────────────╮
│ Please choose one of the following TTS providers:                            │
╰──────────────────────────────────────────────────────────────────────────────╯
╭─────────────────╮ ╭──────────╮ ╭─────────────────╮ ╭────────╮
│ GoogleTranslate │ │ AWSPolly │ │ StreamlabsPolly │ │ TikTok │
╰─────────────────╯ ╰──────────╯ ╰─────────────────╯ ╰────────╯

2
Unknown Choice
╭──────────────────────────────────────────────────────────────────────────────╮
│ Please choose one of the following TTS providers:                            │
╰──────────────────────────────────────────────────────────────────────────────╯
╭─────────────────╮ ╭──────────╮ ╭─────────────────╮ ╭────────╮
│ GoogleTranslate │ │ AWSPolly │ │ StreamlabsPolly │ │ TikTok │
╰─────────────────╯ ╰──────────╯ ╰─────────────────╯ ╰────────╯

2
Unknown Choice
╭──────────────────────────────────────────────────────────────────────────────╮
│ Please choose one of the following TTS providers:                            │
╰──────────────────────────────────────────────────────────────────────────────╯
╭─────────────────╮ ╭──────────╮ ╭─────────────────╮ ╭────────╮
│ GoogleTranslate │ │ AWSPolly │ │ StreamlabsPolly │ │ TikTok │
╰─────────────────╯ ╰──────────╯ ╰─────────────────╯ ╰────────╯

2
Unknown Choice
╭──────────────────────────────────────────────────────────────────────────────╮
│ Please choose one of the following TTS providers:                            │
╰──────────────────────────────────────────────────────────────────────────────╯
╭─────────────────╮ ╭──────────╮ ╭─────────────────╮ ╭────────╮
│ GoogleTranslate │ │ AWSPolly │ │ StreamlabsPolly │ │ TikTok │
╰─────────────────╯ ╰──────────╯ ╰─────────────────╯ ╰────────╯

GTTS
Unknown Choice
╭──────────────────────────────────────────────────────────────────────────────╮
│ Please choose one of the following TTS providers:                            │
╰──────────────────────────────────────────────────────────────────────────────╯
╭─────────────────╮ ╭──────────╮ ╭─────────────────╮ ╭────────╮
│ GoogleTranslate │ │ AWSPolly │ │ StreamlabsPolly │ │ TikTok │
╰─────────────────╯ ╰──────────╯ ╰─────────────────╯ ╰────────╯

Google
Unknown Choice
╭──────────────────────────────────────────────────────────────────────────────╮
│ Please choose one of the following TTS providers:                            │
╰──────────────────────────────────────────────────────────────────────────────╯
╭─────────────────╮ ╭──────────╮ ╭─────────────────╮ ╭────────╮
│ GoogleTranslate │ │ AWSPolly │ │ StreamlabsPolly │ │ TikTok │
╰─────────────────╯ ╰──────────╯ ╰─────────────────╯ ╰────────╯

GoogleTranslate
╭──────────────────────────────────────────────────────────────────────────────╮
│ Saving Text to MP3 files...                                                  │
╰──────────────────────────────────────────────────────────────────────────────╯
Saving... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3 it/s  
Saved Text to MP3 files successfully.
╭──────────────────────────────────────────────────────────────────────────────╮
│ Downloading screenshots of reddit posts...                                   │
╰──────────────────────────────────────────────────────────────────────────────╯
Launching Headless Browser...
Skipping translation...
Downloading screenshots... ━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  22% 0:01:51
Screenshots downloaded Successfully.
╭──────────────────────────────────────────────────────────────────────────────╮
│ We need to download the backgrounds videos. they are fairly large but it's   │
│ only done once. 😎                                                           │
╰──────────────────────────────────────────────────────────────────────────────╯
Downloading the backgrounds videos... please be patient 🙏 
Downloading parkour.mp4 from https://www.youtube.com/watch?v=n_Dv4JMiwK8
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/olkosmolko/Downloads/RedditVideoMakerBot-master/main.py", line 70, in <module>
    main()
  File "/Users/olkosmolko/Downloads/RedditVideoMakerBot-master/main.py", line 39, in main
    download_background()
  File "/Users/olkosmolko/Downloads/RedditVideoMakerBot-master/video_creation/background.py", line 50, in download_background
    YouTube(uri).streams.filter(res="1080p").first().download(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/__main__.py", line 295, in streams
    self.check_availability()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/__main__.py", line 210, in check_availability
    status, messages = extract.playability_status(self.watch_html)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/__main__.py", line 102, in watch_html
    self._watch_html = request.get(url=self.watch_url)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/request.py", line 53, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

**Comment by JasonLovesDoggo** [comment]
Go to the directory you have python installed in then click install.certificate.command 

If you don't know where you have it installed in Google it

**Comment by smolkoolko** [comment]
TYSM! It works now!
