### ISSUE TITLE
Text-to-speech isn't supported for this language

### ISSUE THREAD

**Issue by MPagliari** [elebumm/RedditVideoMakerBot#810]
**Describe the bug**
I'm getting an issue on a certain Subreddit
https://www.reddit.com/r/AskReddit/comments/vpjri2/what_game_is_so_recognizable_you_only_have_to_say/
I believe this to be the culprit 

[❗ U+2757](https://emojipedia.org/emoji/%E2%9D%97/)

It causes Tiktok TTS to spit out a message:

"speaker":"en_us_001"},"extra":"message":"success","status_code":0,"status_msg":"success"}
{"data":{"s_key":"","v_str":"","duration":"","speaker":""},"extra":{"log_id":"202207021614360100020077350020110C2B912A"},"message":"Text-to-speech isn't
supported for this language","status_code":1,"status_msg":"Text-to-speech isn't supported for this language"}

**To Reproduce**
use this subreddit:
https://www.reddit.com/r/AskReddit/comments/vpjri2/what_game_is_so_recognizable_you_only_have_to_say/
set TTsChoice = Tiktok and voice = ""

**Expected behavior**
I expect [U+2757] to be replaced with "!" or any subreddit that causes message: "Text-to-speech isn't supported for this language"
to be skipped

**Screenshots**
![image](https://user-images.githubusercontent.com/1887228/177008601-c7558899-1967-4ac9-9047-bf374a3a355e.png)
![image](https://user-images.githubusercontent.com/1887228/177008639-924aeafa-b956-412c-8724-dfc3f61814bf.png)

**System (please complete the following information):**

- Python 3.10.5
- OS: Windows 10 Version	10.0.19044 Build 19044

- App version / Branch [e.g. latest, V2.0, master, develop ]
BOT VERSION = 2.1

**Comment by MPagliari** [comment]
Tested on latest bot V2.2.1

Error output is different but other subreddits are working just this one about recognizable video games is not
![image](https://user-images.githubusercontent.com/1887228/177009536-78eb04f6-ba55-4205-a6d1-d96e4ff6ca49.png)

**Comment by Ohmnito** [comment]
Solution for this here: #806
