### ISSUE TITLE
I need help by setup

### ISSUE THREAD

**Issue by Ayley** [elebumm/RedditVideoMakerBot#812]
I dont understand what i have to choose at the following options.

TTSCHOICE
TIKTOK_VOICE
STREAMLABS_VOICE
AWS_VOICE
POSTLANG
POST_ID
REDDIT_CLIENT_ID
REDDIT_CLIENT_SECRET

**Comment by Ohmnito** [comment]
For
REDDIT_CLIENT_ID
REDDIT_CLIENT_SECRET

go to https://www.reddit.com/prefs/apps and at the bottom of the page click on "create another app". Enter a name for the app (whatever you want) click on "script" and add a URL for "redirect URI" (like your Twitter or anything like that).
It will then create an app with 2 important Infos:
1) a "personal use script" that you will copy and paste for the  REDDIT_CLIENT_ID field
2) a "secret" code that you will copy and paste for the  REDDIT_CLIENT_SECRET field

for POST_ID enter the 6 characters of the post URL (the 6 characters after /comments/)  if you want to make a video from a specific post.

for POSTLANG is only for translation, don't put anything if your post, this is only if you want to translate the comments to another language.

for
TTSCHOICE this is where you choose the tts engine between gtts, aws_polly, streamlabs_polly or tiktok

choose a voice here if you chose one of these tts engine. For more info about what voices are available, go to the TTS folder.
TIKTOK_VOICE 
STREAMLABS_VOICE
AWS_VOICE
