### ISSUE TITLE
Fails on last part 

### ISSUE THREAD

**Issue by noubyg** [elebumm/RedditVideoMakerBot#814]
![cap](https://user-images.githubusercontent.com/47767192/177019156-48245d00-ac10-48ba-be43-f130b6d839be.PNG)

**Comment by vitviki** [comment]
Hey, can you change the TTS to TikTok and see if it works? In few cases Polly hasn't been working as it should be.

**Comment by JasonLovesDoggo** [comment]
Fixed in develop
