### ISSUE TITLE
main.py opens for a sec then closes

### ISSUE THREAD

**Issue by qwertynotavailable** [elebumm/RedditVideoMakerBot#816]
When I try to open main.py it only opens for less than a second.

Please help me but be specific because I am new.

**Comment by CordlessCoder** [comment]
Actually follow the docs, run main.py ina terminal and actually send the error.

**Comment by qwertynotavailable** [comment]
> Actually follow the docs, run main.py ina terminal and actually send the error.

is that for mac? i am on windows 10

**Comment by CordlessCoder** [comment]
> > Actually follow the docs, run main.py ina terminal and actually send the error.
> 
> is that for mac? i am on windows 10

Follow the docs. It's not for Mac.

**Comment by CordlessCoder** [comment]
https://github.com/elebumm/RedditVideoMakerBot#installation-

**Comment by CordlessCoder** [comment]
It's literally right there

**Comment by Pavloskaza** [comment]
> Actually follow the docs, run main.py ina terminal and actually send the error.

Traceback (most recent call last):
  File "Z:\RedditVideoMakerBot-master\main.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by CordlessCoder** [comment]
You didn't install the requirements.
Do step 3 & 4 before step 2
