### ISSUE TITLE
mutagen.MutagenError: [Errno 2] No such file or directory: 'assets/temp/mp3/title.mp3'

### ISSUE THREAD

**Issue by IslaFTW** [elebumm/RedditVideoMakerBot#821]
Thread = vpinmz
TTS Provides = TikTok or StreamlabsPolly

For StreamlabsPolly im using = Enrique
For TikTok im using = es_mx_002

![image](https://user-images.githubusercontent.com/60049112/177028220-81fb8370-c3ff-491e-887f-f0b3293d3a91.png)

**Comment by muhammedaksam** [comment]
I am having same issue with StreamlabsPolly. I am trying to fix it.

**Comment by LiranTheGameMaker** [comment]
@muhammedaksam did you succeed?

**Comment by muhammedaksam** [comment]
> @muhammedaksam did you succeed?

Unfortunately, no. I can't figure out what's wrong. Checked previous versions and couldn't find any difference.

**Comment by LiranTheGameMaker** [comment]
When is the next release that will have this patched, based on your approximates?

**Comment by JasonLovesDoggo** [comment]
Fixed in develop

**Comment by washeido** [comment]
> Fixed in develop

As a noobie, i don't know what you mean by "fixed in develop".  Would you be so kind to clarify?
