### ISSUE TITLE
MoviePy calling wrong folder

### ISSUE THREAD

**Issue by mxgmr** [elebumm/RedditVideoMakerBot#822]
While creating the video, MoviePy asks for assets/mp3/ , this folder doesn't exists, because audios are saved on assets/temp/mp3

<img width="895" alt="Captura de Pantalla 2022-07-03 a la(s) 1 57 26 a m" src="https://user-images.githubusercontent.com/99062438/177028787-3e5b98a8-e165-42d4-976e-9b9960fedb99.png">

Line 47 on final_video.py asks for the wrong folder, it should be assets/temp/mp3

<img width="719" alt="Captura de Pantalla 2022-07-03 a la(s) 1 58 56 a m" src="https://user-images.githubusercontent.com/99062438/177028840-e16ab7b3-68fe-4f5c-8f04-4e2ec5e41428.png">

SOLUTION:
Just change line 47 with:
audio_clips = [AudioFileClip(f"assets/temp/mp3/{i}.mp3") for i in range(number_of_clips)]

**Comment by muhammedaksam** [comment]
This issue fixed with #803. Make sure to fetch.
