### ISSUE TITLE
401 HTTP Response Error (prawcore.exceptions.ResponseException)

### ISSUE THREAD

**Issue by ZelKed** [elebumm/RedditVideoMakerBot#825]
![image](https://user-images.githubusercontent.com/76404202/177043458-bd41c567-c9b5-4f7d-a4b9-e6164d964267.png)

**Comment by B1GJ** [comment]
Probably something to do with u not giving the correct credentials for the reddit API to work and that's why you're getting a 401 unauthorized.
Check if you entered all the correct credentials in the .env file

**Comment by JasonLovesDoggo** [comment]
What the second comment said
