### ISSUE TITLE
Error when creating screenshots of posts

### ISSUE THREAD

**Issue by Whiskey-Bravo** [elebumm/RedditVideoMakerBot#826]
**Describe the bug**
The bot runs fine until it takes the screenshots. It tells me: "C:\Users\user\AppData\Local\ms-playwright\chromium-1012\chrome-win\chrome.exe" And after that error it tells me that Playwright was just installed or updated and that I should run "playwright install".
But that doesn't work either.

**To Reproduce**
I don't know how to reproduce it, it just happens when I run it with python main.py

**Expected behavior**
It should continue making the video.

**Screenshots**
The error:
![Error](https://user-images.githubusercontent.com/86281016/177043964-dda1d9a0-58f5-4397-980f-367af4a4e4c1.png)

The "playwright install" thing:
![image](https://user-images.githubusercontent.com/86281016/177044005-6131d381-ce9f-4c7c-b6f7-d17de11c36bf.png)

When I try to run the "playwright install" command it tells me that the command does not exist.

**System:**

- Python Version: Python 3.9.13
- OS: Windows 11
- App version: 2.2.1 
- Branch: master

**Comment by muhammedaksam** [comment]
You should run `python -m playwright install` through your terminal.
