### ISSUE TITLE
Does this work on linux? 

### ISSUE THREAD

**Issue by PrismFlux** [elebumm/RedditVideoMakerBot#828]
See titlem

**Comment by rastogiujj12** [comment]
yes

**Comment by CallumIO** [comment]
Need more info please @PrismFlux 
If you are on ubuntu, it's trivial - same goes for most Debian based distros
On Arch/Fedora/SUSE its more involved due to playwright

**Comment by micziz** [comment]
Yes! As long as you follow the steps you are good.

**Comment by PrismFlux** [comment]
@CallumIO i'm on debian :D

**Comment by PrismFlux** [comment]
can someone please explain to me how i install the programm and run it on debian?

**Comment by CordlessCoder** [comment]
@PrismFlux its identical to any other platform. You ensure you have python installed and follow the installation steps in the README
