### ISSUE TITLE
Not working the code is broken

### ISSUE THREAD

**Issue by kunjbosamia** [elebumm/RedditVideoMakerBot#833]
**on runnig python main.py I am getting this output**

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "/home/kunj/kunj bosamia/one more redit video make/RedditVideoMakerBot/reddit/subreddit.py", line 9, in <module>
    from utils.videos import check_done
  File "/home/kunj/kunj bosamia/one more redit video make/RedditVideoMakerBot/utils/videos.py", line 12, in <module>
    redditobj: dict[str],
TypeError: 'type' object is not subscriptable

**To Reproduce**
run the program by entering this command - python main.py 

**Expected behavior**
should generate the video in results folder

- Python Version: [e.g. Python 3.8]
- OS: ubuntu
- App version - latest

**Comment by B1GJ** [comment]
It's some stuff with type hinting that only works on python 3.9+ versions I think. 
To fix it you can add `from __future__ import annotations` at the top of every python file where you get this error/type hinting is used or you can upgrade to python 3.9+

**Comment by durlabhs10** [comment]
I also got the same error, but was fixed once I upgraded python 3.10

**Comment by micziz** [comment]
The merging of the jason fork pushed the version requirement from 3.6 to 3.9. Try following this guide to install the latest version https://www.makeuseof.com/install-python-ubuntu/.  Also check this out https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa.

**Comment by JasonLovesDoggo** [comment]
> The merging of the jason fork pushed the version requirement from 3.6 to 3.9. Try following this guide to install the latest version https://www.makeuseof.com/install-python-ubuntu/.  Also check this out https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa.

Actually it wasn't the merging of my fork that caused that just an FYI
