### ISSUE TITLE
this is a question

### ISSUE THREAD

**Issue by haldoytest** [elebumm/RedditVideoMakerBot#838]
Why are you using reddit api
You need playwright to take screenshot of thread
so why not use use playwright to grab random thread and avoid reddit api
can you explain why not just use playwright and avoid using reddit api

**Comment by micziz** [comment]
I think what he meant is why cant we just use playwright...

Playwrigth is a headless browser. It gets a link, and then it screenshots. It cannot click on a random thread to get the link to screenshot it. So the reedit API is needed. Plus, even if it was possible it would take more time.

**Comment by JasonLovesDoggo** [comment]
Kind of what the other two people said but not really The reason you need praw is to get the actual text of the post for the TTS engine to use.
It's also a lot faster for the thread randomness
