### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Weemizo** [elebumm/RedditVideoMakerBot#839]
![image](https://user-images.githubusercontent.com/60063669/177127115-674ad5e0-0920-4c71-94d9-93e5c0b8cf64.png)

**Comment by Weemizo** [comment]
and i chose Brian as the TTS for aws, streamlabs polly

**Comment by muhammedaksam** [comment]
This issue is fixed with #836. You can change your files for now.

**Comment by micziz** [comment]
It cannot find the config file... Will look more into it.

**Comment by JasonLovesDoggo** [comment]
#848
