### ISSUE TITLE
No module named 'reddit.subreddit'

### ISSUE THREAD

**Issue by ParrotInTheGarden** [elebumm/RedditVideoMakerBot#840]
i am getting this error when i try to run main.py 

 File "main.py", line 6, in <module>
    from reddit.subreddit import get_subreddit_threads
ModuleNotFoundError: No module named 'reddit.subreddit'

**Comment by micziz** [comment]
I cannot solve this if you give me more info.

**Comment by ParrotInTheGarden** [comment]
> I cannot solve this if you dont give me more info.

what info do you need?

**Comment by JasonLovesDoggo** [comment]
> I cannot solve this if you dont give me more info.

Well I don't know about you but I can

**Comment by JasonLovesDoggo** [comment]
Add an empty `__init__.py` file In reddit directory
