### ISSUE TITLE
Program not working

### ISSUE THREAD

**Issue by AfnanDanish** [elebumm/RedditVideoMakerBot#841]
Gives me an error in the terminal after #836, sorry I'm really new to Git so If I'm missing something do point it out please. Thank
![Screenshot 2022-07-04 165914](https://user-images.githubusercontent.com/100599203/177150688-c9ba3fc4-ce89-47b3-b313-12a70ca0ba3e.png)
s

**Comment by micziz** [comment]
You need to install sox. Since it's not in the `requirements.txt`, you will need to install it by yourself...

```
pip3 install sox
```

Check out this http://sox.sourceforge.net/

**Comment by AfnanDanish** [comment]
@micziz Thanks man that worked.
