### ISSUE TITLE
issue using polly

### ISSUE THREAD

**Issue by thetiger2131** [elebumm/RedditVideoMakerBot#842]
i dont know what is triggering this but its prolly something ive configured wrong in .env. every time i select awspolly as a tts it  
says config file not found. i dont know why this is happening or what ive done wrong. ill just let you look at the screenshot i took
![Capture](https://user-images.githubusercontent.com/108672806/177152378-064add2a-7dbc-4612-ae1a-3bd5564d8559.PNG)
.

**Comment by micziz** [comment]
#836

**Comment by JasonLovesDoggo** [comment]
Wrong what the other person said
But #838
