### ISSUE TITLE
config profile (polly) could not be found

### ISSUE THREAD

**Issue by vitviki** [elebumm/RedditVideoMakerBot#848]
Getting the following error when using AWS_Polly

> .local/lib/python3.10/site-packages/botocore/session.py", line 404, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (polly) could not be found

It's crashing while executing `session = Session(profile_name="polly")`

**Comment by muhammedaksam** [comment]
It's probably related to #836 as well. It's not getting merged yet. But you can change your files manually for now.

**Comment by JasonLovesDoggo** [comment]
nope aws Polly requires an AWS account. 
use streamlabs polly to bypass the account
