### ISSUE TITLE
i got an error

### ISSUE THREAD

**Issue by PrismFlux** [elebumm/RedditVideoMakerBot#850]
File "main.py", line 20
SyntaxError: Non-ASCII character '\xe2' in file main.py on line 21, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

is the output when im running main.py
using debian

**Comment by PrismFlux** [comment]
nvm i fixed it by typing python3.9 instead of python ,but how do i setup a reddit app as a "script"?

**Comment by JasonLovesDoggo** [comment]
Read the docs
