### ISSUE TITLE
The user name cannot contain the character '-'

### ISSUE THREAD

**Issue by vitozyf** [elebumm/RedditVideoMakerBot#851]
**Describe the bug**
The user name cannot contain the character '-'

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**

- Python Version: [e.g. Python 3.6]
- OS: [e.g. Windows 11]
- App version / Branch [e.g. latest, V2.0, master, develop ]

**Additional context**

**Comment by muhammedaksam** [comment]
This is fixed with #823. Make sure to fetch it.
