### ISSUE TITLE
Word blacklist

### ISSUE THREAD

**Issue by UpFault** [elebumm/RedditVideoMakerBot#852]
Check the contents of the post and it’s comments for black listed words, certain words may cause the removal of posts on tt platform

**Comment by JasonLovesDoggo** [comment]
Good idea

**Comment by Niellles** [comment]
Splitting the text at the blacklisted word and then inserting a beep in between the audio seems the easiest way to go about this.

An improved version would be specifying the length of the beep in the blacklist configuration.

**Comment by Niellles** [comment]
Similar to #407.

**Comment by JasonLovesDoggo** [comment]
Yep
