### ISSUE TITLE
codec error

### ISSUE THREAD

**Issue by Ahrizze** [elebumm/RedditVideoMakerBot#865]
**Describe the bug**
Im having a bug with the codecs (i think), and it is 99% probability not a bug, just me doing something wrong c:

**To Reproduce**
user@user MINGW64 /h/bash2/RedditVideoMakerBot (master)
$ python main.py
Using Spain server backend.
Traceback (most recent call last):
  File "H:\bash2\RedditVideoMakerBot\main.py", line 18, in <module>
    print(
  File "H:\movidasbash\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 2-8: character maps to <undefined>

user@user MINGW64 /h/bash2/RedditVideoMakerBot (master)
$ python3 main.py
Traceback (most recent call last):
  File "H:\bash2\RedditVideoMakerBot\main.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

(idk if it matters but its not the same if i execute python and python3, im just a html/css/js starter noob so i didnt started with python yet)

**Expected behavior**
It should run the main.py as normal, printing the cool logo, but it appears that

**System (please complete the following information):**

- Python Version: 3.10
- OS: Windows 10

Sorry for the troubles if its something im doing wrong and thanks for your time c:

**Comment by muhammedaksam** [comment]
`python -m pip install python-dotenv`

**Comment by Ahrizze** [comment]
thanks! @muhammedaksam i will try it!!
