### ISSUE TITLE
the bot is making video longer then 60 second

### ISSUE THREAD

**Issue by Sadid57** [elebumm/RedditVideoMakerBot#869]
![Screenshot 2022-07-06 195745](https://user-images.githubusercontent.com/108466620/177567660-89646488-c225-44f4-b690-bd2e4c07eedf.png)

**Comment by William9923** [comment]
Hi @Sadid57 , yes currently the bot check whether the final video is more than the default max length (50) when adding clips for the final video. 
in the next improvement it will be, thus solving this issue 🙏 
```if length + nextcliplength >= maxlength
then dont include next clip
```

**Comment by matichek** [comment]
Yes, I have the same
