### ISSUE TITLE
SoXI error code 1 

### ISSUE THREAD

**Issue by Redditor293** [elebumm/RedditVideoMakerBot#873]
When running TikTok voice or any other than Google Translate , this error comes up

Run with different voice

Expected to work as usual 

**Screenshots**

**System (please complete the following information):**

- Python Version: 3.10
- OS: Windows 10 
- 
- ![image_2022-07-06_173144799](https://user-images.githubusercontent.com/108824152/177599454-c1158844-1a66-4ca7-89ad-da645eed1a2e.png)

- App version / Branch : V 2.2.2
**Additional context**

**Comment by JasonLovesDoggo** [comment]
Fixed in develop
