### ISSUE TITLE
Error when Running | TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by RedrcknRbn** [elebumm/RedditVideoMakerBot#874]
**Describe the bug**
The following error comes up when attempting to run:
`Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "/home/runner/RedditVideoMakerBot/reddit/subreddit.py", line 9, in <module>
    from utils.videos import check_done
  File "/home/runner/RedditVideoMakerBot/utils/videos.py", line 12, in <module>
    redditobj: dict[str],
TypeError: 'type' object is not subscriptable`

**Expected behavior**
I had expected the program to succeed running.

**Screenshots**
![image](https://user-images.githubusercontent.com/63996530/177607379-cd448c3a-5f2f-4813-951c-f1f1be9781c2.png)

**System:**

- Python Version: Python 3.7.4
- OS: Replit Website - Linux Ubuntu (Unknown Version)
- App version / Branch: Latest

**Comment by Niellles** [comment]
Same here when on master, develop branch works.

Will try and investigate when I get the time.

**Comment by JasonLovesDoggo** [comment]
Give me 15 minutes to fix and push to develop

**Comment by RedrcknRbn** [comment]
This issue is still happening

**Comment by RedrcknRbn** [comment]
` python3 main.py
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "/home/runner/RedditVideoMakerBot/reddit/subreddit.py", line 9, in <module>
    from utils.videos import check_done
  File "/home/runner/RedditVideoMakerBot/utils/videos.py", line 12, in <module>
    redditobj: dict[str],
TypeError: 'type' object is not subscriptable`

**Comment by JasonLovesDoggo** [comment]
fixed in develop. use develop.
