### ISSUE TITLE
Add the ability to generate the video with 1 command with args

### ISSUE THREAD

**Issue by pintermor9** [elebumm/RedditVideoMakerBot#876]
**Is your feature request related to a problem? Please describe.**
That it takes long to do the interactions or always change the .env file

**Describe the solution you'd like**
That I don't have to mess with env vars. 
For eg. I could just generate a video by doing:
`py main.py --subreddit AskReddit --theme light`

**Describe alternatives you've considered** (optional)

**Additional context** (optional)

**Comment by JasonLovesDoggo** [comment]
I mean you anyways have to use the .env file for credentials and stuff so this is kind of Meh A command line interface should be implemented in the future though
