### ISSUE TITLE
Create an option for the script to read a reddit story.

### ISSUE THREAD

**Issue by Denotess** [elebumm/RedditVideoMakerBot#88]
The script wouldnt read multiple comments of the thread, it would just read the story and automatically adjust the video length.

**Comment by JasonLovesDoggo** [comment]
storymode

**Comment by ParkerDaudt** [comment]
Was storymode properly implemented? I see that the .config.template.toml file describes it as not yet implemented

**Comment by JasonLovesDoggo** [comment]
> Was storymode implemented? I see that the .config.template.toml file describes it as not yet implemented

No but this was a duplicate
