### ISSUE TITLE
2.2.2 makes unnecessary long videos

### ISSUE THREAD

**Issue by CJthisis** [elebumm/RedditVideoMakerBot#882]
**Describe the bug**
At the end of nearly every video I created with 2.2.2, after the last comment has been read, there are a few seconds of video that don't need to be there. 

**To Reproduce**
Just use the master version of 2.2.2, this didn't happen with 2.1.

**Expected behavior**
Every video should be cut of when there is no more comments to read.

This video was made with 2.2.2:

https://user-images.githubusercontent.com/99442347/177735147-262928d9-5823-4ea0-af67-6c0be5e80651.mp4

This video was made with 2.1:

https://user-images.githubusercontent.com/99442347/177735985-68a5fb15-cf6a-41bc-8381-7b5071480cba.mp4

**Comment by William9923** [comment]
related #869
