### ISSUE TITLE
bash: pip: command not found

### ISSUE THREAD

**Issue by wimpyadhesive** [elebumm/RedditVideoMakerBot#889]
I cloned the repository and the pip command isnt working, any help would be appreciated
![image](https://user-images.githubusercontent.com/108883964/177800180-dd8d12b0-0b70-4598-9125-f17479c1c64b.png)

**Comment by CordlessCoder** [comment]
Install python with pip. No one ever claimed cloning the repo will magically install pip

**Comment by wimpyadhesive** [comment]
> Install python with pip. No one ever claimed cloning the repo will magically install pip

Sorry, I don't have a lot of coding knowledge. Thank you

**Comment by wimpyadhesive** [comment]
The reason it wasn't working is because I was dumb and had to install python directly from the windows store
