### ISSUE TITLE
Error running Main.py

### ISSUE THREAD

**Issue by realdav2** [elebumm/RedditVideoMakerBot#89]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/106691949/171460988-68b9d72b-d20c-47b5-a66e-3ff4352aa425.png">

Apart from that I don't know if my client ID is right since I can't find any and it seems its the same as the secret key and how am I supposed to name the .env file ? cause osx you can't name .env is invalid ( idk im very very new to phyton)

**Comment by twannieboyy** [comment]
reinstalling what?
