### ISSUE TITLE
[Error] playwright._impl._api_types.Error: Browser closed. 

### ISSUE THREAD

**Issue by AllHighOnly** [elebumm/RedditVideoMakerBot#890]
I have installed all the requirements and set up the .env file succesfully, but then I got this error:

`playwright._impl._api_types.Error: Browser closed.`

Chrome is just open so not sure whats wrong...

- Python Version: 3.10
- OS: MacOS Big Sur
- App version / Branch: Latest

**Comment by William9923** [comment]
Please give us the full error logs. Cannot identify whats the problem. Thanks

**Comment by AllHighOnly** [comment]
Sorry for late response, here it is:
`│ Downloading screenshots of reddit posts...                                   │
╰──────────────────────────────────────────────────────────────────────────────╯
Launching Headless Browser...
Traceback (most recent call last):
  File "/Users/Mac/Downloads/RedditVideoMakerBot-2.2.2/main.py", line 70, in <module>
    main()
  File "/Users/Mac/Downloads/RedditVideoMakerBot-2.2.2/main.py", line 38, in main
    download_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "/Users/Mac/Downloads/RedditVideoMakerBot-2.2.2/video_creation/screenshot_downloader.py", line 35, in download_screenshots_of_reddit_posts
    browser = p.chromium.launch()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 11433, in launch
    self._sync(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 89, in _sync
    return task.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/playwright/_impl/_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 370, in _
    return await result
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser closed.
==================== Browser output: ====================
<launching> /Users/Mac/Library/Caches/ms-playwright/chromium-1012/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/var/folders/wk/ys668bkx42zfmfchnjrjp6xm0000gn/T/playwright_chromiumdev_profile-dq6YFm --remote-debugging-pipe --no-startup-window
<launched> pid=11403
[pid=11403][err] dlopen /Users/Mac/Library/Caches/ms-playwright/chromium-1012/chrome-mac/Chromium.app/Contents/MacOS/../Frameworks/Chromium Framework.framework/Versions/104.0.5112.20/Chromium Framework: dlopen(/Users/Mac/Library/Caches/ms-playwright/chromium-1012/chrome-mac/Chromium.app/Contents/MacOS/../Frameworks/Chromium Framework.framework/Versions/104.0.5112.20/Chromium Framework, 261): image not found.
[pid=11403] <process did exit: exitCode=null, signal=SIGABRT>
[pid=11403] starting temporary directories cleanup
=========================== logs ===========================
<launching> /Users/Mac/Library/Caches/ms-playwright/chromium-1012/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/var/folders/wk/ys668bkx42zfmfchnjrjp6xm0000gn/T/playwright_chromiumdev_profile-dq6YFm --remote-debugging-pipe --no-startup-window
<launched> pid=11403
[pid=11403][err] dlopen /Users/Mac/Library/Caches/ms-playwright/chromium-1012/chrome-mac/Chromium.app/Contents/MacOS/../Frameworks/Chromium Framework.framework/Versions/104.0.5112.20/Chromium Framework: dlopen(/Users/kayalsido/Library/Caches/ms-playwright/chromium-1012/chrome-mac/Chromium.app/Contents/MacOS/../Frameworks/Chromium Framework.framework/Versions/104.0.5112.20/Chromium Framework, 261): image not found.
[pid=11403] <process did exit: exitCode=null, signal=SIGABRT>
[pid=11403] starting temporary directories cleanup`

**Comment by William9923** [comment]
Hi, to make sure are you running in a docker? 
If yes, i think its a known issue [ref](https://stackoverflow.com/questions/69472876/cannot-run-playwright-inside-docker-image)
If not, you should run the installation of dependencies:
- `playwright install-deps` or
- `python -m playwright install-deps`

**Comment by AllHighOnly** [comment]
> Hi, to make sure are you running in a docker? If yes, i think its a known issue [ref](https://stackoverflow.com/questions/69472876/cannot-run-playwright-inside-docker-image) If not, you should run the installation of dependencies:
> 
>     * `playwright install-deps` or
> 
>     * `python -m playwright install-deps`

I tried these:
`playwright install-deps`
`python3.10 -m playwright install-deps`
But i still get the same error :(

**Comment by ORI299** [comment]
did you solve it?

**Comment by AllHighOnly** [comment]
Nope, I quit trying Op 17 jul 2023 om 00:14 heeft ORI299 ***@***.***> het volgende geschreven:﻿
did you solve it?
