### ISSUE TITLE
Received 401 HTTP Response

### ISSUE THREAD

**Issue by wimpyadhesive** [elebumm/RedditVideoMakerBot#892]
When I run 'python main.py' it says this:
![image](https://user-images.githubusercontent.com/108883964/177826017-b63b9613-621d-49a6-90f4-90fae4da511e.png)
It says it cannot find the .env.template file but I had to rename it to .env because if I didn't it started asking me a bunch of questions that were already on the template. I don't know if this is relevant or not but it also says "Import "dontev" could not be resolved" in the problems section of the terminal even though I already installed dontev.

**Comment by wimpyadhesive** [comment]
I had to save the .env file

**Comment by knight753951** [comment]
I can not find .env file,help

**Comment by CordlessCoder** [comment]
> I can not find .env file,help

Bexause it doesn't exist. Just start the bot without touching files and it'll ask you to input the values interactively.
