### ISSUE TITLE
ffmpeg error. (Moviepy error: failed to read the duration of file assets/ ....)

### ISSUE THREAD

**Issue by Aztra9** [elebumm/RedditVideoMakerBot#896]
this happens and I have looked at other issues like this and they did not help anyone know what to do
![Error9](https://user-images.githubusercontent.com/77209267/177898941-c0b490d3-96ee-406d-9c5a-19ca9cfd47ea.PNG)

**Comment by JasonLovesDoggo** [comment]
@CallumIO

**Comment by William9923** [comment]
hi @dasbts , if possible could you also open a PR for this and explain your solution. Would be a great contribution for us 🙏

**Comment by JasonLovesDoggo** [comment]
> hi @dasbts , if possible could you also open a PR for this and explain your solution. Would be a great contribution for us 🙏  

Yeah they all just using the solution I told them to I believe

It's already fixed in the third branch

**Comment by JasonLovesDoggo** [comment]
fixed in feat/background-audio
