### ISSUE TITLE
How do you go from an older version to a later one ?

### ISSUE THREAD

**Issue by Kawaso** [elebumm/RedditVideoMakerBot#898]
I am sorry if this is a bad question or something but I am pretty new to this and I don't really know how this works . 
So for example when you will add that it can add music in the background if i already have the script what should i do to get the newer version ?

**Comment by Kawaso** [comment]
I have another question i don't quite understand how to find my reddit client ID

**Comment by JasonLovesDoggo** [comment]
I am having some major problems adding background audio see the third branch though for my progress

**Comment by reneeqytan** [comment]
@Kawaso For your second question, your Reddit Client ID can be found **at the bottom of https://www.reddit.com/prefs/apps page.** You have to actually make a Reddit App first, though. After you've done that, I've attached a diagram of where you can find the Client ID.

<img width="1431" alt="Screen Shot 2022-07-08 at 5 29 07 pm" src="https://user-images.githubusercontent.com/104421279/177963182-3d7b09a1-44fe-4209-967c-73b0e15cf2a0.png">
