### ISSUE TITLE
Not sure what happerned was working 10 minutes ago now wont run, is the most recent version

### ISSUE THREAD

**Issue by jordan1121** [elebumm/RedditVideoMakerBot#899]
![capture 1](https://user-images.githubusercontent.com/106795034/177939649-8166230b-67fd-4604-823c-078da5b316ec.PNG)
Looked for a similar bug report but couldn't find anything helpful

**Comment by reneeqytan** [comment]
Have you modified the number of times it runs? If you did, try setting it back to default. 

References to the `number_of_comments` and `TIMES_TO_RUN` shows up quite a lot of times in the errors.

**Comment by jordan1121** [comment]
Thanks seemed to  be an issue with both time to run and opacity
