### ISSUE TITLE
Playwright error

### ISSUE THREAD

**Issue by VSPuzzler** [elebumm/RedditVideoMakerBot#903]
I get this error when running the code:
![image](https://user-images.githubusercontent.com/79369814/178024983-fbd569a5-ca9f-4989-92b1-86c256994fd6.png)
I looked up this error and wasn't able to find a solution. For those who came across this problem, how did you fix it?

**Comment by William9923** [comment]
mm as the error said, just `playwright install` or `python -m playwright install`. Follow the guide.

**Comment by VSPuzzler** [comment]
Thank you, the second command worked for me!
