### ISSUE TITLE
Enhancement in README.md for beginners.

### ISSUE THREAD

**Issue by JeelTikiwala** [elebumm/RedditVideoMakerBot#907]
Should markdown to write client_id and client_secret in subreddit.py file from reddit script app in detail.

**Comment by CordlessCoder** [comment]
Actually write a detailed explanation of the issue/proposed fixes, this "issue" is worthless

**Comment by 16aces** [comment]
I agree with the OP, it seems like a lot of these bug reports would go away with some basic info/links added to the read me and the .env Template file.

**Comment by CordlessCoder** [comment]
> I agree with the OP, it seems like a lot of these bug reports would go away with some basic info/links added to the read me and the .env Template file.

Just so you know, .env is gone, we switched to TOML(in the develop branch for now)
