### ISSUE TITLE
Code not running

### ISSUE THREAD

**Issue by d7jxfe** [elebumm/RedditVideoMakerBot#909]
**Describe the bug**
prawcore.exceptions.NotFound: received 404 HTTP response

**Comment by William9923** [comment]
Hi, 404 (Not Found) occurs if the bot unable to access Reddit.
Make sure you have:
1. Good internet connection
2.  Reddit is not blocked in your country
Big thanks 🙏

**Comment by JasonLovesDoggo** [comment]
Or If you put the subreddit name wrong
