### ISSUE TITLE
Midtier PC how long does it take ? 

### ISSUE THREAD

**Issue by realdav2** [elebumm/RedditVideoMakerBot#91]
So it shows  me in my task manager it uses 95-100%cpu but on intel power gadget it only shows me it uses 15%. I am using a MacBook Pro and its like already 15 min in the job and only got 9% done 
<img width="614" alt="image" src="https://user-images.githubusercontent.com/106691949/171468336-d840c4d4-2ba7-41b0-8b74-6f2a48a898ed.png">

Is it normal ti takes so long or is it just my pc with is complete garbage 

<img width="390" alt="image" src="https://user-images.githubusercontent.com/106691949/171468465-dd3e54ba-aef5-4551-8c95-74c905a7a135.png">

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/106691949/171468591-e53e3abd-8278-4287-8e42-c569c3e19c81.png">

**Comment by elebumm** [comment]
I believe MoviePy takes a little while to do things. On average it takes me around 4-5 minutes to render out the final video. 

See this: https://zulko.github.io/moviepy/getting_started/efficient_moviepy.html

To see if you can go into the code and improve performance :)

**Comment by realdav2** [comment]
sadly I have no idea how to do that and sadly I have my editing pc packed right now for moving house bin around 40 min 11% so far im using an i5 mbp
