### ISSUE TITLE
Not installing dependencies (requirements.txt)

### ISSUE THREAD

**Issue by AussieSLA** [elebumm/RedditVideoMakerBot#911]
Import "dotenv" could not be resolved

Import "boto3" could not be resolved

Import "botocore.exceptions" could not be resolved

i have these errors - please can you give me a more in depth way to use this code as i do not understand all of it ;)

thanks

**Comment by William9923** [comment]
Follow the guide. Install the `requirements.txt` using either one of this command:
- `pip install -r requirements.txt`
- `python -m pip install -r requirements.txt`

**Comment by JeelTikiwala** [comment]
Try to install single dependencies which are giving the errors.
