### ISSUE TITLE
Video is not synced to text properly

### ISSUE THREAD

**Issue by DustEyezz** [elebumm/RedditVideoMakerBot#914]
I used the TikTok voice. Everything seemed fine until a long comment appeared. Afterwards everything was all over the place with TTS reading random comments. Once gave me an error along the lines of (could not sync audio to video) although I cannot replicate it. 
TTS: TikTok
Character limit : 1200
Python 3.10.5
Master Branch 09.07.2022 (day of the issue being opened)

**Comment by dasbts** [comment]
Yeah I have many results where it just skips a lot of the comment if it's a long comment. The devs told me in Discord that they are going to go through the splitting functionality again.

**Comment by JasonLovesDoggo** [comment]
Should be fixed now
