### ISSUE TITLE
Manual moving of downloaded assets required for different backgrounds of different topics

### ISSUE THREAD

**Issue by dasbts** [elebumm/RedditVideoMakerBot#917]
**Describe the bug**
Having different backgrounds for different ideas doesn't work if you don't move already downloaded backgrounds out of the assets. 

**To Reproduce**
Download let's say 5 backgrounds, then change the background.py into having only 1-2 backgrounds (with different links than the first run), this time the following code will think that it already has enough videos downloaded as it only checks the length of the folder contents, not the actual contents: 
```
    if not len(listdir("./assets/backgrounds")) >= len(
        background_options
    ):
```
Then it will start using whatever is in there instead of downloading the new videos. 

**Expected behavior**
I was hoping it would look through the file names (or the link names might even be better) of the background_options list rather than just the length of the folder contents. 
My current solution is to just move the files out of the backgrounds folder and into a custom named folder to keep track of the different ideas, same for the background.py which I now manually change. 

**System (please complete the following information):**
- Python Version: Python 3.9 (Pretty sure it's the same on any version)
- OS: Windows 10 (Pretty sure it's the same on any OS)
- App version / Branch: latest develop

**Comment by JasonLovesDoggo** [comment]
This is the intended behavior
I'm sorry but if you manually editing stuff you have enough expertise to be able to copy a file over

**Comment by JasonLovesDoggo** [comment]
This is so you don't have to manually add every video to YouTube if you want to have more than the specified backgrounds
