### ISSUE TITLE
Getting stuck on colab 

### ISSUE THREAD

**Issue by belimitless-xd** [elebumm/RedditVideoMakerBot#918]
I'm trying running this script on google colab, so far i have install everything successfully  , but at the end the script is getting stuck.

![image](https://user-images.githubusercontent.com/66120346/178111300-97d99767-4537-4ceb-98a0-54661aa97e04.png)

**Comment by William9923** [comment]
hi, we haven't tested the bot in the colab, so we are not too sure about either the bot is supported/not in colab. Would you willing to try it in the Terminal first?

**Comment by JasonLovesDoggo** [comment]
I'm sorry but Google colab is not a supported system You are welcome to try to fix it yourself but it's not in the range of anyone's duty to help you
