### ISSUE TITLE
I need some more help!

### ISSUE THREAD

**Issue by augis5654** [elebumm/RedditVideoMakerBot#921]
PS C:\Users\augus\OneDrive\This PC\RedditVideoMakerBot-master> & C:/Users/augus/AppData/Local/Microsoft/WindowsApps/python3.10.exe "c:/Users/augus/OneDrive/This PC/RedditVideoMakerBot-master/main.py"

Traceback (most recent call last):
  File "c:\Users\augus\OneDrive\This PC\RedditVideoMakerBot-master\main.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

I am quite new so i need some help with this, Thank you.

**Comment by Nipa-Code** [comment]
there's a file called `requirements.txt`, it has all requirements you will need to run the `main.py` file. To install those, run `python -m pip install -r requirements.txt`. Hope this helps.

**Comment by William9923** [comment]
if needed, you could also install the python-dotenv separately using `pip install python-dotenv`
