### ISSUE TITLE
Videos.json entry added when background download fails.

### ISSUE THREAD

**Issue by dasbts** [elebumm/RedditVideoMakerBot#923]
**Describe the bug**
If there is an error while downloading the backgrounds it seems to still add the thread to videos.json. 

The error that produced this for me was ConnectionResetError: [WinError 10054] but I believe any error would cause this. 

**To Reproduce**
Trying to download multiple backgrounds, the error that caused this issue was after waiting a very long time for one background to download, it successfully finally did so but the next one gave error "ConnectionResetError: [WinError 10054]" but I believe any error would cause this. 

When error occurs, check videos.json if the Reddit thread has been added. 

**Expected behavior**
videos.json to only add entry after succesful render. 

**System (please complete the following information):**

- Python Version: Python 3.9
- OS: Windows 10
- App version / Branch: latest develop

**Comment by JasonLovesDoggo** [comment]
Solution: find a more stable connection

**Comment by dasbts** [comment]
Hmmm first off I found that it does not happen with most other errors (this one was some library error since it threw in some Swedish language in there too). The connection is stable, maybe not enough apparently but it's 100/100 mbps fiber.

**Comment by JasonLovesDoggo** [comment]
> Hmmm first off I found that it does not happen with most other errors (this one was some library error since it threw in some Swedish language in there too). The connection is stable, maybe not enough apparently but it's 100/100 mbps fiber with ethernet cable connection. 

I mean that should be enough It's more about stability but I will change where save data is called

**Comment by JasonLovesDoggo** [comment]
fixed.
