### ISSUE TITLE
Threads without comments gives error rather than skipping it

### ISSUE THREAD

**Issue by dasbts** [elebumm/RedditVideoMakerBot#924]
**Describe the bug**
If a thread has no comments, but is still a hot topic, it throws an error and gets stuck in an infinite loop rather than adding it to videos.json or in other ways skipping the thread. For storymode this would ofc. be interesting to still render out, but not in the current state. The error I got which I haven't found anyone else write about is: 
```
Traceback (most recent call last):
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\main.py", line 61, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\main.py", line 50, in run_many
    main()
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\main.py", line 42, in main
    make_final_video(number_of_comments, length, reddit_object)
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\video_creation\final_video.py", line 48, in make_final_video
    for i in range(0, number_of_clips):
TypeError: 'NoneType' object cannot be interpreted as an integer
```

**To Reproduce**
Let the bot run in a subreddit that has threads where there are no comments and you will get the error described above. 

**Expected behavior**
For the bot to skip the thread in case if there is no comments, or for it to in the coming storymode just read the OP comment and then cut the video. 

Right now I have to add it to the videos.json manually with a placeholder ID, but if there is a different background it sometimes renders the thread again, so I might have to add a different ID for each background credit. 

EDIT: I searched the sourcecode and found that the variable "idx" which is the "reddit_id" variable, it uses the reddit_thread, so I understand now how when I asked this in Discord, it could not be possible, but that's another bug I guess, sometimes it renders it again with another background, I'm guessing the issue is that videos.json is scanned currently for unique entries rather than only unique ID's. 

**System (please complete the following information):**

- Python Version: Python 3.9
- OS: Windows 10
- App version / Branch: latest (thought it was develop but apparently my stupid GitHub cloned the "stable"...) 

Also I searched for this but couldn't find any issues with this specific error of 'NoneType' object cannot be interpreted as an integer. Hopefully it haven't been submitted before.

**Comment by dasbts** [comment]
As a quick solution temporarily I just add "if number_of_clips is not None:" as well as necessary indents before the for loop at row 48, and row 82 of final_video.py so it will add to videos.json anyway upon error, however it also renders it out, but it works for now if anyone wants to run something continuously until future solutions exist.

**Comment by dasbts** [comment]
So changing into TTSCHOICE="GoogleTranslate" gives another error: 
```
Traceback (most recent call last):
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\main.py", line 61, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\main.py", line 50, in run_many
    main()
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\main.py", line 38, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\video_creation\voices.py", line 49, in save_text_to_mp3
    return text_to_mp3.run()
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\TTS\engine_wrapper.py", line 65, in run
    self.call_tts(f"{idx}", comment["comment_body"])
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\TTS\engine_wrapper.py", line 93, in call_tts
    self.tts_module.run(text=process_text(text), filepath=f"{self.path}/{filename}.mp3")
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\TTS\GTTS.py", line 15, in run
    tts = gTTS(text=text, lang=os.getenv("POSTLANG") or "en", slow=False)
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\venv\lib\site-packages\gtts\tts.py", line 134, in __init__
    assert text, "No text to speak"
AssertionError: No text to speak
```

**Comment by dasbts** [comment]
Ok so since I managed to work in the stable version previously due to Github clone being bad I now have the develop version, and it's not the same row numbers. 

So, what I changed is row 73:
```
    if number_of_clips is not None:
        audio_clips = [AudioFileClip(f"assets/temp/mp3/{i}.mp3") for i in range(number_of_clips)]
    else:
        audio_clips = []
```
Then row 93 (after the previous change): 
```
    if number_of_clips is not None:
        for i in range(0, number_of_clips):
            image_clips.append(
                ImageClip(f"assets/temp/png/comment_{i}.png")
                .set_duration(audio_clips[i + 1].duration)
                .resize(width=W - 100)
                .set_opacity(new_opacity)
            )

``` 
However, this also involves solving another bug. I had to comment out row 76 and 77 in subreddit.py as when I had already rendered all the topics on the hot or top page of the first refresh of the website, even tho there are more threads to check, it doesn't find these as an issue with selenium (which I was told playwright works kind of the same) is if there is no more elements in a dynamically loading website (which this is the case of as you scroll to bottom to fetch more) it just stops if you don't tell it to scroll to the bottom. 

After doing this it works fine again, but now I'm getting the ffmpeg error once again which is my next mission. However, if someone finds energy to look into trying to get playwright to scroll to the bottom if there are no more threads, please do.

**Comment by JasonLovesDoggo** [comment]
Will fix

Great issue by the way clear description and accurate issue

**Comment by tonywiththetommy** [comment]
![image](https://user-images.githubusercontent.com/95452531/178189888-d749e32d-132f-48ed-af3a-6a53a6e38b57.png)
easy fix

**Comment by tonywiththetommy** [comment]
can make a variable for rejecting posts without minimum amount of comments set by user

![image](https://user-images.githubusercontent.com/95452531/178245879-66904bff-2b93-4e61-a494-55f7c83bdae6.png)
![image](https://user-images.githubusercontent.com/95452531/178245976-821367b1-6851-4044-b0fc-c1426cf8e100.png)

**Comment by JasonLovesDoggo** [comment]
done.

> can make a variable for rejecting posts without minimum amount of comments set by user
> 
> ![image](https://user-images.githubusercontent.com/95452531/178245879-66904bff-2b93-4e61-a494-55f7c83bdae6.png) ![image](https://user-images.githubusercontent.com/95452531/178245976-821367b1-6851-4044-b0fc-c1426cf8e100.png)

**Comment by dasbts** [comment]
Awesome, thank you! But shouldn’t it be ”<=” rather than ”<” on row 37?

Från: ***@***.***>
Skickat: den 12 juli 2022 02:27
Till: ***@***.***>
Kopia: ***@***.***>; ***@***.***>
Ämne: Re: [elebumm/RedditVideoMakerBot] Threads without comments gives error rather than skipping it (Issue #924)


done.

can make a variable for rejecting posts without minimum amount of comments set by user

[image]<https://user-images.githubusercontent.com/95452531/178245879-66904bff-2b93-4e61-a494-55f7c83bdae6.png>[image]<https://user-images.githubusercontent.com/95452531/178245976-821367b1-6851-4044-b0fc-c1426cf8e100.png>

**Comment by JasonLovesDoggo** [comment]
well actually yeah.
