### ISSUE TITLE
Doesn't accept my reddit username

### ISSUE THREAD

**Issue by Mikorin-13** [elebumm/RedditVideoMakerBot#928]
**Describe the bug**
when i enter my reddit username, it asks me to enter it again (i.e: wrong username) instead of proceeding to the next input.
i tried entering my username/display name/username preceded by a "u/"
**To Reproduce**
Enter all of the information needed until you reach username
**Expected behavior**
code asks me to enter the next input in the list

**System (please complete the following information):**

- Python Version: 3.10.5
- OS: Windows 10
- App version / Branch: latest

**Additional context**

**Comment by JasonLovesDoggo** [comment]
You are not supposed to add u/ in front

**Comment by JasonLovesDoggo** [comment]
Sorry I misread that.
Could you tell me your Reddit username by any chance

**Comment by Mikorin-13** [comment]
> Sorry I misread that.
> Could you tell me your Reddit username by any chance

thanks for the fast reply, it worked now, i think the problem was in my account cuz when i used another one it worked

**Comment by JasonLovesDoggo** [comment]
> > Sorry I misread that.
> > Could you tell me your Reddit username by any chance
> 
> thanks for the fast reply, it worked now, i think the problem was in my account cuz when i used another one it worked

Could you still just tell me your Reddit username for me to test
