### ISSUE TITLE
I can only use Google Translator

### ISSUE THREAD

**Issue by AsiTomas** [elebumm/RedditVideoMakerBot#929]
I have a problem, I can only use Google as voice. Nothing else works.
TikTok error: raise HeaderNotFoundError("can't sync to MPEG frame")
mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame
StreamlabsPolly error: raise MutagenError(e)
mutagen.MutagenError: [Errno 2] No such file or directory: 'assets/temp/mp3/title.mp3'
ASWPolly error: raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (polly) could not be found

Can somebody help me please :). Thanks

**Comment by JasonLovesDoggo** [comment]
What version

**Comment by Rlag1998** [comment]
I'm having the same issue, version 2.2.2.

**Comment by Rlag1998** [comment]
Ah, the .env values just have to be set properly, using examples from the TTS folder.

**Comment by William9923** [comment]
> Ah, the .env values just have to be set properly, using examples from the TTS folder.

Hi, @AsiTomas please try this solution. Make sure the configuration is filled correctly. I will close this issue, but feel free to open it in case it didn't work

ps: Also use our most current version (v.2.2.2 or develop)

**Comment by AdmiralAtomic** [comment]
> > Ah, the .env values just have to be set properly, using examples from the TTS folder.
> 
> Hi, @AsiTomas please try this solution. Make sure the configuration is filled correctly. I will close this issue, but feel free to open it in case it didn't work
> 
> ps: Also use our most current version (v.2.2.2 or develop)

Thats not the issue in this case. This means that the AWS Polly isnt installed on the system which you can fing out how to do here: 
Linux: https://docs.aws.amazon.com/polly/latest/dg/setup-aws-cli.html
Windows: https://docs.aws.amazon.com/polly/latest/dg/install-voice-plugin2.html

The error that appearrs AFTER this though may be a .env error cause im stuck at that bit but idk what im doing wrong.
![image](https://user-images.githubusercontent.com/75228915/178143465-b1be3f5a-f9e7-4e3b-958a-378ca57978f4.png)
