### ISSUE TITLE
How to install ffmpeg

### ISSUE THREAD

**Issue by Shadowles19** [elebumm/RedditVideoMakerBot#93]
<img width="906" alt="Screen Shot 2022-06-01 at 10 21 40 AM" src="https://user-images.githubusercontent.com/106671929/171471541-a465be67-b1a4-4ecd-a964-1fb9f62b7007.png">

-------------------
I tried doing 'pip install ffmpeg-python' but it still didn't work

**Comment by mrpekr** [comment]
from [requirements.txt](https://github.com/elebumm/RedditVideoMakerBot/blob/master/requirements.txt) you can see that its imageio-ffmpeg so the command  is `pip install imageio-ffmpeg`

**Comment by FreebieII** [comment]
Hi @Shadowles19 

I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
