### ISSUE TITLE
Add Comment or Better Error Message When Playwright having issue

### ISSUE THREAD

**Issue by sparkyrider** [elebumm/RedditVideoMakerBot#931]
**Describe the bug**
If the post ID provided in the .env file contains over the maximum number of characters allowed,  it will throw a timeout error. 

**To Reproduce**
Set the Post ID to a post that has a long top comment. (over the character limit), then run the script. It will fail with this error
`playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
`
**Expected behavior**
Should either move on to a different comment or throw a proper error. 

- Python Version: 3.10.5
- OS: M1 OSX
- App version / Branch [master]

**Comment by William9923** [comment]
Hi, i don't think this is a bug related to Character limit.
Instead, it might be caused due to playwright unable to access reddit during the timeout duration (30s)

I would suggest you try to make sure reddit is accessible in that duration.

**Comment by William9923** [comment]
But i believe you have a good suggestion. A lot of playwright errors are hard to intepreted by user, thus confusing them. Catching those issue and showing simplified error might be useful for lot of user.
