### ISSUE TITLE
Add docs on how to implement AWSPolly

### ISSUE THREAD

**Issue by AdmiralAtomic** [elebumm/RedditVideoMakerBot#934]
**Is your feature request related to a problem? Please describe.**
Feature is related to the errors that display when attempting to run AWSPolly. I understand that this is due to not having AWS credentials, but i have 0 idea how to apply AWS credentials to the script.

**Describe the solution you'd like**
I just want a set of instructions included in the readme that explain how this works and how to add AWSPolly credentials.
**Describe alternatives you've considered** (optional)

**Additional context** (optional)
Image of the error i previously mentioned when attempting to run AWSPolly without the proper setup.
![image](https://user-images.githubusercontent.com/75228915/178126015-1980119c-8deb-4217-b7f7-427c954aa053.png)

**Comment by William9923** [comment]
I think this is a good idea, adding more sophisticated documentation related to AWS Polly might be useful. Will label as a good first issue

**Comment by JasonLovesDoggo** [comment]
Install the cli and login

Improved the EH in the code in 2.3
