### ISSUE TITLE
Failing at the End of The Process

### ISSUE THREAD

**Issue by Endrecho** [elebumm/RedditVideoMakerBot#935]
I keep getting: OSError: MoviePy error: failed to read the first frame of video file assets/temp/background.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.

This error is caused by the GoogleTranslate option. Any help would be appreciated and any stuff needed to help can be given.

**Comment by William9923** [comment]
Related #896 (i think this is a duplicate). Will close this issue, feel free to open if next release not fix your problem 🙏 (v2.3 wait for it :D)
