### ISSUE TITLE
Video bugging out at the end

### ISSUE THREAD

**Issue by Britanniann** [elebumm/RedditVideoMakerBot#936]
The video gets added around 3 additional seconds of frozen background footage without any voicover nor comment displayed

Run the script and look at the temp video file

- Python Version: Python 3.10
- OS: Windows 10
- Master branch

**Comment by CJthisis** [comment]
> The video gets added around 3 additional seconds of frozen background footage without any voicover nor comment displayed
> 
> 
> 
> Steps to reproduce the behavior:
> 
> Run the script and look at the temp video file
> 
> 
> 
> - Python Version: Python 3.10
> 
> - OS: Windows 10
> 
> - Master branch

Happens to me as well! But I'm on the newest dev branch.

**Comment by tonywiththetommy** [comment]
get the same issue occasionally on develop

**Comment by William9923** [comment]
Duplicate #869

**Comment by tonywiththetommy** [comment]
> Duplicate #869

this isnt a duplicate issue, it should be reopened. watch [my video example](https://www.youtube.com/watch?v=Wb3pkdWjB-4) 1:56
