### ISSUE TITLE
Can only use Google Translate

### ISSUE THREAD

**Issue by SkyfireGaming** [elebumm/RedditVideoMakerBot#941]
I can only use the Google Translate TTS option. If I try to run a different TTS it crashes.

My ENV file:
REDDIT_2FA="no"
OPACITY=1.0
REDDIT_PASSWORD="*********"
POST_ID=""
TIKTOK_VOICE="en_uk_001"
REDDIT_CLIENT_ID="yDXa022GnDc8tc3VqN2Nsg"
ALLOW_NSFW="True"
TIMES_TO_RUN=""
TTSCHOICE="tiktok"
POSTLANG=""
REDDIT_CLIENT_SECRET="88nWW0xsvaIIKUzKrI1OG4wbe0YOJA"
SUBREDDIT="askreddit"
AWS_VOICE="Brian"
THEME="dark"
REDDIT_USERNAME="CaptainSkyfire"
STREAMLABS_VOICE="Brian"
MAX_COMMENT_LENGTH=500

My ENV Template file:

REDDIT_CLIENT_ID=""
#EXPLANATION the ID of your Reddit app of SCRIPT type
#RANGE 12:30
#MATCH_REGEX [-a-zA-Z0-9._~+/]+=*$
#OOB_ERROR The ID should be over 12 and under 30 characters, double check your input.

REDDIT_CLIENT_SECRET="88nWW0xsvaIIKUzKrI1OG4wbe0YOJA"
#EXPLANATION the SECRET of your Reddit app of SCRIPT type
#RANGE 20:40
#MATCH_REGEX [-a-zA-Z0-9._~+/]+=*$
#OOB_ERROR The secret should be over 20 and under 40 characters, double check your input.

REDDIT_USERNAME="CaptainSkyfire" #asdfghjkl
#EXPLANATION the username of your reddit account
#RANGE 3:20
#MATCH_REGEX [_0-9a-zA-Z]+$
#OOB_ERROR A username HAS to be between 3 and 20 characters

REDDIT_PASSWORD="*************" #fFAGRNJru1FTz70BzhT3Zg
#EXPLANATION the password of your reddit account
#RANGE 8:None
#OOB_ERROR Password too short

#OPTIONAL
RANDOM_THREAD="yes"
# If set to no, it will ask you a thread link to extract the thread, if yes it will randomize it. Default: "no"

REDDIT_2FA="" #no
#MATCH_REGEX ^(yes|no)
#EXPLANATION Whether you have Reddit 2FA enabled, Valid options are "yes" and "no"

SUBREDDIT="askreddit"
#EXPLANATION what subreddit to pull posts from, the name of the sub, not the URL
#RANGE 3:20
#MATCH_REGEX [_0-9a-zA-Z]+$
#OOB_ERROR A subreddit name HAS to be between 3 and 20 characters

ALLOW_NSFW="True"
#EXPLANATION Whether to allow NSFW content, True or False
#MATCH_REGEX ^(True|False)$

POST_ID=""
#MATCH_REGEX ^((?!://|://).)*$
#EXPLANATION Used if you want to use a specific post. example of one is urdtfx

THEME="DARK" #dark
#EXPLANATION sets the Reddit theme, either LIGHT or DARK
#MATCH_REGEX ^(dark|light|DARK|LIGHT)$

TIMES_TO_RUN="" #2
#EXPLANATION used if you want to run multiple times. set to an int e.g. 4 or 29 and leave blank for 1

MAX_COMMENT_LENGTH="500" #500
#EXPLANATION max number of characters a comment can have. default is 500
#RANGE 0:10000
#MATCH_TYPE int
#OOB_ERROR the max comment length should be between 0 and 10000

OPACITY="1" #.8
#EXPLANATION Sets the opacity of the comments when overlayed over the background
#RANGE 0:1
#MATCH_TYPE float
#OOB_ERROR The opacity HAS to be between 0 and 1

# If you want to translate the comments to another language, set the language code here.
# If empty, no translation will be done.
POSTLANG=""
#EXPLANATION Activates the translation feature, set the language code for translate or leave blank

TTSCHOICE="tiktok"
#EXPLANATION the backend used for TTS. Without anything specified, the user will be prompted to choose one.
# IMPORTANT NOTE: if you use translate, you need to set this to googletranslate or tiktok and use custom voice in your language

STREAMLABS_VOICE="Brian"
#EXPLANATION Sets the voice for the Streamlabs Polly TTS Engine. Check the file for more information on different voices.

AWS_VOICE="Brian"
#EXPLANATION Sets the voice for the AWS Polly TTS Engine. Check the file for more information on different voices.

TIKTOK_VOICE="en_uk_001"
#EXPLANATION Sets the voice for the TikTok TTS Engine. Check the file for more information on different voices.

#OPTIONAL
STORYMODE="False"
# IN-PROGRESS - not yet implemented

_____

When running the bot with these settings, this is what shows right before crashing
![2022-07-10 13-21-49 00_00_16_49 Still001](https://user-images.githubusercontent.com/79760036/178155522-3cd551cf-8e1a-4429-8385-c26ae0c9dae3.png)

**Comment by JasonLovesDoggo** [comment]
Yeah I'm not going to read all of that Just use develop branch

**Comment by SkyfireGaming** [comment]
I don't know what that means

**Comment by JasonLovesDoggo** [comment]
> I don't know what that means

Download the develop branch and use that
