### ISSUE TITLE
Add custom resolution for background

### ISSUE THREAD

**Issue by HyptexPvP** [elebumm/RedditVideoMakerBot#943]
**Is your feature request related to a problem? Please describe.**
Make the background much bigger so we can see the video in fullscreen if not uploaded on tiktok.

**Describe the solution you'd like**
Allow the user to change the resolution / how big the video is.

**Comment by thefinaloneg** [comment]
I've been attempting to work on this, and I'm almost done. The one issue I'm having is I'm not sure why I can't access the settings.config properly. 
`[settings.background]
background_choice = "minecraft"
width = 1080
height = 1920`
I've modified the template file to also ask for the width and height, which is now stored under settings.background. However, when I try to access it in final_video.py like this:
`W, H = settings.config["settings"]["background"]["width"], settings.config["settings"]["background"]["height"]`
I get 

  File "/Users/final/Desktop/RedditVideoMakerBot/video_creation/final_video.py", line 22, in <module>
    W, H = settings.config["settings"]["background"]["width"], settings.config["settings"]["background"]["height"]
TypeError: There are no type variables left in dict['settings']

**Comment by JasonLovesDoggo** [comment]
> I've been attempting to work on this, and I'm almost done. The one issue I'm having is I'm not sure why I can't access the settings.config properly. 
> 
> [settings.background]
> background_choice = "minecraft"
> width = 1080
> height = 1920
> 
> I've modified the template file to also ask for the width and height, which is now stored under settings.background in the config.toml file properly. However, when I try to access it in final_video.py like this:
> `W, H = settings.config["settings"]["background"]["width"], settings.config["settings"]["background"]["height"]`
> I get 
> 
>   File "/Users/final/Desktop/RedditVideoMakerBot/video_creation/final_video.py", line 22, in <module>
>     W, H = settings.config["settings"]["background"]["width"], settings.config["settings"]["background"]["height"]
> TypeError: There are no type variables left in dict['settings']
> 

Add it to the template file

**Comment by Supreme-hub** [comment]
Hey, when are you calling the config? You must do it inside a function. The reason for this is because settings.py needs to run before you can access them.
