### ISSUE TITLE
tts occasionally cuts off first line of comment

### ISSUE THREAD

**Issue by tonywiththetommy** [elebumm/RedditVideoMakerBot#946]
**Describe the bug**
tts occasionally cuts off first line of commend, seems to be when a comments third line included edit:

**To Reproduce**
multi line comments

**Expected behavior**
read all comment lines, dont skip the first lines

**Screenshots**
[vid](https://youtube.com/shorts/cjJRsv_CZTA)

**System (please complete the following information):**

i am running this on my develop branch but it has happened to me on main as well, I can run an unedited branch for a while to export plenty of videos and provide examples of the bugs in the normal branches 

**Additional context**

**Comment by JasonLovesDoggo** [comment]
Fixed In 2.3
