### ISSUE TITLE
not downloading / starting process

### ISSUE THREAD

**Issue by Minty569** [elebumm/RedditVideoMakerBot#949]
when I run python main.py it runs code but never gives any errors or the vide
![Capture1](https://user-images.githubusercontent.com/106637473/178247127-3c855b7f-d2e1-4768-95aa-539a93571b39.PNG)
![Capture2](https://user-images.githubusercontent.com/106637473/178247133-d4ac6a71-9232-4da0-84a7-345e15bc25f6.PNG)
o

**Comment by PersonHalf** [comment]
> have you setup your reddit api app

diff account but yes the reddit API was done

**Comment by William9923** [comment]
I think this happen due to invalid credential. Please double check your credential (username, password, reddit_client_secret, etc). Feel free to open it again if issue persist
