### ISSUE TITLE
ffmpeg exe obviously not supported on Mac

### ISSUE THREAD

**Issue by totalsoda** [elebumm/RedditVideoMakerBot#95]
Tried installing MacPorts and a ffmpeg wrapper for python however still currently trying to work it out.

**Comment by Shadowles19** [comment]
Having the same issue, if you figure it out please let me know

**Comment by Shadowles19** [comment]
Watch this video it helped me and worked: https://www.youtube.com/watch?v=H1o6MWnmwpY&ab_channel=RickMakes

**Comment by totalsoda** [comment]
That worked for me as well thank you. Still have some issues but that fixed the FFmpeg issue.
