### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SCR4PEE** [elebumm/RedditVideoMakerBot#952]
The tool crashes after selecting a language other than Translator. On the other hand, after selecting the translator, the program downloads screenshots and sounds, but it does not download the background, and it seems to me that it crashes. 2 thing or actually the question of how to get a Post ID on reddit?

**Comment by William9923** [comment]
Hi,
1. Would be great if you provide us the error logs.
2. It need a long time to download the background (it depends on your internet connection)
3. https://www.reddit.com/r/oddlyterrifying/comments/vwf76p/damn/ -> POST_ID = vwf76p
Thanks 🙏
