### ISSUE TITLE
can't sync to MPEG frame

### ISSUE THREAD

**Issue by Cmarino25** [elebumm/RedditVideoMakerBot#953]
**Describe the bug**
Code stops and spits error:

raise HeaderNotFoundError("can't sync to MPEG frame")
mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame

**To Reproduce**
run program via "python main.py"

**Expected behavior**
Program to run

**Screenshots**
![image](https://user-images.githubusercontent.com/90123136/178262628-a7e1ad52-bba6-4f04-8c14-ec999f5148c4.png)

**System (please complete the following information):**

- Python Version: Python 3.10.5
- OS: Win 10
- App version: Latest

**Additional context**

**Comment by Cmarino25** [comment]
Seems to work fine with the Google Translate TTS Voice

**Comment by tonywiththetommy** [comment]
you using tiktok tts to get this error?

**Comment by Cmarino25** [comment]
> you using tiktok tts to get this error?



> you using tiktok tts to get this error?

Yeah Using TikTok TTS gests this error googletranslate works fine but i havent tried anyothers

**Comment by JasonLovesDoggo** [comment]
Fixed in 2.3
