### ISSUE TITLE
can't sync to MPEG frame

### ISSUE THREAD

**Issue by lamasterso** [elebumm/RedditVideoMakerBot#954]
raise HeaderNotFoundError("can't sync to MPEG frame")
mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame

**Comment by VSPuzzler** [comment]
> upload complete error log, also, what tts you using? cos if you're using tiktok tts you could change the max chars from 300 to 270 and i no longer get cant sync to mpeg frame

How do I change it? Which file does my responses get saved into because it only asked me once in the first time I used it.

**Comment by VSPuzzler** [comment]
> upload complete error log, also, what tts you using? cos if you're using tiktok tts you could change the max chars from 300 to 270 and i no longer get cant sync to mpeg frame

I tried 250 and I still get the error.

**Comment by William9923** [comment]
Duplicate #953
