### ISSUE TITLE
Make the bot read text based images 

### ISSUE THREAD

**Issue by Foxcer11** [elebumm/RedditVideoMakerBot#956]
Sometimes posts include pictures that include texts like https://www.reddit.com/r/oddlyterrifying/comments/vwf76p/damn/ for example 

Uses of this :

more options to choose, and makes the post simpler for the watcher to understand rather than having to read it himself.

It would be nice if the feature could also be toggled on or off 

More examples of some other posts  :

https://www.reddit.com/r/Damnthatsinteresting/comments/vwhiuh/18years_ago_200_women_lynched_a_serial_rapist_in/
https://www.reddit.com/r/GreenAndPleasant/comments/vwdnkh/getting_the_big_questions_right/
https://www.reddit.com/r/meirl/comments/vw03lb/meirl/

**Comment by William9923** [comment]
Hi, I think this idea is quite far from what the bot trying to achieve (to make reddit video). But, will keep this issue open for the future.

**Comment by StopmotionSimonYT** [comment]
This would be a whole new project, not something you can implement easily
