### ISSUE TITLE
need help cant get past the screenshoting with any tts

### ISSUE THREAD

**Issue by Gh0stSim0n** [elebumm/RedditVideoMakerBot#961]
Exception has occurred: TimeoutError
Timeout 30000ms exceeded.
=========================== logs ===========================
<launching> C:\Users\admin\AppData\Local\ms-playwright\chromium-1012\chrome-win\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=C:\Users\admin\AppData\Local\Temp\playwright_chromiumdev_profile-k4XT5T --remote-debugging-pipe --no-startup-window
<launched> pid=12000
============================================================
  File "C:\Users\admin\Desktop\reddit bot\RedditVideoMakerBot-master\video_creation\screenshot_downloader.py", line 35, in download_screenshots_of_reddit_posts
    browser = p.chromium.launch()
  File "C:\Users\admin\Desktop\reddit bot\RedditVideoMakerBot-master\main.py", line 38, in main
    download_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "C:\Users\admin\Desktop\reddit bot\RedditVideoMakerBot-master\main.py", line 49, in run_many
    main()
  File "C:\Users\admin\Desktop\reddit bot\RedditVideoMakerBot-master\main.py", line 59, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))

**Comment by JasonLovesDoggo** [comment]
full error is needed

**Comment by William9923** [comment]
@Gh0stSim0n , i think this issue happen because of your internet connection. Try using the bot in a faster network 🙏

**Comment by Gh0stSim0n** [comment]
> @Gh0stSim0n , i think this issue happen because of your internet connection. Try using the bot in a faster network 🙏

hey how much will it need approx? ig my home connection is around 2mbps does it need more?
