### ISSUE TITLE
AWSPolly Bug in .env file

### ISSUE THREAD

**Issue by amit397** [elebumm/RedditVideoMakerBot#962]
**Describe the bug**
I ran the bot a couple of times and ended up making a couple of videos and it worked out when I did every single time, however every single time I used TikTok TTS and it worked. I wanted to use the AWSPolly because when I heard it I thought it would be better for the videos however when I select that option in CMD the error that pops up is "File "C:\Users\amitz\AppData\Local\Programs\Python\Python39\lib\site-packages\botocore\session.py", line 404, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (polly) could not be found"

**To Reproduce**
run the code and pick AWSPolly with this env file:
TIMES_TO_RUN="1"
POSTLANG=""
REDDIT_CLIENT_SECRET="AM0XxhIKu3UTyHd0g0c7Q8XZwZfNkQ"
REDDIT_CLIENT_ID="VnKju6czR0YYfFifszw9Lw"
REDDIT_PASSWORD="Amit2004"
STREAMLABS_VOICE="Matthew"
OPACITY=1.0
SUBREDDIT="AskReddit"
AWS_VOICE="Joanna"
POST_ID=""
ALLOW_NSFW="True"
MAX_COMMENT_LENGTH=1000
REDDIT_2FA="no"
TTSCHOICE=""
TIKTOK_VOICE="en_us_006"
REDDIT_USERNAME="faagtfook"
THEME="DARK"

**Expected behavior**
The code should run and the video should be made normally but with the AWSPolly Voice 

**Screenshots**
![image](https://user-images.githubusercontent.com/60118573/178335619-d3f260d1-ee13-44c9-8e57-8f1c7dd8f337.png)

**System (please complete the following information):**

- Python Version: Python 3.9.5
- OS: Windows 10
- App version / Branch Latest

**Additional context**

**Comment by JasonLovesDoggo** [comment]
you need to install the CLI 
this is also a duplicate
