### ISSUE TITLE
NoneTye object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by AidenBedore212** [elebumm/RedditVideoMakerBot#965]
**Describe the bug**
When I try and run main.py, all goes well until creating the final video. Then I get an error. I've dug through the code but don't see
why getenv("TIMES_TO_RUN") would yield nonetype. Any help would be greatly appreciated.

**Screenshots**
![error1](https://user-images.githubusercontent.com/68352566/178346088-30fbf1c7-3ac9-4140-be5e-62eff79c8487.PNG)
![env file](https://user-images.githubusercontent.com/68352566/178346260-0ffa6072-d17a-45ed-8898-2b02dff0a1b4.PNG)

- Python Version: [e.g. Python 3.6]
- OS: [e.g. Windows 11]
- App version / Branch [e.g. latest, V2.0, master, develop ]

**Additional context**
I'm new to using the terminal this way. If I try and run a command like "python main.py" I get an error.
However, "py main.py" works. I don't know if that's helpful but it's very weird to me.

**Comment by JasonLovesDoggo** [comment]
fixed.
