### ISSUE TITLE
FFMPEG: Format mp3 detected only with low score of 1, misdetection possible!

### ISSUE THREAD

**Issue by CJthisis** [elebumm/RedditVideoMakerBot#966]
I have the DEV build of the 10th of July, and I have NO idea where this error came from, so no description.

Even if I restart powershell, this error still persists, and i cant get a video to render.

![grafik](https://user-images.githubusercontent.com/99442347/178357647-03636665-62c8-4f71-a50c-78c15dcc19fe.png)

This is my .config.template.toml file, i just had to rename it to upload it to GitHub.
[.config.txt](https://github.com/elebumm/RedditVideoMakerBot/files/9087566/default.config.txt)

**Comment by JasonLovesDoggo** [comment]
fixed.
