### ISSUE TITLE
Skip thread feature request

### ISSUE THREAD

**Issue by BradTFT** [elebumm/RedditVideoMakerBot#967]
when making the video, sometimes the thread the bot picks randomly just isnt that interesting. so i suggest adding a confirm/skip feature

kinda like this:
```
video will be: boring video title. confirm or skip? (C/S)
```
or something

simple quality of life solution. the way this could be done is: on skip input, rerun the function for finding the subreddit. easy enough (i think atleast)

lmk what you guys think tho

**Comment by tonywiththetommy** [comment]
good idea for a feature, i was thinking about this too, along with a 'choose which comments to reject' feature.

**Comment by JasonLovesDoggo** [comment]
If this would be implemented it would have to be a optional flag defined in config.toml not the default mode

**Comment by tonywiththetommy** [comment]
> If this would be implemented it would have to be a optional flag defined in config.toml not the default mode
yeah absolutely, there could be an option for automatic or manual mode, which could open the program up to a lot more customization, ie. choose manual background video start time, background audio start time etc etc.

**Comment by BradTFT** [comment]
cool so you guys like it?

**Comment by JasonLovesDoggo** [comment]
yeah it's fine I just need to do some stuff first

> cool so you guys like it?

**Comment by BradTFT** [comment]
sweet. should i start a pull request?

**Comment by JasonLovesDoggo** [comment]
> sweet. should i start a pull request?

No promises it will be merged though but yeah
