### ISSUE TITLE
Create an option for the script to run a number of times automatically.

### ISSUE THREAD

**Issue by Denotess** [elebumm/RedditVideoMakerBot#97]
You would add an input which would make the script loop as many times as you want and make as many videos as you want.

**Comment by Goodgamer78** [comment]
`@echo off
:x
python3 main.py
goto x`
Put this into a .bat file, and it will run infinitely until you close the command prompt. The videos would get overwritten, though. Very basic but it runs.

**Comment by CallumIO** [comment]
Closing as stale. Reopen if needed.
