### ISSUE TITLE
make the bot read a specifc comment thread

### ISSUE THREAD

**Issue by Foxcer11** [elebumm/RedditVideoMakerBot#970]
like post Id but for comments

benefits of this enhacment

comments are a very important part of a post, sometimes it could be even more important than the op depending on the post.

if the user could control the comments that appear In the video than the video would become more interesting 

an example of a comment thread I would have used if this feature is available 
https://www.reddit.com/r/TooAfraidToAsk/comments/vx2s2k/what_does_gaslighting_mean/iftjnbb?utm_medium=android_app&utm_source=share&context=3

**Comment by JasonLovesDoggo** [comment]
It shall be done How is the question though
The problem is on the user side of things not bot side
