### ISSUE TITLE
virus error moviepy

### ISSUE THREAD

**Issue by Stipe-x** [elebumm/RedditVideoMakerBot#972]
When running the command "pip install -r requirements.txt" the cmd and the terminal state the following

Collecting moviepy==1.0.3
  Using cached moviepy-1.0.3.tar.gz (388 kB)
  ERROR: Error [WinError 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software while executing command python setup.py egg_info
  Preparing metadata (setup.py) ... error
ERROR: Could not install packages due to an OSError: [WinError 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software

I tried turning off the antivirus but it doesnt help

![Snimka zaslona (29)](https://user-images.githubusercontent.com/79104957/178497800-836bd22e-f082-4f16-8049-47d51ed63066.png)

System (please complete the following information):

Python Version: Python 3.9
OS: Windows 11
App version / Branch: Latest

**Comment by JasonLovesDoggo** [comment]
ngl sounds like a you problem 🤣
