### ISSUE TITLE
the ability for it to read out OP's post

### ISSUE THREAD

**Issue by ibby55** [elebumm/RedditVideoMakerBot#975]
It would be handy if the bot had the ability to read just the OP's post, as right now, for me, it's making videos of r/nosleep and just reading the commments. not exactly helpful for stories.

**Comment by bobcat4848** [comment]
I believe this is being worked on, alongside a "storymode" which will read the title and the post itself, minus the comments

**Comment by JasonLovesDoggo** [comment]
Exactly what Bob said
