### ISSUE TITLE
Final background video length is not right

### ISSUE THREAD

**Issue by TheodorePappas** [elebumm/RedditVideoMakerBot#977]
**Describe the bug**
When the final video is created around 4 seconds before it ends (this is when the voiceover and the screenshots have finished) the background video freezes and a still image of it is shown (for those remaining 4 seconds).

**Expected behavior**
Obviously the final video has to end when the voiceover and screenshots (the selected reddit thread in general) have finished and not continue further.

**Additional context**
Other users have experienced the same problem with the latest version (2.3).

**Comment by William9923** [comment]
Hi, i think this is a duplicate issue from #869

**Comment by joshgreenwood2003** [comment]
> Hi, i think this is a duplicate issue from #869

this is not a duplicate, this is different behaviour to #869

**Comment by DadiBit** [comment]
I believe the issue is related to the fact that the code use a hardcoded constant video framerate (30), while the video uses a variable one. I use a custom background of 1.5h of me doing Minecraft parkour, so I'm not sure about the YouTube video.
If you use MediaInfo you can see:
```
$ mediainfo --Output=$'Video;Video: %Duration% ms\\n\nAudio;Audio: %Duration% ms' temp.mp4
Video: 54700 ms
Audio: 52244 ms
```
