### ISSUE TITLE
Make flexibility to add new videos

### ISSUE THREAD

**Issue by imdelette** [elebumm/RedditVideoMakerBot#986]
**Is your feature request related to a problem? Please describe.**
background_options in `video_creation/background.py` isn't flexible to add new background videos. 

**Describe the solution you'd like.**
Move background_options to a JSON file. It is also worth allowing the user to add/remove a new/an existing file in directory or a new/an existing object in the JSON file (e. g. add a comment what user should run or add a custom commands in the project).
Minor suggestion:
Make a script that can take a name of the video owner from html page and add it in options.

**Comment by JasonLovesDoggo** [comment]
I have already moved the config to a different file in feat/watermark But I readd The option to simply drag and drop

**Comment by JasonLovesDoggo** [comment]
See #1158
