### ISSUE TITLE
Temporary png and mp4 files aren't removed

### ISSUE THREAD

**Issue by imdelette** [elebumm/RedditVideoMakerBot#987]
**Describe the bug**
Temporary png and mp4 files aren't cleared, only mp3 files from the `assets/temp/mp3` folder

**To Reproduce**
Run a program and check the `assets/temp` folder after program completion

**Expected behavior**
Removed all temporary files from the `assets/temp` folder

**System (please complete the following information):**

- Python Version: 3.10.5
- OS: Arch Linux
- App version / Branch: V2.3, develop

After program completion:
![image](https://user-images.githubusercontent.com/52404270/178930076-dc46a835-6ba7-41d9-bc74-a8591e9013f9.png)

**Comment by JasonLovesDoggo** [comment]
This doesn't affect the output of the program in the slightest.
Either way it's fixed in the third branch
